---
author: Tom Slee
categories:
- blog archive
date: 2006-11-24 21:20:32
title: "Bureaucracy: it ain't just the government"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

A glimpse inside the world of that old efficient, lean and mean, innovative private industry, Microsoft style, from someone who spent a year working on the shutdown menu.




The scary thing about the story is that you can imagine how it happens, one step at a time, with a good reason for each step. This is not a "what's wrong with Microsoft" story, this is a "what happens in big organizations" story. Read and weep.




Link: [moblog: The Windows Shutdown crapfest](http://www.drizzle.com/~lettvin/2006/11/windows-shutdown-crapfest.html).


<blockquote>So just on my team, these are the people who came to every single planning meeting about this feature [the shutdown menu]:
> 
> 

> 
> * 1 program manager
> 

> * 1 developer
> 

> * 1 developer lead
> 

> * 2 testers
> 

> * 1 test lead
> 

> * 1 UI designer
> 

> * 1 user experience expert
> 

> * --
> 

> * 8 people total
>   
These planning meetings happened every week, for the entire year I worked on Windows.  
In addition to the above, we had dependencies on the shell team (the guys who wrote, designed and tested the rest of the Start menu), and on the kernel team (who promised to deliver functionality to make our shutdown UI as clean and simple as we wanted it). The relevant part of the shell team was about the same size as our team, as was the relevant part of kernel team.  
So that nets us a conservative estimate of 24 people involved in this feature. Also each team of 8 was separated by 6 layers of management from the leads, so let's add them in too, giving us 24 (6 * 3) - 1 (the shared manager) 41 total people with a voice in this feature. Twenty-four of them were connected sorta closely to the code, and of those twenty four there were exactly zero with final say in how the feature worked. Somewhere in those other 17 was somebody who did have final say but who that was I have no idea since when I left the team -- after a year -- there was still no decision about exactly how this feature would work.

> 
> By the way "feature" is much too strong a word; a better description would be "menu". Really. By the time I left the team the total code that I'd written for this "feature" was a couple hundred lines, tops.
> 
> </blockquote>

**Update.** The original post was down for a while, leading to a flurry of readers coming here instead, but is now [back up](http://www.drizzle.com/~lettvin/2006/11/windows-shutdown-crapfest.html). Any Joel readers who end up here anyway may want to read what I have to say about the question of [choice in software](http://whimsley.typepad.com/whimsley/2006/08/software_featur.html). Or not, of course.


		
