---
author: Tom Slee
categories:
- blog archive
date: 2015-04-05 05:08:22
tags:
- airbnb
title: What's going on with Airbnb in LA?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Today's LA Times says "[Airbnb cuts ties with vacation-rental firms in Los Angeles](http://www.latimes.com/business/la-fi-airbnb-rift-20150404-story.html)". The story says that "Two of the home-sharing giant's largest Los Angeles-area hosts—vacation-rental firms with dozens of apartments apiece—said Friday that Airbnb had dropped them from its site this week, canceling upcoming bookings and scrubbing their listings."

An Airbnb rep called one of the affected landlords (AE Hospitality) and "mentioned the growth plans of Airbnb conflicts with us listing on their website… No explicit reason was given."

I got a call from Tim Logan, one of the reporters on the story, asking if I could see anything going on, and was able to take a quick look and (at that time) it looked like 10 of the top 13 hosts (in terms of number of listings) were completely removed from the site, and I'm quoted in the story with that figure. Now I've been able to take a more complete look and can say a bit more.

There are two questions, of course. One is "What is happening?" What listings are being removed, whose are they, and what can we tell about those listings? The second question is "Why?" Let's start with the "What?"

I ran a survey of Los Angeles in October 2014, and another over the last couple of days. Here are the main findings.

There is always a lot of flux in Airbnb listings, and much of that comes from people who give the service a try and then decide it's not for them. But in Los Angeles there is something else. Here is a table showing the top   hosts (by number of listings) from October 2014, and the number of listings they now have on the site.
<table rules="groups" cellspacing="0" frame="hsides" border="2" cellpadding="6" >Table 1: The top hosts (by number of listings) in October 2014, and the number of listings they had then (2nd column) and have now (3rd) on Airbnb. The link goes to the host page (if it exists) or is redirected to a generic Airbnb page if the host has been removed. 

<tr >
**Host ID**
**October 2014**
**April 2015**
Reviews
Average Rating
</tr>

<tbody >
<tr >

<td class="left" >[3965199](http://airbnb.com/users/show/3965199)
</td>

<td class="right" >74
</td>

<td class="right" >0
</td>

<td class="right" >15
</td>

<td class="right" >4.50
</td>
</tr>
<tr >

<td class="left" >[1463129](http://airbnb.com/users/show/1463129)
</td>

<td class="right" >73
</td>

<td class="right" >0
</td>

<td class="right" >397
</td>

<td class="right" >4.47
</td>
</tr>
<tr >

<td class="left" >[558295](http://airbnb.com/users/show/558295)
</td>

<td class="right" >50
</td>

<td class="right" >0
</td>

<td class="right" >113
</td>

<td class="right" >4.54
</td>
</tr>
<tr >

<td class="left" >[293855](http://airbnb.com/users/show/293855)
</td>

<td class="right" >30
</td>

<td class="right" >0
</td>

<td class="right" >296
</td>

<td class="right" >4.26
</td>
</tr>
<tr >

<td class="left" >[7954](http://airbnb.com/users/show/7954)
</td>

<td class="right" >26
</td>

<td class="right" >0
</td>

<td class="right" >47
</td>

<td class="right" >4.60
</td>
</tr>
<tr >

<td class="left" >[295792](http://airbnb.com/users/show/295792)
</td>

<td class="right" >23
</td>

<td class="right" >0
</td>

<td class="right" >143
</td>

<td class="right" >4.68
</td>
</tr>
<tr >

<td class="left" >[3281907](http://airbnb.com/users/show/3281907)
</td>

<td class="right" >23
</td>

<td class="right" >0
</td>

<td class="right" >25
</td>

<td class="right" >4.50
</td>
</tr>
<tr >

<td class="left" >[66892](http://airbnb.com/users/show/66892)
</td>

<td class="right" >22
</td>

<td class="right" >0
</td>

<td class="right" >65
</td>

<td class="right" >4.68
</td>
</tr>
<tr >

<td class="left" >[2917744](http://airbnb.com/users/show/2917744)
</td>

<td class="right" >22
</td>

<td class="right" >1
</td>

<td class="right" >291
</td>

<td class="right" >4.85
</td>
</tr>
<tr >

<td class="left" >[4925293](http://airbnb.com/users/show/4925293)
</td>

<td class="right" >20
</td>

<td class="right" >0
</td>

<td class="right" >27
</td>

<td class="right" >4.85
</td>
</tr>
<tr >

<td class="left" >[9088345](http://airbnb.com/users/show/9088345)
</td>

<td class="right" >20
</td>

<td class="right" >0
</td>

<td class="right" >120
</td>

<td class="right" >4.41
</td>
</tr>
<tr >

<td class="left" >[465624](http://airbnb.com/users/show/465624)
</td>

<td class="right" >18
</td>

<td class="right" >18
</td>

<td class="right" >789
</td>

<td class="right" >4.44
</td>
</tr>
<tr >

<td class="left" >[8608492](http://airbnb.com/users/show/8608492)
</td>

<td class="right" >18
</td>

<td class="right" >0
</td>

<td class="right" >39
</td>

<td class="right" >4.42
</td>
</tr>
<tr >

<td class="left" >[3392276](http://airbnb.com/users/show/3392276)
</td>

<td class="right" >16
</td>

<td class="right" >18
</td>

<td class="right" >43
</td>

<td class="right" >4.67
</td>
</tr>
<tr >

<td class="left" >[8518444](http://airbnb.com/users/show/8518444)
</td>

<td class="right" >16
</td>

<td class="right" >21
</td>

<td class="right" >23
</td>

<td class="right" >4.52
</td>
</tr>
<tr >

<td class="left" >[49765](http://airbnb.com/users/show/49765)
</td>

<td class="right" >15
</td>

<td class="right" >13
</td>

<td class="right" >1
</td>

<td class="right" >0.00
</td>
</tr>
<tr >

<td class="left" >[148358](http://airbnb.com/users/show/148358)
</td>

<td class="right" >15
</td>

<td class="right" >11
</td>

<td class="right" >160
</td>

<td class="right" >4.95
</td>
</tr>
<tr >

<td class="left" >[1497543](http://airbnb.com/users/show/1497543)
</td>

<td class="right" >15
</td>

<td class="right" >15
</td>

<td class="right" >252
</td>

<td class="right" >4.76
</td>
</tr>
<tr >

<td class="left" >[3127239](http://airbnb.com/users/show/3127239)
</td>

<td class="right" >15
</td>

<td class="right" >15
</td>

<td class="right" >184
</td>

<td class="right" >4.32
</td>
</tr>
<tr >

<td class="left" >[8206200](http://airbnb.com/users/show/8206200)
</td>

<td class="right" >15
</td>

<td class="right" >15
</td>

<td class="right" >109
</td>

<td class="right" >4.39
</td>
</tr>
<tr >

<td class="left" >[57161](http://airbnb.com/users/show/57161)
</td>

<td class="right" >14
</td>

<td class="right" >16
</td>

<td class="right" >145
</td>

<td class="right" >4.31
</td>
</tr>
<tr >

<td class="left" >[1466173](http://airbnb.com/users/show/1466173)
</td>

<td class="right" >14
</td>

<td class="right" >15
</td>

<td class="right" >517
</td>

<td class="right" >4.30
</td>
</tr>
<tr >

<td class="left" >[3324376](http://airbnb.com/users/show/3324376)
</td>

<td class="right" >14
</td>

<td class="right" >15
</td>

<td class="right" >101
</td>

<td class="right" >5.00
</td>
</tr>
<tr >

<td class="left" >[11907135](http://airbnb.com/users/show/11907135)
</td>

<td class="right" >14
</td>

<td class="right" >0
</td>

<td class="right" >39
</td>

<td class="right" >4.18
</td>
</tr>
<tr >

<td class="left" >[1316725](http://airbnb.com/users/show/1316725)
</td>

<td class="right" >13
</td>

<td class="right" >14
</td>

<td class="right" >9
</td>

<td class="right" >4.83
</td>
</tr>
<tr >

<td class="left" >[1458653](http://airbnb.com/users/show/1458653)
</td>

<td class="right" >13
</td>

<td class="right" >13
</td>

<td class="right" >291
</td>

<td class="right" >4.60
</td>
</tr>
<tr >

<td class="left" >[3947940](http://airbnb.com/users/show/3947940)
</td>

<td class="right" >13
</td>

<td class="right" >13
</td>

<td class="right" >142
</td>

<td class="right" >4.23
</td>
</tr>
<tr >

<td class="left" >[7266554](http://airbnb.com/users/show/7266554)
</td>

<td class="right" >13
</td>

<td class="right" >24
</td>

<td class="right" >127
</td>

<td class="right" >4.58
</td>
</tr>
<tr >

<td class="left" >[16151602](http://airbnb.com/users/show/16151602)
</td>

<td class="right" >13
</td>

<td class="right" >14
</td>

<td class="right" >67
</td>

<td class="right" >4.34
</td>
</tr>
<tr >

<td class="left" >[489690](http://airbnb.com/users/show/489690)
</td>

<td class="right" >12
</td>

<td class="right" >12
</td>

<td class="right" >46
</td>

<td class="right" >4.72
</td>
</tr>
<tr >

<td class="left" >[1173362](http://airbnb.com/users/show/1173362)
</td>

<td class="right" >12
</td>

<td class="right" >0
</td>

<td class="right" >150
</td>

<td class="right" >4.45
</td>
</tr>
<tr >

<td class="left" >[2324191](http://airbnb.com/users/show/2324191)
</td>

<td class="right" >12
</td>

<td class="right" >15
</td>

<td class="right" >173
</td>

<td class="right" >4.32
</td>
</tr>
<tr >

<td class="left" >[3967730](http://airbnb.com/users/show/3967730)
</td>

<td class="right" >12
</td>

<td class="right" >14
</td>

<td class="right" >118
</td>

<td class="right" >4.64
</td>
</tr>
<tr >

<td class="left" >[4265938](http://airbnb.com/users/show/4265938)
</td>

<td class="right" >12
</td>

<td class="right" >8
</td>

<td class="right" >42
</td>

<td class="right" >4.11
</td>
</tr>
<tr >

<td class="left" >[5592355](http://airbnb.com/users/show/5592355)
</td>

<td class="right" >12
</td>

<td class="right" >10
</td>

<td class="right" >68
</td>

<td class="right" >4.62
</td>
</tr>
<tr >

<td class="left" >[219283](http://airbnb.com/users/show/219283)
</td>

<td class="right" >11
</td>

<td class="right" >16
</td>

<td class="right" >34
</td>

<td class="right" >4.78
</td>
</tr>
<tr >

<td class="left" >[239712](http://airbnb.com/users/show/239712)
</td>

<td class="right" >11
</td>

<td class="right" >12
</td>

<td class="right" >590
</td>

<td class="right" >4.23
</td>
</tr>
<tr >

<td class="left" >[1221532](http://airbnb.com/users/show/1221532)
</td>

<td class="right" >11
</td>

<td class="right" >12
</td>

<td class="right" >25
</td>

<td class="right" >4.30
</td>
</tr>
<tr >

<td class="left" >[1254174](http://airbnb.com/users/show/1254174)
</td>

<td class="right" >11
</td>

<td class="right" >12
</td>

<td class="right" >86
</td>

<td class="right" >3.90
</td>
</tr>
<tr >

<td class="left" >[3097566](http://airbnb.com/users/show/3097566)
</td>

<td class="right" >11
</td>

<td class="right" >11
</td>

<td class="right" >88
</td>

<td class="right" >4.45
</td>
</tr>
<tr >

<td class="left" >[9762413](http://airbnb.com/users/show/9762413)
</td>

<td class="right" >11
</td>

<td class="right" >12
</td>

<td class="right" >253
</td>

<td class="right" >4.57
</td>
</tr>
<tr >

<td class="left" >[9928881](http://airbnb.com/users/show/9928881)
</td>

<td class="right" >11
</td>

<td class="right" >0
</td>

<td class="right" >20
</td>

<td class="right" >4.40
</td>
</tr>
<tr >

<td class="left" >[19341612](http://airbnb.com/users/show/19341612)
</td>

<td class="right" >11
</td>

<td class="right" >0
</td>

<td class="right" >12
</td>

<td class="right" >4.54
</td>
</tr>
<tr >

<td class="left" >[213865](http://airbnb.com/users/show/213865)
</td>

<td class="right" >10
</td>

<td class="right" >9
</td>

<td class="right" >158
</td>

<td class="right" >4.46
</td>
</tr>
<tr >

<td class="left" >[2622454](http://airbnb.com/users/show/2622454)
</td>

<td class="right" >10
</td>

<td class="right" >10
</td>

<td class="right" >780
</td>

<td class="right" >4.52
</td>
</tr>
<tr >

<td class="left" >[5281327](http://airbnb.com/users/show/5281327)
</td>

<td class="right" >10
</td>

<td class="right" >4
</td>

<td class="right" >212
</td>

<td class="right" >4.65
</td>
</tr>
<tr >

<td class="left" >[5425196](http://airbnb.com/users/show/5425196)
</td>

<td class="right" >10
</td>

<td class="right" >0
</td>

<td class="right" >190
</td>

<td class="right" >4.17
</td>
</tr>
<tr >

<td class="left" >[9505402](http://airbnb.com/users/show/9505402)
</td>

<td class="right" >10
</td>

<td class="right" >19
</td>

<td class="right" >247
</td>

<td class="right" >4.65
</td>
</tr>
<tr >

<td class="left" >[9759851](http://airbnb.com/users/show/9759851)
</td>

<td class="right" >10
</td>

<td class="right" >11
</td>

<td class="right" >8
</td>

<td class="right" >4.69
</td>
</tr>
<tr >

<td class="left" >[3343353](http://airbnb.com/users/show/3343353)
</td>

<td class="right" >9
</td>

<td class="right" >14
</td>

<td class="right" >14
</td>

<td class="right" >4.89
</td>
</tr>
</tbody>
</table>
Airbnb has basically removed all the top hosts (who had 20 or more listings) and also removed a smattering of others. (If you have a booking at [this listing](https://www.airbnb.com/rooms/1359998) I would make other plans.)

So why has Airbnb done this? They made their usual bland, substance-free comment to the LA Times: that the company's "mission is to connect hosts with guests and provide a quality, local and authentic experience. We routinely review our platform for market quality and adherence to this mission."

Quality looks out: as a user to the site what you see is the rating of the listing, and many of the eliminated hosts have high average ratings. For example, the [Urban Flat Team](https://www.airbnb.com/users/show/2917744) have had their listings removed but had an average rating of 4.85 (out of five), while the [Venice Beach Hostel](https://www.airbnb.com/users/show/1254174) has a rating of only 3.90 (which is pretty crap) but is still on the site.

It's also nothing to do with the type of listing. Most of the top listers are listing out mainly "Entire home/apt" listings (as opposed to a private room in a house or a shared room) but then so does [Prive Luxury Rentals](https://www.airbnb.com/users/show/8518444) and they have actually increased their number of listings from 16 to 21.

What's left is the statement of the sales rep to the AE Hostel agency: that these listings are interfering (probably with no fault of their own) with Airbnb's public image. The LA Times mentions the possibility
of maneuvering in advance of an IPO, and this must be in the minds of some of the Airbnb executives. Also, the LAANE report from last month may be having an impact.

My guess is that Airbnb knows it has to look after its image as a peer-to-peer company, and that they are removing some of the most high profile professional partners from the site in preparation. So all well and good (although hardly fair on those partners), but is it sincere?

Probably not. Here are a few facts that Airbnb will probably not publicise:



	
  * In October 2014 there were 49 hosts with 10 or more listings in LA. Now there are 60.

	
  * In October 2014, visits to Airbnb hosts in LA were split evenly between "single-lister" hosts and "multi-lister" hosts. Now the balance has tilted slightly towards multi-listers: their percentage has increased from 50% to 52%.

	
  * In New York, where Airbnb previously had a clean-up of large listers, the number of hosts with 10 or more listings has increased from 19 to 46 between October 2014 and March of this year.


In short, the professionalization of the Airbnb business continues, and this looks like just an attempt to remove some of the more obvious commercial companies.

Could it be something else? Of course it could, but if Airbnb wants to be taken seriously as a company that can regulate itself (and it really does) then it needs to come clean with the reasons for its actions rather than hiding between vacuous PR speak and turning, seemingly at random, on its partners.		
