---
author: Tom Slee
categories:
- blog archive
date: 2007-03-10 18:50:13
title: The Long Tail 7 - The New Tastemakers
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is another part of my critical reader's companion to _The Long Tail_, and it discusses Chapter 7 - The New Tastemakers. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html). 

* * *

In a [comment on Chapter 6](http://whimsley.typepad.com/whimsley/2007/03/new_marketplace.html#comments), John points us to an [article](http://www.dlib.org/dlib/april06/dempsey/04dempsey.html) which mentions [Ranganathan's Five Laws of Library Science](http://en.wikipedia.org/wiki/Five_laws_of_library_science).These laws are:




  1. Books are for use.


  2. Every person his or her book.


  3. Every book its reader.


  4. Save the time of the reader.


  5. The library is a growing organism.

Laws 2 and 3 remind us that the whole publishing process is about guidance. Guiding readers to books they like, and guiding books to readers who like them. The various stages of writing, submitting to publishers, editing, publishing, publicising, reviewing, discovering, recommending, locating, browsing, requesting, buying/borrowing, delivering are one path through the maze that is needed to guide books to their readers and readers to their books. Guidance is the subject of Chapter 7.




I want to leap ahead some pages into the chapter this time. Because on at last, after a hundred and nine pages, we get some real evidence of a specific industry that is showing a big Long Tail effect - and it's our old friend Netflix.




Filters rule [108-110] is a reflection of Anderson's belief in the power of filters to "level the playing field, offering free marketing for films that can't otherwise afford it, and this spreading demand more evenly between hits and niches" [110]. The main effect, he says, is "to help people move from the world they know ('hits') to the world they don't ('niches')" [109].




The evidence that he gives in this section in favour of the claim comes Reed Hastings, CEO of Netflix (and provider of a blurb for the book):

<blockquote>Historically BlockBuster has reported that about 90% of the movies they rent are new theatrical releases. Online they're more niche: about 70% of what they rent from their website is new releases and about 30% is back catalog. That's not true for Netflix. About 30% of what we rent is new releases and about 70% is back catalog and it's not because we have a different subscriber. It's because we create demand for content and we help you find great movies that you'll really like. And we do it algorithmically, with recommendations and ratings.
> 
> </blockquote>

In fact, since the book was published, Netflix have set up the [Netflix Prize](http://www.netflixprize.com/) for people to suggest better algorithms. The first submission to improve the accuracy of the algorithm by 10% will win $1 million. So Netflix are taking this seriously. Finally, there appears to be some substance behind the shifting generalities of the book. 




Or is there? Lee Gomes of the Wall Street Journal [begs to differ](http://online.wsj.com/public/article/SB115447712983624018-0lesF4BaCaky8M_CIQ_qf11qgPA_20070802.html?mod=blogs).

<blockquote>Netflix defines "back catalog" expansively. A spokesman says it's anything outside of the 50 or so DVDs getting heavy studio promotion at any given time. So even recent megahits like "Spiderman II" are in the back catalog.
> 
> 

> 
> What's more, since Netflix rents 60,000 titles, it follows that those 50 titles -- eight-tenths of 1% of inventory -- generate 30% of all rentals.
> 
> </blockquote>

This was the second of two Gomes articles on the Long Tail and part of a debate that focused on the extent of the effect that Anderson is describing. The [first](http://online.wsj.com/article/SB115387606762117314.html?mod=Portals) article was a review of the book, and in that review he referred to [work](http://www.people.hbs.edu/aelberse/papers/hbs_07-015.pdf) by Harvard Business School's Anita Elberse that only "shows a 'slight shift' toward the tail. But she also noted 'a rapidly increasing number of titles that never, or very rarely, sell,' which suggests 'it is difficult for content providers to profit from the 'tail.' ". Again, a "slight shift" is not an "epochal shift". Anderson [responded](http://www.longtail.com/the_long_tail/2006/07/factchecking_my.html) to that review, arguing that 

<blockquote>As Professor Elberse told Gomes, she was only describing Nielsen VideoScan data, which is almost entirely taken from bricks-and-mortar sources. The Netflix data, which was the basis of the Long Tail analysis that she and I worked on together, tells a very different story (Elberse's terms of data access don't allow her to share that data; my terms allowed me to share what I published in the book). We both urged Gomes to make clear that the "slight shift" measured didn't refer to the Netflix data that was at the core of the book's conclusions. But he chose to make the point he wanted to make.
> 
> </blockquote>

In comments to that post, Elberse herself stepped in to say that

<blockquote>You [Anderson] say "Nielsen VideoScan data (...) is almost entirely taken from bricks-and-mortar sources." I don't think this is entirely correct. The VideoScan data reflect both offline and online sales, and actually break them down by channel. The breakdown is not as detailed as one might wish in an ideal world, but they do allow one to track whether, say, the share of offline sales go down over time. Therefore, I do think the fact that my colleague and I only observe a "slight" shift is meaningful.
> 
> </blockquote>

In a letter [published](http://www.roughtype.com/archives/2006/07/lee_gomes_respo.php) on Nicholas Carr's weblog, Gomes said.

<blockquote>I'd like to correct an extremely serious misrepresentation Chris made at the end of his blog posting, to the effect that Anita Elberse of Harvard "urged" me not to characterize her work the way I did. This is manifestly false. Chris is either misremembering or deliberately conflating two separate issues. Prof. Elberse did indeed in an email remind me that the data she had for Netflix was under NDA, and I could thus not report it. But the comment had nothing to do with what Chris says it does. Let Prof. Elberse herself describe whether I got it right; below is the full text of an email she sent me after the story ran:
> 
> 

> 
> "I just read your article, and just wanted to thank you for being so careful in quoting me. I wish all journalists stayed this close to what was actually said! :-)
> 
> 

> 
> "You did beat me 'to the market' with your article, but I hope our academic article (which should be ready in a few weeks) will further clarify the long tail phenomenon (or lack thereof)."
> 
> </blockquote>

A lot of heat there. For anyone interested in more depth, I recommend you to Anita Elberse and Felix Oberholzer-Gee's working paper "Superstars and Underdogs: An Examination of the Long Tail Phenomenon in Video Sales" ([50 page PDF](http://www.people.hbs.edu/aelberse/papers/hbs_07-015.pdf)). Here is a paragraph from the abstract:

<blockquote>To shed light on this debate, we study the distribution of revenues across products in the  
context of the U.S. home video industry for the 2000 to 2005 period. We find superstar and long-tail  
effects in home video sales, but each effect comes with a twist. There is a long-tail effect in that the  
number of titles that sell only a few copies every week increases almost twofold during our study  
period. But at the same time, the number of non-selling titles rises rapidly; it is now four times as  
high as in 2000. Many underdogs thus in fact appear to be losers. We also find evidence of a  
superstar effect. Among the best-performing titles, an ever-smaller number of titles accounts for the  
bulk of sales. The caveat here is that today’s superstars lack the punch of earlier generations: video  
sales generally decrease over time across all quantiles of the sales distribution, but this effect is most  
pronounced among best-selling titles. Our findings have important implications for entertainment  
companies. Exploiting the tail might prove unprofitable if many titles do not sell at all. At the same  
time, producing superstars is more difficult than ever. The trends we uncover thus point to  
significant challenges for the entertainment industry.
> 
> </blockquote>

In short, this most significant, most specific piece of information regarding an actual shift to long-tail behaviour, prompted and guided by Internet recommendation algorithms, turns out to be as insubstantial as other pieces of evidence. Filters don't rule.




Well, with that over, let's go back to the beginning. There is, we all know, a lot of stuff on the Internet, which is why the picture is so appealing. But as John pointed out in his Chapter 6 comment (and as I'll say in more detail in Chapter 8), the tail has to be fat as well as long for the "theory" to make any sense. We also know that increasing returns and large fixed costs coupled with small marginal costs and freedom from geographical limitations gives the aggregators of the Internet (Amazon, Netflix, iTunes and the other handful of examples that Anderson returns to over and over again) the potential to be globe-straddling colossi, or [oligonomies](http://www.oligopolywatch.com/2003/08/04.html), to use Steve Hannaford's word, who are oligopolies as far as customers go and oligopsonies as far as suppliers go. So the Internet is likely to have fewer vendors selling larger numbers of products than the brick & mortar world - One Big Virtual Tent rather than Many Small Tents. But where does this leave us when it comes to demand? It all depends on whether guidance on the Internet can help people find niche products in the Big Tent better than guidance in the physical world can help people find what they want in the Many Small Tents. The issue of guidance, then, is central.




Not only is it central, but it's a particularly difficult problem for niche items. The problem of finding quality in "experience goods" - such as books, movies, and to some extent music - is a problem of asymmetric information. As such, it is prone to a form of market failure that goes under the name of the [market for lemons](http://en.wikipedia.org/wiki/The_Market_for_Lemons). In short, the incentives are set up to encourage various forms of false reporting and gaming of the system (I have a strong incentive to give my own book a five-star rating on Amazon, for example). Knowing this, customers avoid those parts of the market where the asymmetry in information is strongest - the niches - and flee to those parts where information is most reliable - the hits. Predictability can drive out quality when information is scarce and unreliable. The market for lemons has been one of the most influential ideas in economics over the last several decades, its ramifications are ubiquitous, and it earned its inventor [George Akerlof](http://en.wikipedia.org/wiki/George_Akerlof) a Nobel Prize. But even though Anderson describes his book as "partly an economic research project" [11] there is no evidence this idea has troubled him, and it is not mentioned in his book.




Let's look at how Anderson says guidance happens in the Long Tail world. Here's the big picture, optimistic as ever:

<blockquote>Faith in advertising and the institutions that pay for it is waning, while faith in individuals is on the rise. Peers trust peers. Top-down messaging is losing traction, while bottom-up buzz is gaining power. Dell spends hundreds of millions each year on promoting its quality and customer service, but if you Google "dell hell" you'll get 55,000 pages of results [click [here](http://whimsley.typepad.com/whimsley/2007/03/progressive_blo.html) to see why this number is wildly wrong]. Even the word "dell" returns customer complaints by the second page of results. The same inversion of power is now changing the marketing game for everything from individual products to people. The collective now controls the message....The new tastemakers are us... The ants have megaphones. [98-99]
> 
> </blockquote>

But as Oligopoly Watch reminded us just [yesterday](http://www.oligopolywatch.com/2007/03/09.html), "while the myth is that the Internet represents an infinite array of shelves (I think of [Borges's library of Babel](http://en.wikipedia.org/wiki/The_Library_of_Babel)) with everything democratically and randomly available, the real world has a way of organizing things up front or way back, even when it's all cyberspace." Aggregators are One Big Virtual Tent, and vendors will scrabble to get a place on the tables by the entrance. Oligopoly Watch quotes a Wall Street Journal article on Apple's iTunes ('Music's New Gatekeeper') as saying "Every day, the roughly one million people who visit the iTunes Store home page are presented with several dozen albums, TV shows and movie downloads to consider buying -- out of the four million such goods the Apple site offers. This prime promotion is analogous to a CD being displayed at the checkout stands of all 940 Best Buy stores or featured on the front page of Target's ad circular." Here is a way that Internet commerce, with its tendency to produce oligopolies, promotes uniformity rather than promoting diversity. Instead of many different store fronts, we have One Big Virtual Storefront. A high proportion of regular bookstores' sales come from the highly-promoted items, and there is no reason to believe that aggregators' sales will be different.




Bonnie McKee [98-103], My Chemical Romance [103-104] and BirdMonster [104-106] are three stories about different bands and their mixed experiences with online recommendation systems, social networking sites, and blogs to promote their music. While Anderson says that the stories show "how the three forces of the Long Tail are overturning the status quo in the music industry" [104]. A big statement, with little behind it. My Chemical Romance is a success, Bonnie McKee is struggling, and BirdMonster is a local band in San Fransisco. This is new? No.




The Power of Collective Intelligence [106-108] introduces us to the filter, which is "the catch-all phrase for recommendations and other tools that help you find quality in the Long Tail" [106]. Anderson is very enthusiastic about recommendation systems, saying that "the trend-watchers at Frog Design" see the rise of recommendations as "nothing less than an epochal shift" [107].




The adoption of recommendation systems on all kinds of web sites has been a boon to help promote worthwhile content and demote non-worthwhile content, and as they get more sophisticated they are a continuing innovation of great worth. But they set out to rectify a problem that is peculiar to the Internet, after all, which is the problem of anonymity and lack of trust. How do you establish trust in the online world? The existence of recommendations is a reflection of the fact that the Internet is handicapped when it comes to reliable and trustworthy communication. Recommendation systems are a great effort to overcome an obstacle that the physical world (which has its own problems) faces to a much smaller degree. When a friend recommends a book or movie to me, I have a reasonable idea of how to take that recommendation because I know my friend. When a book has a 3.5 rating on Amazon.com with three reviews, what am I to make of that? Was it friends of the author? Quite possibly.




The next section, "Filters Rule" was discussed at the top of the article.




One Size Filter Doesn't Fit All [110-112] looks at various kinds of filter in more depth. It shows that filters are an increasingly sophisticated set of tools for aggregators to use to attract customers. But it does not show whether or not these filters are anything close to the power of our own offline networks of friends. 




Not All Top Ten Lists are Created Equal [112-115] is more in a similar vein. Some online sites have developed filters that use an increasingly fine granularity and set of classifications of online lists. But can any algorithmic granularity capture our quirky tastes?




Is the Long Tail Full of Crap? [115-119] is a venture into explanation. It contains references to information theory, to zero sum games, to non-rivalrous goods, and to wide dynamic ranges. But they are name dropping, inserted to hint at a greater intellectual behind the Long Tail. It isn't there. The point he is making is that, as Theodore Sturgeon [I always thought he was a creation of Kurt Vonnegut, but Wikipedia [tells me](http://en.wikipedia.org/wiki/Theodore_Sturgeon) that Vonnegut's Kilgore Trout was based on the real-life Theodore Sturgeon] apparently said "ninety percent of everything is crud". But as long as you have unlimited shelf space, it doesn't matter, because filters can help you find the good. There is an odd unsubstantiated claim that the material "in the tail" ranges from worse than that in the hits to better but, he goes on, "averages don't matter. Diamonds can be found anywhere."[118].




The Tail That Wags Everything Else [119-122] is another slight section which reiterates the previous point: "As the Tail gets longer, the signal-to-noise ratio gets worse. Thus, the only way a consumer can maintain a consistently good enough signal to find what he or she wants is if the filters get increasingly powerful" [119]. It is out here in the tail, where comments on Amazon, links, and other filters are rare per item, that problems of asymmetric information are greatest, raising a further undiscussed barrier to those good quality items in the tail achieving recognition. So filters have a greater job to do, and are fighting an uphill battle. How do they do? Well I could use the [Anderson method](http://whimsley.typepad.com/whimsley/2007/03/progressive_blo.html) and point out that typing "ebay fraud" into Google gives [about] 4,160,000 hits - but in fact, Google estimates being what they are, the number is actually 780, so that tells us little. But see [here](http://www.freedom-to-tinker.com/?p=1127), [here](http://www.wired.com/wired/archive/15.03/herding_pr.html), and [here](http://www.wired.com/news/technology/internet/0,72832-0.html?tw=wn_index_2) for articles about manipulating reputation systems - the last two, ironically, from the Anderson-edited Wired Magazine. The first article of the three, by Princeton University Computer Science Professor Ed Felten, says this:

<blockquote>There’s a myth floating around that such systems distill an uncannily accurate folk judgment from the votes submitted by millions of ordinary citizens. The wisdom of crowds, and all that. In fact, reputation systems are fraught with problems, and the most important systems survive because companies expend great effort to supplement the algorithms by investigating abuse and trying to compensate for it. eBay, for example, reportedly works very hard to fight abuse of its reputation system.
> 
> </blockquote>

"The wisdom of crowds, and all that" just about summarizes Anderson's sunny outlook on this promising but still-flawed, and perhaps unavoidably flawed, method for directing demand.




I should also point out that Anderson also briefly quotes[120] Nassim Taleb's engaging book [Fooled By Randomness](http://www.google.ca/url?sa=t&ct=res&cd=1&url=http%3A%2F%2Fwww.fooledbyrandomness.com%2F&ei=nzvzRYaQAqiWgQKIvpTBAQ&usg=__eerzwziMB85Mj_Zz1BRGu270Bdg=&sig2=uTaqkkB3iAsgEUCgW2hnVg), on the unpredictability of hits. 




Pre-Filters and Post-Filters [122-124] distinguishes the "pre-filters" of the offline world which "filter before things get to market" and the recommendation and search technologies, or "post-filters" of the Internet. Here, then, are two models of guidance in an attempt to achieve that "every book its reader" ideal. Given the challenges faced by post-filters (the increasing "signal to noise" ratio in the tail discussed by Anderson, the potential for gaming the system, the market-for-lemons problem that particularly targets niche products in the face of that potential), it is good to see Anderson does acknowledge the difficulties: "Because post-filters tend to be amateurs, oftentimes that means less critical independence and more random malice." But in general he is remarkably sunny about the prospect for Internet recommendations to direct people reliably to even the deepest darkest corners of the One Big Virtual Tent. Filters are great, but they have a big job to do. Overall, I don't share his optimism.


		
