---
author: Tom Slee
categories:
- blog archive
date: 2014-01-03 14:25:00
tags:
- sharing-economy Uber
title: On Surge Pricing
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Lots of controversy about the "surge-pricing" from car-rental outfit [Uber](http://uber.com), both during a [mid-December snowstorm](http://www.metro.us/boston/news/2013/12/15/uber-mad-boston-cab-passengers-vent-as-snow-drives-uber-prices-through-the-roof/) and on [New Year's Eve](http://www.prdaily.com/Main/Articles/Uber_fields_dozens_of_complaints_about_hefty_New_Y_15849.aspx). Fares increased up to eight times the normal, so that people were getting charged hundreds of dollars for short rides. The company's response was that surge pricing is [here to stay](http://www.capitalnewyork.com/article/city-hall/2013/12/8537861/uber-its-here-stay).

The argument is standard supply-and-demand, economics 101. If demand goes up, increase the price to increase supply. Or, as the company [says](http://blog.uber.com/uber-nye-2014):


<blockquote>With surge pricing, Uber rates increase to get more cars on the road and ensure reliability during the busiest times. When enough cars are on the road, prices go back down to normal levels.</blockquote>


But there are two things that I haven't seen elsewhere (correct me if I'm wrong); not even on Matthew Yglesias's [post](http://www.slate.com/blogs/moneybox/2013/12/16/uber_surge_pricing_the_company_should_give_the_extra_money_to_the_driver.html) at Salon, and he is a [magnificent](https://twitter.com/mattyglesias/statuses/405719658378326016) observer of this and all other things.

**Thing One:** I really don't care if you engage in "surge pricing" on New Year's Eve, at rush hour, or at any other time when traffic is predictably busy. Knock yourself out, it's absolutely fine by me. But surge pricing because of severe weather is something different, because at times of emergency we expect people to pull together: we expect people to check on their neighbours (for free!), to help people who are stuck (without charging!) and to generally be community-minded about things. Emphasizing monetary incentives at such a time undermines (or "crowds out") community motives: if my neighbour and I help push your car out of a snowbank without payment then we're just doing the right thing, but if my neighbour is being paid and I'm doing it for free, then I'm just being a mug. Surge pricing for reasons of severe weather is a bad idea. You may get a few more cabs on the road, but you make the emergency worse.

**Thing Two:** Customers were complaining that they didn't know about the extra pricing until after they had taken their ride. Uber explained that they must have known: there was a perfectly clear screen notifying them about surge pricing, and they tapped the screen to agree to it. Now I used to do online documentation, and I've spent my fair share of time frustrated at the stupidity of users who cannot navigate my crystal-clear and elegant design ("Look: the button at the top there. It's obvious"). But in the end anyone involved in user experience has to acknowledge that the user is right. What's obvious to a designer or a trained user is not at all obvious to a casual user.

So if you design an app with the express purpose of making it easy to use without even thinking, and if a customer uses it fifty times and gets the same result each time, then they are not going to be paying attention the 51st time, especially after a few drinks. If you then add one extra screen in the middle of the ordering sequence that's going to cost users an extra $300, then it's up to you to test it till the cows come home to make sure that people know what they are agreeing to. Arguing that users should have been more careful is a really bad excuse. We should all read license agreements too, but none of us do. We just click, click, click until we get to the thing we want. Read? Of course I don't read! And who's ever heard of a $300 button in a mobile app? Sorry Uber: if you charge people an extra $300 for using your app too casually then it's your own fault.		
