---
author: Tom Slee
categories:
- blog archive
date: 2009-01-28 06:47:25
title: One hundred thousand
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

That's the total number of page views of this blog, according to Sitemeter, although TypePad says it's only 83,000 or so. Still, it seems like a time to take stock or at least review some basic stats:

First post: November 2005. Total number of posts, excluding this one, 292. So that's about two a week. 

  
Number of visits: about 60,000. So on average a visit is two pages. Most are only one, and a few people with nothing better to do click around once in a while.  
  


Average page view rate is about 100 per day. Probably a good half of those are inappropriate searches, and it looks which leaves an actual readership of about 50 people per day. In general my traffic is lower than that, but I seem to have a handful
of patrons (thank you Nick C, Henry F, Mark T, Brad D) who
have sent people this way and then I get a spike. 

  
Most views in a day was over 2500 when Nick Carr pointed people to [Mr. Google's Guidebook](http://whimsley.typepad.com/whimsley/2008/03/mr-googles-guid.html). I've only had one post get traffic through reddit or digg, which was a computer software post some time ago.

  
Audience: On average, I'm writing for an audience of about 100 people, although there is no way to tell someone who reads every word I write from someone who glances at the title and moves on. 

  
Comments: 429, or about 1.5 comments per post. My impression is this is pretty low even for blogs of my readership. Not surprising as I am too slow a writer to get into many of the debates that prompt comments and don't link to other bloggers as much as I should. Partly, while some widely read blogs post link collections to draw people's attention to particular views, it seems a waste to post such collections here. There is little point in me saying "hey, look what the BBC/New York Times/CBC has posted"; if you need a guide to the news you won't find it here.  
  
Thanks to those of you who come here regularly. I will try to respond to comments more often, but let's face it, that resolution may well go the way of my others.

  
Now, if I just carry on blogging for another two years I should have the same size audience as my 30 second [caterpillar video](http://ca.youtube.com/watch?v=zE-p2JE-Oc8) has achieved on YouTube, recorded in less than twenty minutes in a single afternoon.  



		
