---
author: Tom Slee
categories:
- blog archive
date: 2006-06-09 00:18:52
title: Reading about Iraq
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I don't usually post about Iraq, because I don't really have anything to offer. But I could not help contrast the idea that the killing of Zarqawi is somehow significant with the following two pieces.




First, from the best blogger in the world at [Baghdad Burning](http://riverbendblog.blogspot.com/2006_06_01_riverbendblog_archive.html#114954848489173468).

<blockquote>We heard the news about the dozens abducted from the Salhiya area in Baghdad. Salhiya is a busy area where many travel agencies have offices. It has been
particularly busy since the war because people who want to leave to
Jordan and Syria all make their reservations from one office or another
in that area.
> 
> </blockquote>




<blockquote>According to people working and living in the
area, around 15 police cars pulled up to the area and uniformed men
began pulling civilians off the streets and from cars, throwing bags
over their heads and herding them into the cars. Anyone who tried to
object was either beaten or pulled into a car. The total number of
people taken away is estimated to be around 50.
> 
> </blockquote>




<blockquote>This has been
happening all over Iraq- mysterious men from the Ministry of Interior
rounding up civilians and taking them away. It just hasn’t happened
with this many people at once. The disturbing thing is that the Iraqi
Ministry of Interior has denied that it had anything to do with this
latest mass detention (which is the new trend with them- why get
tangled up with human rights organizations about mass detentions,
torture and assassinations- just deny it happened!). That isn’t a good
sign- it means these people will probably be discovered dead in a
matter of days. We pray they’ll be returned alive…
> 
> </blockquote>




<blockquote>Another piece of particularly bad news came later during the day. [Several students riding a bus to school were assassinated in Dora area. ](http://news.yahoo.com/s/nm/20060605/ts_nm/iraq_dc_223;_ylt=An_yyn96X_i1DTdg8J7K8WYUewgF;_ylu=X3oDMTA2ZGZwam4yBHNlYwNmYw--)No
one knows why- it isn’t clear. Were they Sunni? Were they Shia? Most
likely they were a mix… Heading off for their end-of-year examination-
having stayed up the night before to study in the heat. When they left
their houses, they were probably only worried about whether they’d pass
or fail- their parents sending them off with words of encouragement and
prayer. Now they’ll never come home.
> 
> </blockquote>




<blockquote>There’s an ethnic cleansing
in progress and it’s impossible to deny. People are being killed
according to their ID card. Extremists on both sides are making life
impossible. Some of them work for ‘Zarqawi’, and the others work for
the Iraqi Ministry of Interior. We hear about Shia being killed in the
‘Sunni triangle’ and corpses of Sunnis named ‘Omar’ (a Sunni name)
arriving by the dozen at the Baghdad morgue. I never thought I’d
actually miss the car bombs. At least a car bomb is indiscriminate. It
doesn’t seek you out because you’re Sunni or Shia.
> 
> </blockquote>




<blockquote>We still
don’t have ministers in the key ministries- defense and interior. Iraq
is falling apart and Maliki and his team are still bickering over who
should get more power- who is more qualified to oppress Iraqis with the
help of foreign occupiers? On top of all of this, rumor has it that the
Iraqi parliament have a ‘vacation’ coming up during July and August.
They’re so exhausted with the arguing, and struggling for power, they
need to take a couple of months off to rest. They’ll leave their
well-guarded homes behind for a couple of months, and spend some time
abroad with their families (who can’t live in Iraq anymore- they’re too
precious for that).
> 
> </blockquote>




And second, from Juan Cole at [Informed Comment](http://www.juancole.com/2006/06/zarqawi-killed-in-baquba-prime.html):

<blockquote>Zarqawi had been a significant leader of the Salafi Jihadi radical
strain of Islamist volunteers in Iraq, and had succeeded in spreading
his ideas to local Iraqis in places like Ramadi. He engaged in
grandstanding when he renamed his group "al-Qaeda in Mesopotamia," even
though he had early been critical of al-Qaeda and had a long rivalry
with it. For background, see [the Zarqawi file](http://www-personal.umich.edu/%7Ejrcole/zarqawi/zarqawix.htm).  
  
There
is no evidence of operational links between his Salafi Jihadis in Iraq
and the real al-Qaeda; it was just a sort of branding that suited
everyone, including the US. Official US spokesmen have all along
over-estimated his importance. Leaders are significant and not always
easily replaced. But Zarqawi has in my view has been less important
than local Iraqi leaders and groups. I don't expect the guerrilla war
to subside any time soon.  
  
Baqubah is dangerous not because of
Zarqawi but because it is a mixed Sunni-Shiite and Kurdish area that
had Baath military installations and arms depots, and enough Sunni
Arabs from the old regime know about them to work them against rising
Shiite and Kurdish dominance.  
  
On the other hand, there have been
persistent reports of a split between the main arm of the guerrilla
resistance, the Sunni Arab Iraqis, and Zarqawi's group.   
  
[Al-Hayat reports today [Ar.]](http://www.daralhayat.com/arab_news/levant_news/06-2006/Item-20060607-b0285dac-c0a8-10ed-00c1-55653b5c5568/story.html)
that groups in Fallujah have launched attacks on Zarqawi followers
there after the latter attacked the al-Husain Mosque in the Askari
quarter two days ago, destroying the tomb of the founder of the mosque
within it. (Salafis influenced by Saudi Wahhabism despise attendance at
saints tombs, insisting on a Protestant-like elimination of all
intermediaries between human beings and God. Many Islamists in Fallujah
are actually Sufis, who value saints in the way rural Catholics do.) An
attempt by the radical Salafis to destroy the mosque (on the grounds
that it had been tainted with polytheism) was stopped by the "1920
Revolution Brigades," a local ex-Baathist group. There was a running
gun battle between the two.  
  
Zarqawi's group had also tried two
days ago to attack a Fallujah police station, but they were repulsed by
local tribal youth. The battle left two cars burned and 4 dead from the
tribe of Al-Bu `Isa.
> 
> </blockquote>

The contrast between the dregs we get on the news here and these kind of comments is astounding. Read the two of them, and it's clear that this event will have no effect whatsoever on the level of destruction in Iraq.




I've been reading these writers for a couple of years or so. Both have shown a steady progression towards disillusionment, anger, and despair over the state of Iraq. Watching Juan Cole go from moderate, academic observer to outright fury has been quite something.  



		
