---
author: Tom Slee
categories:
- blog archive
date: 2007-07-18 21:26:21
title: Dave Meleney
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is a difficult post to write. 




Those of you who read the comments section of the blog will have seen quite a few comments by Dave Meleney, a libertarian from Colorado. Sadly I found out - simply because I looked at a google search that came to this weblog and clicked a link - that Dave died last Thursday in an accident while trimming trees. The link I clicked led to a brief note [here](http://lpcolorado.blogs.com/lpcolorado/2007/07/the-lpco-mourns.html).




As is the way with Internet contacts I knew a few things about Dave, but almost nothing about his real life. I knew that he was a Bonsai enthusiast who had grown huge numbers of bonsai trees, and yet I didn't know how old he was. I knew that he had been to China, but not what he looked like.




The other thing I know is that Dave commented on weblogs a lot (both here at Whimsley and elsewhere, at Marginal Revolution for example). Most recently we had a brief exchange in which he posted a comment last Wednesday ([link](http://whimsley.typepad.com/whimsley/2007/07/happy-shoes-iv-.html#comments)) that I replied to a few days later, not having a clue of what had happened in the meantime. We disagreed - mainly over the role of multinational companies in poor countries, which he saw as overall hugely positive for the poorest people in those countries, and over the role of government - but he was unfailingly polite and thoughtful and articulate. He even offered my family the use of a cabin even though we had never met and even though I don't know what family he has.




So I am in the odd position of saying that I will miss Dave, even though I hardly knew him. I am convinced he was a kind and generous man -something that emails I have received in the last 24 hours from a couple of people who did know him better confirms. My heart goes out to his family. 




If it is not inappropriate I'd like to suggest that anyone of his Internet contacts who has read his comments and engaged in conversation with Dave, and who wishes to express their condolences, might go to the [posting at the Libertarian Party of Colorado](http://lpcolorado.blogs.com/lpcolorado/2007/07/the-lpco-mourns.html) and add a brief note to the comments there.




Rest in peace Dave.


		
