---
categories:
- blog archive
title: Google's countercultural moment is over
date: 2009-01-15
author: Tom Slee
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::
-

  
For many cultural and artistic movements there is a "counter-cultural moment" when a previously obscure and out-of-the-way tendency suddenly gains prominence. It may be the surrealists in the '30s, Bauhaus in the '20s, the hippy movement in the late '60s, punk in the late '70s - each had a few years in which it was both important and yet still opposed to the mainstream. But that counter-cultural moment is short, often just a handful of years, and once it is over, the movement either becomes the mainstream or fades away. Only nine years after the summer of '67 the hippies were a thing of the past and punk set itself up in direct opposition to the pompous and irrelevant dinosaurs that "progressive rock" bands had become.  
  
"Geek culture" has had its counter-cultural moment. It's over.  
  
It is now eight years today since Wikipedia started, four years since blogging, ten years of Google. These formerly "hungry upstarts" are now the establishment. Netflix partners with Wal-Mart, Google partners with CBS, Amazon is bigger than any of those "establishment" bookstores it challenged and pushes around publishers with impunity. Geek culture is now mainstream. Google, Amazon, Netflix have passed their counterculture sell-by date.  



		
