---
author: Tom Slee
categories:
- blog archive
date: 2006-01-31 16:11:45
title: 'Why Globalization Works: Notes Part 1'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is part one of some notes taken while reading _Why
Globalization Works _by Martin Wolf, and it covers parts I and II of the book.
I’m reading it because it is a well-respected book putting the case in
favour of globalization, a project I am in general opposed to (at least the way
globalization is usually defined). It is a “brilliant book” (Lawrence
Summers, President, Harvard University), a “devastating intellectual critique
of the opponents of globalization” (Mervyn King, Governor of the Bank of
England), and “a definitive analysis” (Kenneth Rogoff, Harvard University).
Whether I’ll get around to part two of these notes is open to question.




* * *




Every academic discipline has its own way of putting itself
at the centre of the world. Chemists point out that everything around us and
inside us is made of chemicals. Physicists say that cosmology asks the only
questions worth answering. Literary theorists say that there is nothing outside
the text, and the interpreters of texts (ie themselves) are therefore the ones
who bring meaning to the world. The economists’ version of this conceit is to
claim that markets are responsible for all the good in the world. It is a
conceit that Martin Wolf indulges in the early chapters of _Why Globalization
Works_, and it shapes his argument in the rest of the book, so it is worth
inspecting. 




Wolf overreaches when setting out his claims, both in terms
of what a market is and in terms of its centrality in the story of human
progress. 




For most of us, the market is that part of the capitalist
system that involves commercial exchange. Such a definition involves two
limitations. First, it defines “the market” in the sense that we usually use
it, as part of capitalism: people have had markets for thousands of years, and
yet when Adam Smith wrote about the wealth of nations it was not these markets
that he was writing about. Second, it emphasizes that modern capitalist
societies are many faceted, and some of these facets --- political democracy,
the modern state, scientific research, and portions of culture, are
nevertheless largely outside “the market”.




Wolf traces the origins of market-based wealth production
back before the industrial revolution and the founding of capitalism, to a
thousand years ago. He claims that we are living in “the millennium of the
market” (p. 43) and as evidence of this points to the fact that population and
economic growth started well before 1800. Yet correlation is not causation, and
the existence (p 41) of commercial activity in China during the Sung dynasty
(960 – 1279) does not demonstrate that markets have driven progress. Perhaps
this is splitting hairs – the book is about the modern age after all – but I
don’t think so. Wolf is setting the stage for an argument that an expansion of
global markets is what we need, and if the stage is built on rickety
foundations that argument cannot hold. There is little in his argument about
“the millennium of the market” that is convincing.




The second way in which Wolf overreaches is of more
immediately obvious importance. In talking about the role of the state in
liberal democracies, Wolf conflates several meanings of “markets”. As I said
above, to observer that we live in a capitalist society does not mean that all
elements of our society are capitalist. We also live in a scientific society, a
technological society, a cultural society, a welfare-state society and a
hierarchical society – do these aspects of the world have a part to play too?
What Wolf does in his discussion of market economies is to move back and
forward between a narrow meaning of markets (capitalist exchange) and a broader
meaning (the entire society of which it is a part), and the result is
confusion.




This confusion is most obvious when Wolf discusses
opposition to the market (pages 54 to 55). Wolf claims that “The market economy
does not merely support its critics, it embraces them”. Here he is defining the
market economy broadly enough to include those who oppose the actions of
markets, and goes on to assert that markets breed freedom. Yet to look at the
history of freedom in western Europe is to see a continual struggle to broaden
franchises to include non-property owners, women, people of colour, and so on
that was carried out by opponents of the property-owning classes, who would
have been quite happy to keep things as they were. The growth of freedoms and
rights within the workplace are also the result of countless years of
cumulative struggle and pressure from workers. To simply say that “market
economies” provide freedoms is insufficient, because Wolf is about to argue
that we need to enlarge the scope of private industry, restrict the role of
government, and (between the lines) remove bargaining levers that workers and
the disenfranchised may have. The modern liberal democracy is the result of a
continual pulling and pushing of many forces, of which the market is only one.
Its future shape will be determined by the balance of power between all parts
of society, not by the market alone. By presenting liberal democracies as
“market economies”, as many economists do, Wolf underplays importance of those
other forces.




Wolf’s portrayal of history has other lacunae. Repeatedly he
defines one of the important roles of the state as providing security of
property rights, so that long-term contracts can be made with assurance. Yet
historically the role of the state at some crucial points in history has been
to redistribute property. The enclosure movement in the early 19th
century was an example of property rules being redefined, people being expelled
from what was previously thought of as their property, in order for the
land-owning classes to gain more land. This is not “security of property”. The
same is apparently happening in modern-day China.




Meanwhile, his view of the market portion of the economy is
rose-tinted. He is casual about many market failures (pervasive asymmetric
information problems are noted, but “Happily, there are solutions” – p 47). He
sees innovation as a function located entirely within the private sphere: “innovation
rather than price competition is the central feature of the market process” (p
51), “Innovation then does not come from outside the market. it is hard-wired
into capitalism” . In considering these claims it is worth reflecting that some
of the biggest innovations of recent years have come from national and
international government actions taking place outside the market. The
development of the Internet, surely one of the major technological innovations
of the last 50 years, is one such: the networking mechanisms, the programming
languages, and the web browsers on which it is built were developed largely in
the labs of DARPA and the NCSA in the US, CERN in Europe, and AT&T (during
the years in which it was a monopoly) in the US. The market may have helped to
bring the fruits of the developments to consumers, but it did not make the big
innovations. Yet such activities took place within market economies, and so
Wolf attributes them to the market. 




It is hardly surprising that he concludes that governments
need only provide some assurances that business as usual can take place, and
the entrepreneurs will innovate. Looking at the post-Soviet economies, one
could also argue that if entrepreneurs are to innovate rather than to plunder
the resources of their society, they must be prompted, cajoled, bribed, and
funded by the state in order to do so.




One final gripe. In these early chapters Wolf lets his lack
of respect for anti-globalization arguments come to the fore, and it doesn’t
help his case. He dismisses the protestors as “spoiled children” (p 10). He
quotes (p55) a passage from Naomi Klein’s _No Logo _(one that was also
quoted in The Economist’s review of the book) as evidence that she indulges in
“paranoid fantasies”. The quote in question starts in mid sentence, and the
implied meaning is directly opposed to the actual meaning in Klein’s book, as
she pointed out to _The Economist _when it first published the quotation.
Elsewhere (p 11) he quotes a banner from a protest march “replace capitalism
with something nicer” as an example of something that is not “the route to a
tolerable future” --- as if a banner ever captures deep or subtle thoughts.
Banners may be simple, but arguing against banners in a 400 page book is also.
This is not honest argument.




In short, while setting up his argument for the remainder of
the book, Martin Wolf paints a picture of the world that is undeniably
broad-ranging and widely read, but which remains shallow and distorted. The
positive qualities of innovation and freedom that he associates with markets
are mainly qualities of modern liberal democracies as a whole, and are
qualities with many diverse sources. The early chapters of his book are a
statement of his point of view, and interesting as such, but they are not even
handed and they are not convincing.







**Update: **[Part II](http://whimsley.typepad.com/whimsley/2006/02/why_globalizati.html) is now posted.[ ](http://whimsley.typepad.com/whimsley/2006/02/why_globalizati.html)


		
