---
author: Tom Slee
categories:
- blog archive
date: 2008-12-12 10:48:06
title: I am a Champion of Authenticity. You are in the Vanguard of Corruption.
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Here is a quandary in three parts. I don't know how to think about it clearly, much less how to resolve it.

Part 1 is a [letter](http://www.theglobeandmail.com/servlet/story/LAC.20081212.COLETTS12-15/TPStory/Opinion/letters) in today's Globe and Mail from Charles Cook:

Imagine settling down in a nice theatre
seat only to have Marge Simpson sit in front of you. Thirty years ago,
my balcony afforded a good view of Lake Ontario and the Toronto
Harbour. Gradual infill building has blocked it all but I proudly boast
of what is left, a view of the CN Tower.




With a watchful eye on high-rise projects, I got wind of a new mega
condo to be built between me and this Toronto icon. When (or now, if)
it's completed, my iconic view will be gone. New condo buyers
everywhere should not be influenced by artists' impressions of the view
from an unbuilt living room. Marge Simpson may be their first guest.

The letter writer may suffer from Marge Simpson's towering blue hairdo in front of him, but he seems blind to the fact that he is a Marge Simpson in front of someone else. And the first condo building is probably more of an issue than the hundred and first. It's a vanguard of corruption.

Part 2 is the occasional appearance of groups called something like "Artists Against Gentrification" (for Detroit see [here](http://www.flickr.com/photos/shaviro/3560458/)). It's a concept that is [easy to mock](http://www.sfgate.com/cgi-bin/article.cgi?f=/c/a/2008/01/18/DDTCUEADL.DTL). Seeking out cheap space in neighbourhoods that are not their own, yet which offer cultural novelty and distinctiveness, some artists like to think of themselves as champions of authentic neighbourhoods. Others cast them as the ground troops that come in first, paving the way for upscale developers.

But part 3 is more difficult for me to mock. The place I work is in a "Research and Technology Park" at the north end of the University of Waterloo ([here](http://www.uwrtpark.uwaterloo.ca/index.html)). It's a recent development; it has a handful of new office buildings surrounded by empty fields and untended scrubland. Sometimes I walk to work through this scrub and it's amazing what you see. We have foxes, deer sometimes. The other day a hawk flew across the path ten feet in front of me at knee hight, driving a flock of pigeons into the air. There's sometimes a blue heron in a gravel pond, and a groundhog I see regularly as it watches the construction of a new building from just outside its hole. 

All this wildlife in the middle of town would vanish, of course, if the R&T park gets more tenants, or if the scrubby landscape is manicured to look more attractive. I would miss it and something valuable would be lost. 

Yet of course I'm only aware of these gems because I work in the first building to be built in the park. I'd like to think I'm a champion of authenticity, but I guess I'm just in the vanguard of corruption.

The quandary is obvious. There are parts of the world ("authentic" parts) that have value because they are different from their blander surroundings. And yet the value of those parts is largely invisible, and so they are vulnerable to the economic forces that would brush them aside. Preserving these authentic parts of the world requires that we know about them, and that requires someone from the outside to go in and tell us about them. So is that person then selfishly trying to preserve a private playground or nobly trying to preserve a valuable but vulnerable niche?

It's the problem with eco-tourism that the more it seeks to create awareness of the wilderness the more it damages that wilderness. From quaint pottery shops in Burnsall and Grassington, to hippies in Goa, to Jane Goodall and David Attenborough, how do we distinguish the genuine champion from the tourist? And how do we preserve what needs to be preserved without pandering to the demands of those who want to just keep a new find all to themselves in the name of authenticity.

I can think of no general principle to tell one from the other. But if anyone has pointers to ways of thinking about authenticity I'd like to hear them.


		
