---
author: Tom Slee
categories:
- blog archive
date: 2011-09-02 16:25:51
title: Two Digital Fallacies
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

The first is what I call the _Long Tail Fallacy_. It goes like this:






  1. Look on the shelves of a big chain bookstore or music store. It's  mainly mainstream stuff. Boo. 


  2. Look at the variety at Amazon or iTunes. Hooray! 


  3. Isn't it great how the Internet has liberated us from the tyranny  of physical shelves and geography? 




Did you see the switch? Here it is again. Watch closely.






  1. Look at what was on mainstream network TV decades ago. Not much. Boo. 


  2. Look at all that variety on YouTube. Hooray! 


  3. Isn't it great how the Internet has liberated us from the tyranny  of mainstream media? 




See how I did that? Or again, this time from _Digitally Enabled Social Change_ by Jennifer Earl and Katrina Kimport (p91).






  1. Look at offline rallies as reported by the New York Times. Only big  and complex protest events. Boo. 


  2. Look on the Internet. Online petitions, campaigns to save TV shows,  all kinds of actions. Hooray! 


  3. Isn't it great how the Internet has unleashed a torrent of activism  among the population? 




I think of the second as the _Christmas Fallacy_:






  1. Publishing used to be expensive. 


  2. Now it's cheap. 


  3. We have an abundance of publishing! 




Seems reasonable enough? What about this:






  1. Christmas comes but once a year. 


  2. I wish it could be Christmas every day. 


  3. We'd have an abundance of Christmas! 




We wouldn't, of course. We'd have no Christmas at all.


		
