---
author: Tom Slee
categories:
- blog archive
date: 2007-01-23 13:44:42
title: Grumpy employees are productive employees
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I love this article. Jennifer Wells in the Toronto Star interviews Jing Zhou, of Rice University. Wells' article [When negative thinking is job 1](http://www.thestar.com/columnists/article/173194) is about the paper "When job dissatisfaction leads to creativity: Encouraging the expression of voice".

<blockquote>**M**onday,
Monday. Can't trust that day. You know what we're talking about. The
work week commences and finds you in a bad mood. Attitude? Negative.
> 
> Well
here's something to buoy dyspeptic workers. According to Jing Zhou – a
professor of management at Rice University in Houston and co-author of
a new research paper on job dissatisfaction – grumpy employees can be
forces of good within an organization.
> 
> That perpetually peppy co-worker of yours? Vastly over-rated.
> 
> 

> 
> **Let's
begin with the long-held assumption that a high level of job
satisfaction contributes positively to organizational effectiveness.
You call that an "intuitively appealing link." Has there been no
empirical research to support this assumption?**
> 
> 

> 
> People in our
field, when you see things like this, you do something called a meta
analysis... Taken as a whole, 100-something studies. What do they tell
us? What's the general conclusion? That's why we say when we look at a
meta analysis result... the relation between job satisfaction and
effectiveness is not there.
> 
> 

> 
> **Yet the image of the happy, smiling employee persists as the standard for good employee behaviour does it not?**
> 
> 

> 
> A
lot of those things are our perceptions and are not supported by the
data. Lots of times when people are really happy, co-operative, things
like that, I think they would be very beneficial for a company if the
company wants people to do exactly what they are told. You know, the
routine kind of tasks... But tasks are complex in today's competitive
environment, so they need to be able to think.
> 
> 

> 
> **You sampled 149
employees and found something quite surprising: those with high job
dissatisfaction exhibited the highest creativity. How do you explain
that****?**
> 
> 

> 
> This is so unconventional, it was scary to begin
with because you know we thought we are kind of arguing against the
majority. But if you look at the whole thing it makes sense, because
these are the employees whose job was not research and development. So
they go to work not thinking "I'm going to be creative today." They
only become creative when they're dissatisfied with something and try
to find a solution to it.
> 
> 

> 
> **So the bad-mood employee can work as a change agent, in a positive way, within a corporation**.
> 
> 

> 
> Exactly,
because they see problems, whereas those who are very happy and
content, the people who are always, you ask them, "Are you satisfied
with your job?" "Yes." "Are you satisfied with your work environment?"
"Yes. I'm happy with everything. I don't see problems." Therefore they
don't try to find new ideas to solve problems.
> 
> 

> 
> **So it is the miserable employee who may have come up with new and better ways of doing things**.
> 
> 

> 
> We
want to be a bit careful with the "miserable." I know it's exciting to
use those extreme words. When we say "bad mood," this is within the
typical normal range of peoples' negative emotion. We're not suggesting
that those are clinically depressed people... We're suggesting the
source, the source that triggers the bad mood, is probably that people
were not happy with how things are run in the workplace. So if
companies are sensitive to that and capture that negative energy early
they probably can channel that into... an effort to find a good idea, a
new idea to solve problems. 
> 
> 

> 
> **I'm sensing management resistance to this idea**.
> 
> 

> 
> Yeah. Yeah. Sure. Absolutely... A lot of managers who are leaders act on conventional wisdom, not on what is right.
> 
> 

> 
> **You are not, in fact , suggesting that bad moods _necessarily_ lead to creativity in the workplace**. 
> 
> 

> 
> No that's not what we're suggesting.
> 
> 

> 
> **Under which conditions can job dissatisfaction lead to positive outcomes****?**
> 
> 

> 
> If
you have a culture that supports innovation, if you have a supervisor
or co-worker who provides developmental feedback, to focus the person
who's in a bad mood, focus the person's attention to discovering
problems, improving things. That would help. From the person's
perspective... lots of people when they're not happy they just get up
and leave. The person would need to feel somehow that it's hard to
leave. We call that continuous commitment. Somehow it's hard to leave
and you're almost forced to try to make things better.
> 
> 

> 
> **I was
particularly struck by this sentence in your paper: "When employees
respond to job dissatisfaction with loyalty, they are, in essence,
burying their heads in the sand and carrying on as if everything were
fine despite their discontentment." Can you expand on that?**
> 
> 

> 
> If
they are loyal blindly... If they already see a problem but for
whatever reason they feel to be loyal is to pretend there's nothing
wrong. That would be horrible for the organization... Managers who
don't want to hear different opinions will reward yes men and yes women
in the workplace. So some employees have learned not to rock the boat,
not to say anything that the leaders don't want to hear, even when they
see problems. In that kind of culture and environment, they won't be
creative. They'll just pretend nothing is happening.
> 
> 

> 
> **So an
active response to the unhappiness is needed on the part of the
employee as opposed to passivity, or quitting. You encourage the
"expression of voice." What do you mean by that?**
> 
> 

> 
> By
voice we mean... they need to be able to speak up. Something is not
right here. The way we're doing things is no longer effective. Let's
find a new and better way of doing it.
> 
> 

> 
> **What can organizations do to encourage this untapped creativity****?**
> 
> 

> 
> First
of all they need to have a new mindset. This is what we're trying to do
in this stream of research. To realize that creativity is not just a
job for R and D people. It's a job for everyone... Once the top
management has this mindset, then they can do things we're suggesting
in our research, such as encouraging people to provide feedback,
provide a culture that will support innovation and provide the climate
where people... try to make a change for the better.
> 
> 

> 
> **Companies have a knack for placing non-risk-taking, non-creative types in management positions**. 
> 
> 

> 
> Exactly. 
> 
> 

> 
> **What then must be done****?**
> 
> 

> 
> Well,
either they do something now or be forced to do something by the
external environment. You know what I mean. If they cannot make a
change on their own terms, the competition will force them to... So
they need to either go through training or somehow change the way
leaders are developed and promoted to find and promote and select
leaders who do have this healthy dose of risk-taking mindset.
> 
> 

> 
> **I feel it's time to tell my manager to embrace my sour moods. Is there a particular strategy you would recommend****?**
> 
> 

> 
> First
of all, this research is about changing the conventional wisdom. So
they need to be aware this is based on scientific research. They need
to know this data comes from very vigorous research. Second, I think
today's managers are so busy, running the processes of meetings and
stuff like that, they lose the personal touch. I say, how about an
informal conversation? How about taking someone to lunch? Why can't a
manager engage in those personal touches?
> 
> 

> 
> **Perhaps I could simply pass along a copy of your research paper**.
> 
> 

> 
> Sure, that would help. I guarantee it.
> 
> </blockquote>


		
