---
author: Tom Slee
categories:
- blog archive
date: 2009-07-19 11:37:46
title: 'Wikibollocks: Lawrence Lessig/Kevin Kelly Edition'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::


I don't usually read _Wired_ so I didn't see Kevin Kelly's article called "[The New Socialism: Global Collectivist Society is Coming Online](http://www.wired.com/culture/culturereviews/magazine/17-06/nep_newsocialism?currentPage=all)". I didn't miss much. It was a precis of Clay Shirky's book _Here Comes Everybody_ (my views on that are [here](http://whimsley.typepad.com/whimsley/2008/04/here-comes-ever.html)), about how the Internet is dramatically enhancing our abilities to cooperate, collaborate, share, join and do all kinds of groupy things, prefaced by a few paragraphs in which he tried to claim that this groupiness is "socialism". In that it's social, or something. KK doesn't really care if it's socialism or not of course, but using the word in the pages of a Condé Nast-owned publication sounds daring and provocative, so why not? And what else would you expect from someone who calls himself "Senior Maverick at _Wired_ Magazine" [[link](http://www.kk.org/biography/index.php)]? (In the comments section of the first link of the following paragraph, Seth Finkelstein says all this more energetically.)

Law professor Lawrence Lessig [took](http://lessig.org/blog/2009/05/et_tu_kk_aka_no_kevin_this_is.html) [umbrage](http://lessig.org/blog/2009/05/on_socialism_round_ii.html) at the dread word, because "at the core of socialism is coercion" so "I will never agree to call what millions have voluntarily created on the Net 'socialism.' That term insults the creators, and confuses the rest." I didn't read his posts when they first came out either, so I missed the sentence "No one forces Wikipedia editors to build a free encyclopedia", which is close enough to a certain book title to catch my eye.

But I did see Henry Farrell's [fine post](http://crookedtimber.org/2009/07/07/the-left-that-dare-not-speak-its-name/), calling Lessig's arguments "a horrible, _horrible_ mess":

<blockquote>"Item one: under Lessig’s definition, when the Young Socialists League of the Socialisty Socialists of America organizes its volunteer commune in Ann Arbor, this commune isn’t a socialistic one, because no-one is being forced to join. Item two – that if you are to deplore your critics for having mysteriously misinterpreted you as associating coercion with Stalin, you probably shouldn’t have been arsing on about Stalin, collective farms _und so weiter_ in your original post. This class of rhetorical maneuver is what we call running with the hare and coursing with the hounds in the country where I grew up."
> 
> </blockquote>

This sent be back to the original articles, which I read with increasing irritation. I'm eagerly awaiting Henry Farrell's promised longer post on the subject, but there's no sign of it yet. So as a substitute here's what gets me pissed off about the Lessig/Kelly debate.

It's not what they disagree about that annoys me. Is this socialism or is this just love? At some point the label doesn't matter: you say tomayto and I say tomahto, a rose by any other name, sticks and stones, etc.

No, it's what they agree on that drives me spare. The idea that the technological innovation surrounding the Internet is a transformative social movement and, what's more, a political movement in the broad sense. LL and KK ascribe explicit political consequences to open source software, the hacker ethos, Wikipedia, and so on. They adopt and share with others an implicit belief in technological determinism, in which new technology is inherently linked to a particular kind of progressive and liberating social change. Clay Shirky is another who looks at the world this way:

<blockquote>"The internet’s output is data, but its product is freedom, lots and lots of freedom. Freedom of speech, freedom of the press, freedom of association, the freedom of an unprecedented number of people to say absolutely anything they like at any time, with the reasonable expectation that those utterances will be globally available, broadly discoverable at no cost, and preserved for far longer than most utterances are, and possibly forever." [[link](http://many.corante.com/archives/2007/07/09/andrew_keen_rescuing_luddite_from_the_luddites.php)]
> 
> </blockquote>

KK calls the development of open source and social software "an alternative to capitalism and corporatism", and LL sees the debate in explicitly political terms:

<blockquote>... sloppiness here has serious political consequences. When a founder of the movement which we all now celebrate calls this movement "socialist," that plays right in the hand of those would attack everything this movement has built.
> 
> </blockquote>

Here's the problem.

This rhetoric of liberation has led many a talented and idealistic young person to believe that coding, especially for free, is a political statement. In the guise of an anti-establishment, scrappy, can-do underdog attitude, LL, KK and their colleagues have created an environment in which well-intentioned people really believe that the commercialization of friendship by Facebook is a democratizing force, that it's progressive for technology entrepreneurs to make billions from the work of artists who get nothing, and that posting book reviews on Amazon and movie reviews on Amazon-owned IMDB is contributing to a public good. In which otherwise intelligent people believe that Google and Twitter are somehow morally different from Microsoft and Wal-Mart because their employees are younger and because they use phrases like "radical transparency" without living up to them.

Some of those young people have created great things. Others have been suckered into digital sharecropping efforts believing that they are doing something worthwhile, painting a fence for some Tom Sawyer with a venture capitalist behind him who makes a mint off their efforts. And others have become those rich young men (almost always men) with their private jets. As Time Magazine wrote in its portrait of Flickr founders Caterina Fake and Stewart Butterfield: "IPOs? Web 1.0. Building it and flipping it to Yahoo, Google or Microsoft? Web 2.0".

So let's get some things clear.

- The Internet doesn't have one product, it has many products. Some of which are wonderful and some of which are politically reactionary. It has produced some admirable and exciting cultural innovations, and it has also led to a huge influx of money to the pockets of Silicon Valley billionaires and away from proprietors and employees of small-scale, independent outfits that are vital to our cultural health.

- The Internet is not inherently anti-corporate and it is not anti-state. If you want to be part of an anti-corporate movement, simply doing your digital thing is not enough.

- Google is not an upstart. Anyone who can read [their statement](http://www.billboard.biz/bbbiz/content_display/industry/e3i5da91363c00f697e2b83e6d4e7c17ece) about making YouTube profitable and still think Google is run by coders, not bean counters, is kidding themselves.

- The open source "movement" is not a political movement and open source is not a political virtue. Open source is perfectly compatible with businesses as conservative as they come. The largest death machine on the planet has its own open source initiative [[link](http://news.cnet.com/8301-13505_3-10037544-16.html)]; anything key to IBM's strategy is not an alternative to capitalism. Of course, Google says that in building its new Chrome OS on top of Linux "We have a lot of work to do, and we're definitely going to need a lot of help from the open source community to accomplish this vision" [[link](http://googleblog.blogspot.com/2009/07/introducing-google-chrome-os.html)]. So go ahead, help them, but don't think you're doing something progressive.

- I'm not saying that the Internet is inherently reactionary, any more than it is inherently progressive. Political activists are spending a lot of time building digital tools to help maintain movements and promote worthwhile causes, to promote worthwhile goals, and these are useful activities. Even I use Drupal and CiviCRM for groups I am a member of. But let's not think that these tools make this generation of activists materially different from previous generations. Elsewhere on this blog Phil Edwards (blog [here](http://gapingsilence.wordpress.com/)) relayed a question he asked John Curtice: "has pervasive Internet access been a force for good in terms of expanding participation, i.e. were people who wouldn't previously have been informed & involved using the Net to get informed & involved? His answer was, um, no, not really - political activism was a minority pursuit & always had been, and the Net hadn't made it any less of one. Afterwards I asked the Shirky/Howard Dean question - had the Net been a negative influence, in that the frictionless ease of Net activism actually attracted people away from real-world politics? His answer was, um, no, not really - political activism was a minority pursuit & always had been, and in all probability the same minority were going to the physical meetings and joining the Facebook groups" [[link](http://whimsley.typepad.com/whimsley/2008/10/wikibollocks-tapscott-on-young-voters.html#comments)].

Somehow the digirati choose to ignore the fact that the major media corporations they love to knock are doing just fine in the brand new world of the Internet - but then a Condé Nast publication may be expected to believe that. LL's talk of a "hybrid economy" is filled with optimistic assumptions about the behaviour of the new corporations and breezy acceptance, even approval, of the fact that his young children's everyday social interactions are now a legitimate target of advertisers. Even when a cool kid shows signs of disillusionment, as Boing Boing's Cory Doctorow did recently, he wraps his claims in qualifiers:

<blockquote>I sympathize with companies and creators who want to keep Google or Amazon from becoming gatekeepers on culture. Not because of who runs Amazon or Google -- I know senior people at both companies whom I believe to be honorable and decent -- but because no one should be that gatekeeper. I'd oppose consolidation in distribution and sales channels, even if the companies involved were Santa Claus Inc., Mahatma Gandhi Ltd., and Toothfairy Enterprises LLC. [[link](http://www.internetevolution.com/document.asp?doc_id=178058)]
> 
> </blockquote>

Cory - you're on the right track, but why would you think that the character of the people you know matters a damn? It certainly sounds like you think the "honorable and decent" nature of people at Google and Amazon ameliorates the impact of those companies. The problems with the mainstream institutions you have so little time for are nothing to do with levels of honour and decency among their senior people. This is not a matter of good guys and bad guys. As someone who knew a bit about socialism once said "In the social production of their existence, men [and women too] inevitably enter into definite relations, which are independent of their will, namely [the] relations of production appropriate to a given stage in the development of their material forces of production."

I'm not anti-technology. But it's time to think about the Internet and digital technology in the same way that we think of the road system or other pieces of our social infrastructure. It would be ludicrous to claim that roads have one product. I just watched my son drive off with a car full of friends to a weekend at a cottage - a form of freedom possible only because of the technology of the road. But I worry a little, as any parent does, because roads are dangerous places too (as a scar on forehead from when I was eight years old reminds me). Few people are pro- or anti-road in general any more; instead the interesting questions are about how to make the most of the benefits roads can bring and how to limit the damage they can cause. The same goes for the Internet: let's not assume its progressive nature, let's not assume that everyone working in an open source manner or building new technologies is somehow on the same side, let's appreciate those who are building progressive spaces on the Internet because they are progressive spaces, not because they are on the Internet.
