---
author: Tom Slee
categories:
- blog archive
date: 2005-12-07 09:05:23
title: Who shops with an eye to the big picture?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Two-thirds of the way down the oddly-named Lionel Shriver's column "[Nativity scenes are out, carols are banned, and don't dare wish anyone merry Christmas: the festive season, US-style](http://www.guardian.co.uk/Columnists/Column/0,5673,1660576,00.html)" is some interesting stuff about how freely-made consumer choices takes us to places we don't want to be. She writes it well, as you would expect from the author of "We Need to Talk About Kevin".


<blockquote>**Books make good gifts this year,** since discounts offered by UK chains are now as drastic as 50%. But don't imagine that high-street behemoths alone are sacrificing for the affordability of your winter presents. Publishers are out of pocket, as are authors like me. Discount deals in trade for volume are not yet as unsustainable as in the dairy industry; the 17p per litre that supermarkets pay for milk is often less than it costs to produce. But publishing has become less profitable, and so has writing books.

> 
> 

> 
> I don't know what the answer is. Wal-Mart-writ-large seems the natural end point of capitalism, which thrives on economies of scale. With the clout to demand rock-bottom prices from suppliers and pass the savings to customers, big fish eat little fish until the commercial ocean floats only a few whales. Hence the local greengrocer gives way to Sainsbury's, the family-owned hardware store to Home Depot, the independent bookseller to Waterstone's (now mounting a take-over bid for Ottakar's). Alan Bennett's appeal to buy his book from independents is laudable but unrealistic. I can't ask prospective buyers of my own novels to pay full-price, when I purchase most books on Amazon myself. Aside from a few toffs who spurn the ambience of the cut-rate, we're all going to buy our milk, nails, and hardbacks where they're cheapest.
> 
> 

> 
> In the big picture, everyone is the poorer when producers and employees are low-balled, and thus pump less money into the economy. But who shops with an eye to the big picture? In the short-term, Wal-mart employees are so poorly paid that the only place they can afford to shop is Wal-mart.
> 
> </blockquote>

This is pretty much exactly the argument I make in [Chapter 1](http://www.tomslee.net/excerpt.html). If we don't want to end up with nothing but Wal-Marts, we need to take collective action, not individual action.


		
