---
author: Tom Slee
categories:
- blog archive
date: 2010-12-05 21:05:12
title: WikiLeaks Shines a Light on the Limits of Techno-Politics
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

The [hacker ethic](http://en.wikipedia.org/wiki/Hacker_ethic), [open source](http://en.wikipedia.org/wiki/Open_source_movement), [open government](http://en.wikipedia.org/wiki/Open_government), [radical transparency](http://www.wired.com/wired/archive/15.04/wired40_ceo.html) and [mass collaboration](http://en.wikipedia.org/wiki/Mass_collaboration): all these ideas are linked by a belief that the Internet will promote  non-hierarchical organization, decentralization, “democratization”,  openness and sharing. A  side effect of the WikiLeaks cables is to show  that, for all the talk of movements and revolutions, these beliefs are  empty of real political content. The cables prompt some tough questions,  but the fault lines those questions reveal run perpendicular to digital  attitudes, not parallel. When push comes to political shove, open  source proponents and so on are found on both sides of the debate. The  Internet is a new terrain, but the battles being fought on it are old  ones.  
  
For  example, Open Government advocates are one group having a tough time  reacting to the leaks, and their struggles show that the real issues are  not the open source/hacker technological questions of openness, access  to data, and transparency, but the old political question of “US foreign  policy, for or against?”  
  
“Is WikiLeaks open government?” [asks](http://gov20.govfresh.com/is-wikileaks-open-government/) O’Reilly’s Alex Howard, but he doesn’t answer his own question. Tech President’s Nancy Scola [writes](http://techpresident.com/blog-entry/what-wikileaks-means-open-government) about “What WikiLeaks Means for ‘Open Government’” and also avoids  coming down on for or against WikiLeaks. In typically gnomic fashion,  Tim O’Reilly stays firmly on the fence, [tweeting](http://twitter.com/#%21/timoreilly/status/8943982939738113) that WikiLeaks neither champions nor defies open government, instead it  “*challenges* [open government government 2.0] philosophy. Challenges  are good if we rise to them.” Whatever that means.  
  
Of those who do take a position, some believe that WIkiLeaks is bad for open government ([here](http://govinthelab.com/wikileaks-is-a-blow-to-open-government/), [here](http://anthonydwilliams.com/2010/11/29/could-wikileaks-set-back-open-government/) for just two) and others (fewer, from what I can see) that it is good.  
  
The  internal struggle highlights an emptiness at the heart of the Open  Government idea. It is based on the idea that more data available to  more people will make government work better, either by improving  efficiency and access (Open 311 etc) or by highlighting particular  problems (maplight.org and so on), or perhaps both. But while WikiLeaks  is making more data available to more people it has no interest in  making the US government work better: quite the opposite. As Assange’s [writings](http://cryptome.org/0002/ja-conspiracies.pdf) and [this](http://zunguzungu.wordpress.com/2010/11/29/julian-assange-and-the-computer-conspiracy-%E2%80%9Cto-destroy-this-invisible-government%E2%80%9D/) widely linked essay by Aaron Bady make clear, WikiLeaks is using  information exposure to put sand in the gears of the US State  Department.  
  
There  is one agreement among Internet/Open Government supporters, which is  that the cables highlight excessive government secrecy, and that it  shows us that government should be more open to start with. From  Australia, Stephen Collins [admits](http://www.acidlabs.org/2010/11/30/open-government-in-a-wikileaks-world/) that “there’s an uncomfortable feeling in the open government world at  the moment,” but goes on to argue that “phe­nom­ena such as Wik­ileaks  are a symp­tom,  rather than the dis­ease itself. Wik­ileaks exists because of the  fail­ure of governments around the world to operate openly enough  through­out their his­tory.” Jeff Jarvis [makes](http://www.buzzmachine.com/2010/12/04/wikileaks-power-shifts-from-secrecy-to-transparency/) the same argument, suggesting that nothing in the documents is that bad  anyway: “the revelation of these secrets has not been devastating.  America’s and Germany’s relationship has not collapsed because one  undiplomatic diplomat called Angela Merkel uncreative.”  
  
But  while there are many cables in the pile that are of no interest to  anyone and which seem to be marked as secret for no good reason, to  focus on those is to ignore the real revelations that are coming out,  day after day. The purpose of the leaks is to derail the American global  agenda - if they haven’t succeeded, they will try again.  
  
The  openness question is always contingent, and to phrase political  questions in terms of data is sidestepping the big issue. Your answer to  “what data should the government make public?” depends not so much on  what you think about data, but what you think about the government.  Everyone is in favour of other people’s openness.  
  
The  same fault lines are appearing around issues such as Amazon and  PayPal’s refusal to deal with WikiLeaks. Despite all the talk from the [commanding heights of Silicon Valley](http://www.foreignaffairs.com/articles/66781/eric-schmidt-and-jared-cohen/the-digital-disruption) about the Internet as an enabling technology for dissidents in other  countries, especially Iran and China, the enthusiasm for dissent at home  is muted. I am a dissident, you are a criminal?  
  
(If  anyone cares, my view is that the leaking of these WikiLeaks cables was  a brave act and if it damages US foreign policy in the Middle East and  elsewhere, which I think it will, I’m all for it.)


		
