---
author: Tom Slee
categories:
- blog archive
date: 2008-04-06 20:30:14
title: Here Comes Everybody
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_Here Comes Everybody: The Power of Organizing Without Organizations_, Clay Shirky, Penguin, 2008.

* * *

"We are living", says Clay Shirky, "in the middle of a remarkable increase in our ability to share, to cooperate with one another, and to take collective action, all outside the framework of traditional institutions and organizations" [p. 20]. Digital technologies are now part of our social fabric, and all "the phones and computers, the e-mail and instant messages, and the webpages are manifestations of a more fundamental shift. We now have communications tools that are flexible enough to match our social capabilities and we are witnessing the rise of new ways of coordinating action that take advantage of the change" [20].




_Here Comes Everybody _is an accessible and challenging introduction to these changes - to the many ways every Shem, Shaun and Issy can now share, collaborate, and act together. It combines some great stories with non-technical introductions to some of the key ideas (a little game theory, a little network theory, a few power laws) and is well worth reading -- but it should be read with caution.




The reason for this mixed verdict is the dual nature of the book itself. _Here Comes Everybody _has two voices. One (let's call him 'Shirky') is a perceptive and creative interpreter of the ways that digital technology is changing society. I like and respect Shirky. He is blunt and provocative enough to cut through the mess of questions that come up when tackling something as far-reaching as the Internet, while being even-handed and reserved enough to respect the complexity of his subject. Here is Shirky on the erosion of journalism and photography:

<blockquote>There is never going to be a moment when we as a society ask ourselves, "Do we want this? Do we want the changes that the new flood of production and access and spread of information is going to bring about?" It has already happened; in many ways, the rise of group-forming networks is best viewed not as an invention but as an event, a thing that has happened in the world that can't be undone. As with the printing press, the loss of professional control will be bad for many of society's core institutions, but it's happening anyway. [p73]
> 
> </blockquote>

I've struggled with this message for a few days because I don't like its determinism, but he has convinced me. Shirky separates what is happening from what is desirable (not that everything digital is undesirable) and that's an important separation to make if we are to be at all clear-headed.




Shirky is not a techno-inevitabilist in a broad sense. Nuclear power, for example, "is a technology that society can, for the moment, make a decision about" [299]. As with driving a car, we "have a good deal of control over both the route and the speed with which nuclear power progresses, including the option to simply pull over" [299]. But when it comes to digital technologies we are steering a kayak: "We are being pushed rapidly down a route largely determined by the technological environment... Our principal challenge is not to decide where we want to go but rather to stay upright as we go there." [300]




The other voice (let's call him 'Clay') is a techno-enthusiast and an inveterate story-teller. When Clay looks at the Internet he sees no reason for worry - he sees freedom and unlimited potential. It's "the largest increase in expressive capability in the history of the human race" [106], bringing with it a world in which, when "people care enough, they can come together and accomplish things of a scope and longevity that were previously impossible; they can do big things for love." [142] Shirky may warn that there are losses from social changes, but Clay is breezily dismissive: "The spread of cheap and widely available creative tools is sad for people in the advertising business in the same way that movable type was sad for scribes -- the loss from this kind of change is real but limited and is accompanied by a generally beneficial social change." [209] This is the logic of The Lottery - the short story in which one person is stoned so that others can be better off.




I blame Clay and his enthusiasms for the two major flaws of this book. 




The first is a fallacy of composition. Clay looks at the Internet and sees lots of groups forming (and things are easy to see on the Internet because even our most casual utterances get stored on someone's servers for posterity to investigate) and he concludes that the world is alight with a new groupiness, the likes of which we have never seen. From time to time Shirky pipes up to remind his alter ego that this is not enough, that "treating the internet as some sort of separate space... was part of the problem" [194]. "The internet augments real-world social life rather than providing an alternative to it" [196]. One implication of Shirky's caution is that, to evaluate the state of groups in our world, we also have to look at how our use of the Internet may have displaced other forms of group building. But while Shirky knows all about _Bowling Alone_, Clay is too busy running off to tell us a story about Meetup.com to take a really close look at how those positives and negatives are adding up. 




While Clay is telling us all about the use of digital technology to spark innovative forms of protest in Belarus, which is a fascinating story, we really need Shirky to ask why, with all these group-forming tools at our disposal and despite the documented disillusionment with the war in Iraq, there is so little coherent protest happening compared to previous wars? Is it really the case that society now is becoming, thanks to the internet, more democratic, more collaborative, and more cooperative than before? I am not convinced. Clay is in danger of making the same mistakes that William Greider made in _One World, Ready or Not_, and which [Paul Krugman demolishes](http://web.mit.edu/krugman/www/hotdog.html) - of finding lots of examples of groups and inferring that the world must have more groups in it than it used to - but that logic is flawed.  





Now Shirky is far too well-informed to fall into this kind of trap. Shirky recognizes that, just as removal of a bottleneck at one point in a highway may prompt a new bottleneck to form a few miles down the road, so the "removal of technological limits has exposed a second set of social ones" [91]. But Clay's enthusiasms mean that the book is unbalanced, and this second set of limits never really gets investigated closely. Clay the enthusiast wins out over Shirky the dispassionate observer. If you are going to argue that groups are forming as never before, and if you are going to use minor events like angry airline passengers protesting about being trapped on runways to claim that "Consumers now talk back to businesses and speak out to the general public, and they can do so en masse and in coordinate ways" [179] then you really have to think about consumer activity before digital technology. Here is "talking back to business" with a vengeance:

<blockquote>August [1800] - Notwithstanding that the last day of this month was a Sunday, it was marked as the commencement of a serious riot. A great increase in the price of provisions, more especially of bread, had roused the vindictive spirit of the poorer classes to an almost ungovernable pitch. They began late in the evening, by breaking the windows of a baker in Millstone Lane, and in the morning proceeded, with an increase of numbers and renewed impetuosity, to treat others of the same trade in the same unwelcome manner. Granaries were broken into at the canal wharfs, and it was really distressing to see with what famine-impelled eagerness many a mother bore away corn in her apron to feed her offspring. [[link](http://www.nottinghamcity.gov.uk/greensmill/shhist.htm)] 
> 
> </blockquote>

Do consumers have a stronger voice now than in the past? I don't know, but I do know that a story or two about American Airlines passengers is not going to convince me. If Clay wants to tell us about a student group using Facebook to protest about British Bank HSBC's cancellation of interest-free loans then perhaps he should think about the longstanding student boycott of Barclays Bank during the 1970's and 1980's that contributed to the end of apartheid. But he doesn't, and that's disappointing.




The second flaw - also a common one - is a reluctance to follow the money. Between them, Clay and Shirky convince me that the Internet marks a change; that a society with an Internet is different from a society without one. Also, they convince me that the Internet is not a single model of sharing/collaboration/collective action; it's many models. So let's talk about these models, about which ones have legitimacy and longevity and which don't. To do so requires Shirky to take the broad brush that Clay is using and to start to make smaller, more detailed points.




Perhaps we no longer need books telling us that the Internet is a big thing. It is time to treat that fact, as Shirky sometimes does, as the starting point for a discussion rather than the conclusion. The questions then become ones of what kind of structures will form and persist in the online world, and if you are going to talk about these questions then you have to address the economics of the problem. 




Money matters. 




People's willingness to contribute to Wikipedia, Shirky points out, is tied to the non-profit status of Wikipedia. A threat from Spanish participants to start an alternative version convinced founder Jimmy Wales to "formally forgo any future commerical plans for Wikipedia, and to move the site from Wikipedia.com to Wikipedia.org, in keeping with its nonprofit status. Similarly, he decided to adopt the GNU Free Documentation License for Wikipedia's content [which] assured contributors that their contributions would remain frerely available" [274]. There is an ongoing tension between contributors to sites and the "owners" of those sites that is visible on MySpace (see Billy Bragg's efforts to gain musicians rights over their content), on Facebook (the failed "Beacon" program as one example) and even Google and the line it walks with advertising content on its search results. Contributor-driven movie database IMDB was taken over by Amazon, but Amazon does not put its name on the pages of the site - does it fear that people would not contribute so freely if they realized they were just making Jeff Bezos even richer? The book ends with a story by Clay about a successful revolt by participants at digg.com - but once again, a story is not enough to support the thesis he is trying to make.




There are many issues of democracy, ownership, privacy and control that, depending on how they are resolved, will influence our chances of staying upright as we get carried along by this technological flood. Clay Shirky shows in this book that he has many insights that we can use, but to really help steer this kayak we need more Shirky and less Clay.


		
