---
author: Tom Slee
categories:
- blog archive
date: 2007-03-25 19:26:13
title: Tims Spey Way Challenge
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This post is for anyone who knew me from PHGS and who is as out of touch with people from school as I am.




I went to Friends Reunited for the first time in ages to look through people's entries, and was shocked to see that Tim Lester has recently been diagnosed with motor neuron disease. A couple of weeks ago he set off on a fundraising walk through the highlands of Scotland, where he now lives, so go donate at [http://www.justgiving.com/timsspeywaychallenge](http://www.justgiving.com/timsspeywaychallenge) and show your support for Tim. There's a clickable link in the right hand column of this page as well.  





Here's what he has to say at [Justgiving - Tims Spey Way Challenge](http://www.justgiving.com/timsspeywaychallenge).


<blockquote>On Wednesday 29th November 2006 I was diagnosed as having Motor Neuron Disease - www.scotmnd.org.uk . Once I had picked myself up off the floor I thought I had to do something positive and decided in a moment of lucid thought that I would walk the Spey Way and try and raise some money for charity along the way. This is one of four designated long distance footpaths in Scotland and follows the course of the great River Spey from it's source in the Cairngorms to where it enters the Moray Firth (just down the road from where we now live, see photo opposite). More information from www.speysideway.org . I probably won't be able to do a Jayne Tomlinson but as long as I can put one foot in front of the other I will keep going (and even if I have to end it in a wheelchair I will). As Motor Neuron Disease is very close to my heart I would like to raise some money for them to do more research in to this little understood disease, and also Meningitis Research. This is a charity that we have done our little bit for over the years, our son Alex having survived its' ravages at an early age, and it would be good if we could raise some funds for them too. Walking will commence on the 3rd March, and don't worry I won't be galloping to the end! Your support, both monetary and in person if you can make it this far North, would be appreciated as it would be great to share some time together on this adventure.
Donating through this site is simple, fast and totally secure. It is also the most efficient way to sponsor me: Scottish Motor Neurone Disease Association will receive your money faster and, if you are a UK taxpayer, an extra 28% in tax will be added to your gift at no cost to you.
So please sponsor me now!
Many thanks for your support.
> 
> </blockquote>

He also has a [myspace page](http://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=135598089) for the walk and there's a newspaper story [here](http://www.northern-scot.co.uk/news/fullstory.php/aid/1607/Finding_a_Way_to_take_life_one_step_at_a_time.html).




I haven't seen Tim in many years, but - if you read this Tim - when we were at school you seemed like one of the few people in our year who actually had it all together. At least, after you got rid of the Ziggy Stardust haircut. First, you had the rugby thing going. Then, you had the music thing going with Mike Parker and Jim Hogarth. And then you were dating Barbara Armstrong, who had emerged from some kind of an invisible cocoon she was hiding in for years to suddenly become attractive-and-outspoken-and-Oxford-bound Jo Armstrong. 




So you managed to be one of the cool people in school without getting an attitude about it, and always seemed just as happy to spend time with those of us who were less cool as with those who were more so. I hope you've carried on being as admirable - I'm sure you have. It's a hell of a thing to get that diagnosis, but taking on the walk sounds like just the kind of thing you'd do - no messing, getting out and do something useful. Best wishes to you in the walk and everything else, my friend. 


		
