---
author: Tom Slee
categories:
- blog archive
date: 2014-07-08 01:50:00
tags:
- airbnb
title: Airbnb in Barcelona
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				So Airbnb is in trouble in Barcelona ([Guardian](http://www.theguardian.com/technology/2014/jul/07/airbnb-fined-illegal-tourist-lets-barcelona-catalonia), [El Pais](http://elpais.com/elpais/2014/07/07/inenglish/1404733914_341057.html), [El Pais again](http://blogs.elpais.com/trans-iberian/2014/07/a-take-on-airbnb-in-barcelona.html)). The company was fined €30,000 by Catalonia's local government the Generalitat "for illegally commercializing short-stay apartment rentals that are not listed on the Catalan Tourism Register." Here are a few notes for context.

Barcelona has a particular problem with tourists: it has [too many of them](http://www.theguardian.com/travel/2014/jun/15/barcelona-tourism-boom-economy-residents). "The city's 1.6 million residents have seen the number of visitors to the city skyrocket from 1.7 million in 1990 to more than 7.4 million in 2012." As one besieged local says, "We're part of what they're selling, but they're destroying it."

Airbnb has done its usual [lightweight study](http://blog.airbnb.com/airbnb-economic-impact/#barcelona) on the city. It's interesting partly for what it doesn't say, because as a city with a highly developed tourist industry, Barcelona is a sign of what is likely to be the pattern for Airbnb for the future. So, here's a quick rundown on Airbnb's usual economy with the truth.

I actually found more hosts than the 4,000 that Airbnb claims: my recent [scan](http://tomslee.net/2014/05/the-shape-of-airbnbs-business.html) of their site picked up 6442 hosts and 11284 listings. (part of a series of studies: [here](http://tomslee.net/2013/10/notes-on-airbnbs-new-york-business.html), [here](http://tomslee.net/2013/11/airbnb-business-in-new-york-revisited.html), and also [here](http://tomslee.net/2014/06/the-shape-of-airbnbs-business-ii.html)).

Airbnb avoids its usual claim of "the overwhelming majority of Airbnb hosts in Sydney are ordinary residents who rent out the home they live in" because it's just not true. 75% of hosts rent out a single listing, which is lower than in most other cities. And the majority of Airbnb listings come from people who are renting out more than a single offering, and I estimate that over 60% of Airbnb revenue comes from multiple listers.

The idea that Airbnb is made up of hosts sharing a part of their home also fails in Barcelona. 59% of listings are "whole home", and these make up a whopping 81% of Airbnb revenue from the city.

In short, Barcelona is exactly the kind of place that needs to regulate tourism, in order to keep a balance between the income from tourists and preserving the city as a place to live, work (and visit). Airbnb is promoting its "home-sharing" story to justify its lack of interest in these regulations, but the story has even less truth to it than in New York and elsewhere.		
