---
author: Tom Slee
categories:
- blog archive
date: 2007-05-20 18:37:37
title: The liberation mythology of the internet
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Nicholas Carr of [Rough Type](http://www.roughtype.com) has been reading David Weinberger's Everything is Miscellaneous, and is disappointed. But in his disappointment he coins a phrase I really like: "the liberation mythology of the Internet".

<blockquote>I only reached the bottom of page nine, at which point I crashed into this passage about music: 
> 
> <blockquote>For decades we've been buying albums. We thought it was for artistic reasons, but it was really because the economics of the physical world required it: Bundling songs into long-playing albums lowered the production, marketing, and distribution costs because there were fewer records to make, ship, shelve, categorize, alphabetize, and inventory. As soon as music went digital, we learned that the natural unit of music is the track. Thus was iTunes born, a miscellaneous pile of 3.5 million songs from a thousand record labels. Anyone can offer music there without first having to get the permission of a record executive. 
>> 
>> </blockquote>
> 
> "... the natural unit of music is the track"? Well, roll over, Beethoven, and tell Tchaikovsky the news.

> 
> There's a lot going on in that brief passage, and almost all of it is wrong. Weinberger does do a good job, though, of condensing into a few sentences what might be called the liberation mythology of the internet. This mythology is founded on a sweeping historical revisionism that conjures up an imaginary predigital world - a world of profound physical and economic constraints - from which the web is now liberating us. We were enslaved, and now we are saved. In a bizarrely fanciful twist, made explicit in Weinberger's words, the digital world is presented as a "natural" counterpoint to the supposed artificiality of the physical world.
> 
> </blockquote>

  



There's much more at Rough Type, as Carr [demolishes](http://www.roughtype.com/archives/2007/05/long_player.php) Weinberger's claim.


		
