---
author: Tom Slee
categories:
- blog archive
date: 2007-01-07 20:03:45
title: 'Bouquests & Brickbats: David Olive'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

A bouquet, not a brickbat, for Toronto Star Business Columnist David Olive, who has had a mighty busy New Year by the looks of things. Not only does he have four columns in today's Sunday Star - two on the hanging of Saddam Hussein, one on the $210 million parachute for Robert Nardell on resigning from Home Depot, Inc, and one   
response to letters on an earlier column, but he also has a long piece in [This Magazine](http://thismagazine.ca/) on Red Toryism.




I've enjoyed David Olive's writing for a long time. He's not particularly left-wing, but he does have a strong sense of social justice, and -- unusually for a business columnist -- it comes through in his business writings. He's done sterling work over the years reporting on CEO salaries, for example. He's careful with his facts, writes clearly, and makes strong points in a thoughtful manner. We could do with more journalists like him.




Link: [TheStar.com - Business - A $210 million parachute](http://www.thestar.com/Business/article/168599).


		
