---
author: Tom Slee
categories:
- blog archive
date: 2009-07-03 22:47:05
title: Googling Barbie Again
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

My writer's block has writer's block. Still, I don't want this place to be abandoned completely so I'm going to revisit an oldie but goodie: what do you see when you google barbie?  
  
Yochai Benkler made a big deal of the Google search results for Barbie in his book _The Wealth of Networks_ (2006), where he claimed that, whereas other search engines gave you only sales-related Barbie sites in the top ten, Google's "radically decentralized" algorithm revealed an entirely different picture of Barbie. "The little girl who searches for Barbie on Google will encounter a culturally contested figure. The same girl, searching on Overture, will encounter a commodity toy".  
  
But that was in 2006. Since then things have changed in the google-sphere. I posted about this 18 months ago in [Barbie slinks back to the confines of feminist-criticism symposia](http://whimsley.typepad.com/whimsley/2008/01/barbie-back-to.html). Here were the Google first page results from 2006 as reported by Benkler:  
  
barbie.com  
Barbie Collecter  
AdiosBarbie.com  
Barbie Bazaar  
If You Were a Barbie, Which Messed Up Version would you be?  
Visible Barbie project (macabre images...)  
Barbie: The Image of us all (1995 undergraduate paper)  
Andigraph.free.fre (Barbie and Ken sex animation)  
Suicide bomber Barbie  
Barbies (dressed and painted as countercultural images)  
  
and here were the results in January 2008:  
  
Barbie.com - Activities and Games for Girls Online! (together with eight other links to My Scene, Evertythingggirl, Polly Pocket, Kellyclub, and so on).   
Barbie.co.uk - Activities and Games for Girls Online!  
Barbie - Wikipedia, the free encyclopedia  
Barbie Collector - (The official Mattel site for Barbie Collector)  
Barbie Girls  
Mattel - Our Toys - Barbie  
The Distorted Barbie  
YouTube - barbie girl - aqua  
Barbie - Barbie Dress up - Fashion for Barbie  
Barbie.ca  
  
and I concluded that "this search is basically owned by Mattel. Clicking the top link takes you to a pink page with "Think Pink" written in the middle of it, and the majority of the sites feature pink prominently. No more defining the cultural symbols of our day for you, nine-year-old girl! Quit the self-aware political discourse and get back to dressing that doll in gender-appropriate colours (as selected for you by Mattel)."  
  
Every now and again I [google barbie ](http://www.google.ca/search?q=barbie)and see what's changed as the Google search engine becomes more elaborate. So here are today's results (from southern Ontario).  
  
Barbie.com - Activities and Games for Girls Online! (together with eight other links to My Scene, Evertythingggirl, Polly Pocket, Kellyclub, and so on).   
Barbie.com - Fun and Games  
Barbie - Wikipedia, the free encyclopedia  
News results for barbie (with several other links)  
Barbie Collector - (The official Mattel site for Barbie Collector)  
Barbie.co.uk - Activities and Games for Girls Online!  
 Barbie.ca  
Barbie Girls - and a sublink  
Celebrate 50 Years of Barbie  
Video results for barbie - with two links to Aqua's Barbie Girl video  
Searches related to barbie - all strictly orthodox except for one about Taiwanese actress and singer Barbie Xu.  
  
Yes, the little girl who searches for Barbie on Google will now encounter a commodity toy.  
  
The one big change in the last 18 months is that the remaining countercultural site from 2008 has now been pushed over the edge to page 2 of the search results, displaced by two Google-owned collections of links (News and Videos). I'm sure you've seen this in your own searches. Google presents more links on and around the "top ten" results, in "related searches", and in collections of video, news, and image links. One effect of this change is that Google now often gets one more click from you before you leave their domain. Google is extending its role from pointing you vaguely towards your destination to guiding you more precisely, and more profitably, all the way along the path.  
  
Of the other top-level links, seven are owned by Mattel (Two to barbie.com, Barbie collector, Barbie Girls, barbie.co.uk, barbie.ca, Celebrate 50 years of Barbie) and the remaining link is to Wikipedia, now the only non-commercial site on the front page. Following [Nick Carr's informal experiment](http://www.roughtype.com/archives/2009/01/all_hail_the_in.php) we may have expected Wikipedia to move even higher in the results, but it has just held its place.   
  
Independent sites are out there in their millions of course, but they are unfortunately being pushed to the periphery of our field of vision by commercial efforts - of Mattel in this case. It should be no surprise that as the web has become mainstream, and as corporations realise the necessity of investing in their web presence, the web begins to look more like other mainstream media. Perhaps more evidence that the Web's counter-cultural moment is over.  


<blockquote></blockquote>

  
  



		
