---
author: Tom Slee
categories:
- blog archive
date: 2006-10-24 23:08:24
title: Book Review at Stumbling and Mumbling
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Chris Dillow at Stumbling and Mumbling writes a [very generous review](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2006/10/noone_makes_you.html) of _No One Makes You..._ Good reviews mean more the smarter the reviewer, so this is very good indeed.




But the trouble with smart reviewers is that they spot those parts of an argument that you skate around, unsure of how thick the ice is. And while Chris is kind enough to call them "quibbles" his points are good ones. I know it's Not Done to comment on reviews, but maybe I'll make an exception here.




First, he wonders how widespread the market failures I describe are. I don't know that there is a way to answer this question. A market failure does not always reveal itself in any obvious way. When eminent economists find it difficult to agree even on such empirical questions as "[is inequality increasing in the USA](http://whimsley.typepad.com/whimsley/2006/07/inequality_i_ch.html)", I don't know whether we'll see an empirical answer to the prevalence of market failures. And the costs of overcoming asymmetric information problems are sometimes hard to spot because there are so many different mechanisms. But there are a couple of observations that I can make:




  * The broader view you take of a market -- that is, as you move away from the purely monetary & private aspects of a transaction to take account of other factors such as status, norms, social impact -- the more externalities come into play, and so the more common failures will be. That is, economists themselves will see only a small part of the failure of markets - others, such as [sociologists](http://whimsley.typepad.com/whimsley/2006/08/economists_and_.html), will see more.


  * There are some industries that are almost exclusively devoted to correcting market failures, and so their costs could be seen as a measure of market failure. Advertising (large-scale at least, not classifieds) and law spring to mind. And it is important to note that just because information asymmetries can be overcome at a big cost doesn't mean the problem is solved.



His second point is about Hayek, whom I've never read much of. The bits I have always seemed to be talking about a reality I didn't recognize. So I can't really address the point, and will go and read. Mea culpa.




But the third point Chris makes, which is that I don't say much about government failure, I do have an excuse for. Basically, it seemed to me that no one needs much convincing these days that governments can, left to themselves, screw things up pretty badly. You only have to read EMT Tom Reynolds [writing about government targets](http://randomreality.blogware.com/blog/_archives/2006/10/24/2437110.html) today to know that (although, come to think of it, the idiocies he describes are rife in private industry too). Cynicism about politicians and governments is so widespread that the point about bureaucracies hardly needs to be made. What is important is to tackle this idea that markets are a fine alternative.




Well, these scribbles hardly do justice to the points, but that's all I've got this evening. Thanks again to Stumbling & Mumbling for the review.


		
