---
author: Tom Slee
categories:
- blog archive
date: 2013-06-12 16:43:17
title: 'Open Wide: Me at The New Inquiry'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				I am thrilled to have [an essay](http://thenewinquiry.com/essays/open-wide/) at [The New Inquiry](http://thenewinquiry.com/), a great publication that usually features really provocative writing from people who are half my age and twice as well-read.

The essay is called [Open Wide](http://thenewinquiry.com/essays/open-wide/) and is about the difficult relationship between commons and private capital, particularly digital commons. It was inspired by David Harvey's 2012 book of essays [Rebel Cities](http://www.versobooks.com/books/1411-rebel-cities); Harvey doesn't talk about digital commons at all, but he has a lot of enlightening things to say about urban commons. While he sees commons as "spaces of hope for the construction of... a vibrant anti-commodification politics", Harvey is far more hard-headed than most about the challenges that face commons-based production and about the effects that private capital can have on commons. Much of what he had to say has clear implications for the world of digital production, where leading thinkers have systematically ignored the issues Harvey raises.

The New Inquiry publishes challenging and difficult pieces, and this is not a particularly easy read: an attempt to be theoretical and literary at the same time. I owe a particular debt to [Rob Horning](http://thenewinquiry.com/author/rob/), whose editing made a huge difference: any bite and focus that it has is due largely to Rob's engagement. Faults and errors are, of course, my own.		
