---
author: Tom Slee
categories:
- blog archive
date: 2013-03-15 18:19:05
title: 'FutureEverything: Notes Against Openness'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				I'm really looking forward to being part of [FutureEverything](http://futureeverything.org/) in Manchester next week, where I'll be a panellist at [Open Data Manchester](http://opendatamanchester.org.uk/2013/02/27/open-data-manchester-special-the-promises-and-perils-of-open-data/) on Tuesday and at [Policies and Politics of Open Data](http://futureeverything.org/summit/conference/sessions/policies-politics-of-open-data/) on Thursday. Each event starts with five-minute lead-ins from the panel members. Some of the panellists are real experts who know more than I do about open data, but "in for a penny, in for a pound": so on Tuesday I'll use my five minutes to argue against standards (and especially universal standards), and on Thursday I'll argue that openness is an idea that has outlived its usefulness.

Here are notes for Thursday's opening remarks, which will be familiar to regular readers. I think I'll have to cut them down a bit for time.



* * *



We all know that the ideas and actions around "Open Government Data" have created a very wide umbrella that covers many different agendas. It covers civil liberties campaigners, civic activists, startups, politicians from across the political spectrum, and major international corporations. And we all know that those agendas and groups are a bit uncomfortable being in such close proximity. But like "freedom", "openness" is something that everyone can agree on, and it's served to paper over the cracks between these disparate interests.

Unfortunately, it looks to me increasingly as if the language of transparency, the language of non-commercial civic engagement, and the romantic language of rebellion are being used to provide an exciting and appealing facade for an agenda that has nothing to do with transparency, nothing to do with civic participation, and a lot to do with traditional power politics and profit making.

It's time to get out from under the umbrella and to acknowledge that we are in different camps with different goals. And to do that we need to get rid of the idea that "openness" is an unalloyed virtue.

Here are two examples of how openness is being misused.

The first is about openness and transparency, and it's from Canada where I live and of which I am a citizen. The Government of Canada has an active open data program. It's a member of the Open Government Partnership, now chaired by Francis Maude; if you look in Capgemini's recent white paper on [The Open Data Economy](http://www.capgemini.com/insights-and-resources/by-publication/the-open-data-economy-unlocking-economic-value-by-opening-government-and-public-data/) you'll see Canada together with the UK, the USA, France, and Australia as one of the government trendsetters. Last October Jonathan Rosenberg of Google posted an article on the company web site titled "[The Future is Open](http://www.google.com/think/articles/the-future-is-open.html)", in which he wrote:


<blockquote>Claims to governmental transparency are one thing – moves like the one Canada made recently, with its formal Open Government Declaration, are another. The document recognises that open is an active state, not a passive one – it's not just that data should be free to citizens whenever possible, but that an active 'culture of engagement' should be the goal of such measures.</blockquote>


So three cheers for open government Canada? Of course, that's only one side of the story. Here's a list of other events in Canada around openness and transparency.



	
  * Library and Archives Canada, which is the equivalent of the British Library, has seen its acquisition and lending programs cut back. Its historical item spending has been cut from $385K ('08-'09) to $12K ('12-'13) as its overall budget has been cut from $173M to $108M. ([Toronto Star, March 10, 2013](http://www.thestar.com/news/insight/2013/03/10/historical_letters_not_wanted_at_library_and_archives_canada_critics_say.html))

	
  * The Government is "muzzling its scientists" according to [the BBC](http://www.bbc.co.uk/news/science-environment-16861468). A protocol introduced in 2008 requires that "all interview requests for scientists employed by the government must first be cleared by officials. A decision as to whether to allow the interview can take several days, which can prevent government scientists commenting on breaking news stories. Sources say that requests are often refused and when interviews are granted, government media relations officials can and do ask for written questions to be submitted in advance and elect to sit in on the interview."

	
  * Cuts to Statistics Canada: in response to yet another wave of cuts, a group of concerned academics recently wrote that "For many of us, it started with the census. In a controversial move, our government switched from a mandatory to a voluntary census in the summer of 2010. The former Statistics Canada chief, the media and the research community reacted with shock and largely opposed the change to no avail … We have now halted the collection and analysis of our most informative longitudinal information on our labour force, on the workplace, on health and health care, and on child well-being. Add to this our universal census of the population. How might Canada expect to meet the policy challenges of the future when we no longer have the ability to understand where we are today?" ([University of Manitoba](http://umanitoba.ca/outreach/evidencenetwork/archives/6846))

	
  * The move to packaging legislation in so-called "Omnibus bills" that cover many different initiatives in a single, perhaps several hundred page, package has severely curtailed public debate over new initiatives and major legislative changes.


If there's a message here, it's just that _openness cannot be measured in bytes_. And if someone _is_ measuring it in bytes, then you have to wonder what the motives are. So the CapGemini report (above) looks at the Open Data Economy simply by comparing the open data portals that each nation has produced. This is datawashing.

A brief second story. If you look at what kind of new economic possibilities are being promoted by open data, CapGemini highlights Zillow, a Real Estate Advertising network based in California, which uses open tax data, county records, and home-for-sale listings. If there is one industry who has proved able to use the language of openness and disruption to great effect, it's the Silicon Valley venture capital industry. But whereas when Linus Torvalds started Linux "openness" was a tool for individuals to build something to compete with large enterprises, now "openness" is a tool for large enterprises with a lot of funding to hammer smaller non-profit groups. We hear the language of openness and disruption coming in education, where Coursera and Udacity can go to Davos and paint themselves as radicals, to Uber and AirBnB, whosee millionaires claim to be part of a "sharing economy" disrupting nightmare overlords like the Bed & Breakfast industry or the taxi cartels. We are seeing the emergence of a winner-take-all economy in which small organizations and small businesses are severely handicapped against those with capital behind them. All in the name of openness.

If we see civic participation as an end in itself, which I do, then we need to treat civic computing like a cultural activity. That means we need to build some barriers to protect civic-scale groups from large companies who have advantages of scale, and who can deliver "efficiency" but not participation. Tony Ageh of the BBC, speaking at this conference, describes a vision of public domain data as a "commons" but I think he gets it wrong. A commons is not a free-for-all, where anyone can come and take anything they want. A commons suggests a group of people who all have an interest in maintaining and cultivating a shared resource, and that suggests limits to access from outside. There is room for a number of models of providing mixed access to data, from non-commercial licenses, to closed partnerships between cities and citizen groups, to non-standard formats for sharing that reflect the quirks of individual cities and groups. Each of these seems to break the idea of "openness" in one way or another, but we should be prepared to do so. Openness in and of itself is not enough to hold together a worthwhile coalition and it's time to get over it.		
