---
author: Tom Slee
categories:
- blog archive
date: 2010-01-09 00:33:51
title: The Myth of Digital Democracy, by Matthew Hindman - reviewing the reviews
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_The Myth of Digital Democracy,_ Matthew Hindman, Princeton University Press  2009

* * *




The last sentence of Matthew Hindman's _The Myth of Digital Democracy_ is "It may be easier to speak in cyberspace, but it remains difficult to be heard". The book is about collecting and analyzing the following large data sets on the way to this conclusion:






  * The links among 3 million American political web pages together with data showing how Google leads its users to political sites. Hindman concludes that "link structure is an effective proxy for audience share" and that "communities of Web sites on different political topics are each dominated by a small set of highly successful sites". The scale of online concentration is so profound, he argues, that claims the Internet "democratizes" politics are misleading. For example, when it comes to blogs, "the top blogs are now the most widely read sources of political commentary in the United States", but these widely-read bloggers are very few in number (a few dozen) and they are "overwhelmingly.. well-educated white male professionals". The kind of voices that get heard in political discussion are the same kind that were heard through offline media, only perhaps more so. "The vigorous online debate that blogs provide may be, on balance, a good thing for US democracy. But as many continue to celebrate the democratic nature of blogs, it is important to acknowledge that many voices are left out."


  * Data from [Hitwise](http://www.hitwise.com) of search-engine-directed traffic show that online politics is a tiny sliver of Internet traffic, and that "Scholars, public officials, and journalists have paid a great deal of attention to online politics. Citizens themselves, though, have directed their attention elsewhere." Not too surprising perhaps.


  * Data from Hitwise and other sources, of patterns of concentration in [American] online and traditional news media. He concludes that online media is much more concentrated (a few outlets get a larger share of the traffic) than many offline industries, particularly radio. The biggest story is what he calls "the missing middle":  
  
From the beginning, the Internet has been portrayed as a media Robin Hood - robbing audience from the big print and broadcast outlets and giving it to the little guys. But the data in this chapter suggest that audiences are moving in both directions. On the one hand, the news market in cyberspace seems even more concentrated on the top ten or twenty outlets than print media is. On the other, the tiniest outlets have indeed earned a substantial portion of the total eyeballs... It is the middle-class outlets that have seen relative decline in the online world. Moreover, it is overwhelmingly smaller, local media organizations that have lost out to national sources. [p100]




It is a refreshing change to read a book about the cultural and political impact of the Internet that actually looks closely at Internet traffic (what people read) rather than at the number of sites (what people write), and it's this perspective that leads Hindman to his myth-busting conclusions. The main flaw of the book is that it falls between two stools: it's clearly an academic work that started as a set of papers or a thesis, but it is looking for a wider, popular audience. To reach that audience, Hindman should have got rid of many technical details and written a book with more narrative, but if you don't mind reading technical studies, this is a good one, and I recommend it.

_The Myth of Digital Democracy _has been out for a year or so now, so after I finished it, I looked at some reviews, and got a surprise. The books detractors argue that no one claimed the Internet democratizes politics, and if they ever did then they don't any more, and if they still do then they mean something different.

So here are links to some critiques of Hindman's book, and some words in defence of _The Myth of Digital Democracy_:



  * Charlie Beckett of the LSE's think tank POLIS [writes](http://www.charliebeckett.org/?p=1672) that the idea "that the Internet is innately democratic and that it will have revolutionary political consequences" is "a straw man". He goes on: "I always struggle in lectures or talks when I have to find quotes from these digital utopians. I can always cite lots of people (like me) who argue that the Internet has given us great tools and that it offers huge potential for civic engagement and public self-expression. I can even find examples, from Mysociety to Iran and Twitter that show concrete cases. But I don’t know many serious people talking about a revolution."  
  
This is a little cheeky from someone whose own book is called SuperMedia, and which is [publicised](http://www.polismedia.org/publications/savingjournalism.aspx) as a "manifesto" for a "radical new relationship between the media and the public", and which apparently "explores the potential for an entirely new type of journalism... and makes the case that journalism could be the catalyst for change needed to solve many of the world's problems." All sounds pretty revolutionary to me. Beckett is getting hung up on the title, which was probably the publisher's idea anyway, and needs to read the book more closely.  
  
As for actually finding quotes about the Internet's innately democratic and revolutionary (or at least radically disruptive) nature, well there's always Google's description of its own PageRank search algorithm as "drawing on the uniquely democratic nature of the Internet" and its recent [claims](http://googleblog.blogspot.com/2009/12/ordinary-citizens-extraordinary-videos.html) that in Iran, citizen video reporting via YouTube "appears to have become an essential part of their struggle". Or there's Lawrence Lessig in _Remixed_: "The neutral platform of the Internet democratized technical and commercial innovation. Power was thus radically shifted." Or Yochai Benkler at the very beginning of his influential _The Wealth of Networks:_ "Enabled by technological change, we are beginning to see a series of economic, social, and cultural adaptations that make possible a radical transformation of how we make the information environment we occupy as autonomous individuals, citizens, and members of cultural and social groups. It seems passe today to speak of 'The Internet revolution.' In some academic circles, it is positively naive. But it should not be." And that's ignoring all the [talk of Twitter Revolutions](http://www.google.ca/search?q="twitter+revolution") in Moldova and Iran, and [Egypt's Facebook Revolution](http://www.nytimes.com/2009/01/25/magazine/25bloggers-t.html?_r=3).   
  
Discussion of the Internet's impact on all aspects of our society is routinely cast in a revolutionary light, with a strong dose of "power to the people", and if such language is usually kept out of academic journals, that's no reason to ignore it.  



  * For Mark Bahnisch of [Inside Story](http://inside.org.au/the-stuff-that-myths-are-made-of/), Hindman "narrows down the possible targets for his myth-busting to the claim that the internet will bring about 'democratisation.' But it's unclear who's actually making this claim, and Hindman ignores most of the more nuanced and specialised scholarship on the topic. If what he has to say when he gets down and dirty with the blogs later on is any indication, the real target is a nuch of journos and op-edders writing in the New York Times circa 2004."   
  
Bahnisch is saying Hindman should ignore "journos and op-edders" with audiences of millions and focus instead on "nuanced and specialised" scholarship that general readers like me will never read. Rubbish. The real debate about the role of the Internet is a public one, and Hindman has done exactly the right thing to tackle this perception that's out there among the unwashed masses like myself. If the nuanced and specialized among us have good things to say, they should get out there in public and say them.  



  * When it comes to the concept of democratization, Bahnisch and [others](http://gatewatching.org/2008/05/18/long-tails-all-the-way-down-rethinking-a-lists/) people bring up "Michel Bauwens' concept of equipotentiality" as an alternative meaning interpretation of "democratization". [Equipotentiality](http://p2pfoundation.net/Equipotentiality) is a fancy word for speculations about how peer-to-peer networks function: no one said that democratization means a wider set of voices are heard, simply that anyone can _potentially_ reach an audience of millions, and if only a few do, well good for them.  
  
The whole point Hindman's approach makes is that concepts, whether they coin new words or not, need to be grounded in reality. Is the loose world of blogs equipotential? Who knows, given the vagueness of the concept? But that potential is certainly not equirealized and that's a point worth making.  



  * Allison Hayward [writes](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1491737) that "to observe that 'digital democracy isn't always and everywhere the rule is not the same thing as saying that the Internet hasn't 'democratized' politics... For the Internet to be 'democratizing' we shouldn't require that it be _revolutionary_, only that at the margins it provide a broader population with more opportunities to contribute, volunteer, engage, and advocate, and make changes that are sustainable over time."  
  
Sigh. Hindman has demonstrated that many of these functions are not accessible to a broader population in any meaningful way. The book challenges those who believe the Internet is "democratizing" in whatever way to show there is some substance to these claims, and the rebuttals are wishful thinking based in, well, nothing much really.  



  * Matt Bai [argues](http://www.democracyjournal.org/article.php?ID=6671) that Hindman's data is old, and "the political impact of the Internet is spreading so quickly that it's almost impossible to capture and quantify": he disparages Hindmans's graphs and equations and prefers anecdotes about internet activists from modest backgrounds.   
  
By the time I'd read this review I was feeling pretty sorry for Matthew Hindman, because it is clear that he just can't win. Bai has a belief in the power of the Internet that borders on the mystical ("spreading so quickly that it's almost impossible to capture and quantify"), so what would it take to persuade him otherwise? Nothing short of careful, detailed data I'm sure. But when someone does the work, well it takes time, and so it is dismissed as "old" and full of obscure graphs and equations. There is little point entering such an argument.  



  * Along these lines Henry Farrell, in the Times Higher Education Supplement, [suggests](http://www.timeshighereducation.co.uk/story.asp?storyCode=407101&sectioncode=26) that Hindman should just not engage with these claims, that he spends too much time "refuting bad ideas" and tackling "stupid claims for the democratic benefits of technological pixie dust" and goes on to say that "To really understand how the internet affects democratic politics, we need to forget about the internet evangelists. Not only were they badly wrong, but their notions of democracy were sloppy and unhelpful."  
  
I sympathize with Henry Farrell: it would be nice if we could forget about bad ideas and move ahead on more constructive paths, and I hope people do. But sloppy or not, those notions of democracy are out there, and are still influential, and Hindman has made a valuable contribution towards refuting them.








		
