---
author: Tom Slee
categories:
- blog archive
date: 2014-09-16 23:29:00
title: All Sharing Economy, All the Time
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				




So it's been a long time since I posted here. Basically, I thought I'd said all I had to say about the sharing economy: it's being covered in so many places now a blog has less of a contribution to make. So I pondered the meaning of life and thought I'd move on to other things (and thanks to Kieran for counsel on that).







But oddly enough, requests for comment and posts about the sharing economy continue to come in, far more than any other topic I've written on, so that's where the demand is (thanks to Trebor, Cameron, CBC (times 2) and Andrew (even if we don't get anything worthwhile from that effort)).

What's more, the dividing lines are being drawn increasingly clearly as labour and community groups line up on one side, and fans of deregulation, conservatives, republicans and Fox News line up on the other. It's good to be contributing to something worthwhile (thanks to LAANE from Los Angeles for a chance to support their efforts).

So I'll be spending the next several months focusing on the sharing economy, and hope to build up a useful set of resources here, as well as contributing elsewhere. It's likely that this blog will be more narrowly focused than in the dim and distant past when I used to write about other things. It will also get repetitive and repetitive. You have been warned.






		
