---
author: Tom Slee
categories:
- blog archive
date: 2009-11-14 17:45:53
title: 'The Pirate’s Dilemma by Matt Mason: A Review'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::

In _The Pirate's Dilemma_ Matt Mason claims to speak from the perspective of rebellious and subversive youth culture while he promotes the worst kind of corporate astroturfing which is too bad because his message that many new ideas emerge from outside the mainstream and from outside the market is important and his message that pirates who skirt the edges of the law to bring culture to new audiences have done much to improve our society also matters, but when an author wants us to believe he is anti-establishment while he praises the vitamin water company Glacéau for "keeping it real" in its advertising campaigns with 50 Cent while telling us that it was sold to Coca Cola for $4.1 billion in 2007, praises Procter & Gamble for its viral video campaign, is entranced by the way that Nike's Air Force One sneaker owes its success to the "remix" well where do you start? Mason loves the idea that youth culture, existing in spaces outside the mainstream and outside the commercial world, has had a huge impact on our modern world and I am with him 100% but the lives of many idealistic, left-wing youth become enmeshed in compromise as we get older and we stoke the fires of capitalism during the day while trying to throw a little water on those same fires in the evening and I understand how this happens because like many middle-aged people I wrestle with the contradictions and compromises involved, and I admire those few who have stuck to their principles, often at a real cost to their careers and personal lives, which is why the few people who really piss me off, whom I actively scorn and who get my blood boiling, are those like Matt Mason who don the mantle of rebellion and anti-corporate politics while consulting for Disney, Pepsi, and P&G and who claim that selling YouTube to Google for $1.65 billion is a form of rebellion and who babble about the benefits of sharing because "it's not all about the money any more" while giving presentations to the people who brought you McDonald's "I'm Loving It" campaign and who place themselves on the romantic side of the battle between graffiti and advertising in "a turf war that has raged for centuries between the establishment and a secretive, loose-knit network that doesn't like the top-down, one-way flow of information in public spaces" [103] only to step slickly into approvingly quoting advertising agency Droga5 on creating "a dialogue between advertising and graffiti" which really means using graffiti for commercial ends and making a buck and if that's not selling out to the man then what the fuck is really? because the punk spirit Mason loves so much has nothing to do with business models or change agents or entrepreneurial spirit or building a brand or even combining altruism with self-interest because the spirit he writes of was defiantly and nihilistically anti-corporate and Matt Mason lives in a corporate world however much he'd like to think otherwise and when he claims that pirates are those who are "pushing back against authority, decentralizing monopolies, and promoting the rule of the people: the very nature of democracy itself" well I see what he means but then when he goes on to claim that the anti-authoritarian ideals of youth culture are becoming ... a new more extreme, invigorated, and equitable strain of the free market--the decentralized future of capitalism [171] then I just want to shake him by the neck and shout at him that you're obviously not stupid Matt Mason so why don't you do what you know you should do and follow the fucking money before making pronouncements about sharing and decentralization when it's still the case that money is not shared and money is not decentralized because sharing is one thing but if I share and you get the money then I'm not being altruistic I'm just being a sucker and you're not promoting community you're exploiting the good intentions of those who are spending their time and talent on your venture and if you want to impress me with the subversive role of DVD bootlegging don't quote billionaire Mark Cuban and Disney co-chair Anne Sweeney and billionaire Steve Jobs at me because if they have found a way to co-exist with piracy it doesn't mean that these companies stand for a more democratic and equitable form of capitalism it just means they've found ways of using or co-existing with piracy in a way that promotes their own interests over those of their rivals and I end up not taking him seriously at all which is unfortunate because he has many entertaining stories of hip-hop, pirate, and punk culture although I end up not knowing whether to trust them because where the book overlaps with things that I know anything about he is often ludicrously wrong like when he repeatedly refers to Linux as a company [148, 150, 238] or when he quotes Courtney Love saying that record companies "figured out that it's a lot more profitable to control the distribution system than it is to nurture artists... They own the plantation" while completely failing to notice that big chunks of the Web 2.0 world he loves work on exactly the same model, that owning the platform gives control of the distribution system and that's where the money is or when he gives us a canned history of Wikipedia [149-150] which is derived from one interview with Jimmy Wales so it's no surprise that it gets several key facts wrong or when he identifies Steve Jobs with openness and sharing [145] and claims that the notoriously secretive and proprietary Apple won the music wars because it "truly understood sharing" [158] when the fact is that the only thing Apple really wants to share is the music they don't own and not the technology that they do own you can ask Palm about that who can't sync their own phones with iTunes or you can ask the developers who have left the iPhone App Store over Apple's arbitrary and opaque approval process, so Matt Mason in the end sits for me with people from an earlier generation like Kevin Kelly who claims to be a maverick while working for Conde Nast or Chris Anderson who claims to be on the side of small and scrappy businesses against big companies while promoting Amazon or Stewart Brand or John Perry Barlow who strive to combine activities like consulting for senior management at large corporations with statements like "I'm an anti-company man" if you can believe it I mean do you have any self-awareness at all? I want to ask them I think it's the ego that gets to me and the fact that they have been successful in leading people and particularly young idealistic people with good intentions into activities that they think are progressive and politically anti-establishment but which end up just feeding money into the pockets of Silicon Valley venture capitalists and the lucky guys who get to sell their startups to Google for a nice billion or so as if that's a triumph of the little guy give me a break.


		
