---
author: Tom Slee
categories:
- blog archive
date: 2006-07-24 23:27:03
title: 'Inequality II: Consequences'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Following on from the previous post, here are two other places where they talk about the consequences of inequality:




Mark Thoma, yet again, [brings us ](http://economistsview.typepad.com/economistsview/2006/07/taking_the_core.html)a piece from the New York Times which discusses what can happen in a city when the middle ranges of income leaves, so that only the rich and poor are left. Basically, the two become separate cultures.

<blockquote>With a dwindling middle class, rich and poor become more separate. Alan
Berube, an author of the Brookings study, said a two-tiered marketplace can
develop: Whole Foods for the upper classes, bodegas for the lower, with no
competition from stores courting the middle...
> 
> 

> 
> “This trend toward living and interacting with people who are like you is
intensifying a lot,” said Professor Gyourko, who lives in the affluent suburb of
Swarthmore, Pa. “I do not meet the full range of incomes and social classes
within my neighborhood. Well, think about what happens if metropolitan areas
like New York, San Francisco and the like turn into my suburb. You’ll have even
less interaction. The most interesting and potentially foreboding implication of
this sorting is that it changes the way we view life.”
> 
> </blockquote>

And Matthew Kahn asks [When the rich get richer, what happens to the poor?](http://greeneconomics.blogspot.com/2006/07/when-rich-get-richer-what-happens-to.html) and answers

<blockquote>It depends. If the super-rich use some of their $ to finance nice
musuems and art galleries and Buffett-Gates their money to solve public
health challenges then society could be improved along some dimensions.
> 
> 

> 
> Alternatively
if this crew uses their money to purchase 100,000 square foot homes in
desirable areas then the price of land will skyrocket and the middle
class will be squeezed out.
> 
> </blockquote>


		
