---
author: Tom Slee
categories:
- blog archive
date: 2008-10-26 22:05:42
title: O'Reilly vs Carr on Cloudy Monopolies
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

In the offline world it is obvious that industries have different levels of concentration. The forces that shape the grocery store industry are different from those that shape the automobile industry, home furnishing stores, copper mining, the insurance industry, and so on.  


  


In contrast, there is a tendency to think as if all digital industries are governed by the same set of factors. We talk about iTunes as if it has something to say about the success of SalesForce.com; about Netflix as if it has something to do with the success of Google. The runaway success of companies like Facebook and Amazon, which provide services that get more valuable the more people use them, has led to a focus on network effects as the driving force behind industry concentration. But it's obviously true on the Internet just as it's true elsewhere that selling books is different from selling advertising.

  


I say all this because A-list technopundits [Tim O'Reilly](http://radar.oreilly.com/2008/10/web-20-and-cloud-computing.html) and [Nicholas Carr](http://www.roughtype.com/archives/2008/10/what_tim_oreill.php) have competing posts about industry concentration in the world of cloud computing. And while I lean towards Carr, each oversimplifies the issues.

  


O'Reilly coined the phrase _Web 2.0_ and he says the cloud is, not surprisingly, all about Web 2.0. "Understanding the dynamics of increasing returns on the web is the essence of what I called Web 2.0. Ultimately, on the network, applications win if they get better the more people use them." That is, there is one source of increasing returns you need to think about when considering industry concentration on the Internet, and that's network effects. On the other hand, he recognizes that "cloud computing" is a name that covers several different developments, including hosted virtualized computers (Amazon's EC2 and S3), hosted software platforms (Salesforce.com and Google Apps) and cloud-based applications (Facebook, Flickr). He claims that real industry concentration (and hence profits) will take place only in the third of these layers, because only here do network effects really come into play.

  


Carr's recent book _The Big Switch_ caught the wave of cloud computing, and so he says that the cloud is more important than mere Web 2.0. He points out that there are many sources of increasing returns in addition to network effects. Using Google as an example, he points to (not by name) learning-by-doing (Google gets better at search algorithms because they learn from their own experience); high fixed costs (the need for massive data centres); and asymmetric information (the predictability of a brand-name experience). But Carr does not distinguish different aspects of cloud computing.

  


I think Carr is closer to being right. There are so many sources of increasing returns in digital industries, in addition to the big one that the marginal cost of production of a digital good is basically zero, that the normal expected state of Internet industries is surely monopoly, give or take.  
  
But guess what? Not all Internet industries are monopolies and if we are to get to grips with industry concentration in Internet-driven industries we need to acknowledge that different digital industries are pushed by different forces. Different parts of the cloud computing world really are different and will see different levels of concentration.  
  
What we need to do is not so much look at the sources of increasing returns to scale, which are many, but instead look for what factors might _limit_ increasing returns and prevent the expected monopolies from forming. Any such factor will affect different digital industries in different ways. I'll just look at one factor to show what I mean.

  


Just to be au courant, let's look at Paul Krugman's Nobel prize winning work (see a PDF [here](http://nobelprize.org/nobel_prizes/economics/laureates/2008/sci.html)) as a source of inspiration. We have, collectively and individually, a preference for variety (and, loosely speaking, a variety of preferences) and this preference limits industry concentration. Here's how. According to the classical model of trade, industries should get very concentrated as each country focuses on its own area of comparative advantage. If Germany is good at making cars and Sweden is good at making bookcases then all the cars will  be made in Germany and all the bookcases in Sweden - then they will trade cars for bookcases.

  


But in the real world both cars and bookcases are made in both Sweden and Germany and they each trade both cars and bookcases among themselves. Industry concentration is limited. How come?

  


One of the things Krugman used to explain this observation is the idea that as consumers we have a taste for variety. So MacDonald's may have economies of scale and sell a lot of burgers, but no one wants to eat MacDonald's all the time so there's a limit to how much of the restaurant industry MacDonald's can win over. There are many sources of heterogeneous tastes. Geography is an obvious one - I'm not interested in a bookstore in Saskatoon because I've no way of getting there. Culture is another - I'm not interested in Russian-language books. And when it comes to music and clothes, well there's no accounting for taste. But wherever there is a taste for variety, industry concentration will be limited.

  


It will be interesting to see what kinds of variety create barriers to concentration in the cloud. On the hardware/virtual machine realm I can imagine security and service level agreements providing distinguishing factors that may encourage variety. Is it worth a hosting company going through endless certifications to get validated as a secure-host for private data? Will they bet the bank on high service levels? At the Web 2.0 applications level, it's worth remembering that culture provides a surprisingly strong barrier for some experiences. As just one physical world example, the record of giant grocery stores outside their own country is surprisingly patchy. Wal-Mart, Tesco and Carrefoure each hold sway in their own country but haven't been able to be successful in the others'. When I signed up to Facebook the obvio
us Americanness of the site was a turn off (which college did I go to? a politics spectrum from "conservative" to "very liberal"?). Perhaps this is why different countries have different major social networking sites.

  


But my fear is that a taste for variety may not be strong enough to hold back very large concentration at many levels. You might think that people searching for different kinds of information may use different search engines. In Canada when I search for NDP I want to find the New Democratic Party, but an Irish searcher may be looking for the National Development Plan. But so far Google has been able to use its sources of increasing returns to scale to accommodate this variety and more, without letting competitors in. There are basically no niche search engines.

  


It's the same in online encyclopedias; in the real world the physical limits of books mean that there are all kinds of specialist interests that Encyclopedia Britannica cannot cater to, and so we have encyclopedias of film, of football, of frogs, and so on. In the online world there's only one encyclopedia and it covers all these areas.

  
And that's why I am inclined to agree with Carr.  



		
