---
author: Tom Slee
categories:
- blog archive
date: 2009-07-24 20:27:08
title: 'Online advertising: when better is worse'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

There I was, reading [this](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1428065) paper called "Online Advertising, Identity and Privacy" by Randal Picker of the University of Chicago Law School, and learning quite a bit from it. He's obviously thought hard about the conflicts (privacy) and opportunities (advertising) that arise when people provide their identity to online services, and about what kind of regulation may be needed to ensure those services behave responsibly with the data they collect. After all, as he says:  


<blockquote>In the past, we have regulated intermediaries at these transactional bottlenecks - banks, cable companies, phone companies and the like - and limited the ways in which they can use the information that they see. Presumably the same forces that animated those rules - fundamental concerns about customer privacy - need to be assessed for our new information intermediaries.  
</blockquote>

In introducing the topic of advertising, Picker makes the standard point that "Ads in these [traditional] media are targeted to rough demographics. The Internet, in contrast, promises advertising matched to me". And this, he claims, is a good thing: "Think about TV advertising and how many ads that you see for products that you never consume. Those ads are almost all wasted. Behavioral advertising [ie, personalized, online advertising] offers the promise of tailoring ads to individual consumers greatly increasing the efficiency of each ad dollar spent".  
  
And then it clicked. I'd never realised it before, but the assumption that accurate advertising is better for me than inaccurate advertising is completely wrong. 180 degrees wrong. The truth is that accurate, targeted advertising is not a good thing, it's a terrible thing.   
  
To be slightly more nuanced, there are two kinds of ads in the world: listings and intrusions (I'm sure there are better names out there, but that's all I can think of), and while accurate listings are OK, accurate intrusions are a terrible thing, because they intrude more effectively.  
  
Listings are ads that I seek out: If I'm looking to buy a second-hand chest of drawers I'll look in the back of the local paper, or on Craigslist or on Kijiji, and here I want to be able to find what I'm looking for, just like Randal Picker says. An ad for a car is no use if I'm looking for a chest of drawers. if I were looking for a job I'd want ads that match my skills and interests. So when we're talking about listings, accuracy is good.  
  
But then there are all those ads that you try to ignore, because they work by getting in your way when you're not looking to buy anything at all. TV ads, radio ads (thank heavens for the CBC), some newspaper and magazine ads are all intrusions. They work by intruding into something else that you're doing and catching your attention. And what I want from these ads is for them to be as obviously wrong and inaccurate as possible, because then I know I can ignore them safely. The more inaccurate they are, the less they drag at my attention, and the less likely they are to pull me away from what I'm trying to do. More accurate ads are a more effective distraction. And while that may be good for the advertiser, and even for the owner of the delivery medium, it's bad for me.   
  
This is not some fancy rhetorical point - it's actually how I experience newspapers and the Internet, and I suspect you do too.   
  
Think about Adwords. When you carry out a search, you don't want the advertised listings, you want the "honest", unpurchased listings. Try it yourself. If you are interested in finding out more about the subject of this post you may google [[online advertising](http://www.google.ca/search?q=online+advertising&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a)] (go ahead and click: the link opens a new window). Do you want any of those listings down the right hand side? No you don't. Do you want to go to those top three advertised links? No you don't. Fortunately, they are all pretty much obviously outfits you don't want anything to do with and you can easily ignore them. But if they were closer to what you were really interested in, you'd have to look over them, wonder whether to click them, decide whether to discard them or not. It's all effort and attention and I'm lazy enough that I really don't need it. The closer those ads are to what I'm looking for, the more distracting they are, and the more effort it is to drag my eyes away from them to the results I actually want.  
  
Fortunately, despite the promises of individually targeted ads that know my inner desires and motivations, we don't have to worry about them becoming too accurate to ignore in the near future. After all, right now all we get is weight loss ads on Facebook and everywhere else and everyone gets to see those. Unless... you do see them too, don't you?  
  



		
