---
author: Tom Slee
categories:
- blog archive
date: 2008-05-18 15:18:35
title: Money Ruins Everything, but we have to talk about it anyway
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

In _Money Ruins Everything_ ([blog post](http://crookedtimber.org/2008/05/17/money-ruins-everything/), [complete article](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1126088)), John Quiggin and Dan Hunter look out at the new forms of creative expression introduced by the Internet (blogs, wikis, citizen journalism, and to some extent open-source software) and conclude that today's most important innovations are driven by the collaboration of amateurs with non-economic motives. They give this development progressive political overtones by labelling it "the 'amateur collaborative content' movement" [p216] and explicitly identify it as a non-commercial alternative to the market. I don't know Dan Hunter's other writings but Quiggin, at least, is a social democrat whose views I usually agree with and whose writings I read often and respect, so I don't disagree lightly with him. But the picture they paint is a distorted one so I have to.




[Note to regular readers: you may want to move right along - much of what's here is stuff I've written earlier in other contexts. It's just more of the same, but it needs to be said.]




There are three major things wrong with the paper.




  1. A portion of the activity they describe as non-commercial is in fact commercial. 


  2. They exaggerate the rise of the amateur in the Internet age. 


  3. They neglect the other side of the coin, which is the spread of commercialism into areas that were previously non-commercial.






I thought I'd talk about all three, but it's taking too long to write and I need to go and cook some dinner as part of my contribution to our household's creative production so I'll just address the first. If I were to say something about the other two it would be




(2) in assessing the rise of the new amateurism they neglect instances of amateur production that existed before the Internet and may be driven out by the rise of the Internet. And 




(3) Facebook represents the commercialization of conversation, not the amateurization of collaborative content production.




The distinguishing technological feature of the collaborative web ("web 2.0") is the shift from peer-to-peer networks to a "platform" architecture that is built on top of the lower-level protocols of the Internet. 




Wikipedia is a platform: it defines the ways in which you can interact with it, stores the changes you make, and provides security and authentication mechanisms among other things. Facebook is a platform. Amazon is a platform. YouTube is a platform. Blogging takes place on platforms. So the authors are wrong when they say that "As a result of various forces—notably the ascension of the general purpose computer, peer-to-peer technologies, and the internet—all manner of established verities in the content industry are falling." [p215] None of the platforms mentioned above operate in a peer-to-peer manner.




The distinction matters because when content is built on a platform, it is in some important senses owned by the platform-owner or aggregator. Private ownership is present, even if the content (videos, book reviews etc) is explicitly shared by its amateur producer. The suggestion that "Users can modify open source software as they see fit, and can choose whether to make their modifications publicly available, but cannot charge for the use of software derived from an open source program." [218] is incorrect for open source software itself (it applies only to GPL'd software and not software produced under other open source licenses such as the BSD license, and even then copyright owners - such as MySQL AB, now a part of Sun Microsystems - can and do charge for some versions of the software). More importantly for this paper, it is also misleading when it comes to collaborative content. Chad and Steve cannot sell an individual video produced by an amateur, but they can sell the entire collection of videos lock stock and barrel to Google for [about a third of a billion dollars each](http://www.roughtype.com/archives/2007/02/it_youtube_and.php); Michael Birch can [sell Bebo and all its content](http://www.nytimes.com/2008/03/22/opinion/22bragg.html?_r=1&oref=slogin) (including Billy Bragg's songs) to AOL and pocket $600 million. Now that's commercial. Or you can get a seat at Davos, of course, which now seems to be the Cannes red carpet equivalent for our youthful webby leaders.




Amateur production on a non-commercial platform such as Wikipedia is non-commercial. And it's important. No argument there. But amateur production on a commercial platform is commercial activity. With one party in each transaction motivated my money, it's the sound of one hand shaking. [Back in 2003](http://www.tbray.org/ongoing/When/200x/2003/07/12/WebsThePlace) Tim Bray's dinner companion Robb Beal introduced the phrase "digital sharecropping" to distinguished building software "for any platform that is owned and operated by a company" from building sofware for the web. But now that dichotomy has faded: the web includes many platforms owned and operated by companies and sharecropping has moved online along with it. Nicholas Carr has been [particularly pointed](http://www.roughtype.com/archives/2006/10/web_20ier_than.php) about the movement of [digital sharecropping onto the web](http://www.roughtype.com/archives/2006/12/sharecropping_t.php), and Seth Finkelstein has pointed to several examples including [citizen journalism](http://sethf.com/infothought/blog/archives/001108.html). It's a phrase that should be front and centre of everyone's mind when they see the phrase "networked production".




The distinction can often be seen in who is sharing what. On a non-commercial platform, the amateurs share and the platform owners share as well. At least, my understanding is that on Wikipedia not only the content but also the software and large amounts of data mining derived from it about users and so on is shared publicly. In contrast, on a commercial platform only the amateur material is shared. The contributions of the commercial part of the transaction (Amazon's sales data for example; data on user habits; the software that runs the platform itself) are not shared -- in fact this half of the story is hidden with as much zealousness as the source code of any closed-source company. One of the reasons that "The Long Tail" was such a flop of a book is that the data Chris Anderson relies on is unavailable for anyone else to inspect, and much of it was given to him in filtered form by the content owners.




A second failure is most obviously present in the following paragraph (page 245). 

<blockquote>Copyright thus provides incentives to the intermediaries of the content industries—publishers, agents, movie studios, retail stores, etc.— where the processes of moving content from creator to user are expensive or capital-intensive. These “content processes” include the creation of the content, the selection of the content for commercial publication, its production and dissemination, its marketing, and its eventual use. Until recently each of these processes has been too expensive, too difficult, or too specialized for amateurs to undertake. So until now, highly capitalized intermediaries were necessary to ensure that content moved into society.
> 
> </blockquote>

Amazon, Google and so on are obviously highly capitalized. More so, in fact, than many small distributors of pre-web content. The web is seeing the movement of content into society consolidated into a handful of "highly capitalized intermediaries": very large and wealthy commerically-driven web site owners, including such old-school outfits as News Corporation, the owner of MySpace. It does no good to ignore this trend.







The paper also elides the distinction between amateur and professional motivations, with the temptation to caricature employed work as factory-line production of alienated labour, while amateur work is driven by love. To take a relevant example, what is the overlap between the motivations of John Quiggin (blogger) and John Quiggin (employee)? Is his work for the University of Queensland driven by the his "first rule" which is "never to give more than you get?" [231] And if not, why does he think that software engineers for commercial software companies writing closed-source programs are driven by different motivations? There is a possible argument (nicely made by Geof in [a comment on a previous post](http://whimsley.typepad.com/whimsley/2008/05/linux-again.html#comment-113333922)) about alienation and the relationship between the developer and the code, but this does not cover production in sharecropping platforms. I'm more inclined to go with [another comment by Dipper](http://whimsley.typepad.com/whimsley/2008/04/linux-grows-up.html#comment-111344030), that participation in many cases can be covered by standard utilitarian calculus.







One argument made by the authors is that the incorporation of money into production would drive out amateur efforts in a blood-donation kind of way. I'm happy to help push someone's car out from a snow drift for free, but I wouldn't do it for a dollar. But there are two groups of people with an incentive to keep money out of the equation: one is the promoters of real community-driven, shared production (the authors' camp, and one I'm quite happy with) and the other is the turbocapitalist platform owners such as Amazon (would you review a book for a nickel? would you trust the review of someone who did?) It is this shared interest in supressing the role of money for very different reasons that makes me most queasy in contemplating the future of the Internet. We need to be clear in distinguishing public goods from privately owned plantations. Unfortunately, in this paper, John Quiggin and Dan Hunter fail to make the distinction and the result is a distorted picture of web-based creative work. Money may ruin everything, but turning a blind eye to money doesn't get around that problem.




I feel like I'm being harsh on the authors here - as I say, I agree with their political sympathies, and the one I have read (Quiggin) is obviously smart and well informed on many issues. But serious social scientists need to do serious work on the nature of production on the Internet and not just adopt the turbocapitalist line. Me, all I can do is raise a few questions. But then, when it comes to social science, I'm just an amateur.


		
