---
author: Tom Slee
categories:
- blog archive
date: 2008-12-31 11:19:01
title: "Mr. Amazon's Bookshop: First Visits"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[The table of contents for Mr. Amazon's Bookshop is [here](http://whimsley.typepad.com/whimsley/2008/12/mr-amazons-bookshop.html)]

Whimsley Hall is never a salubrious place, but in the days
following Christmas it is truly disgusting. Mice chase spiders, earwigs
and silverfish over the piles of discarded plates and glasses that are
the inevitable aftermath of the annual party I throw for the villagers.
The children have played their last game of Pin the Tail on the Vicar,
and have vanished, thank God. I am sure some of the greedy little
bastards steal my silverware; I know that the older children use Hide
and Seek as an excuse to search through my erotica collection. And
their parents are worse; they pretend to be friendly but I know they
are only after the contents of my cellar, and to a one they seem to
have a huge capacity for drink and other forms of debauchery. But they
too are finally gone. People think I am fortunate, living in this
picturesque and rambling manor, but the duties of the landed gentry are
not easily shirked, and so year after year I spend the days between
Christmas and New Year's sitting at my desk with aching head and foul
breath. Usually I spend these days reading a book, but this year I do
not have a single one that takes my fancy. The reason is simple: I
refuse to buy my books from a certain popular bookshop in town. Small
wonder that as I sit, my mind is wandering back to a similar
post-Christmas event a few years ago...




I had decided, that day, to walk from Whimsley Hall down into the
village. I hoped that the unseasonably fresh air would clean away my
own hangover and would also get me away from the Hall while the
servants cleaned away the bacchanalian refuse. I would willingly help
them of course, but their nature is coarser than mine so it only makes
sense to leave them to it.  






I am a regular visitor to each of the village book shops and I
wanted to pick up a novel or two. We had a lot of bookstores in
Whimsley village until recently. One specialized in mysteries, one in
politics, one in books about my hobby (Mr. Babbage's _Books with a Difference (Engine_)), and there were a couple of second hand stores as well. Then there's [Words Worth](http://www.wordsworthbooks.com/) the general bookstore and [Heather's Big House O'Books](http://www.chapters.indigo.ca), a
big but crass place I avoid when I can, but with an undeniably good
selection. And if I'm in a hurry for a page-turner I can always pick up
a best seller at the supermarket (you didn't think we had a supermarket
did you? Oh yes, we're up to date in Whimsley village). So we were well
provided for. I really didn't think there was room for another book
shop, but I had heard from Google - my butler and the source of a
remarkable range of odd facts and fancies - of a new shop in town
called _Mr. Amazon's Bookshop_ and I decided, being the open-minded chap I am, to give it a try.  






Google had told me that Mr. Amazon has the most amazing selection
of books, so you can imagine how surprised I was when I walked in the
door. Mr. Amazon is famous now, so you probably know what his shop
looks like, but in case you haven't been there let me tell you. The
door is unprepossessing. Once inside there's a bare wooden floor. No
books, no shelves. It's always empty of people. There are a couple of
posters on the wall, and a short, trim middle-aged man, dressed smartly
but informally, sits straight-backed behind a high desk. That first day
I shook my umbrella to hide my confusion and nearly turned to leave,
but then I thought it would be rude just to walk out so I asked him a
question.






"Excuse me, I seem to have stepped into the wrong place. I thought this was a book shop."






"It is," said the man behind the desk. "And a very fine one I'm proud to say."





Was the man mad? I squinted at him though my monocle but he looked
calm enough. I gestured at the empty room and addressed him again.






"Well, most bookshops have - you know - books. You don't seem to have any at all! There's not a single shelf in sight!"





"On the contrary sir, we have the finest collection of books in the
village. We are aware of all books, we just don't have shelves. Is
there one you would like to see?"





"Not one in particular, I just thought I'd look around - see what
you specialize in, you know. See what your collection's like. But, I've
just realized I'm late for... something - got to be going. Toodle pip!"  







I turned to leave, but he spoke before I got out of the door.






"We are aware of all books sir. Any book you like, we have it. Is there one you would like to see?"





His words were so peculiar I decided that the butler was playing a
trick on me. He'd sent me here to see this batty little man as a joke.
Obviously the proprietor was touched in the head. I just shook my head
and exited.





I forgot all about Mr. Amazon's bookshop for a couple of months, and
then an odd circumstance found me making a second visit. My plumber, a
retired scholar, is a regular source of book recommendations. When I
ask her how she can stand dealing with the contents of Whimsley Hall's
bathrooms after studying Shakespeare's sonnets she just looks at me and
shakes her head and says "it's a long time since you were at a
university isn't it?" Anyway, she had told me about a new novel called _Special Topics in Calamity Physics_,
which was apparently a hit in America and which both she and her
husband had enjoyed. I'd been to a couple of the bookshops in the
village but they both said they hadn't got it yet. Disappointed, I was
on my way home when I realized I was walking right by Mr. Amazon's
Bookshop. Truth to tell, I was surprised to see it still there. "Maybe
it's actually got some books now", I thought as I walked in through the
door. And I was confronted with the empty, hardwood-floored room and
that funny little man sitting pertly behind his desk, just as before.




"Still no books I see?"






"On the contrary sir," he said. "We are aware of all books, we just don't have shelves. Is there one you would like to see?"  







The man was obviously run by clockwork or mad as a hatter, but I thought I'd amuse myself a little.






"Well actually there is. I'm looking for [Special Topics in Calamity Physics](http://www.amazon.com/Special-Topics-Calamity-Physics-Marisha/dp/067003777X) by Marisha Pessl. It's new and the other shops don't have it yet. Maybe you could point me to it?"  






I confess I smiled a little as I turned theatrically around, as if
scanning the shelves. But quick as a kingfisher the little man reached
under his desk, brought out a book, and held it out in front of him.
"Ah yes, a fine choice. Here it is. Two hundred and sixty four of our
customers have told us about this book, and 149 gave it more than three
stars out of five. Take a look."






I stepped forward and reached for the book, but he pulled it away.





"Sorry sir, you may not touch the books in our store, but feel free
to read the back cover as I hold it. Or I'll be happy to open it for
you to look inside."






I was surprised and a little offended, but at least he had the book.






"Never mind, I'll take it", I muttered, putting a few guineas on the desk. 






"Thank you sir. Good Day." And with that he put the book back beneath the desk.






"Aren't you forgetting something?" I said sharply. "My book?"






"No sir. We deliver our books. You will receive yours shortly. Good day. By the way, customers who bought _Special Topics in Calamity Physics_ also bought _The Secret History_ by Donna Tartt and _Absurdistan_ by Gary Shteyngart. Would you be interested?"






"I should think not! Just see to it that my book is delivered, that's all." And I stamped out furiously, cursing the difficulty of getting good service these days.


		
