---
author: Tom Slee
categories:
- blog archive
date: 2008-06-28 09:27:00
title: Why oh why can't we have a better academia?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I have been in a sour mood all day, and that is going to spill over into this mean-spirited post. Too bad.

The original reasons for my foul temper had nothing to do with online things or with academia, but then the Internet made it worse.

Reading Carnegie Mellon University's Cosma Shalizi (excluded from the title) is always enlightening and usually lifts my spirits, but today [he points us](http://cscs.umich.edu/%7Ecrshalizi/weblog/581.html) to a poor [article by Chris Anderson](http://www.wired.com/science/discoveries/magazine/16-07/pb_theory), editor of Wired Magazine. I made the mistake of following the link and my sour mood deepened. 

Then I see that Anita Elberse of Harvard Business School has actually looked at some data behind the same Chris Anderson's Long Tail hypothesis (please, don't call it a theory) and, not surprisingly [found it misguided](http://harvardbusinessonline.hbsp.harvard.edu/hbsp/hbr/articles/article.jsp?OPERATION_TYPE=CHECK_COOKIE&referer=/hbsp/hbr/articles/article.jsp&productId=R0807H&TRUE=TRUE&reason=freeContent&FALSE=FALSE&ml_subscriber=true&_requestid=13055&ml_action=get-article&ml_issueid=BR0807&articleID=R0807H&pageNumber=1). You would think that would cheer me up, but reading Anderson's response just ([here](http://conversationstarter.hbsp.com/2008/06/challenging_the_long_tail.html) and reprinted [here](http://www.longtail.com/the_long_tail/2008/06/excellent-hbr-p.html)) plunged me further into gloom. Why? Because although he loses this battle (if asked I will bore people with the details, but I really don't think there is a point), sloppy business journalism has won the war.

Face it. Chris Anderson now has people at _Harvard Business School_ of all places spending their valuable time following up his idle speculations. He comes up with a half-baked idea, has basically no data to support it, and yet here are academics - smart people, with tenure, real jobs and things to do - actually spending their time following up these idle daydreams; acting as his research assistants. What a waste.

And that's not all. Here are other people - like Princeton University's [Ed Felten](http://www.freedom-to-tinker.com/?p=1302), [Drew Conway](http://blogs.nyu.edu/blogs/agc282/zia/2008/06/the_hubris_of_the_end_of_theor.html) from New York University, [Fernando Pereira](http://earningmyturns.blogspot.com/2008/06/end-of-theory-data-deluge-makes.html) from the University of Pennsylvania and [John Timmer](http://arstechnica.com/news.ars/post/20080625-why-the-cloud-cannot-obscure-the-scientific-method.html) who teaches at Cornell - smart people who work in universities, and probably with families and friends who could use their attention - who feel they have to spend their time explaining a few of the reasons why he is wrong in his latest screed. And [here ](http://www.econtalk.org/#a003601)is Russ Roberts of George Mason University giving the man an hour of respectful time in his weekly economics podcast. And here I am (although I ain't no academic, that's my excuse) wasting my evening writing this junk.  
  
Journalists and popular science or technology writers should take the serious thoughts of others and communicate them in an interesting and attention-getting way. But now everything is back-to-front. How do a few stories from a business journalist set the research agenda of Harvard Business School and claim the attention of otherwise intelligent academics?

The intellectual agenda has been derailed by snake-oil sellers. Why has academia let it happen?

(Title, of course, stolen from the impeccable academic [Brad DeLong](http://delong.typepad.com/))


		
