---
author: Tom Slee
categories:
- blog archive
date: 2015-03-13 19:01:23
tags:
- airbnb
title: Yesterday in Airbnb
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				First, [this report](http://www.laane.org/airbnb-report) on Airbnb in Los Angeles, by the Los Angeles Alliance for a New Economy (LAANE), is fantastic, especially compared to Airbnb's [own study](http://blog.airbnb.com/airbnbs-positive-impact-in-los-angeles-2) from December. It mixes data with thoughtful commentary with investigative work that could only be carried out by someone who knows the city. (I did contribute a bit of help in the data collection area, but had nothing to do with writing or the report itself.) Here are some highlights.



	
  * Airbnb's report has this to say about its impact on neighbourhoods (in total):




<blockquote>Airbnb distributes economic impacts to neighborhoods that have not traditionally benefited from tourism spending. With Airbnb properties in more than 80 Los Angeles neighborhoods, Airbnb visitors are staying in and exploring places they might never have otherwise visited.</blockquote>




The LAANE report shows that the Airbnb business is, in fact, concentrated on areas that are already heavily affected by tourism: while "AirBnB has units listed throughout Los Angeles, but just nine of the City’s 95 neighborhoods are responsible for generating 73 percent of the company’s revenue." In tourist hotspot Venice, one in eight units are now Airbnb rentals.






	
  * 1010 Wilshire is a high end apartment building with 227 units in Downtown Los Angeles; but 20% of its units are now listed as tourist accommodation on Airbnb.

	
  * The host you see on the site, with a photo and personal note, may not actually be the host. "Danielle and Lexi" were two young women with "verified ID", but it turns out that they are just a front for Ghc vacation property rentals.


And there's a lot more. Worth a read if you have any interest in the subject. The report has been picked up by the [LA Times](http://www.latimes.com/business/realestate/la-fi-airbnb-housing-market-20150311-story.html#page=1), [Curbed LA](http://la.curbed.com/archives/2015/03/airbnb_neighborhoods_los_angeles.php), and more.

Elsewhere, Inside Airbnb has extended its beautiful maps to [Portland](http://insideairbnb.com/portland/). They have also collaborated with [Willamette Week](http://www.wweek.com/portland/article-24210-air_invasion.html) to chart the shape of Airbnb's business in the city, and the results will be familiar to readers of this site: Airbnb's story of being a site where "regular people occasionally rent the home in which they live" is misleading.

The real Airbnb story is gradually getting out there, of a site that uses the heartwarming stories of a few of its hosts to provide a cover for a growing cadre of professional renters using the site to avoid municipal regulations around safety (no fire inspections), zoning (driving gentrification of tourist areas), and taxes. It's good to see diligent, talented people like LAANE and Inside Airbnb push the debate forward.		
