---
author: Tom Slee
categories:
- blog archive
date: 2008-07-05 12:59:01
title: What do you say to your heroes? Serving petrol to Ernie Wise
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

The filling
station where I worked at weekends was quiet - it's closed now - and I
often spent much of my shift reading anything from [Judge Dredd](http://en.wikipedia.org/wiki/Judge_Dredd) comics
to the [The Worm Ourobouros](http://en.wikipedia.org/wiki/The_Worm_Ouroboros) to the unabridged _Count of Monte Cristo_ -
while using up my pay on sweets and listening to the top 40 countdown
on the transistor radio.

I can't remember what year it was when [Ernie Wise](http://en.wikipedia.org/wiki/Ernie_Wise)
and his wife Doreen Blythe stopped in to fill up their white Rolls
Royce but I only worked at the filling station in the late '70s, so I know it was when [Morecambe and Wise](http://en.wikipedia.org/wiki/Morecambe_and_Wise)
were among the most famous faces in the country. Their show was a
weekly family event for us. I doubt if the humour has aged well,
but I know I laughed at the Anthony and Cleopatra
sketch with Glenda Jackson until the pop I was drinking came right out of my
nostrils. 28 million people watching their Christmas specials couldn't all be wrong.

Of course, I recognized Ernie
Wise as soon as I approached the car but I was cool about it. No
fawning, because surely celebrities don't need people gasping at them
all the time. I just said "What'll it be sir?" and I filled the tank.
His wife needed cigarettes so they came in the shop and paid at the
till. I was more polite than usual but otherwise I tried to act like I
was just serving a regular customer.


...until they were almost out the door. Then I spoke up: "Excuse me
sir?" He turned. "I just wanted to say thanks. You've given me and my
family a lot of good times and a lot of enjoyment." He stopped for a
second, uncertain whether to offer an autograph or what I wanted, but
then he just said "Oh. Thank you." and I said "Pleasure to be of
service" and off he went.

Actually that's not what happened. 

In
reality I didn't say anything at all as he went out the door and maybe
that's just as well. But looking back I do wish I'd spoken up. Every
week for years Morecambe and Wise would come into our house. An hour
later they would leave, and we were always in a better mood than when
they entered. He deserved a thankyou for that, awkward or not.


		
