---
author: Tom Slee
categories:
- blog archive
date: 2006-07-23 00:36:10
title: Design change
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I've just changed the design at my [nonblog web site](http://www.tomslee.net).




Why? Well, because it was pretty hideous before, and also because I recently put together a [web site for my better half](http://www.slsupeene.net), and I thought my own place deserved a bit of spit and polish. I'm not really sure about the colour scheme, but I'll give it a week or so and see how it looks after that time.




**Update: **I just made a few more changes so it looks better in Internet Explorer. It still looks best in Firefox, but the differences are now pretty minor.




For anyone who cares about such things, the colour scheme was inspired by the [Dark Rose](http://www.csszengarden.com/?cssfile=/194/194.css&page=0) design by Rose Fu at the [css Zen Garden](http://www.csszengarden.com), which has lots of great ideas for anyone looking to design a site.




**Update 2: **I added fancier scrolling behaviour, for Firefox only, so that only the main column moves as you scroll the page (you have to look at one of the longer pages to see it, or have your browser in a small window). There are workarounds that let you simulate this CSS position:fixed behaviour in IE, but that seems like too much work.


		
