---
categories:
- Essays
title: "Transport: time for cities to lead"
author: Tom Slee
date: 2018-09-19
---



_Tom Slee, September 19, 2018, El País Series on Shared Mobility_

I learned a lesson a few weeks ago, when I spent a weekend in Montreal.
Long a bicycle-mad city, its nine-year-old Bixi ride-share program is
well used and convenient, with over 6,000 bikes sprinkled around its 500
docks throughout the city.[^fn:1] But what really makes the difference is
not so much the bikes themselves, or the docks, or the payment system,
as the separate bike lanes and 700 km of cycle paths that make it safe
to cycle around.[^fn:2] Without investment in infrastructure, the bikes
themselves would not make much difference.

The same goes in the Netherlands: the Dutch own more bicycles per person
than any other country in the world, and almost a quarter of the Dutch
population cycles every day.[^fn:3] In Amsterdam there are twice as many
bikes as cars on the street during rush hour. And the reason is the
roads: 35,000 km of dedicated cycling infrastructure (separate lanes)
and a low speed limit.

Infrastructure innovations make a difference. And while bicycles may not
be the future of transport, the lesson applies to other forms of big
city transport. It's a lesson worth keeping in mind with the flood of
transport stories that is coming from the technology industry.

Uber has changed the way many people get around cities. And Uber's
success has produced imitators; a whole generation of
technology-inspired transport visions from Silicon Valley and from
China. Shared bikes (docked and now dockless) and motorized scooters
share the headlines with pooled ridesharing, Elon Musk's tunnels and
driverless cars as the transport of the future. It can seem that transit
innovation is coming from technology companies and not from cities. But
appearances can be deceptive and in this case they are. It is cities
(city governments and citizens) who will shape the transit of the
future, and they should look to each other for inspiration rather than
to Uber and Tesla. Because the challenge is not so much about vehicles
as about space: not so much about cars as about roads.

When Uber moved from being a status-conscious “everybody's private
driver” to being a mode of mass transit, it promised a sustainable
future. We would need less parking space and would live more
economically as private cars faded away; replaced by transport as
reliable as running water. And they would help cities be more efficient
by sharing their traffic flow data, helping to optimize the use of our
roads. But while Uber has grown rapidly year on year, it is not a
template for healthy transit futures.

One reason is that, remarkably, Uber continues to be unprofitable. With
every quarter's financial results the path to profitability seems less
certain. Maybe Uber has grown not just because of its revolutionary
application, but because it subsidizes car rides.[^fn:4] Sooner or later,
it is going to have to make a profit; for commuters, cost matters, and
the idea that everyone can ride an Uber to work may not make economic
sense in the long run.

A second reason is that Uber is increasingly leading to
congestion.[^fn:5] In major cities, Uber is competing with more
space-efficient mass transit, not complementing it as it promised. New
York City is the best studied city, where 60,000 Uber and Lyft vehicles
are slowing the traffic by about 30%. These vehicles spending as much
time driving empty as a regular yellow cab, despite the high-tech
matching algorithms, and put 2.8 new miles on the road for each mile of
personal driving removed.[^fn:6] Even the shared services such as Uber
Pool have similar statistics. This is no way to build a sustainable
transport infrastructure, and self-driving vehicles would have exactly
the same problem. Smartphones are part of our present and our future,
but they won't fix traffic.

For more important innovation, look to Mexico City: since it pioneered
its Bus Rapid Transit (BRT) with dedicated lanes and frequent service,
its steadily growing fleet (now over 700 buses) move 1.8 million people
a day.[^fn:7] In New York City Uber provides 6 rides per vehicle every
day; in Mexico City the BRT provides 2500 rides per vehicle. Other forms
of mass transit are similar: in London, 2 million people per day ride on
about 700 tube trains for over 2000 rides per vehicle. When it comes to
moving lots of people in a big city, mass transit is the way.
Congestion, as traffic expert Jarrett Walker likes to say, is a matter
of urban geometry.[^fn:8]

If we are looking to a future of bigger cities, denser city centres,
then we need to make mass transit cool again, and throw off its shabby
image (especially in North America). It will be investment in roads,
paths, and buses that will improve our cities, and those will come from
city governments looking to each other, learning from each other's
innovations and experimenting with new variations. When it comes to
transit, the ballot box is a more important technology of change than
the smartphone.

[^fn:1]: “BIXI Montréal.”
[^fn:2]: Bruemmer, “Montreal's Bike Path Network: Mind the Gaps.”
[^fn:3]: “Dutch Cycling Figures | BICYCLE DUTCH.”
[^fn:4]: Horan, “Will the Growth of Uber Increase Economic Welfare?”
[^fn:5]: LeBlanc, “Studies Are Increasingly Clear.”
[^fn:6]: Schaller, “The New Automobility: Lyft, Uber and the Future of American Cities”; Schaller, “Unsustainable? The Growth of App-Based Ride Services and Traffic, Travel and the Future of New York City.”
[^fn:7]: “Mexico City Metrobús.”
[^fn:8]: Walker, “Does Elon Musk Understand Urban Geometry?”
