---
author: Tom Slee
categories:
- blog archive
date: 2007-07-03 12:06:12
title: Happy Shoes II
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

At the end of the [previous post](http://whimsley.typepad.com/whimsley/2007/07/happy-shoes.html) it
looked as if, so long as enough consumers are prepared to
pay a premium for ethically-produced goods, Happy Shoes should be able
to make a profit, pay its workers better than Sweatshoes, and satisfy
customers all at the same time.




But -- contrary to what Potter & Heath claim -- it is difficult for companies to make money by selling
"shoes made by happy workers" because "ethical production" is a [credence good](http://en.wikipedia.org/wiki/Credence_good). When you buy shoes, you can tell if your new shoes fit well, you
can tell what they are made of, and you can tell whether you like the style. But you can't tell what the person making them got paid.
Like the benefits of fluoridated toothpaste and organically-grown vegetables,
it's something you basically have to take on trust.





This lack of information provides an opening for unscrupulous
vendors. To understand this market we have to think not only about Sweatshoes
offering their $100 shoes and about Happy Shoes offering their $120 pair, but
also about a third company. "Ethical Feet" comes to town
with some fine-sounding words about their commitment to fairness and decency,
offering to sell you an ethically made pair of shoes for $115 -- $5 less than
Happy Shoes. It sounds like a good deal -- the benefit of ethical consumption, and an extra $5 left in your pocket.   






But the difference is that Ethical Feet doesn't
actually pass on any of the extra $15 you pay to the people making the
shoes. It just keeps your money. Ethical Feet would sell the shoes
cheaper than Happy Shoes, but make more profit -- $25 profit per pair
rather than $20.   






It looks like Ethical Feet may drive Happy Shoes out of
business by making unverifiable false promises, but the story does not stop here. This is not a tale of corporate trickery and consumer
stupidity. As George Akerlof [writes](http://nobelprize.org/nobel_prizes/economics/articles/akerlof/index.html): this problem of trust is "as old
as markets themselves. It concerns how horse traders respond to the natural
question: "if he wants to sell that
horse, do I really want to buy
it?"




Smart consumers who are
prepared to pay more for ethically produced goods are still not
prepared to be suckers. We are not going to pay $115 or even $120 for a
pair of shoes just because a company says they
are made by happy workers -- a claim we cannot verify. In a market of
smart consumers wanting to buy shoes made by happy people, the $115 Ethical Feet shoes _and the $120
Happy Shoes _- stay on the shelf. As consumers we can't tell the difference between Ethical Feet and Happy Shoes, and we know that a company that carried out its promises is vulnerable to unscrupulous competition.




The company that stays in business is Sweatshoes. It pays cheaply and
sells cheaply, and as consumers we pay $100. We may not feel good about
this, but at least we are not being tricked. The end result is just the
same as if we didn't care about the salaries at all. As consumers, it
seems we are not sovereign when it comes to ethical production.




The next post will probably deal with ways around this problem.


		
