---
author: Tom Slee
categories:
- blog archive
date: 2015-09-16 22:52:18
tags:
- '1099'
title: 'Sharing Economy: Three Critical Pieces'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Nick Carr [writes](http://www.roughtype.com/?p=6527) about sharing power drills, following up on (my mention yesterday of) Sarah Kessler's article about this prototypical sharing transaction, following the drill meme back to its origin and adding some interesting reflections on the complexity of sharing transactions.


<blockquote>A drill is a fairly inexpensive commodity. It’s easy to buy one, and it doesn’t take up much room in your house. And once you own it, you can use it any damn time you please. (The upside of low utilization is high availability.)... Buying and owning a drill, in other words, doesn’t involve much in the way of transaction costs, either up-front or ongoing.

Now if, instead of buying the drill for yourself, you decide to share it with some other people, whether through a neighborhood co-op or some rental arrangement, suddenly you face all manner of transaction costs. You have to hash out the financial arrangements, you have to figure out where the drill happens to be at the moment you need it, and you have to go out and pick it up and bring it home (burning gas, perhaps, as well as time). And if somebody else wants to use the drill at the same time you need it, then you’re in for some negotiations and probably some irritation. And if the drill breaks or gets lost (or a “little screw head” gets misplaced), a whole new set of transaction costs kick in. And, don’t forget, your knuckleheaded neighbor never recharges the battery after he uses the drill, so you’re going to wedge yourself into the closet only to find that the drill is dead. More irritation.

Transaction costs, in this context, might also be called pain-in-the-butt costs, and pain-in-the-butt costs don’t have to get very high before you say, “Screw it, I’m buying a drill.” You accept, even welcome, low levels of utilization in order to avoid onerous transaction costs. And, yes, you are being totally rational. Utilization is not everything.</blockquote>


Read, as they say, the whole thing.

Jathan Sadowski and Karen Gregory have a really good piece in the Guardian asking "[Is Uber's ultimate goal the privatisation of city governance?](http://www.theguardian.com/technology/2015/sep/15/is-ubers-ultimate-goal-the-privatisation-of-city-governance)" It is sparked by Uber's experiments in shared rides, and schedule rides through fixed stops, in San Francisco. Some have argued that Uber is looking to privatize public transport, but Sadowski and Gregory think there is something else:


<blockquote>the company wants to be involved in city governance – fashioning the new administrative capacities of urban environments. Rather than follow government rules, like any other utility, Uber wants a visible hand in creating urban policy, determining how cities develop and grow, eventually making the city itself a platform for the proliferation of [“smart”, data-based systems](http://www.theguardian.com/technology/2014/jul/20/rise-of-data-death-of-politics-evgeny-morozov-algorithmic-regulation).</blockquote>


FWIW I think they are on the right track: as cities become data-driven, city governments will increasingly be looking to new software systems to run them; but why should cities continue to be run by governments? Why not just outsource the whole thing to Silicon Valley, and specifically Uber, where the expertise in number crunching and algorithmic delivery lies? So long as we think in terms of a consumer model of citizenship where we consume services, rather than a democratic model in which we participate in the shaping of our cities, the prospect is dangerously tempting.

Finally, Michelle Chen in The Nation tells us " [This Is How Bad the Sharing Economy Is for Workers](http://www.thenation.com/article/this-is-how-bad-the-sharing-economy-is-for-workers/)". It's a thorough look at the labour issues around the "gig economy", built around a new report by the National Employment Law Project (NELP) called "[Rights on Demand](http://www.nelp.org/publication/rights-on-demand/)". Chen says the report is


<blockquote>focused on regulating the so-called “on-demand economy” of tech-driven gig employment, to put forward concrete policy models that can help restructure the “1099” contractor relationship to offer workers greater protection. One potential model is the statutory employee framework, under which contractors are for certain regulatory purposes considered workers, generally for tax laws. NELP notes that local and state policymakers can expand this structure to provide “portable” benefits by “directly requir[ing] that companies that use IRS-Form-1099 workers abide by labor standards such as the minimum wage and others, and pay into Social Security and state workers’ compensation and unemployment insurance funds.”</blockquote>


She looks at the prospects for workers' rights in the sharing economy, and with a lot of links she points out some places where action is being taken to push back against the efforts of some sharing economy companies to push all the risk and uncertainty of their business onto the shoulders of their service providers. A valuable resource.



		
