---
author: Tom Slee
categories:
- blog archive
date: 2006-11-21 18:49:17
title: Tuangou
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Start with a long history of taking pride in haggling, put up some
websites for these hagglers to team up, and what you get is tuangou: a clever form of collective action among consumers.



<!-- more -->


I saw mention of it just now in an interesting piece by [Rob Horning](http://www.popmatters.com/pm/blogs/marginalutility_post/7954/p/). He is writing about spontaneous collusion and price targeting among companies trying to set consumer against consumer:  






<blockquote>

> 
> But then I wonder if that isn’t the real trap here, the false
satisfaction one feels in “beating” the system that has in fact
contained you. If I let myself glory in other consumer’s stupidity or
ignorance, then I have given myself incentive to keep them ignorant and
aligned myself with the retailers rather than those like me, fellow
consumers. If everybody follows suit, then we remain collectively
ignorant at war with each other rather than with the retailers trying
to stratify and bamboozle us. (That’s why [tuangou](http://en.wikipedia.org/wiki/Tuangou)
seems strangely appealing in theory.) This war of all against all
caters to our individualism and reinforces competitiveness as the
default mode of social interaction among peers. Shopping, which seems
more and more the primary social activity, becomes a zero-sum game
among consumers; we have no reason to cooperate. I gain when you lose.
I fly cheaper when you pay more for your ticket. And I can think I’m a
deserving winner and you are a deserving loser. This isn’t a big deal
with airline tickets, when it comes to our annual salaries or general
class prerogatives, it becomes a bigger deal. This kind of thinking
leads people to conclude that the poor are simply stupid rather than
structurally disadvantaged; being poor, as this Ezra Klein [post](http://ezraklein.typepad.com/blog/2006/11/the_difference_.html)
shows, is matter of having no safety net, no margin for error or bad
luck in situations that are already stacked against you due to
inherited disadvantages.
> 
> 
</blockquote>




So what is tuangou? Well Wikipedia has [an entry](http://en.wikipedia.org/wiki/Tuangou) of course, which says it is "team buying":




<blockquote>Several people - sometimes friends, but possibly
strangers connected over the internet - agree to approach a vendor of a
specific product in order to haggle with the proprietor as a group in
order to get discounts. The entire
group agrees to purchase the same item. The shoppers benefit by paying
less, and the business benefits by selling multiple items at once.
> 
> </blockquote>

Wikipedia points to [this article](http://www.economist.com/printedition/PrinterFriendly.cfm?story_id=7121669) from the Economist.




<blockquote>

> 
> ON AN otherwise
quiet Friday afternoon in Guangzhou, a city in southern China, 500
shoppers gather outside a Gome electrical superstore in the downtown
district. They arrive en masse at the designated time—June 16th at
4pm—that they had previously agreed online. Several hours later, they
emerge clutching boxes, having secured 10-30% discounts on cameras, DVD
players and flat-screen televisions. “It was great,” says Fairy Zhang.
“We just bought an apartment and this way we can afford nice things for
it.” The previous weekend, over 100 locals visited Meizhu Central, a
well known furniture outlet, to haggle over the prices of kitchen
cabinets and dining-room furniture...
> 
> 

> 
> Team buying
turns haggling, a tradition in China, into an art-form. That such
aggressive consumer behaviour has arisen in a country without much of a
consumer economy and weak individual rights is less surprising than it
might seem. In the countryside there are more and more organised
protests against government corruption and dictatorial landlords, with
even poor people using technology like the internet and mobile phones
to help. Now their urban, middle-class brethren are adopting their
tactics—if only for shopping. However, if China's economy ever slumps,
urban consumers could use their organisational skills to confront the
government directly. Beijing might be watching the spread of team
buying with trepidation.
> 
> </blockquote>


		
