---
author: Tom Slee
categories:
- blog archive
date: 2014-05-19 03:20:58
title: Out and About
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Despite the slack posting here (but I do have some things I'm working on, honest), I am flattered that people still want to talk to me about sharing economy and related topics. Here are some recent posts and articles where I appear.



	
  * I'm going to be talking sharing with a panel of people at [Personal Democracy Forum 2014](https://personaldemocracy.com/conferences/nyc/2014). Unusually for a technology-focused conference, over half the speakers are female, which is great. The blurb for my pane; says "_Defining and Debating the "Sharing Economy"_ (Thurs June 5, 3:30-4:30pm): Tom Slee, James Slezak, Denise Cheng, Adam Greenfield, Nancy Scola (moderator). Is there such a thing as the "sharing economy," or are some people more interested in sharing, while others are interested in the economy? How can we usefully distinguish between "sharing economy" enterprises that empower their users and those that may actually seek to exploit them? A critic [that's me], an advocate and an academic observer will take a close look at these questions and try to get to the bottom of what is good and what is hype about this emerging phenomenon."

	
  * Terry Dawes of [CanTech Letter ](http://www.cantechletter.com/2014/04/jeremy-rifkins-views-future-neat-simple-wrong/)is right. Jeremy Rifkin's views on the future are indeed, neat, simple, and wrong.

	
  * Jon Zerolnik of LA-based investigative website _Capital and Main_ interviews me about [Couchsurfers and Billionaires](http://capitalandmain.com/couch-surfers-and-billionaires-on-the-sharing-economy/).

	
  * Thanks also to Houston Davidson of the College Hill Independent for talking to me about [Sharing for Money](http://www.theindy.org/260).

	
  * The always-excellent Nancy Scola [writes](http://nextcity.org/daily/entry/sharing-economy-expert-arun-sundararajan) about Arun Sundararajan and quotes me.

	
  * Hey, look! My non-earth-shattering 1988 paper with Preston McDougall on "The correspondence between Hückel theory and _ab_ _initio_ atomic charges in allyl ions" is now [online](http://www.nrcresearchpress.com/toc/cjc/66/11)!

		
