---
author: Tom Slee
categories:
- blog archive
date: 2014-09-24 02:50:49
title: Uber Drivers Organizing
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				A short note about the ways that Uber drivers are getting increasingly vocal and organizing to push back against the company and its frequent rate cuts, policy changes, and no-tip policy. This post lists only American events.

**Protests**



	
  * In Los Angeles, drivers [protested](http://losangeles.cbslocal.com/2014/09/02/uber-defends-slashing-drivers-rates-amid-la-protest/) fare cuts. Uber says they will make more money (because of more rides) but never backs that claim up. It's hard to think why drivers would protest if they were better off.

	
  * In New York, up to a thousand drivers [protested](http://www.slate.com/blogs/moneybox/2014/09/12/uber_drivers_strike_they_protested_cheap_uberx_fares_uber_backed_down.html) over rule changes, fare cuts, [and](http://www.businessinsider.com/ubers-drivers-say-they-dont-get-any-tip-money-from-all-inclusive-fares-2014-9) Uber's no-tip policy. And it looks like they got Uber to back down on some of their policy changes.

	
  * The Washington Post has [a good piece](http://www.washingtonpost.com/local/trafficandcommuting/some-uber-drivers-say-companys-promise-of-big-pay-day-doesnt-match-reality/2014/09/06/17f5d82c-224a-11e4-958c-268a320a60ce_story.html) about the challenges drivers face.

	
  * After a protest over fare cuts in June, Seattle drivers took to [honking their horns](http://slog.thestranger.com/slog/archives/2014/08/29/uber-drivers-honking-their-horns-in-downtown-seattle-to-protest-pay-cut) in August.


**Legal challenges**



	
  * In Boston, Attorney Shannon Liss-Riordan is [taking on Uber](http://www.bostonmagazine.com/news/blog/2014/06/26/labor-lawyer-files-lawsuit-uber-unfair-practices/) over its claim that drivers are not employees.

	
  * In San Francisco, a lawsuit has been [given the go-ahead](http://www.cnet.com/news/are-ubers-gratuity-fees-misleading-judge-says-let-court-decide/) over Uber's gratuity policy.

	
  * Meanwhile, a [San Francisco ruling](http://www.bizjournals.com/sanfrancisco/blog/techflash/2014/08/independent-contractor-ruling-fedex-uber-lyft.html) that FedEx drivers really are employees (not independent contractors) may have an impact on Uber down the road, as a big part of its business model is to avoid any of the commitments that go with providing actual jobs.


**Online Talk**

If you want to get a glimpse into how Uber drivers are thinking, there are active forums at [UberPeople.net](http://uberpeople.net) and on a [reddit subforum](http://www.reddit.com/r/uberdrivers/). See, for example, [this description](http://uberpeople.net/threads/driving-in-la-since-the-latest-pay-cut.2388/) of driving in LA since the most recent rate cut.		
