---
author: Tom Slee
categories:
- blog archive
date: 2007-02-13 21:49:35
title: How should we link to books?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Most people, when they mention a book and want to link to something about that book, link to Amazon. It's easy and it's become the norm.




But I don't like it. Neither, unsurprisingly, does Dave from [How to Furnish a Room](http://howtofurnisharoom.blogspot.com/). I've noticed he links to Powells web site, which is cunning. People can read about the book, but Powells (US based) does not compete with the Words Worth behemoth. Linking to Amazon has made the Amazon page the canonical page for many books and encourages us all to think "buy book, go to Amazon" and if we all do that then where do we browse in the real world? What's an independent bookstore aficionado to do?




But what's the alternative? Linking to Powells solves the competition problem, but it's clearly a bit of a slapdash fix. Usually I try to link to the publisher's site for a book, but that can take a bit of work to locate in some cases or in the case of older, out of print books. I've heard there are networks of independent bookstores that provide something similar, but I've not found it yet.




Good ideas - hell, any ideas - welcome.


		
