---
author: Tom Slee
categories:
- blog archive
date: 2008-03-24 21:30:25
title: The Anarchist in the Library
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[_The Anarchist in the Library_](http://www.perseusbooksgroup.com/basic/book_detail.jsp?isbn=0465089852), Siva Vaidhyanathan, Basic Books 2004.

* * *

Siva Vaidhyanathan (see [here](http://www.googlizationofeverything.com/) and [here](http://www.sivacracy.net/)) sees the central problem of the Internet and of society as a whole, as the tension between decentralization/freedom/anarchy and centralization/control/oligarchy.

<blockquote>The great challenge in the new century is to mediate between two divergent trends -- anarchy and oligarchy. In the war between distribution and concentration of information, the issues and conflicts seem intractable. [xvii]
> 
> </blockquote>

In the world of the Internet, at least in the years leading up to 2004 when the book was published, these poles of anarchy and oligarchy manifest themselves technologically. Anarchy is the "ideology of peer-to-peer systems" such as the file-sharing and media-sharing networks that have followed Napster; it is characterized by a fluid, decentralized architecture in which "all the 'thinking'.. happens at the end point" and in which there is "no discernible command-and-control system" [17]. On the other side, digital rights management is the technology of oligarchy, imposing controls on what you can and cannot do with the software and media that you buy (or, increasingly, license). I don't usually buy the technology-determines-behaviour line, but his discussion of what it means for a technology to "have an ideology" is the best I've read, and is well illustrated by the distinction between technologies that operate on the basis of protocols (handshakes, conventions) and those that work on the basis of controls. 




When I first picked up this book (from my library) I assumed that the author was another techno-utopian and that he is firmly on the side of freedom and anarchy over control and oligarchy (as who but the most unromantic of us could not be)? Not unreasonable, given chapter titles like_ Hacking the Currency_ and _The Peer-to-Peer Revolution and the Future of Music_, but wrong. In fact, although his heart is with the anarchists, Siva Vaidhyanathan is best described as a librarian. Not as in somebody who works in a library, but as in someone who is a fan of libraries:

<blockquote>Librarians should be our heroes. The library is not just functionally important to communities all over the world; it embodies Enlightenment values in the best sense. A library is a temple devoted to the antielitist notion that knowledge should be cheap if not free -- doors should be open. Supporting libraries -- monetarily, spiritually, intellectually, and legally -- is one of the best things we can do for the life we hope to build for the rest of the century. [Page 119]
> 
> </blockquote>

Libraries seem anachronistic -- if they did not already exist, they could not be created now (in North America anyway) -- and yet they are among the most popular of institutions. People make jokes (deserved or not) about the service of the post office, the inflexibility of government, and the so on, but no one (well, apart from [Seinfeld](http://www.imdb.com/title/tt0697721/)) pokes fun at libraries. Even [some libertarians](http://www.marginalrevolution.com/marginalrevolution/2007/09/library-appreci.html), who see any path laid by the state as a road to serfdom, love libraries. Our [local](http://www.kpl.org/) [libraries](http://www.wpl.ca/) are always busy, and after a bad patch some time ago appear to be thriving with their mix of Internet access, DVD and CD rentals and, of course, loads of books. The popularity of the library surely comes from its nature as patron-focused but not commercial (no "consumers" here) and state sponsored but not monopolistic. It is populist and yet highbrow. 




In the end Vaidhyanathan takes a dialectical stance and rejects both anarchy and oligarchy in favour of the library - a civic, noncommercial, open and public model. I didn't see this coming until well into the book, which after the first couple of chapters is more a set of essays around a common topic than a sequential argument. I thought he was heading towards one more simplistic agenda ("information wants to be free" anyone?) but he pulls himself back from the brink and ends up writing [185] "The heart of my argument in this book is a call for modesty and patience" and this:

<blockquote>The urge to break heads, to do the bidding of oligarchy by any means necessary is intimately linked to specters of anarchy. The urge towards anarchy depends on oligarchic abuses. Each creates the conditions that allow the other to thrive. The question for us in the twenty--first century should not be choosing anarchy or oligarchy by constructing and maintaining systems that discourage both. Anarchy is a reaction, not a vision or solution that can produce the best society and the best human future. [187]
> 
> </blockquote>

One of the reasons he pulls back is a debate with Randy Cohen of the _New York Times_, which he describes with admirable honesty [63]. 

<blockquote>"The history of popular culture is a continuous struggle on the artists' part not to get robbed... it seems to me that what MP3 [digital music] does is democratize the ability to rip off an artist," Cohen wrote to me. "And what's particularly galling is that you not only want to do it, you want to be praised as a social progressive when you do."  
He got me. That's my schtick. By the guiding principles Cohen deployed in our peer-to-peer debate, I had no escape. He considered copyright to be an artists' right and concern; I consider the chief player in the copyright system to be the corporation.
> 
> </blockquote>

The artists' struggle continues. The commercial oligarchs do whatever they can to avoid paying artists, as the Hollywood writers' strike showed and as [recent press](http://www.nypost.com/seven/02272008/business/infringement__99428.htm) about royalty awards not being passed on to artists makes clear. But the free-use techno-anarchists exploit artists too. Greatest Living Englishman Billy Bragg [writes](http://www.nytimes.com/2008/03/22/opinion/22bragg.html) in the New York Times about how he advised Michael Birch, the founder of social networking site Bebo.com, on how to handle artistic content on the site (via [Nicholas Carr](http://www.roughtype.com/archives/2008/03/meanwhile_back.php)). Bragg was angry that while artists contributed to the site, Michael Birch sold it to AOL for $850million and the artists got nothing. Here is part of his op-ed:

<blockquote>He was hoping to expand his business by hosting music and wanted my advice on how to construct an artist-centered environment where musicians could post original songs without fear of losing control over their work. Following our talks, Mr. Birch told the press that he wanted Bebo to be a site that worked for artists and held their interests first and foremost.
> 
> 

> 
> In our discussions, we largely ignored the elephant in the room: the issue of whether he ought to consider paying some kind of royalties to the artists. After all, wasn’t he using their music to draw members — and advertising — to his business? Social-networking sites like Bebo argue that they have no money to distribute — their value is their membership. Well, last week Michael Birch realized the value of his membership. I’m sure he’ll be rewarding those technicians and accountants who helped him achieve this success. Perhaps he should also consider the contribution of his artists. 
> 
> 

> 
> The musicians who posted their work on Bebo.com are no different from investors in a start-up enterprise. Their investment is the content provided for free while the site has no liquid assets. Now that the business has reaped huge benefits, surely they deserve a dividend...
> 
> 

> 
> If young musicians are to have a chance of enjoying a fruitful career, then we need to establish the principle of artists’ rights throughout the Internet — and we need to do it now. 
> 
> </blockquote>

Instead of cheering for one side or the other, Vidhyanathan's book foresees and acknowledges both these problems. And problems they are. He does not offer clear or simple solutions, but he points us thoughtfully in the right direction, and that's a very valuable contribution. So I definitely recommend the book, even though I wish it were a bit less scattered than it is (and that it had a better index). It's an exploration, not a recipe for the future, and has the rough edges that come with that territory, but there is a lot of food for thought in the pages.




_The Anarchist in the Library_, written in 2004, is already a bit outdated. Not the author's fault of course, but it is already odd to read a book about the Internet that has no mention of Wikipedia and no index entry for Google. These recent developments have changed the nature of the Internet. Peer to peer networks are still around, but I don't think they are the defining feature of the Internet. If we think of music we think of iTunes, not Napster; if we think of books we think of Amazon; if we think of social networks we think of Facebook and MySpace. None of these are peer-to-peer: they are centralized technologies built on the basis of controls, not protocols. Software architecture is often described as a stack, and while the low-level plumbing of the Internet remains a peer to peer protocol, the higher levels of the stack are "platforms" or client-server models of request and response. The techno-capitalist digirati have moved happily onto such platforms, and the centralization of ownership that they carry with them. In the era of [utility computing](http://www.nicholasgcarr.com/bigswitch/), peer-to-peer networks appear to be on the wane.




There is one other place in which I think Vaidhyanathan gets it wrong. He underestimates the role of information asymmetries and transaction costs. He says that "Major record labels perform four basic tasks: production, distribution, price fixing, and gatekeeping" [48]. But there is a fifth, which is promotion. Simply putting a record on the Internet is hardly more effective than playing your music on your front lawn - the problems of finding something no one knows exists are far greater than he credits. One major function of libraries, after all, is to match readers and books ("Every reader his/her book" in one of Ranganathan's [five laws of library science](http://www.slais.ubc.ca/COURSES/libr517/03-04-wt2/projects/ranganathan/contri.htm) -- thanks John). When Vaidhyanathan tells a journalist that African musicians don't need record companies because "The artists can do it all themselves for less than $10,000" he is naive. Billy Bragg's friends on Bebo did the same, and it got them nowhere. Others have proclaimed this line before - for example Chris Anderson in [my least favourite book](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html) talks about the band Birdmonster who eschewed labels

<blockquote>Label were calling with deals, but Birdmonster turned the offers down. As [lead singer Peter] Arcuni put it, “We’re not anti-label in principle, but the numbers (risk vs. reward) didn’t add up.”
> 
> A music label exists primarily to fulfill four functions: 1) talent scouting; 2) financing (the advances bands get to pay for their studio time is like seed capital invested by a venture capitalist); 3) distribution; 4) marketing. 
> 
> 

> 
> From Birdmonster’s perspective, they didn’t need that.
> 
> </blockquote>

Well, apparently [they do now](http://www.longtail.com/the_long_tail/2008/03/follow-up-a-lon.html). The problem is that so much of culture is governed by asymmetric information, information cascades, and network effects. You don't know what a book is going to be like until you buy it, so simply knowledge of the existence of a book is insufficient - you need recommendations and reliable ones at that. I've gone on about this in various ways [here](http://whimsley.typepad.com/whimsley/2008/03/long-tail-of-ne.html) and [here](http://whimsley.typepad.com/whimsley/2007/04/predicting_hits.html) and [here](http://whimsley.typepad.com/whimsley/2006/07/movies_nobody_k.html). His neglect of these forces is one of the reasons I thought he was heading down the techno-utopian path, but as I say he ends up, thankfully, rejecting the "California Ideology" [155] in favour of something less catchy, less simple, but more hopeful.


		
