---
author: Tom Slee
categories:
- blog archive
date: 2008-01-21 20:28:38
title: "\"The Big Picture, Which Is That There Isn't Any\"*"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Four related observations:




  * [Kieran Healy writes](http://crookedtimber.org/2008/01/14/opt-out-organ-donation-in-the-uk/#more-6575) that rates of organ donation depend less on "this or that policy in general" (markets vs donations, presumed consent vs. informed consent) than on the organizational underpinnings of the procurement system. "Reform of the rules governing consent is often accompanied by an overhaul and improvement of the logistical system, and it is this—not the letter of the law—that makes a difference. Cadaveric organ procurement is an intense, time-sensitive and very fluid process that requires a great deal of co-ordination and management. Countries that invest in that layer of the system do better than others, regardless of the rules about presumed and informed consent."


  * [Dani Rodrik writes](http://rodrik.typepad.com/dani_rodriks_weblog/2008/01/second-best-ins.html) that the level of economic growth among underdeveloped countries depends on adopting a "second-best mindset". It is wrong to presume, as the IMF does, that "it is possible to determine a unique set of appropriate institutional arrangements ex ante and [view] convergence towards those arrangements as inherently desirable" or that there is a single set of "best practices" that, so long as you follow them as closely as you can, will lead to success. Instead, things go better if you focus on the particularities of an individual country and design around those. 


  * [Margaret Wente talks](http://www.theglobeandmail.com/servlet/story/LAC.20080115.COWENT15/TPStory/TPComment/?query=) to Howard Fuller of Milwaukee's school voucher system. He points out that the success or failure of the program has a lot to do with how it is implemented in each individual school and not so much with the overall framework.


  * [My brother](http://dorsetdipper.blogspot.com/) tells me that the British High Street now has shareholder-owned stores (Marks & Spencer etc) next to stores owned by private funds (Debenhams) next to worker-owned co-ops (John Lewis). Perhaps the success or failure of a company depends less on the ownership model and more on other details.



The common thread is that the big decisions and big ideas make less of an impact than the low-level, detailed specifics of each situation. Faced with a big strategic choice between A and B, many aspects of the world are not like this  
  
|--------A---------| |---------B---------|  
  
but are more like this:  
  
|--------A---------|  
|---------B---------|  
  
You can take either A or B and still be a success or a failure.  
  
It's a small step from there to saying that people at the top of large organizations (whether they be governments or countries) have surprisingly little influence and that we should not pay much attention to broad pronouncements and grand visions. It's people dealing with everyday problems that we should pay attention to.   
  
Or, as George Bernard Shaw said "The golden rule is that there are no golden rules".  
  
* The title comes from Jon Elster, responding to a [review by Aaron Swartz](http://www.amazon.com/review/R1VMC7GVLZRD4I/ref=cm_cr_dp_cmt?%5Fencoding=UTF8&ASIN=0521777445#wasThisHelpful) of his book "[Explaining Social Behavior](http://www.cambridge.org/catalogue/catalogue.asp?isbn=9780521777445&ss=fro)"  



		
