---
author: Tom Slee
categories:
- blog archive
date: 2011-08-29 23:34:57
title: Media Disruption Exacerbates Revolutionary Unrest? Notes.
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

In the New York Times [today](http://www.nytimes.com/2011/08/29/business/media/in-times-of-unrest-social-networks-can-be-a-distraction.html), there's a piece about a conference paper  by Navid Hassanpour, "Media Disruption Exacerbates Revolutionary  Unrest: Evidence from Mubarak's Natural Experiment" {[link](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1903351)}. I took a  look: here's some immediate reactions.




The theoretical part of the paper is yet another cascade model of  protest, a kind of Granovetter++, which comes down to this:






  * Individuals are nodes in a network, and face a decision of  protesting or not. Each has a personal threshold for action (in  terms of the activity of their neighbours) and some small portion  have a zero threshold, acting as seeds for the dynamics. 


  * Individuals update their threshold based on the level of activity  among their neighbours; the more their neighbours are protesting,  the more likely they are to join in. 




The dynamics of the model is the spread of action through the network,  a cascade caused by each actor becoming first more prone to action as  those around them take up action, and then joining in themselves.




A "media disruption" reshapes the network – different media lend  themselves to different network structures – and the dynamics of this  reshaped network will be different, leading to different regions of  activity and inactivity.




For many networks, one equilibrium is for almost everyone to be  inactive, as each actor has a high threshold for action absorbed from  their inactive neighbours. A set of dense connections can freeze  regions of a network in states of inactivity: each individual may come  in contact with active individuals, but the numerous connections to  inactive individuals keeps them mute.




Individuals in a less dense network have a greater possibility of  becoming active in response to a population of activists because they are less restrained by the inactive people around them, and this is  the basic mechanism for the "media disruption exacerbates unrest"  thesis.




So it's a bit like an Ising model of magnetism with ferromagnetic  coupling: ions can be spin Up or Down, and their orientation depends  on the orientation of their neighbours. One difference: ions don't  come with different tendencies to choose Spin Up. It's a simple  model - it doesn't try to model the availability of information  itself, or have anything to say about political preferences or  economic situation beyond the threshold for action. But it does bring  in the relationship between network structure and outcome.




There is an empirical part to the paper as well. There is a survey of  past revolutions and their relationship to media penetration, which  does not convince one way or another (it seems to me there is a  conflation of social media and mass media that extends throughout the  paper). More interestingly, Hassanpour looks at the progress of the Egyptian  uprising and contends that when the government shut down the Internet and phone networks on  January 28 it produced, instead of the single gathering at Tahrir  Square that had been in progress for several days, eight separate  protests in different parts of Cairo. He quotes Peter Bouckaert of  Human Rights Watch: "It's clear that the very extensive police force  in Egypt is no longer able to control these crowds. _There are too many protests in too many places_." In the absence of a broadly unifying  social media that focused attention on the single winner-take-all  protest at Tahrir, people were driven out onto the street to see what  was happening and generated local protests instead.




Hassanpour suggests three effects of the disruption of the Internet  and of the more widely used cell phone networks:






  * it upset apolitical citizens, turning them against the government; 


  * it forced more face-to-face contact; 


  * it decentralized the rebellion. 




The facts on the ground are open to many interpretations, of which  Hassanpour's is one. He doesn't convince me  (I  don't have the expertise to judge his empirical evidence) but it's a possibility, and I found  it a valuable read.




Despite the title, the main interest  is not whether social media increases or decreases the net level of  activity, but that it reshapes it. There is overlap with Kieran  Healy's just-posted work-in-progress, _The Performativity of Networks_,  {[link](http://orgtheory.wordpress.com/2011/08/26/the-performativity-of-networks-2/)} where he argues that network algorithms, when implemented in  social media products, "reorganize the phenomena they purport to  describe" (social networks in this case). Facebook is a performance of  a theory of friendship.




Digital technologies have been given credit for an almost endless list  of roles in uprisings in authoritarian states. Digital technologies  help activist circles to better communicate (blogs, IRC chat, and  encrypted communications of various levels of security). They build a  broader and deeper public sphere by being a space for open discussion  (Facebook and Twitter). They give voice to citizens to speak to the  outside world and witness the actions of their government (YouTube  videos, Twitter, and blogs). They are a stark contrast to mass  media. But they also complement Al Jazeera, who can draw from citizen  videos. And they complement offline collaboration and offline  organizing as well. Hassanpour points out that digital organizing  activities are mainly Internet based while SMS is a medium more suited  for on-the-fly information (SMS). In short, there is little that can't  be attributed to social media in one form or another.




Hassanpour at  least makes a specific claim, that a disruption of digital  technologies produced an immediate and tangible reshaping of political  activity, and he has a mechanism for his claim. I'm sure others will  interrogate the evidence. There have been  many calls to go beyond "duelling anecdotes" in looking at the role of  social media, and this paper is an attempt to do that. It's flawed,  but if you ask me it's going in the right direction.


		
