---
author: Tom Slee
categories:
- About
date: 2019-07-01 18:36:55
title: Resume
toc: true
---


**2000-present**

Writing and commentary

-   2006: *No One Makes You Shop at Wal-Mart*, Between the Lines Press
-   2006-present: Writing on technology and politics, on this blog and
    in various print & online publications
-   2011-present: Invited contributor and speaker on open data and on
    the sharing economy.
-   2015: *What's Yours is Mine*, OR Books

For more detail, see [Publications](http://localhost:1313/about/publications/)

**2011--present**

Senior Product Manager, SAP SE.

(In 2011 Sybase was taken over by SAP SE. The views expressed on this
site are, of course, independent of my employer.)

**1994--2011**

Sybase Inc., Waterloo, Ontario --- [SQL
Anywhere](http://www.sap.com/pc/tech/database/software/sybase-sql-anywhere/index.html) R&D
division.

-   1994--1996: Technical Writer
-   1996--2005: Manager, [Technical Publications](http://dcx.sap.com/)
-   2005--2011: Senior Product Manager

**1991--1994**

Director of Scientific Support, Hypercube Inc, Waterloo, Ontario.

**1989--1991**

Postdoctoral Researcher, Theoretical Chemistry, University of Waterloo,
Waterloo, Ontario with [R.J. LeRoy](http://leroy.uwaterloo.ca/).1991

**1988--1989**

Postdoctoral Researcher, Inorganic Chemistry, University of Oxford, with
[D.M.P. Mingos](http://en.wikipedia.org/wiki/Michael_Mingos).

**1986**

Administrative assistant, McMaster University Centre for Peace Studies

**1986**

Contract researcher: Energy Probe

**1985--1986**

National Vice President, Canadian Union of Educational Workers

**1981--1986**

Ph.D., Theoretical Chemistry, McMaster University, Hamilton, Ontario,
with the late [R.F.W. Bader](http://www.chemistry.mcmaster.ca/bader).

**1978--1981**

B.Sc. (Hons) First Class, Theoretical Chemistry, University of
    Sussex.
