---
author: Tom Slee
categories:
- blog archive
date: 2007-04-07 12:32:16
title: Wikinomics - or Et Tu, Rabble.ca
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I'm just finishing with The Long Tail. Do I have to do it all again with [Wikinomics](http://www.wikinomics.com) ? Am I doomed to be a perpetual curmudgeon? If rabble.ca's newest venture is anything to go by, the answer is yes.  


[rabble.ca](http://www.rabble.ca) is a news site that I generally like. It describes itself this way:

<blockquote>_ rabble.ca_ was built on the efforts of progressive journalists, writers, artists and activists across the country. We launched rabble on April 18, 2001, just before the protests against the Summit of the Americas in Quebec City, and leapt onto the Net with the kind of coverage you could only get from the point of view of the rabble. We have covered events and issues in ways you'd be hard pressed to find anywhere else ever since.
> 
> </blockquote>

And I'd often agree - they reprint pieces by Rick Salutin, Linda MacQuaig, Thomas Walkom, Jim Stanford, Scott Piatkowski and other smart and left-wing journalists and commentators. It was founded by Judy Rebick. (For those of you outside Canada, there's a lot of Canadian lefty cred in the names in this paragraph.)




So why oh why are they giving a whole [lot](http://www.rabble.ca/reviews/review.shtml?x=58377) of [space](http://www.rabble.ca/bookstore/detail.shtml?x=58050) to Wikinomics, the web 2.0, long-tail-like wealth-of-networks, wisdom-of-crowds book by Don Tapscott and Anthony D. Williams. They're even holding a [virtual event](http://www.rabble.ca/bookstore/detail.shtml?x=58050) in Second Life.




rabble.ca must think there is something about the book that is "progressive". But what it is defeats me entirely. Could it be the front-cover blurb by the CEO of Procter & Gamble? The [praise](http://www.wikinomics.com/book/reviews.php) by executives from ATT, the World Economic Forum, OgilvyOne, IBM, and Roche Diagnostics, Socialtext, Royal Bank of Canada, Walt Disney, MetLife, Google, and Cisco? Is it this week's [Business Week Special](http://www.businessweek.com/innovate/di_special/wikinomics.htm)?




I've read chapter 1 (available [here](http://www.wikinomics.com/book/IntroAndOne.pdf)) and it's Long Tail all over again. Breathless prose ("we are entering a new age... liberate people to participate in innovation and wealth creation within every sector of the economy... a world where knowledge, power, and productive capability will be more dispersed than at any time in our history... harness the new collaboration or perish... - and that's just in the first dozen pages). Promises of democracy, empowerment of regular people (that's you and me, squire), the breaking down of old hierarchies. It sounds great. But...




I hate to say it, but in these tech-utopian books why does no one follow the money? If we're all so empowered and trust our peers, how come they get CEOs to blurb their book? If we're all so productive, how come inequality is increasing - and nowhere more so than in high tech industries?

And just like the Long Tail, the word-pictures the authors sketch are massively selective in their portrayal of the past and the future. The past is all rigid hierarchy, the future (left to technology and markets, apparently) is all explosive growth and innovative open source. IBM is promoted as "embracing open source" but they don't mention how it just set a [record](http://www-03.ibm.com/press/us/en/pressrelease/20868.wss) for the number of patents in a year. Isn't this at least part of the picture?




I feel like I've read the book already. For those who have been following my Long Tail grumbles, doesn't the following paragraph read just like Mr. Anderson?

<blockquote>For individuals and small producers, this may be the birth of a new era, perhaps even a golden one, on par with the Italian renaissance or the rise of Athenian democracy. Mass collaboration across borders, disciplines, and cultures is at once economical and enjoyable... A new economic democracy is emerging in which we all have a lead role.
> 
> </blockquote>

Come on rabble.ca: just because the new executives don't wear ties, business is still about the money. Technology is fine, but politics still exists. You disappoint me.




But wait! It so happens I know a thing or two about chemistry, and Wikinomics
has something just for me, right there in Chapter 1. Maybe this will save the book for me.

<blockquote>"Or perhaps your
thing is chemistry. Indeed, if you're a retired, unemployed, or
aspiring chemist, Procter & Gamble needs your help... Now you can
work for P&G without being on their payroll". 
> 
> </blockquote>

Is this some kind of joke? Sorry for being materialistic, but I think I'll give that opportunity a miss. 





		
