---
author: Tom Slee
categories:
- blog archive
date: 2014-04-25 01:01:48
published: false
title: Economist on sharing economy
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				


## The sharing economy


Consumers and investors are delighted by startups offering spare rooms or rides across town. Regulators and competitors are not so sure

AT LYFT’S base in Clara Street, in San Francisco, all is bustle. New staff are being shown the ropes. At least three dogs are tucked under desks or following their owners around. At 15,000 square feet (1,390 square metres), the place is almost four times as big as the old office, but it is already cramped. Lyft is about to move again, to a space of 60,000 square feet.




Lyft is a darling of the “sharing economy”, which uses the internet to bring together people with underused assets—anything from spare rooms to spare time—and others who might like to rent them. Lyft’s stock-in-trade is seats in cars: it registers and vets drivers who are willing to offer a ride in return for a “donation” and to place Lyft’s trademark fluffy pink moustache on the front of their vehicles; passengers request a Lyft, and pay, via a smartphone app. The two parties rate each other afterwards, also through the app, which is a common practice in the sharing economy. Fifteen months ago the service operated only in San Francisco. Now it is in over 30 American cities and entering more by the week. This month it raised $250m from venture capitalists.

It is not travelling alone. SideCar, a similar San Francisco startup, has spread to ten cities. Uber, backed by Google and best known for sleek black limousines, also offers ride-sharing services in both America, under the name of UberX, and Europe, as UberPOP. RelayRides, which lets motorists loan out their cars when they are not using them, is also found across America.

Along with transport, the market most affected by sharing has been accommodation, in which Airbnb, yet another San Francisco company, is the most prominent—and the sharing economy’s brightest star. Its “hosts” offer rooms, flats or houses for short stays in 34,000 cities. On April 18th Airbnb reportedly raised between $450m and $500m in a venture-financing round that valued it at $10 billion.

Not everyone is as delighted by the rise of the sharing economy as its participants and investors. Taxi drivers on both sides of the Atlantic have complained loudly (and, at least in Milan and Paris, violently) about the intruders who, they say, not only undercut their fares but are poorly vetted and underinsured. They have found ready listeners among officials and judges.

On April 15th a court in Brussels prohibited drivers from accepting passengers through UberPOP, on pain of a €10,000 ($13,800) fine. Last month Seattle’s council declared that Lyft, SideCar and UberX should be limited to 150 drivers each at a time—though a petition has gained enough signatures to put this requirement on hold. A judge has already told Lyft to apply the brakes in St Louis, only a few days after it rolled into town. RelayRides shut down in New York almost a year ago, because it fell foul of the state’s insurance laws. In other states, explains Andre Haddad, the chief executive, the company’s insurance policy kicks in once a car is rented out. New York law, however, insists that the owner remains liable.

At its latest valuation, Airbnb is purportedly worth more than all but the biggest hotel chains. Hoteliers do not welcome the competition either, though they claim it has not affected them much. In most cities Airbnb and others have not yet taken much of their business, though this may change, especially at the cheaper end of the market (see [article](http://www.economist.com/news/business/21601259-there-are-signs-sharing-site-starting-threaten-budget-hotels-room-all)).

Inhospitable rules

Authorities have been gunning for Airbnb anyway. In particular, it has been caught by rules, notably in New York and San Francisco, that outlaw short-term renting to different degrees. In both cities, housing is pricey, if it is not rent-controlled. The idea is to stop homes being turned, in effect, into hotels—and unlicensed, untaxed hotels at that. (Separately, subletting may also break the terms of a lease, putting tenants in hot water with their landlords.)

Airbnb has thus come under fire from Eric Schneidermann, New York’s attorney-general. He is demanding that the company hand over information about hosts with more than one property listed on the site. According to Skift, a travel-industry website, there are 1,849 of these, accounting for 30% of Airbnb’s New York listings; 102 have seven properties or more. This week Airbnb removed 2,000 hosts from its site, but it is resisting Mr Schneidermann’s demands, on privacy grounds. It portrays the attorney-general as persecuting ordinary New Yorkers who want to earn a few extra dollars by renting out their home for a couple of nights. He retorts that some, especially those offering multiple properties, are making a business out of short-term lets, and that these are his only targets. The two sides were in court on April 22nd, but no verdict was reached.

Some sharing-economy businesses have managed to avoid regulatory speedtraps. One such is BlaBlaCar, a French ride-sharing company operating in several European countries. Its users share only intercity rides, and so do not annoy urban cabbies, even though a lift from Nantes to Rennes, more than 100km away, costs no more than a short taxi ride in Paris, according to Frédéric Mazzalla, one of BlaBlaCar’s founders. And drivers merely cover their costs, so they do not trouble the taxman either. “It’s very clear that our drivers don’t make any profit,” Mr Mazzalla says.

Even where companies and regulators have been in conflict, there are signs of peace breaking out. Airbnb has said it is willing to collect hotel taxes in New York, Portland and San Francisco. It has recently revised its terms and conditions, spelling out in greater detail its hosts’ obligations to declare what they earn, as well as to honour their leases. San Francisco is considering the legalisation of some short-term letting. Hosts must live in the property at least three-quarters of the time, register with the city and pay the 14% hotel tax.

Corey Owens, head of public policy at Uber, says that in his industry local authorities can be put into three “buckets”. In the first are those with strict rules that they intend to keep, such as Austin, London, New York and Philadelphia. In the second are places where the future is ambiguous: here he puts Baltimore, Brussels, Paris and Washington, DC. Authorities in the third bucket have recognised that the world is changing. California, where the taxi regulator adopted new rules for ride-sharers last year, is the “primary example”. The trend, Mr Owens thinks, is for regulators to shift from the second bucket to the third, as Washington’s watchdog has done. Alas, in some places—such as Brussels—they may be heading in the other direction.



		
