---
author: Tom Slee
categories:
- blog archive
date: 2005-11-22 23:42:42
title: We'll Have to Do Something About the Rich
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

An excellent piece by Jonathan Friedland in tomorrow's Guardian (hey, it's before midnight where I am) about the growing gap between rich and poor in the UK. (Link: [Guardian Unlimited | Columnists | It may be beyond passe - but we'll have to do something about the rich](http://www.guardian.co.uk/Columnists/Column/0,5673,1648493,00.html).)




The phenomenon of growing inequality is present in Canada too. Increasing wealth and income at the top, flat or declining wealth and income at the bottom (in absolute as well as relative terms) and as a result changes like this:

<blockquote>When Margaret Thatcher
came to power in 1979, just under 6% of national income went to the top
1%. That figure stood at 9% a decade later, but under Tony Blair it has
risen to at least 13%: a tiny group taking nearly an eighth of our
collective wealth.
> 
> </blockquote>

The hook is a paragraph about London bankers ordering the most expensive cocktail they could concoct -- which came to £333 a glass. "The bankers ordered two rounds for
their table of eight. Their final bill for the night: £15,000." Does this matter? Friedland asks. Yes, he answers himself, even though it is unfashionable to say so...

<blockquote>... the story about the
£333 cocktails emerged in the same week as Shelter reported that
children were being forced to sleep in kitchens, dining rooms and
hallways because of cramped housing affecting 500,000 families in
England alone. Of these, three in four said that the lack of space was
damaging their children's education or development; many spoke of
depression and anxiety. And the scale of the problem has remained
unchanged since 1997
> 
> </blockquote>

He finishes up by predicting that "this issue's coming back. Just watch". I agree -- left to itself the inequality spiral continues, and at some point it is going to lead to big social unrest. Sooner or later, we'll have to do something about the rich.


		
