---
author: Tom Slee
categories:
- blog archive
date: 2008-10-20 01:44:10
title: YouTube Becomes Big Business
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

It's one of those hoary old sayings - it's been around for maybe two whole years now - that while the Geezer Generation of passive consumers watched network TV, the Net Generation of cool participators go on YouTube and do their creative teenage thing. But it's no longer either/or. A few recent milestones highlight how YouTube is changing.

  


First, Avril Lavigne [pipped](http://www.fool.com/investing/high-growth/2008/10/09/youtube-the-moneymaker.aspx) a homegrown video to be first to 100 million viewers and now "six of the 10 most-watched videos of all time are straight music videos."  
  


Second, CBS has [reached an agreement](http://online.wsj.com/article/SB122366964694723851.html?mod=googlenews_wsj) with Google to show full-length TV shows on YouTube.  
  


Third, Tina Fey's Sarah Palin sketches for Saturday Night Live have been watched more times on the Internet than on TV. Says the [Associated Press](http://ap.google.com/article/ALeqM5ic82WX2E_eXIkAG-tx_JyR5blC3gD93U06LG1):

  


<blockquote>There were 10.2 million people watching the season-opening "Saturday Night Live" when Fey first appeared as Palin, with Amy Poehler portraying Hillary Clinton, according to Nielsen Media Research. These days, that's a good-sized audience for prime-time, let alone late-night, TV.  
Another 1.2 million people captured the episode on their DVRs and watched within the week. Through the middle of last week, NBC estimated that it had streamed the skit online more than 13 million times. Those are just the numbers NBC can keep track of; the skit was undoubtedly captured and posted or e-mailed many more times.  
NBC perfected "widget" technology only a few months ago, allowing video of its material to be captured across the Internet while retaining a tie to the network's Web site. It has aggressively marketed the Fey skits to political and comedy blogs...  
...There's also the chance for even more revenue. Only in the past few weeks has NBC Universal perfected the technology to place a movie studio advertisement at the end of the clip it distributes online. Pre-clip advertising would add even more value.
> 
> </blockquote>

  


It's not actually YouTube - as the article says, NBC now posts its own videos and removes them from the YouTube site when viewers post there - but these developments show that Internet viewing can be complementary to, not competitive with, mainstreamTV. And "going viral" is no longer reserved for amateur guitar players. In fact, in an example of the [centripetal web](http://www.roughtype.com/archives/2008/10/the_centripetal.php), the Internet now lets US Network productions go where they could not go before - you can now watch Fey/Palin in the UK on the Guardian and The BBC web sites.

  


Whether TV networks will end up hosting their own material a la NBC, or whether there will be more CBS-style Google/network deals that see the networks outsourcing the hosting to YouTube in return for a slice of the advertising money, who knows? But the trend is clear; the confrontation between Internet and TV is coming to an end. The old enemies were perhaps never really at each others throats, and now they will cohabit happily. And while YouTube will continue to host amateur videos (why not?) it will make money from the music videos and the TV networks as it moves to higher-quality images and longer shows. Google's [expanded YouTube advertising initiatives](http://www.guardian.co.uk/business/feedarticle/7884701) will help these deals along.

  


The [Carr-Benkler wager](http://en.wikipedia.org/wiki/Carr-Benkler_wager) is looking more and more like a win for Carr.


		
