---
author: Tom Slee
categories:
- blog archive
date: 2006-12-23 17:28:23
title: "Bad Reviews: What's a Novice Author To Do?"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Hooray! I thought all the book reviews were done some time ago, but one more appeared in the December 2006 edition of the [Literary Review of Canada](http://www.reviewcanada.ca).




Boo! Not only is the review (not available online) almost entirely negative, but it also misrepresents the book entirely. I don't mind the negative, but the misunderstanding and misrepresenting pisses me off something terrible.




I have a response forthcoming in the January/February 2007 edition, in which I do what you are supposed to do and take the high road. It seems to be common wisdom that it is Not The Done Thing to argue with reviewers, although Peter Woit does it all the time (that is, argues with reviews of his string theory book _Not Even Wrong_) regularly in his [blog](http://www.math.columbia.edu/~woit/wordpress/), and it comes over OK.




So should I post what I really think here on this little corner of the Internet or not? Do I descend into the gutter, biting and scratching and swearing and generally lowering the tone of the neighbourhood, or do I stay up here, tight-lipped and dignified on the lofty high ground, breathing the etherial air that we morally pure people breathe. 




What's the right thing for a novice author to do?


		
