---
author: Tom Slee
categories:
- blog archive
date: 2008-11-18 23:29:16
title: Link Books to Their Open Library Page
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

When you reference a book and want readers to be able to find more about it, it's common to link to Amazon. There are problems with Amazon being the default site for all books: by linking there you are basically recommending that your readers support Amazon and don't support your local bookstore.

So how about linking to [Open Library](http://openlibrary.org/) instead whenever you mention a book, like [the best novel ever](http://openlibrary.org/b/OL7962182M)? It's an evolving initiative with a fine mission: _One web page for every book_. It's got some quirks still - the treatment of books with many editions is a bit of an issue - but it's a great idea and it's noncommercial, which is hugely important for a common resource. You won't find much information there about most books, but you will find links to buy a book at some of the bigger online bookstores and to your local library catalogue if you're lucky.

Now if only they could link to your local bookshop, which should be possible for those who have online ordering stores like [our neighbourhood one](http://www.wordsworthbooks.com), I'd be very happy with it.

Obviously there's more work to be done there, but one way to get it done is to make people aware of it, and one way to do that is to link to it.

So spread the word: **link books to their Open Library page**. 


		
