---
author: Tom Slee
categories:
- blog archive
date: 2011-09-17 21:53:49
title: 'Internet-Centrism 1 (of 3):  Evgeny Morozov and The Net Delusion'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I've never met Evgeny Morozov, but I have to say I love the guy  because over the last three years he's succeeded in doing something  that desperately needed to be done: he's provided a strong counterweight to  an overhyped narrative of digital revolution. And then, since _The Net Delusion_ came out at the beginning of the year, he's had to put up  with a lot of unjustified condescension and caricature from some who  suffer from the very "Internet-centrism" that is the target of his  book.




Take the _MIT Technology Review_, which just ran a set of writings about  the Arab Spring uprisings. The contributors characterize the debate  over social media's importance as "wildly overdrawn" ([Aaron Bady](http://www.technologyreview.com/blog/guest/27110/)); "highly polarized" ([John Pollock](http://www.technologyreview.com/web/38379/)), a "false debate" ([Zeynep Tufekci](http://www.technologyreview.com/blog/guest/27122/)),  a "false dichotomy" ([Jillian C. York](http://www.technologyreview.com/blog/guest/27145/)).  And some put Morozov, together  with Malcolm Gladwell, at one pole of that debate, with "the  cyber-utopians" at the other.  Now Gladwell is a high-profile name who  dipped his oar into the waters of digital scepticism in a single article, and he can deal with what he gets from that. But  Morozov, judging from his age, is looking to build an academic career  on his work and he's at a vulnerable stage, so being the focus of so  much attention is both a blessing and a curse.




In Streetbook, his contribution to the MIT Review articles, John  Pollock summarizes _The Net Delusion_ by writing that "[it] decries the  'naive belief in the emancipatory nature of online communication'".  Now if you are going to accuse Morozov of being one pole in an overly  polarized and, by implication, simplistic debate, you should at least  get his position right, and this portrayal is simply unfair. The  quotation comes from page xiii of the book's introduction, and is  Morozov's portrayal of "cyber-utopians". Using this quotation makes it  seem that Morozov sees his opponents in exagerrated and simplistic  terms.  But the bigger target of the book is what Morozov labels  "Internet-centrism", a setof assumptions that has policy-makers  "answer[ing] every question about democratic change by first reframing  it in terms of the Internet rather than the context in which that  change is to occur." {p. xvi}




Morozov is not a digital dystopian; hell, he [owns](https://twitter.com/#!/evgenymorozov/status/114935396164571136) both a Kindle _and_ an  iPad; he writes "The premise of this book (_The Net Delusion_) is thus  very simple: To salvage the Internet's promise to aid the fight  against authoritarianism, those in the West who still care about the  future of democracy will need to ditch both cyber-utopianism and  Internet-centrism" {p xvii}. His position is well within the confines  of mainstream political science — in particular, he accepts the  "project of promoting democracy" as generally a well-intentioned  effort from the US, which is a far-from radical stance — so it's  remarkable that he has become such a polarizing figure. _The Net Delusion_ is a strong book, but a limitation is that it fails to  challenge that project and the intentions behind it sufficiently.




Over the course of the year, _The Net Delusion_ has become a victim of  its own success. Critiques argue that it is time to move beyond  "[duelling anecdotes](http://crookedtimber.org/2010/09/30/blogs-bullets-and-bullshit/)" to a more sophisticated level of analysis, and  both [Patrick Meier](http://irevolution.net/2009/11/19/anecdote-heaven/) and [Mary Joyce](http://www.meta-activism.org/2011/02/net-delusion-reviewslacktivism/) (as well as the more predictable  [Adam Thierer](http://techliberation.com/2011/01/04/book-review-the-net-delusion-by-evgeny-morozov/)) accuse Morozov of dealing too much in story, not  enough in larger-scale data analysis or theoretical work. The  accusations miss the point: there was no duel of any significant kind  until Morozov stood up against the tide of "Twitter Revolution"  euphoria that erupted along with the Iranian protests in 2009. He  introduced a counterweight into a public debate environment that uncritically accepted the thesis that the Internet is intrinsically on the  side of dissidents under authoritarian regimes; that the affordances  it offers benefit the powerless against the powerful. Having  rebalanced the debate, he is now met with a somewhat patronizing  declaration that we are past all that, and it is time to move on to  more sophisticated and nuanced discourse. Joyce is right when she says  that he can be binary in his thinking, and that the book lacks theory,  but these accusations are beside the point. It was a book written  quickly, in response to the needs of the time, and it met those  needs. Arguing that a more subtle, thorough book would be better is to  miss the political situation in which it was written, and which it  effectively challenged. Morozov deserves a better response from social  scientists than he has received.




Despite the claims of moving beyond the Morozov/Shirky binary debate,  some of the MIT Review articles suffer from the very Internet-centrism  that Morozov criticizes, in particularly the [Streetbook](http://www.technologyreview.com/web/38379/) centrepiece.  But that's a topic for [Part 2](http://whimsley.typepad.com/whimsley/2011/09/so-three-cheers-for-evgeny-now-back-to-the-mit-review-articles-some-of-which-display-the-very-internet-centrism-that-moroz.html).


		
