---
author: Tom Slee
categories:
- blog archive
date: 2016-02-12 14:48:18
title: 'Airbnb report: media coverage'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				The media response to [the Airbnb report](http://tomslee.net/how-airbnb-hid-the-facts-in-nyc) from [Murray Cox](http://insideairbnb.com/how-airbnb-hid-the-facts-in-nyc/) and me has been gratifying. Here are the major stories to date.

Mainstream media:



	
  * New York Times: [Airbnb Purged New York Listings to Create a Rosier Portrait, Report Says](http://www.nytimes.com/2016/02/12/business/airbnb-purged-new-york-listings-to-create-a-rosier-portrait-report-says.html)

	
  * The Guardian: [Airbnb purged more than 1,000 New York listings to rig survey – report](http://www.theguardian.com/technology/2016/feb/10/airbnb-new-york-city-listings-purge-multiple-apartment-listings)

	
  * Fortune: [Researchers say Airbnb Fudged New York City Listing Data](http://fortune.com/2016/02/11/airbnb-listings-research-data/)

	
  * CNBC: [Report Says Airbnb Fudged Data To Hide Illegal Hosts](http://www.cnbc.com/2016/02/12/report-says-airbnb-fudged-data-to-hide-illegal-hosts.html)


New York & real estate:

	
  * The Real Deal: [De Blasio chides Airbnb over alleged data purg](http://therealdeal.com/2016/02/17/de-blasio-chides-airbnb-over-alleged-data-purge/)e

	
  * New York Daily News: [Airbnb dropped 1,000 possibly illegal listings before opening its books to lawmakers](http://www.nydailynews.com/news/world/airbnb-dropped-1g-questionable-listings-opening-books-article-1.2526230)

	
  * 


The Real Deal:  [Airbnb purged over 1,000 listings before December data release: report](http://therealdeal.com/2016/02/10/airbnb-purged-over-1000-listings-before-december-data-release-report/)


	
  * 


New York Magazine: [Airbnb accused of purging 1000 NYC listings to make its numbers look better](http://nymag.com/following/2016/02/airbnb-accused-of-purging-1000-nyc-listings.html)


	
  * TechnoBuffalo: [Airbnb used dirty tactics to clean up 1,000 New York City listings](http://www.technobuffalo.com/2016/02/11/airbnb-used-dirty-tactics-to-clean-up-1000-new-york-city-listings/)

	
  * New York Business Journal: [Airbnb honesty in question after report claims the startup 'photoshopped' data](http://www.bizjournals.com/newyork/news/2016/02/11/airbnb-honesty-in-question-after-photoshopped-data.html)

	
  * Curbed: [Airbnb May Have Deleted NYC Listings to Bolster Its Image](http://ny.curbed.com/archives/2016/02/12/airbnb_may_have_deleted_nyc_listings_to_bolster_its_image.php)


Tech press:

	
  * Re/code: [Did Airbnb Purge Potentially Illegal NYC Listings Ahead of Its Own Data Dump?](http://recode.net/2016/02/10/did-airbnb-purge-potentially-illegal-nyc-listings-ahead-of-its-own-data-dump/)

	
  * Fusion: [A new report alleges that Airbnb manipulated data to make itself look better to regulators](http://fusion.net/story/267202/a-new-report-alleges-that-airbnb-manipulated-data/)

	
  * Digital Journal: [Airbnb allegedly purged 1,000+ New York listings to rig survey](http://www.digitaljournal.com/business/business/airbnb-removed-over-1-000-new-york-listings-to-rig-survey/article/457233)

	
  * Gizmodo: [Looks Like Airbnb Manipulated Its Own Data To Appear Less Evil](http://gizmodo.com/looks-like-airbnb-manipulated-its-own-data-to-appear-le-1758476967)

	
  * The Awl: [The Mystery of the Thousand Missing Airbnbs](http://www.theawl.com/2016/02/the-mystery-of-the-thousand-missing-airbnbs)

	
  * Boing Boing: [The mystery listings Airbnb "purged" before transparency report](http://boingboing.net/2016/02/11/about-those-mystery-listings-a.html)


Other things:

	
  * Alternet: [How Airbnb Misled the Public and the Press](http://www.alternet.org/economy/how-airbnb-misled-public-and-press)

	
  * Next City: [Airbnb Allegedly Manipulated Data to Hide Illegal Hosts in NYC](https://nextcity.org/daily/entry/aribnb-data-new-york-city-illegal-hosts)


International:

	
  * Accommodation Association of Australia [(reprint of press release)](http://www.aaoa.com.au/Media/News/tabid/1884/ItemID/1116/View/Details/Default.aspx)

	
  * El Confidencial: [Acusan a Airbnb de manipular sus datos para ocultar propiedades ilegales](http://www.elconfidencial.com/tecnologia/2016-02-11/acusan-a-airbnb-de-manipular-sus-datos-para-ocultar-propiedades-ilegales_1150524/)

	
  * Preferente:  [Airbnb, acusada de manipular datos para ocultar propiedades ilegales](http://www.preferente.com/noticias-de-agencias-de-viajes/airbnb-acusada-de-manipular-datos-y-ocultar-propiedades-ilegales-258363.html)

	
  * Allcompanies (Dutch): [Airbnb verwijderd meer dan 1.000 New York aanbiedingen te rig survey – rapport](http://allcompanies.website/2016/02/11/airbnb-verwijderd-meer-dan-1-000-new-york-aanbiedingen-te-rig-survey-rapport/)


		
