---
author: Tom Slee
categories:
- blog archive
date: 2011-09-22 08:10:22
title: 'Internet-Centrism 3 (of 3): Tweeting the Revolution (and Conflict of Interest)'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[Time saver announcement: The most interesting thing in here is probably the conflict of interest in a recent Twitter-Arab Spring paper, which starts here.]




Earlier today I thought I was doomed to fail; that part 3 of this  prematurely-announced trilogy was just not going to get written. I  tried a few things, threw them away. Tried a few more, scrunched them  up into balls of electrons, and dragged them to the little waste bin  up there in the corner of the screen. Life was looking grim (although  not as grim as the awesomely atmospheric [trailer](http://t.co/Hpcg7XUD) for the Andrea Arnold  version of Wuthering Heights, shot in wonderful Swaledale, and coming  soon to a theatre near me, I hope).




But then two research papers about Twitter and the Arab Spring  appeared within days of each other. Could these be raw material for a  little grumbling about Internet-centrism, I thought? Well knock me  sideways, it turns out they could.










First up is [Opening Closed Regimes](http://pitpi.org/index.php/2011/09/11/opening-closed-regimes-what-was-the-role-of-social-media-during-the-arab-spring/), by Philip N. Howard and others, a  report from the _Project on Information Technology and Political Islam_ at the University of Washington. "What was the role of social media  during the Arab Spring?" it asks, and it answers the question with  ne'er a duelling anecdote in sight, which you would think would be a  good thing.




But it's not. The paper is resolutely and exclusively like the drunk  looking under the lamp post to find his keys, because that's where the  light is brightest. There's lots of data about what happens on Twitter  because the Twitter API provides access to large numbers of tweets  together with all their metadata, and then you can slice and dice them  to your heart's content. And that's what these researchers have  done. I know from personal experience how tempting it is to think  there's gold in them thar queries, that if you interrogate the data in  just the right way you'll find the key to unlock the box and find  enlightenment, or at least an unmixed metaphor.




Not that there's anything wrong with data mining Twitter. But if it's  the only data source you use, you really can't use it to make broader  statements. And the paper does make broad claims, like "Social media  played a central role in shaping political debates in the Arab  Spring", and "Twitter seems to have been a key tool in the region for  raising expectations of success and coordinating strategy. Twitter  also seems to have been the key media for spreading immediate news  about big political changes from country to country in the region."  These are statements that reach out from Twitter to the broader social  context of which it is a part, but if Twitter is literally the only  medium you look at, then obviously it is likely to appear "central"  and "a key tool". A section titled "Social Media's Centrality to  Political Conversation" analyzes the volume of online content during  the time leading up to the uprisings, and looks at how the web sites  of political actors linked to social networking and other news  services. There's nowt but digital content. What the section is really  looking at is social media's centrality to _online_ political content.




There's no mention here of other ways in which individuals actually  exchanged information, whether in university campuses, on [the football terraces](http://whimsley.typepad.com/whimsley/2011/09/so-three-cheers-for-evgeny-now-back-to-the-mit-review-articles-some-of-which-display-the-very-internet-centrism-that-moroz.html), in mosques, through professional networks of lawyers and  teachers, via posters or leaflets, or around kitchen tables. All this  teeming activity is simply invisible, out there in the obscure  unilluminated and unexamined darkness. Out of sight, out of mind.




_Opening Closed Regimes_ reminds us that comparisons are  essential. Mapping social media interactions, or online linkage  patterns, no matter how ingeniously, is never going to tell us  anything about how online behaviour fits into the broader social  world. And it's never going to justify conclusions like "During the  Arab Spring, individuals demonstrated their desire for freedom through  social media, and social media became a critical part of the toolkit  used to achieve that freedom."













But _Opening Closed Regimes_ is better than the other paper, _The  Revolutions Were Tweeted: Information Flows During the 2011 Tunisian  and Egyptian Revolutions_ ([pdf](http://ijoc.org/ojs/index.php/ijoc/article/viewFile/1246/613)) by Gilad Lotan and others including  (to my dismay) danah boyd, whose writings I usually really learn  from - like [Six Provocations for Big Data](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1926431), for example.




This paper also takes Twitter feed data - nothing else at  all: nada, zilch, zero - slices, dices, etc etc as before, and then says "we discuss how  Twitter plays a key role in amplifying and spreading timely  information across the globe".




The paper is published in the [International Journal of Communication](http://ijoc.org/),  which you'll be glad to know "adheres to the highest standards of peer  review and engages established and emerging scholars from anywhere in  the world". So I was a little surprised when I looked up lead author  Gilad Lotan, who lists his organizational affiliation as _Social Flow_.




[**Update: **the authors now provide an appendix to the paper explaining the relationship between the company, the lead author, and the work. I accept that explanation. I leave the post here, but please read it in that light.]




Why? Because it turns out that [Social Flow](http://www.socialflow.com/) is a private company that  "has developed the industry's first and only social media optimization  technology that uses real-time data – including the Twitter and bitly  firehoses – to help publishers, retailers, and brands earn maximum  potential engagement on Twitter." That's right, it's basically SEO for  Twitter. It develops algorithms that "dynamically publishes the best  message at the best time to ensure its clients get the maximum amount  of engagement from their Followers."  Yup, these people are going to  pollute your Twitter feed, and make money from it. Small wonder that  the paper paints such a positive picture of Twitter's influence.




Social Flow is a venture capital funded company based in New  York. According to [CrunchBase](http://www.crunchbase.com/company/socialflow), they recently received $7M in Series A  funding from [a variety of venture capitalists](http://techcrunch.com/2011/04/07/socialflow/) including "Softbank,  with Softbank NY, RRE Ventures, Betaworks, High Line Venture Partners,  AOL Ventures, SV Angel and some individual angels investing." Plus,  they have a lovey-dovey relationsihp with Twitter itself. TechCrunch  comments that:




<blockquote>

> 
> Neither side would comments on the terms of the relationship — but  it's clearly beneficial to both.
> 
> 

> 
> "This is exactly what we want to see out of the ecosystem," Twitter  Platform lead Ryan Sarver adds. "These guys are building a real  business,"
> 
> 
</blockquote>




Thanks Ryan.




And just in case you wondered: their investor Betaworks has also  invested in Tweetdeck and Summize: other companies that have actually been  bought by Twitter.




There is no mention of this blatant conflict of interest, which took  me all of 30 minutes to look up, in the paper. The "International  Journal of Communication" should be ashamed for publishing it.




After that, it's hardly worth even reading the paper. But I did. It  suffers from some of the usual Internet-centric fallacies.




Here's the VERY FIRST SENTENCE (capital letters in tribute to [Tiger Beatdown's third birthday](http://tigerbeatdown.com/2011/09/21/tiger-beatdown-birthday-party-spoiler-it-is-just-a-post/)): "The shift from an era of broadcast  mass media to one of networked digital media has altered both  information flows and the nature of news worked." Apparently positioning Internet sources as a competitor to broadcast media is so obviously true that  it doesn't need support. Except that it's far from obvious  that there is such a shift, even in North America, with audiences  consuming [just as much television as they ever have, with social media being an increasingly important _complement _to TV](http://whimsley.typepad.com/whimsley/2011/08/as-tv-goes-online-the-internet-becomes-more-like-tv.html). And of course in  North Africa the spread of television is much more recent - the growth  of Al Jazeera even more so - so that there has almost certainly been  no such shift at all.




The conceptual background of the paper is rife with such  assumptions of the way the digital and "mass media" world  differ. Studies investigate "how news emerges from networked actors  who span different professional and organization identities and  contexts" – note the organic, bottom up word "emerges" – in contrast  to the world of mainstream media, in which "journalists tend to  produce news designed for their publishers and editors", and enact  "rituals of objectivity" to distance themselves from audiences. It's a caricature of the Internet compared to a cartoon of non-digital media.




And so it goes. The study itself is quite narrow, analysing  information flows around Twitter, and makes cautious conclusions about  the meaning of those information flows. But it acquires interest only  from the suggestions, throughout, that this is part of a bigger picture of  bottom-up newsmaking through social media. Their findings, for example, "confirm the  notion that Twitter supports distributed conversation among  participants and that journalism, in this era of social media, has  become a conversation".




Now I don't mind a critical look at mainstream media – there's no  shortage of things to criticize after all, and I suspect this is why  well-intentioned people with anti-establishment agendas fall into the  Internet-centricity trap. But even if "mass media" was nothing but a  Debord-ian "society as spectacle" dystopia, that doesn't make the  venture-capital-driven world of social networks an alternative: social media companies  are as mainstream, capitalist, and establishment as you can get. And  they are no friends of liberation movements.




So, going back to the MIT Technology Review articles that I discussed [last time](http://whimsley.typepad.com/whimsley/2011/09/so-three-cheers-for-evgeny-now-back-to-the-mit-review-articles-some-of-which-display-the-very-internet-centrism-that-moroz.html), there are three contributions from people who are clearly on the left politically, and who seem to follow a broadly anti-establishment agenda, and whose writings I respect. But, if I can psycho-analyze from a distance, their writings show that they would dearly love Internet technology to be a natural ally of those who seek a more egalitarian, less hierarchical world. Unfortunately, wishes don't always come true.













Aaron Bady [argues](http://www.technologyreview.com/blog/guest/27110/) that social media promotes, by its architecture, a notion of _leaderlessness_ that is counter to the authoritarian nature of Egypt and other Arab states. Zeynep Tufekci [sees](http://www.technologyreview.com/blog/guest/27122/) Facebook's features as "the ideal infrastructure to create the information/action cascade" that was the Arab Spring uprisings. Jillian York [is more sceptical](http://www.technologyreview.com/blog/guest/27145/), but still looks for "the _democratizing_ prospects of social media tools elsewhere: the strengthening of the public sphere… the transfer of the interaction from social networks to manifestation in the real world, on the street". Reading these accounts, one cannot help but see three people who want to change the world for the better, and who are hoping that these new technological tools tip the balance of this continuing struggle in favour of the powerless, and against the powerful.




But their claims place technology ahead of issues of commerce and ownership, and I think that's a mistake:






  * Networks on Facebook may not have leaders, but Facebook itself is a centralized, commercialized system that has promoted its owners into positions of wealth (six billionaires) and power (access to heads of state, influence in Washington, a welcome at Davos). Is this an architecture of leaderlessness? Why would we spend intellectual and other effort arguing that this business is (even with caveats) a force for good in the world? Sure I use Facebook, but I also watch TV and that doesn't mean I trust the TV companies further than I could throw them.


  * The wealth and power that Facebook and Google owners have accumulated depends directly on the commercial exploitation of the traffic through their sites. YouTube, Facebook, and Twitter will act as a "public sphere" only until the commercial interests of the site collide with the politics of the discussion. Once that boundary is crossed, these spaces become more Panopticon than public square. Is this an ideal infrastructure for activism?


  * By focusing their hopes to a particular set of technologies that carry massive public data sets with them, it's almost impossible _not_ to overestimate the role these technologies play in public discussion, as we saw with the two research papers. We track the conversations on Twitter during the revolution, but not the conversations among neighbours around kitchen tables. Out of sight, out of mind.




So, from those who seek to make money from commercializing our every social interaction, to those who mistakenly identify today's mainstream Internet with the alternative ethos of a decade ago, there are plenty of people out there who are prone to see the world through the rose-tinted and digitally-enhanced glasses of Internet-centricity. But that doesn't make them right.











		
