project:
  type: website
  output-dir: docs
  preview:
    port: 4444
    browser: true

website:
  title: "Tom Slee"
  description: "Personal web site"
  twitter-card: true
  favicon: logo.png
  page-footer: 
    left: "2023, Tom Slee" 
  navbar:
    background: DarkCyan
    pinned: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Essays
        href: essays.qmd
      - text: In Progress
        href: inprogress.qmd
      - text: "Ridehail Lab"
        href: https://tomslee.github.io/ridehail/lab/
      - text: "Whimsley (blog archive)"
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/tomslee
      - icon: twitter
        href: https://twitter.com/whimsley

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

