---
author: Tom Slee
categories:
- blog archive
date: 2006-05-30 21:05:13
title: Reader, you're a right dimwit
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[Bookslut](http://www.bookslut.com/blog/archives/2006_05.php#009001) points to [an article in The Times by Libby Purves](http://www.timesonline.co.uk/article/0,,1056-2202068,00.html) on how bookstores (in the UK) have publishers caught in a prisoner's dilemma when it comes to promoting books, and as a result readers are stuck in a market for lemons. Here is an excerpt:

<blockquote>Reports have “revealed” the so-called secret fees paid by publishers to
booksellers in order to get books stocked, “chosen” and recommended by
the big book chains. 
> 
> 

> 
> That W H Smith’s “book of the week” title, which attracts you as
if it had won a prize, has been bought and paid for. The publisher
handed over £50,000. Waterstone’s Book of the Week accolade is £10,000,
less for ecstatic mini-reviews. Borders charges for “fiction buyer’s
favourite”. Smaller sums buy other levels of prominence; only some
local staff “picks” are related to actual content. It is not uncommon
for a catalogue to recommend a title warmly before the compiler has
even seen it. A pre-Christmas push costs £200,000 and a big campaign
double that. One publisher told a newspaper: “We’ve got to play by the
rules because we need them.” It is considered suicidal not to join in. 
> 
> </blockquote>

<blockquote>...Seventy per cent of promotional budgets go on furtive payments to
bookshops. The message to the author is: “Nobody would read you if we
didn’t pay, so shut up grumbling.” To the reader the message is: “You
are a fool pig, guaranteed to go for the shiniest swill-bucket.” To the
newspapers who publish bestseller charts it is simply: “Gotcha!” 
> 
> 

> 
> Most of these charts cover sales in one particular week, so
they favour the fast-selling and heavily displayed. They are no index
of pleasure or even real popularity. It is not uncommon for a book to
reach high rank one week and live off that glory (“surprise soaraway
bestseller for tragic Gwendolen”) when in fact it has shifted fewer
hardbacks than another book that never got near the top 20 because it
sold more gradually. 
> 
> </blockquote>

<blockquote>Well, so be it. Bookselling is a trade; it is sad but not
criminal that it operates like one, cutting deals to maximise profit.
It is sad but not surprising that big booksellers do not care that
their practices are widening the gulf between hyped authors and the
rest, squeezing out new writers and truncating the careers of those who
fail to return the publisher’s investment fast enough. They do not care
that the literary double-or-quits economy prevents the slower, organic
growth of writing careers. 
> 
> 

> 
> The responsibility spreads wider, though. You would think
that, knowing how skewed the trade has become, book page editors would
question the status quo as journalists do in every other area. You
would think that their mission was to seek out interesting new books
while scornfully ignoring hype-fests. There is little evidence of this,
except in some odd and praiseworthy corners. Journalists like to feel
they are up there with the “buzz”, even if the buzz is largely
artificial. Where reviews do diverge from the well-trodden track of the
week’s “key” books, it is often only into a cosy circuit of settling
old scores, or bigging up friends who will soon return the favour. This
is often undeclared, which shocks the strait-laced American media (read
the _New York Times _arts ethical policy online, boys, and hang your heads).

> 
> 

> 
> Newspapers and magazines are also magpies, attracted to the
glitter of the young, the pretty, the well-connected, the celebrity. If
Keira Knightley publishes a novel tomorrow it will not go short of
attention, while if a new Orwell or Greene emerges from the ranks he
may fall back unnoticed. There are some flukes, but even notable “word
of mouth” successes often turn out to be no such thing. And the moment
an unhyped book starts to move, the big chains will be on to the
publisher with display offers they dare not refuse. All success becomes
a commodity. 
> 
> </blockquote>

This fits with what I've seen, and with my argument in Chapter 9. Other reports (which I can't find now) suggest that compared to ten years ago, more books are published now than used to be, and more titles are carried (in some form or other) by bookstores. But the total volume of books sold is about the same as it used to be, and of that amount more goes to just a few bestsellers. It's what happens in a market when you don't know what you're buying. Book buying is going, apparently, from being a high-information market to a low-information market. 




On the down side, it's kind of a depressing view of the book industry. On the up side, it's a great excuse if No One Makes You doesn't do that well.




Libby Purves, by the way, wrote my favourite parenting book, [How Not To Be a Perfect Mother](http://www.amazon.co.uk/exec/obidos/ASIN/0007163843/026-9913670-8640468).


		
