---
author: Tom Slee
categories:
- blog archive
date: 2007-04-09 08:09:10
title: The Long Tail 14 - Long Tail Rules
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is another part of my critical reader's companion to _The Long Tail_, and it discusses Chapter 14 - Long Tail Rules. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html).

* * *

I'm getting tired, and need to get to the end of this book quickly. Then I can write a wrap-up post and be done. This final chapter (almost! there is a "coda") contains nine rules for building "a Consumer Paradise" [217], grouped under three headings. Here we go. 




Lower Your Costs [217-219]  
Rule 1: Move inventory to the edge - The advice is to transfer your costs to your suppliers: keep a virtual inventory. For example, Amazon Marketplace products are "held at the very edge of the network by thousands of small merchants. Cost to Amazon: zero" [218].   
Rule 2: Let customers do the work - He calls this "crowdsourcing" [219]. Let customer reviews rank your books, write your content, and so on, because "collectively, customers have virtually unlimited time and energy" [219].




As I've said repeatedly, the benefits of being an aggregator are that you profit from being a natural monopoly, or at least part of a natural oligopoly. Once you can establish yourself as the place to be, vendors will want to - have little choice but to - sell their stuff on your site. Once you become the bookstore of choice, customers may add their reviews to your site. But of course there is one place where the Long Tail does not really eliminate scarcity - and that's in the supply of aggregators. When inventory is stored at the edge someone is still paying the cost of stocking it - it's just not Amazon. The Long Tail slides back and forth between talking about zero-cost (total) and zero-cost (someone-else's cost) - but never says which one is which. These are different things.




One of the changes we've seen in both sides of the technological vice (online stores + big-box stores) is that power has shifted away from manufacturers and to retail outlets. Amazon can sell goods without paying for them first. Wal-Mart is trying to introduce systems that will pay suppliers only when someone actually buys a product, so that their own shelf space becomes free (to them). It's a power shift leading to a transfer of costs, not a cutting of costs - and power matters.




Think Niche [219-221]  
Rule 3 - One distribution method doesn't fit all  
Rule 4 - One product doesn't fit all  
Rule 5 - One price doesn't fit all.  
As with much of the book, this section contains unsubstantiated claims: Rhapsody is "experimenting with track prices from $0.79 to $0.49 and finding that cutting the price in half roughly triples sales" [221]. Really? How often? All of them? We need more than this. And if the experiment was so successful, then we may wonder why the [current](http://www.rhapsody.com/rhapsody_faqs#6) (April 2007) Rhapsody web site says this:

<blockquote>Can I download tracks with Rhapsody?  
Yes. You can purchase music from Rhapsody for $0.99/track, or $0.89/track with a membership.
> 
> </blockquote>

No mention of variable pricing beyond encouraging membership.




Lose Control [221-224]  
Rule 6 - Share information. Well, up to a point. One of the most pervasive ironies of the whole book is that it keeps going on about sharing information, but the very facts that are at the core of the book are hidden behind some of the thickest walls around. Actual Netflix sales distributions? Actual sales of Amazon books? Actual sales of iTunes music? None of it is here. Quite why Anderson thinks we are in a new age of openness is beyond me.  
Rule 7 - Think 'And', not 'Or'  
Rule 8 - Trust the market to do your job - His advice is to "throw everything out there and let the market sort it out", which is really a restatement of his Rule 2 - Let customers do the work. As I've said before, there is a big difference between what works for aggregators and what works for producing actual variety. 




As just one example that I haven't mentioned before, Anderson keeps on about how referrals allow customers to move from the head to the tail of the distribution. But what happens if you start at the tail? No One Makes You Shop at Wal-Mart is currently (April 6) ranked 381374. The recommended books that appear on the page have the following rankings: 475137, 18675, 201, DVD #569, and 90396. That is, if you start off in the tail, the recommendation system pushes you back up towards the head of the distribution. Hence Amazon can profit by stocking all books, even if it doesn't sell much of them, because the reference system is a way of promoting other, better selling books. Now I don't know what the net effect is, but neither does Mr. Anderson.  
Rule 9 - Understand the power of free is an argument for combining premium pricing and a free version of what you provide (fair enough), and for an advertising-supported revenue model. Well if one thing is becoming ubiquitous, it's advertising. Is this a move to a niche nation or a numb nation? I for one do not welcome our new advertising-sponsored overlords. Consumer paradise? I think not.


		
