---
author: Tom Slee
categories:
- blog archive
date: 2007-09-21 22:17:46
title: INLAND EMPIRE
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Some films you watch for plot, some for action, some for characterization, some for laughs. David Lynch films you watch for the atmosphere and for the occasional shocking scene. Complaining about the plot of a Lynch movie is like complaining about olives not being sweet: it's just not the point.




I don't know what I think of INLAND EMPIRE "overall". I don't even know what such an "overall" would mean - should I add up the minutes I like, subtract the minutes I didn't like, and assess the film on the resulting number?




To judge a Lynch film I ask whether it stays with me; whether scenes play themselves over in my mind during the days after I watch it. And INLAND EMPIRE has enough of those scenes to make me glad I watched it. It's not Mulholland Drive, one of my favourite films of all time, but then what is?




One scene in particular is stunning - not one I've seen talked about elsewhere. It's about fifteen minutes in. Fading star Nikki Grace (Laura Dern) has won a part in a new film being directed by an unctuous Kingsley Stewart (Jeremy Irons), and she turns up on the empty, hangar-like set to do a read-through with her co-star, the sleazy Devon Berk (Justin Theroux). From what we've seen so far all these characters seem shallow; caricatures of actors and directors.




Dern, Irons, and Theroux sit at a trestle table and then Irons suggests they read through a scene where Devon's character (Billy Side) arrives home to find Nikki's character (Susan Blue) upset. After a few awkward moments, Devon/Theroux starts reading.




And everything changes. 




The camera closes in on Dern as the two characters say their lines, quietly and intently, staring at each other, the plain dialogue punctuated by long pauses. You start to wonder, is this acting or is it real? Who is meaning these lines? Susan or Nikki or Laura Dern? Billy or Devon or Justin Theroux?




"Are you crying?" whispers Billy/Devon/Theroux. 




A long pause. 




"Yes" mouths Susan/Nikki/Dern. And a tear tracks down her cheek. 




Then they are interrupted and the tension is broken.




When the interruption came I realized I'd been holding my breath during the whole reading. It's actually shocking, how fine good acting can be. The film is worth it for that scene alone.


		
