---
author: Tom Slee
categories:
- blog archive
date: 2013-06-14 16:57:52
title: Should the Apache Foundation delist Accumulo?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				The Apache Foundation hosts the [Apache Accumulo](http://accumulo.apache.org/) project, which is a data storage and retrieval system for big data [created by the NSA](http://en.wikipedia.org/wiki/Apache_Accumulo) in 2008 and submitted to Apache in 2011. Derrick Harris at GigaOm [describes](http://gigaom.com/2013/06/07/under-the-covers-of-the-nsas-big-data-effort/) Accumulo as "The technological linchpin to everything the NSA is doing from a data-analysis perspective"; it is [probably](http://www.forbes.com/sites/siliconangle/2013/06/07/how-the-nsa-tracks-your-calls/) part of the [BoundlessInformant](http://www.guardian.co.uk/world/interactive/2013/jun/08/nsa-boundless-informant-data-mining-slides) open source stack (see [this presentation [PDF]](http://www.pdl.cmu.edu/SDI/2013/slides/big_graph_nsa_rd_2013_56002v1.pdf)) that stores and analyzes the Verizon FISA data.

The [Apache Foundation](http://www.apache.org) "provides support for the Apache community of open-source software projects, which provide software products for the public good." It looks to me like Accumulo is outside that mandate.

The Apache Foundation may, because of its membership, be more open to pressure than other organizations involved in the NSA's big data effort. Are there grounds for a campaign to pressure Apache into removing Accumulo from its list of projects?

There may also be questions about more general-purpose projects that complement Accumulo, like Apache Hadoop, Apache Zookeeper, and Apache Thrift, but these were not designed so specifically for the NSA's data handling needs as Accumulo.

Meanwhile, of course, [stopwatching.us](https://optin.stopwatching.us/).

Update June 15: Follow-up post, [yes it should](http://tomslee.net/2013/06/587.html).		
