---
author: Tom Slee
categories:
- blog archive
date: 2007-02-03 19:29:57
title: 'In memoriam: Anatol Rapoport'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I saw in the Globe and Mail that Anatol Rapoport died in Toronto on January 20, at the age of, I think, 95. He was an important person in many ways. I never met him, but I've been influenced both directly and indirectly by his mix of strong intelligence and conviction.




For anyone reading this who doesn't know who Rapoport was, here are a few scattered items I know of about the man. There is more in the [Globe and Mail obituary](http://www.theglobeandmail.com/servlet/story/LAC.20070131.OBRAPO31/TPStory/?query=rapoport).




  * His book "Strategy and Conscience" was a unique contribution to the struggle against militaristic thinking in the cold war. It responded to the technicians of the Rand Corporation and others whose supposedly rational thinking was helping to guide strategy. Rapoport's response to them was unique. He took them on at their own game, so to speak, and showed how the game theory approach missed key aspects of the conflict. He was not "anti game theory" by any means -- quite the opposite -- but also knew the limits of theory and the dangers of elegant but ultimately simplistic thinking.


  * As game theory developed in the '50s and '60s Rapoport was one of those who investigated the interface between the formal side of game theory and a recognition that people behave in a rich psychological manner. This form of experimentation has continued and expanded right through to the present day.


  * I read some of his 1984 book "Mathematical Methods in the Social and Behavioral Sciences" and it's a great book. There are not many people who have a strong and original mathematical mind and yet know how to apply it with wisdom, but Rapoport's reach and depth in the book is hugely impressive.


  * In addition to this intellectual strength, Rapoport was one of the leading figures in Peace Studies in this country. It's taken a long effort from many people to make the obvious point that war is a complex and important problem, and if we are to understand how to achieve peaceful outcomes then no one discipline is enough. We need to bring the insights of as many disciplines as possible to bear on one of the most important problems of our times. There is a need for a strong intellectual effort to accompany other efforts in the search for peace, and Peace Studies is where that comes from.



I know two people who have known Rapoport at different times. Both were very impressed by him personally. He was obviously a cultured, somewhat intimidating, productive and original thinker and person. I wish I'd met him.  
  
In the acknowledgement at the beginning of "No One Makes You Shop at Wal-Mart" I listed several people whose intellectual debt is obvious throughout the book. In the 10 months since it was published two of those have died (Jane Jacobs and Anatol Rapoport). The world is worse off without them.




One final note. In looking for more information about Rapoport I came across a quotation from Daniel Dennett (another of my favourite writers) who [wrote](http://ase.tufts.edu/cogstud/papers/dawkinsreview.pdf) this:

<blockquote>The social psychologist and game theorist Anatol Rapoport (creator of the winning Tit-for-Tat strategy in Robert Axelrod’s legendary prisoner’s dilemma tournament) once promulgated a list of rules for how to write a successful critical commentary on an opponent’s work. First, he said, you must attempt to re-express your opponent’s position so clearly, vividly and fairly that your opponent says “Thanks, I wish I’d thought of putting it that way.” Then, you should list any points of agreement (especially if they are not matters of general or widespread agreement), and third, you should mention anything you have learned from your opponent. Only then are you permitted to say so much as a word of rebuttal or criticism.
> 
> </blockquote>

Challenging words.


		
