---
author: Tom Slee
categories:
- blog archive
date: 2009-03-02 22:35:42
title: The Brilliant Bechdel/Wallace Movie Test
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I had not heard of this amazing test until seeing a mention in the morning paper, but it has been around since 1985. That was when Liz Wallace told it to her friend Alison Bechdel who put it in the comic strip Dykes to Watch Out For. See [here](http://www.dykestowatchoutfor.com/the-rule) for the comic and [here](http://bitchphd.blogspot.com/2008/07/bechdel-rule-and-dark-knight.html) for discussion.

For others who have been in the dark, here is their devastatingly simple rule.  
  


To be worth watching, a movie must



  1. Have at least two women in it,


  2. who talk to each other,


  3. about something besides a man.


This morning's paper went through the Time Magazine top ten movies of all time list. Classics like The Godfather and 2001 A Space Odyssey fail. I have a feeling both TV programs I watched this evening fail. And I'm half way through reading The Unbearable Lightness of Being, which I think is likely to fail as well.


		
