---
author: Tom Slee
categories:
- blog archive
date: 2010-11-04 20:54:00
title: Eleanor Wachtel interviews John Le Carre
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I am a big fan of CBC's _Writers and Company_, and Eleanor Wachtel's interviewing in particular.




Her two-parter with John Le Carre is brilliant, with Le Carre's reflections on his father, on the deep state, on the writer's "chip of ice in the heart", on Tony Blair ("We've had a Prime Minister who to my mind committed the biggest crime any Prime Minister - any Leader - can commit: that is, to take a country to war under false pretences.")




Le Carre has this to say about the information society:




<blockquote>

> 
> "The dissemination of information on a vast scale is not the same as the dissemination of the truth. Thus we still have an extraordinary percentage of the American people who believe that Saddam Hussein was responsible for the twin towers; that the war against Iraq was a war to avert a threat to the United States. I am appalled by the extent to which the increase in communication adds to the power of manipulation by politicians."
> 
> 
</blockquote>




And much more. Listen [here](http://www.cbc.ca/writersandcompany/episode/2010/10/10/sunday-10-october-2010-and-tuesday-12-october-2010-john-le-carr-interview/) and [here](http://www.cbc.ca/writersandcompany/episode/2010/10/17/john-le-carre-interview-part-two/).


		
