---
author: Tom Slee
categories:
- blog archive
date: 2007-03-08 22:41:07
title: Progressive Blogger Welcome and Long Tail 7 Teaser
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

First, welcome to readers from [progressivebloggers.ca](http://www.progressivebloggers.ca), where I am now an affiliate (just).




If you are coming here for the first time, let me catch you up. I'm in the middle of a chapter-by-chapter, nearly page-by-page critique of Chris Anderson's book about "the future of business" called "[The Long Tail](http://www.thelongtail.com/)". I'm doing it because the book is widely read, influential, enthusiastically pro-market, and also sloppy and wrong wrong wrong. If you want to see the beginning of the series, go [here.](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html) If you want to see them all in descending order, go [here](http://whimsley.typepad.com/whimsley/the_long_tail/index.html).




I usually try for about three chapters a week, but I only got two done over the last week, so here's a bonus teaser for the next chapter, which is Chapter 7. It's a little thing - one sentence in the middle of the book - but it says something about the author's cavalier attitude to facts.




Chris Anderson says:

<blockquote>Dell spends hundreds of millions each year on promoting its quality and
customer service, but if you Google "dell hell" you'll get 55,000 pages
of results.[99] (I put page numbers in square brackets)
> 
> </blockquote>

At ten results per page (the default) that's 550,000 results. Let's see if we can reproduce this number.




First let's try "dell hell" in quotes, as he shows it. Over at the right of the page it says "results 1-10 of about 69,600". That's 696 pages, not 55,000. 




But Google's "about" numbers are notoriously inaccurate. To get a more precise number, first I recommend changing the preferences to return 100 results per page (less clicking), redo the search, and then click through the pages. How many results do you end up with? A total of 693. That's 70 pages of results, not 55,000.




Suppose he meant without the quotes. Let's try that. The "about" number at the top right of the page is now 1,620,000 - or 162,000 pages of regular results. That's about three times the number Anderson quotes - perhaps that's what's changed in the last two years. So this is where he gets his number from, I guess.




But as I said, that "about" number is notoriously unreliable. Click through the pages and how many results do you get? 753. That's 76 pages of results at the default ten-per-page.




So Anderson claims 55,000 pages of results because it's a big number, and a big number illustrates the point he is making, but a five minute test shows that he is overestimating by about 54,924.




So much for that claim. And unfortunately (in case you were wondering what I think) it's typical of the book.


		
