---
author: Tom Slee
categories:
- blog archive
date: 2009-01-24 08:57:38
title: The Outsider Manoeuvre
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Writers and actors are notorious for seeing themselves as outsiders. "Why did you become an actor?" they are asked. "Well, I was always a bit of an outsider..." This morning, take director [Terence Davies](http://www.theglobeandmail.com/servlet/story/LAC.20090124.DAVIES24/TPStory/TPEntertainment/Movies/):

<blockquote>"I felt like an outsider because I was from a large working-class family. And I spoke with this kind of [posh] accent even by the time I was 11," Davies noted in our interview. "I've always felt an outsider. I think I was reasonably intelligent, I largely taught myself because I didn't go to university. And I was Catholic. And I was gay. I mean, in a large, working-class Catholic family, that's very hard."
> 
> </blockquote>

He may be right, what do I know? But it is a standard manoeuvre and we should not trust it.

  


Politicians are fond of the same trick, of course. Americans saw this in spades over the last few months with the self-positioning of the Republicans, after eight years in power, as "mavericks".

  


And the phenomenon reaches into the world of blogs as well. [Dan Gilmor at Talking Points Memo](http://tpmcafe.talkingpointsmemo.com/2009/01/23/the_medias_role_in_the_financial_crisis/) writes about "The Media's Role in the Financial Crisis", making it clear that TPM and DG in particular are not part of the media. They are outsiders.

  


But they are not.

  


Dan Gilmor is, [according to his Wikipedia entry](http://en.wikipedia.org/wiki/Dan_Gillmor), Director of a new Knight Center for Digital Media Entrepreneurship at Arizona State University's Walter Cronkite School of Journalism and Mass Communication. He's a long-time journalist. He just doesn't want to appear as one - hence his book title from a few years ago "We the Media".

  


And TPM is a widely-read collection of writings, many by actual journalists, surrounded by advertisements. It may not have started off as media, but it is now media in most senses we use the word.

  


I saw a link to the Gilmor piece posted on [boingboing.net](http://www.boingboing.net/2009/01/23/media-helped-create.html), introduced like this:

<blockquote>In Talking Points Memo, Dan Gillmor makes some stinging points about the media's complicity in manufacturing the financial crisis by unquestioningly promoting reckless bubble spending while pooh-poohing any idea that the bill would come due some day:
> 
> </blockquote>

But boingboing is also advertising-funded, and run by people who write  as a full time job. It is media.

  


The First Rule of Critical Reading, digital or otherwise, should be "don't believe what people say about themselves".  Particularly if they position themselves as outsiders.  


  


Take it from me. Look around: I have no advertising here and I'm not paid to write this stuff.

  


I'm an outsider.


		
