---
author: Tom Slee
categories:
- blog archive
date: 2011-04-29 22:23:39
title: '"Real-Time Entertainment" outpacing the web'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

As measured by the byte, the Internet is increasingly a video-consumption medium dominated by a small number of large providers. Wired [reports](http://www.wired.com/epicenter/2011/04/netflix-file-sharing/) that "In the evenings, Netflix accounts for more than 40 percent of U.S. bandwidth usage, by some measurements", more than the cumulative amount of web browsing traffic.




So far as traffic is concerned, the Internet is becoming (as Tim Wu has warned us it might) a medium for commercial broadcast transmission of studio-produced products.




Netflix's success is starting to sideline peer-to-peer traffic in movies, just as iTunes sidelined peer-to-peer traffic in music. To quote from the Wired article again: “I think Netflix, iTunes and Direct Download all play a role in the diminishing P2P traffic volumes,” [Arbor Networks chief scientist Craig] Labovitz said. Direct download refers to sites such as Rapid Upload and MegaVideo that many have turned to, to share files with friends and the world, without the need for peer-to-peer software.


		
