---
author: Tom Slee
categories:
- blog archive
date: 2008-03-17 21:40:02
title: Long Tail of News? Actually No.
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[Second](http://whimsley.typepad.com/whimsley/2008/02/long-tail-of-bo.html) in a series.




Ironically, [Wired](http://news.wired.com/dynamic/stories/S/STATE_OF_JOURNALISM?SITE=WIRE&SECTION=HOME&TEMPLATE=DEFAULT&CTIME=2008-03-16-16-32-59) points to a report by the (American) Project for Excellence in Journalism on [The State of the (American) News Media 2008](http://www.stateofthenewsmedia.org/2008/). Here is a little excerpt from the Executive Summary.

<blockquote>The state of the American news media in 2008 is more troubled than a year ago.  
And the problems, increasingly, appear to be different than many experts have predicted.  
Critics have tended to see technology democratizing the media and traditional journalism in decline. Audiences, they say, are fragmenting across new information sources, breaking the grip of media elites. Some people even advocate the notion of “The Long Tail,” the idea that, with the Web’s infinite potential for depth, millions of niche markets could be bigger than the old mass market dominated by large companies and producers.1  
The reality, increasingly, appears more complex. Looking closely, a clear case for democratization is harder to make. Even with so many new sources, more people now consume what old-media newsrooms produce, particularly from print, than before. Online, for instance, the top 10 news Web sites, drawing mostly from old brands, are more of an oligarchy, commanding a larger share of audience than they did in the legacy media. The verdict on citizen media for now suggests limitations. And research shows blogs and public affairs Web sites attract a smaller audience than expected and are produced by people with even more elite backgrounds than journalists.
> 
> </blockquote>


		
