---
author: Tom Slee
categories:
- blog archive
date: 2011-10-16 15:07:42
title: 'Morozov on Jarvis: Is There a Point?'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Jeff Jarvis's 2009 book _What Would Google Do? _is a breathless paean to the benefits of sharing, linking, and being open, but it has not a single reference or footnote, and no bibliography. Jarvis extols the virtues of listening and speaks of mutuality but in the end, of course, the benefits flow one way. Jeff Jarvis has become wealthy from this new ethic of sharing -- he is fond of "starting conversations" which he can then take ownership of -- but when it comes to giving credit to those who come before, for example by referencing previous writers on the topics he addresses, well it just seems like it's too much work for him. The book is one long argument by assertion, unsupported by facts and liberally sprinkled with utterances like "small is the new big" or "We have shifted from an economy based on scarcity to one based on abundance" or "Google has built its empire on trusting us".




It looks like his new book, _Public Parts_, is more of the same. _The New Republic_ just published a long review of the book by Evgeny Morozov[ here](http://www.tnr.com/print/article/books/magazine/96116/the-internet-intellectual) or [here](http://www.tnr.com/article/books/magazine/96116/the-internet-intellectual). It's forthright, opinionated, angry, entertaining and also makes some damning arguments against the book.




Jeff Jarvis responds to the review [here](http://www.buzzmachine.com/2011/10/13/a-bad-review-of-me/) in bizarre fashion. He first raises the prospect of personal prejudice ("Morozov reliably dislikes me, just as he dislikes people I quote") and then dismisses the review as "he writes only a personal attack". Morozov spends 800 words critiquing Jarvis's misunderstanding of ideas about the public sphere and his oversimplification of Habermas, which Jarvis distorts and reduces to a complaint "about the names Habermas and Oprah appearing in the same book". Morozov spends 600 words on _Public Parts'_ culturally narrow ideas about Germany, Finland, and the strange attitudes of non-Americans to privacy, which Jarvis encapsulates as "[Morozov] finds Streetview to be a case of Germans 'tyrannized by an American company'". In short, Jarvis exaggerates and distorts the arguments before dismissing them.




*  * *




To anyone who reads carefully, the argument is over and Morozov wins, but unfortunately that's not the end of the story. Much of Morozov's frustration comes from Jarvis's refusal to engage with the world of facts. He stays safely in the world of pronouncement ("Publicness is a sign of our empowerment", "the crowd owns the wisdom of the crowd" and so on). Jarvis is skilled at the marketing of ideas: if you Google [publicness], four of the first page listings are about or by Jarvis, and this canny use of branding will keep his profile high, well beyond the reach of factual criticism. Jarvis knows his audience and what they want to hear, and what they want is a self-help message for businesses: the world is changing, everything you thought you knew is irrelevant, and I have the key to the future.




So what, then, is the point of the hours Morozov spent writing a 7,000 word review if he won't reach Jarvis's core constituency? There are two other audiences that such pieces can reach. One is to shore up those who broadly agree with Morozov's perspective (yes, like me) that there is an ulterior motive, a very familiar and old-fashioned one, behind this talk of sharing and publicness. We cannot read every new book, watch every new TED talk, attend every conference and yet we do need to stay current and stay informed. I am not going to read _Public Parts_ because there are so many other things to read, but I cannot afford to be completely ignorant of it. Morozov's review does the job for me.




The second is more important. Many people are attracted by the romantic rhetoric of openness, sharing, and the end of existing institutions, but not all have yet sorted out the political consequences of a commitment to these virtues. There are still people on the fence - and it's important for these people to know that, no matter what progressive-sounding language is used, some of the most idealistic arguments for sharing are made by those who will mine the data you provide in order to build fortunes from advertising. To shape that debate and to keep a political space open for an Internet that does not simply follow the venture-capitalist idea of progress, we need fact based arguments, so kudos to Morozov for doing the necessary work in this case.


		
