---
author: Tom Slee
categories:
- blog archive
date: 2006-08-04 21:44:01
title: 'UnMarkets Everywhere: A Courageous "Blogger"'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

From the recently-discovered [weblog of Michael Perelman](http://michaelperelman.wordpress.com/), an uplifting story about a civic-minded news service in Monrovia, Liberia.




Perelman says:

<blockquote>I don’t really have a good foundation in this
technology. I realize that it doesn’t take much to sit at a keyboard
and make grant pronouncements about the way the world should be.
> 
> Today I read in the New York Times about the
“blogger” using centuries-old technology in a way that puts the modern
media to shame.
> 
> The article describes Alfred Sirleaf, the
33-year-old managing editor of The Daily Talk, a white plywood shed
trumpeting the latest headlines along Tubman Boulevard, one of the
capital’s main thoroughfares.
> 
> 

> 
> He writes his stories very carefully on large
blackboards and even makes accommodations to help communicate the
material to illiterates. He had to struggle to get a high school
education. He has been arrested. And yet he continues to persevere.
> 
> 

> 
> And most of all the displays a spirit that puts the the corporate media to shame.
> 
> </blockquote>

From the New York Times article:

<blockquote>The shoestring operation brings him no income.
> 
> 

> 
> “I just manage along with whatever money I can
find,” he said. Occasional gifts of cash and pre-paid cellphone cards
keep him in business.
> 
> </blockquote>




[Go read it](http://michaelperelman.wordpress.com/2006/08/04/a-courageous-blogger/).


		
