---
author: Tom Slee
categories:
- blog archive
date: 2013-01-04 15:56:46
title: Self-Assessment 2013
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_Attention conservation notice: self-involvement._




_Update:_ Comments are closed because, in the light of morning, this looked like fishing for compliments (with added whining!) But no! It is merely an aide-resolution, to get myself moving forward in 2013.




## Background




New Year. Time to take a realistic look at the state of my writing.




The goal of my writing was to have an impact, however small, on issues that matter to me. I had been an activist in a number of political, union, and social justice organizations, and writing seemed to be a way to continue to contribute that fit into a new stage of my life. I've been trying to write in my spare time for roughly 15 years now. When I started, my children were entering school; now they are adults.




The first half of that 15 years was spent writing and studying/researching _No One Makes You Shop at Wal-Mart_. Whimsley started off as an attempt to promote the book, but soon moved into technology & politics, where it has stayed ever since.




The total cost of this writing project to me and my family is now well into six figures in foregone income: several years ago I "negotiated" a four-day working week, largely to pursue this project. On the other hand, it has to coexist with a nearly-full-time job, which means that although much of what I write has a pseudo-academic bent, I doubt that I'm in a position to obtain qualifications relevant to what I write about.




I hesitate to post this, as it's self-involved and not very cheery, but it may provide some useful information for other bloggers.




## Assessment




Here are some metrics for the seven years since _No One Makes You Shop at Wal-Mart_ was published, most of which relate to my blogging:






  * Sales of "No One Makes You Shop at Wal-Mart". Around 1,000 2,000. Most in the first year. (Thanks to Brad DeLong and Alex Tabarrok for many of those)


  * Blog readership: Sitemeter says about 100 hits a day, and I guess that about half of that is people/bots who don't read. The traffic is about the same as it was in 2008.


  * Number of invitations to contribute to other publications: 3. (Thanks to Bronwyn Drainie and Alastair Cheng)


  * Number of invitations to contribute to other sites: 3. (Thanks to Henry Farrell)


  * Number of invitations to conferences and workshops: 2. (Thanks again, Henry)


  * Number of publications to have quoted my work, to my knowledge: 1. (Thanks Evgeny Morozov)


  * Awards, prizes, or nominations for same: 0.




What can I say? That is not a picture of success, and given the generous support I have received, the responsibility for remaining mistakes clearly lies, as they say, with the author.




My major reward from blogging has been to discover a small but select group of very smart people who have continued to read this blog, promote it from time to time, and engage in conversation. Thanks to each of you.




The highlight of this year came out of a rant on the "Open Data movement", written in a fit of pique one morning and publicised by Evgeny Morozov on Twitter, which led to an opportunity to post at Crooked Timber on the topic. Second was contributing to the Literary Review of Canada again. But let's be honest: writing to have an impact at the age of 53 feels very different from writing at the age of 38, and the numbers make it clear that it's not working. To reinforce that feeling, the traffic for an individual post at the blog depends hugely on whether some of a small number of individuals link to it: I am still dependent, that is to say, on patronage and on chance, and I have not managed to build an audience of my own to sustain significant interest.




### Diagnosis




I suspect my own failings are the major cause for this poor performance. I write slowly and infrequently, and usually long pieces. Clearly the style and content of my writing has failed to build a significant audience.




A second reason is that, naive as this sounds (especially in the light of what I write), I actually thought that writing stuff and putting it on the web would be enough to build a reputation and an audience. Clearly it isn't, and that should not be surprising. I have no credentials behind what I write, I'm terrible at self-promotion, my networks related to my writing are minimal, and although some pieces have been provocative I am uncomfortable in the culture of quickfire debate that drives much political writing. None of those things is likely to change. 




If anything, the effort has emphasized to me the importance of credentials. I know that I use them myself: coming across a new blog or a new book I look for what others have said about the writer. I don't know why I wouldn't expect others to do anything different when deciding about me. 




### Prognosis




Uncertain. I suspect that I will continue here for a while yet, but something has to change. Fortunately I will have quite a lot of time in 2013, so it's not a bad time to try to change something. I am looking at these possibilities. 






  1. See what I can do with [this paper](http://papers.ssrn.com/abstract=2116471) to gain credentials. I am circulating it, but see comment on self-promotion above.


  2. Pull together a book based on what I've been doing here (likely working title "Wikibollocks: The Broken Promises of Openness") but I suspect that it would be too dry for a popular book (plus I cannot point to a big reader base when approaching publishers), and that I'm undercredentialled to write an academic book. If I were a publisher I would not take me on.


  3. What's that? Why yes, I am open to offers.

So, we'll have to see.  



## Favourites




On the bright side, here are some pieces I still feel good about (31 of them). It's good to have them still out there.




### The Sharing Economy






  * [Peer-to-Peer Hucksterism: An Open Letter to Tim Wu](/2012/12/peer-to-peer-hucksterism-an-open-letter-to-tim-wu.html) (2013)




### Open Data






  * [Why the "Open Data Movement" is a Joke](/2012/05/why-the-open-data-movement-is-a-joke.html) (2012)


  * [Open Data Movement Redux: Tribes and Contradictions](/2012/05/open-data-movement-redux-tribes-and-contradictions.html) (2012)


  * [Seeing Like a Geek](http://crookedtimber.org/2012/06/25/seeing-like-a-geek/) (2012) - _Invited_, at Crooked Timber




### Open Government






  * [What is Wrong with Government 2.0](2010/11/what-is-wrong-with-government-20.html) (2010)


  * [What Else is Wrong with Government 2.0](/2010/11/what-else-is-wrong-with-government-20.html) (2010)


  * [WikiLeaks Shines a Light on the Limits of Techno-Politics](/2010/12/wikileaks-shines-a-light-on-the-limits-of-techno-politics.html) (2010)




### Open Source






  * [Linux Grows Up and Gets a Job](/2008/04/linux-grows-up.html) (2008)


  * [Paying for Linux](/2008/05/linux-again.html) (2008)




### Reputation Systems






  * [Click to Judge](http://reviewcanada.ca/reviews/2012/04/01/click-to-judge/) (2012) - _Invited_, at the Literary Review of Canada


  * [Online Monoculture and the End of the Niche](/2009/03/online-monoculture-and-the-end-of-the-niche.html) (2009) - a little theory


  * [Netflix Prize: Was the Napoleon Dynamite Problem Solved?](/2009/10/netflix-prize-was-the-napoleon-dynamite-problem-solved.html) (2009)


  * [The Netflix Prize: 300 Days Later](/2007/07/the-limitations.html) (2007)




### Privacy and Data Aggregation






  * [Data Anonymization and Re-identification: Some Basics of Data Privacy](/2011/09/data-anonymization-and-re-identification-some-basics-of-data-privacy.html) (2012) - technical




### Digital Technologies and the Arab Spring uprisings






  * [Digital Activism: If Information is Not the Problem, Information is Not the Solution](/2010/01/digital-activism-if-information-is-not-the-problem-information-is-not-the-solution.html) (2010)


  * [Egypt's "Facebook Revolution": Looking Under the Lamp Post?](/2011/02/egypts-facebook-revolution-looking-under-the-lamp-post-.html) (2011)


  * [More Egypt, More Facebook](/2011/02/more-egypt-more-facebook.html) (2011)


  * [Internet-Centrism 2 (of 3)](/2011/09/so-three-cheers-for-evgeny-now-back-to-the-mit-review-articles-some-of-which-display-the-very-internet-centrism-that-moroz.html) (2011)


  * [Internet-Centrism 3 (of 3)](/2011/09/earlier-today-i-thought-i-was-doomed-to-fail-that-part-3-of-this-prematurely-announced-trilogy-was-just-not-going-to-get-wr.html) (2011)


  * [Identity, Institutions, and Uprisings](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2116471) (2012) - academic paper (submitted)


  * [When Theories Matter: Uprisings in Authoritarian States](/2012/12/when-theories-matter-uprisings-in-authoritarian-states.html) (2012)


  * [What Cascade Theories Don't Tell Us](/2012/12/what-cascade-theories-leave-out.html) (2012)




### Irritabilia






  * [Wikibollocks: The Shirky Rules](/2010/04/wikibollocks-the-shirky-rules.html) (2010)


  * [Mr. Google's Guidebook](/2008/03/mr-googles-guid.html) (2008) - a little whimsy. My most-read post.




### Book Reviews




There are quite a few, but these are my favourites






  * [The Long Tail](/2007/03/the_long_tail_l.html) (2007) - 160 pages of page-by-page critique


  * [The Pirate's Dilemma](/2009/11/pirates-dilemma-review-remixed.html), by Matt Mason (2009) - stream of irritation


  * [Here Comes Everybody](/2008/04/here-comes-ever.html) by Clay Shirky (2008)


  * [Identity Economics](/2010/05/identity-economics-by-george-akerlof-and-rachel-kranton-a-rambling-review.html), by George Akerlof and Rachel Kranton (2010)


  * [The Myth of Digital Democracy](/2010/01/the-myth-of-digital-democracymatthew-hindman-princeton-university-press-2009matthew-hindmansthe-myth-of-digital-democracyfi.html), by Matthew Hindman (2010)


  * [Adapt](/2011/06/an-uncertain-world-ii-adapt-by-tim-harford.html), by Tim Harford (2011) - probably my favourite


  * [Sixty-Two Things Wrong with "Future Perfect"](/2012/12/sixty-two-things-wrong-with-future-perfect.html) (2012)





		
