---
author: Tom Slee
categories:
- blog archive
date: 2006-11-22 13:11:33
title: Best Seller!
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Not quite the New York Times best seller list, but I am on the nearly-as-important [Words Worth Books best seller list](http://www.wordsworthbooks.com/BestSellers.htm), appearing at number 5 on their paperback nonfiction list (ahead of Al Gore's Inconvenient Truth but behind Stephen Lewis, Jane Jacobs and "Waterloo Trails and Bikeways").




**Paperback Non Fiction**




212 - Race Against Time 2/E - Stephen Lewis  
116 - Waterloo Trails & Bikeways  
87 - Fantastic Realities - Frank Wilczek   
80 - Dark Age Ahead - Jane Jacobs  
**63 - No One Makes You Shop at Wal-Mart** **- Tom Slee**  
61 - Inconvenient Truth - Al Gore   
61 - End of Food - Thomas Pawlick   
50 - Guidebook to Woolwich Trails - Trails Group  
49 - Manitoulin Rocks - Peter Russell  
45 - Temperament - Stuart Isacoff  
42 - Sophie's World - Jostein Gaarder  
  
I know that part of the reason is that the staff has been helping to sell the book (Dave, this means you), so many thanks to Words Worth Books for their support of _No One Makes You Shop At Wal-Mart_.




Link: [Best Sellers](http://www.wordsworthbooks.com/BestSellers.htm). 




Also see the Words Worth blog, called (I have no idea why) [How To Furnish a Room](http://howtofurnisharoom.blogspot.com/).


		
