---
author: Tom Slee
categories:
- blog archive
date: 2005-11-18 19:59:22
title: Healthcare Delivery
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

The healthcare debate south of the border is ferocious, of course. It is good to see one of my favourite blogs, [Brad DeLong's Semi-Daily Journal](http://delong.typepad.com/sdj/2005/11/paul_krugman_ke.html)
keep on delivering the goods on the issue, even if this time BDL is
just passing on the latest Paul Krugman New York Times column on the
issue.




DeLong's was the first weblog I tracked regularly, and it
is still one of the best. I have no clue how he keeps posting several
times a day on average for (pause to see how long it has been going)
well, a few years at least on everything from his main theme
(economics, wot wiv him being an economics lecturer and all) to
America's Stupidest Dog to many other things. Anyone reading here
should probably go [there instead](http://delong.typepad.com/sdj/).


		
