---
author: Tom Slee
categories:
- blog archive
date: 2015-05-22 15:42:59
title: Stallman on Openness. Don't be an Ass
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				In today's Guardian Richard Stallman [writes](http://www.theguardian.com/technology/2015/may/22/malware-viruses-companies-preinstall) a call-to-arms against technological surveillance. His form of opposition is to create free/libre software, but that is no solution.

Stallman confronts his readers: "Should you trust an internet of proprietary software things? Don’t be an ass." He claims that "proprietary software is computing for suckers" and that proprietary software is a virtual synonym for malware. Of course proprietary software can be used and is being used to snoop on users, to shackle users, and to report data to companies. But so is free/libre software. Free/libre is not a magic talisman that protects you from all these harms. An internet of open source software things could be just as intrusive as an internet of proprietary software things.

Stallman writes: "What kinds of programs constitute malware? Operating systems, first of all. Windows snoops on users, shackles users and, on mobiles, censors apps; it also has a universal back door that allows Microsoft to remotely impose software changes." 

So what about the free/libre alternative Linux, which apparently he wrote ("I developed the GNU operating system, which is [often called Linux](http://gnu.org/gnu/linux-and-gnu.html)"), probably right after he "started free software in the 80s". My Android phone runs Linux, and it spies on me. And all those NSA computers used for spying? They run on Linux. The biggest corporate contributor to Linux is Intel: is Intel morally better than Microsoft as a result of its contributions? (hint: No)

Or what about the databases used to actually store all that snooping information. The Acculumo database that the NSA developed specifically for the purpose and which is now kindly supported by the Apache Foundation; the Hadoop distributed file system that underlies Accumulo; the Java programming language used to write Hadoop and Accumulo? All open source.

In short, free/libre software is no longer an alternative to corporate and state snooping and shackling, it's part of the problem.

Stallman avoids this conclusion by mixing up two separate things as if they are one. He calls on his readers to resist surveillance "by rejecting proprietary software and web services that snoop or track". These are two different things. "Web services that snoop or track" can be and often are built on free/libre software. 

Stallman also calls on his readers to resist surveillance "by organising to develop free/libre replacement systems and web services that don’t track who uses them". But again this is mixing up two separate things. "Web services that don't track who uses them" can be built on proprietary software just as easily as they can be built on free/libre software.

Stallman gets it right in his third call, to resist surveillance "by legislation to criminalise various sorts of malware practices". The problem is one of practices, not free/libre vs proprietary software. I know some readers will say I am trying to blame the technology, but they will be wrong. And technology is not the answer either. Much as Stallman and others would like to believe that their practices of software development (free/libre versus proprietary) makes them rebellious hackers against an oppressive empire, freedom-loving opponents of surveillance, they do not.		
