---
author: Tom Slee
categories:
- blog archive
date: 2006-03-07 21:58:41
title: Stuff and Status
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

"Where money speaks, there all law is silent" - Anon, reign of Henry III (1216 - 1272).




MarketThinkers like the Cato Institute, have a blind spot when it comes to inequality, and David Schmidtz has it in spades, judging from his Cato Unbound lead essay "[When Inequality Matters](http://www.cato-unbound.org/2006/03/06/david-schmidtz/when-equality-matters/)". 




Schmidtz distinguishes two forms of egalitarianism: the "liberal egalitarianism" ("liberal" meaning something closer to conservatives or economic libertarians in the context of Cato Institute papers) and plain ol' "egalitarianism". The former (which Schmidtz approves of) is focused on eliminating inequality of rank and status (the "right to command"), and Schmidtz is all in favour of getting rid of "any natural ranking of individuals into those who command and those who obey." Fair enough. The later is apparently focused on reducing inequality of (wealth) distribution, and this is not something Schmidtz likes. He sums the difference up by saying "Liberal egalitarianism has a history of being, first and foremost, a concern about status, not stuff." Most of his essay is talking about why he opposes inequality of status, but is happy with inequality of "stuff". 




But these two are absolutely and intricately mixed, as Anon recognized three quarters of a millenium ago. You can't have inequality of stuff without inequality of status. What do people do with their "stuff"? They buy political influence and use their economic power when bargaining with others. In short, they use it to promote an inequality of status. There is no significant difference between the two, and for some reason Cato and those just don't see this. I have no idea why not.




There is a discussion at [Crooked Timber: Cato on inequality](http://crookedtimber.org/?p=4399) but it goes off the rails.


		
