---
author: Tom Slee
categories:
- blog archive
date: 2006-03-11 19:54:30
title: "Economist's View: Mankiw on Globalization: People Should Move"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

From Mark Thoma yet again, an example of just how entrenched the unrealistic picture of perfect markets is. A lot of my book is spent arguing that the simplistic free-market picture of the world is too influential and that we really need to get rid of it from public debate. From time to time I wonder if I am being unfair and setting up a straw man. Then I look around and it really does seem that even (or especially?) influential, high-profile people do have this simplistic view of the way the world works stuck firmly in their brains. Greg Mankiw was Chairman of the President's Council of
Economic Advisers from 2003 and 2005.




In [Mankiw on Globalization: People Should Move](http://economistsview.typepad.com/economistsview/2006/03/mankiw_on_globa.html) Mark Thoma reports a panel discussion chaired by now ex-Harvard president Larry Summers:

<blockquote>Summers urged the economists, who kept returning to nuanced policy
discussions, to come up with more practical political advice. Referring to
Flint, Mich., where workers’ jobs are being outsourced, he challenged the
academics to come up with a realistic suggestion for the Buick-city mayor. 
> 
> </blockquote>




<blockquote>“That’s the political reality,” said Summers, pointing to former Senator Bob
Graham D-Fla. in the audience who was nodding in agreement. ... “...Maybe the answer is [to] put an economics
course in every high school and we’ll be OK,” said Summers, taking a jab at
Mankiw who earlier suggested that introducing economic principles to Americans
in high school would help people better understand globalization. 
> 
> </blockquote>




<blockquote>“I don’t know about the mayor, but I know what the people should do,” Mankiw
said, “The people should move.” 
> 
> </blockquote>




<blockquote>Summers countered, “Where do you think the people in Flint should go?”...
> 
> </blockquote>


		
