---
author: Tom Slee
categories:
- blog archive
date: 2007-02-24 22:06:48
title: The Long Tail 3 - A Short History of the Long Tail
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Back from doing some actual work for a few days, this is another part of my critical reader's companion to _The Long Tail_ and discusses "Chapter 3 - A Short History of the Long Tail". Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). The previous part in this series is [here](http://whimsley.typepad.com/whimsley/2007/02/this_is_part_of.html).  
  
Chapter 3 is a complement to Chapter 2 and completes Part One of the book (although it's not labelled as such). While Chapter 2 set out to chart the rise and fall of the blockbuster, Chapter 3 charts the rise and rise of the Long Tail in a short ten page trip from the Sears Catalogue the web and beyond. It's a short chapter, and a digression from the main thread of the book, so I don't have a whole lot to say about it. But I said I'd go through chapter by chapter so I will.  
  
The first section describes the rise of the Sears Wish Book and the catalogue retailing business. The catalogue allowed people - especially those in small towns and rural areas (as piefuchs pointed out in comments on the [previous part](http://whimsley.typepad.com/whimsley/2007/02/this_is_part_of.html)) - to choose from a much wider range of goods than ever before (200,000 in the 1897 Wish Book [43]) because the catalogue replaced physical shelves in physical stores. "With the heavy thunk of a single mail drop, the choice of available products increased a thousandfold from the typical inventory at the general store". Sears was able to do this because, like Wal-Mart many years later, it introduced new efficiencies into its management of the supply chain. Big warehouses in Chicago together with "virtual" warehouses that were its network of suppliers meant that they could stock items efficiently. It was a big change. The Sears Catalogue has several parallels to the online world that Anderson calls "the ultimate catalog". One that he does not mention is that it was not easily mimicked. Once there is a big catalogue, a second big catalogue doesn't help much. The cost of keeping an item on the virtual shelf -- whether that be a catalogue or a web server -- is small, but the cost of building a virtual shelf in the first place is actually pretty big, and once someone's built a good one it is difficult to compete with them.  
  
Feeding the Tail [44-46] describes how supermarkets did the same thing as the Sears Catalogue had done years before - provided "greater variety, lower prices, and one-stop shopping" [45]: basically they exploited economies of scale. In fact, Anderson tells us the supermarket took off during the 1950s and 1960s: those years of "lockstep culture"[29] described in Chapter 2 did after all have another side to them and that side was variety - in the form of thousands of items on the shelves of the supermarket. It is worth reflecting on these parallel stories that Anderson is telling us. To characterize the 1950s as an age of mass culture and then to describe the rise of a culture of variety at the same time does raise questions. It is often said that the plural of anecdote is not data, and this chapter reminds us why. There are many stories in this world, stories that are true and which can illustrate any message you want to deliver. But stories by themselves are not enough to support broad conclusions. The chapter also reminds us that there are other sides to our current day culture in addition to the availability of lots of online books. We'll see more of what those are in later chapters, but Wal-Mart is, as pointed out in the discussion of Chapter 1, just as much a creature of the modern technological world as Amazon.  
  
The Touchstone Customer [45-46] is a digression on how new technology -- toll-free calling and credit cards -- led to a resurgence in catalogue shopping, again by making it easier for sellers to present a wide selection of items to their customers, but it is The Ultimate Catalog [47-49] that brings to the real point of the chapter, describing Jeff Bezos building the Amazon enterprise. The discussion shows how the book market has some properties (a number of products too large for even the bulkiest paper catalogue, a mature wholesaling and distribution system, a product that doesn't decay in the warehouse) that made it the ideal place for Internet commerce to start. There are, it suggests, particular things about books that make them special when it comes to online selling. To the extent that is true, the success of Amazon may not indicate "the future of business". The success of Amazon is real, of course, although its profitability has been erratic. It's an interesting story. But if a book is put on a web page, does that make it a product? Given Anderson's failure in the early chapters to show a really significant shift of purchasing patterns between the offline and online worlds to a new Long Tail world, the story is interesting, but what lessons we learn from it are not so clear.  
  
The final section of the chapter, Long Tails Everywhere [50-51] is, like the Tails Everywhere section of the [Introduction](http://whimsley.typepad.com/whimsley/2007/02/youll_be_very_g.html), a bizarre leap that stretches the idea of the Long Tail to breaking point and beyond. Getting carried away, Anderson writes (without further justification or description) of open source projects as "the Long Tail of programming talent", offshoring as the Long Tail of Labor, microbreweries as the Long Tail of beer, customized clothing as the Long Tail of fashion, online universities as the Long Tail of education, internet porn as the Long Tail of pornography, and al Qaeda as the Long Tail of warfare. Superficially attractive, such examples have no unifying mechanism underlying them and often little justification in terms of actual change. Was the Spanish Civil War any less Long Tail, whatever that means in this context, than 9/11? If offshoring is the Long Tail of labor are suburbs the Long Tail of cities? As for the resurgence of microbreweries, my explanation of that is [here](http://www.google.ca/url?sa=t&ct=res&cd=1&url=http%3A%2F%2Fwhimsley.typepad.com%2Fwhimsley%2F2006%2F01%2Flearning_by_dri.html&ei=HGzaRb27A47SgALUyfWCCQ&usg=__JRwX8wxUV3kO2n3QVitp-gqDk1o=&sig2=tsceZlz8cohnrHiX9PQYYA), and it has nothing to do with the cost of shelf space. Anderson provides no explanation of how microbreweries fit into his ideas, what shelves are longer and why. I know from experience that when you work on a project for a long time it is tempting to see the whole world through the lens of the ideas you are working on, but in this section Anderson needed an editor to haul him back from the edge.  
  
Chapter 2, particularly in its final pages, opens questions about what Anderson really means by The Long Tail. He gives several different definitions throughout the book from narrow to broad, but, getting ahead of ourselves for a minute, perhaps the best summary sentence is that at the beginning of Chapter 4, where he says that the Long Tail is "shifting away from a focus on a relatively small number of hits (mainstream products and markets) at the head of the demand curve, and moving toward a huge number of niches in the tail." One thing about this definition is that it identifies the Long Tail as an economic phenomenon - it's about supply and demand, buying and selling - and as a shift - a change from a previous narrower market to some newer market. Interpreting the Long Tail in a non-economic and static sense as "variety" or "large number of t
hings" (or "The Long Tail is nothing more than infinite choice" [180]) makes it so broad as to lose any useful meaning. Casual soccer games are not part of the Long Tail of Soccer just because there are a lot of them being played in different places; my desk is not a Long Tail of Paper just because it's a mess of many different pieces of paper; and saying that "offshoring taps the Long Tail of labor" [50] adds nothing new or useful to discussions of changes in the patterns of international labour.  
  
By the end of this chapter, Anderson considers that he has shown that the Long Tail is a real phenomenon and has both a history and a future. He's ready to move on to the mechanisms that give it shape in the next chapter. The thing about a book is, if you disagree with the setup (and as I hope I have shown in these postings, there are enough weak points in Anderson's description to make the reality and significance of the Long Tail highly questionable) it's difficult to go on. Discussion of mechanisms assumes a real phenomenon. It will be challenging to write about that without becoming repetitive.


		
