---
author: Tom Slee
categories:
- blog archive
date: 2012-12-08 16:46:21
title: What Cascade Theories Don't Tell Us
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_Attention conservation notice: 3,000 words of amateur rumination on the problems with agent-based theories of uprisings. Part of a series about [identity, institutions, and uprisings](http://papers.ssrn.com/abstract=2116471)._




In the torrent of debate over the causes and dynamics of the "Arab Spring" uprisings, one of the strongest currents has its source in cascade models of uprisings. The starting points for these  models are Mark Granovetter's simple and abstract [Threshold Models of Collective Behaviour](http://www.stanfordlibrary.us/dept/soc/people/mgranovetter/documents/granthreshold.pdf) and Thomas Schelling's similar ideas in "Macromotives and Microbehaviour". If a population of individuals is presented with a choice between A and B, and if each will choose A only if some number of other people (their "threshold") also choose A, then very small differences in the distribution of thresholds can lead to very different results. In some cases, everyone chooses A, in others everyone chooses B, in others, the population is split. One spark sputters; an identical spark starts a prairie fire.




[Timur Kuran](http://link.springer.com/article/10.1007%2FBF00116762) and [Susanne Lohmann](http://journals.cambridge.org/action/displayAbstract;jsessionid=890ED8F2F614B07CF205C5A8D6375D40.journals?fromPage=online&aid=7676388) used these ideas to explain the sudden and surprising uprisings of 1989 in Eastern Europe. Both drew attention to the paucity of information in an authoritarian state, about what others believe and about the nature of the state itself. Highly motivated protesters with a low threshold engage in dissent or protest and thereby reveal information to other disgruntled people about the breadth of disenchantment, or about the nature of the state, or about the experience of other individuals in relation to the state. Others join in and by doing so reveal more. And so it goes. With the right distribution of thresholds, a single person's action can light a fire that sweeps across a continent. Sudden, dramatic uprisings in authoritarian states are a switch from one equilibrium to another as dissent draws back the veil of silence and people see each other, see the nature of the regime under which they live, and realize that everyone else sees it too.







## Digital cascades







A new twist has been added to the cascade mix by the 2009 revolt in Iran and the "Arab Spring" uprisings that erupted in Tunisia two years ago. The highly-publicised role of social media posed new challenges for theories of contentious politics, and three related facets of the events of Spring 2011 made cascade theories appealing:






  * The sudden, unexpected nature of the uprisings and their swift spread from country to country bring to mind the Eastern European regimes in 1989-1990.


  * The lack of a strong, organized opposition during the early stages of the uprisings is a challenge for theories of social movements, and plays to the strengths of cascade models.


  * The prominent role of digital technology, and particularly social media, lends itself to network-based models of society.




Cascade models suggest that contentious politics is an assurance game that can be solved so long as the transaction costs associated with information exchange are low enough. According to a popular narrative, social media networks lower those costs, rendering newly vulnerable those states that rely for their stability on information scarcity and on preference falsification. In an information-rich world, the low-information equilibrium is no longer tenable.




Cascade models have, well, cascaded out from academia and into the mainstream world as the primary way to understand the Arab Spring uprisings. For one influential statement, see [Clay Shirky in Foreign Affairs](http://www.foreignaffairs.com/articles/67038/clay-shirky/the-political-power-of-social-media), but a quick look through a bibliography of Arab Spring literature ([here](http://pomeps.org/category/academic-works/arabuprisings/), [here](https://docs.google.com/document/d/1DU8AOlkTV6F0ZyoGcbk_060iBZG5tWKwj_n97EJPe9M/edit)) will reveal many more. 




As the current gained strength, it absorbed a number of tributaries. One was the Habermasian idea that a rich public sphere or a strong civil society is the fertile ground in which discontent can take root. Another stream focuses on the role of information and the media, bringing communication studies and media studies scholars into the cascade current. The end result is a current that has brought to the fore the role of social media in the Arab Spring, flowing into the sea of mainstream opinion. If you follow the River Nile of commentary about "Twitter Revolution" and "Facebook Revolution" and "Revolution 2.0" upstream far enough you reaach the theoretical source: Granovetter and Schelling, Kuran and Lohmann.




But it's a long way from Granovetter to the Arab Spring, and along the way important things have been lost, and Mistakes Have Been Made.













## Caught in the Net







One of the lovely things about cascade theories is that they lend themselves to simulations. Take that idea of a threshold, for example. Doesn't it make sense that your threshold for action depends more on the actions of people in your social networks than people in some distant city that you've never met? So you can start doing computer simulations of cascades, and how they depend on network structure, and how they depend on the density of connections, and… well, the possibilities are almost endless. So network models have become a common way to extend the original simple ideas in more sophisticated ways. New hypotheses get expressed as network models, and the conclusions feed back into the theory.




But all the simulations in the world don't change the fact that adopting a network model is an input to the theory, not an output, and that the [network society](http://en.wikipedia.org/wiki/Network_society) perspective brings with it a whole set of assumptions and priorities that need examination. For example, adopting a network model means relegating organizations and institutions to the periphery, and moving ideas of "self-organization", connectivity, and peer-to-peer communication to the centre -- not because of any factual conclusion but because some concepts can be expressed naturally within a network model and others can't. Concepts of symbolism, identity, institutions, and the difficulty of establishing trust are hard to express and so get pushed aside or ignored completely. The popularity of agent-based models doesn't disprove the importance of such concepts, it just makes us blind to them.










## Information and symbolism




Just as the cascade point of view has taken on the "network society", so it has highlighted the role of information in authoritarian states, and hence the role of media and technology in fostering change. It's true that information in authoritarian states is limited, almost by definition, but it's a long way from that to the idea that the paucity of common knowledge is what is holding back uprisings. Again, it's easy to express ideas of information flow across networks within agent-based models, but that doesn't actually tell us that information flow in authoritarian societies is the barrier to social change. Yes, there is something of interest in the lens that information provides, but treating it as the only lens of interest is too narrow.




Once you start swimming in the cascade current, you find yourself surrounded by like-minded individuals. It's no surprise that agent-based theories have found fertile ground among those interested in technology. After all, technophiles are typically happy with a focus on the role of information, tend to have a mathematical cast of mind, but are less happy with sociological concepts or social-historical investigations of social movements. Economic concepts and techniques find a welcome home (transaction costs and utility functions) while talk of collective identity is more difficult to translate into agent models. To be blunt, adopting the agent-based outlook saves you a lot of work, because you don't have to read all those historical studies of movements and organizations and make up your mind about the issues they raise.




That there is something of a cultural divide between the agent-based modelers and other currents of the debate, such as those who study social movements, is not new to me of course: here is [Andrew Walder](http://iis-db.stanford.edu/pubs/22750/ars2009.pdf):




<blockquote>

> 
> The field of social movements and contentious politics has been a prolonged effort to establish a sociological alternative to the more parsimonious theories of economics. The increasing insistence on the subjective dimensions of mobilization—collective action frames, the formation of collective identities, the role of emotions—is essentially motivated by a feeling that the initial emphasis on organizations, networks, and political opportunity structures were not sufficiently different from rational social choice models to offer a fully sociological alternative.
> 
> 
</blockquote>




Protests and other acts of dissent share many common features. For one, they are often deeply symbolic acts. Protesters choose symbolic days on which to make their point (the 40th anniversary of the GDR), they focus their actions on national symbols (the storming of the National Palace by the Sandinistas). Presenting protest as information-revelation ignores the symbolic nature of protests, the importance of demonstrating "worthiness, unity, numbers, and commitment", the practice of drawing from a shared repertoire of actions, which other currents of thought have shown to be important. At least, my reading of the literature suggests that there is a lot of verbiage around the basic theory, and sometimes in this verbiage there is reference to the symbolic nature of the protests, but there's little to actually tie the words to the theory. 




If scholars of social movements have demonstrated that identity and its formation are important motivators for political action, and if these factors appear nowhere in the cascade models that seek to explain sudden political change, then there's a gap in the theory.







## Preference falsification, or obedience?







In Timur Kuran's work, the central concept of "preference falsification" is grounded in the distinction between an internal, private viewpoint and an externally expressed opinion. There is, however, a difficulty with ascribing political function to an internal, psychological state of mind. A diagnosis of "preference falsification" is only possible after the fact of an uprising. Before the fact, from a political point of view there is no observable difference between a nation of preference falsifiers and a nation of contented citizens, and to the extent that there is any observable difference between the two, preference falsification loses its explanatory power. Similarly, what is the observable difference before the uprising between Lohmann's East German citizens, who each have bad experiences with their government but are unaware of its overall bad performance, and an East Germany of citizens who have had good experiences with their government?




The concept of preference falsification makes it dangerously easy to read one's own assumptions and views into the lives of others. The danger becomes apparent in Kuran's book-length exploration of preference falsification. He treats affirmative action in American society as a case of preference falsification, in which the "real" feelings of the silent majority were (are?) opposed to affirmative action, but were not voiced because "to voice misgivings is to invite censure. Conscious of the risks, Americans have tended to hide their reservations behind a veneer of public consent" (p 222), a claim that many would consider exaggerated, at least. He is quick to interpret an incorrect poll on the eve of Nicaragua's 1990 election as evidence of oppression by the Sandinistas over the previous decade. And while Kuran spends much time on preference falsification under Soviet Bloc communism, he has nothing to say about 1930s Fascist Europe. What does the concept of preference falsification have to say about lack of successful internal uprisings against the governments of Nazi Germany and Fascist Italy? Were these cases of falsified preferences that did not have a chance to be unfalsified, or did the populace "really believe" in the official ideology? And is the distinction between the two politically meaningful or did Hanna Arendt have it right when she wrote that "politics is not like the nursery; in politics obedience and support are the same".




The Arendt quotation comes from a persuasive essay by Xavier Marquez, "[On the Meaning of Political Support](http://abandonedfootnotes.blogspot.ca/2011/09/on-meaning-of-political-support.html)". Marquez goes on to quote Robert F. Worth of the New York Times writing about the fall of Gaddafi: "Everyone in Tripoli, it seemed, had been with Qaddafi, at least for show; and now everyone was against him." Here is Marquez at length:




<blockquote>

> 
> Were these people deceiving themselves or others? Did the soldiers really support Gaddafi in the past but now do not? Do some of these people support Gaddafi still? The question makes less sense to me than it once did. It is clear that they once obeyed Gaddafi and now do not… but to attempt to determine if, in their heart of hearts, these people supported Gaddafi then (net of all of these forces) and now do not seems slightly absurd. Their obedience and disobedience, support and lack of support are nothing but the vector product of all the forces (threats of coercion, positive incentives, beliefs about Gaddafi, idiosyncratic likes and dislikes, moral convictions, obscure and half-formed ideas about the future, etc.) operating through them. It may make sense to attempt to disentangle these forces if we are interested in legal or moral responsibility, or in the private tragedies of everyday life in Libya, but it does not make sense to me to attempt to figure out if Gaddafi enjoyed some "genuine" level of support (independent of coercion, money, etc.) as a separate explanatory factor.
> 
> 
</blockquote>




It's not that there is nothing to preference falsification, but it has come to occupy a status of orthodoxy, and it has pushed other mechanisms into undeserved obscurity. In Steven Pfaff's excellent "Exit-Voice Dynamics and the Collapse of East Germany", which presents a rich and multifaceted account of the events of 1989, I could not help but see a tension: it seemed to me that he falls back on preference falsification as explanation more often than he would like to (although he does point to other mechanisms) because of the absence of alternative frameworks in which to think.













## Safety in numbers?







Finally, somewhere in the middle of most cascade models there is a "safety in numbers" assumption. Lohmann (on p92 of her major article) writes that the cost of protest "is assumed to be decreasing in the turnout… This assumption can be motivated with the 'safety in numbers' characteristic of the technology of suppression: given the amout of resources a regime devotes to suppressing mass protest, it is plausible that a higher number of activists is associated with a lower likelihood that any one activist will experience injury, death, or imprisonment." Kuran writes "The external payoff to siding with the opposition… is apt to become increasingly favorable… with S (the size of public opposition). The larger S, the smaller the individual dissenter's chances of being persecuted for his identification with the opposition."




This assumption is weak. An action that the government could afford to ignore during a period of political calm cannot be ignored if it gets big enough. Tienanmen Square did not become a safer place the more people gathered, and neither does Tahrir Square: perhaps quite the opposite. Many protests are deliberately risk-seeking, actively looking to provoke a response from the government. As Gandhi said, "The function of a civil resistance is to provoke response and we will continue to provoke until they respond or change the law."




Do people join large protests because it is safer than joining small protests? Or do they join them because, for example, large protests simply matter more? When a country polarizes, the central issues become deeper dividing lines between supporters of the status quo and those in opposition. The question "which side are you on?" becomes one that has to be answered.




## Wrapping Up




What I've tried to say is that there are underexplored weaknesses in the cascade theory description of uprisings which have continuing impacts on current debates, not only in the academic world, but in the wider world - even including the decisions and actions of dissidents in perilous circumstances. The weaknesses lie in the notions of preference falsification, in assumptions about safety in numbers, in assumptions built into the network models constructed on top of cascade models, and in blind spots regarding the forms of political action, the importance of symbols, the roles of institutions, the formation of identity, and other factors that shape the events around sudden uprisings. The effects of these weaknesses are amplified by the enthusiastic adoption of cascade models, supplemented by loose analogies and anecdotes as if they form part of the theory itself, and have a distorting effect on our understanding of these events, making it easy to see some patterns and difficult to see others. Of course, it would be easier to counter the influence of information-driven cascade theories if there were alternative approaches that also reproduced the dramatic "cascade" results. More on that next time.




Org version 7.8.10 with Emacs version 23


		
