---
author: Tom Slee
categories:
- blog archive
date: 2007-01-20 12:19:52
title: 'Collective Action among Small Producers: Indies unite to challenge Big Four
  digital deals | The Register'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

From the Register: [Indies unite to challenge Big Four digital deals | The Register](http://www.theregister.co.uk/2007/01/20/indie_labels_unite/).


<blockquote>The world's biggest record label, albeit a "virtual" one, emerged today at the Midemnet conference in Cannes.

> 
> Indies have found themselves treated as second class citizens or ignored altogether in the era of digital music. The new organization Merlin will act as a global rights licensing agency, and represents the growing influence of the independent sector acting collectively. Members hope that collective action will lead to better deals with online stores such as Apple's iTunes, and music-oriented sites such as MySpace.
> 
> 

> 
> "Merlin came together to license the individually unlicenseable," said Beggars Group chairman Martin Mills. "It's the virtual fifth major."
> 
> 

> 
> No individual Merlin member label claim as much as one per cent of the world's market share, but collectively they add up to 30 per cent of the global music market - and 80 per cent of the world's new releases.
> 
> 

> 
> "We're the largest company in the world if we act together," said Martin Lambot of the PIAS Group, and former president of Impala, the global indie labels' association.
> 
> </blockquote>

  




		
