---
author: Tom Slee
categories:
- blog archive
date: 2012-04-06 15:38:23
title: Click to Judge
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				




I recently contributed an essay to the always-excellent _Literary Review of Canada_, which is out in the April issue and is one of the contributions that they have put online so you can read it in its entirety for free [here](http://reviewcanada.ca/reviews/2012/04/01/click-to-judge/), you lucky people. It's a review of an essay collection called "The Reputation Society", edited by Hassan Massum and Mark Tovey. Unfortunately I didn't like the book much. The concluding paragraph of my review is this:




<blockquote>

> 
> There is a need for inventive and serious thought about the issues of reputation and trust in an increasingly digital world. Our social and commercial interactions will be increasingly mediated by large-scale software systems, and we need ideas about how best to design, navigate and regulate these systems. Unfortunately, by avoiding real-world cases and thorny problems, The Reputation Society provides no answers.
> 
> 
</blockquote>




My starting point for the review, although it's not explicit in the essay, is that information asymmetry is at the heart of anything to do with trust, reputation, and the market; and despite what some optimists claim, sheer volume of opinions does not solve the problem. Recently, I even deleted this paragraph from [the Wikipedia article on Information Asymmetry](http://en.wikipedia.org/wiki/Information_asymmetry):




<blockquote>

> 
> Although information asymmetry has recently been noted to be on the decline with the rise of the internet, which allows ignorant users to acquire hitherto unavailable information such as the costs of competing insurance policies, or the price of used cars, it is still heavily applied to human resource and personnel economics regarding incentive schemes when the employer cannot continually observe worker effort.
> 
> 
</blockquote>




"The costs of competing insurance policies, or the price of used cars" has nothing to do with information asymmetry. The question is, how do you know if I'm telling the truth, when I have an incentive to distort it? How can we establish trust?




Wikipedia itself provides a useful case study. For many topics there is little incentive for a contributor to provide false information beyond the thrill of vandalism, and the fact that such vandalism can be undone with a single click means that trust is not a significant issue throughout many parts of the encyclopedia. Why would anyone lie about the birth date of Henry III of Castile being [4 October 1379](http://en.wikipedia.org/wiki/Henry_III_of_Castile)? As a result, "anyone can edit" applies and the encyclopedia has become the phenomenon it is.




There is a small number of pages ([several thousand](http://en.wikipedia.org/wiki/Wikipedia:Pending_changes) of the 3.3 million in English Wikipedia, or 0.1%) that are the subject of repeated edit wars, and which "are semi-protected to reduce the risk of inappropriate editing". The policies and practices around these pages have undergone continual revision ([Seth Finkelstein](http://sethf.com/infothought/blog/) will know more) and the costs of maintaining neutrality are high; one way or another, when there is a conflict of interest, it needs special treatment.




When it comes to reputation, there's always a conflict of interest. A hotel has an interest in promoting its own image, and in worsening the image of its competitors. Simply throwing open the floodgates doesn't resolve this basic problem, and the paragraphs on TripAdvisor at LRC explain why. (That said, I have no doubt my cousin's place [Riad Africa](http://www.tripadvisor.co.uk/Hotel_Review-g293734-d2341980-Reviews-Riad_Africa-Marrakech_Marrakech_Tensift_El_Haouz_Region.html), in Marrakesh, is indeed a wonderful place to stay).




On the web, as elsewhere, there will be many ways explored to solve the proble of trust. [Angie's List](http://www.angieslist.com/) takes an approach that is almost the opposite of TripAdvisor in its reviews of contractors and services: it requires membership, and all reviews are checked by a human. A result is that, success or not, Angie's List is run much more like non-web reputation services: restaurant review guides, holiday home guides, and so on. If the main benefits of the web are free-for-all Wikipedia-style contributions, then it remains to be seen how reliable it can be for issues like reputation, where conflict of interest and asymmetric information are the sticking points.








		
