---
author: Tom Slee
categories:
- blog archive
date: 2015-09-15 08:16:40
tags:
- airbnb
- uber
title: A few updates
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				I've completed my book manuscript, and it's time to return to blogging. I'm going to change things a bit. Mostly until now I've done fairly long-form essays every now and again, but I'm going to try going more frequent and more links than original stuff (so if you get the emails you may want to click that Unsubscribe button). I don't think there is a place that aggregates Sharing Economy events and commentary, so I'm going to try that for a while.

To start off, here are three interesting pieces. All links open in a new tab.

The indefatigable Ellen Huet [highlights](http://www.forbes.com/sites/ellenhuet/2015/09/11/uber-raises-uberx-commission-to-25-percent-in-five-more-markets/) Uber's continual efforts to raise its take of each ride: it has now raised its commission to 25% in five more cities.


<blockquote>In the last few months, Uber has quietly bumped up commissions from 20% to 25% for new drivers in five cities. New York City drivers who joined as of April will pay 25%, as well as drivers in Toronto, Indianapolis, Boston  and Worcester, Mass., who joined as of August, the company confirmed.

> 
> San Francisco drivers who joined in the last year still pay a 25% commission. An Uber spokeswoman declined to say whether the 30% commission pilot program has spread to more drivers or markets.
> 
> 
Keeping the higher commission to recent drivers doesn’t actually limit its impact very much. Uber’s workforce is constantly churning and growing: In January, an Uber-conducted study showed [a quarter of its active drivers had joined in the last month](http://www.forbes.com/sites/ellenhuet/2015/01/22/uber-study-workforce/). It’s unclear if raising the commission deters new drivers from signing up, but if the policy has spread from its first test city, it suggests it makes economic sense.</blockquote>


The churn among Uber's drivers matches that in Airbnb's hosts: new people try it out, and a lot decide it's not for them. You would think that the more Uber takes from each ride, the weaker its claims that it is not responsible (just a technology company) when things go wrong, but it looks like they are confident they can take more money without taking on more risk.

Ilya Marritz in WNYC news [reports](http://www.wnyc.org/story/when-inspectors-look-illegal-hotels/) on city inspectors chasing down potential illegal rentals:


<blockquote>WNYC has obtained detailed records from a year and a half of inspections. Here’s what we learned by reading through all 2,684 reports.

...from October 2013 through April 2015, the city received 1,616 complaints about illegal hotels. In the same period, inspectors made 2,684 visits looking for rentals that violate local laws</blockquote>


While Airbnb is responsible for most, it surprises me how many reports are from non-Airbnb listings. In particular, Priceline has more than HomeAway.


<blockquote>Airbnb - 101
Booking.com (owned by Priceline)– 40
Portobello Suites – 11
VRBO (owned by HomeAway)– 11
Homeaway.com – 10
Tripadvisor - 5
Agoda (owned by Priceline)– 3
Expedia – 3</blockquote>


I do wish she had given us more of the report details, but there are some gems there, like this one:


<blockquote>“Unidentified Woman Opened Door And After Saying She Did Not Live There Attempted To Slam Door On Identified Police Officer. Woman In Back Screamed To Her Dont Let Them In. Male Came And Id Self As Owner Of Multiple Apts And Said We Should Be Going After Real Criminals Not What They Are Doing.”</blockquote>

		
