---
author: Tom Slee
categories:
- blog archive
date: 2008-10-27 21:54:30
title: 'Cloudy Monopolies II:'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

After yesterday's bout, Tim O'Reilly [responds](http://radar.oreilly.com/2008/10/network-effects-in-data.html) to Nicholas Carr and Nicholas Carr [responds](http://www.roughtype.com/archives/2008/10/further_thought.php)
to Tim O'Reilly's response. There's something about the blog world that
makes referring to these two as Carr and O'Reilly seem terse, and yet
to call them Nick and Tim just looks unctuous. So I'll call them by
their initials: NC (C for Carr and Cloud) and TO (for Tim O'Reilly and
Two point O). 

To bring you up to date:



  * TO claims NC
interpreted "network effects" too narrowly ("Nick only sees first order
network effects") while NC claims TO interpreted "network effects" too
broadly ("today O'Reilly is expanding his definition of 'network
effect' far beyond his original definition").


  * Meanwhile NC claims
that TO interpreted "cloud computing" too narrowly ("O'Reilly is here
using 'cloud computing' in the narrow sense...') while TO claims NC
interpreted "cloud computing" too broadly (well, I can't find a
sentence to back that up, but it's just too symmetrical to leave out).




TO
actually has a point, and I agree with him that NC is overly-narrow.
There are many kinds of indirect network effects that still qualify for the name. For example, here I am
referencing only TO and NC while [others](http://www.cloudave.com/link/network-effects-monopoly-and-cloud-computing) [have](http://broadstuff.com/archives/1328-Increasingly-foggy-conditions-around-Cloud-Computing.html) [also](http://www.mathewingram.com/work/2008/10/26/nick-carr-still-wrong-on-google-part-2/)
contributed to the debate. And I suspect that TO and NC have taken this
issue up because their opponent is an A-list blogger and so a dispute
gives the issue a [prominence](http://www.techmeme.com/081026/p13#a081026p13) it would otherwise not have. So both TO and NC are gaining readers because they already have a lot of existing readers. So the world turns.

But on the big issue, I still side with NC. Here's why.

TO defines the original issue as this claim, written by [Hugh Macleod](http://www.gapingvoid.com/Moveable_Type/archives/004638.html):
"Nobody's saying that one day a single company may possibly emerge to
dominate The Cloud, the way Google came to dominate Search, the way
Microsoft came to dominate Software." But then TO later redefines the
question as whether the cloud infrastructure business is likely to be a
low-margin business based on selling commodities. Given NC's question
"will the infrastructure suppliers also come to dominate the supply of
apps?" the dispute is actually about not one question, but a set of distinct questions:






  1. Is infrastructure cloud computing a low-margin business?


  2. Is infrastructure cloud computing a commodity business?


  3. Is infrastructure cloud computing a natural monopoly?


  4. Do profits lie solely at the top layer of the cloud (applications/APIs)?


  5. Are the synergies among layers of the cloud enough that success in one area translates into success in other areas?




You see, this is why I'm no top blogger. Each of these is a complicated
question, and I'm not qualified to answer any of them. It's not even
clear to me which of these questions are separate. This is why I don't
trust big ideas or catchy names and why I'll never write a best-selling
business book (well, one reason. I'm sure there are many more). But in
pursuit of some light rather than heat I'll try to draw some lines.


Most importantly, the first three of these questions are obviously related, but TO combines them and confusion results. A typical commodity business (selling
widgets that are the same as the next guy's widgets) is low margin
because a commodity business is characterised by decreasing returns and
so by low barriers to entry and intense price competition. But you can
be in the business of selling commodities and yet still profit from
increasing returns. Amazon is a prime example. Books are commodities
(anyone can sell a book), and this limits Amazon's margin per book to
being small. But online bookstores are not commodities - they are
characterised by huge fixed costs (the Amazon computing infrastructure)
and there are massive barriers to entry in the online bookselling
business. So Amazon is a low-margin seller of commodities but is also a
near-monopoly. Wal-Mart is another example in the physical world - it's
obviously in a low margin business (really low) but it has used
economies of scale to build a large market share in the US. Telcos and
utility companies are others where the forces towards a natural
monopoly are strong enough to have attracted antitrust action while
still being low-margin. Few would dispute the fact that Amazon and
Wal-Mart are both immensely powerful companies. The argument that
"infrastructure cloud computing is a commodity business, therefore no single
company will dominate that layer of the cloud" is simply false.


Is infrastructure cloud computing a natural monopoly? There are many
forces (network effects and others) pushing it in that direction, but
there are others (the variety of services demanded in particular) that
pull it away from a natural monopoly. I suspect this market will be
oligopolistic rather than monopolistic - that there will be enough
fragmentation in the kinds of offering available that a demand for
variety will make it more like the automobile industry than like the
online bookstore industry.


Do profits lie solely at the top layer of the cloud? Again, no. You can
be low-margin and high profit as long as the scale is big enough (see
Amazon and Wal-Mart, above). 


And finally, are synergies enough that a single company (Google being
the obvious one) may come to dominate all layers of the cloud? That's a
hell of a question. If there is any company that could do so it would be Google. And
if it does then I hope the antitrust people are all over it. But
sources of variety are surprising - many people thought that the age of
TV would mean local accents would die out, but of course they are still strong in many places - and I am hopeful
that there are enough such sources to prevent the web collapsing into a
Google-shaped black hole.


		
