---
author: Tom Slee
categories:
- blog archive
date: 2008-02-02 22:42:33
title: Long Tail of Books? Actually No.
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Thanks to [Dave](http://howtofurnisharoom.blogspot.com/2008/02/because-being-beaten-by-alice-sebolds.html) for seeing [an article](http://www.theglobeandmail.com/servlet/story/RTGAM.20080202.books02/BNStory/Entertainment/home) I missed in the paper this morning.




Although lots of people talk about how the fragmenting of mass culture is changing, it turns out no one is actually doing anything about it, so we end up with [influential but sloppy books](http://www.longtail.com) based on an anecdote, a hunch, and a whistle.




Now we have the Canadian Heritage-commissioned _Book Retail Sector in Canada_ [report](http://www.pch.gc.ca/progs/ac-ca/progs/padie-bpidp/reports/rapport-report_2007/rapport-pdf-report_e.pdf) about the book market in Canada. Here are some numbers:




  * The overall trend is "more sales for fewer books.”   




  * Number of new titles from Canadian publishers: 12,000 in 1998 to 17,000 in 2004 (40% growth).


  * Total unit sales over the same period: up only 11%.


  * As a result "both the average sales per title in Canada and the average print runs in many title categories have been falling in recent years"


  * Of the 675,000 titles available in in Canada in 2006, 45% did not sell a single copy.  




  * 10,000 titles (2.7%) accounted for 64% of unit sales.


  * 500 titles (less than 0.1%) accounted for 22% of unit sales.  




  * In 2006 Indigo accounted for 44% of domestic book sales; independent bookstores 20%, non-traditional retail (Costco, hardware stores etc) 20% and online booksellers only 4%.


  * Average household expenditure on books: $106.


  * Promotion matters: "a title’s placement and promotion within retail outlets is a highly important selection filter for book shoppers faced with a huge range and volume of available books."


  * Indigo’s Toronto-based buying team buys for all Indigo stores in the country; if an Indigo buyer decides not to carry an individual book, the publisher of that title effectively loses access to roughly half of the Canadian retail channel.



There's a lot more in the report, which is likely to be a benchmark for some time.


		
