---
author: Tom Slee
categories:
- blog archive
date: 2007-03-29 09:36:38
title: Finney passes to Nugent
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

For the first time in my lifetime (just) a PNE player has scored for England. I know it was Andorra, but still.




Now for the premiership.




Link: [BBC SPORT | Football | Internationals | Finney delighted with Nugent goal](http://news.bbc.co.uk/sport2/hi/football/internationals/6506109.stm).


<blockquote>Sir Tom Finney has spoken of his pride at seeing David Nugent become the first Preston North End player to score for England in 49 years.

> 
> "It was only a tap in but nevertheless he scored and that was very important on his debut," Finney told BBC Sport.
> 
> 

> 
> "It gives me a bit of a thrill to see a Preston player wearing an England shirt - the club itself will be very proud."
> 
> 

> 
> Finney was the last Preston player to score for England when he found the net against Northern Ireland in 1958.
> 
> </blockquote>

  




		
