---
author: Tom Slee
categories:
- blog archive
date: 2011-02-14 23:54:32
title: "Egypt's \"Facebook Revolution\": Looking Under the Lamp Post?"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

The "Facebook Revolution" narrative of the Egyptian rebellion is everywhere.




A few examples: Jared Cohen calls digital media an "accelerant" ([>>](http://www.foreignaffairs.com/discussions/interviews/qa-with-steven-a-cook-and-jared-cohen-on-tunisia?page=2)); Don Tapscott ([>>](http://www.theglobeandmail.com/news/opinions/opinion/a-new-kind-of-revolution/article1899638/)) writes that the protests are "Enabled by social media"; Fox News says that Facebook has "Turned Our Entire World Upside Down: Right before our eyes we see Facebook's effects" ([>>](http://www.foxnews.com/opinion/2011/02/04/hackbarth/)); Micah Sifry writes at CNN that "Without the relatively free arena of online social networking sites and tools like Facebook, Twitter and YouTube, young Egyptians like Ghonim could not have built the resilient and creative force that finally toppled Hosni Mubarak." ([>>](http://articles.cnn.com/2011-02-11/opinion/sifry.egypt.technology_1_egypt-internet-access-revolution/2?_s=PM:OPINION))










Most compellingly, here is high profile Egyptian activist Wael Ghonim:




<blockquote>

> 
> I want to meet Mark Zuckerberg one day and thank him… I'm talking on behalf of Egypt. This revolution started online. This revolution started on Facebook. This revolution started in June 2010 when hundreds of thousands of Egyptians started collaborating content. We would post a video on Facebook that would be shared by 60,000 people on their walls within a few hours. I always said that if you want to liberate a society just give them the Internet. If you want to have a free society just give them the Internet." ([>>](http://www.cnn.com/video/#/video/bestoftv/2011/02/11/exp.ghonim.facebook.thanks.cnn?hpt=T1))
> 
> 
</blockquote>




and also: "This is the revolution of the youth of the internet, and now the revolution of all Egyptians."




Narratives matter. We use them to make sense of the world, and we use that understanding to make decisions. Narrative is "the simple order that consists in being able to say: 'When that had happened, then this happened.' We like the illusions of this sequence, its acceptable appearance of causality: it has the look of necessity." (Frank Kermode, "The Sense of an Ending", p127.)




So is the Egyptian rebellion a "Facebook Revolution"? There are reasons to think the narrative is exaggerated…













### The easiest people to talk to







Most obviously, it is much easier to talk to English speaking participants than non-English speakers. English speakers are far more likely to be part of the one-fifth or so of the country that has access to the Internet. ([World Bank Development Indicators](http://www.google.com/publicdata?ds=wb-wdi&met=it_net_user_p2&idim=country:EGY&dl=en&hl=en&q=internet+usage+in+egypt)). And it is easy to contact people over the Internet, so we hear from people who are on the Internet. It is easy to follow Twitter feeds, so we hear Egyptian tweets.













### The easiest story to tell







It isn't just the sources, though. The Facebook Revolution narrative is an interesting story to tell to a contemporary Western audience. For us, a story built around the familiar yet novel world of Facebook and social media is an easy way into the Egyptian rebellion. How many of us know much about the specifics of Egypt's history, its recent past, or the economic sources of discontent? It is a much quicker and lighter story to say "look at the Facebook page." We can even go and look at it ourselves ([>>](http://www.facebook.com/group.php?gid=38588398289)). Talking about strikes is more likely to lose an audience.




So every time prominent activist Wael Ghonim is mentioned, he is described as a "Google executive Wael Ghonim" even though he has explicitly said that "Google has nothing to do with this" ([>>](http://www.cbsnews.com/8301-501465_162-20031608-501465.html)). Do we hear the employer of any of the other leaders? April 6 Movement founders Asmaa Mahfouz, Ahmed Maher and Ahmed Salah are commonly described as "activists". It is possible to track down Maher's occupation as a "civil engineer", but with no employer. The discrepancy is glaring, and so Google gets to be associated with the uprising, adding to the digital tone of the story.













### Underreported players







As people look back for the roots of the rebellion, the _April 6 Movement_ and the _We Are Khaled Said_ Facebook page have received much of the attention. But there are other strands that fed into the protests. The April 6 Movement was created to commemorate an industrial strike, after all, at a textile factory. There have been more than 3,000 separate labour protests in Egypt since 2004 according to a [report](https://docs.google.com/viewer?url=http://www.solidaritycenter.org/files/pubs_egypt_wr.pdf) by the AFL-CIO. The Kefaya movement is considered by some experts to be a central organizer of the January 25 protests, along with Mohamed ElBaradei's organization ([two-minute video with Samer Shehata](http://www.dailymotion.com/video/xguklc_grittv-samer-shehata-muslim-brotherhood-not-lead-in-egypt_news)).













### Self-Organization?







The technological narrative has also been used to describe the rebellion as "leaderless" and "self-organizing" (see a claim for this by Wikinomics' Don Tapscott [here](http://www.theglobeandmail.com/news/opinions/opinion/a-new-kind-of-revolution/article1899638/), and an illuminating analysis of the question by sociologist Zeynep Tufekci [here](http://technosociology.org/?p=366)). Tapscott takes a strong form of the argument: "Just as people can self-organize to contribute to Wikipedia, the computer operating system Linux, or the world’s biggest library of video content, they can participate in social change and coalesce into revolutionary movements as never before."




(Aside: Does anyone else find the language of "self-organization" insulting to the protesters? It slides too easily into [this kind of thing](http://www.hyperorg.com/blogger/2011/02/11/freedom-for-egypt-some-tweets-a-thought-about-a-future-of-journalism-and-a-question/): "much in the same way that slime mould coalesces in a forest and moves towards an emergent common 'goal,' so too do simple-message-connected crowds of people coalesce to move towards a common, emergent goal without the overt direction of an explicit leader." So brave protesters are like slime mould? Really?)




But of course coordination and leadership is not necessarily going to be obvious to Western eyes. As David Kirkpatrick [writes](http://www.nytimes.com/2011/02/10/world/middleeast/10youth.html) in the New York Times: "They are the young professionals, mostly doctors and lawyers, who touched off and then guided the revolt shaking Egypt, members of the Facebook generation who have remained mostly faceless — very deliberately so, given the threat of arrest or abduction by the secret police."




Some organizing was kept off Facebook on purpose, and so received little attention - like these [flyers](http://jdeanicite.typepad.com/i_cite/2011/02/what-is-to-be-done.html) that Jodi Dean points to. As she says, even Lenin - not exactly known as a networky kind of bloke - agreed that "mass movement and 'professional revolutionaries' are not alternative organizational forms. Each is necessary".




Another counterpoint to this "leaderless protest" story is a fascinating Wall-Street Journal article by Charles Levinson and Margaret Croker, who tell a story ([The Secret Rally that Sparked an Uprising](http://online.wsj.com/article/SB10001424052748704132204576135882356532702.html)) about clandestine meetings of small groups of organizers outwitting the efforts of the police to follow what's going on. Of course, getting such a story requires a lot of interviewing and building of confidence.




But there is a kernel…
















So yes, I do think the Facebook Revolution narrative is overstated, and that the Egyptian rebellion marks much less of a break from previous revolts than the language of "Revolution 2.0" suggests. I agree with [this article](http://techcrunch.com/2011/02/11/tools-of-revolution/) in TechCrunch (of all places) that "People, not Things, are the Tools of Revolution". But there is a kernel of truth there, I do admit. Ghosim's quotation at the top of the page is a clear indicator that some young Egyptians feel a sense of identity with Facebook and the Internet: that it is their generation's culture, not their parents and not the authorities. But that's for another time.








		
