---
author: Tom Slee
categories:
- blog archive
date: 2017-06-19 00:42:08
title: 'At the Boston Review: "Silicon Valley to Liberal Arts Majors: We Want You"'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				I have a book review / essay up at the Boston Review. Titled "[Silicon Valley to Liberal Arts Majors: We Want You](http://bostonreview.net/science-nature/tom-slee-silicon-valley-liberal-arts-majors-we-want-you)" it is a review of two books: _The Fuzzy and the Techie: Why the Liberal Arts Will Rule the Digital World  _by Scott Hartley and _What Algorithms Want: Imagination in the Age of Computing_ by Ed Finn.

The beginning:


<blockquote>

> 
> If you are a student of the liberal arts, is there a place for you in our increasingly-digital world? Not really, according to many. Bill Gates thinks your programs should be cut in favor of STEM subjects, his fellow tech-billionaire Vinod Khosla says “little of the material taught in liberal arts programs today is relevant to the future,” and Marc Andreesen says you will end up working in a shoe store. Maybe you should just learn to code.
> 
> 

> 
> Tech billionaires claim that fuzzies—students of the liberal arts and social sciences—are doomed to working in shoe stores, but two new books pin the future of tech on them.
> 
> 

> 
> Or maybe not. Two new books make a case that the technology industry can no longer be driven purely by software engineer hackers, and that you have a critical role to play in guiding it in more ethical and humane directions. That said, their authors differ dramatically about what that role is. Scott Hartley wants you to bring your skills and insights to the world of technology startups, to unlock the full potential of technological innovation. Ed Finn, on the other hand, seeks to hold the technology industry to account: he believes we need “more readers, more critics,” posing questions about who technology serves, and to what ends...
> 
> 
</blockquote>




A few notes:






 	
  * The essay benefited greatly from editing by Deb Chasman and Adam McGee.

 	
  * It has been repeatedly tweeted by the account of the book "The Fuzzy and the Techie". I can't work out if they didn't actually read it, or if they just think any publicity is good publicity, or if I was kinder on the book than I intended to be.

 	
  * "Liberal Arts". Is that purely an American thing now? I sometimes can't tell any more. And sometimes it includes natural scientists, sometimes the meaning seems more narrow. At any rate, I wrote the review not really knowing precisely what it means.

		
