---
author: Tom Slee
categories:
- blog archive
date: 2012-12-15 23:05:45
title: Sixty-Two Things Wrong with "Future Perfect"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				We interrupt the posts on identity and uprisings to bring you this not-so-handy print-off-and-keep companion for readers of Steven Johnson's new book **Future Perfect: The Case for Progress in a Networked Age**. From here on, the author is "SBJ" and the book is "FP". Page numbers are in parentheses.



	
  1. First, and the reason I am writing this: Claiming that the "peer progressive worldview" stands for decentralization and egalitarianism. It will lead instead to an increasingly polarized world, with centralization of information on an unprecedented scale.

	
  2. Starting with a promise that it does not keep. In its opening pages, FP tells the story of air traffic to highlight the unappreciated, steady, incremental progress of living conditions over the course of the 20th century, brought about by a combination of private enterprise and government regulation, rightly highlighting the overlooked role of public sector in improving quality of life. The author criticizes "progressives" for being too "ambivalent about actual progress" (xxxiii), yet soon the boot will be on the other foot, and SBJ will cast aside this optimistic tale of progress. The progressives that so dismay him, of whom I am one, turn out to have a more positive attitude to history than the "peer progressives" that the book celebrates.

	
  3. Having a short attention span. Only a few pages further on, the switch takes place, unremarked. SBJ writes of his peer progressives that "In an age of great disillusionment with current institutions, here was a group that could inspire us, in part because they had attached themselves to a new kind of institution, more network than hierarchy – more like the Internet itself than the older models of Big Capital or Big Government" (xxxvii). The institutions that he was praising just a few short pages ago are now caricatured with Big Capital Letters, labelled as relics of old-style thinking (see also p 51). SBJ now adopts the very disillusionment that so upset him, turns away from incremental progress, and never looks back, taking on the more romantic mantle of the revolutionary. The truth in his introductory pages, that the value of incremental progress will inevitably be overlooked, is ironically confirmed.

	
  4. Dismissing the work of aid workers. As if to rub our noses in his rejection of incrementalism, SBJ tells a story about foreign aid workers Jerry and Monique Sternin, and their work in Vietnam. He praises these protagonists because they "did not descend on those communities with the usual imperious style of many foreign aid groups" (p 21). And in that imperious style, the work of charities around the world is dismissed. There is not a sentence, here or elsewhere, about the dedicated individuals who do not fit his message that everything must be changed. There are no grey areas here, and no need to think twice about this blanket, qualifier-free condemnation. Curmudgeon I may be, unready to adopt the self-proclaimed optimism of the author, but my cynicism seems to me shallow compared to the cavalier attitude of FP. A list of "things wrong" may seem negative, but it at least reflects an engagement with the subject, a consideration of the author's point of view. "Usual imperious style" indeed.

	
  5. Identifying peer networks inconsistently, wherever it suits him, leading to a morass of confusion. Many structures contain different elements, hierarchical, competitive, and collaborative, and SBJ simply highlights the aspect that fits his message. He likes the Sternins' work, so he says they build on the "peer networks of rural Vietnam". Peer progressives, the author tells us, "genuinely like free markets", except when they yield "power concentrated in a handful of economic oligarchs" (p 29), but then again when the economic oligarchs live in Silicon Valley, we will see that things are different again.

	
  6. Making a brief reference to trading towns of the early Renaissance as "adher[ing] to peer-network principles in much of their social organization" (p 27) is far from enough to claim that these towns are "the birthplace of modern capitalism" (28), and to place the whole of modern industry on the network side of the leger. A flimsy statement, unsupported by evidence or argument, and not to be taken seriously.

	
  7. And what a misuse of history throughout! The book treats the rich and diverse history of organizational structures as a source of a few nuggets, chosen to illustrate a pre-defined agenda.

	
  8. Speaking of which: no bibliography, a mere seven pages of notes, and seven pages of index.

	
  9. Only TED, that admirer of bite-size chunks of information, could refer to this short book as a [tome](http://blog.ted.com/2012/09/18/on-our-reading-list-steven-johnsons-book-future-perfect/). It is slim: 250 pages of generously-sized and widely-spaced text.

	
  10. Caricaturing the cultural industry in order to bury it. There are eight pages on the novelty and potential of Kickstarter, the fundraising site for creative activities. The main story is of Jacob Krupnick, a film maker who raised $24,817 on Kickstarter to make a 71-minute dance music video, with almost half of the 600 donations being less than $30. We are told that "Historically, Jacob Krupnick would have been forced to choose among three paths… go mainstream, find a wealthy benefactor, or turn his creative vision into a part-time hobby" (35). I have taken to pausing after every bold, broad-brush assertion like this to think of a story that would tell the opposite message. In this case I think of Glasgow's Bill Forsyth, who in 1980 raised £2,000 for his first film, "That Sinking Feeling" by [posing as a concerned youth worker](http://www.bbc.co.uk/blogs/markkermode/2012/09/that_sinking_feeling_1.html). He sent his begging letter to local bookies, brewers, distillers, and others. A local trade union sent £2, both William Hill and Marks & Spencers sent £25, and a biscuit company sent a few pounds too. Forsyth, of course, went on to make Gregory's Girl and Local Hero.

	
  11. Ignoring the role of money. When I hear someone tell me that it's not about the money I reach for my wallet. "What is ultimately important about Kickstarter is not whether it is a for-profit company or a creature of the gift economy or some interesting hybrid – what is important is the social architecture of the service" (47). Kickstarter's requirement of delivering money to its owners and/or shareholders will shape the direction it takes.

	
  12. Identifying fundraising over the airwaves (by American National Public Radio for example) as a centralized "Legrand Star", while claiming fundraising on Kickstarter is a peer network (39). After all, each project raising funds on Kickstarter is its own "Legrand Star". Meanwhile, the centralized 311 system is portrayed as a network. See 4, above.

	
  13. Giving the Internet too much credit for the Arab Spring uprisings. "To date, the most prominent examples of network architectures influencing real-world change have been the decentralized protest movements that have emerged over the past few years: MoveOn, Arab Spring, the Spanish Revolution, Occupy Wall Street… ." (48 – 49)

	
  14. "Arab Spring" is not and never was a movement (48).

	
  15. The Spanish Revolution? There wasn't one. (48)

	
  16. Claiming that [the] Arab Spring is "something of a distraction" and not "concrete and practical". "The grand spectacles of Occupy or Arab Spring have turned out to be something of a distraction, averting our eyes from the more concrete and practical successes of peer networks." (49)

	
  17. "But every material advance in human history – from the Great Wall to the Hoover Dam to the polio vaccine to the iPad – was ultimately the by-product of information transfer and decision making. This is how progress happens: some problem or unmet need is identified, imaginative new solutions are proposed, and eventually society decides to implement one (or more) of those solutions." Here is the play without Hamlet. What dark tragedies are glossed over in "society decides". This is a bloodless, technocratic view of material progress, reflecting the similarly bloodless path he charts to the future, in which problems are solved, but struggles never fought. (49)

	
  18. Believing in a magic bullet. "When a need arises in society that goes unmet, our first impulse should be to build a peer network to solve that problem". (50)

	
  19. Believing that he is beyond all that old Left/Right stuff. (51)

	
  20. Claiming the peer network "is not some rarefied theory, dreamed up on a commune somewhere, or in a grad school seminar on radical thought" (52). Not only anti-intellectual, he is also dismissive of other alternative cultures.

	
  21. Presenting New York's "311 service", a municipal non-emergency incident-reporting system, as a peer network; it is the centralization of a previously disparate set of services, a Legrand Star of information collection using standard big-enterprise Customer-Relationship Management software from Oracle (55 – 58).

	
  22. Spending several pages telling us how the 311 phone service for problem reporting allowed the government of New York to track the periodic maple syrup smell to a flavour compound manufacturer processing fenugreek seeds. What is the point? The identification of one smell is so non-earth-shattering as to be sleep-inducing.

	
  23. How many times will we be told about the revolutionary potential of reporting the location of potholes using a smartphone app? (57) Has there ever been any evidence that pothole-location-ignorance is a problem to be solved, never mind the limiting factor on local government's ability to keep our streets in good condition? If so, why have none of these accounts produced it?

	
  24. Being blind to the privacy concerns of New York Taxi drivers. He speaks of installing "GPS devices that communicate vast amounts of information back to the Taxi and Limousine Commission" in taxis (65) as if it puts the taxi drivers as peers in a peer network. But it doesn't. It's a centralizing, hierarchical, overseeing move. The fact that SBJ does not see this is an indication of his willingness to see what he wants to see. This is the "peer progressive" world? (63) Count me out.

	
  25. Underestimating the role of actual peer networks. When friends of the authors wanted to renovate their basement, they found out about major roadworks in the area just in time, from neighbours (67). "Yet despite its urgency, the news had arrived on their doorstep via the word-of-mouth network of two neighbours gossiping together". (68) SBJ sees this as a failing of traditional news distribution, calling for a new peer-network structure, but he should see as evidence of the strength of existing networks.

	
  26. Not trusting undesigned systems. Neighbourhood networks do not have a purpose, while the "peer networks" that SBJ promotes are single-purpose problem-solving initiatives (see 16, above). Power in designed networks resides with the network owner; power in informal networks is dispersed. By neglecting neighbourhoods (despite his claim to be writing in the spirit of Jane Jacobs) he is missing the complexity and richness of real-world networks.

	
  27. Misunderstanding the role of news in his "pothole paradox". What he sees as neighbourhood news (76 – 77) does not need a purpose-built institution to deliver it, it needs strong communities. Blaming "traditional journalistic institutions" for having a poor track record of meeting this need is like blaming restaurants for not meeting the need for family breakfasts, mistaking a commercial need for a community need.

	
  28. Focusing on the supply side, ignoring the demand side. Surveying the shape of the media, FP gives a familiar description of the variety and proliferation of online content. "There is going to be more content, not less; more information, more analysis, more precision, a wider range of niches covered." (90) But what voices will be heard, and what opinions amplified? Here, he is silent. He claims that the news system is transitioning "from a small set of hierarchical organizations to a distributed network of smaller and more diverse entities" (79): I hoped to see him take on some of the serious critiques of this claim, notably Matthew Hindman's extensively researched "Myth of Digital Democracy", but there is no mention: all we get are stories of Macworld and online technology blogging.

	
  29. So many stories. Stories should be supplements to argument, not the substance of it.

	
  30. Quoting "The future is here, it's just not evenly distributed yet." It was a clever phrase when William Gibson coined it, but now it is well past its expiry date: it has become a lazy way to brush aside questioning voices. (85)

	
  31. Ignoring inconvenient exceptions in the history of the media. Every weekday throughout my childhood, my parents had **The Guardian** delivered to the door. Owned and run for many years by a non-profit organization (The Scott Trust), it was set up in 1821 by a group of non-conformist Mancunians. For many years after moving to Canada I got the country's largest circulation daily, **The Toronto Star**, owned by a charitable organization (the Atkinson Foundation). And these are only two I know of - I am far from a media expert. But in FP we read that "For more than a century, serious journalism has been financially supported by the massive profits newspapers accumulated, thanks in large part to the near monopoly they had on local advertising." (91) [Most major newspapers, my understanding is, have always run at a bit of a loss, this being the price that their owners pay to have their say in national debates. But I may be wrong.]

	
  32. Treating intrusive, data-mined advertising as a positive, productive system, while foreign aid is a problem to be fixed (see 3, above), and education is too (see below). Now, a checkin at a lecture on Foursquare goes out to friends, "alerts local businesses who can offer your promotions through Foursquare; the link to the talk helps Google build its index of the Web, which then attracts advertisers interested in your location or the topic of journalism itself…. you are helping your friends figure out what to do tonight, you're helping [the host] promote its event; you're helping a nearby bar attract more customers; you're helping Google organize the web… new forms of value are created, and the overall productivity of the system increases." (94) The assumption of a confluence of interests among advertisers and individuals; the idea that we need to increase the "productivity of the system", whatever that means in this context: these are dystopian visions.

	
  33. Claiming that ProPublica licenses its content "so that whoever wants to publish its articles may do so" (94) does not fit with ProPublica's [own statement](http://www.propublica.org/about/) that "Many of our 'deep dive' stories are offered exclusively to a traditional news organization, free of charge, for publication or broadcast. We published more than 110 such stories in 2011 with more than 25 different partners."

	
  34. Having ignored the history of non-profit news publishing (see above, and BBC anyone?) SBJ emphasizes the non-profit nature of ProPublica, drawing attention to the novelty of the model (95). But FP fails to tell us how ProPublica works. [It is funded by the Sandler Foundation, and it is chaired by Herbert Sandler, a savings and loan CEO who sold his bank to Wachovia Bank for $24 billion in 2004. The Sandlers got $2.4 billion and put $1.3 billion into the Sandler Foundation. Not so different from the Atkinson Foundation and the Scott Trust.]

	
  35. Confusing the ability to put a page on the web with reaching a mass market. "Every niche perspective – from the extremes of neo-Nazi hate groups to their polar opposites on the far Left – now has a publishing platform, and a global audience, that far exceeds anything they could have achieved in the age of mass media." (99 – 100). I can think of one or two unsavoury groups in 1930s Europe who seemed to reach a fairly big – one might even say global – audience.

	
  36. In fact, throughout the whole book there is a silly and distorted comparison of "the Internet" (now) with "mass culture" (past), sweeping to one side all the alternative culture that has somehow persisted over the years. It's a stacked deck.

	
  37. Treating academia as it treates history, as a source for cherry-picking stories that support an existing viewpoint. In this case, the work of two academics who questioned the "filter bubble" effect (102). It's the only academic study quoted in the book, so far as I can remember.

	
  38. Quoting David Brooks on anything. (103)

	
  39. Ignoring the history of "leaderless" protest. SBJ writes of the Seattle protests of 1999 that "it's almost impossible to think of another political movement that generated as much public attention without producing a genuine leader" (106), and I think back to my own political coming-of-age: who were the leaders of the anti-apartheid movement, of Rock Against Racism, of the campaign for abortion rights? Who led the North American resistance to the US wars in Central America, or the poll tax protests in the UK? I see no evidence that the protest movements of today are more leaderless than those of 30 years ago. And I am confident that it's only my ignorance which precludes me from giving earlier examples.

	
  40. In 2001, the American state had not "optimized its military to do battle with other states" (110). As early as the 1980s, the focus on "[Low Intensity Warfare](http://www.amazon.com/Low-Intensity-Warfare-Michael-Klare/dp/0394555791)" was well documented, in support of military adventures in Central America, and counterinsurgency in the Pacific. [Also, of course, to fund the "Afghan resistance" to the Russians. That turned out well.]

	
  41. Twitter was not responsible for "spawning pro-democratic flashmobs in the streets of Cairo". (111)

	
  42. It is true that the whole section on the Internet's "capacity for shape-shifting" (118) and its affordances, or lack of them, is inoffensive. But it has no strong message either.

	
  43. The Internet makes communication cheaper, but it wrong to say it "democratizes the control of information". (121)

	
  44. "There is no contesting the tremendous, orders-of-magnitude increase in the numbers of people creating and sharing, thanks to the mass adoption of the Internet". (121) There is some contesting it. The verbs "creating and sharing" cover many counting oddities: tweeting during a TV show counts, but talking to your family during a TV show does not count. There is and has always been a wealth of "creating and sharing" to which books such as FP are completely blind.

	
  45. Prizes and tournaments are generally not peer networks. Prizes are a useful mechanism to tackle some problems, but again he ropes them into his peer network picture by seeing networks where he wants to see them.

	
  46. Caricaturing "old-style" leftists. The political right and left are characterized as "the mirrored alternatives of Big Capitalism and Big Government" (139): so much for the co-operative movement and many other autonomous movements on the political left.

	
  47. When John Harrison won the longitude prize he was not "at the edge of the network". (142) The participants in a prize competition are not a "peer network". Uless by "network" you mean "a lot of people".

	
  48. The sponsors of prizes have sometimes been networks, as in his tale of the Royal Society for the Arts, but often are not.

	
  49. The X Prize Foundation (147) is indeed a peer network. Of billionaires. The resurgence of prizes is not a mark of a new egalitarianism, it is the mark of a new patronage culture born of huge inequality.

	
  50. Being unwilling to reach out beyond his immediate circle of comfortable thinkers creates a filter bubble of his own. For example, on the topic of government corruption, his sole source is Lawrence Lessig (157).

	
  51. Offering fixes to the problems of democracy through vote delegation (proxy votes), but completely missing the fundamental role of the secret ballot. "proxy votes could be bought, of course. A phony public school expert could walk through a neighbourhood handing out twenty-dollar bills to anyone willing to pledge his school superintendent vote to her. But this is true of any democracy." (171) It is simply not true in a democracy with a secret ballot, because no one can verify how an individual's vote was cast, but proxy votes involve an actual visible and trackable transfer of a vote (vote selling), which is completely different. The problem of vote selling, so far as I can tell, is a fatal one for the technocratic schemes in this chapter.

	
  52. Presenting Whole Foods Markets as a model of the new decentralized, flattened organization, while ignoring its anti-union, libertarian roots. Autonomy is OK, just so long as it is our autonomy.

	
  53. Flattened hierarchies (179) do not necessarily translate into more empowered employees or decentralized organizations. Instead, they can do the opposite, and "[broaden the span of control for the CEO](http://www0.gsb.columbia.edu/faculty/mguadalupe/papers/PAPER_FlatteningFirm_Guadalupe_Wulf_Jan2010.pdf)".

	
  54. Taking pains to distinguish "peer progressives" from "libertarians" on the economic right, but not mentioning that the chapter on "Conscious Capitalism" takes its name from an [organization](http://consciouscapitalism.org/) co-founded by John Mackey, CEO of Whole Food Markets and a committed [Randian libertarian](http://en.wikipedia.org/wiki/John_Mackey_(businessman)).

	
  55. Attributing the success of Silicon Valley to "the unique social chemistry of the Bay Area, with its strange cocktail of engineering geeks, world-class universities, and countercultural experimentation. But the organizational structure of most Silicon Valley firms also deserves a great deal of credit" (185). The idea that Silicon Valley firms are more "egalitarian operations" (185) than others is daydreaming.

	
  56. A fundamental rule of any serious thinking is not to take people at their own valuation, but SBJ breaks this rule repeatedly. He takes his description of the culture and goals of Whole Foods, Intel, and Facebook straight from the leaders of the companies.

	
  57. Intel founder Noyce says he "rejected the idea of a social hierarchy" (186), and there may be some truth to that, but to take seriously the idea that other Silicon Valley CEOs have adopted a peer network approach one would have to avoid looking at any list of the world's wealthiest people.

	
  58. Disparaging the education system. My parents were both teachers, and my father did teacher training for many years, so I have absorbed some feeling for the difficulties of making schools effective. But never fear, the peer progressives are here. After a whole page of thinking about the problems of schools SBJ concludes that they would be better if they were run like Whole Foods Markets, because "peer progressives want do do away with the bureaucracies as well as the union mentality. They want schools to be run like EOBs (employee-owned businesses), where teachers are shareholders in an enterprise that grows more valiable as it reaches its goal" (192). And that's it. No notes, no references to other thinkers. It becomes clear what it means to be an optimist, to be a pragmatic peer progressive. Thousands, perhaps millions of people have thought long and hard about education systems and their problems, but it is fine to ignore them all and still be an optimist. Instead, one can wave a few sentences of lazy thought in their direction, confidently asserting that this is the way forward: yet to question this is presumably to be cynical and negative. I'm sorry, but this is not optimism, and it is not pragmatism, it is the juvenile hubris of the know-it-all.

	
  59. Facebook does not "want to strengthen the social ties that allow humans round the planet to connect, organize, converse, and share" (193). It does not "consider the cultivation and proliferation of Baran Webs to be its defining mission". It just says it does. The onus is on the author to show the truth of the statement, and he does not.

	
  60. "The Facebook platform" is not "a continuation of the Web and Internet platforms that lie beneath it" (193). Facebook is the biggest centralized system ever built: a billion people connected to a single of servers, mediated by a single set of policies, making money for a single set of shareholders. One Server Farm to Rule Them All.

	
  61. Faced with the immense wealth of the early Facebook investors, and the personal control that Mark Zuckerberg has, SBJ admits that there is massive cognitive dissonance in the "peer network" idea. But his solution is simply to hope: "top-down control is a habit that will be hard to shake… But the empirical track record of conscious capitalists and employee-owned businesses suggests that we might have been focusing on the wrong elements all along." (195)

	
  62. Believing that struggle is unnecessary. It is not mentioned anywhere in the book.






Date: 2012-12-15 22:49:53

Org version 7.8.10 with Emacs version 23



		
