---
author: Tom Slee
categories:
- blog archive
date: 2011-08-12 16:57:29
title: A Riot to Tweet?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

If there is one thing that could make me look with favour on the idea  of "[banning suspected rioters from social media](http://www.guardian.co.uk/media/2011/aug/11/david-cameron-rioters-social-media)", it's reading Jeff  Jarvis [lecture](http://www.guardian.co.uk/commentisfree/2011/aug/11/social-media-riots) the UK government about free speech, pointing to the  US constitution and continually promoting his new book as he does so.




Jarvis' argument combines slanted rhetorical questions with banal  platitudes. He asks "Who is to say what communication and content  should be banned from whom on what platform?  On my BlackBerry? My  computer?  My telephone? My street corner?" To which Mr. Cameron would  probably say "Me and the police. Weren't you listening?"




And then there are these:






  * When anyone's speech is not free, no one's speech is free. 


  * Censorship is not the path to civility. Only speech is. 


  * Restricting speech cannot be done except in the context of free speech. 


  * A tool used for good can be used for bad. 


  * When debating public identity, one must decide what a public is. 




To which I say: "If you have something to say, just say it."




In short, Jarvis knows nothing about the riots but knows that any  interference with Twitter is a Bad Thing. And we should read his new  book; the issues it tackles are full of, in a word that has gone viral  among the digerati, "nuance".




Jeff Jarvis is backed up by Mathew Ingram, [here](http://gigaom.com/2011/08/08/network-effects-social-medias-role-in-the-london-riots/) and [here](http://gigaom.com/2011/08/11/blaming-the-tools-britain-proposes-a-social-media-ban/). Ingram also  does not know anything about the riots, but is also sure that the  wrong thing to do is to interfere with Twitter because that  "represents nothing less than an attack on the entire concept of  freedom of speech, and that has some frightening consequences for any  democracy." He does, thankfully, avoid telling us to read Jeff  Jarvis's book.




Ingram claims that the mainstream media has covered the use of social  media "hysterically", linking hilariously to _The Sun_ as proof. Listen  Mathew, _The Sun_ could cover a Queen's Park question time hysterically.




While Jarvis stays away from saying anything at all  about the riots, Ingram seems convinced that social media played a  role in the riots because, well, because. He has no specific evidence,  but will that stop our critic of hysterical coverage? It will not.  "While they may not cause revolutions, there's no question that these  kinds of mobile, real-time networks and technologies can help to fuel  them when they occur" he writes, and then quotes Googler Jared Cohen's  claim that "social media tools may not be a trigger for such events,  but they can clearly act as 'an accelerant'". And in case you  wondered, he goes on "It seems totalitarian states like Egypt and  Libya aren't the only ones struggling with the impact of social media  and the desire to muzzle services like Twitter and Facebook."




The message from both comes across loud and clear. The riots are a  secondary story, what really matters is the ability of Twitter and  Facebook to carry on their businesses. It's a silly message.


		
