---
author: Tom Slee
categories:
- blog archive
date: 2007-02-16 10:44:56
title: A School District With Low Taxes and No Schools - New York Times
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Here is a case of free riding in spades, from Jeff Topping in the New York Times.

<blockquote>Just to be clear, Patrick Flynn says he loves public education. He just does not like the idea of paying for it.
> 
> 

> 
> So when it came time last
November for the expanding, unincorporated desert community of Troon to
choose between joining a nearby school district, and paying higher
property taxes to help finance it, or starting its own, Mr. Flynn led
the movement that created the Christopher Verde School District. 
> 
> 

> 
> Not that the Christopher Verde district will have any schools, teachers or, apparently, students. 
> 
> 

> 
> The children of Troon will continue to attend nearby schools. And thanks to a loophole in [ ](http://topics.nytimes.com/top/news/national/usstatesterritoriesandpossessions/arizona/index.html?inline=nyt-geo)Arizona law, the grown-ups of Troon will continue to avoid paying property
taxes in those districts, which makes officials in the districts less
than mirthful.
> 
> 

> 
> “The whole purpose of this was to avoid taxes on their million-dollar homes,” said State Senator Linda Gray, a Republican who has sponsored a bill to prevent the formation of a school district
without schools. (Ms. Gray conceded that there was at least one Flynn
supporter who had “a half-million-dollar home.”)
> 
> 

> 
> <story continues at the link below>
> 
> </blockquote>

Link: [A School District With Low Taxes and No Schools - New York Times](http://www.nytimes.com/2007/02/16/us/16scottsdale.html?ex=1329282000&en=0d764ce8d52599d4&ei=5088&partner=rssnyt&emc=rss).


		
