---
author: Tom Slee
categories:
- blog archive
date: 2015-09-16 09:32:06
tags:
- sharing economy
title: The case of the power drill
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				The case of the power drill was one of the archetypes of the Sharing Economy. Sarah Kessler has [an excellent piece](http://www.fastcompany.com/3050775/the-sharing-economy-is-dead-and-we-killed-it) in FastCompany about what's happened to this original vision: the sharing of under-used possessions, the promotion of access over ownership. It turns out that these efforts have fizzled, which is too bad.

Kessler starts off by looking back:


<blockquote>"How many of you own a power drill?" Rachel Botsman, the author of the book _The Rise Of Collaborative Consumption_, asked the audience at [TedxSydney](http://www.ted.com/talks/rachel_botsman_the_case_for_collaborative_consumption?language=en) in 2010. Predictably, nearly everyone raised his or her hand. "That power drill will be used around 12 to 15 minutes in its entire lifetime," Botsman continued with mock exasperation. "It’s kind of ridiculous, isn’t it? Because what you need is the hole, not the drill."

After pausing for a moment as the audience chuckled, she provided the obvious solution.

"Why don’t you rent the drill? Or rent out your own drill to other people and make some money from it?"</blockquote>


The power drill became one of the touchstones of the sustainability vision of sharing:


<blockquote>Even companies that weren't renting power drills proselytized the theory. "There are 80 million power drills in America that are used an average of 13 minutes," Airbnb CEO Brian Chesky told the [_New York Times_](http://www.nytimes.com/2013/07/21/opinion/sunday/friedman-welcome-to-the-sharing-economy.html) in a 2013 column about the sharing economy. "Does everyone really need their own drill?"</blockquote>


But, Kessler reports:


<blockquote>There was just one problem. As Adam Berk, the founder of Neighborrow, puts it: "Everything made sense except that nobody gives a shit. They go buy [a drill]. Or they just bang a screwdriver through the wall."</blockquote>


Worth reading the whole thing.

In a similar vein, another Sarah (Lacy) [reflected ](https://pando.com/2015/07/28/homejoy-only-uber-is-uber/)(Pando members only, now) on the failure of Homejoy and the difficulties that TaskRabbit and other home service offerings have had, and suggests that "the only Uber of anything is Uber". Delivery companies too may have a hard time reproducing the Uber/Airbnb growth curve (right now I'm staying with my mother in the UK: supermarkets do their own deliveries and it works perfectly fine without any sprinklings of Silicon Valley magic dust). As she writes: the thing with Uber and Airbnb is that every time you want to get a ride or a place to stay, chances are it's a different driver or a different host, so every time you use the service its ability to match you with a service provider is useful. For Homejoy, you really want the same cleaner every time, and for a supermarket delivery there's no reason to have a different person every time either. The platform doesn't add much value once you have found the right person.

Which makes me think a couple of things. First, it's always a good idea to challenge the idea of technological inevitability: sometimes technology-driven solutions work, sometimes they don't.  For all I try to be a perennial doubter, I didn't ask hard enough questions about the utility of the underlying sharing model: I thought there must be something there and I just didn't get it yet.

Second, the Internet is basically a communications medium, and communications is often not the main problem to be solved. Using power drills is not mainly about communications, it turns out it is mainly about convenience:


<blockquote>"For a drill, which by the way now costs $30, and you can get it on Amazon Now and have this thing delivered to you in an hour if you live in New York City—for something worth $30, is it really worth your time to trek potentially 25 minutes to go get something that you spent $15 to use for the day, and then have to trek back?"</blockquote>


In this case, the Internet doesn't solve the convenience problem at all. Community sharing is still a worthwhile goal, but for many aspects of community sharing, the Internet does not add a lot.		
