---
author: Tom Slee
categories:
- blog archive
date: 2006-01-12 13:32:04
title: DVD Dilemma
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

There is an interesting dynamic to the battle over the next-generation of DVDs. In one corner there is Microsoft, Toshiba, Intel and some others supporting the HD-DVD format. In the other is Sony and most of the Hollywood studios, supporting Blu-ray.




It is clearly in the interests of all the companies to agree on one standard. 

<blockquote>"The damage the industry does to itself by not
choosing a format is enormous," said Brad Anderson, vice chairman and
chief executive officer of Best Buy, one of the largest U.S. consumer
electronics and appliances retail chains. "Two incompatible formats is
as much a nightmare as you can make for consumers," he added.
> 
> </blockquote>

And yet they can't. 




<blockquote>"There's no question that a format war is not a
good idea but I don't see what we can do about it except push on and
convince everybody that a revolutionary high-definition disc (Blu-ray)
is better than an evolutionary high-definition disc (HD-DVD)," [a Sony spokesperson] said
during a news conference at the Consumer Electronics Show in Las Vegas.
> 
> </blockquote>

Ted Schadler of Forrester Research says that for whoever wins it is a pyrrhic victory "Eventually they both lose." The two sides are stuck in a prisoner's dilemma, where giving way is the worst outcome, so they may end up with a merely kind-of-bad outcome instead. 




Usually this is the kind of thing that is good for customers, because competition among companies, after all, is a good thing. But in this case it is not so clear that competition is a good thing, because the other side of the story is one of increasing returns. There is a lot to be gained for consumers in having a single standard. We'd rather all keyboards use QWERTY than have a superflous choice of keyboard layouts, and the same goes for DVD formats. Who wants to buy both HD-DVD and Blu-ray to play high-definition movies and next-generation games? In the absence of a clear standard, it is quite possible that consumers will just stay away in droves.




That could be very bad for the DVD-makers because, as Bill Gates said in an interview with the Daily Princetonian
college newspaper last year "this
is the last physical format there will ever be. Everything's going to
be streamed directly or on a hard disk."




So what is good for consumers here? Probably an agree-upon standard and competition of other features based on that standard. In the format area at least, competition is not a good thing, but it is not clear that Microsoft, Sony and the rest can find a way out of their dilemma.




Link: [Fight between Blu-ray, HD-DVD bad for everyone | InfoWorld | News | 2006-01-09 | By Dan Nystedt and Martyn Williams, IDG News Service](http://www.infoworld.com/article/06/01/09/73709_HNblurayhddvdfightbad_1.html).




Link: [Guardian Unlimited Technology | Technology | Two tribes go to war](http://technology.guardian.co.uk/weekly/story/0,16376,1683932,00.html).


		
