---
author: Tom Slee
categories:
- blog archive
date: 2011-06-05 22:11:59
title: 'Housecleaning: blogroll etc'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I've tidied the place up a bit.




The blogroll (does anyone look at these any more?) was really out of date, so I binned it and made a new one. It's mainly blogs where I comment, blogs of people who comment or link here, friends, and family, with a slant towards including less prominent blogs and ones I agree with. It leans heavily towards the subject matter here (though not much technology), and I snobbishly include only blogs I am happy to tell people I read, so no trash TV blogs here. Not that I read any.




I'd like it to be gender balanced, but it's currently 14 male/7 female/ 4 group blogs. I'll see if I can fix that over the next week or two. Any suggestions?




If you should be on the list and are not, let me know - I'm sure it was an accident.




And I added a Favourite Posts list, because even at my rate of posting there's quite a lot here since I started over five years ago and there are a few I'd like to remember.


		
