---
author: Tom Slee
categories:
- blog archive
date: 2006-05-28 18:55:29
title: Great Throbbing Caterpillars
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I was out in the front yard just now, trimming some miniature pine trees we have (to keep them miniature) when, all of a sudden, one of the branches moved. 




Then it moved again.




What had looked like a slightly darker area of the tree was, in fact, a mass of caterpillars. And yes, they were throbbing, rhythmically. 




You want proof? I've got proof. Here. Look at this. I put a video up on You Tube (my first posting there).




[Watch the Caterpillars](http://www.youtube.com/watch?v=zE-p2JE-Oc8)





Each caterpillar is about 2 cm (3/4 in) long. I've no idea what they are or whether I should be killing them. They've been doing the synchronized throbbing thing for about an hour at least now.




Two questions:




Q1 - Will use of the phrase "throbbing caterpillars" lead to a spike in traffic to this site?  
Q2 - Is Great Throbbing Caterpillars a great name for a band. A. Yes.



		
