---
author: Tom Slee
categories:
- blog archive
date: 2012-05-02 15:09:12
title: Is philosophy a joke?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

No, not a continuation of the theme of the previous two posts.




My son, who has been pursuing a degree in philosophy over the last couple of years with steadily mounting frustration, has decided to "drop out", work for a while, and consider where he goes next. He signs off his blog [here](http://screwplato.wordpress.com/2012/03/18/dropped-out-of-university-ending-the-blog/):




<blockquote>

> 
> Although it is unfortunate to quit before I can figure out whether (the vast majority of) philosophers are actually as staggeringly incompetent as they appear to be, or are simply playing an elaborate practical joke, I simply couldn’t stand it either way.
> 
> 
</blockquote>




Yes, he's disenchanted. I'm proud of him and his efforts to find a way to apply reason to important questions about life, and I've been dismayed to watch the discipline of philosophy lose someone as motivated as he has been, [punishing originality rather than encouraging it](http://screwplato.wordpress.com/2011/01/04/originality-in-philosophy-courses-is-punished-instead-of-encouraged/), [pandering to intuition](http://screwplato.wordpress.com/2011/02/19/intuition-pandering-vs-actual-moral-philosophy/), and [giving up on reason](http://screwplato.wordpress.com/2010/12/29/are-philosophers-giving-up-on-reason/) while spending its time on issues such as [whether proper names are rigid designators](http://screwplato.wordpress.com/2011/05/18/what%E2%80%99s-the-point-of-naming-and-necessity/).




I'm no philosopher, but while I look forward to seeing what my son does next, I have no inclination whatsoever to read _Naming and Necessity_.


		
