---
author: Tom Slee
categories:
- blog archive
date: 2007-02-06 00:08:29
title: Tit fot Tat
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

First, my thanks to Mark Thoma, John Quiggin, and Brad DeLong for responding to my request to mark the passing of Anatol Rapoport. It's odd whose death gets noticed and whose doesn't: Jane Jacobs' passing was remarked far and wide (and rightly so) but Rapoport, who I think was as important a thinker in a different way, seemed to get less attention. Their posts helped to right that a little in the social science blogosphere.




Comments on Brad DeLong's posting pulled him into a sequence of posts about Tit for Tat and other repeated prisoner's dilemma strategies, in [A Note on a GRIM Game of Repeated Prisoner's Dilemma...](http://delong.typepad.com/sdj/2007/02/a_note_on_a_gri.html)., and [More on Tit for Tat](http://delong.typepad.com/sdj/2007/02/more_on_titfort.html). For what it's worth, I'm just going to put my two cents in here.




First, I do agree with one commenter (David Cameron) that the submission of Tit for Tat, although widely known because of Axelrod's writing about the tournaments, was certainly not the most substantial of Rapoport's contributions. Still, it has a certain _je ne sais quoi_ that obviously catches the attention, as all the discussion at BDL's site makes clear.




The fact that Rapoport submitted (twice) and won with Tit for Tat was a reflection of what he had learned pragmatically in his experiments in playing repeated prisoner's dilemma (on a petty side note, I can't bring myself to use Axelrod's term "iterated prisoner's dilemma" which seems slightly pretentious and also inaccurate). The observation that T4T is not a subgame-perfect equilibrium for the game is beside the point in some ways - the tournament was just that, and the strategy won.




But of course there is more to it than the tournaments, because of the pedagogical use Axelrod made of them and of Tit for Tat as a way of looking at many disparate problems. There seem to be two arguments against Axelrod's book. 




The first is that strategies similar to T4T but slightly different can be discovered that do better under a wider class of situations. This does not seem too important. The repeated Prisoner's Dilemma is, after all, never an exact match to any real world situation (and the real world is surely what we are interested in), so a theoretically more rigorous (or, in this case, computationally better) solution for the game is not guaranteed to perform better in the real world - where what constitutes a "move" is never precisely clear, and the game is never as self-contained as the idealized game that game theory studies. Axelrod accepts this, and so goes happily into all kinds of areas which are sometimes little more than reminiscent of his tournament. Even in the modelling work he discusses there are many variants - spatial games where neighbours are fixed, for example. So the key insights here are that (a) reciprocity as an approach can be successful in a wide variety of situations, (b) T4T catches the essence of reciprocity in a compact form, and (c) the success of reciprocity is surprising. So I'm with Axelrod on this.




The second critique is that strategies completely unlike T4T may do better, and in particular a strategy such as "GRIM", which defects for ever on first losing. One of the comments points out that Grim is a subgame perfect equilibrium for the infinitely repeated PD. The idea of a "successful strategy" in an infinitely repeated game is fickle (it depends, for example, on the other strategies allowed, of which there are infinitely many) and it is not clear to me that subgame perfect equilibrium is the best criterion, but this is nevertheless a valuable reminder that reciprocity is not always the outcome of repeated interactions - sometimes the outcome is much less happy. And that's OK. It is probably true that Axelrod overstates the case in his enthusiasm for T4T, but T4T does show that a grim outcome is far from inevitable, which in the real world is plenty to be going on with.




How rigorous we need to be in treatments of formal, idealized problems to learn practical lessons for messy real world situations is itself a messy real-world problem, and those mathematically inclined who argue that a fully rigorous treatment of a problem is the only basis for such lessons are wrong. So I give Axelrod a lot of credit here. His book, after all, prompted many many fruitful questions - and that is, perhaps more than precise answers, the mark of important ideas.


		
