---
author: Tom Slee
categories:
- blog archive
date: 2005-11-26 20:24:19
title: USB Christmas
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

The number amd variety of things you can plug into the USB port on a computer is getting ridiculous. A [search](http://www.engadget.com/search/?q=usb+power&submit=Go) for "USB Power" on the wonderful Engadget gives a stupendous list of improbable items, including:




****





1. [USB powered gloves](http://www.engadget.com/entry/1234000590065822/)
  
_Posted by Thomas Ricker on 10/31/2005_
  
Anything,
and we mean anything that can be made... can be made better with a
little USB power. Add a bit of camouflage and you'll understand why
we're lovin' on these new craptastic USB heated gloves




2. [USB-powered Verilux Natural Spectrum Book and Travel Light](http://www.engadget.com/entry/1234000033063784/)
  
_Posted by Evan Blass on 10/17/2005_
  
Oftentimes
when we are in and around our local library sucking down free WiFi, we
notice several people (not the ones sleeping in the over-stuffed
chairs, mind you) peering into strange stacks of




3. [USB-powered Deco Lights](http://www.engadget.com/entry/1234000943060160/)
  
_Posted by Ryan Block on 9/24/2005_
  
When
Alek's online Christmas decorations control system turned out to be a
hoax, a light must've gone off in someone's head. Yup, you guessed what
comes next in the long line of illustrious




4. [Logitech intros V20 USB-powered laptop speakers](http://www.engadget.com/entry/1234000480056448/)
  
_Posted by Donald Melanson on 8/29/2005_
  
Logitech
just introduced a new pair of speakers designed for use with laptops.
We can't tell you anything about the most important part -- how they
sound -- but we do know that the V20s will set you




5. [Thanko’s USB-powered iShaver](http://www.engadget.com/entry/1234000473054105/)
  
_Posted by Ryan Block on 8/11/2005_
  
Is
it powered by electricity? Because if it is, we want to see it powered
by USB. And if it isn't... we want to see it powered by USB. So thanks,
Thanko, for your latest, the iShaver. Probably works




6. [Boynq USB-powered light](http://www.engadget.com/entry/1234000770045548/)
  
_Posted by Thomas Ricker on 6/4/2005_
  
Doubtful
anyone who needs (or more importantly, is willing to use) the Boynq
D-Light USB-powered Lamp is going to look good embalmed in a pasty
orange glow. But here you have it, another whacky




7. [USB-powered lava lamp](http://www.engadget.com/entry/1234000637044382/)
  
_Posted by Peter Rojas on 5/24/2005_
  
We're
pretty sure that the sheer geekiness of plugging this into a USB port
kills whatever swinging bachelor pad/hippie love nest vibe you might be
trying to create, but Lava World International is




8. [eMagin USB powered OLED 3D visor](http://www.engadget.com/entry/1234000270036305/)
  
_Posted by Barb Dybwad on 3/16/2005_
  
The
promise of the near view display is there, though prior implementations
have been poor. A head-mounted screen should theoretically provide the
equivalent to a very large disply viewed from a few




9. [The USB-powered thermal wrist protector](http://www.engadget.com/entry/1234000720032816/)
  
_Posted by Ryan Block on 2/22/2005_
  
A
USB-powered thermal wrist protector/strap on Engadget that facilitates
one's ceaceless habit of sitting in front of the computer, researching,
purchasing, and using USB-powered gadgets via




10. [The USB-powered blue-glo Mac mini Skirt](http://www.engadget.com/entry/1234000170031894/)
  
_Posted by Peter Rojas on 2/16/2005_
  
Ok,
so at the end of the day it's still just an acrylic pedestal for the
Mac mini, but Plasticsmith must know how to get on our good side,
because now they've busted out a USB-powered version of




11. [The USB-powered piezo negative ionizer](http://www.engadget.com/entry/1234000423030935/)
  
_Posted by Ryan Block on 2/9/2005_
  
They
call it aeroionotherapy--some believe in it, some don't--and it's
supposed to relieve you of restlessness, anxiousness, depression, and
high blood pressure if you charge the air in a room with




12. [The USB-powered desktop fan/clock radio](http://www.engadget.com/entry/1234000897029209/)
  
_Posted by Peter Rojas on 1/27/2005_
  
By
this point it seems like pretty much everything that can be turned into
a USB-powered gadget has been (not to mention a few things that
probably should never have been led down that path), so




13. [USB-powered fake flowerpot speaker](http://www.engadget.com/entry/1234000887021843/)
  
_Posted by Peter Rojas on 11/29/2004_
  
You
know, it's hard enough already trying to convince people who drop by
the house that we're not insane, so the last thing we're going to do is
completely confirm that by plugging this USB-powered




14. [USB-powered air humdifier](http://www.engadget.com/entry/1234000340021613/)
  
_Posted by Peter Rojas on 11/26/2004_
  
You'd
probably want to keep lots of moisture away from your PC, so that you
won't, you know, destroy it, but if you can't quite resist, a shop in
Japan is selling a USB-powered air humidifier. Would




15. [The USB-powered Santa](http://www.engadget.com/entry/1498518862884828/)
  
_Posted by Peter Rojas on 11/17/2004_
  
Be
honest, do you really need to put up any other Christmas decorations
besides this USB-powered, drum playin' Santa Claus which regales you
with Jingle Bells, Joy to the World, The First Noel, and




16. [USB-powered Christmas Tree and snow man](http://www.engadget.com/entry/8930472159314672/)
  
_Posted by Peter Rojas on 10/25/2004_
  
It really wouldn't be an Engadget Christmas without this USB-powered snow man or Christmas Tree on your desk, would it?




17. [The USB Power Pack](http://www.engadget.com/entry/1488507740662585/)
  
_Posted by Peter Rojas on 9/30/2004_
  
You
know us. We can't resist anything USB-powered. We're totally suckers
for it, which is why we we're giddy at the prospect of this portable
battery pack which we picked up at Compact-Impact that




18. [Mini Power Minder, a new kind of USB power](http://www.engadget.com/entry/7943838951650352/)
  
_Posted by Ryan Block on 9/15/2004_
  
We
can't think of too many examples of times when we need to shut down a
bunch of stuff at the same time as our computers since most anything
connected to them needs recharging anyway (excepting




19. [USB-powered gadgets!](http://www.engadget.com/entry/0524298117686276/)
  
_Posted by Peter Rojas on 6/10/2004_
  
The New York Times has just uncovered this crazy new trend: USB-powered gadgets! Anyone else heard of this before?




20. [The Cleanlon USB-powered air purifier](http://www.engadget.com/entry/1376273305105716/)
  
_Posted by Peter Rojas on 6/4/2004_
  
Somehow
we missed this from the other day, but the New York Times actually
reviewed one of those USB-powered air purifiers. The only thing about
reviewing the Cleanlon is that they couldn't tell if




21. [USB powered frangrance diffuser](http://www.engadget.com/entry/9389631206441507/)
  
_Posted by Peter Rojas on 5/10/2004_
  
What's
scary is that this isn't even the first one of these: it's a USB
powered fragrance-oil diffuser (basically a fancy Glade Plug-In) from
Osmooze called the USB P@d that actually let's you




22. [USB-powered fragrance-oil burner](http://www.engadget.com/entry/2487485527337141/)
  
_Posted by Peter Rojas on 3/6/2004_
  
The
fact that it's sold out implies that somebody has been buying this, but
we've been scratching our heads at the prospect of Arvel's USB-powered
fragrance-oil burner, which is supposed to help make




23. [Socket Mobile Power Pack](http://www.engadget.com/entry/1234000247022278/)
  
_Posted by Dan Wu on 12/3/2004_
  
Socket's
Mobile Power Pack has 7200mAh of juice in its battery, allowing you to
charge cellphones, Pocket PCs, Palm devices, Nintendo GBA/DS, and
digital cameras, but the best part is that it has a




24. [The Buffalo BSKP-CU201/BK Skype conference phone](http://www.engadget.com/entry/1234000807069612/)
  
_Posted by Thomas Ricker on 11/25/2005_
  
Those
Skype handsets are coming fast and furious these days. Now Buffalo
brings us the ingeniously named BSKP-CU201/BK handsfree USB kit which
features an integrated speaker and omnidirectional mic




25. [Azio Dual-Link Charger does USB, car lighter](http://www.engadget.com/entry/1234000197062537/)
  
_Posted by Marc Perton on 10/11/2005_
  
We've
seen a handful of hydra-headed chargers, which let you juice up your
cellphone via USB, car cigarette lighter or other power sources, and we
suspect that Azio's Dual-Link Charger isn't that




... and that's just the first 25 of the 156 in the list. A flashing pencil sharpener, an aquarium, a humidifer, a battery charger, noise-cancelling headphones. The world of gadgets is getting weirder and wonderfuller.


		
