---
author: Tom Slee
categories:
- blog archive
date: 2012-01-02 15:03:35
title: '2012 Predictions: Turning Points for the Web'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				




## Table of Contents









  * Avoiding Cynicism (As If)


  * Facebook: Privacy Hits the Mainstream 


  * Amazon: Abusing Community 


  * Apple: Stepping in Front of Google 













## Avoiding Cynicism (As If)













Peering into the New Year, my better half Lynne reflected yesterday that it is a duty of each of us, as we grow older, to be vigilant against encroaching cynicism. She's right (of course!), and I do feel that strong and steady current tugging me sluggishly downstream towards the lazy, easy waters of geezerhood, to a place where everything new shows itself only by its flaws and in which every new glass is basically empty.




Luckily, 2012 looks like being a banner year for those of us who take a critical view of the hype and commercialization around digital technology, so I'm actually feeling quite cheery. The number of digital hecklers is growing1, and will continue to do so as the relations between the mainstream Internet and its audience/members sours. A growing wave of disenchantment is gathering enough steam [sic] to become a creative force in its own right, and I think that's going to be fascinating to watch, as well as potentially a period of renewal for alternative culture.




So Happy New Year, and here are a few predictions for 2012. I don't think the full impact of any will be over and done during the calendar year, but I do think we'll look back at 2012 as a turning point in attitudes to digital technologies.













## Facebook: Privacy Hits the Mainstream




Prediction
    High-profile privacy cases in 2012 will dramatically                 accelerate the level of public distrust in Facebook,                 which will spill over to other Internet aggregators. 



Privacy has always been the other side of the openness coin. Everyone loves openness, of course, but the last year or two has made it clear that behind Mark Zuckerberg's Facebook profile ([*](https://www.facebook.com/zuck?sk=info)) claim that "I'm trying to make the world a more open place" there is a hard, cold, commercial reality. Are we sharing among each other, or are we feeding Facebook? And where is the boundary between the two?




Here's a dilemma my son faces, which also confronts many other young people. After university one potential employer is the Canadian government. If he clicks his support on Facebook for political protests, will government background checks have access to this information and will it count against him? There's no point asking Facebook even if you did trust it, because today's terms and conditions may change, and the laws governing it may change too. From being an open space where it is easy to express our political views, Facebook is becoming a panopticon where we censor ourselves, not knowing who is watching.




It's not clear that the advertising driven model of web technology is sustainable given its dependence on data that we are increasingly reluctant to give up. As ex-Facebook engineer Jeff Hammerbacher says, "The best minds of my generation are thinking about how to make people click ads," he says. "That sucks." We've lived with this downside until now but as the choices become more stark this may change, and when things change on the Internet, they can change very quickly. danah boyd's view that "Facebook is a utility; utilities get regulated" ([*](http://www.zephoria.org/thoughts/archives/2010/05/15/facebook-is-a-utility-utilities-get-regulated.html)) will become mainstream. We'll see demands2 for changes to Facebook's practices (see the Europe vs Facebook group ([*](http://europe-v-facebook.org/EN/en.html)), and the Irish data protection commissioner's report [here](http://www.guardian.co.uk/technology/2011/dec/21/facebook-advertising-data)) gaining momentum.













## Amazon: Abusing Community




Prediction
    Change in the open source world as                 Google takes on Amazon. 



Amazon is rapidly making a name for itself as the company to give the Internet a bad name. From brutal working conditions ([*](http://www.mcall.com/news/local/mc-allentown-amazon-complaints-20110917,0,7937001,full.story)) to treating physical bookstores as showrooms ([*](http://www.nytimes.com/2011/12/13/opinion/amazons-jungle-logic.html)) to union-bashing ([*](http://www.theatlantic.com/technology/archive/2011/12/in-the-wake-of-protest-one-womans-attempt-to-unionize-amazon/249853/)) to McCarthyist policies around Wikileaks ([*](http://en.wikipedia.org/wiki/Amazon.com_controversies#WikiLeaks_hosting)) to tax opposition ([*](http://www.huffingtonpost.com/2011/08/15/amazon-boycott-taxes-_n_927667.html)) to screwing libraries ([*](http://librarianinblack.net/librarianinblack/2011/10/wegotscrewed.html)), this company has done everything it can to demolish the image of the Internet as a source of cooperation, collaboration, and open friendship. It has perfected the act of free-riding on open source efforts, building its (remarkable, it must be said) profitable EC2 infrastructure on Xen Hypervisor, using Linux extensively, and not contributing back ([*](http://www.h-online.com/open/features/Time-for-Amazon-to-pay-its-dues-to-open-source-1249811.html)), in the same way it happily takes all those volunteer hours put into Wikipedia and uses them to sell its own devices, messing with authors' rights as it does so ([*](http://www.roughtype.com/archives/2011/09/beyond_words_th.php)).




The Kindle Fire is the icing on the cake: Amazon has taken the Android operating system and its Linux kernel and used it to power the Amazon tablet. In doing so, it has taken Google's language of openness around Android (always suspect) and thrown it right back in Google's face, removing the Google applications and most evidence that the device is running Android, and making it an Amazon device from end to end.




With the Kindle Fire looking likely to become the top selling Android tablet, you have to wonder how long Google will welcome this state of affairs. There's a lot of talk about the rivalry between Google and Apple, but the tension between Google and Amazon is the conflict that may change the open source world. The licensing terms for open source software have been increasingly friendly to commercial exploitation of community projects, moving steadily away from the more restrictive GPL ([*](http://blogs.the451group.com/opensource/2011/12/15/on-the-continuing-decline-of-the-gpl/)), and Amazon's nose-thumbing may be the step that forces a re-evaluation of this enterprise-friendly stance.













## Apple: Stepping in Front of Google




Prediction
    As the open web fragments, Google will look to its bottom line. 



Speaking of Google, Apple's voice control system Siri may be the biggest threat the friendly ad-broker has yet faced, and you could argure that Siri is the major threat to the openness of the web.




It's increasingly obvious that the web has several natural bottlenecks, and that these bottlenecks are simultaneously the places where money can be made and chokepoints where political pressure can be applied. Ever since broadband and mobile access replaced ye olde dialup and Internet access became dominated by telcos and cable companies, ISPs have been one set of bottlenecks. Mobile device makers are another. The DNS system itself is yet another, which SOPA is looking to squeeze. Finally, there is aggregation, Silicon Valley's preferred source of influence.




Aggregation creates a single point of entry into a part of the web, whether it's aggregating consumer items (Amazon), digital products (Apple), people (Facebook), or the web itself (Google), and aggregation is driven by increasing returns to scale. The point of aggregators is to stand between us and what we want to reach, guiding us to those parts of it that seem best.




The thing about Siri is that it stands in front of Google, potentially displacing the search box as iPhone users' point of entry to the web. Just as removal from Google's search engine makes you vanish from the web, so Siri has the potential to make Google vanish. Well, not vanish in the short term, but fade at least. Apple negotiates deals with providers like Yelp and Wolfram Alpha, doing an end run around the PageRank algorithm.




If Siri and other voice-recognition "assistants" move towards the mainstream, we can expect to experience an increasingly curated/censored version of the web ([*](http://crookedtimber.org/2011/11/30/10-things-the-iphone-siri-will-help-you-get-instead-of-an-abortion/)). The relationship between Apple and the anti-establishment has always been love-hate, and Siri may drive it into hate-hate.




Google's friendly image can last only so long as its growth rate and profit margins stay healthy. It's already lost the aura of being the place to be for programmers, soon we'll soon see enough competition to force Google into a more orthodox stance, and that will shock a lot of observers.







## Footnotes:







1 A few years ago Andrew Keen's silly "Cult of the Amateur" was   the most prominent digital criticism book. Now we have Zittrain   ("The Future of the Internet and How to Stop It"), Carr ("The   Shallows"), Turkle ("Alone Together"), Wu ("The Master Switch"),   Lanier ("You Are Not a Gadget") and many more.




2 "Demands" is not the best word, as Chris Dillow points out ([*](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2012/01/demands.html))














		
