---
author: Tom Slee
categories:
- blog archive
date: 2007-02-17 19:32:34
title: The Long Tail 0 - Cards on the Table
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

My next several postings are going to be a critical reader's companion for The Long Tail by Chris Anderson. And if you're going to read these postings, there are some things you should know - and that's what this introductory post is for, to make sure all my cards are on the table.  
  
The posts talk about _The Long Tail_, but they are really about two books. Both were published in summer 2006 and both were about the changing face of individual choice in today's economy and culture. If it wasn't for The Long Tail's index being two pages shorter, both would be exactly 240 pages long. Both authors have a training in science, but neither are professional economists or cultural studies professionals. In fact, both work in the computer industry, one as an editor of Wired Magazine, and one for a computer software company. At the time of writing, The Long Tail is at number 310 in the Amazon best seller list. The other book currently stands at 806,127.  
  
Obviously that second author is me. My book is "No One Makes You Shop At Wal-Mart: the surprising deceptions of individual choice" and it was published by Between The Lines of Toronto, a small publisher whose staff love books and love to publish provocative, left-wing titles with an academic slant. The Long Tail is published by Hyperion, of New York. As for the subject and the authors' take on it, mine is encapsulated in that phrase "the surprising deceptions of individual choice" and Anderson's in a chapter title "The Paradise of Choice". Couldn't be more opposite.  
  
So there's a danger here, because I have a chip on my shoulder. The Long Tail and No One Makes You... cover overlapping territory, and have almost diametrically opposite views. I think that Anderson is basically wrong. Not completely wrong, but basically wrong. What's more, and what's more important, I think his book is fundamentally sloppy and misleading despite the fact that there are a few good insights - and he does have a great title. But you, dear reader, knowing that I have the aforementioned chip on my shoulder, might naturally and understandably think this is sour grapes - the envious grumblings of a bit player when a more talented writer has seized the agenda and won the argument.  
  
And maybe it is. I'd like to say not, but who am I to say? Any honest person knows that we are not the best judge of our own motivations. I'm sure as hell not the best judge of mine, and that's why I wanted to get this off my chest before starting. If you see bias in what I say, you know where it comes from.  
  
But even with that danger of misdirected envy, there are still things I want to say, so all I can do is put down what I think and you can judge it on its merits. One option would be to take a five paragraph run at the book, but its success and its influence have been so significant that it needs more. I'm going to take a chapter-by-chapter run at the thing (with a couple of extra posts as well).  
  
Just a few more preparatory statements before we can start.  
  
First, this is a reading of the book, which is a bit different from the idea behind the book. There are only a few cases where I have gone beyond what is in the book to cite discussion and research that has happened since its publication (or before). A book should stand reasonably well on its own, or point to places for more reading if it leaves discussions open-ended.  
  
Second, there are some things that are important to me in non-fiction books. Consistency is important. So is clarity. And so is logic. If they don't matter to you - if rhetoric or eloquent phrasing or memorable stories matter more, then you and I are going to have different opinions.  
  
Third, I reference page numbers in the book in square brackets, like [23] this.   
  
I think that's all. The next post takes a look at the cover (this project may take a while to complete).  
  
  



		
