---
author: Tom Slee
categories:
- blog archive
date: 2013-11-01 21:24:00
title: This Week in the Sharing Economy
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				


	
  * Airbnb:

	
    * Airbnb [released](http://blog.airbnb.com/airbnbs-economic-impact-nyc-community/) a study they commissioned, entitled _The Airbnb Community’s Economic Impact on New York City_. Carried out by [HR&A Advisors](http://www.hraadvisors.com), the study claimed that “Airbnb generated $632 million in economic activity in New York in one year”. The study was written up, together with the conclusions, in [Business Week](http://www.businessweek.com/articles/2013-10-22/airbnb-says-it-has-a-huge-impact-on-nycs-economy-except-when-it-doesnt), [The Wall Street Journal](http://online.wsj.com/news/articles/SB10001424052702303448104579149844259343658), [The New York Post](http://nypost.com/2013/10/23/airbnb-claims-site-helps-ny/), as well as [TechCrunch](http://techcrunch.com/2013/10/22/airbnb-nyc-632-m/), [AllThingsD](http://allthingsd.com/20131022/in-new-york-fight-airbnb-says-it-has-proof-that-hosts-rent-out-their-own-homes/), and [many more](https://www.google.ca/search?q%3Dairbnb%2Bnew%2Byork%2Bstudy&oq%3Dairbnb%2Bnew%2Byork%2Bstudy).

	
    * But wait! It turns out the study is all of 300 words with no indication where the data comes from, what “economic impact” means or how it was calculated, what it means that Airbnb “supported 950 jobs in the outer boroughs”, where the tourist spending figures came from, or anything else. Truly strange.

	
    * Meanwhile, some developers are [notifying](http://valleywag.gawker.com/major-new-york-city-developer-bans-airbnb-for-its-nega-1453473087) their tenants that they should not sublet their rooms through Airbnb and other sites, as

	
    * Peter Thiel’s _Founders Fund_ [has invested](http://techcrunch.com/2013/10/28/airbnb-200m) $200 million in the company.

	
    * I can sympathise with people like [Kimberly Kaye](http://www.nydailynews.com/opinion/rent-home-airbnb-article-1.1490082) who find Airbnb helpful,

	
    * but despite these cases, it looks like [buying an apartment specifically to rent out](http://needwant.com/p/buying-apartment-airbnb/) is becoming increasingly common (see the interesting discussion at [Hacker News](https://news.ycombinator.com/item?id%3D6655492), where it is the top post).

	
    * and leading, unsurprisingly, to the rise of [management firms](http://beyondstays.com/),

	
    * and concerns like [these](http://www.sfbg.com/2013/08/06/thin-air) from the San Francisco Bay Guardian persuade me that Airbnb is not a bonus for a city,

	
    * as does [this thoughtful essay](http://www.rooflines.org/3498/airbnb_way_to_make_ends_meet_or_destroyer_of_affordable_housing/) by Miriam Axel-Lute at rooflines.

	
    * If you are pretty enough, you can always go [to LoveRoom instead](http://mashable.com/2013/10/29/loveroom-airbnb-no-ugly-people/).




	
  * More on the Sharing Economy

	
    * Kevin Roose in _New York Magazine_: [In the New Economy, Everyone Is an Indentured TaskRabbit](http://nymag.com/daily/intelligencer/2013/10/new-economy-is-indentured-taskrabbits.html)

	
    * while Nancy Scola asks [Are We TaskRabbiting Ourselves to Death?](http://nextcity.org/sharedcity/entry/are-we-taskrabbiting-ourselves-to-death)

	
    * Darwing Bond-Graham in _Alternet_: [Uber and Lyft Get a Lot of Hype – But Ridesharing Is a Parasitic Business Model](http://www.alternet.org/labor/backed-billionaire-investors-ridesharing-companies-lyft-and-uber-are-dismantling-public)

	
    * In _Governing_, J.B. Wogan asks [How Will the Sharing Economy Change the Way Cities Function?](http://www.governing.com/topics/urban/gov-how-sharing-economy-will-change-cities.html)

	
    * Lobby Group [Peers](http://peers.org) hosted a set of [dinners](http://action.peers.org/page/s/dinner-with-peers-report),

	
    * and Businessweek’s Joshua Brustein went to one, concluding that [The Sharing Economy Isn’t Quite a Kick to Capitalism’s Crotch](http://www.businessweek.com/articles/2013-10-18/the-sharing-economy-isnt-quite-a-kick-to-capitalisms-crotch)

	
    * Meanwhile, in _The Atlantic Cities_, Emily Badger has a good piece about [The Rise of Invisible Work](http://www.theatlanticcities.com/jobs-and-economy/2013/10/rise-invisible-work/7412/).

	
    * An older post that is worth a read: _The Phantom Cab Driver_ asks: [100,000 Uninsured Rides and Counting: In Good Hands with Lyft and Sidecar?](http://phantomcabdriverphites.blogspot.ca/2013/02/100000-uninsured-rides-and-counting-in.html)

	
    * Payments is a key component for “sharing economy” companies, and it turns out it’s largely handled by [Stripe](http://www.itworld.com/operating-systems/375702/how-stripe-company-youve-never-heard-powers-sharing-economy).




		
