---
author: Tom Slee
categories:
- blog archive
date: 2007-04-06 12:40:38
title: The Long Tail 13 - Beyond Entertainment
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is another part of my critical reader's companion to _The Long Tail_, and it discusses Chapter 13 - Beyond Entertainment. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html).

* * *

This penultimate chapter of the book describes "five examples of the Long Tail at work outside of media and entertainment" [201]. These examples are eBay, KitchenAid, Lego, Salesforce.com, and Google. There is another side to each of these stories. 




eBay [201-203] has been hugely successful at being a marketplace for all kinds of odds and ends. Is it a Long Tail success?




The other side of the story. Let's remember that a Long Tail business is one that provides both the "head" and the "tail" of products. As Anderson writes, MP3.com was a music aggregation site, but it failed. The "problem with MP3.com was that it was only Long Tail" [149]. Meanwhile, iTunes focused more on the head, and makes all its money from it, then apparently builds on the familiarity it provides to use smart software to help people expand their tastes. Its growth came from being a marketplace for junk; Anderson's story of its growth implicitly admits this by saying that it "now does far more than clear the nation's attics" [202]. eBay is a broker ("facilitator" [202]) that matches buyers and sellers.




eBay breaks a second rule for Long Tail businesses. Because it does not stand between the buyers and sellers (unlike Alibris and Amazon Marketplace, as we saw in [Chapter 6](http://whimsley.typepad.com/whimsley/2007/03/new_marketplace.html), who ensure that they are the hub of all transactions and so collect all the information from both buyer and seller), eBay "can't offer many of the powerful filter technologies, such as recommendation engines, that drive demand so effectively at other Long Tail retailers" [203]. Putting aside yet again the question of how successful they are in reality as opposed to imagination, this "one size fits all" model he has in his head leads Anderson to suggest that eBay has a "vulnerability" [203] because of its reluctance to collect information about all the trades going on under its virtual roof.




What Anderson doesn't point out is that the eBay model gives the small vendor who is selling through eBay a bigger say in the sale. I find the eBay model more "democratic" to use one of the book's favourite words, in that it actually shares information with the vendors rather than hiding information from them as Alibris and, apparently, Amazon Marketplace do.




eBay is a huge success, an important story, but not a Long Tail one in all but the most crude sense. Yes, it sells a lot of many things, but as Anderson says when he wants to spin things in that direction, that's not the force behind the Long Tail story.




KitchenAid [203-205] is a little anecdote about how the maker of small kitchen appliances sells lots of colours ("over 50") online, compared to only a handful in the stores it supplies.




The other side. Whoop-de-do: this is nothing that can't be done in a catalogue. It's a neat thing for KitchenAid to do, but there's nothing fundamental here.




Lego [205-207] is building an online community of enthusiasts, who design and share their own constructions ("peer production" [206]) and can order the pieces to provide them. Is this the "Long Tail of plastic bricks" [207]?




The other side. Lego may like openness and they are trying some interesting things (Mindstorms for example), but there is another part to this story. [Lego](http://en.wikipedia.org/wiki/Lego_Group#Trademark_and_patents) is as interested in fixed ownership as ever: it has been fighting the loss of its patents for years. With the effort to extend its patent on the blocks themselves [failing](http://www.michaelgeist.ca/index.php?option=com_content&task=view&id=1014&Itemid=89&nsub=), it is nevertheless continuing to [extend their patents](http://www.iht.com/articles/2005/02/02/business/lego.php) and prevent other companies from making inroads in the world of blocks.




Salesforce.com [207-210] is an innovative company that is succeeding in a big way. It provides "hosted software" to companies (mainly small companies) to carry out "customer relationship management" tasks (CRM). Now it wants to become a one-stop shop: an aggregator for business applications, in the same way that Amazon is an aggregator for books. Salesforce has set up a platform called AppExchange that would "allow hundreds of smaller developers, many of them in low-cost places such as India, to reach those same customers" [208]. 




AppExchange may succeed in its goal. It's as close as Anderson comes to a legitimate Long Tail story here. In addition, Salesforce.com has just hired [Peter Coffee](http://blog.sforce.com/sforce/2007/01/apex_and_pure_v.html), an industry journalist who has long been one of the smartest technical commentators on software, to handle part of its platform.




The other side. This is a story in its early days. There are two sides to the move to aggregation and platforms: the owner of the winning platform in a particular area can win big, and Salesforce may become one of those winners unless Google or one of its other competitors beats it. It is less clear how much of its revenue will come from niche providers (no figures yet), and it is even less clear that the providers of goods for those platforms can win significantly. I suspect that many participants in AppExchange will share the [opinions of Geoff Merrick](http://www.internetnews.com/ent-news/article.php/3662481), chief architect of Salesforce partner Okere, who says "his company views being on the AppExchange as a way of developing name recognition rather than as a source of revenue". The venture is new, and the verdict is not yet in. Let's see.




Google [210-216] is included here on the basis of extending the advertising market into the Long Tail with its Adwords and AdSense programs. Traditional advertising, Anderson says, "is a classic, hit-centric industry where high costs enforce a focus on the biggest sellers and buyers" [210]. Now, with customizable search engines (maps, images, etc), and the fact that most search terms are different (no surprise there) Anderson claims that Google is "barreling down the Long Tail of everything" [206]. 




The other side: The portrayal of "traditional advertising" is a straw man, like so many of the setups for the stories in this book. Traditional advertising is not just car companies advertising on prime-time television, it includes classifieds, Yellow Pages ads, flyers inserted in local newpapers, and so on. And does the Google money come from nowhere, or is this a shift of advertising budgets for small players from these local-focused efforts onto the Internet? There is nothing here to tell us. If advertising is shifting from local papers to Google Adsense, you can't just close one eye and say "I see a Long Tail". Well, you can, but it doesn't mean much.




Even as a story of business success, there are no figures here. How much of Google's revenue comes from its "Long Tail" of advertising? He doesn't say. Somehow the vaunted openness that the book is so keen on always stops one step short of actual revenue breakdowns, whether its Netflix or Google. Anderson does admit that "Although most of its [Google's] revenues come from the head of the curve, most of its customers are somewhere in the tail" [215], which makes you wonder what the revenue pattern is for Google. At the time of its [$1B investment in AOL](http://news.bbc.co.uk/2/hi/business/4547672.stm) just over a year ago, the BBC reported that "AOL is currently Google's biggest customer. During the first nine months of this year [2005], it accounted for about $429m, or 10% of Google's revenue."




Sometimes I feel like I'm nipping round the edges of the ideas in this book, but the lack of substance and lack of solid figures continues to irritate. Big Picture thinking is one thing, but this hyper-optimistic selective vision is another. 




Let's just be clear here - I'm sure that there will be many success stories in the coming years of companies who build aggregation platforms for various kinds of content, and who make a LOT of money doing so. I'm just not convinced that most of their revenue will come from "the Tail" of their content. Despite the talk of "democracy" I'm not convinced that the residents of the Tail will benefit much; and I'm definitely not convinced the net effect on our culture is one of increased real variety and diversity.


		
