---
author: Tom Slee
categories:
- blog archive
date: 2006-12-17 18:59:16
title: Technology Makes You Stupid
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Labour saving devices save you physical effort, so unless you deliberately do something about it, labour saving devices cut down your physical exercise and make you unfit.




New research (via Slashdot and the Independent) shows that brain-saving devices cut down your brain exercise and make you stupid.




On the bright side, the research also shows that those who share my laziness are not condemned to remain stupid, because our brain can still develop.

<blockquote>Satellite navigation systems can stunt your brain, preventing it from developing, according to scientists. They have discovered that taxi drivers have actually grown more brain cells because of all the knowledge they keep in their heads.

> 
> 

> 
> When the scientists compared the brains of taxi drivers with those of other drivers, they found the cabbies had more grey matter in the area of the brain associated with memory.
> 
> 

> 
> They believe that this part of the brain, the mid-posterior hippocampus, is where black-cab drivers store a mental map of London, including up to 25,000 street names and the location of all the major tourist attractions.
> 
> 

> 
> The research is the first to show that the brains of adults can grow in response to specialist use. It has been known that areas of children's brains can grow when they learn music or a language.
> 
> </blockquote>




Link: [Independent Online Edition > Health Medical](http://news.independent.co.uk/uk/health_medical/article2081652.ece).



		
