---
author: Tom Slee
categories:
- blog archive
date: 2005-12-19 22:58:41
title: Trubba Not
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Ive startit reading [Riddley Walker](http://www.ocelotfactory.com/hoban/riddley.html) again. Evry time I read it theres summit new. New chance evry time.




Here's Riddley on technological progress (p. 96):

<blockquote>Some of them ther shels ben broak open you cud see girt shynin weals like jynt mil stoans only smoov Id all ways usit the word _shyning_ same as any 1 else myt. The sun is shyning or the moon is shyning. Youwl see a shyning on the water or a womans hair. When you talk of the Little Shyning Man its jus the middl word of what hes callt there aint no real meaning to it. Suddn when I see the shyning of the broakin machines I begun to get some idear of the shyning of the Littl Man. Tears begun streaming down my face and my froat akit.... How cud any 1 not want to get that shyning Power back from time back way back? How cud any 1 not want to be like them what had boats in the air and picters on the wind? How cud any 1 not want to see them shyning weals terning?
> 
> </blockquote>

Riddley on individual choices:

<blockquote>Only my self! Looking at them words going down on this paper right this minim I know there aint no such thing there aint no only my self you all ways have every 1 and every thing on our back. Them as stood and them as run time back way back long long time they had me on ther back if they knowit or if they dint.
> 
> </blockquote>

Riddley on Wal-Mart (p 147):

<blockquote>What ever happens itwl be that you dint want to happen. What ever dont happen that'wl be the thing you wantit. Take your choosing how you like youwl get what you dont want.
> 
> </blockquote>

Aksherly thats not Riddley that Granser talking but its still the same he knows what he means rite enuf. 




Trubba not.


		
