---
author: Tom Slee
categories:
- blog archive
date: 2014-06-13 18:58:00
title: Notes from Personal Democracy Forum 2014
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				So I was lucky enough to be at the [Personal Democracy Forum](http://personaldemocracy.com/conferences/nyc/2014) at the beginning of June in New York. A few scattered thoughts.

I had a prejudice that this would be something of an inward looking conference, and was happy to be proved wrong. The range of perspectives was much broader than I expected, and while the core of the conference is the intersection of the internet with electoral politics and governance, the range of topics was broader than I expected too.

Which made the many references throughout to some loosely-defined "we" a bit odd. These were references from the stage and from organizers that implied a community around the internet and its use in (loosely progressive?) politics. This was the 11th PDF, a lot has changed over the last decade, and I'm not sure there is such a "we" any more.

The highlight of Day 1 was the appearance by video of Edward Snowden, a year after the first published leaks. Snowden impressed. He came across as thoughtful, well-read, articulate, and modest, which is a compelling combination. He even looked bashful at the prolonged applause, which was winning. I wish I could say the same for John Perry Barlow, who was "in conversation" with him, but I can't. Barlow kept dragging the conversation around to himself and kept prompting Snowden to agree with him - prompts that Snowden politely stepped around. Snowden's main point was a simple one: that, whatever one thinks of states spying on each other (as in, the US spying on Angela Merkel for example), mass surveillance of entire populations is significantly different and crosses a pretty clear line into illegitimacy. In addition, it has not even proved to be useful for its stated goals of preventing terrorist attacks. Snowden may turn out to be as pivotal figure for our time as Daniel Ellsberg was for the Vietnam War era. The video is [here](https://www.youtube.com/watch?v=3QrZlHFgxA0).

Some other selected personal highlights from the talks, with links where I can…

The theme for Day 1 was "Save the Internet", focusing on the role of an open internet for political freedom. I found [Katy Pearce](https://www.youtube.com/watch?v=iD1HgZWtQnQ)'s talk on "How Authoritarian Regimes Take Advantage of Social Media" and Zeynep Tufekci's talk on "[Movements in a Connected Age: Better at Changing Minds, Worse at Changing Power?](https://www.youtube.com/watch?v=5Jq3Uze-vKc&list=PLcvJwS9IjFNYc6mo5eDKoDATd6NrU5cvy)" both fascinating. Pearce has been looking at activism in the former Soviet states for years, and she paints a complex picture of the tensions and continuing changes as digital technologies morph and take on new roles in society. Tufekci returned from her native Turkey with interesting ideas about the difference between what is needed to spark sudden uprisings and what is needed to sustain a social movement or to achieve lasting political change. Demonstrations, she argued, act as a signal for a movement's organizational capacity. When demonstrations happen more easily, governments may misread the organizational strength they imply–and perhaps this happened in Egypt in 2011–but such misreadings won't persist.

Later on, after my own panel session on the sharing economy was over (written up by Sam Roudman [here](http://techpresident.com/news/25112/defining-sharing-economy-dissecting-its-merits), I felt it went pretty well but then I'm not the one to ask), more talks. Susan Crawford on the potential for municipal investment in "dark fibre" (ie, optical cables that are open for use) was all new to me – she writes about it [here](http://scrawford.net/fiber-by-cities-washington-dc-san-francisco-seattle/). Sue Gardner, now leaving Wikipedia, is an inspirational figure and her concerns about [Building the Public Internet](http://www.youtube.com/watch?v=Ns2qmtah3lM&feature=share&list=PLcvJwS9IjFNYc6mo5eDKoDATd6NrU5cvy&index=4) were compelling. You can find similar thoughts by her [here](http://qz.com/99329/how-we-are-losing-the-war-for-the-free-and-open-internet/) from last year.

Day 2's theme was "The Internet Saves", the idea being to focus on digital activities that used the Internet for good. The first morning session was great: [Matthew Burton](https://www.youtube.com/watch?v=llVmp1S5GA8Matthew%20Burton) and [Mike Bracken](https://www.youtube.com/watch?v=H-hKVQnNOUs) both talked about the importance of government service – a welcome change from the usual tech focus on entrepreneurship as the solution to social problems – and both delivered far more than they promised, which is the right way to go. If you have 17 minutes, do listen to Bracken: entertaining and novel. Bracken draws his language from Tim O'Reilly, speaking of "Government as a Platform", but his conception differs from that of O'Reilly (does one write "O'Reilly's"? that doesn't look right). The bulk of the O'Reilly "Government as a Platform" talk is more accurately described as "Government as Data Source": government provides the data, private industry uses it to build services. Bracken was talking about building a complete stack of services within the government, and to me that's a different take on the topic, and one that is far more promising.

But then came Brad Smith, Microsoft's General Counsel, and the contrast could hardly be more stark. Lots of overblown rhetoric and ringing phrases but much less substance and little self-awareness. Let's just say he sounded like a trial lawyer. And then much of the rest of the morning reflected the Omidyar Network's approach to dealing with social issues by setting up businesses to deal with it, an approach I am [not fond of](http://tomslee.net/2013/09/six-degrees-of-omidyar.html). Omidyar Network is clearly doubling down: one short talk here was about [HandUp](https://handup.us/), a startup that funnels donations to the homeless. Yes, a startup. So there was more for me to grumble about here, but again – that's the point of a good conference, to hear different points of view.

The format for the whole program was talks of about 20 minutes with no questions (plus breakouts). It worked well: allowing Q&A would have slowed everything down, and a lot of positions got spelled out just by having the variety of presenters on stage.

So good job TechPresident, and thanks for the opportunity to take part.		
