---
author: Tom Slee
categories:
- blog archive
date: 2007-08-12 17:43:05
title: Preconceptions
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

If you read this paragraph about Kanye West [from today's Observer](http://observer.guardian.co.uk/omm/story/0,,2144021,00.html) and don't do a double take, you have fewer preconceptions than I.

<blockquote>An only child ('Kanye' is an Ethiopian name which means 'the only
one'), whose parents split before he was a year old and who divorced
when he was four, Kanye was mainly raised by his doting mother, Donda.
They are still extremely close; he wrote a song for her on his last
album, 'Hey Mama', which, sweetly, she now has as the ringtone on her
cellphone. When Kanye was still a young child, they moved from Atlanta,
Georgia, to Chicago, where she became the chair of the English
department at Chicago State University before latterly taking over as
his manager.
> 
> </blockquote>


		
