---
author: Tom Slee
categories:
- blog archive
date: 2011-07-16 09:36:07
title: 'Linking to Dystopia: Wikileaks, Google, and Amazon'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				



  * [[WikiLeaks claims credit for the Egyptian uprisings](http://thenextweb.com/me/2011/07/10/why-egypt-wasnt-waiting-for-wikileaks-to-ignite-a-revolution/)] The frustrating thing is that WikiLeaks is an important and worthwhile development (and yes I have donated money to it). But there is a self-centred nature to its publicity that doesn't help, especially when it's way off the ball like this one. (via [Jodi Dean](http://jdeanicite.typepad.com/i_cite/2011/07/why-egypt-wasnt-waiting-for-wikileaks-to-ignite-a-revolution.html))


  * [[Making the world's information available, until we get bored](http://www.miller-mccune.com/media/how-google-disrespected-mexican-history-33540/)] Google's massive resources and short attention span is becomign a problem. In 2008 Google announced, in its usual self-congratulatory tone, a project to digitize the world's newspaper archives as part of its mission to make information accessible to everyone.[*](http://googleblog.blogspot.com/2008/09/bringing-history-online-one-newspaper.html) In May, Google shut down the initiative, with less fanfare, choosing instead to focus its efforts on a new payment system.[*](http://searchengineland.com/google-shuts-down-ambitious-newspaper-scanning-project-77970)[*](http://thephoenix.com/BLOGS/phlog/archive/2011/05/19/google-abandons-master-plan-to-archive-the-world-s-newspapers.aspx) According to the Richard Salvucci[*](http://www.miller-mccune.com/media/how-google-disrespected-mexican-history-33540/) Google has done this before, buying the _Paper of Record_ initiative and then shutting it down without explanation.[*](https://paperofrecord.hypernet.ca/default.asp)


  * [[Everyone Knows You're a Dog](http://www.theregister.co.uk/2011/07/14/google_profiles_youtube_verification_id/)] _El Reg_ is reporting that YouTube is moving towards a "real name" policy, which would seriously screw anyone wanting to upload videos of repressive actions. This looks to be part of the Google+ move to respond to Facebook: Google needs real names to better track your activity and hence to sell you to advertisers. The scope for unidentified and pseudonymous use of the web as described by Google [here](http://googlepublicpolicy.blogspot.com/2011/02/freedom-to-be-who-you-want-to-be.html) is about to get smaller.


  * [[Amazon joins the Tea Party?](http://www.slate.com/id/2299051/pagenum/all)] Amazon has long been the beneficiary of US sales tax laws written before online commerce, which charge sales tax only on purchases in states where companies operate. This means that in most states, buying from Amazon is cheaper than buying from a physical bookstore. You could argue that it's too much to expect Amazon to volunteer to pay taxes, but it's now actively opposing California's recent modernization of its sales tax code, complaining with a straight face that tracking tax information is too difficult. If only there was some kind of souped up calculator-type-machine that could help with that.[*](http://www.nytimes.com/2011/07/12/technology/amazon-backs-end-to-online-sales-tax-in-california.html)


		
