---
author: Tom Slee
categories:
- blog archive
date: 2010-11-07 13:02:23
title: 'Macrowikinomics I: Generalities'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is the first of a several-part series of posts on the new book _[Macrowikinomics](http://www.macrowikinomics.com/)_, by Don Tapscott and Anthony D. Williams. This post is a broad statement of what I think of the book: subsequent posts will look at particular case studies. Numbers in [square brackets] are page numbers in the book.




* * *




The Internet is a new terrain on which old conflicts of class, gender, wealth and power are being played out, and it’s not clear which contestants this new battleground favours.




That’s not how Don Tapscott and Anthony D. Williams see things. In _Macrowikinomics_, their follow-up to the hugely successful _Wikinomics_, they portray the Internet itself as a revolutionary force for change, carrying us to a radically different future. To them, society has a new set of fault lines and they are technological rather than political or economic. They divide the failing, decaying institutions of a bygone age (musty, industrial, closed, and hierarchical) from the blooming organic forms of the digital world (dynamic, self-organized, collaborative, open, and democratic). It’s get on board or be left behind. In this way the book is at right angles to reality. I don't completely oppose what they say, I just think the fault lines that matter run along a different direction.  
  
Tapscott and Williams value things that matter to many people, myself included. They value voluntary collaboration and sharing, openness and integrity in politics and business, and democracy in the sense of people having a say in the shape of their society. They seek ways to extend civic engagement, promote volunteer action, and encourage “global governance from the ground up” [302]. Their attitudes to egalitarianism are probably different from mine, but in terms of what constitutes a fair society we have some things in common. So it is unfortunate that I disagree with them deeply. Yet disagree I do, and these posts must be a largely negative commentary on their book.  
  
You can see the root of my disagreement, plain as day, on the book jacket, where six of the seven blurbs are from CEO’s of major companies. Appealing to these elite voices contradicts the message of the book, which is that we need to abandon hierarchy and move to a more democratic “age of networked intelligence” [24]. The contradiction continues inside, where the book adopts a consistently populist tone, arguing against “the cult of the policy expert” [270], with sentences like this sprinkled liberally throughout.




<blockquote>

> 
> The closed, hierarchical, and static regulatory structures of today must give way to new processes that embody values of openness, empowerment, inclusiveness, and knowledge sharing. [294]
> 
> 
</blockquote>




Then a few pages later they enthusiastically claim that “the Global Agenda Partnership shows a way forward”[307] for global governance. What is this Partnership? It is an initiative of the organization that hosts the Davos summits, the exclusive, by-invitation-only annual gathering of the world’s richest and most influential. If the Davos attendees are not elite, I don’t know who is.  
  
I suspect that Tapscott and Williams do not see this juxtaposition of billionaires and populism as contradictory. After all, if the crisis is one of vision, inspiration, and having the courage to take the digital plunge then anyone can lead that transformation, be they CEO or student or social worker. The new revolutionaries and the defenders of the old order are distinguished by attitude and aptitude, not by class and gender. Some are prepared to bet on the new technologies of participation and some have closed minds, remaining tied to outdated business models.  
  
I can’t agree. _Macrowikinomics_ sees the world through the lens of technological determinism, and it is a distorting lens. It sees the technology of the Internet as unleashing change on society, but is blind to the ways that society has changed the Internet and the ways in which, as the digital world has gone mainstream, it has increasingly taken on the characteristics of mainstream culture.   
  
On one side, _Macrowikinomics_ exaggerates the political and economic possibilities of digital collaboration as well as the discontinuity between today’s digital culture and the activities of previous generations. On the other side, it ignores the unsavoury possibilities that seem to accompany each and every inspiring initiative on the Internet (every technology has its spam) and inspirational initiatives for change that take place away from the digital world. Most importantly, it does not register the corrosive effect of money (and particularly large amounts of money) on the social production and voluntary networked activity that they are so taken with.  
  
Bu do these distortions matter? _Macrowikinomics_ is primarily a call to action. The program of the book is to relay stories about inspirational Internet-based initiatives, often based on conversations with the leaders of those initiatives. You will find few nay-sayers in these pages, and most often we must take the cast of characters at their own evaluation. The description of the Huffington Post, for example, is taken almost entirely from statements by Huffington herself and by admirers. I don’t mind that: who would want every book to be a cautious and balanced, analytical tract? The authors have an explicit agenda, and they are committed to making their case for a shift to digital collaboration. And so long as they are calling for people to use the possibilities of the Internet for good, isn’t that what matters?  
  
Unfortunately no, because the unrealistically sunny pictures of digital culture painted in _Macrowikinomics_ will lead idealistic people to misdirect their talents and energy. The book promotes many forms of digital activity as contributions to positive social change when the reality may be that they are making little difference, or even doing the opposite, perhaps transferring money from local communities to the pockets of Silicon Valley billionaires. A corrective set of lenses is needed, and that's what I'll try to provide in these posts.  
  
There is a danger that I’ll come across as an anti-Internet malcontent. But digital curmudgeons such as Andrew Keen tend to agree with many digital utopians that the Internet is forcing a change in the balance of power in society: the difference is that they are repelled by the change rather than entranced by it. Myself, I disagree that the balance has shifted very much at all. We live an increasing portion of our lives digitally, but the struggles we face remain the same and the major sources of conflict in society are unchanged. There are many inspiring digital initiatives and experiments carried out by admirable people, but it’s the people who are inspiring, and the technology is more often than not secondary. The Internet simply happens to be the natural terrain for today’s activists, because that’s where the people are.


		
