---
author: Tom Slee
categories:
- blog archive
date: 2006-10-22 23:27:29
title: In the Land of the Taliban - New York Times
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

* * *

[In the Land of the Taliban - New York Times](http://www.nytimes.com/2006/10/22/magazine/22afghanistan.html?_r=1&oref=slogin) - Elizabeth Rubin

* * *

I've been working on a couple of short essays to put up here, but they are not quite ready yet. Part of the reason is that I've been reading this astounding piece by Elizabeth Rubin, who reports from Afghanistan on the state of that country. I recommend that you click the "print" button on the page, print off all 20 pages of it, and read it closely, because it tells you more about what's going on than anything else I've read in the last two years.




Here are a few tiny pieces, chosen almost at random:




She talkes with one Abdul Baqi about an attack on the family of legislator Amir Dado, until recently intelligence chief of Helmand Province:

<blockquote>Abdul Baqi was also delighted by the attack. He would tell me that
Dado used to burn rocket casings and pour the melted plastic onto the
stomachs of onetime Taliban fighters he and his men had captured. Abdul
Baqi also recalled that during the civil war that ended with the
Taliban’s seizure of Kabul, Dado and his men had a checkpoint where
they “grabbed young boys and robbed people.”
Mullah Omar and his followers formed the Taliban in 1994 to,
among other things, bring some justice to Afghanistan and to expel
predatory commanders like Dado. But in the early days of Karzai’s
government, these regional warlords re-established themselves, with
American financing, to fill the power vacuum that the coalition forces
were unwilling to fill themselves. The warlords freely labeled their
many enemies Al Qaeda or Taliban in order to push the Americans to
eradicate them. Some of these men were indeed Taliban. Most, like Abdul
Baqi, had accepted their loss of power, but they rejoined the Taliban
as a result of harassment. Amir Dado’s own abuses had eventually led to
his removal from the Helmand government at 
> 
> United Nations
> 
> 
insistence. As one Western diplomat, who requested anonymity out of
personal safety concerns, put it: “Amir Dado kept his own prison,
authorized the use of serious torture, had very little respect for
human life and made security worse.” Yet when I later met Amir Dado in
Kabul, he pulled out a letter that an officer in the U.S. Special
Forces had written requesting that the Afghan Ministry of Defense
install him as Helmand’s police chief and claiming that in his absence
“the quality of security in the Helmand Province has dramatically
declined.”
> 
> </blockquote>




On a Taliban video:

<blockquote>They invoke a nostalgia for the jihad against the Russians and inspire
their viewers to rise up again. One begins with clattering Chinooks
disgorging American soldiers into the desert. Then we see the new
Afghan government onstage, focusing in on the 
> 
> Northern Alliance
> 
> warlords — 
> 
> Abdul Rashid Dostum
> 
> ,
Burhanuddin Rabbani, Karim Khalili, Muhammad Fahim, Ismail Khan, Abdul
Sayyaf. It cuts to American soldiers doing push-ups and pinpointing
targets on maps; next it shows bombs the size of bathtubs dropping from
planes and missiles emblazoned with “Royal Navy” rocketing through the
sky; then it moves to hospital beds and wounded children. Message:
America and 
> 
> Britain
> 
> 
brought back the warlords and bombed your children. In the next clip,
there are metal cages under floodlights and men in orange jumpsuits,
bowed and crouching. It cuts back to the wild eyes of 
> 
> John Walker Lindh
> 
> 
and shows trucks hauling containers crammed with young Afghan and
Pakistani prisoners — Taliban, hundreds of whom would suffocate to
death in those containers, supposedly at the command of the warlord and
current army chief of staff, General Dostum. Then back to American
guards wheeling hunger-striking Guantánamo prisoners on gurneys.
Interspliced are older images, a bit fuzzy, of young Afghan men, hands
tied behind their backs, heads bowed, hauled off by Communist guards.
The message: Foreigners have invaded our lands again; Americans,
Russians — no difference.
> 
> </blockquote>

Interviewing a school headmistress and landowner, also a Ministry of Women's Affairs deputy:

<blockquote>She weighed the Taliban regime against this new one in terms of
pragmatic choices, not terror or ideology. She said that she had just
wrapped up the case of a girl who had been kidnapped and raped by
Kandahari police officers, something that would not have happened under
the Taliban. “Their security was outstanding,” she said.

> 
> 

> 
> Under the Taliban, she said, a poppy ban was enforced. “Now the
governors tell the people, ‘Just cultivate a little bit,”’ she said.
“So people take this opportunity and grow a lot.” The farmers lease
land to grow poppies. The British and the police eradicate it. The
farmer can’t pay back the landowner. “So instead of paying, he gives
the landowner his daughter.” 
> 
> </blockquote>

The picture is depressing, it is complicated, and it has the aura of reality. We desperately need to hear more stories like this. The current debate is "us against the bad guys - fight or leave?" is so hopelessly out of contact that it is not worth having.


		
