---
author: Tom Slee
categories:
- blog archive
date: 2006-04-17 11:04:11
title: The Man Who Saved the World
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

So far as I know, there is only one person in history who can legitimately claim to have saved the world. We only found out about him in 2002, and still seem to know very little about him (here is the little that [Wikipedia](http://en.wikipedia.org/wiki/Vasili_Alexandrovich_Arkhipov) has to say - no birth date, no indication when he died, even the rank is not clear). 




He was some kind of second-in-command on a submarine during the Cuba
missile crisis and made the call not to launch a nuclear torpedo when it
seemed like perhaps the US had attacked them with depth charges. 




It is wonderful that the person who can make this singular claim was so unlike the usual idea of a hero. Not a "visionary leader", not at the pinnacle of a career, not a Dirty Harry/Rambo go-get-em type. Basically he was a civil servant doing his job, calming someone down (in this case the captain), and advising caution and wait-and-see. 




How very non-heroic for a hero.

Update: perhaps [Stanislav Petrov](http://en.wikipedia.org/wiki/Stanislav_Petrov) can make the same claim.


		
