---
author: Tom Slee
categories:
- blog archive
date: 2010-11-27 21:31:13
title: Wu Knows What a Monopoly Is?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Columbia Law School professor Tim Wu wrote a bit for the _Wall Street Journal_ called [In the Grip of the New Monopolists](http://online.wsj.com/article/SB10001424052748704635704575604993311538482.html). It's about Facebook, Google, eBay, Apple, and Amazon -- and a bunch of people say he doesn't know what he's talking about.




George Mason University's Adam Thierer claims that [Tim Wu Redefines Monopoly](http://techliberation.com/2010/11/13/tim-wu-redefines-monopoly/), and accuses Wu of being "hell-bent on redefining the English language". TechDirt's Mike Masnick [states confidently](http://www.techdirt.com/articles/20101113/16010011846/success-by-itself-is-not-a-monopoly.shtml) that "domination of a market, by itself, does not create a monopoly", and [goes on](http://www.techdirt.com/articles/20101116/01370411876/tim-wu-insists-that-market-domination-is-a-monopoly.shtml) "if we look at the basic definition of a monopoly, you see that it's about having an _exclusive_ situation – being the only seller in the market, or having _exclusive_ control". In [BusinessWeek](http://www.businessweek.com/technology/content/nov2010/tc20101126_023905_page_2.htm) and [GigaOm](http://gigaom.com/2010/11/25/tim-wu-google-facebook/) Mathew Ingram picks up the story and declares "none of these examples – with the possible exception of Google and search – meets any kind of serious test of the term monopoly" and that "It's not clear what Wu even means by saying that Apple has a monopoly on "online content delivery."




But Wu is right and they are wrong. Monopoly is an economic term and he is writing in the Wall Street Journal, so it's not far-fetched to use the economic definition. And no less a source than Google's own economist Hal Varian defines a monopoly as "a situation where a market is dominated by a single seller". Not "where there is only one seller". The graduate text "The Theory of Industrial Organization" by Jean Tirole says that "most of the [monopoly] phenomena here could be derived even in the presence of competitors as long as the firm retained some market power. So it's pretty clear that economists use the term the way Wu does.




I did point this out in the comments to Adam Thierer's piece, and Cato Institute's Jim Harper (or maybe some other Jim Harper?) replied that "The stylized version of the word "monopoly" adopted by some economists is fine for them to use in talking among themselves. In the Wall Street Journal, readers will take it to mean "one seller," just like they take "monorail" to mean "one rail" and "monotheism" as the belief in one god, etc."




But is that how people use the word in everyday life? Let's turn to a couple of tech columnists to see how they use "monopoly". Here is one [Mike Masnick](http://www.techdirt.com/articles/20101108/03035911755/microsoft-s-anti-piracy-efforts-millions-spent-driving-people-to-open-source-software.shtml): "In the past, Microsoft used to be willing to admit that unauthorized copies helped the company, as it helped establish its software as a near-monopoly in certain areas, and kept competitors out." Or how about one [Mathew Ingram](http://www.niemanlab.org/2009/09/micropayments-for-news-the-holy-grail-or-just-a-dangerous-delusion/) - the one who says "It's not clear what Wu even means by saying that Apple has a monopoly..."-arguing against a suggestion that micropayments can work for newspapers:




Reifman defends his approach by pointing to several successful models of payment for services, including iTunes, text messaging, TiVo, and broadband Internet. The first thing that leaped out at me is that three of those four things — iTunes, text messaging and broadband Internet — are a result of something approaching a monopoly (or an oligopoly or cartel, in the case of text messaging and broadband Internet). Apple can charge for music because it controls access to the songs from all the major record labels. Phone companies and cable companies can charge usurious rates for text messaging and Internet because they have little or no real competition.




Yes, I guess people really do use "monopoly" the way Tim Wu does.


		
