---
author: Tom Slee
categories:
- blog archive
date: 2008-10-15 22:27:53
title: 'WikiBollocks: Tapscott DigiDemocracy Hype Shock Horror'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Don Tapscott [gets it all wrong](http://www.theglobeandmail.com/servlet/story/RTGAM.20081014.wcodigital14/BNStory/usElection2008/home) about  the "Net Generation":

<blockquote>[T]he new generation is turning into a political juggernaut that will dominate and change U.S. politics in the future. ..  They have at their fingertips the most powerful tool for informing, organizing and mobilizing. What's more, they know how to use it effectively, by communicating directly with each other, instead of waiting for orders from campaign headquarters.  
And they won't settle for politics as usual. Having grown up digital, they will want to be involved in the act of governing by contributing ideas before decisions are made. What's more, they'll insist on integrity from politicians; if politicians say one thing and do another, they'll use their digital tools to find out, and spread the news.  
Along with possibly being a decisive factor on Nov. 4, afterward they'll shake up the business of government. No matter who wins, the new president will have a tiger by the tail.
> 
> </blockquote>

  
Lots of young people are voting for Obama & Young people use the Internet => The Net is giving rise to a new era of participation and blah blah blah.

  


If he had waited a day and watched the Canadian results he would have seen that there is no evidence of a boom in young voters here. The overall turnout was way down and there is no indication in the results or elsewhere of a significant boom in young voters (although it may be up from the [historic low](http://www.mapleleafweb.com/features/voter-turnout-canada) of 25% of the 18-24 age group in 2000). And  yes, Canadian youth use the Internet.

  


For anyone not completely committed to Wikibollocks the conclusion is obvious: youth participation in the US is more to do with the Big Eared One than with Facebook. But The Globe and Mail just print this junk anyway.

  


Tapscott's Wikinomics was abysmal, and I see his new Grown Up Digital is at 4000 in the Amazon rankings. I think I'm going to have to give my blood pressure a boost and read the damn thing. Watch this space.


		
