---
author: Tom Slee
categories:
- blog archive
date: 2005-11-18 20:32:35
title: A new eugenics?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Interesting letter by the always-worth-reading Margaret Somerville in the Globe and Mail this morning, following an article by the rarely-worth-reading Mararet Wente on abortion and disability. She says:

<blockquote>Re Margaret Wente's Disabled Kids Are The Abortion Debate No One Wants
To Have (Nov. 17): Whatever our view of the ethics at the individual
level of parents-to-be screening their embryos and fetuses for genetic
and developmental abnormalities and discarding those that are
genetically or developmentally "defective," these decisions at a
societal level will have the effect of wiping out certain groups of
people, such as those with Down syndrome or achondroplasia (dwarfism),
or who are profoundly deaf or manic-depressive.
> 
> 

> 
> And as genetic knowledge expands, other groups are likely to be reduced. Female embryos and fetuses are already being eliminated, and some fear a similar fate if the genes for homosexuality are identified. The cumulative effect of individual decision-making is wiping out certain groups, a situation that would never be tolerated as public policy.
> 
> 

> 
> Are we creating a "new eugenics" -- deliberately eliminating genetically undesirable people from society? Those favouring screening finesse this question by arguing that an individual's choice regarding the nature of their child is not a eugenic decision and comes with their "absolute right to reproductive autonomy". They say eugenics is practised only when a choice is made in relation to a group or class or by someone who's not the future parent. But is that sophistry?
> 
> 

> 
> And where the government supports screening programs to avoid, as a recent article in the medical journal The Lancet euphemistically puts it, "live-born children with preventable physical or metnal handicaps," is this really the adoption of public policy of eugenics?
> 
> </blockquote>

I wouldn't pretend to know how to balance this particular tension between individual reproductive rights and the collective consequences of individual choice, but I can't imagine there is a clean solution to this messy problem. Somerville has written on this stuff a lot (see The Ethical Canary, for example) and Thomas Schelling (Choice and Consequence) has some insights into this, as into so much else.


		
