---
author: Tom Slee
categories:
- blog archive
date: 2013-09-08 02:48:00
title: Impostor Syndrome
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				_This is a vivid and completely unsubtle dream I had in late July, or maybe early August. Offered for anyone who has similar ones: feel free to add your own._

I’m about to give a talk in Manchester, in a large crowded room that looks like a courtroom. I’ve given the talk the day before, in Liverpool, and it went well, but now I’m feeling nervous because I can’t find my notes anywhere. I’m sure they’re in a pocket, or a bag, but I just can’t find them and now the crowd is coming in.

The room is full and there are two young white men with dark hair who are my hosts. One stands up to introduce me. He starts with “Tom Slee spent …” and then looks for the background information, and then at the other young white man with dark hair. He thinks I come from somewhere impressive; that I have qualifications for the talk I am about to give; that I have credentials that will roll off the tongue and give the evening a stamp of prestige.

I don’t. It’s not like I’ve deceived anyone – the other host knows my background, it just doesn’t include anything impressive. The introducer looks to the other host and asks “where is he from?” and the other host says “Nowhere. He doesn’t have an affiliation.”

There is great embarrassment all around as everyone realizes that I am not the kind of speaker they were expecting, and this is not the kind of event they thought they were in for. Swiftly and quietly, everyone starts to leave.

My humiliation at this misunderstanding is matched only by my relief. I still haven’t found my notes. I have no idea what I could have spoken about.		
