---
author: Tom Slee
categories:
- blog archive
date: 2010-11-13 23:49:12
title: What is Wrong With Government 2.0
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_- why open data needs a non-commercial-use license, and the lessons of microcredit._




“Government 2.0” is the initiative to make government data open to the public using Web-based technologies. Leading light Tim O’Reilly describes it as “government as platform”. The idea is that open data - provided in such a way that programmers can write software to read it, analyze it, and transform it - increases transparency and promotes innovation.




Government 2.0 is on a roll. It got a big boost in the US from Barack Obama’s [early memo](http://www.google.com/url?q=http%3A%2F%2Fwww.whitehouse.gov%2Fthe_press_office%2FTransparencyandOpenGovernment%2F&sa=D&sntz=1&usg=AFQjCNHh8y_lZRX83PZDtX7nXJbUXeOLeA) on transparency and open government, and the setting up of the [data.gov](http://www.google.com/url?q=http%3A%2F%2Fdata.gov&sa=D&sntz=1&usg=AFQjCNFA6mHV3awfDO42uTwaYOenE0SGng) website. In the UK there is [data.gov.uk](http://www.google.com/url?q=http%3A%2F%2Fdata.gov.uk&sa=D&sntz=1&usg=AFQjCNGlekx3eAQutEU6rVXfddLacqGb0A) and David Cameron’s “[Big Society](http://www.google.com/url?q=http%3A%2F%2Fthebigsociety.co.uk%2F&sa=D&sntz=1&usg=AFQjCNHXYvyP6s1Aun8yiClPjTh2DGOqhQ)” initiative. Even Canada’s notoriously secretive government is consulting about it and [many cities have opened up data feeds](http://www.google.com/url?q=http%3A%2F%2Fwww.guardian.co.uk%2Fnews%2Fdatablog%2F2010%2Fnov%2F09%2Fcanada-open-data&sa=D&sntz=1&usg=AFQjCNECJfDsPDGpYRpn7lArcw7FnnEEjw). And there are other initiatives [around the world](http://www.google.com/url?q=http%3A%2F%2Fwww.guardian.co.uk%2Fworld-government-data&sa=D&sntz=1&usg=AFQjCNFDDnlaczbg_2AyY8Y1booQMvXjhw). Sounds great? Well yes and no.




**2.0 Agendas**




The rhetoric of Government 2.0 draws heavily from efforts by private citizens and non-profit groups to make government more accountable. It has a civil liberties flavour, with talk of citizen engagement and of citizens’ rights (“giving citizens access to data that is theirs”), participatory society, collaborative democracy, transparency, and so on. Take the new collection of essays [Open Government](http://www.google.com/url?q=http%3A%2F%2Foreilly.com%2Fcatalog%2F9780596804367&sa=D&sntz=1&usg=AFQjCNEeUCHXvFke9arCa0X_uOTiljCw3A). The examples of Government 2.0 initiatives almost all deal with citizen access to the US government’s inner workings: campaign contributions, lobbying data, congressional votes, legislative proceedings, federal government contracts and spending, court proceedings. It describes efforts by non-commercial groups such as [opensecrets.org](http://www.google.com/url?q=http%3A%2F%2Fopensecrets.org&sa=D&sntz=1&usg=AFQjCNHkNZ6RPifsdOx6UamjvR21mR7T7w), [maplight.org](http://www.google.com/url?q=http%3A%2F%2Fmaplight.org&sa=D&sntz=1&usg=AFQjCNFRH3g5BSRxuALR9jj2zU0wz_XjPQ), [followthemoney.org](http://www.google.com/url?q=http%3A%2F%2Ffollowthemoney.org&sa=D&sntz=1&usg=AFQjCNELjV7tTppx4NineKjfOOBNO5a7zw), [govtrack.us](http://www.google.com/url?q=http%3A%2F%2Fgovtrack.us&sa=D&sntz=1&usg=AFQjCNEFTfWGafW7rx_HOrKrkAvqhJ7rgw) and so on to use this data to enforce greater accountability. This is all fine and good - although proponents should recognize that this access to information is one step in an arms race and that those who want to hide information will now look for ways to do so.




But the “Open Government” project has a second agenda: it demands that data be made open not only to citizens, but also to private companies. The recent [Gov 2.0 Summit](http://www.google.com/url?q=http%3A%2F%2Fwww.gov2summit.com%2Fgov2010&sa=D&sntz=1&usg=AFQjCNEhWiZl0rZC6D9Gi8RljJFSc6xNVw) and [Gov 2.0 Expo](http://www.google.com/url?q=http%3A%2F%2Fwww.gov2expo.com%2Fgov2expo2010&sa=D&sntz=1&usg=AFQjCNEPw8eE8oxPaGQ9N3iCe_ix9w_aHQ), also organized by O’Reilly Media, are big Washington events sponsored by major technology companies. It is clear that there is money to be made in Government 2.0 - money that is mentioned very sparingly in the Open Government book.




**Participation or privatization?**




Should we care if private companies get our data for free? After all, maps and weather have already been made available, and innovative commercial applications such as Google Maps have made it useful to the public. Many Government 2.0 enthusiasts see commercial opportunities complementing non-commercial activities. Tim O’Reilly writes, “The whole point of government as a platform is to encourage the private sector to build applications that government didn’t consider or doesn’t have the resources to create. Open data is a powerful way to enable the private sector to do just that.”




There’s another name for outsourcing government services to private industry, and that’s privatization. Talking of “a dramatic redistribution of power from elites in Whitehall to the man and woman on the street”, as David Cameron [did](http://www.google.com/url?q=http%3A%2F%2Fwww.number10.gov.uk%2Fnews%2Fspeeches-and-transcripts%2F2010%2F07%2Fbig-society-speech-53572&sa=D&sntz=1&usg=AFQjCNFTn6b9ia_pnjJA7OwGqi9yqfDPZQ), is a lot like the Margaret Thatcher line that selling off nationalized industries was restoring them to the people. As Ed Miliband says, “for all the talk of a big society, what is actually on the way is cuts and the abandonment of community projects across Britain.” O’Reilly is very close to supporting the Big Society program (he praises it in a recent [tweet](http://www.google.com/url?q=http%3A%2F%2Ftwitter.com%2F%23!%2Ftimoreilly%2Fstatus%2F29122374574&sa=D&sntz=1&usg=AFQjCNGnvPydo5hzL8WACOG0tm9Gyti5kw)) and says that “In some sense, government hitting the wall on deficits is a good thing, if it forces a real reboot,“ which is not only callous, but uncomfortably close to Naomi Klein’s “Shock Doctrine” thesis. You have to wonder, is this what the civil libertarians who have been pulled into the Gov 2.0 effort really want? Some of them need to think a little harder before following Tim O’Reilly’s tune.




**The problems with profit**




Many of the heavy hitters in Silicon Valley believe in “social entrepreneurship”, in the belief that they represent an enlightened, humane, and smart capitalism. But money has a way of corrupting. The story of microcredit has lessons that Government 2.0 promoters could learn from.




Mohammed Yunus won a Nobel Prize for founding the non-profit Grameen Bank that extended “microcredit” loans to groups of poor people, with very encouraging results. When Pierre Omidyar, the eBay billionaire, got involved in microfinance he decided that the “non-profit” part of the story was a limitation. As the New Yorker’s Connie Bruck [reported](http://www.google.com/url?q=http%3A%2F%2Fwww.newyorker.com%2Farchive%2F2006%2F10%2F30%2F061030fa_fact1%3FcurrentPage%3Dall&sa=D&sntz=1&usg=AFQjCNEJmnyN5a65I7A8G3KTxWCge6nPtA) a few years ago: “Yunus is now seen by Omidyar and many others as the archetypal founder, too wedded to his original vision. In recent years, younger and nimbler players have been taking microfinance—their preferred term—toward the idea of building a fully commercial, profit-making sector. This conflict, between pure do-gooders and profit-minded do-gooders, has come to define the current debate in the microfinance world.”




Unfortunately it has not turned out so well. Yunus’s [worry](http://www.google.com/url?q=http%3A%2F%2Fwww.philanthrocapitalism.net%2Ftag%2Fpierrre-omidyar%2F&sa=D&sntz=1&usg=AFQjCNH5X491Y6jwSKu1aGV0P3VAGibUkw) that profit-oriented companies were “pushing microfinance in the loansharking direction” has been born out. This year’s IPO by SKS Microfinance, a for-profit company active in India, [made tens of millions](http://www.google.com/url?q=http%3A%2F%2Fwww.muhammadyunus.org%2FIn-the-Media%2Frich-ipo-brings-controversy-to-sks-microfinance%2F&sa=D&sntz=1&usg=AFQjCNHV_9bi9OoohP78q6Qd8AJNUrTZEA) for some of its board members, as well as for board members of Seattle-based nonprofit Unitus, which has invested in SKS. Meanwhile, the loans from these commercial microfinanciers have [become](http://www.google.com/url?q=http%3A%2F%2Fwww.bbc.co.uk%2Fnews%2Fbusiness-11664632&sa=D&sntz=1&usg=AFQjCNHDpP2cEGhxWAb-rL_fqkQzut5DOA) “death traps”, and after seventeen SKS clients in the Indian state of Andhra Pradesh [committed suicide](http://www.google.com/url?q=http%3A%2F%2Fwww.theglobeandmail.com%2Fnews%2Fworld%2Flittle-loans-big-trouble%2Farticle1797584%2F&sa=D&sntz=1&usg=AFQjCNFHLVnO_NN94rb_yfNEhT8-WKsiDg) the clamour for answers about the role of profit has become louder. There are real differences between profit-seeking and not-for-profit groups, and they must be kept in mind.




**A step forward**




There are other issues with Government 2.0 that I may come back to later, but let’s wrap this up. Glossing over the difference between companies and citizens obscures key issues at the heart of Government 2.0 and risks corrupting the whole enterprise. Fortunately, there is a solution. When government puts its data into the open, it does so with a license attached to it. In most cases this license permits both non-commercial and commercial use of the data, so long as the source is acknowledged. It’s time to consider licensing the data for [non-commercial use only](http://www.google.com/url?q=http%3A%2F%2Fcreativecommons.org%2Flicenses%2Fby-nc%2F2.5%2F&sa=D&sntz=1&usg=AFQjCNGL8gAHvHr_azYTNWKp3PVv9v45BA), and having a separate license for commercial users. Perhaps permitting some limited commercial use for free, but charging for more extensive use, would be a first step to protecting our data from the temptations of profit.




Update: Part two is [here](http://whimsley.typepad.com/whimsley/2010/11/what-else-is-wrong-with-government-20.html).


		
