---
author: Tom Slee
categories:
- blog archive
date: 2006-07-10 21:52:05
title: Juicy kidneys! Get yer nice fresh kidneys here!
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

RAD points me to a [New York Times article](http://www.nytimes.com/2006/07/09/magazine/09wwln_freak.html?_r=1&oref=slogin) by Stephen Dubner and Steven Levitt about buying and selling organs. That’s organ as in kidney or liver, not organ as in church or Hammond. It’s an interesting entry to a very topical topic: one that still has shock value but which we are going to hear about more in the future.




My point of view, unsurprisingly, is that I don’t trust market
mechanisms to deal with the problem. This essay is a starting point for
thinking about it. I hope to follow it up later with a second attempt.




* * *




The reason people are talking about buying and selling kidneys
is that organ transplants are safe and cheaper than they used to be, so lots of
sick people could benefit from an increase in organ donations, and so that
spare kidney you’ve been keeping around is now a very popular kidney, used and
second-hand though it be. So why, ask Dubner and Levitt, don’t we let people
buy and sell their kidneys? After all, “most people can live safely on one
kidney”, they say. They suggest that the main reason we don’t allow buying and
selling of kidneys is what they call “the repugnance factor”, and they have a
point, even though another reason is that it’s impossible to read that sentence
without it looking like this: “most **BUT
NOT ALL!!!** people can live safely on one kidney **UNLESS SOMETHING GOES WRONG WITH THE OTHER ONE**”.




The Dubner and Levitt article is a bit odd actually. It
suggests it’s talking about how paying people for their kidneys may save the
lives of people who need a new kidney, while also letting people with spare
kidneys earn some cash on the side. But when it comes to the specifics they don’t
talk about buying and selling at all. Instead, they talk about a matching
program that matches incompatible donor-patient pairs. In these pairs, each
potential donor’s kidney is a bad match for the immune systems of their partner—but
the system matches them with similarly incompatible pairs and the two matched
pairs can basically swap a kidney. No money involved. Then they talk about a
potential donor who was going to sell his kidney to a stranger and, when he discovered
that accepting payment for organs is illegal, went ahead and donated it anyway.
No money exchanged. They don’t really investigate payment for organs at all.




* * *




Still, even if D&L don’t actually talk about trading our
internal garbage collectors for money, other people are doing so. Down the hall
from Steven Levitt at the University of Chicago is Gary
Becker, the Nobel Prize winner who is in favour of markets in everything.
Together with graduate student Julio Elias, Becker has talked up the idea for
several years now and – Becker being Becker -- he gets a fair amount of press
for it. 




There are some technical reasons why I’m not convinced by
[Becker and Elias’s argument](http://home.uchicago.edu/~jjelias/Organs_Becker_Elias.pdf) (PDF). They aren’t at the centre of my problems with the
idea, but effectiveness does matter, so let me pursue these problems here.




First, they maintain that right now the supply curve for
kidneys is vertical. That is, a fixed amount of people are prepared to donate
kidneys. But the people most likely to donate kidneys are the relatives of
those on the operating table, so when the number of operations increases, so
the number of those relatives increases, and so the supply of kidneys increases.
It looks to me like that line should be sloping. Have I missed something? Hey,
it’s been known.




They go on to suggest that the actual number of kidneys
needed for transplants, compared to the total renal population of North
America, is so small that once you offer a reasonable amount of money you could
get as many kidneys as you could possibly want. That is, by offering payment
the supply curve goes from vertical to horizontal. And then they go on to
calculate how much you’d need to offer to induce people to sell. What they
don’t take account of (though in a more recent essay Becker considers and
dismisses this argument) is the possibility that offering to pay for kidneys
might actually cut down the supply. This would be counter to most economic
thinking, of course. The argument goes back to Richard Titmuss, a British
academic who wrote a few decades ago about blood donation in a book entitled
“The Gift Relationship”. Titmuss argued that offering to pay for blood would
actually dissuade some people from donating, because whereas people feel good
about themselves for donating blood, they don’t feel good about themselves for
selling blood. [Recent experiments in Sweden](http://whimsley.typepad.com/whimsley/2006/05/blood_and_money.html) suggest that there is
something to Titmuss idea. Becker doesn’t provide a real case against it, he
just asserts that the effect would be small.





Put these two things together and the effectiveness of even
a perfect market with no cheating or deception is less attractive than Becker
suggests. Instead of a dramatic change from a vertical supply curve to a
horizontal one, you have a more nuanced change. And that’s if everything else
works dine.




* * *




Becker also dismisses the other main arguments about the
introduction of payments, which are:




  * that the result will be poor people selling
their kidneys in order to supply longer life to the rich, giving yet another
twist to the growing gap between rich and poor in the world. 


  * that the dangers of malpractice and deception of
one form or another are so large – especially for those without the resources
to get legal assistance and advice, that poor people in particular will be
preyed on.


  * that just about any system you put in place
provides incentives for all kinds of nastiness. This applies to presumed
consent mechanisms as well. And although this kind of thing can sometimes be
dealt with, it’s costly to do so.



Well, I hope to look at some of these in a Part II later.




* * *




There are some countries that have already taken deliberate
steps to make it easier for people to get new organs. Nancy Scheper-Hughes is a
sociologist at the University of California, Berkeley, and she has carried out research on organ trading around the world. In a [2003 forum](http://www.lahey.org/Pdf/Ethics/Ethics_Fall_2003.pdf) she described these efforts:




<blockquote>There’s the
Israeli model: very low donation rates so you export your transplant patients
elsewhere and you give them medical insurance to pay for it, even at the cost
of their buying kidneys from poor peasants in Eastern
Europe. There are the Philippine, Iranian and Iraqi models:
government-sponsored payments that allow very poor people to sell their organs
for as low as $500, which leads to deep social resentments. The Chinese model:
you can use the organs of executed prisoners. The Russian model: in which there’s
not such a careful monitoring of confirmatory tests for brain death. The Spanish
model: paying the procurers. More humanely, there is the Austrian and Belgian model
of presumed consent.

> 
> </blockquote>

There’s no doubt other countries will be dealing with the
issue in the future. But Scheper-Hughes is on the money (so to speak) when she
points out that the presumed consent model requires a trust in the fairness of
the medical system that certainly doesn’t exist in the US.

<blockquote>“we don’t
have the kind of social consensus whereby people feel that their organs will be
fairly and equally distributed among the poor as well as the wealthy or well
insured, among women as well as men, or that all will have an equal right to
get an organ should they need one. So first we have to address the lack of
national health care, the 44 million uninsured, and the contradiction in asking
poor people in America
– who tend by and large to be over-represented in emergency rooms and ICUs – to
donate organs when they and their relatives may not even have basic health
care.
> 
> </blockquote>




Canada may not be in quite the same straights as the US in that way, but it’s got some
real issues, and they need to be dealt with in order to deal with the issues surrounding
organ transplants.


		
