---
author: Tom Slee
categories:
- blog archive
date: 2015-12-02 02:10:45
tags:
- airbnb
title: Airbnb's business in New York City
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				[According to the New York Times](http://www.nytimes.com/2015/12/02/technology/airbnb-releases-trove-of-new-york-city-home-sharing-data.html), Airbnb yesterday "released" data about their business in New York City. As I first reported on Airbnb in New York [two years ago](http://tomslee.net/2013/11/airbnb-business-in-new-york-revisited.html), when that business was a lot smaller, I was interested. Airbnb's Chris Lehane says "Our hope is that people will understand 99 percent of people on Airbnb in [New York City](http://topics.nytimes.com/top/classifieds/realestate/locations/newyork/newyorkcity/manhattan/?inline=nyt-geo) are using it as an economic lifeline,” and who could object to that? Would the real numbers show that we critics are wrong?

My work has been based on scrapes of the Airbnb web site (now done better by Murray Cox at [Inside Airbnb](http://insideairbnb.com)), so it's necessarily less accurate than Airbnb's own data. On the other hand, I don't have a $25 billion market valuation at stake in the answer, so it may be easier for me to be honest in my reporting.

I hoped that "released" meant that I could get the data, but I was quickly disillusioned. It turns out to mean "made available only by making an appointment to visit Airbnb’s New York City office", which is a bit of a joke. Instead, all we get is the summary statements from Airbnb PR. Still, it is better than nothing. So I read on...

My first response to the New York Times article was dismay at this statement: "From November 2014 until November 2015, some 93 percent of revenue earned by active hosts in New York City who share their entire home came from people who have only one or two rental listings on the platform". That is a number far higher than I had seen, and suggests that a much bigger portion of the Airbnb business is their archetypal "regular New Yorkers occasionally renting out the home in which they live" than I had thought. I had reported about 40% of Airbnb's business coming from people with more than one rental listing and the numbers suggested 20% of business coming from people with more than two listings. Have I and other critics been getting it wrong? In the absence of complete data we have to make some estimates about income after all. This would be unfortunate as I have just [PUBLISHED A BOOK ABOUT THE SHARING ECONOMY THAT MAKES A GREAT CHRISTMAS PRESENT](http://www.orbooks.com/catalog/whats-yours-is-mine-by-tom-slee/) and that is critical of Airbnb.

But today the New York Times ran a correction: "From November 2014 until November 2015, some **75 percent **of revenue earned by active hosts in New York City who share their entire home came from people who have only one or two rental listings on the platform."  (my emphasis). The change from 93% to 75% is significant: that's almost four-fold increase in the proportion that comes from three-or-more listers. All of a sudden the Airbnb numbers look much more like those collected by myself and other external investigators, which Airbnb routinely say are inaccurate.

So what's the real picture? Yes, 25% of Airbnb revenue in NYC comes from people renting out "more than two" listings. My own estimate actually comes out _below_ that at 20% so my estimates are more friendly to Airbnb's "regular people" pitch than reality. My numbers also show that about 40% of total revenue comes from people with more than one listing, which is just what I reported two years ago. It's likely that the real number is closer to half, given the way my estimates seem to underestimate revenue from "more than three" listers. In short, far from showing that the critics were wrong, Airbnb's numbers show that our data, which they have been rubbishing, is pretty good and even generous to them: their numbers suggest that even more of the business comes from multiple listers than we have been claiming.

So here's the right way to say it. "From November 2014 to November 2015, about half of Airbnb's revenue in New York City comes from multiple-listing hosts. Hosts with three or more listings contribute 25% of the total." That's a much more commercially-focused operation than the original claim.

The 93% number that Airbnb gave is, by the way, their projection on next year's figures, to  which I can only say - if you're going to release data, maybe talk about the data and not about your dreams and aspirations? So far their supposed efforts to clamp down on hosts with many listings have been half hearted, and given that it may cut into their revenues we should not give it a lot of credibility. Airbnb has been talking the talk a long time about this challenge on their site, and yet so far they have done basically nothing about it (I'm travelling and don't have access to the full data set at the moment, or I'd show you).

Maybe more on this later. But for now, the new Airbnb numbers do nothing to undermine the critics' case.

		
