---
author: Tom Slee
categories:
- blog archive
date: 2006-05-19 22:44:31
title: Paradigm-Busting
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I got my author copies of the book today.




Pretty exciting!




It looks good - the cover is the tipped over shopping cart/trolley that I posted a couple of posts down. The colour (turquoise with a touch of grey, if that makes any sense) works, and I like the image a lot. 




The book is a trade paperback size (6" by 10") and its 240 pages are in a well-spaced, good sized, easy to read font (Stone). There's a continuity between the cover and the inside - the fonts for the headings are repeated on the cover, and the star that is used as a separator between sections is used again on the cover (a reference to Wal*Mart). There's even a shade of grey inside, used for the chapter numbers, which gives a slightly classier feel.




I hadn't seen the index (done by yours truly) in final form before, and it looks fine. I didn't end up putting any of those Easter Eggs in that you see in some indexes (eg, _No Logo_ has an index entry for "index, puzzling self reference to" on page 437 (or something) which is, of course, the page the index entry appears on). Still, there is something oddly personal about indexes - there can't be too many that have all of the following index entries in them:




asymmetric information  
beer  
_Dirty Pretty Things_  
focal point effect  
gene stacking  
hydrogen bomb  
intermolecular forces  
organized crime  
Qin, Emperor of China  
_Ulysses Unbound _(Jon Elster)  
van der Waals, Johannes  
wildebeeste




And as a bonus, there is a great review comment on the back from Jim Stanford, Canadian Auto Workers economist, Globe and Mail columnist, and an energetic commentator in many places. Here's what he has to say:

<blockquote>Conservatives dress up their destructive policy prescriptions in the language of 'individual choice.' Tom Slee's paradigm-busting book shows there are other, better ways for society to make choices. Marvelous and timely.
> 
> </blockquote>

Now that's a lot better than "uneven" from the other day.


		
