---
author: Tom Slee
categories:
- blog archive
date: 2007-05-18 13:31:38
title: A response to Alex Tabarrok
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

At Marginal Revolution, Alex Tabarrok has posted a [fine review](http://www.marginalrevolution.com/marginalrevolution/2007/05/no_one_makes_yo.html) of No One Makes You Shop at Wal-Mart: I'll be keeping this paragraph somewhere to cheer me up when I'm feeling gloomy:

<blockquote>Slee's book is the best of the anti-market books: it is well written, serious, and knowledgeable about economics. In fact, I regard Slee's book as an excellent primer on asymmetric information, free riding, externalities, herding, coordination problems and identity - Economics 301 for all those budding young Ezra Klein's of the world who think that Economics 101 isn't quite right.
> 
> </blockquote>

Very nice. But coming from his libertarian point of view, it's not surprising he has some criticisms. Let's skip right past the lesser ones to the Most Serious Of All:

<blockquote>The chapter on power is terrible, I did throw the book against the wall. Perhaps in order to prepare us to welcome government as the deliverer of our true preferences, Slee wants to diminish the distinction between liberty and coercion. But a true liberal should never write things like this:
> 
> <blockquote>...the formal structure of democracy and free markets is not enough to rule out exploitation and plunder - characteristics usually associated with repressive regimes.
>> 
>> </blockquote>
> 
> If Tom visits GMU (I happen to know he reads MR) he should watch out because I shall kick him in the shins stating, "I refute you thus."
> 
> 

> 
> More seriously, repressive governments around the world threaten, rob, torture and murder with impunity. Courageous individuals have died trying to escape such regimes while others have died fighting for their rights. No matter how great are differences in wealth, it is morally wrong to equate what goes on in repressive regimes with capitalist acts between consenting adults.
> 
> </blockquote>

Strong stuff, and it hits home because I always thought that chapter to be the weakest in the book. But blogs are no place for mild-mannered agreement so let me try to return the kick in the shins.




Most of us see many problems of this world in shades of grey, but there are always a few issues that are starker and more elemental, which we see as black or white. The "shades of grey" issues are questions of nuance and detail - these are questions where reasonable people can reasonably disagree, where we look to modest reform to improve matters, and where we look for technical solutions. It's the dichotomies where we stand our ground - these are the things that define our politics; they are matters of principle - it's right vs. wrong and communication across these divides is difficult. So what are these fundamental, black vs white issues? 




Karl Marx knew what he thought was fundamental:

<blockquote>The history of all hitherto existing society is the history of class struggles.
> 
> </blockquote>

My brother once relayed to me a very short conversation he had in a pub with a radical feminist:

<blockquote>Brother: throughout history the fundamental oppression is that of one class by another.  
Feminist: throughout history the fundamental oppression is that of women by men.  
Imagined Next Line By Both: who else can I sit with?
> 
> </blockquote>

Peter Singer (in "A Darwinian Left", page 8) sets out what he sees as "fundamental to the left": it is to be "on the side of the weak, not the powerful; of the oppressed, not the oppressor; of the ridden, not the rider."




Where do libertarians draw their line? It's coercion versus liberty: the state versus markets, laws versus bargains. That's why a typical Cato Institute [article](http://www.cato-unbound.org/2007/05/07/daniel-b-klein/economics-and-the-distinction-between-voluntary-and-coercive-action/) is something like "Is the Minimum Wage Coercive?" Small wonder then, that it's a chapter setting out to recast this dichotomy as shades of grey that makes Alex Tabarrok throw the book against the wall. You can see elsewhere in Alex's review that this is the fundamental dichotomy he has in mind as he reads. When I talk about collective action he assumes I'm talking about government intervention in the economy because that's where he sees me, as his ideological opposition, coming from.




It's a mark of the success of the libertarian project that the left has bought into this false dichotomy of state versus markets. We (the left) are the victim of our own success - the post-war construction of the welfare state, the achievements of social democracy, the provision of public education, and of public healthcare. We've let ourselves be identified with these achievements, and so now stand as conservative defenders of the state against the market-favouring radicals. Yet things need not be so. I look on my bookshelves and see some books from the UK of the late '70s and early '80s: "In and Against the State", Ralph Miliband's "The State in Capitalist Society" and so on. Those on the left have a long history of opposition to the state, and a recognition of its problems. The difference is, we on the left don't see the state as the root of the problems. The state may be a hammer, but it's the arm holding it we need to worry about. "The executive of the modern state is but a committee for managing the common affairs of the whole bourgeoisie" wasn't it?. 




The point of my chapter is to remind us that the state is not the sole source of coercion, and that libertarians have a blind spot to coercion in the non-state sector. In the comments section of a recent Marginal Revolution [post](http://www.marginalrevolution.com/marginalrevolution/2007/05/is_the_minimum_.html) about the Cato Institute Minimum Wage article I said "_My employer requires that I follow instructions from my manager or I can be fired. Is that also coercive? Yes." _and another commenter responded _"_No, refusing to buy future labor from you is not coercive." I can see what he or she means, but you can also see the false dichotomy here - the law is coercive, everything else is a matter of choice. Tell that to (among many many examples) workers [locked-in overnight](http://www.nytimes.com/2004/01/18/national/18WALM.html?ex=1389762000&en=659ee9a0025b35de&ei=5007&partner=USERLAND) at Wal-Mart stores. Was slavery coercion? Yes, and it would surely be a stretch to see slavery as a problem rooted in the state.




Alex writes "If there were no asymmetric information, no herding, no coordination problems and so forth I guarantee that there would still be plenty of inequality." True enough, but if there were no state, no laws, no public health standards, and so forth I guarantee that there would still be plenty of coercion.




We are obviously speaking from very different points of view. Are there paths across the divide? I would suggest there are. Alex claims that I have "no appreciation that what some of us MarketThink people really advocate is civil society which includes non-profits and voluntary collective action of all kinds." Compare that assertion with Erik Olin Wright's rather wordy but still worth reading "Taking the Social in Socialism Seriously" ([PDF](http://www.ssc.wisc.edu/%7Ewright/Published%20writing/Taking%20the%20social.pdf)), which also focuses on civil society as a way out of the market/state dichotomy. Or the way in which both communitarian left and libertarian right took Jane Jacobs to their hearts. There is a phrase there (voluntary collective action) that we all seem to favour, even as some of us focus on the collective and others on the voluntary. Perhaps a focus on the possibilities of that phrase would be worth exploring.




**Update: **Brad DeLong links to AT's review [here](http://delong.typepad.com/sdj/2007/05/tyler_cowen_on_.html#comments) (but credits the review to AT's partner in marginal crime Tyler Cowen). The comment thread has quite a different set of sympathies!




**Update 2:** The other day I was pleased that my amazon.com Sales Rank was around 42,000. It is now 3634 - entirely due to the review.


		
