---
author: Tom Slee
categories:
- blog archive
date: 2011-10-18 19:06:54
title: Comment problems and one other update
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I've had a couple of people tell me they were unable to post comments. After taking this up with Typepad, I have shifted from their "Typepad connect" system back to the vanilla commenting system. If you have problems posting a comment, then I would appreciate an email at last name dot firstname (gmail). And you can rest assured it isn't personal unless you are a spambot, in which case it is, or would be if you were a person.




Also, in [a recent post](http://whimsley.typepad.com/whimsley/2011/09/earlier-today-i-thought-i-was-doomed-to-fail-that-part-3-of-this-prematurely-announced-trilogy-was-just-not-going-to-get-wr.html) I suggested that there was a conflict of interest in a [paper](http://ijoc.org/ojs/index.php/ijoc/article/viewFile/1246/613) I read. The authors have now published an explanation at the end of the paper and I retract the suggestion (I still don't understand why lead author Gilad Lotan lists his affiliation as he does, but that's his personal decision). I've put a note in the post to clarify.


		
