---
author: Tom Slee
categories:
- blog archive
date: 2016-05-26 18:07:09
title: Regulating the Sharing Economy
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				A long overdue post.

There is no slowdown in the debates about how to regulate Airbnb, Uber, and other Sharing Economy companies, as city after city in country after country faces up to the challenges of how to deal with these new actors. If only there were a clearly thought-out, well-written work that spelled out the issues involved, provided a framework in which to think about how to respond, and provided a useful set of recommendations that provided the starting point for regulatory ideas.

Well luckily there is.

Vanessa Katz's "[Regulating the Sharing Economy](http://scholarship.law.berkeley.edu/btlj/vol30/iss4/18/)" was published last September the Berkeley Technology Law Journal. I heard about it at the time (thanks Chris Hoofnagle), but I was just going through final edits on "What's Yours is Mine" and did not have a chance to write about it. I assumed someone else would, but a quick Google suggests that it has been overlooked. This is a shame. If you are interested in the topic, I strongly recommend it.

Now I am not a lawyer, still less a legal scholar, so I don't really know the standards that apply to law scholarship, but as someone concerned with the topic I can say this: there are proposals for regulation that have been picked up and become part of the public debate (eg from venture capitalist Nick Grossman,[*](http://www.nickgrossman.is/2015/06/04/regulation-the-internet-way/) self-regulation proponent Arun Sundararajan,[*](https://lawreview.uchicago.edu/page/self-regulation-and-innovation-peer-peer-sharing-economy) Tim O'Reilly[*](http://beyondtransparency.org/chapters/part-5/open-data-and-algorithmic-regulation/)), and I learned more from Katz's piece than from any of these. It's one of the few articles I've gone back to over and over again because Katz offers a way to think through the issues, to go beyond the too-easy claim that new technologies and new businesses need new rules, and to think about what's really new, and what's left unchanged.

A good starting point is to ask why we want to regulate some industries and not others, and Katz identifies a few principles that explain why we have a public interest in some private transactions. One class is "special relationships" in which the consumer is particularly vulnerable, and when additional burdens are placed on the service provider:



 	
  * Relationships that pose potential health, safety, and financial concerns for consumers: landlord-tenant relationship being one example.

 	
  * Relationships in which service providers have a disproportionately strong bargaining position: innkeepers and "common carriers" such as taxi drivers are required to accept all customers without discrimination. It's a constraint on business, but one that is justified by the vulnerability of the customer.

 	
  * Relationships in which the service provider is the "least-cost  avoider" - the party who can adopt precautions against a certain risk at lowest cost. Katz does not spell it out, but these situations are related to markets with asymmetric information: to keep the market working the service provider (as least-cost avoider) is required to guarantee certain standards: product liability being an example.


Sharing economy companies are quick to say that many existing regulations do not apply to them, but Katz is one of the few who asks the other question - what regulations are needed to deal with new challenges raised by the platform companies. Among these are reputation systems and their lack of appeal / process, privacy (a big deal when we start talking about in-car cameras, as well as customer data), and surge pricing (what happens when Uber offers personalized pricing based on your phone battery levels?)

All in all, an excellent read.		
