---
author: Tom Slee
categories:
- blog archive
date: 2013-03-09 20:28:47
title: Evgeny Morozov's "To Save Everything, Click Here"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Everybody loves Jane Jacobs.

I love Jane Jacobs. "Austrian" economists with whom I disagree, like Alex Tabarrok, love Jane Jacobs. You probably love Jane Jacobs. Steven Johnson says he loves Jane Jacobs in his recent book _Future Perfect _ -- __but so does Evgeny Morozov at the beginning of _To Save Everything, Click Here, _and Morozov is arguing _against _Johnson. Someone has to be getting Jane Jacobs wrong. Much of this essay is an attempt to see why Morozov gets Jacobs right, while Johnson and others are missing something important.


~ ~ ~


From 2005 to 2007, Evgeny Morozov tells us, he thought that digital technology might be a way to rid the world of autocratic regimes. His disillusionment was channelled into his influential first book, _The Net Delusion_, a full-on attack on "the sheer callousness and utopianism" of the "Internet Freedom" project (p 354).

This time around, Morozov's target is much broader, but still centred in the world of digital technologies, and particularly the Internet. He takes aim at the ideologies that have grown up around the Internet, and their many manifestations.

Chapter 7 is typical of the book. Here is a collection of people who record and track their everyday lives online, and then analyze and quantify their existence, from toothbrushing to reading to fecal contents. These "datasexuals" now have a social movement, of a sort, which they call the "Quantified Self" movement. It would be easy to dismiss the Quantified Selfers as harmless eccentrics if they did not have a significant presence among the opinion shapers and leading lights of Silicon Valley, and if the mindset they embody was not clearly present, if in moderated form, in the wider digital world, and if the assumptions and goals were not oozing out over the rest of us. From quantifying oneself in a private context it is a short step to the presentation of self through these numbers, and the use of them as a basis for optimization and refinement. So Morozov cites Reid Hoffman, founder of LinkedIn, who says that self tracking is a way to "acknowledge that you have bugs, that there's new development to do on yourself" (237) so that we can algorithmically measure, tweak, and refine ourselves and our self-presentation to the world.

From here it is just one more short step to the buying and selling of our personal data: to insurers in return for lower premiums, to advertisers in return for better deals. Our personal data becomes a new "asset class" and executives respond by "trying to shift the focus [of debate] from purely privacy to what we call property rights" (235). New social pressures emerge as the digitizers follow their path of bits, algorithms and markets (career counsellors now routinely recommend that building a strong presence on LinkedIn is a route to a better job), and we can replace debates about privacy with reassurances about personal choice. "Privacy is mostly an illusion, but you'll have as much of it as you want to pay for" says Kevin Kelly (236). New companies emerge to optimize our self-presentation on the web (reputation.com), new norms emerge as "If you're going out with someone, and they don't have a Facebook profile, you should be suspicious" (Slate's Farhad Manjoo, quoted on p. 239). Why would you not share your real-time blood alcohol levels with your employer if you don't have anything to hide? (240).

The impact of the digital on our lives is such that, while the social consequences of self-tracking seem immense, they are just one thread among many of the digital revolution. In separate chapters, Morozov investigates new developments in policing, arts and culture, politics, government, social engineering, civic life, health, the workplace, and the increasingly designed, architected environments in which we live. There is no aspect of life that isn't ready to be tweaked, nudged, hacked and filtered into optimal performance.

How to respond to such a flood of changes? One is tempted to define oneself by an attitude to digital technologies themselves: to be unequivocally pro- or anti-technology. But to reject or to accept technology wholesale has no future: wholesale rejection entails rejection, not just of integrated circuits, but of the people connected by them: shaping the use of technology lies not in the realm of individual choice, but of social choice. Wholesale acceptance seems fatalistic – abandoning the possibility of having any say in the forces shaping the societies in which we live.

Morozov undertakes two projects, one successfully and one less so. The first is to provide a framework in which to think about the new inventions that are being sold to us, and the patterns of thought behind them. Morozov identifies a twin-tracked ideology behind the inventions and inventiveness of the digital world. One track is "Internet-centrism" – the practice of "taking a model of how the Internet works and applying it to other endeavours". Writers have imbued the Internet with "a way of working"; it has a "grain" to which we must adapt; it has a culture, a "way it is meant to be used", and it comes with a mythology in which iTunes and Wikipedia become models to think about the future of politics, and Zynga is a model for civic engagement (15). The second track is "solutionism": the recasting of social situations as problems with definite solutions; processes to be optimized (23).

Morozov does a fine job of articulating Internet-centrism and solutionism as two facets of a single Silicon Valley ideology, whose followers include the Valley's software industry leaders, venture capitalists, conferences and "thought leaders", as an evolution of the "Cyberselfish" ideology identified a decade ago by Paulina Borsook. The common assumptions, shared biases, and individualistic predilictions give a cohesiveness and homogeneity to the new ideas and inventions, actively constructing and shaping the digital environment from which they claim to draw their inspiration. The insistence on "disrupting" our social and environmental lives; the idea that the solutions inspired by and enabled by the Internet mark a clean break from historical patterns, a never-before-seen opportunity – these mean that the only lessons to learn from history are those of previous technological disruptions. The view of society as an institution-free network of autonomous individuals practicing free exchange makes the social sciences, with the exception of economics, irrelevant. What's left is engineering, neuroscience, an understanding of incentives (in the narrowly utilitarian sense): just right for those whose intellectual predispositions are to algorithms, design, and data structures. Morozov argues that these orthodoxies have had "a corrosive effect on public discourse and on reform projects" (16) and it's difficult to argue otherwise.

Morozov's approach to unpicking the hidden assumptions of solutionism, and the unpalatable consequences of its application, is impressive but less successful. In order to avoid a blanket technopessimism he makes two moves. The first is to adopt a broadly social constructionist approach to the world of digital technologies. The Internet does not shape us, it is shaped by the society in which it is growing. He is with Raymond Williams, against Marshall McLuhan. His stance here is blunt: he refuses to see "the Internet" as an agent of change, for good or bad. "The Internet" is not a cause; it does not explain things, it is the thing that needs to be explained. Chapter 2 is titled _The Internet Tells Us Nothing (Because It Doesn't Actually Exist)_.

The second, more surprising move, is to adopt a critique that was first described in a pejorative sense by Albert Hirschmann. "In his influential book _The Rhetoric of Reaction_, Hirschmann argued that all progressive reforms usually attract conservative criticisms that build on one of the following three themes: perversity (whereby the proposed intervention only worsens the problem at hand), futility (whereby the intervention yields no results whatsoever), and jeopardy (whereby the intervention threatens to undermine some previous, hard-earned accomplishment)" (6). Morozov does not see himself as a conservative, but instead places himself in the tradition of other thinkers who have stood against programs of organized efficiency; "Jane Jacobs attacks on the arrogance of urban planning, Michael Oakeshott's rebellion against rationalists in all walks of human existence, Hans Jonas's impatience with the cold comfort of cybernetics; and, more recently, James Scott's concern with how states have forced what he calls 'legibility' on their subjects" (7). The list is an interesting one because, as I mentioned at the beginning, it features the same cast of characters that the solutionists -- those whom Morozov opposes so implacably -- routinely invoke as their own inspirations.

The Hirschmann framework provides Morozov with a recipe for how to think about the many solutionist initiatives he tackles, and many of the passages in the book have a similar structure. Let's return to self-tracking for a moment. Morozov's first line of critique is Hirschmann's "jeopardy": he invokes the 'technostructuralists' to ask not just what individual choices self-tracking offers, but to ask how it changes the environment we inhabit. A decision not to share becomes a tacit acknowledgement that you have something to hide. The danger is that "if you are well and well-off, self-monitoring will only make things better for you. If you are none of these things, the personal prospectus could make your life much more difficult, with higher insurance premiums, fewer discounts, and limited employment prospects" (240). It erodes privacy, the ability to make a clean start, and erodes risk-taking behaviour given the consequences of failure. A second line of critique is to ask what, as our quantifiable aspects become the focus of attention, is missing in the quantified portrait that emerges: what intangible aspects of ourselves become invisible. Do these numbers, he asks, miss meaning? Where do ethics and aesthetics go to in a world of numbers? Morozov surveys the centuries-old debates over the virtues and perils of quantification. Here the critique stumbles, as Morozov rolls out thinker after thinker in a parade of reasons to doubt the benefits of quantification. From Nietzsche to Nussbaum, from nutritionism (the quantification of food) to water-metering and the evolution of clothes-washing norms, to the benefits of friction and dissonance in our everyday lives, there is no doubt he covers an impressive amount of ground, but the argument is scattershot; disjoint. The end result is an erudite and widely-sourced list of the ways in which technologies may lead to bad outcomes – but it is still a list, and it lacks the force of a strong central thesis behind it.

The other chapters follow a similar pattern: the perversity, futility, and jeopardy of solutionist agendas show a breadth of investigation that should shame many of his more populist opponents, and provide valuable contexts in which to think about technological programmes. In particular, his insistence on seeking out historical precedents for today's arguments is a welcome change from the language of "rupture" that many solutionists prefer.

If there is a unified point of view behind the critique, it can be traced back to the "anti-solutionists" with whom Morozov identifies. Like Morozov and like Steven Johnson, I'm a big admirer of Jane Jacobs's _Death and Life of Great American Cities_, and James Scott's _Seeing Like a State_: which makes me wonder how can they end up in such different camps. The fault, you will not be surprised to hear, belongs with the solutionists.

One of the remarkable insights of computer scientists (and social scientists and natural scientists in the computer age) is an understanding of how great complexity and diversity can be generated by populations of simple agents following simple rules. Just as schools of fish and flocks of starlings create sweeping artistic displays by pursuing simple individual rules, so the rich tapestry of city life emerges from simple everyday interactions. The ideas of network theorists lend themselves to talk of self-organization, non-hierarchical structures, and informational cascades. Computer scientists take ideas such as the "Game of Life", the stunning images of fractal shapes, and the rich behaviour of networks to illustrate how complexity arises from simplicity. From spin-glasses in magnets to the sorting and emergence of patterns revealed by Schelling and his intellectual descendants, simple "micromotives" give rise to surprising and intricate patterns of "macrobehaviour". Such agent-based thinking seems at first to mesh perfectly with Jacobs's closely observed studies of city life. She famously focused her piercing, analytical eye on the details of every day life in large cities, and used her observations to challenge and then triumph over the grand visions and arrogance of top-down city planners. It's the bottom-up nature of her approach that inspires: the planners are trying to impose patterns on populations from above but they miss the relationship between the large and the small. It is tempting, then, to take the descriptions of Jacobs's cities and encode them in algorithms: agent-based simulations of the effects of block size on pedestrian traffic patterns seem almost mandated, so obvious a next step do they seem from Jacobs's chapter on the topic.

Yet this step, I increasingly believe, is a mistake. Solutionism is ultimately central planning by another name. The arrogance of the urban planner reappears as the arrogance of the agent-based modeller and the Internet entrepreneur: the plan is still monolithic, but now takes the shape of a network. As Steven Johnson says, when his "peer progressives" see a social problem, they design a peer network to solve it. But what has happened to the citizens in this network? They have been reduced to dumb followers of simple rules. The richness and complexity – all the interest, in fact – lies in the structure of the network. If the outcome isn't what you want, well tweak the incentives, adjust the topology of the network, provide an additional option for the nodes (sorry, people) to choose from. For all its talk of bottom-up, decentralized thinking, the Internet-centric solutionists end up with an impoverished perspective of individual behaviour.

Just because complex and rich behaviours _can_ arise from simple rules doesn't mean that people _are_ simple beings. Any theory that applies both to murmurations of starlings or spin-glasses of magnetic ions as well as to cities of humans is, almost by definition, missing the distinctive features of human societies. Complexity can arise from simplicity at the small scale, but macro-level complexity also arises from micro-level complexity. The subtle and ill-understood nature of our own needs and interactions will defeat the best efforts of solutionist planning, just has it has defeated those of central planning and of free markets.

In his final chapters, Morozov appeals to this particularist view of the world, in which each node of a network is different from others, and in which general solutions don't exist. To discard the importance of the details of our daily interactions, as the solutionists inevitably do, is to inevitably provoke unexpected responses, unintentional side effects, and unanticipated breakdowns of the solutionist schemes. When Brian Chesky of AirBnB [complains](http://skift.com/2013/01/11/airbnb-responds-to-illegal-rentals-story-first-of-all-its-not-illegal-everywhere/) that there are 30,000 different cities in which he wants to operate, and that it's just not practical to negotiate with each one, he is not designing a bottom-up solution, he is imposing a top-down network. He is demanding that cities become "legible" in James Scott's terminology, to his overarching (and simplistic) algorithms.

To reach for an alternative vision, Morozov looks to artists who have engaged in "adversarial design" to illustrate the importance of acknowledging micro-level complexity. But to look to the artificiality of the arts is second-best here; there is enough variation and richness of detail in the normal everyday world to illustrate the importance of variation and local knowledge and unanticipated interactions.

But despite these minor complaints, "Click Here" is an admirable and significant achievement. It identifies and makes a valuable and intellectually adventurous assault on what is becoming an increasingly obvious problem: the appropriation of democratic and "bottom-up" visions by those who seek to impose their own top-down networks on the rest of us, and who reduce us to simplistic nodes in the process. This is a valuable book: now if only someone could make a TED Talk of it.

Written using Org version 7.6 with Emacs version 23.		
