---
author: Tom Slee
categories:
- blog archive
date: 2006-12-29 19:14:20
title: Trackbacks Are Dead
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I hand over a few dollars each month to Six Apart, who own Typepad, for this blog. There are free ones, of course (blogger for one) but when I started off I decided that Trackbacks were worth paying for. If you make a post about an entry on someone's blog, then you can add a trackback, which is a link from their blog post to yours. It looked to me like a valuable part of the conversational aspect of blogs.




But it seems that trackbacks are doomed. I don't think blogger ever supported them. And now many blogs have disabled them, because all you get is trackback spam which is a pain in the neck to deal with. I've noticed that they seem to be going the way of the dodo, and now I see that [Trackbacks Are Dead](http://www.rabidpaladin.com/archive/2006/12/21/Trackbacks-Are-Dead.aspx). It's a shame - one more victim of the plague of spam.




But this little corner of the web is quiet enough I still have trackbacks enabled. 


		
