---
author: Tom Slee
categories:
- blog archive
date: 2005-12-31 23:21:55
title: The Commons Blog
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I have spent some time this afternoon at [The Commons Blog](http://www.commonsblog.org/), subtitled "Markets Protecting the Environment". It is a group blog run by proponents of Free-Market Environmentalism (FME). This is not something that I would expect to agree with, but not a strand of thought I have looked at much, so I read over their "[About Free-Market Environmentalism](http://commonsblog.org/about_freemkt.php)" page and a book review of David Roodman (of the Worldwatch Institute)'s "The Natural Wealth of Nations". 




(the trackback is to the latest post on their blog, because I can't trackback to the home page).




It is not news that, in the search for ways to control environmental damage, one of the routes that is being tried is that of markets. Emissions trading schemes for greenhouse gases and sulphur dioxide are prominent examples. Fine, I say -- whatever works in cutting down pollution. I have no particular axe to grind for or against the use of markets in this way. I imagine they will work well in some cases (easily tracked gases that become widely distributed), and not in others (difficult to track pollutants, or pollutants that are local (such as mercury) for which a market may lead to very polluted "hot spots".




But this is not what FME is about. They argue that using markets "simply as tools for the fficient delivery of environmental goals... [while] the goals themselves remain collectively determined" is simple market socialism. Instead, they want to use markets as a way of "determining what is to be done" as well as how it should be accomplished.




The basic premise is that private ownership provides the incentive needed for conservation: "The record of private owners in conserving resources is superior to that of government agencies". And there are certainly cases of well-preserved or conserved resources that you can find. The beautiful picture on the commons blog front page of the Natural Bridge of Virginia is an example. But a bridge is one thing, and not perhaps typical. To extrapolate these concrete, easily identified objects to "property rights" in such things as dioxins and blue whales is a big step, and not one they convince me can be made. 




Let me give a few reasons why they fail to convince me. 




One issue is that they have a cavalier attitude to the nature of environmental problems. 




  * Resources? "There is little reason to fear running out of oil or mineral resources, for prices will rise well before stocks expire".


  * Sulphur dioxide and acid rain? "But was a sulfur oxide emission reduction plan needed at all? The most
extensive US study of acid rain to date suggests that acid rain was not
a substantial threat to forests and streams, despite environmentalist
claims to the contrary."


  * Climate change? A whole series of articles on the blog suggests that the position of FME is that this too is not much of a problem.



There is a collective action problem to be overcome when it comes to collecting the information on which environmental action is predicated. Groups that help to overcome this problem seem to me to be either government sponsored or to be enthusiasts (bird watchers, for example, who track bird numbers over time) -- neither of which is a market-based approach. So the fact that they are dubious about a whole raft of environmental assessments makes me think that their "leave it to the market" approach to establishing environmental goals -- which ignores this collective action problem -- is not one they are particularly concerned with, because when it comes to it they don't think the problems are that big.




A second reason is an impression that the FME outlook is, in the end, more about
getting rid of government activity than about the environment per se. Their worldview is one in which the only two players are government bureaucracies and markets. And they rule out government point blank: "It was the fatal conceit of socialism, in Hayek's famous phrase, that wise government bureaucrats could guide society to a better future. Substituting red aspirations with green ones does not change the undertaking's essential nature - or its likelihood of success." This leads to odd judgement calls. On the one hand, designing a (Pigouvian) tax code "that fully and accurately internalizes negative environmental externalities (forget the positive) is a fool's errand. It requires "impossibly detailed knowledge". On the other hand, when it comes to establishing property rights "the technical requirements of property rights definition and enforcement are also substantial" - and yet they are optimistic that the market can deal with them, even though they require the same "impossibly detailed knowledge" that the tax approach does.




A third reason that they don't convince me is that their tone is too often smug. They are preaching to the converted. The pervasive use of "government bureaucrats" serves only to emphasize their lack of efficiency. The suggestion that the collapse of the Eastern Bloc demonstrates the failure of any role for the state once and for all ("Central planning has clearly failed.") In the book review (see top of this post) they start off by saying "We are all free-market environmentalists now" before going on to claim that Worldwatch is merely "faux-market". Or categorizing Worldwatch as being "like so many others that mouth adherence to market strategies". Such digs are everywhere, and they don't help.




A fourth reason, they slide by some of the problems of private ownership, while
overestimating the problems of public ownership. It is easy to say that
"behind every tree should stand an owner who can act as its protector"
but you can't really say the same about a salmon that swims thousands
of miles. And while they like to quote Garrett Hardin about the failure
of collective ownership they seem to neglect the well-know fact that
many instances of collective ownership have succeeded well (Elinor
Ostrom and others having catalogued lots of these). And they don't pay
attention to the argument by CW Clarke that it may make perfect
economic sense for a single fishing body to drive whale populations to
extinction even in the absence of a commons.




Finally, they use the passive voice trick a lot to mask some real difficulties with their program. That is, they slip into the passive voice and so obscure just who is meant to be the active role in an activity. I suspect this is not deliberate, but it is revealing anyway. For example: "In a true market system the involuntary imposition of waste streams by one party onto others would be forbidden". By whom? I suspect they know it must be the state, but can't get themselves to say so. The drive (of private industry) to reduce costs results in pollution only "when property rights are insufficiently protected". But who is to do the protection? And when it comes to automobile air pollution "An owner would be assessed a fee proportional to the amout of pollution his auto generated". Who is to assess the fee? and who is to determine the amount of pollution generated?




These slips do suggest that in some ways FME has more overlap with other environmentalists than they would like to admit. Activities such as purchasing of wildlife reserves by the Audubon Society in the USA or compensating farmers to ease the reintroduction of wolves into Montana are apparently part of the free market, but I suspect there are few environmentalists who would argue against them. And to lump the activities of volunteer groups into the "private" realm is itself problematice -- such collective groups are typically neither of the state nor of the market, and the FME attempt to claim them is unfounded. If that's what FME is really arguing for, OK, but it's not that big an intellectual deal.


		
