---
author: Tom Slee
categories:
- blog archive
date: 2007-04-15 22:56:44
title: Infotopia
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[Cass Sunstein](http://en.wikipedia.org/wiki/Cass_Sunstein) is a University of Chicago Law Professor whose book, [Infotopia](http://www.oup.com/us/catalog/general/subject/Law/TechnologyandTelecomsLaw/?view=usa&ci=9780195189285), I got to read on a recent trip. The subtitle is How Many Minds Produce Knowledge and it's all about mechanisms - particularly Internet-driven mechanisms - for combining the insights of many people to produce, as he says, knowledge. It's a good, thought-provoking book and I recommend it.




Here's something I had to struggle with: Sunstein is a big proponent of using prediction markets to make some kinds of decision, and he is very doubtful about the merits of deliberation: sticking people in a room and talking things out to come to a decision. 




My first reaction is that I feel deliberation should be workable, and my first reaction to markets is suspicion - enhanced by the fact that Sunstein comes from the University of Chicago, where the very right-wing Economics and Law movement came from. I don't know Sunstein's politics, but it's clear from the book that his heart is in the right place. He believes in the importance of marginalized people whose opinions and knowledge are too often overlooked, and in the contributions they can make. So is there a case for markets in the situations he's talking about, in the aggregation of knowledge?




Let's think about my hostility to markets. 




Those of a libertarian right-wing outlook see the source of social problems as hierarchy, centralization, planning, bureaucracy, socialism, and the state. Socialists see the source of social problems as the concentration of wealth, privilege, and ownership in the hands of the few.




The dispute spills over into the realm of the mechanisms we look to as bulwarks against oppression.   
Those of us on the left, believing in the ability of wealth to divide and conquer, look to collective action as protection against private ownership of property. It's the old story - hang together or hang separately. Co-operatives, co-operation, unions, solidarity.




Those on the right see collective institutions as bearing the seeds of oppression and coercive suppression of individual liberty. They look to individualistic mechanisms such as property rights and markets as protection. Free exchange respects individual autonomy and liberty - but those of us on the left see the potential for exploitation, the rule of money, and marginalization of those without the price of entrance into the market.




An economic way of phrasing this is that both sides see [principal-agent](http://en.wikipedia.org/wiki/Principal-Agent_problem) problems as a root cause of oppression. The potential for [moral hazard](http://en.wikipedia.org/wiki/Moral_hazard) is there in both collective organizations and in any organization with market power: the temptation to oppress, to deceive, to lie, to mislead are all present. Failures of information ([asymmetric information](http://en.wikipedia.org/wiki/Information_asymmetry) among others) and problems of [transaction costs](http://en.wikipedia.org/wiki/Transaction_costs) are ubiquitous.




In all this, it's worth reflecting on what is central and what is secondary. What matters, after all, is liberty, equality, fraternity (and sorority as well). The questions of markets, voting, democracy, deliberation, are instrumental questions. To some extent we can separate them from the primary problem. My suspicion of and distrust of markets comes from a belief in the alienating effect and excluding effects of turning things that matter into commodities to be bought and sold - particularly in highly unequal societies.




So when it comes to using markets as a deliberation mechanism - including markets using virtual money - then my suspicions may not be relevant. Yes, the proponents of these instruments hark back to Hayek - whose politics I shy from - and his [The Use of Knowledge in Society](http://www.econlib.org/Library/Essays/hykKnw1.html). Does this mean I must object to the use of, say, prediction markets to gain information? A clear-sighted view must say no.




Perhaps, at the same time, it would do me good to question the use of deliberation as a means of making decisions and pooling information. Feminists have long maintained, after all, that marginal groups get excluded from such discussions in a statistical manner, if not an absolute one. 




Reading Infotopia was a great way for me to address these unasked questions because Sunstein himself presents the strengths and weaknesses of both sides of his argument. He may be a lawyer, but he's not in court here, arguing for his client at all costs. The book has a balanced, open-minded approach that is a refreshing change from Some Other Book I've been reading lately. (Or maybe he knows that readers respond to indications of open-mindedness, and he's just a more skilled proponent of his own point of view? Whatever, it works). His equivocation and insistence on making distinctions is welcome. It prompts questions in the reader, rather than diverting the reader past the problems.




So I recommend this book. It'll make you wonder what's happening when you are next with a group of people trying to talk your way to a decision. And it makes me want to look at some prediction market software for use at the workplace.




It does have limitations. The big one is that it's really just a starter. It could do with going a lot further in addressing the uses and limits of the tools he investigates. Markets, for example, seem suited only to questions that have numerical answers (price) or binary answers - but he doesn't mention this limitation or what follows from it. He doesn't distinguish cases where membership in a group is open from where it is closed, or compulsory participation versus voluntary. He briefly mentions a hybrid technique called Delphi, with a mixture of deliberation and voting, but only briefly. There is little about referenda, demand-revealing or otherwise, and little about other forms of voting or methods for achieving consensus in an inclusive fashion. Finally, he does not address the question of learning. Discussion, after all, is not just about decision-making but is also about learning, while markets separate the two. So the reader is left with a lot of open questions at the end of the book. But these would have turned it into a much bigger book too, and right now it's good and short and thought provoking, which is plenty. 


		
