---
author: Tom Slee
categories:
- blog archive
date: 2007-07-28 09:47:03
title: Arms Races
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

There's nothing that isn't obvious here. I'm just so mad I have to post something.




First the Americans [say ](http://news.bbc.co.uk/2/hi/south_asia/6919552.stm)that uranium enrichment is a valid part of a civilian nuclear program, but only for countries it likes. 




If you were Iran, how would you respond to nuclear proliferation among American allies?




Now we hear about a huge arms deal with Saudi Arabia (BBC)[ ](http://news.bbc.co.uk/2/hi/americas/6920458.stm):

<blockquote>**The United States is reported to be preparing a major arms deal with Saudi Arabia worth $20bn (£9.8bn) over the next decade.**
> 
> 

> 
> It is said to be part of a strategy for countering Iran's growing strength.

> 
> </blockquote>




If you were Iran, how would you respond to additional American arms in the middle east?




Of course, the Americans realise that someone in the region is likely to be pissed off when large amounts of arms start rolling off the ships in Saudi Arabia. But they have a plan to deal with that:

<blockquote>To counter objections from Israel, they said, the Jewish state would be offered significantly increased military aid.

> 
> </blockquote>

If you were Iran, how would you respond to increased American military aid to Israel? 




Of course, the Americans realise that other Arab states in the region are likely to be pissed off because the Saudis are being treated as a favourite. But they have a plan to deal with that too:

<blockquote>Other US allies in the region - Bahrain, Kuwait, Oman,
Qatar and the United Arab Emirates - could receive equipment and
weaponry as part of the deal, the officials said.
> 
> </blockquote>

If you were designing a policy to encourage Iran to build nuclear weapons and expand its military capabilities, is there anything that you would do differently? I can't think of anything.


		
