---
author: Tom Slee
categories:
- blog archive
date: 2008-03-07 14:39:26
title: Mr. Google's Guidebook
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Whimsley Hall is now strewn, like Miss Haversham's house, with cobwebs and dust. Most visitors no longer come in by the front door to take a tour. Instead, Mr. Google (a travel agent who doubles as our butler) directs them straight down to the basement where the family archives are kept and tells them to look at one particular historical document called [The Netflix Prize: 300 Days Later](http://whimsley.typepad.com/whimsley/2007/07/the-limitations.html). They  read this and then they walk right out.

I shouldn't complain. It's nice that they visit at all - much better than rattling around here by myself - so I should be very grateful to Mr. Google for bringing these people to visit, but it does leave me wondering why he always sends them to look at this same corner of the house. I have a few other items lying around that I think are just as pretty but Mr. Google takes the visitors right by them without so much as a glance.

So when he brought me the sherry decanter the other day I challenged him on it. I thought it was an innocent enough question to ask of one's butler. Little did I realize the terrifying journey I was embarking on with that one question. He explained that when you ask him a question he "[understands exactly what you mean and gives you back exactly what you want](http://www.google.com/corporate/tech.html)." That sounded a little presumptuous so I asked him how he could be so confident in his understanding and he replied, rather stiffly if you ask me, "If I did not give you exactly what you wanted then you wouldn't have asked me in the first place would you?" There was something about the slow, pronounced way he articulated this that made me feel like Wooster to his Jeeves so I didn't pursue the topic, fearing he would get upset. I wouldn't want him to leave; it's so hard to find good help nowadays.

As I sipped my sherry I realized that I don't really understand the man. For a butler and travel agent he seems remarkably well-to-do, and yet when I ask why he works so hard (I happen to know he is butler at several other houses in the county as well as mine) he insists he is only interested in helping people and points to his family motto, which he keeps on a little card that he brandishes frequently. "[Don't be evil](http://investor.google.com/conduct.html)", it says.

Still, after a few glasses I still felt a little bolshie over Mr. Google's tone and I remembered that some months previous he had actually given me a copy of his biography (he is a most talented individual, I grant). He had told me it was an authorized volume with interviews and selections of his personal correspondence. I hadn't paid much attention to it at the time, but now I took a candle, wandered over to the west wing of Whimsley Hall, and climbed the stone staircase to the very top, where the library is. There I found the biography already lying on a table by the window, which was strange because I had never taken it off the shelf before, and as I sat down to read I realized that it does indeed tell me all about our Mr Google.

Was I surprised! The biography was a revelation. I don't get out often these days (it's the gout) and I am now woefully out of touch, but it turns out that there is more to Mr. Google than I ever dreamed. He is responsible for an astonishingly popular free publication called [Mr. Google's Guidebook](http://www.google.com). It's one of the most remarkable books you'll ever read - if you open it twice you never see quite the same page. In fact the only book I've ever heard of to match it is a limited edition print called "[The Book of Sand](http://en.wikipedia.org/wiki/The_Book_of_Sand)" that my friend Mr. Borges had in his library before he went mad.

Here is how Mr. Google's Guidebook works.

A long time ago, people used signposts to get where they wanted to go. Each signpost was a little underlined phrase in blue that took you to a new place. People would wander all over the place, hopping from one place to another, looking at signposts to see where to go next. These signposts made a sort of map. The complete map of the world is a very big and complicated thing of course, but here is a little piece of it (thanks to [this article](http://www10.org/program/society/yawyl/YouAreWhatYouLink.htm)).












Mr. Google realized that most people don't really want maps, they want guidebooks. And he also realized how he could use those signposts to build a good guidebook. When someone puts up a signpost it shows that they feel this destination is a place worth going to. Mr. Google's Guidebook is very well indexed, so when you look up something like "I would like to visit a peaceful country retreat" it takes you to a page of recommendations. To generate these recommendations Mr. Google counted all the signposts that pointed to peaceful country retreats and pick those retreats that most signposts pointed to. "Here", he would say, "[I recommend](http://www.google.ca/search?q=%22peaceful+country+retreat) you go to Harburn House, or Green Mountain Bed and Breakfast". Mr. Google's Guidebook became something of a sensation. Once it was established, he put in a few advertisements alongside each question and made a pretty penny from it.

As I read further, a storm rose up in the west. The candle flickered as the wind came in through the ill-fitting windows. Maybe this forbidding atmosphere explains why the more I read the more I worried that there might be something a little sinister about our Mr. Google. Mr. Google's Guidebook has become very influential. In fact, I understand he now has a cave somewhere in [view of the mountains](http://www.ci.mtnview.ca.us/) that is full of large and noisy engines, with powerful pistons cranking away to produce new versions every day. That initial guide of his, so clean and tidy, has become a monstrous device like one of those machines designed by [Mr. Goldberg](http://images.google.ca/images?q=rube+goldberg) or [Mr. Robinson](http://images.google.ca/images?q=heath+robinson). He claims that every edition of his guide "[considers more than 500 million variables and 2 billion terms](http://www.google.com/corporate/tech.html)".

It was late at night by the time I read this remarkable fact, and I'd had several more glasses of sherry. A particularly strong gust rattled the window and I stood up to close the shutters. The wind blew the window open and I had to reach out to grab it. It was then that I noticed in the distance a flash of flame and a column of thick black smoke rising in the distance _from right near Mr. Google's cave!_ It looked positively diabolical. I believe I actually cried out in shock.

After a tussle I got the shutters closed and, shaken, returned to my leatherbound armchair and took another sip to calm my nerves. My mind was racing. "Come on Whimsley", I thought, "You're just imagining things". How could there be anything sinister about the Guidebook? I opened a page of the biography at random and it set my mind somewhat at ease. Here is what I read:


<blockquote>At some universities, administrators are taking a new approach to deciding where to put footpaths. At first they don't put footpaths anywhere; they just let students walk across the grass to get where they need to go, wearing away the grass and creating rough tracks as they do so. Then when it is clear where the popular tracks go the university can just tidy them up, put down some paving stones, and they have a path in the right place.
It's called the Wisdom of Crowds. The students decide where the paths go by just going about their everyday life, and the university taps into their preferences to design an environment that reflects exactly what the students would want to do.
That's what we've done here at _Mr. Google's Guidebook_. We track how people walk around, which signposts they follow, and that lets us put paths in the right place, just where you want them to be. We can lead you just where you want to go; lead you to interesting and even unexpected destinations that will provide you with just what you asked for, and more.</blockquote>


Maybe that's all it is then, I thought. Maybe everyone wants to read about the Netflix Prize and no one wants to read [25 essays about the Long Tail](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html). Maybe I've had one moment of startling insight amidst so much dross. But somehow, as my mood plumbed new depths, my brain clung to a stubborn belief that the prettiest thing in Whimsley Hall is an ancient manuscript that sets out, with wit and panache, the [problems with toilets](http://whimsley.typepad.com/whimsley/2006/10/the_state_versu.html). This gem lies in a corner covered with grime and neglected by Mr. Google. How could I possibly explain such gross inequity? Pondering this problem, I fell asleep in the chair and drifted into a strange dream...

_I was standing with my mother in York; one of many visits some years ago. She was pointing to a Chinese take-away restaurant that occupied one narrow division of a long terrace of houses and shops on one of the old streets of that city.
- Look at that, she said, Why is that restaurant right where it is? Why does it go from here to here (gesturing to the edges of the restaurant) rather than some other place?
- I have no idea.
- It's because of the vikings. Over a thousand years ago the land was divided, and then subdivided as it was passed down from father to sons. Each son inherited a narrower strip, so that it had access to the road, and as a result property lines were narrow. Over the years new buildings have been erected until the current use of land has nothing to do with the original, and yet the boundaries remain; archaic, obsolete, and yet fixed. Unless a new motorway comes through they may stay the same way for another thousand years.
- How strange, I commented.
- Not as strange as the egg rolls, she replied...
Then I was in a train, reading a newspaper article about [Alfred Wainwright](http://www.wainwright.org.uk)'s classic hand-written guides to the paths of the Lake District. It explained that, while the routes of footpaths usually evolved over time rendering such guides as Wainwright's obsolete, the very success of Mr. Wainwright's magnificent effort had preserved their relevance. People used the guides to follow the paths, cementing the routes in place for much longer than would have been the case without them._

I awoke with a start. What an odd thing to remember. Why now? My mother is in fine fettle - no worries there. And Wainwright's Guides? I hadn't thought of them in years. It must be something else that produced that dream. And then I realized, it was all about Mr. Google's Guidebook. I struck my forehead, blinded by this insight, and rushed to the table. Picking up the quill pen, I dipped it in the ink and began to write feverishly on the pad of paper lying there...


<blockquote>Mr. Google is lying! (I wrote) His Guidebook no longer reflects the paths set out by travellers as they navigate their lives. It is no longer an outside observer of people's wanderings. Google's success has changed the way people find their routes. Here is the way it happens. When a new cluster of destinations is built there may be a flurry of interest, with new signposts being erected pointing towards one or another of those competing locations. And those signposts have their own dynamics, perhaps forming a power law as [set out by Mr. Shirky](http://www.shirky.com/writings/powerlaw_weblog.html) or perhaps something different, as [Mr. Shalizi has explained](http://en.scientificcommons.org/22568192). But that's not the end of the story. After some initial burst, no one makes new signposts to this cluster of destinations any more. And no one uses the old signposts to select which particular destination to visit. Instead everyone uses Mr. Google's Guidebook. It becomes the major determinant of the way people travel; no longer a guide to an existing geography it now shapes the geography itself, becoming the most powerful force of all in many parts of the land.

So my Netflix Prize essay got selected by Mr. Google's machines as one of the more interesting and insightful commentaries - the machines are perceptive, we must grant them that - and it soon appeared as number 3 on the list of recommended destinations for anyone looking for "[Netflix Prize](http://www.google.ca/search?q=netflix+prize)", right after the official site itself. And now no one is guided here by those few original links - the relevance of their effect is as vestigial as the effect of the Vikings' property rules. Mr. Google's Guidebook has cemented the verdict in place long after the early discussion has lost its relevance, like the edges of the Chinese take-away and like Mr. Wainwright's guides fixed the routes of the paths he charted. With little new being written about the Netflix Prize the Guidebook is the major source of new journeys. And so the Guidebook changes the pattern of the landscape from a rich, linked one with its power law shape (or other shape). Instead, there is a two stage process in the evolution of much of the landscape. The first stage is a brief discussion, from which Mr. Google picks a few winners. In the second stage, after that discussion has faded away, the continuing popularity of the winners is assured simply by their positioning in the Guidebook. Mr. Google has singlehandedly changed the way people travel, changing the selection of destinations from an ongoing referendum to a brief discussion from which he anoints a few winners.Mr. Google no longer gives you what you want, he selects a winner from the crowd and then tells you it's what you wanted.</blockquote>


I was just about to put down the pen, exhausted now, when I heard a creak and the door to the library opened. I lurched around to see coming through the door --- Mr. Google himself! His face was no longer subservient as befits a butler. Instead it was smirking. And his teeth - surely they had not been so pointed before. I shrank.

But Mr. Google did not attack me with a knife, or bite me in the neck. Nothing so dramatic. He simply looked over at my scribbled notes and sighed a world-weary sigh.
- You don't understand do you sir?
- What do you mean Google? I understand everything now.
- Really? This document here? And what does that matter if no one reads it? And who decides whether anyone can come here to view it? Exactly how do you propose to publicize your absurd opinions if not through me?

My shoulders sagged. Defeat. Of course, there was nothing I could do. "So you'll silence it then. Keep people away. My revelations will moulder, along with [that masterpiece about the toilets](http://whimsley.typepad.com/whimsley/2006/10/the_state_versu.html)".

- No (said Google). That's what I mean - you really don't understand. You see, I don't care if people come and look at these hen scratches or not. Maybe they will, maybe they won't. As long as I can sell a few advertisements on that page of my guidebook I really don't care. After all, what better praise for a Guidebook than to help people find out what's wrong with it? Just leave your manuscript with me. I'll look after it.

He held out his hand, imperious now. I felt disheveled after my long night. My brain was spinning. I could see no alternative. In a vain attempt to maintain some self-respect I drew myself up to my full height and pulled back my shoulders, adopting a bearing appropriate for my class. "All right Google. Here you go. Don't lose it now."

"Thank you sir. You can be sure I won't lose it. I never do lose anything you know."

I turned away from him and stumbled down the stairs. I had ended up giving him an order, and he had accepted it. Yet I could not shake the impression, even as he brought me a glass of sherry that evening in my sitting room, placing the silver tray beside me with deference, that Mr. Google - far from being a butler and travel guide - was more a master than a servant.






		
