---
author: Tom Slee
categories:
- blog archive
date: 2010-10-07 22:53:37
title: The Waki World of Macrowikinomics
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_Macrowikinomics_ is the new book from Don Tapscott and Anthony D. Williams, authors of 2007's "best-selling management book in the United States" _Wikinomics_. It [proclaims](http://www.businessweek.com/managing/content/sep2010/ca20100928_230402.htm) the end of the industrial mode of production, that "centralized, one-way, one-size-fits-all mass model controlled by the powerful owners of production and society". The authors tell us that "The world is broken and the industrial economy and many of its industries and organizations have finally run out of gas".


But "don't look to big government or big corporations to supply the answers." The way forward is Internet-driven mass collaboration, [for example](http://www.huffingtonpost.com/don-tapscott/macrowikinomics-rebooting_b_741466.html) "ordinary people everywhere are connecting to create a mass movement that is bringing greater awareness and sense of community to the process of making household and business decisions that can reduce our carbon footprints."


It's all relentlessly populist and anti-establishment, so there is something wackily wonderful about this list of endorsers on [the book's web site](http://www.macrowikinomics.com/about/praise-for-macrowikinomics/).


  * CEO of Dell Inc

  * President and CEO of Transparency International-USA

  * Professor at the University of Michigan

  * Chairman and CEO of ONEX

  * CEO of Intergroup Financial Services Corporation, Peru

  * Chief Scientist, BT Group PLC

  * Executive Vice President, Scotia Capital

  * Executive Vice President, Best Buy

  * CIO, Procter & Gamble

  * CEO, Celestica

  * Co-CEO, SAP (and now my boss)

  * Vice President, Yale University

  * Chairman, Spencer Trask & Company

  * CEO, Juniper Networks

  * President EMEA, Dupont,

  * CEO, SAS Institute

  * Chairman and CEO, OgilvyOne

  * President and CEO, Business for Social Responsibility

  * CEO, Swift

  * CEO, Google

  * CEO, Heidrick & Struggles

  * Chairman and CEO, Manpower

  * Founder and Executive Chairman, World Economic Forum

  * CEO, Best Buy

  * Chairman and CEO, Accenture

  * CEO, Nike


Now if there's one thing that pisses me off, it's people who don the mantle of rebellion and anti-corporate populism while promoting the commercialization of our public sphere and the commodification of our private lives, and I suspect that's exactly what is going on here.


MacroWikinomics has received a lot of publicity, so I'm off to [the local bookshop](http://www.wordsworthbooks.com/) to get a copy tomorrow, and if it lives down to my expectations then watch this space for a page-by-page_ Macrocritical Reader's Companion to Macrowikinomics, _the long-delayed_
_sequel to my [Critical Reader's Companion to the Long Tail](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html) from a couple of years ago.


		
