---
author: Tom Slee
categories:
- blog archive
date: 2007-04-27 14:39:56
title: Good Guys or Bad Guys in Afghanistan? It Makes Little Difference
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Following revelations that Afghans captured by Canadian troops have been tortured by the Afghan police and intelligence forces, Globe and Mail columnists [Christie Blatchford](http://www.theglobeandmail.com/opinions/columnists/Christie+Blatchford.html) and [Margaret Wente](http://www.theglobeandmail.com/opinions/columnists/Margaret+Wente.html) rushed to defend the troops in separate columns last Tuesday.




Canadian soldiers in Afghanistan, they say, are fine people. Blatchford writes that Canadian soldiers "treat their Afghan prisoners fairly and indeed often with gentleness." Wente writes that "I have deep sympathy for our military leaders, who genuinely want to do the right thing". 




But these good guys are in a bad place. Blatchford says "Afghan justice is rough justice at best. This is a country steeped in decades of war and violence and vengeance" and Wente says "Nothing could be less surprising than the revelation that the Afghan secret police practise routine torture".




The problem is the Afghans themselves. Blatchford says that "not all of those who were detained and handed over by Canadians were merely mild-mannered farmers unfairly caught up while they tended their crops" and Wente says that "abuse of Afghan prisoners by Afghans" is "regrettable, but what else can you expect?"




The idea that most people caught up in a war are innately good or innately bad is a destructive idea. A few are heroes, a few take to corruption and power like a duck to water, and most of us, as in all walks of life, muddle along trying to do the right thing, compromised by our own lack of courage. The tragic fact is that in war people of all stripes do terrible things, and it doesn't matter a damn what their personal morals are. There is no difference between shot by a bad guy and being shot by [shot by a good guy](http://www.cbc.ca/world/story/2006/08/26/afghanistan.html#skip300x250) in a bad situation. The recent death of Kurt Vonnegut, haunted by the allied bombing of Dresden where he was a prisoner of war, is a reminder of that.




Wente and others who support this war sympathise with Canadians who can't tell a good Afghan from a bad Afghan, but fail to sympathise with Afghans who don't distinguish torturers from the troops who capture them and hand them over. They sympathise with individual Canadians stuck in a violent war but damn individual Afghans stuck in the same war. Wente writes " The question is not whether we can help them build a fair and just society. The question is whether they want one." and it is this dismissive attitude to Afghans - blaming individual Afghans for their collective misery while absolving individual Canadians of crimes carried out in their name - that will lead down the road to [war crimes](http://www.time.com/time/magazine/article/0,9171,1174682,00.html) being committed by "our side" if they haven't been already. 




The virus of mistrust and prejudice caused by years of brutality and conflict affects everyone, and it is wrong to think it is something specific about individual Afghans (or Germans, or Americans) that produces such brutality. The further immersed in the war Canada becomes the more we will see cases of Canadian brutality too. That's what war does.


		
