---
author: Tom Slee
categories:
- blog archive
date: 2007-02-27 19:44:50
title: 'agblosticism: my little gift to the world of words'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

We interrupt this series of long posts to point out that my "about" page ([Whimsley: Not a Blogger](http://whimsley.typepad.com/whimsley/2006/03/not_a_blogger.html)) is _the only place on the entire Internet_ where you can read the word "agblosticism", meaning "scepticism about blogging".

<blockquote>While blogging is not exactly like real life, it is a bit closer to
it than the book thing: if you aim to gain an audience you have to pick
up on what other bloggers are writing about and respond within hours.
So really, blogging just isn't my thing. The arguments go nowhere, no
one changes their mind, and the signal/noise ratio is very low. The
blogging world is a world built for quick-typing extroverts who don't
go in too much for second thoughts.

> 
>   
And there is more to my **agblosticism** ...
> 
> </blockquote>

If you're a blogger, how about using it on your own site? It's not trademarked or anything.




  




		
