---
author: Tom Slee
categories:
- blog archive
date: 2011-08-12 22:39:09
title: So You Think You Can Tweet
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

It's confession time.




I try to put on a countercultural, intellectual persona here, but the truth is that I'm a fan of reality TV - some of it, anyway. In particular, despite having two left feet and being completely the wrong demographic, I adore _So You Think You Can Dance_ (the US version; the judges ruin the Canadian version -- take it up in the comments if you want to fight that one). Season 8 finished yesterday, with the brilliant Melanie Moore winning over the equally brilliant Sasha Mallory, and I'll miss my weekly fix for the rest of the summer. Here's two minutes of why I love it.







There. Don't you feel better?




I know I'm getting sold a packaged bill of goods by a mega corp, but it works because even the best efforts of Gatorade and other sponsors, and the sometimes high cheese factor, cannot smother the heart of the show, which is that a lot of very talented young folks work really hard, put their heart and soul into what they do, and produce some great routines. Plus, Cat Deeley is adorable.




Anyway, one thing many people do after watching shows like this is see what others are saying on various forums and so on about the performances. And I do the same. It's not just me either - there is a trend for TV shows and the Internet to be jointly marketed (Jeff Probst tweets along with Survivor episodes as they broadcast) and as computers move out of the study (if you have one) and into the living room (hello iPad), it's only going to get bigger. A lot bigger.




Jenny Davis at [Cyborgology](http://thesocietypages.org/cyborgology/2011/07/19/new-twitter-records) tells us that the biggest twitter volumes ever recorded were at the end of the Women's World Cup final last month. _Glee_ fans are apparently big at using social media while watching, according to [ReadWriteWeb](http://www.readwriteweb.com/archives/what_glee_means_for_twitter_television.php). Yahoo! [claims](http://www.futureofmediaevents.com/2011/01/26/study-86-of-people-use-mobile-devices-while-watching-tv/)! that! over!80% of! TV! watchers! use a mobile device while watching. The Beeb [chimes in](http://www.bbc.co.uk/news/technology-12809388) with the same kind of numbers. For the TV companies, a big benefit is that social media makes audiences watch the show when it's on, rather than timeshifting it to skip the ads and watch a more convenient time.




It's time to get to my point, which is that the standard story of how we have moved from the old world of mass media TV to the fragmented new worlds of the Internet is misleading. It's quite possible that the Internet will end up complementing mass media, rather than competing with it.




I'll post more about this mistake later, but I'll save you that for now and instead give you what's probably the best known routine for any SYTYCD fan, the Tim Burton-esque Ramalama. Enjoy.











		
