---
author: Tom Slee
categories:
- blog archive
date: 2008-05-03 10:04:35
title: Paying for Linux
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

**Last week on 'Linux Goes Corporate': **After [Nick Carr](http://www.roughtype.com/archives/2008/04/open_source_as_1.php) mentioned [my post](http://whimsley.typepad.com/whimsley/2008/04/linux-grows-up.html) on the [Linux Foundation report](http://www.linux-foundation.org/publications/linuxkerneldevelopment.php) and on Linux as corporate joint venture, [Timothy Lee](http://techdirt.com/articles/20080423/082724929.shtml) and [Ed Cone/Clay Shirky](http://blogs.cioinsight.com/knowitall/content001/decoding_the_professionalization_of_linux.html) responded and then [Doc Searls](http://www.linuxjournal.com/content/linux-now-slave-corporate-masters) put in his two cents worth. The main point of the responses is that the shift from hobbyists to professionals is not important. For example:  





"the open source model is about organization, not who signs your paycheck" (Lee).




"the idea that the minute you pay people to do something, you have the right to manage them and the right to completely take over that work for the benefit of the company -- that's not true" (Shirky). 




"in all the conversations I've had over the years with kernel
developers, none has ever copped to obeying commands from corporate
overlords to bias kernel development in favor of the company's own
commercial ambitions. In fact, I've only heard stories to the contrary" (Searls).




* * *




The professionalization of Linux matters because it marks a change. Open source now is not the same as ten years ago when [The Cathedral and the Bazaar](http://www.firstmonday.org/issues/issue3_3/raymond/) was written.




Despite the historical revisionism of the "paycheck's don't matter" crowd, the absence of paychecks certainly mattered ten years ago. Eric Raymond opened his [classic essay](http://www.firstmonday.org/issues/issue3_3/raymond/) with these sentences:

<blockquote>"
Linux is subversive. Who would have thought even five years ago that
a world-class operating system could coalesce as if by magic out of
part-time hacking by several thousand developers scattered all over
the planet, connected only by the tenuous strands of the Internet?"
> 
> </blockquote>

Ten years on what stands up? "several thousand developers scattered all over the planet" does - the number of participants in the Linux kernel is larger than ever. But the Linux kernel now is not developed by "part-time hacking". And Linux is no longer subversive, in that anything IBM is happy about is not, by definition, subversive.




And it mattered six years ago when Yochai Benkler wrote "Coase's Penguin: Linux and the Nature of the Firm", which contains this statement:

<blockquote>Programmers do not generally participate in a project because someone who is their boss instructed them, though some do. They do not generally participate in a project because someone offers them a price, though some participants do focus on long-term appropriation through money-oriented activities, like consulting or service contracts. 
> 
> </blockquote>

So now programmers do participate in the Linux kernel because their boss instructed them to (or paid them to). 




Now I can imagine people saying that just because the Linux programmers are paid, that doesn't make their motivation financial and that doesn't mean companies can tell them what to do. Here is Lee:

<blockquote>What makes the open source model unique isn't who (if anyone) signs the
contributors' paychecks. Rather, what matters is the way open source
projects are organized internally. In a traditional software project,
there's a project manager who decides what features the product will
have and allocates employees to work on various features.
> 
> </blockquote>

This is a caricature. I work in a commercial, closed-source software company, and my job is very close to that of a project manager. But what an expert programmer spends his or her time on is always a negotiated thing. Partly it's a matter of skill and expertise (who is best placed to identify algorithms or code-level weaknesses and areas for improvement?), partly it's a matter of "what needs to be done" and partly it's a matter of innovation. And as Joel Coehoorn [says](http://techdirt.com/article.php?sid=20080423/082724929#c13) in a comment to Lee's post, "there most definitely are project managers for open source projects. I
can't think of a single successful open source project that doesn't
have a well-defined road map for features." Open source believers too often portray paid closed-source programmers as wage slaves, and paid open-source programmers as free agents working for love (to scratch an itch) who just happen to collect a paycheque. It's a dichotomy that just doesn't hold up.




Shirky argues that "the idea that the minute you pay people to do something, you have the right to manage them...that's not true" but this statement applies to the employees where I work just as much as to IBM employees working on the Linux kernel, and there is nothing about the Linux kernel that gives Redhat programmers a special "ignore the boss" license. Shirky says that "If [a senior manager] announced a strategic change in the kernel they would be laughed out of the room" as if senior managers routinely dictate strategic changes in the Windows kernel or database kernels. More senior managers get laughed out of the room than Shirky would believe.

* * *




This leaves us with ownership. IBM and Redhat do not own and will never own Linux. But Redhat sells Linux, and the ability to sell something is one component of ownership. The distinction is more one of exclusive ownership. And here the Visa analogy I used originally holds up - Visa is now a separate company but it is also a collaborative venture and companies that helped to build it were simultaneously assisting their competitors. Industrial sponsorship of academic research - an activity the pharmaceutical industry relies on - has the same tensions about ownership and organization and direction. 




Open source, like any new phenomenon, is changing. Our understanding of it has to change too. The Linux Foundation report prompts us to re-examine some of the neat and clean dichotomies that were floated around ten years ago and see if they still hold water. A few do, but many don't.


		
