---
author: Tom Slee
categories:
- blog archive
date: 2006-04-14 21:58:40
title: Five Things I Don't Believe...
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

  1. That global warming is a big deal. It's because of listening to the radio in the mid '70's and hearing all those stories from experts about how there wouldn't be any oil in 1990. They made sense at the time, global warming makes sense now. But I don't really believe it.


  2. That open source software is new and different. What puts me off is the hype about the whole Cathedral and Bazaar, Coase's Penguin, Sand Pile & Power Laws, Economics of Networks, and Long Tail thing. It's all what I think of as "Wired Thinking" (after the magazine) -- it's not entirely without merit, and it's not completely stupid, but it has no sense of history and so it's not nearly as smart or original or new as it thinks it is. Speaking of which....


  3. That quantum computing will ever amount to anything. Anything that features the word "entanglement" so prominently is more new age than physics. The EPR thought experiments were dreamed up 70 years ago. Nothing interesting came out of them in the first 60, so why should anything interesting come out of them now? This is a field driven by its cool-sounding name (remember "quantum chaos" anyone?), and it's just possible enough that it could be important, complicated enough that it can be portrayed as cutting edge to likely patrons and smart-but-impressionable graduate students, and far enough out to be not easily disproved. Speaking of which...


  4. That nanotechnology is new. Come on people, it's just chemistry and engineering. All that talk of "self-assembly" is just a new word for "chemical reaction" but it sounds oh-so-edgy. Get over it.


  5. That the world is flat (in the Thomas Friedman sense of the world). This one really should not need saying. It's clearly a case of what Daniel Davies calls ["globollocks"](http://crookedtimber.org/2004/01/16/globollocks-v20) but it seems to be taken as obviously true by a big section of the business community. 'Nuff said.


  6. (Because no one expects the Spanish Inquisition). That whole idea of memes. Yes, I enjoyed Dawkin's Selfish Gene, Dennett's Consciousness Explained and Blackmore's [Consciousness, An Introduction](http://www.amazon.com/gp/product/019515343X/104-9068415-9157531?v=glance&n=283155). But I just don't see what the idea of a meme adds to any discussion about anything at all. Really.



Why do I think I'm entering the "grumpy old bastard" phase of my life? Anyone else got any things they don't believe?


		
