---
author: Tom Slee
categories:
- blog archive
date: 2006-03-19 16:55:47
title: Not a Blogger
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I started this weblog because of the book, thinking that now it is going to be published I might as well do it right, and that means creating a little extra material around it if I can. It (the weblog) has now hobbling along for four months, with a post or two a week (mainly on weekends).




I've learned that I am not a natural blogger, which is why I changed the title text to emphasize that this is "an _occasional_ weblog...". I simply don't have that much to say, and even though I would not call myself busy by many people's standards, I don't always have the time to post something when I do think of something to say, or to find the article that prompted my thought again. There are plenty of weblogs out there which are updated multiple times a day. Such people are some combination of (a) well organized, (b) brilliant, or (c) egotistical. Let's just say there's a mix, and leave it at that.




There is a mismatch between blogging and other kinds of writing anyway. I wrote a book because it is a quiet occupation that suits me. It is a way of arguing without be ingdistracted by other people -- and other people, let's face it, usually just get in the way of a well-thought out argument. Plus, it is a way of avoiding the hurly-burly of actual debate where you have to think on your feet and assert positions you are uncertain of. While blogging is not exactly like real life, it is a bit closer to it than the book thing: if you aim to gain an audience you have to pick up on what other bloggers are writing about and respond within hours. So really, blogging just isn't my thing. The arguments go nowehere, no one changes their mind, and the signal/noise ratio is very low. The blogging world is a world built for quick-typing extroverts who don't go in too much for second thoughts. 




And there is more to my agblosticism. With a book, you have to get a stamp of approval before
inflicting your thoughts on readers (in the form of a publishing
contract), so there is something un-egotistical about a book: "I'm not the one claiming that my scribblings are worth reading, someone else thinks they are too". But with a blog, or other intermediary-free publishing mechanism, there is something about the effort -- "Here Are My Thoughts, Listen To Them!" -- that is presumptious, almost distasteful. I've decided, though, that (with some exceptions) this impression of presumptiousness is wrong. I am not claiming that I have Thoughts You Should Know, I'm just keeping some writing here in this little corner where few people will look and using it as a place to keep my stuff. And if I end up wasting a few minutes of your time because you googled a combination of words that led you here instead of somewhere more useful, well I'm sorry, but perhaps you should try a library instead of Google anyway. 




So, to go back a couple of paragraphs, I have learned that I am not a natural blogger. Nevertheless, I'll carry on with this effort. There are benefits, even without an audience (although hello there EAS, JC, and JAS, if you are still around). It is a useful place to keep some notes. It is a useful discipline to occasionally try to articulate thoughts that otherwise would remain even more foggy. I've heard from two people that I had lost touch with (hello PJM and MC) [which reminds me, I owe you both an e-mail]. And I still hope it will help to accumulate some additional material that may be of use to readers of my book, which is what this is all about. 




But my advice to readers of this weblog is "don't expect anything and you won't be too disappointed".


		
