---
author: Tom Slee
categories:
- blog archive
date: 2006-12-24 10:35:07
title: 'Heckling from the Cheap Seats: Jeremy Rifkin is Wrong About Cities'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Jeremy Rifkin is not a modest man. He entitles his books things like "Entropy: A New World View" and "Biosphere Politics: A New Consciousness for a New Century". I stopped reading his books after "The End of Work", which was very sloppy and so obviously wrong.




But here he is again, in today's Toronto Star, arguing that the global movement into cities is responsible for the population boom. 




The first sentence is typical Rifkin. Then he gets worse. Rifkin is completely, 180 degrees, wrong.




Link: [TheStar.com - opinion - The risks of too much city in a crowded world](http://www.thestar.com/opinion/article/164832).


<blockquote>The coming year marks a great milestone in the human saga, a development similar in magnitude to the agricultural era and the Industrial Revolution. For the first time in history, a majority of human beings will be living in vast urban areas, many in megacities and suburban extensions with populations of 10 million or more, according to the United Nations.

> 
> 

> 
> We have become "Homo Urbanus." ...
> 
> 

> 
> It's no accident that as we celebrate the urbanization of the world, we are quickly approaching another historic watershed: the disappearance of the wild.  
Rising population; growing consumption of food, water and building materials; expanding road and rail transport and urban sprawl continue to encroach on the remaining wild, pushing it to extinction. Scientists tell us that within the lifetime of today's children, the wild will disappear from the face of the Earth...
> 
> 

> 
> I don't want to spoil the party, but perhaps the commemoration of the urbanization of the human race in 2007 might be an opportunity to rethink the way we live. Certainly there is much to applaud about urban life: its rich cultural diversity and social intercourse and its dense commercial activity.
> 
> 

> 
> 

> 
> But the question is one of magnitude and scale. 
> 
> 

> 
> We need to ponder how best to lower our population and develop sustainable urban environments that use energy and resources more efficiently, are less polluting and better designed to foster human-scale living arrangements. 
> 
> </blockquote>

But increasing urbanization is the best hope for cutting the population boom. If you live a rural existence, children are a source of prosperity: you need children to work, to support you, and so on. If you live an urban existence, children are a financial burden. That's why there is no population boom (quite the opposite, in fact) in industrialized countries. His examples - Chicago and New York - are not from a country that has a booming population. Japan's population (without the bonus of immigration) may shrink by 30% in the next few decades.




It's not that urbanization is all good, but to link it to the population boom is completely wrong.  




		
