---
author: Tom Slee
categories:
- blog archive
date: 2006-05-22 21:25:34
title: Blood and Money
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[Stumbling and Mumbling](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2006/05/incentives_in_t.html) often points me to things I didn't know. A few days ago he pointed to this:

<blockquote>if you treat everyone as if they were motivated by money alone, you might drive out these higher motives and worsen management-labour relations. There's some evidence that this happens in blood donations; if you pay people to give blood, some stop giving. 
> 
> </blockquote>




And links to a [paper](http://bmj.bmjjournals.com/cgi/content/full/312/7039/1131?ijkey=d0a8aa3ae571d7f28f11aa8c7339db4d5a4d050c&keytype2=tf_ipsecsha) by some Kiwi researchers that shows it can happen. People donate blood for a variety of reasons, but part of it is because we want to be the kind of person who does their civic duty. If you pay people to donate blood, they no longer get this kind of boost. As a result, some people who previously gave blood no longer do. It makes sense, but the idea that paying people to do something makes them stop doing it takes some getting used to.




The original suggestion was made by [RIchard Titmuss](http://en.wikipedia.org/wiki/Titmuss%2C_Richard) in 1970, but it was met by what some [Swedish researchers](http://www.ne.su.se/research/enter/pdf/johannesson.pdf) refer to (presumably overly-generously) as "skepticism", including rebuttals by two Nobel prize winners (Arrow, Solow).




And yet it looks like Titmuss was right and Arrow and Solow wrong. There have been some recent theoretical studies on it too ([Benabou and Tirole](http://ideas.repec.org/p/iza/izadps/dp1695.html)). The reasoning is similar to the work by Akerlof and Kranton that is the subject of Chapter 11.


		
