---
title: "Advance MAID requests: we need to talk about the day of death"
subtitle: Will Advance MAID requests bring the relief that people are looking for?
# description: >
abstract: >
  The Province of Quebec has recently created procedures that allow advance requests
  for assisted dying. But do they really?
  I sent this to the Globe and Mail as an opinion piece, but they decided not to publish
  it so I thought I'd save it here. It was a response to [a Globe and Mail article](https://www.theglobeandmail.com/canada/article-quebec-maid-advance-request-law/) and followed a short exchange on the Letters page.
abstract-title: ""
author: 
  - name: "Tom Slee"
    url: https://tomslee.github.io
    email: tom@tomslee.net
title-block-banner: true
date: last-modified
date-format: long
published-title: Last updated
categories:
- Essays
- MAID
appendix-style: none
toc: true
toc-depth: 1
toc-title: Contents
knitr:
  opts_chunk:
    out.width: "100%"
number-sections: false
number-depth: 1
callout-appearance: default
execute: 
  freeze: auto
format:
  html:
    html-math-method: katex
    # css: styles.css
    anchor-sections: true
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true
    citation-location: document
    toc-location: left
    lightbox: true
  pdf: 
    documentclass: scrartcl
    papersize: letter
    toc: false
    number-sections: false
    colorlinks: true
    output-file: "algorithmic_pricing_draft"
    output-ext:  "pdf"
    mainfont: "CharterBT-Roman"
    fontsize: 12pt
    linestretch: 1.1
    keep-tex: true
    template-partials:
    - ../title.tex
    geometry:
    - top=30mm
    - left=30mm
    - heightrounded
    include-in-header:
      text: |
        \definecolor{TealHeading}{RGB}{27, 158, 119}
        \newfontfamily\sectionfont[Color=TealHeading]{RobotoCondensed-Regular}
        \newfontfamily\subsectionfont[Color=TealHeading]{RobotoCondensed-Regular}
        \newfontfamily\subsubsectionfont[Color=TealHeading]{RobotoCondensed-Regular}
        \addtokomafont{section}{\sectionfont}
        \addtokomafont{subsection}{\subsectionfont}
        \addtokomafont{subsubsection}{\subsubsectionfont}
        \usepackage{mdframed}
# pdf-font: "ETbb"
# editor: visual
---

Some years ago my mother told my sister: “My greatest fear is losing my mind. If that happens you’re to give me poison and I’ll drink it.” Still, Mum died in March of this year at the age of 93, after several grim years clouded by dementia, so I share the impulse behind [Quebec’s decision to allow “advance requests for assisted dying”](https://www.quebec.ca/en/health/health-system-and-services/end-of-life-care/medical-aid-in-dying/advance-request-medical-aid-dying) and sympathize with the woman in this [Globe and Mail article](https://www.theglobeandmail.com/canada/article-quebec-maid-advance-request-law/).

And yet… if we are to allow advance requests, we need to talk about how those requests will be executed, and to date that public discussion has not happened. To be specific: given the chance, many dementia sufferers will refuse and resist an attempt to end their life, regardless of what requests they signed in the past. What happens then?

If refusal at the point of death is respected, then the new Quebec law is a mere mirage, offering a promise of relief that it cannot deliver. This seems to be what happened in the Netherlands, where advance requests have been legal since 2002 but where a [2011 study](https://pubmed.ncbi.nlm.nih.gov/21649621/) found that “Advance directives for euthanasia are never adhered to in the Netherlands in the case of people with advanced dementia, and their role in advance care planning and end-of-life care of people with advanced dementia is limited.” Such an outcome helps nobody.

If advance requests are to serve a useful purpose, refusal and resistance at the time of death will have to be either overruled or bypassed. Perhaps someone (who?) will sedate or hold down the patient, for medical personnel to administer the final dose. Or perhaps medical staff will avoid the problem by not telling the patient what is being done: “it’s just something to make you feel better.”

Neither of these paths is “assisted dying”. “Assistance” implies the assent of the dying person at the time it happens. Perhaps we are OK with this change. Perhaps we agree that the person making an advance request is the one best placed to represent the interests of their future self, and that the dementia sufferer is no longer competent to change their mind. But if so we should at least say so and not turn “assisted dying” into a euphemism for something else. Instead, we should spell out what that “something else” is.

There are other thorny questions. Anyone who has witnessed a pet being put down knows what a profound and intense experience that can be, and it’s not uncommon for minds to change at the last minute. Witnessing the death of a human loved one would be another level of distress. Faced with the last moments of a drugged or resisting loved one, even someone who has agreed to a relative’s advance request may change their mind. Do they have an option to object? Remembering my mother, it is easy to imagine why one might: “Yesterday she brightened up when she saw me, so she knows who I am sometimes”, “We sat together yesterday and held hands, she was happy. Isn’t that enough?” Similar difficult decisions already exist around “do not resuscitate” orders, but if I put myself in the two positions, they seem to be of a different order.

How and when and by whom death is delivered are not administrative details to be sorted out in regulation: the moment of dying is and must remain at the heart of the matter, and that’s why public discussion must confront it. I don’t have the answers; I hope others do. Watching my mother lose herself was heartbreaking. An advance request would have made the experience different for me and, more importantly, for her. If the right framework could be found, I might make an advance request myself in case dementia comes for me too, but as the Quebec law stands I don’t know what I would be signing up for.

## Links

-   [Government of Quebec page on Advance Request for Medical Aid in Dying](https://www.quebec.ca/en/health/health-system-and-services/end-of-life-care/medical-aid-in-dying/advance-request-medical-aid-dying)
-   [Montreal Gazette Explainer](https://montrealgazette.com/news/quebec/explainer-a-look-at-advance-requests-for-maid-in-quebec) (October 30, 2024)
-   [Globe and Mail article](https://www.theglobeandmail.com/canada/article-quebec-maid-advance-request-law/)
-   [Dying with Dignity](https://www.dyingwithdignity.ca/blog/pr_advance_requests/)
-   [Advance requests for MAiD in dementia](https://www.semanticscholar.org/paper/Advance-requests-for-MAiD-in-dementia%3A-Policy-from-Byram-Wiebe/5625a502153a6aefcd2405793a88b1f5b1780dde): Policy recommendations emerging from a mixed-methods study of the views of the Canadian public and MAiD practitioners.
