---
author: Tom Slee
categories:
- blog archive
date: 2006-07-27 21:26:16
title: bytech is a discerning individual
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Doing one of my periodic googles for the book title, I came across this post by one "bytech" on a webmasters' forum. Obviously a Manitoban of taste and insight.




<blockquote><blockquote>Quote:
Originally Posted by blind2web:
>> 
>> 

>> 
>> "Nobody forces American or British companies to move to low cost countries; these decisions are made in Britain and America by Britains and Americans. "
>> 
>> </blockquote>
> 
> bytech says: "While I agree with you, there is a hook to this. I discovered it after reading "No One Makes You Shop At Wal-Mart". It put a whole new meaning to the word "choice"... I'd recommend the book to almost anyone. You'll see your life from there-on in a whole new way."
> 
> </blockquote>

Thank you bytech! 




Link: [Indian Webmasters - Page 2 - Webmaster Forum](http://www.v7n.com/forums/forum-lobby/33924-indian-webmasters-2.html).


		
