---
author: Tom Slee
categories:
- blog archive
date: 2007-03-05 21:45:21
title: The Long Tail 6 - The New Markets
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is another part of my critical reader's companion to _The Long Tail_, and it discusses Chapter 6 - The New Markets. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/the_long_tail/index.html). You have to read upwards, in usual blog fashion. When I get to the end I hope to put these all together in one big file for download.  


* * *

Bored of this yet? Well that's just too bad, because this blog is nothing but The Long Tail until I've gone through the whole thing, repetition and tedium be damned. So if you don't like that, come back in about three or four weeks if things go according to plan.




Still here? Great. Glad to have you. It is time to cast your mind back and recall that Chapter 4 spelled out the Three Forces of the Long Tail and that Chapter 5 was about the first one: Production. Chapter 6, today's subject, is about the second force: distribution. And whereas Chapter 5 was bolted on to the side of the Long Tail hypothesis, Chapter 6 is right in the middle of it. It's about Internet aggregators, in particular Amazon, and how they go about filling their long shelves.




The first section of the chapter is one of the more interesting stories in the book. It's about the success, at the third attempt, of [Alibris](http://www.alibris.com/), a company that seeks to "deliver the growing power of e-commerce to independent booksellers while delivering extraordinary selection to businesses and book lovers" (from the Alibris web site). The used book market (other than university textbooks) is fine if you are a browser hoping to stumble across a quirky find, but problematic for people looking for a particular book because there are "not enough sellers and buyers of an unbounded set of commodities" [87]. As a result, the odds of finding your book are slim. "Thus, most buyers simply never consider a used-book store when they're shopping for something specific" [87].




Alibris takes the inventory of used book stores, gathers them together, and puts this big database online, making it available to Amazon and other online outlets such as bn.com, where used books appear alongside new books when customers search for a book. The result is a fast-growing used-book industry (11% in the US in 2004) [88]. This story shows what the Internet is good at: bringing unconnected people together. It sounds like, and maybe is, a hopeful story, "creating a liquid market where there was an illiquid market before" [88]. (Aside - it is odd that Anderson talks about the American Alibris and completely neglects its [bigger](http://technology.guardian.co.uk/online/howto/story/0,,1433850,00.html) Canadian competitor [Abebooks](http://www.abebooks.com), who now own the fine [librarything](http://www.librarything.com) web site, but perhaps he is subject to the tyranny of geography in the physical world).




It is likely that a move to used book buying and selling is a pretty diverse market compared to new books, but it may be of interest to note that the Alibris founder [says](http://www.ioba.org/newsletter/archive/v13/tb1.php), in discussing a new Alibris pricing initiative that " It's true that the Alibris Pricing Service really is oriented mainly around common books - but that's more than 80% of the demand out there, so it tackles the vast majority of the market". Alibris is a private company and does not make its detailed sales figures available, so it is difficult to know for sure. But used books are one of those areas where the Long Tail hypothesis has the strongest ring of truth.




Enter the Aggregators [88-89] picks up from the Alibris example and uses it as an example of a "Long Tail 'aggregator' - a company or service that collects a huge variety of goods and makes them available and easy to find" [88]. And the Alibris story shows that there are ways in which the Internet can pull people together. But while aggregation can be a fine thing, it does have a dark side, and that side is market power. Canny aggregators know this. Alibris, for example, does not put its customers in touch with the used book stores that actually sell the books. Instead, the book store owner sends their book to Alibris, who then sends it on to the customer. In this way, Alibris becomes the hub of the market: the central repository of knowledge, while the individual book stores who it relies on are [kept in the dark](http://booksellingonlineblog.com/2006/03/15/alibris-makes-me-gag-again/). This appears to have led to some [resentment](http://palimpsest.stanford.edu/byform/mailing-lists/exlibris/1999/11/msg00135.html) amongst some librarians and book store owners, although I have no idea how widespread this is.




What this means is that online aggregators become the new powerhouse in the industries they move into. Amazon in the world of new books, Abebooks and Alibris in the world of used books, and so on. Google, of course, is seeking to aggregate everything and so become the hub for "the world's information". 




This is a mixed development for those whose information is being aggregated. Newspapers, for example, are [not thrilled](http://blogs.guardian.co.uk/technology/archives/2007/02/13/google_news_loses_belgian_newspaper_case.html) at the idea of [Google News](http://news.google.com) presenting their information freely to the world, while the newspapers themselves struggle over lost income. With Google making scads of advertising money off presenting information to people, it looks like the balance of power has shifted from the content originators to aggregators.




Aggregators are here to stay. What remains to be seen, however, is if they bring with them any real move towards a more diverse pattern of demand and consumption.




So aggregators are the Long Tail enterprises that represent "the future of business", and Anderson says "there are literally thousands of them" [88]. Are we now going to hear about the wave of the future, and see what shape it is taking?




No. Frustratingly, the only examples he lists after that teasing sentence are our old friends Google, Rhapsody, iTunes, Netflix and eBay -- the same handful of companies he's been going on about in the first few chapters. He does also mention Bloglines, an RSS feed aggregator, and Wikipedia, which I've argued is not an "aggregator of the Long Tail of knowledge" but those are the only ones of those "literally thousands" that he actually lists.




What he means by his "literally thousands" becomes clear when he says that "a single blog that collects all the information that it can about a topic, let's say needlework, is an aggregator" [89]. Well, if this is where his "literally thousands" of aggregators are coming from, count me underwhelmed. Amazon is one thing, and someone collecting links on needlework is another. I mean, Wal-Mart puts things on shelves and I put things on shelves, but that doesn't make me the same kind of thing as Wal-Mart. And although he mentioned needlework or "SEC filings or techno music" he does not actually list real sites. The wave of the future, it seems, is still intangible.




Anderson does tease us again by claiming that "in this chapter, I'll focus on the business aggregators. They fall mostly into five categories:




  1. Physical goods (eg Amazon, eBay)


  2. Digital goods (eg iTunes, iFilm)


  3. Advertising/services (eg Google, Craigslist)


  4. Information (eg Google, Wikipedia)


  5. Communities/user-created content (eg MySpace, Bloglines)" [89]



The rest of the chapter, however, is devoted to a discussion of just one aggregator -- Amazon (again!) with occasional mentions of old chums Netflix and Rhapsody. The fact that we are a third of the way into the book and, when it comes to specifics, Anderson keeps going back to the well to show us Amazon or Netflix one more time suggests that he is a little short of real examples, and that perhaps the aggregator model, while a powerful one for some people, is not something that is going to spawn large numbers of companies. 




We've already seen (earlier chapters) that while Amazon does make more money off its "Long Tail" than individual brick and mortar stores, its figures are not spectacularly different after the downward revision between the original article and the published book, and that Rhapsody seems just as hit-dependent as HMV. When it comes down to it, we have here a short, limited list of examples which we've already seen provide little evidence for a significant Long Tail effect.




Hybrid versus Pure Digital [89-91] This section is devoted to a single rather obvious idea, which is that while it's pretty cheap to sell physical goods from digital shelves ("hybrid retailer"), it's even cheaper to sell digital goods from digital shelves ("pure digital retailer") because such a good is just a row in a database table until someone orders it. This latter form of business is, he says "the holy grail of retail - near-zero marginal costs of manufacturing and distribution" [91]. Here, he actually mentions (unlike in the previous chapter) that it is marginal cost that is being minimized. He does not go on to point out that the industries with large fixed costs and tiny marginal costs tend to form oligopolies, but they do. It's the main reason why there really aren't "literally thousands" of aggregators and it's why he has to go back to the same old examples over and over again. Fixed costs and other forms of increasing returns mean that there just aren't that many of them.




Tripping Down the Tail [91-94] is also about Amazon (yawn), and shows how it is getting "closer and closer to breaking the tyranny of the shelf entirely" [94] by introducing Amazon Marketplace - a program in which the Amazon web site is a storefront for many small vendors (rather like eBay). "Retailers and distributors of any size, from specialty shops to individuals, could have their goods listed on Amazon.com just like the products in Amazon's own warehouses - and the customers could buy either just as easily." [93]




Amazon Marketplace shows the real appeal of the aggregator business model, and it's not about Long Tail, it's about One Big Virtual Tent (see yesterday's post). Why? Because the Amazon Marketplace model gets Amazon itself out of the physical shelf business, even though as Anderson writes, apparently without noticing the implications (he really is an incurable optimist) "With the Amazon Marketplace form of distributed inventory, the products are still on shelves around the country, but they are collectively catalogued and offered in one central place - Amazon's Web site. Then, when people order them, the products are boxed up and shipped directly to the customer by the small merchants who have held the inventory all along" [94 - my emphasis] and if the goods don't sell "Amazon bears none of the cost -- the surplus stock simply depreciates on the shelves of a third party" [94]. 




It is easy to see why this is a great deal for Amazon: they are using their market power to put the squeeze on the individual retailers whose very physical shelves are holding very physical products. Like Alibris, Amazon have [put measures in place](http://www.bookthink.com/0086/86web.htm) to prevent customers and sellers communicating directly. They are the ones in charge of this relationship.




So Amazon Marketplace is yet another story with at most a tenuous relationship to the Long Tail thesis. It provides Amazon with another source of revenue, but it is not clear if or how it moves overall customer demand to a Long Tail in any significant way. Sales of small items are gravy for a site with the huge web site resources of Amazon, but Anderson does not say how much business has been done on Amazon Marketplace, whether the small suppliers (for whom it is one more outlet) are gaining or losing overall from any move online that has happened, and so on. If, for example, there is a move to online purchase of the kind of goods found on Amazon Marketplace, then it could make sense for individual retailers to put their items there (because any sale is better than no sale) and yet be worse off than they were before Internet selling came along. It's just shoddy writing. And it doesn't get better.




Inventory on Demand [94-96] is yet more Amazon smoke and mirrors. By this time it is really getting silly. Anderson talks about Amazon's big commitment to print on demand publishing as a way of selling all those niche books. But while he notes that "the potential of print-on-demand is extraordinary" [96] he doesn't give any real-world numbers. How many print-on-demand books does Amazon sell? Not a clue. Will it help publishers get past the problem of returns from physical stores or does POD have its own problems? Who knows? Not Anderson, that's for sure. And then at the very end of the section he says that print-on-demand may also be useful for big sellers (hits) as well as niche products, so it may not actually "push demand down the long tail" at all. Remarkable.




The End of Inventory Altogether [96-97] is the final section of this chapter. It finally moves away from Amazon to talk about iTunes, Netflix and other pure-digital outlets as the wave of the future - which we have already seen are pretty hit-based. There is no doubt that the digital world is getting bigger, but this is not news. I for one am no cellulose sentimentalist and can't wait for flexible [electronic](http://www.engadget.com/2007/01/05/plastic-logic-to-build-first-electronic-paper-plant/) [paper](http://www.engadget.com/2007/01/16/toshiba-matsushita-electronic-paper-alternative-hits-mass-produc/), but when it gets here I hope there is something more solid than The Long Tail to read on it.




So there we are. Another chapter, another lack of real substance to Anderson's thesis. It is clear that there is money to be made by aggregators, but not at all clear that the coming of the aggregators is the coming of "infinite choice" [180].


		
