---
author: Tom Slee
categories:
- blog archive
date: 2011-08-14 22:01:44
title: As TV goes online, the Internet becomes more like TV
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

As I said in my _So You Think You Can Dance_ [confession](http://whimsley.typepad.com/whimsley/2011/08/so-you-think-you-can-tweet.html), it's quite possible that the Internet will end up complementing mass media, rather than competing with it. It turns out this is a current topic.




At _Rough Type_, Nick Carr rounds up some recent evidence, including a Nielsen report showing that American TV viewing per person is at an all-time high:




<blockquote>

> 
> A year ago, the Nielsen Company reported that Americans' TV viewing hit an all-time record high in the first quarter of 2010, with the average person spending 158 hours and 25 minutes a month in front of the idiot box.[*](http://www.roughtype.com/archives/2010/08/charlie_bit_my.php) That record didn't last long. Nielsen has released a new media-usage report, and it shows that in the first quarter of 2011, the average American watched TV for 158 hours and 47 minutes a month, up another 0.2 percent and, once again, a new all-time high.[*](http://www.nielsen.com/content/dam/corporate/us/en/reports-downloads/2011-Reports/nielsen-cross-platform-report-q1-2011.pdf) Twenty years into the Web revolution, and we're boob-tubier than ever.
> 
> 
</blockquote>




... and more, [here](http://www.roughtype.com/archives/2011/08/cognitive_surpl.php).




Meanwhile, in the mainstream press, the _Globe and Mail_'s [John Doyle](http://www.theglobeandmail.com/news/arts/television/john-doyle/is-network-tv-dying-hardly/article2127799/page1/) has been to Beverley Hills to listen to TV execs talk about their line-ups, and they are surprisingly cheery about the state of the biz. A decade ago, according to NBC's Robert Greenblatt, “there was a sense that it’s a declining business, and let’s just sort of manage the decline and hope we can get the best out of it.” Now, things are looking up. Here's CBS chief of research David Poltrack, echoing some of what Nick Carr reports (emphasis is mine):




<blockquote>

> 
> "As this century opened, the focus of the world was on the Internet, and the focus of the television industry was on the DVR. At that time, the business of prognostication was booming, and no one was too optimistic about the future of the broadcast networks. Yet here we stand 11 years later, and the business of network television is alive and well. That doesn’t mean that the entertainment market has not been transformed by the new technologies. It has. **What the pundits got wrong was not the impact of the new technologies but the alleged vulnerability of the television networks. ... As the broadcasters and the cable networks move more content online, the viewers’ online video diet has included more and more episodes of television programs.**
> 
> 

> 
> “It would be no surprise to find, for the first time, a significant number of viewers reporting that they’re watching more television than last year. The fact is, the viewer’s perception of television viewing is program- or content-driven, not distribution-driven. Whether they are watching their favourite program on their computer, their tablet or their smartphone, they consider themselves to be watching television. So contrary to the expectations of the pundits, **the explosion of new sources of video distribution has actually fortified the market for the broadcast networks’ content**.”
> 
> 
</blockquote>




A couple of years ago Cosma Shalizi said this about search: "If your search process _succeeds_ in aggregating what large numbers of people think, it will mostly reproduce established, mainstream cultural hierarchies, _by definition_." (link now rotten - no, [fixed](http://www.stat.cmu.edu/~cshalizi/350/lectures/03/03.pdf)) The same goes for social media as a whole.




Along the same lines, it is perhaps not surprising to see that Wikipedia is, like other institutions, [male dominated](http://www1.umn.edu/news/news-releases/2011/UR_CONTENT_350252.html) with less than 10% of edits made by women. The full paper, from the University of Wisconsin, is [here](http://grouplens.org/system/files/wp-gender-wikisym2011.pdf).




For me, what comes out of these observations is not that the Internet is retrograde -- despite my posts, I do try not to be an old fogy when it comes to technological changes --but that it is best viewed as a site of contention rather than as an actor in the continuing struggle over the future shape of society.


		
