---
author: Tom Slee
categories:
- blog archive
date: 2007-03-15 00:49:36
title: The Long Tail 9.1 - The Short Head Part 1
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is another part of my critical reader's companion to _The Long Tail_, and it discusses the first half of Chapter 9 - The Short Head. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html).

* * *

Before I start, a tip of the hat to Aaron Swartz for his [kind review](http://www.aaronsw.com/weblog/nobodyshops) of No One Makes You Shop at Wal-Mart - even if he does think my politics are odd - and for pointing to this series of posts on Chris Anderson's The Long Tail. And welcome to all those readers who have followed the link. Hope you can stick around - I'm going to be posting two or three things a week until I get to the end of the book, which will probably take a week or two.




The first half of this chapter compares shelves with online stores in a little more detail than earlier chapters, looking at "the virtues of shelves and their costs" [147] as well as the benefits of "the Internet, where niche economics rule" [166]. The second half (coming later this week) looks at how you find things. Let's get to it.




The introductory section puts forward an idea that hits and niches can be complementary. The Long Tail is not against hits. Hits, it says, will always play an important role: they "serve as a source of common culture around which more narrowly targeted markets can form" [148]. Anderson goes on: "Successful Long Tail aggregators need to have both hits and niches. They need to span the full range of variety, from the broadest appeal to the narrowest, to be able to make the connections that can illuminate a path down the Long Tail that makes sense for everyone" [148].




"Long Tail" here has two separate meanings, not well distinguished. One is cultural - the claim that we are moving from "mass markets into millions of niches" [12]. The second is a more narrow business meaning - that you can build a successful online business if you do what Amazon has done so well. The book rarely mentions when it is moving back and forth between these meanings, but it's worth remembering that they are not the same thing at all. We might get successful Long Tail businesses but not a Long Tail culture if online aggregators drive sources of variety out of business.




Let's stick with the narrow business meaning for now. Pages 148-149 document the failure of one of the early online music ventures, MP3.com, because it had only niche music. "The reason MP3.com's model didn't succeed and the iTunes model -- which is less oriented towards independent musicians - did is that iTunes began by making deals with major record labels, which gave it a critical mass of mainstream music. Then it added more and more niche content, as "rights aggregators" [not sure what that means - TS] shipped it hard drives full of hundreds of thousands of independent musicians [presumably their songs, not the musicians themselves - TS]. Thus, iTunes customers were able to dive into an already working market where the categories were defined by known commercial acts, which served as a natural leaping off point for the discover of niche music". [149]




There is an assumption by this stage in the book that iTunes is a "Long Tail aggregator". But is it? iTunes is mentioned on 30 separate occasions in the book, but the only actual figures about their sales are the following:




  * "Apple said that every one of the then 1 million tracks in iTunes had sold at least once" [8]


  * "As of early 2006, Apple had sold 42 million iPods and 1 billion tracks on iTunes" [175]



And that's it. This deserves to be emphasized. The book never demonstrates that iTunes is a "Long Tail aggregator", so its repeated references to iTunes' ability to (for example) "democratize distribution"[57 - table] and drive demand down the Long Tail are nowhere backed up. 




iTunes has a lot of stuff, but does it sell it?




With Apple's own figures being -- like so many others on which the thesis of the book relies -- secret, I can only stand on the outside and listen to those who claim to know. Here's what I could find.   
We already saw in the [notes to Chapter 7](http://whimsley.typepad.com/whimsley/2007/03/the_new_tastema.html) that, according to the Wall Street Journal, iTunes is a hits-driven business: "Every day, the roughly one million people who visit the iTunes Store home page are presented with several dozen albums, TV shows and movie downloads to consider buying -- out of the four million such goods the Apple site offers. This prime promotion is analogous to a CD being displayed at the checkout stands of all 940 Best Buy stores or featured on the front page of Target's ad circular."   
As I quoted in the [notes to the Introduction](http://whimsley.typepad.com/whimsley/2007/02/youll_be_very_g.html), Lee Gomes [wrote](http://online.wsj.com/public/article/SB115387606762117314-Inp5lUxHwVDwS_SJv5zaQShPXlE_20070726.html) that "At Apple's iTunes, one person who has seen the data -- which Apple doesn't disclose -- said sales "closely track Billboard. It's a hits business. The data tend to refute 'The Long Tail.' " One of the things about infinite shelves is that there's no harm in saying "sure, bring in those hard drives with all those songs. Throw them on the shelf." That doesn't mean they get sold.  
Another claim, although also circumstantial, that iTunes is just as hit driven as physical stores was [reported](http://technology.guardian.co.uk/weekly/story/0,,1851309,00.html) in the Guardian in August 2006:

<blockquote>At a recent debate hosted by digital music consultancy firm MusicAlly, eMusic's chief executive David Pakman came up with a startling claim. He said that 10% of product on iTunes accounts for 90% of the store's total sales. Rather than smashing the 80/20 rule, the world's most popular download store appeared to be exacerbating it.
> 
> </blockquote>

He goes on to say:

<blockquote>"For the most part, stores that are stocked with music from the majors tend to focus on mainstream music," he says. "It doesn't mean they don't carry a more diverse selection, but when you have Beyonce and the Pussycat Dolls you put them on the home page, and you market and promote that and use it on your advertising. By definition, that tends to attract youth and mainstream music buyers. They come to your site looking for the hits."
> 
> </blockquote>

As a competitor who focuses on niche music, Pakman has a vested interest in pointing fingers at Apple. This should make us treat his statement with caution, but it also reminds us that we should be suspicious of the vested interests on the other side - those CEO's who blurb Anderson's books and who are looking to promote their businesses as revolutionary and shiny new. It is interesting to note that Pakman and his eMusic does believe in the Long Tail, but with a different slant from the one Anderson is giving it in these pages:

<blockquote>Consequently, 70% of eMusic's catalogue sells more than once every quarter. It sells 5m tracks a month, from a subscriber base of only 200,000 users. "Our observation is that the Long Tail does exist," says Pakman, "but it doesn't happen naturally. You have to focus on selling it, almost at the expense of promoting the popular stuff."
> 
> </blockquote>

iTunes' hits might be "a natural leaping off point for the discover of niche music", but there is little evidence that people are making the jump.

The Urban Tail [149-151] is one of those odd sections Anderson puts in from time to time where he wanders off to almost unrelated topics, seeing power laws everywhere. This doesn't have much to do with the remainder of the book. Here it's cities. "Another sort of 'hit' is major cities" [149] he says, pointing out that the distribution of city populations follows a power law distribution over many orders of magnitude. This is well known, of course. "In a sense, you can think of cities as the Long Tail of urban space in the same way the Internet is the Long Tail of idea space or cultural space" [150]. Hmmm. Not sure I know what that sentence means, but I'm sure it doesn't add to the basic thesis of the book, so I'll move on.

In Defense of Shelves [151-152] has a clear purpose. "Before we bury the shelf, let us first praise it" [151]. It provides some lovely little facts about just how detailed our knowledge of shelf space and how it works is. A nice couple of pages.

Rent by the Half Inch [152-154] starts the attempt to bury the shelf. And shelves do have their problems. Despite everything it's pretty expensive to stock things on shelves, and you can only put an item in one place - a contrast to the digital world, where you can find this very page you are reading by searching for any number of the distinctive and elegant turns of phrase that grace its pixels. This section is a lead-in to the substance of the argument, so there's not much more to say except to point out that Anderson here does his usual trick of comparing the digital world to only the most hit-driven part of the physical world and presenting the comparison as if it was a complete comparison of physical and digital worlds: "Today, the average cost of carrying a single DVD in a movie rental store is $22 a year. Only the most popular titles rent often enough to make that back (there's a reason why they call it 'Blockbuster')." It is likely, of course, that any independent video store (hello [Generation](http://www.genxvideo.com/) [X](http://imprint.uwaterloo.ca/mambo/index.php?option=com_content&task=view&id=144&Itemid=56&issuedate=2006-09-22)) will have cheaper rent than a Blockbuster and so is more likely to stock minority interest content.

The Wal-Mart Effect [154-156], named after the excellent [Charles Fishman book](http://www.walmarteffectbook.com/), continues this slanted comparison by focusing on the company with more shelves than anyone else in the world, and looking at its CD aisle. Wal-Mart stocks about 4,500 unique CD titles, as was noted in Chapter 1, compared to 800,000 for Amazon [155]. As Anderson points out, "Wal-Mart, which accounts for about one-fifth of all music sales in America, is by far the nation's largest music retailer" [155]. "Today, the number of large independent music stores like the one I worked at has dropped dramatically, the classical music listening room is now an endangered species. There are, needless to say, few import aisles left" [155]. 




There is no doubt that Wal-Mart's efforts have directly cut into the diversity of music available on those physical shelves. A [2004 article](http://www.rollingstone.com/news/story/6558540/walmart_wants_10_cds) in Rolling Stone by Warren Cohen charts Wal-Mart's growth and impact: "Unlike a typical Tower store, which stocks 60,000 titles, an average Wal-Mart carries about 5,000 CDs". (Tower has apparently gone bust since then - I'm writing from outside the US, so American readers please excuse my unfamiliarity with Tower). Even some well known albums are missing, Cohen points out in the same article: "At a Wal-Mart Supercenter in Thorton, Colorado, for example, there were no copies of the Rolling Stones' _Exile on Main Street_ or __Nirvana's _Nevermind_.__" Anderson makes a similar point, describing a walk he took around a Wal-Mart in Oakland, where "There are no copies of the Rolling Stones' Exile on Main Street or Nirvana's Nevermind". Oops! I guess Mr. Anderson has been reading Rolling Stone. Should have given Mr. Cohen some credit there.




But enough with the scurrilous suggestions - I do have a serious point to make about this section and it's about that old Wal-Mart/digital comparison. Way back in Chapter 1 Anderson compared Wal-Mart's 4500 CDs (60,000 tracks, he estimated) to Rhapsody, where "Not only is every one of Rhapsody's top 60,000 tracks streamed at least once each month, but the same is true for its top 100,000, top 200,000, and top 400,000 -- even its top 600,000, top 900,000, and beyond" [22]. The listing of increasing hundreds of thousands of tracks is clearly intended to contrast the paucity of choices available on Main Street with the digital Nirvana. It's an intent made even clearer in his diagram on page 23 where he categorizes stuff you can't buy at Wal-Mart as "Products you can't find anywhere but online". But this description is false. The Rolling Stone article suggests that a specialist music store would stock 60,000 titles which, at the same tracks per CD ratio used by Anderson, is 800,000 tracks. Rhapsody's selling is not, perhaps, so niche driven or abundant as we would think.




The big point about The Long Tail is a cultural one, and the moral of the story according to Anderson is that we are moving away from a world of hits to a world of niche interests. But that's not the story this comparison tells. Instead, the story is of a retail model with a fair amount of effective diversity (the specialist record store) being squeezed in a technology-driven vice. One jaw of the vice is the technology-driven Wal-Mart, which uses its IT expertise and economies of scale along with other strategies to take the hits away from the specialists, driving them out of business. The other jaw is the online stores, which also benefit from economies of scale and are left to mop up any demand for diversity that is left, because it is no longer attainable in the physical world. 




From what we can tell, iTunes is doing a poor job of selling niche products and, as the Guardian [quotes](http://technology.guardian.co.uk/weekly/story/0,,1851309,00.html) Greg Eden, general manager of the trade organisation for the UK's independent music sector: 

<blockquote>unlike the high street, online distribution means one supplier can dominate the mass market. "What you see on the internet is very much the 'Highlander Theory'," says Eden. "'There can be only one'. There's only one search engine, there's only one big book retailer, one big online auction house, and so on. . 
> 
> </blockquote>

The driving force of technology is not having effect Anderson would like it to have. There may be ways of generating more demand for out-of-the-mainstream tastes and a challenging, diverse culture, but Wal-Mart + iTunes isn't it.




Next time, the second half of Chapter 9, which turns the topic to finding things on shelves.


		
