---
author: Tom Slee
categories:
- blog archive
date: 2007-04-13 10:34:00
title: 'Starting Non-Fiction Books With Stories: Give it a Break'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I'm tired of the way so many business and cultural books start with a story. It was cute for a while, but I've had enough. It's time for a change.




Here are the beginnings of ten books - not one of which is a novel. Aren't they stupifying in their sameness after the first two or three? (Can you identify them? - Number 5 is a giveaway.)

  1. <blockquote>Don Verrilli might as well have uncorked the champagne bottle right then and there on the marble steps of the Supreme Court -- the case he was about to argue was a slam dunk. It was late March 2005 and Verrilli must have felt like he was on top of the world.
> 
> </blockquote>



  2. <blockquote>No one ever gave me directions like this on a golf course before: "Aim at either Microsoft or IBM". I was standing on the first tee at the KGA golf club in downtown Bangalore, in southern India, when my playing partner pointed at two shiny glass-and-steel buildings off in the distance, just behind the first green.
> 
> </blockquote>



  3. <blockquote>It was late in the afternoon, on a typically harsh Canadian winter day, as Rob McEwen, the CEO of Goldcorp Inc., stood at the head of the boardroom table confronting a room full of senior geologists.
> 
> </blockquote>



  4. <blockquote>In 1988, a British mountain climber named Joe Simpson wrote a book called Touching the Void, a harrowing account of near death in the Peruvian Andes. It got good reviews but, only a modest success, it was soon forgotten. Then, a decade later, a strange thing happened. Jon Krakauer wrote Into Thin Air, another book about a mountain-climbing tragedy, which became a publishing sensation. Suddenly Touching the Void started to sell again.
> 
> </blockquote>



  5. <blockquote>For Hush Puppies - the classic American brushed-suede shoes with the lightweight crepe sole -- the Tipping Point came somewhere between late 1994 and early 1995. The brand had been all but dead until that point. Sales were down to 30,000 pairs a year, mostly to backwoods outlets and small-town family stores. Wolverine, the company that makes Hush Puppies, was thinking about phasing out the shoes that made them famous. But then something strange happened.
> 
> </blockquote>



  6. <blockquote>About six years ago, I went to the Gap to buy a pair of jeans. I tend to wear my jeans until they're falling apart, so it had been quite a while since my last purchase. A nice young salesperson walked up to me and asked if she could help.
> 
> </blockquote>



  7. <blockquote>One day in the fall of 1906, the British scientist Francis Galton left his home in the town of Plymouth and headed for a country fair. Galton was eighty-five years old and beginning to feel his age, but he was still brimming with the curiosity that had won him renown -- and notoriety -- for his work on statistics and the science of heredity. And on that particular day, what Galton was curious about was livestock.
> 
> </blockquote>



  8. <blockquote>Croesus, King of Lydia, was considered the richest man of his time. To this day Romance languages use the expression "rich as Croesus" to describe a person of excessive wealth. He was said to to be visited by Solon, the Greek legislator known for his dignity, reserve, upright morals, humility, wisdom, intelligence, and courage. Solon did not display the smallest surprise at the wealth and splendour surrounding his host, nor the tiniest admiration for their owner.
> 
> </blockquote>



  9. <blockquote>Early on the morning of April 8, 1994, the electrician arrived to start work on a new security system being installed at an upscale home overlooking Lake Washington, just north of Seattle. In the greenhouse, he found the owner of the cottage, Kurt Cobain, lying dead on the floor in a pool of blood.
> 
> </blockquote>



  10. <blockquote>J-20. For those in the know the acronym is easily decipherable: July 20, 2001, the call for action transmitted to hundreds of thousands at the click of a mouse. J-20 - Genoa.
> 
> </blockquote>




Its not only become predictable to start books this way, it's patronizing.




First, the story is obviously a setup, selected precisely so that it illustrates the point the author wants to make, so we're being led down a path here. It has the effect of making me suspicious - it's misdirection: what's up the author's sleeve?




Second: it says to the reader "this is going to be an easy read: don't worry, you won't have to think too hard". Yet almost all these books claim to have important things to say (and a few of them actually do). Do we need this dressing up, this dose of sugar? I don't think so. Get to the point please - if you have one. The idea that profound truths can be identified and transmitted without effort is seductive, but misleading.




Finally, when some of these books have business leaders saying "this book is deep and really influenced us" then you have to wonder about what their idea of deep thinking is.




It's not that I think obscurity and dull prose are the mark of a serious book (or is it?) but this "who moved my cheese?" approach to avoiding proper thinking is a horrible trend.




Here's a great way to start a non-fiction book. I'm cheating - it's from the beginning of Chapter 2 - but Chapter 1 is a kind of preface so I think it qualifies:

<blockquote>Streets in cities serve many purposes besides carrying vehicles, and city sidewalks - the pedestrian parts of streets - serve many purposes besides carrying pedestrians.
> 
> </blockquote>

It's unfamiliar - who thinks about sidewalks and what they do? And what could these other purposes be? So it immediately raises questions in the mind of the reader, prompting active thought and questioning - rather than a comfortable, cocooning "Let me tell you a story" beginning.




Want more? A recent [discussion at Crooked Timber](http://crookedtimber.org/2007/02/19/the-challenge-of-affluence/) lists many academic examples.




No prizes for guessing the most titles from those above - not even spare chocolate eggs - but I'd be interested if anyone can recognize some.


		
