---
author: Tom Slee
categories:
- blog archive
date: 2006-10-06 18:53:57
title: 'Scholarships: Enough With the Leadership Thing'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

For family reasons I've been looking at university scholarships. There
are those that you get if you have a certain average, and then there
are others that you have to apply for and which usually involve a
mixture of scholarship and "other stuff". And that "other stuff" is
almost always defined as "leadership". Like the Lo Family scholarship
at the University of Toronto
(http://www.adm.utoronto.ca/awd/scholarships.htm#UTscholars):

<blockquote>"Awarded to students who are active as leaders, are respected and considered to be well-rounded citizens in their
school and community..."
> 
> </blockquote>

Or at Queen's University, the D & R Sobey Atlantic Scholarship requires
"Academic excellence, proven leadership and involvement in school or
community activities."
(http://www.queensu.ca/registrar/awards/apply/apply-scholar.html). You
get the idea. Of course there are exceptions (like the lovely John
Macara (Barrister) award at U of T: "Preference given to
applicants who can establish that they are the blood kin of the late
Mrs. Jean Glasgow, the donor of this award.") but most of the time it's
all about the leadership.




Now
I have nothing against leaders -- all successful groups need someone to
take credit for their accomplishments -- but this focus on
leadership to the exclusion of all else is a crock. Apart from
being ill-defined, it does a pretty good job of saying to those 17 and
18 year olds out there that there's only one kind of admirable person
in the world, and that's those who join lots of things, play sports
(preferably as captain or quarterback), and Get Involved. Do we really
want a world full of the parentally-pushed, self-important,
power-hungry egotists who fill "leadership" positions as teenagers?




So,
free of charge and in search of a better future for all of us, here is
a list of scholarships I'd like to see adopted by universities:




The Wordsworth Scholarship: awarded
to students who have shown that they deeply appreciate the world around
them and pursue independent expression of their thoughts, regardless of
peer pressure.  
Documentation required:  
- Tear-stained copy of a letter of rejection by a former girlfriend/boyfriend  
- A notebook filled with juvenile poems  
- Letter banning you from school spirit club  

The entrance exam will require you to sit still, in complete silence, for 30 minutes.




The Paddy Clarke Initiative Award: awarded to students with demonstrated ability to take responsibility for their own lives.  
Qualifications:  
- Must have lived in a two-parent home for less than half their childhood.  
- Must have moved out of home at least once during their teenage years. Preference given to those who have lived in a squat.  
- Preference will be given to those convicted of shop-lifting, as long as the theft was for a demonstrably useful object.




The Larkin Scholarship: awarded to middle-class students with regular parents, who have never travelled abroad. Qualifications:  
- Must own and wear bicycle clips regularly  
- Attendance at church or other religious institution preferred. Belief not necessary.




The Perec Prize: awarded to students who have demonstrated precocity in the realm of obscure puzzles and word games.  
Qualifications:  
- An essay is required which must include all of the following:  
- a list of at least 24 related items  
- a meal that is all one colour  
- a mathematical theorem  
The essay must have no hypothesis or conclusion, but must include at least three words that contain all the vowels in reverse order.




The Bookworm Scholarship: awarded
to students who have demonstrated intellectual curiosity by exploring
the the world they live in through the medium of books.  
Documentation required:  
- Dog eared copy of at least three major works of literature.  
- Must have read at least two books banned by major school boards.  
-
The ability to articulate your ideas clearly demonstrates that you
really don't understand the complexity of the world and will exclude
you from this scholarship.


		
