---
author: Tom Slee
categories:
- blog archive
date: 2016-05-26 18:35:05
tags:
- airbnb
title: 'Airbnb in Barcelona: two readings'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				A story on Ada Colau, who [may be the world's most radical mayor](http://www.theguardian.com/world/2016/may/26/ada-colau-barcelona-most-radical-mayor-in-the-world), hjighlighte how Airbnb can create problems for the cities where it operates:


<blockquote>Colau’s stated priority is to move Barcelona away from what she considers “massified tourism”, with no thought for sustainability, strategic planning or input from the public. “Until now, all we have had were private initiatives doing what they wanted,” Colau told me. “This has led to a model that is out of control.” She added: “We suffered the same short-sighted model here with the real estate bubble. We are trying to prevent the same mistakes happening again with tourism.”</blockquote>


For a detailed look behind the scenes, Albert Arias Sans and Alan Quaglieri have a new paper called "[Unravelling Airbnb: Urban Perspectives from Barcelona](https://www.academia.edu/24653298/Unravelling_Airbnb_Urban_Perspectives_from_Barcelona)" (sadly, login required). They investigate the claims made in Airbnb's "reports" on the city and show each of them to be false:


Airbnb claim: The vast majority of Airbnb accommodation is located outside the areas with major concentrations of hotels.
Arias/Quaglieri: There is a strong correlation between Airbnb listings and the presence of hotels. Airbnb supply is located to a large extent in the same neighbourhoods as hotels.




Airbnb claim: Airbnb focuses on a new type of traveller seeking the authentic to immerse themselves in other cultures.
Arias/Quaglieri: Analyzing languages spoken by hosts: the composition of the Airbnb host community is different from the profile of the area as a whole. Airbnb appears as a field for the ‘cosmopolitan consuming class’, where hosts and guests share a similar approach to the city around a ‘cosmopolitan sense of local’ from which a large proportion of the rest of the residents of Barcelona are excluded.




Airbnb: proceeds from Airbnb allow hosts to cover their basic expenses and reach the end of the month
Arias/Quaglieri: Airbnb hosts are not representative of the local communities. They are far more educated, have fewer children, and live in less-crowded households. While Airbnb hosting may help solve the prolems of people living in middle- to upper-class neighbourhoods, it is not a resource open to those in the poorer neighborhoods.




A really interesting read, which is a significant step forward in the debate about Airbnb's impact on the major tourist centres.

		
