---
author: Tom Slee
categories:
- blog archive
date: 2008-06-21 17:45:23
title: 'My New Book: Explosion!TM'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I am excited to announce that I am finally ready to write my next book.
It's going to be great. And here's the best thing of all: you can help me write it! 

It's about the Internet and how it's changing
the world. I've got the outline done and I was just thinking I need a research
assistant to fill in the details. Then I thought - well, why just one?
There are a million research assistants out there - let's crowdsource! 

Any book about the Internet needs a big idea. Not just a
kind-of-big idea either, but a Great-Big-Fuck-Off-Massive Idea. The kind of idea
that is so big you can't get your head round it, and yet which you can put in a short phrase so you can trademark it. My Idea is that there are now _more ideas in the world than ever before_.
What's more, these ideas are not just stuck
inside people's heads doing nothing, but thanks to the Internet everyone is putting their
ideas out there for the world to see. And then these ideas spark other
ideas. So with more ideas than ever
before, and better ways of getting ideas acted on, the future just has
to be insanely great.

We are living in an
_explosion_ of ideas. That's where the title comes
from. I thought of calling it "A Hundred Flowers" because that sounds a
bit more classy and intellectual, but then I thought maybe Maoism isn't where I should
be going with this one and _Explosion!TM_ is probably more catchy.

Here
is my outline. I'm thinking I'll post it on a wiki somewhere and all
you great people can just work on it right there. Then I'll take it to the
publisher and we'll see how it goes. Hey - you may even get an
acknowledgement in a best selling book!

_**Explosion**!TM_  


_Why there are more ideas in the world than ever before and why the future will be amazing_  


  
**Chapter 1. The Internet is Brilliant**

_- An Inspiring Story  
_I'm
starting with the true tale of an everyday white teenage boy from a
middle-class family in California - a university drop out shunned by
classmates and living in a deprived environment except for his
state-of-the art computer network and online poker winnings, who toiled
for years in obscurity only to suddenly hit it rich thanks to the viral
spread of his amazing Idea. 

I'd like you to find that story. 

It doesn't
have much to do with the rest of the book, but it needs to get the
reader fired up. The right story will show how in these days of
meritocratic digital democracy anyone can become a visionary leader in
the radically crazy, wild west world that is the Internet. Pretty cool
eh?  
_  
- The Idea. _  
I've
already told you what The Idea is. I got it this afternoon when I was
thinking about what to write about for my next book. Where can I get an idea, I
thought? Well, I thought, you can get anything you want at Alice's
Internet (that's a joke). So I looked on the internet and there are all
these ideas out there and I thought - wow, that's a lot of ideas.
Probably more than ever before. And that's how The Idea was born.

**Chapter 2. The New World Of Ideas**

If you were an author you would know that after presenting The Idea you have to make it plausible. Not in detail, but
just enough to keep the reader moving along. And that's what this
chapter is for.

Have you ever thought about how many ideas
there are in the world? No? Well I'll tell you. There are millions and millions. If
you google the word "idea" you get 725 million pages. Now that's what I
call a lot of ideas.

In the old days ideas only came from Oxford, Cambridge and
Harvard. I mean, Bertrand Russell was a Lord for Christ's sake. And how
many Lords are there? Not many, that's how many. Now there are Internet
entrepreneurs in [Bulgaria](http://www.usaid.gov/stories/bulgaria/fp_bul_georgiev.html) and [Ghana](http://www.infodev.org/en/Publication.223.html)? Who knew? Is the Internet fantastic or what?

I'll finish the chapter with the story of Stelios Haji-Ioannou. You probably haven't heard of him because you are not an author. He is
not only disabled, but he comes from Greek Cyprus of all god-forsaken
places and yet he started the successful company easyJet when he was only 28. I don't know much
about him yet but his story sounds like a great way to wrap up the
chapter. Actually he's not disabled, but his name does appear at the
top of the list when you google ["disabled entrepreneur"](http://www.google.ca/search?q=disabled+entrepreneur) and that's surely close enough.

**Chapter 3. The History of Ideas**

After
that high-speed opening it's time to go all academic and reflective.
You'd know that if you were an author. I'll talk about all those greek guys (not Stelios; the old ones like Plato
and Socrates) Then I'll say - get this - that there were only a few
thousand people around who could even read back then never mind think
(note to research assistant - get a real number for this will you? and
make it small) and now there are like 6 billion of us. So if you do the
arithmetic there are probably about _a million Platos alive right now_
and a million Socrates and on and on. Whew! I bet that makes you think. 

Now you might say "that's impressive, but how can we find these ideas?" But thanks to the Internet we can
find them because we are all connected. Wow.

I have to demonstrate
my credibility in this chapter so it will take some serious googling to
come up with obscure stories about the Greeks. Maybe the thing to do is
not talk about Plato and Socrates but someone really obscure like
Heraclitus because that sounds way more sophisticated and esoteric. [Wikipedia says](http://en.wikipedia.org/wiki/Heraclitus)
that "he is known for his doctrine of change being central to the
universe" and if my book isn't about change I don't know what is, so
that's a great tie in right there.

**Chapter 4. Why the World Was Miserable Before the Internet**

This chapter is about the 20th century, before the Internet came along. 

I'll
start in the 1950's. Everyone wore the same clothes and it was like the
whole world was filled with creepy borg-like automatons except without
the implants. I'm going to write the whole chapter in black and white
just to emphasize how few bright and colourful ideas there were. I
mean, there was just nothing going on.

Then there was the
1960's, which only had two ideas: peace and love. It was nice
and all, but it was pretty simple and naive when we look back at it
from our hyper-linked present.

The 1970's I think I'll
skip over, because fashions were pretty bad and computers weren't
really happening yet so I don't think there were many ideas about then. There was punk music and space travel, so that's two, but they were
pretty lame really.

No one really knows anything about the
1980's any more, but I think it's the key to the whole story. The
1980's were the decade of the personal computer, of the first
incarnation of Apple, of chaos theory, and of the growth of Japan which
is always good for a few paragraphs.

Then 1990s is all
globalization and stuff, so that'll be OK. And the beginnings of the
Internet, so it'll be, like, the big bang that started everything off.
I think I'll do a whole bit about the first web page because stories are so much better than boring facts and who knew
what that very first page was going to lead to? No one, that's who.

**Chapter 5. The Economics of Ideas**

This
is the chapter with some really serious thinking in it. There used to
be these things called transaction costs that prevented new
ideas getting out there. Thinks like checking the results of research or getting a research paper accepted or finding a publisher for your book, or even doing all
those complicated experiments and stuff that took just forever and never really worked out the way they should have done. It was a real pain in the neck is what I
hear - it's not surprising there were so few ideas around. 

But now all those obstacles have gone and anyone can just have an
idea and publish it on the Internet and the whole world can see it.
It's like there's a Long Tail of ideas and now we can get all those
ideas in the tail and put them on the Internet when they used to just
go nowhere because of transaction costs.

I've done some
research to look at how many pages you get if you google for "idea" in
the last 24 hours, etc. Here's what I found.

<table border="0" id="me5y" classname="zeroBorder" width="100%" cellpadding="3" cellspacing="0" class="zeroBorder" ><tbody id="n25r1" ><tr id="n25r2" >
<td width="50%" id="n25r3" >**Time Period  
**
</td>
<td width="50%" id="n25r5" >**Number of ideas (millions)  
**
</td></tr><tr id="n25r7" >
<td width="50%" id="n25r8" >24 hours  

</td>
<td width="50%" id="n25r10" >11.9  

</td></tr><tr id="n25r12" >
<td width="50%" id="n25r13" >past week  

</td>
<td width="50%" id="n25r15" >9.9  

</td></tr><tr id="oy9s" >
<td width="50%" id="oy9s0" >past month  

</td>
<td width="50%" id="oy9s2" >19.7  

</td></tr><tr id="dm.6" >
<td width="50%" id="dm.60" >past 2 months  

</td>
<td width="50%" id="dm.62" >28   

</td></tr><tr id="dm.64" >
<td width="50%" id="dm.65" >past 3 months  

</td>
<td width="50%" id="dm.67" >31.4  

</td></tr><tr id="zrhv" >
<td width="50%" id="zrhv0" >past 6 months  

</td>
<td width="50%" id="zrhv2" >40.6  

</td></tr><tr id="zrhv4" >
<td width="50%" id="zrhv5" >past year  

</td>
<td width="50%" id="zrhv7" >51.6  

</td></tr><tr id="t90." >
<td width="50%" id="t90.0" >any time  

</td>
<td width="50%" id="t90.2" >725  

</td></tr></tbody></table>

That
means over 1% of all ideas ever have been had in the last 24 hours! I
mean, I know Google exaggerates the number of recent events and I'll make sure to
say that you can't really treat this as rigorous but that's still
pretty amazing. Someone should do a Ph.D. on that - there's an idea for you, for free.

**Chapter 6. With Enough Eyeballs, All Ideas Are Shallow**

Most people think ideas need a lot of thinking to come up with, and now [we can't even read a short story without getting bored](http://www.roughtype.com/archives/2008/06/read_it_if_you.php), so where are these ideas coming from? Actually there's a simple answer - open source. 


A big idea is really just a whole lot of little ideas stuck together. 

It
used to be that one person had to sit down in a garret or something and think of all these
little ideas and string them together until they got a big idea. Now
they just put their little ideas on the Internet and then other people
see them and add their own bits and before you know where you are all
those individual bits have added up to give a big idea, without anyone
having to work hard at all! 


I'll talk about how many people contribute to Wikipedia and how
Facebook was a great idea so that people could talk to each other
without talking and how Google just collects all those great ideas and
makes them available for free.

**Chapter 7 and 8 and 9. The Next Big Idea**

In
a book with a Big Idea this is the tough part. A single idea is pretty
tough to stretch into a whole book, and if you're not careful somewhere
after the half way point there's just not a lot left to say. I think
the thing here is to get a whole bunch of ideas that are out there
right now and put them in these chapters and see which ones take off.
Maybe we'll do Chapter 6 on culture, Chapter 7 on science, and Chapter
8 on social networking. Should be fun. What ideas can you find?

**Chapter 10. The Idea Singularity is Here**

A book called _Explosion__!_
has just got to finish with a bang. 

So here's my big finish. Some ideas die out once they have been thought of. Like the bicycle: once someone had thought of the
bicycle, nothing much else happened to it for a long time. At least I
guess it didn't, and who would know if it did? But some ideas are a launchpad for other new ideas. Like when Newton
had the idea of gravity - it wasn't all over and done with, he started
off a whole new set of ideas. 


If every idea can get picked up by other people then that means ideas spread like a virus. An idea infects other people as it goes through
society. So with more connections between people (like the Internet)
more ideas get picked up and fewer ideas die out. I think we're about
to reach a tipping point where each idea will give rise to more than
one idea. And that means the number of ideas is just going to go crazy.
I mean, you think we have a lot of ideas now - just you wait. Give it a few
years and this world is going to be Idea Planet. It's going
to be fucking great.


So that's the book. Are you ready? Get working!


		
