---
author: Tom Slee
categories:
- blog archive
date: 2010-11-03 23:10:05
title: 'Facebook’s Mobile Platform: Top 7 Creepy Quotes'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Today, Facebook [announced](http://www.engadget.com/2010/11/03/live-from-facebooks-mobile-event) their new "mobile platform" and it was full of creepy quotes. Here are my top seven.




7. "First thing is single sign-on. Making it so that you have the Facebook app and you're signed in, and once you do that you don't have the hassle with any other app on the phone". Yes, it's easy, and it gives Facebook and its partners one big shared pool of information about you, your activities, and your behaviour.




6. "Today we're going to open up the write API, and any app can build on top of this -- any app can write to the location of Facebook and read on top of that." – not sure about this, but it sounds like they are saying any application can collect your current location from your phone? Lovely.




5. "We're working to give deals to people who are nearby local businesses." The idea that you want to have your phone tell you that there is a sale on shoes because you walk near a shoe store is deeply perverted.




4. "The deals platform allows businesses to turn fans and views and eyeballs into dollars." Those would be your dollars.




3. "We have a clear privacy console, and you can switch it off". Well, I'm reassured.




2. "we deliver customers in a really effective way. The mobile apps make it a lot easier." That would be you, being delivered.




And the top creepy sentence goes to guest speaker Sam Altman, CEO of Loopt.




1.  "We believe that data wants to be unified." I believe my data wants you to fuck off.


		
