---
author: Tom Slee
categories:
- blog archive
date: 2006-03-21 22:33:25
title: A "Thank You", battling my worse nature
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

It's never pleasant to find out bad things about yourself, and I just did.




I occasionally go over to [Marginal Revolution](http://www.marginalrevolution.com), a weblog run by Alex Tabarrok and Tyler Cowen. They are very pro-free-market economics lecturers and the weblog attracts a lot of libertarian capitalist types: obviously I disagree with them on just about everything. I post the odd comment -- usually just a short dig at something they say -- and then I go again.




So yesterday morning, just before going to work, I took a look, and Alex Tabarrok had just posted a piece on [Le problème du pain](http://www.marginalrevolution.com/marginalrevolution/2006/03/le_problme_du_p.html), asking "why bread isn't nearly as good in the United States as in Paris". It's a problem a little bit like why beer was bad in Britain for so long, which is something I recently wrote about. The piece I wrote is called [Learning By Drinking](http://whimsley.typepad.com/whimsley/2006/01/learning_by_dri.html), and its point of view is pretty much the opposite of most of those at Marginal Revolution, including Alex T. I was one of the early commenters in the thread, and I put a link to my own piece in my comment. No big deal.




But then Alex Tabarrok added a comment to the thread, and said this [emphasis added]:

<blockquote>... Combined with Tom's comments about well-informed consumes and the
lemons problem (_do read his longer post_) I think this could get us
somewhere ...
> 
> </blockquote>

And with that, all kinds of people came over to my site looking at the piece in question. As I [mentioned](http://whimsley.typepad.com/whimsley/2006/03/not_a_blogger.html) just the other day, this is a quiet corner of the Internets, getting a handful of visitors each day. But all of a sudden I got 100 visitors yesterday and another 100 or so today, all thanks to Alex Tabarrok. And traffic, where weblogs are concerned, is a Good Thing.




Now I like to think I'm more open minded than these pro-market types, but here is Alex T. sending people my way from his far more popular site to read a piece that he probably disagrees with. And I would not have thought to send people his way without a little dig at whatever it was they wrote. So it begins to look as if he is more open minded and generous than I am. Which obviously can't be the case because he is on the other side of the political fence from me.




I guess I have to face it. I owe Alex T. a thank you. Come on, you can do it....




"Thank you Alex Tabarrok for recommending people to my web site."




There. Not too bad. Now off to eat some humble pie.


		
