---
author: Tom Slee
categories:
- blog archive
date: 2011-07-11 21:04:03
title: 'Links: Carr, Facebook, Ravelry, Amazon'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				



  * At The Economist, Nicholas Carr and Jay Rosen are debating "This house believes that the internet is making journalism better, not worse". [*](http://www.economist.com/debate/days/view/720) No prizes for guessing who I agree with: opening statements are factual from Carr, wishful thinking from Rosen. Also mentioned at Nicholas Carr's Rough Type blog.[*](http://www.roughtype.com/archives/2011/07/news_to_me.php)


  * Also on Rough Type, Nicholas Carr is adopting Clay Shirky's asterisk-style[*](http://www.shirky.com/weblog/2011/07/we-need-the-new-news-environment-to-be-chaotic/) linking, at least for one post. I'm doing the same but can't be bothered to get rid of the underlining.[*](http://www.roughtype.com/archives/2011/07/semidelinkifica_1.php)


  * Israel uses Facebook to blacklist pro-Palestinian protesters.[*](http://hosted2.ap.org/APDEFAULT/cae69a7523db45408eeb2b3a98c0c9c5/Article_2011-07-08-ML-Israel-Palestinians/id-32d53b9426a44dcab567eff701ed43fc) The window in which Facebook was a space where the younger generation could meet outside the view of officialdom[*](http://whimsley.typepad.com/whimsley/2011/02/more-egypt-more-facebook.html) is now closed.


  * Ravelry, the social network for knitters, discussed at Slate.[*](http://www.slate.com/id/2298584) Quotation: "The company that runs it has just four employees, one of whom is responsible for programming the entire operation. It has never taken any venture capital money and has no plans to go public. Despite these apparent shortcomings, the site's members absolutely adore it." I'd say "Because of these characteristics" rather than "Despite these apparent shortcomings".


  * Amazon wants to buy UK online bookstore The Book Depository.[*](http://www.guardian.co.uk/commentisfree/2011/jul/09/amazon-book-depository-takeover)[*](http://futurebook.net/content/amazon-washes-away-book-depository) Ofcom is looking into it.[*](http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2011/805523) Others are not happy.[*](http://karenknowsbest.com/2011/07/04/amazon-to-buy-the-book-depository-oh-for-fcks-sake/)


		
