---
author: Tom Slee
categories:
- blog archive
date: 2005-11-21 23:29:32
title: Identity Crisis
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[Philip Pullman's essay](http://books.guardian.co.uk/departments/politicsphilosophyandsociety/story/0,,1645833,00.html) as part of The Guardian's piece on the possibility of laws to curb the promotion of religious hatred is, like much of what he writes, thought provoking and original. ([Norm Geras](http://normblog.typepad.com/normblog/2005/11/religious_belie.html) discusses it as well.)




Part of Pullman's essay is emphasizing the distinction between what we are (identity) and what we do. He starts this way:

<blockquote>1. What we are is not in our control, but what we do is.
> 
> </blockquote>

<blockquote>2.
On the other hand, and simultaneously, what we do depends on what we
are (on what we have to do it with), and what we are can be modified by
what we do.
> 
> </blockquote>

<blockquote>3. What we do is morally significant. What we are is not.
> 
> </blockquote>

The distinction is important, and he goes on to argue that

<blockquote>But to criticise the
religion of someone who makes that religion the primary marker of their
identity will be, specifically, to criticise them. It will be
criticising what they are, not what they do. And if it comes to the
courts, will the law be capable of distinguishing between a rational
analysis of theology and an incitement to brutal violence? Home Office
Minister Hazel Blears doesn't think it will: she has said that she
can't predict how the courts will act. Better safe than sorry, is the
implication.
> 
> </blockquote>

<blockquote>The
inevitable consequence for literature - as many others have pointed out
- will be that publishing decisions will increasingly be made not by
editors, as they used to be; nor by accountants, as they now are; but
by lawyers. And my learned friends will be throwing the pall of their
caution over the theatre as well, to the impoverishment of all of us.
> 
> </blockquote>

Pullman is on the money. There is, however, a missing piece here, or at least one that is not explicitly brought to the fore. In their brilliant description of [Economics and Identity](http://www.econ.umd.edu/~kranton/publications/economicsandidentity.pdf) (which I describe in Chapter 11 of [The Book](http://www.tomslee.net)), George Akerlof and Rachel Kranton bring ideas of identity into game theory and economics. Their model emphasizes how "identity" comes with a set of "prescriptions", which indicate the behaviour that is appropriate for someone of a given identity, or the ideal behaviour associated with a given identity.




Depending on the circumstance, someone may identify themselves in different ways -- by gender, by profession, by religion. The prescriptions associated with these identities depend on the circumstace, but they are rules that are _internalized_, and there is a cost in the form of anxiety when the rules are violated.




So in addition to what you are and what you do, there is also the matter of what "people like you" do -- the rules associated with your identity. And it is in this area that much of the debate over religion comes. To criticize a religion is to criticize its prescriptions -- whether this means that Catholics should not divorce or Sikhs should cover their head, or one of a myriad of others. The struggle within many religions over "what it means to be Muslim/Christian/whatever" is a struggle over alternative sets of prescriptions. It is insufficient to say this is "what you do" because once the prescriptions are internalized there is a real cost to not following the rules. The prescriptions are what connects "what you are" to "what you do".




So Pullman has it almost right, but not quite. It is, as he says, "all very complicated" and it is essential, as he says, that debate over "what it means to be" of one religion or another (or one nationality or another, and so on) continue without censorship, but it would be simplistic to suggest that criticisms of "what people do" can be made separately from criticisms of "what people are."


		
