---
author: Tom Slee
categories:
- blog archive
date: 2006-12-12 22:52:14
title: Popularity Rises With Price
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Here's why people who say that the unemployed should offer to work for less are wrong. It's actually about tuition fees, but it's a reminder that price can act as a signal of quality. What's a little odd is that the price seems to be taken as a signal of quality even though the university itself did not change - that is, there is no guarantee that students who pay the full fees get what they are paying for.

<blockquote>John Strassburger, the president of Ursinus College, a small liberal
arts institution here in the eastern Pennsylvania countryside, vividly
remembers the day that the chairman of the board of trustees told him
the college was losing applicants because of its tuition.

> 
> 

> 
> 

> 
> [ ](http://www.nytimes.com/2006/12/12/education/12tuition.html?em&ex=1166072400&en=6785ef55f841945b&ei=5087%0A#secondParagraph)
> 
> At Ursinus College officials determined that tuition was too low to
draw enough students. So they raised it, and applications surged. 
> 
> 

> 
> 

> 
> It was too low.
> 
> 

> 
> So
early in 2000 the board voted to raise tuition and fees 17.6 percent,
to $23,460 (and to include a laptop for every incoming student to help
soften the blow). Then it waited to see what would happen.
> 
> 

> 
> Ursinus
received nearly 200 more applications than the year before. Within four
years the size of the freshman class had risen 35 percent, to 454
students. Applicants had apparently concluded that if the college cost
more, it must be better.
> 
> 

> 
> “It’s bizarre and it’s embarrassing, but it’s probably true,” Dr. Strassburger said. 
> 
> 

> 
> Ursinus
also did something more: it raised student aid by nearly 20 percent, to
just under $12.9 million, meaning that a majority of its students paid
less than half price.
> 
> 

> 
> Ursinus is not unique. With the race for rankings and choice students shaping college pricing, the [University of Notre Dame](http://topics.nytimes.com/top/reference/timestopics/organizations/u/university_of_notre_dame/index.html?inline=nyt-org), Bryn Mawr College, [Rice University](http://topics.nytimes.com/top/reference/timestopics/organizations/r/rice_university/index.html?inline=nyt-org),
the University of Richmond and Hendrix College, in Conway, Ark., are
just a few that have sharply increased tuition to match colleges they
consider their rivals, while also providing more financial assistance.
> 
> 

> 
> The
recognition that families associate price with quality, and that a
tuition rise, accompanied by discounts, can lure more applicants and
revenue, has helped produce an economy in academe something like that
in the health care system, with prices rising faster than inflation but
with many consumers paying less than full price...
> 
> 

> 
> More at the New York Times, below.
> 
> </blockquote>

Link: [In Tuition Game, Popularity Rises With Price - New York Times](http://www.nytimes.com/2006/12/12/education/12tuition.html?em&ex=1166072400&en=6785ef55f841945b&ei=5087%0A).


		
