---
author: Tom Slee
categories:
- blog archive
date: 2007-05-25 14:37:40
title: 'Believe the Opposite: Radical Opacity'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I'm afraid Clive Thompson has jumped the shark. From being a witty journalist at the interesting [This Magazine](http://www.thismagazine.ca/) he now fits right in at the boring Wired Magazine. On the way he seems to have lost his sense of irony (maybe they don't let you bring irony into Silicon Valley?) and his cynicism. As a result, he has also lost the plot. Come back Mr. Thompson!




His March 2007 article in Wired Magazine called [The See-Through CEO](http://www.wired.com/wired/archive/15.04/wired40_ceo.html) coined the phrase Radical Transparency. Like other Silicon Valley catch phrases, it has that air of youthful rebellion, it is self-consciously ignorant of history (who needs history when all the interesting things are happening right now), and - most important of all - it imparts a feel-good sense of anti-corporate attitude to your next venture funding proposal or business plan. Because like other Silicon Valley catch phrases, Radical Transparency has about as much to do with rebellion as riding a mountain bike.




Here are some snatches from the article, and some recent events in the real world, mainly as reported by The Register - which has thankfully managed to keep its senses of both irony and cynicism - and mainly about Web 2.0 poster-offspring Google and its growing Google-hoard of companies.

<blockquote>**"**You can't hide anything anymore," Don Tapscott says. Coauthor of _The Naked Corporation_, a book about corporate transparency, and _Wikinomics_, Tapscott is explaining a core truth of the see-through age: If you engage in corporate flimflam, people will find out.
> 
> </blockquote>

[Meanwhile, Google plays cat and mouse with regulators.](http://www.theregister.co.uk/2007/05/25/google_privacy/) Leif Aanensen, deputy director general of the Norwegian Office of the Data Inspectorate, has been investigating Google's data retention policy: 

<blockquote>"We are not satisfied," he said. "We didn't get the proper answers."
> 
> "Our main issue was their data retention policy and the use of the data they stored. We asked them what they were doing with the personal data - are you creating profiles - they didn't answer," he said. 
> 
> </blockquote>

Thompson writes: "You can't go halfway naked. It's all or nothing. Executives who promise they'll be open have to stay open."




Meanwhile, Google - who make repeated references to their own "[radical transparency](http://meritocracy.typepad.com/meritocracy/google/index.html)" - are closed-mouth about the introduction of new programs.   
Paying [select few video producers](http://www.theregister.co.uk/2007/05/04/youtube_coughs_up/) for example:

<blockquote>YouTube says anyone who wants to get paid can let it know by registering an interest, but provided no timescale for when it will cough up, or what the carve-up will be.
> 
> </blockquote>

Or will there be [advertising on the iGoogle front pages](http://www.theregister.co.uk/2007/05/02/igoogle_launch/http://www.theregister.co.uk/2007/05/02/igoogle_launch/)? 

<blockquote>The company has not made any noises about placing personalised ads on the new iGoogle personalised homepage, but industry observers are fairly confident it is only a matter of time. 
> 
> </blockquote>

 

When it comes to openness, Thompson writes "there's no use trying to resist. You're already naked." How Naked? Hard to tell, because it is not easy to find out what [information Google keeps about you](http://www.theregister.co.uk/2007/04/25/google_doubleclick_complaint/).   


<blockquote>"Upon arriving at the Google homepage, a Google user is not informed of Google's data collection practices until he or she clicks through four links," says the section of the complaint which details Google's alleged deceptive trade practices. "Most users will not reach this page. In truth and in fact, Google collects user search terms in connection with his or her IP address without adequate notice to the user. Therefore, Google's representations concerning its data retention practices were, and are, deceptive practices. 
> 
> "As a result of Google's failure to detail its data retention policies until four levels down within its website, its users are unaware that their activities are being monitored," says the complaint in the section alleging unfair trade practices. 
> 
> </blockquote>

Thompson writes: 

<blockquote>Secrecy is dying. It's probably already dead. 
> 
> </blockquote>

Meanwhile, here's Google [being radically opaque](http://www.theregister.co.uk/2007/04/23/google_penguins/):

<blockquote>ord broke this month that Google has purchased 800 acres of land in Pryor, Oklahoma. The company has yet to confirm plans for the site, but I'm betting on a new data center rather than an amusement park (in all fairness, you can never tell with this bunch – Ed). 
> 
> 

> 
> Oklahoma proves a handy spot to have a data center since the state's Governor signed a new law that affords the largest corporate energy users the right to keep their power consumption figures a secret. 
> 
> Governor Brad Henry signed the energy law (House Bill 1038) just a couple of days after news of Google's land purchase reached the local newspapers. Coincidence? Sure. 
> 
> The lawmakers behind the bill denied having chats with Google around any legislation. People familiar with the matter, however, did note that the law proves convenient for an entity such as Google that likes to keep as much information secret as possible. 
> 
> If you're a demanding type who needs evidence of Google's secret ways, have a listen to head of strategic development Rhett Weiss. He presided over a party celebrating yet another Google data center in South Carolina. When asked about Google's water and power usage, Weiss [confessed](http://www.roughtype.com/archives/2007/04/the_real_web_20.php): "We're in a highly competitive industry and, frankly, one or two little pieces of information like that in the hands of our competitors can do us considerable damage. So we can't discuss it."
> 
> </blockquote>

What else does Google not tell us? Here's [Nicholas Carr](http://www.roughtype.com/archives/2007/05/dealing_with_go.php):

<blockquote>“We never,” says a Google representative, “comment on who we’re talking to, who we’ve considered, who we’ve rejected. We feel that when we come to an agreement, that’s the time to make an announcement.”
> 
> </blockquote>

So please, Mr. Thompson - exercise some scepticism. Even a little would go a long way.


		
