---
author: Tom Slee
categories:
- blog archive
date: 2008-01-24 20:39:59
title: Beyond Defending the State
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

The other day I [mentioned](http://whimsley.typepad.com/whimsley/2008/01/guest-blog-at-r.html) that I had a posting up at the [Relentlessly Progressive Economics](http://www.progressive-economics.ca/relentless/) blog. For all those who wanted to read the piece, but just couldn't bring themselves to click the link, here is that posting.




* * *




The recent PFE blog [post](http://www.progressive-economics.ca/2008/01/15/social-murder-and-conservative-economics/) by Robert Chernomas and Ian Hudson is a wholesome read. It reminds us that markets and private enterprise deserve less credit than they receive for our current prosperity, such as it is; it lays out the contribution of the state to innovation; it reminds us that unregulated markets are hazardous and often crooked; and it points out that cornerstone social democratic policies such as a healthy minimum wage don't have the dire side effects conservative economics would have us believe they do.




And yet it makes depressing reading. 




I'm not here to pick a fight with Chernomas and Hudson (it was a short excerpt from a bigger piece, after all), but it touched a nerve because for all my adult life (ie since the late '70s) I've been reading the same defensive tone from left-wing economists and after thirty years it's getting a little stale. Is defending the role of the state the best we can do? I hope not because it's not enough.




Just to get back to basics, how many of us became left wing because of a belief in the beneficent power of the state per se? Not me and almost certainly not you. Most of us are left wing because we believe that, left to itself, economic wealth is used to exploit the poorer and weaker in society and that the best response to such exploitation is, the the words of Pete Seeger, to stick together. I don't see the word "state" there. Yes, a democratic state has the potential to be a levelling instrument in an unequal society. But it's not the only such instrument and it's not always a reliable one.




The non-economist left is not always so cozy with the state. I look on my bookshelf and see titles from the UK in the 1970's like Pluto Press's _In and Against the State_, and Ralph Miliband's _The State in Capitalist Society_. They both have harsh words for the institutions of the capitalist state and they identify forces that cause those institutions to act on behalf of the economically powerful. Once you move away from economic policy, most of us on the left are decidedly ambivalent about the state. State institutions have oppressive tendencies; nuclear-armed states are dangerous; the state defends the interests of the powerful. So why, when it comes to economics, are we so tied to the state?




I think it's because the left is a victim of its own successes. The structural achievements of the post-war world are the great social democratic institutions rooted in the state: the construction of social security, the provision and expansion of public schooling and post-secondary education, public healthcare. We've identified with these achievements, so ever since Thatcher & Reagan we have stood as conservative (small c) defenders of the state against the market-populist radicals. 




Unfortunately a siege mentality does not encourage adventurous ideas or internal debate, and as a result unorthodox economic ideas on the left, at least the public expression of them that I'm aware of, has been stifled. As a non-economist, it seems to me that our attitude to economic ideas that don't stem from the state-driven social democratic tradition is too often one of suspicion. I'd love to be proven wrong...




Statist social democratic institutions are not the only tradition that we have. We have traditions of self-government from the co-operative movement, we have traditions from the trade union movement of course, from community-focused movements and small-scale economic organizations, and from social protest. The feminist movement has a far more ambivalent relationship to the state than the traditional left. So maybe we can look at some of these for non-state driven left-wing economic ideas too.




What's more, the world has changed in the last thirty years. It need not be defeatist to say that the policy prescriptions of 1970 may not make sense today. After all, would we expect the policies and goals of socialists and social democrats in 1948 to be the same as those of 1910?




Here is a scatter shot list of policy areas, mainly micro-economic, in which left-wing innovation seems possible, but is happening slowly if at all in Canada. I do hope that I'm missing things. Can readers can put me right?




  * **Corporate ownership** The left has a long tradition of supporting worker ownership. A successful example is the [John Lewis](http://www.johnlewis.com) Partnership that has a prominent position on Britain's High Street. It's commercial, it's a business, and it's worker owned. Have we seen any policy initiatives that encourage and promote this kind of corporate governance?


  * **Corporate taxation** In one blog comment I asked Erin Weir whether the Scandinavian model of low corporate taxation makes sense in Canada. He thought not, but it makes sense to me that in looking at progressive taxation we should direct tax efforts at the owners of corporations, not necessarily the corporations themselves. 


  * **Innovation **Is there a left-wing innovation policy that goes beyond university research to industrial development, and if so what would it look like? The most interesting idea I've seen recently is the suggestion of replacing pharmaceutical patents by prizes, supported by Stiglitz and others (short PDF [here](http://www.cptech.org/ip/health/js_new_scientist_06.pdf)). Has this idea been followed up in Canada?  



  * **Post-secondary education** Historically, the left has been opposed to means testing. But historically we didn't have computers. Stephen Gordon at Worthwhile Canadian Initiative [recently argued](http://worthwhile.typepad.com/worthwhile_canadian_initi/2007/10/how-increasing-.html) that the best way to increase the accessibility of post-secondary education is not through cutting tuition fees for all, but through targeted subsidies. When I challenged him on means testing he replied that "if we can handle the GST credit, why not use the same data for tuition subsidies?" Makes sense to me (even though I am forking out too much money for my son's university). 


  * **Microfinance and community initiatives** How does the left feel about the Grameen Bank and its emulators? The movement has been praised and damned from both left and right. Surely there is something there that has relevance to the Canadian experience? I know I dislike the focus of microfinance organizations like [kiva.org](http://kiva.org) on "entrepreneurs", but perhaps that is just a generational linguistic shift I am not prepared to make. There is also a sense of solidarity in such movements, and a direct approach to providing support for powerless people to take control of their own lives - surely a left-wing goal.


  * **Public health** The debate on health is always phrased in terms of a public system versus a private system, but one of the most successful social health initiatives of the last few decades was sparked by efforts outside both these spheres. The building of a network of sexual assault/rape crisis centres in many of our cities came from feminist activists (see [here](http://www.ocrcc.ca/OCRCCbackgrounder.pdf) (PDF) for example) and remains, if I understand it right, at arms length from government. While government funds have been used (and more could be needed) these have not always been state institutions. Are there ways to emulate the success of this movement in other areas of our society, and what policies would promote this kind of emulation?


  * **Small Business** Our relationship to small businesses is ambivalent. We support them when we talk about communities and worry about the impact of big-box stores coming to town, but we don't see them as a partner in an economic sense. What kinds of small-business economic initiatives have come from the left?


  * **Cities and towns** The Jane Jacobs tradition of diversity and small-scale thinking is one that many on the left love, even while some on the right think she's a great thinker too. She was no fan of central planning of course, but she's also no fan of letting cities just grow according to commercial dictates. Why has the left's adoption of her ideas has been piecemeal? Initiatives at the city level (especially in transit/traffic and housing) seem small-scale, but have the potential to spread from country to country in a remarkable way as activists and planners search for inspiration. The London traffic congestion charge and the bike-friendly initiatives of places like Lyons (now spreading to [Paris](http://www.washingtonpost.com/wp-dyn/content/article/2007/03/23/AR2007032301753.html)) act as experiments that can be modified and built-on by others.



Well, that's probably a confused list. What initiatives have I missed? Is the Canadian economic left less hidebound than I give it credit for?


		
