---
author: Tom Slee
categories:
- blog archive
date: 2007-02-19 19:43:35
title: The Long Tail 2 - The Rise and Fall of the Hit
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is part of my critical reader's companion to _The Long Tail_ and discusses "Chapter 2 - The Rise and Fall of the Hit". Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). The previous part in this series is [here](http://whimsley.typepad.com/whimsley/2007/02/chapter_1_start.html).  
  
A book that paints a big picture, as The Long Tail does, and especially if it is paints using an informal, storytelling brush, can be difficult to refute. Point out the problems with any one story and you can be accused of splitting hairs -- that one story is just a little piece of the picture, and if it's a bit inaccurate then it doesn't affect the basic thesis. On the other hand, if you make big claims and say that "it's all wrong" you lose as well, because that's unconvincing. So if you really want to refute a book (and yes, reader, that is what I want to do) then you've got to go through it page by page, example by example, and make your case.  
  
A big picture really does have to be backed up by real data and real mechanisms somewhere, and the onus is on the author to provide that data and those mechanisms. Anderson fails to do so in The Long Tail. If you construct a theory (and Anderson calls the Long Tail a theory, even though I'd argue it's not) and that theory is to hold water, then sooner or later there has to be something solid to it.  
  
By Chapter 2 I was beginning to wonder where the solid foundation for The Long Tail could be found. We've seen how, in the Introduction and in Chapter 1, the book flits between engaging stories (Touching the Void, the 98 percent rule), ad hoc comparisons that hide as much as they reveal (Rhapsody vs. Wal-Mart, the coming-of-age teenage choice comparison) and generalizations. And so goes Chapter 2. It's not that it's completely wrong, it's that enough of it is inaccurate or misleading to make the big picture melt away like a snowman in the sun.  
  
The main argument of Chapter 2 is that, as the final sentence tells us "we are turning from a mass market back into a niche nation, defined not by geography but by interests" [40]. Yet the content of the chapter shows only that the past contained a mass market culture (among other things) and the present contains niches (among other things). This is not the same at all. You cannot demonstrate a transition by listing all those aspects of the 1950's that were mass market and all those aspects of today that are niche - you have to ask if there were niches back then and if there are mass markets today. And that's where Anderson fails. He just lists examples of mass-market 1950s things and 2007 niche things. It's not enough.  
  
So, now to the page-by-page look at the chapter.  
  
The first few pages of the chapter are a caricature of a cultural history of the USA: of how culture has changed from a predominantly local agrarian structure (pre-industrial revolution) through the growth of urban "mass culture" in the 20th century, to the "end of the hit parade" as the twenty-first century opens. It describes the 1950's as "the ultimate in lockstep culture" [29] - an image of grey, authoritarian conformism -- and there were indeed aspects of the culture that showed such a shared and "lockstep" trend - "by 1954, an astounding 74 percent of TV households were watching I Love Lucy every Sunday night".   
  
Even here we should remember that in 1954 TV was in its infancy - a third of households did not have one. And an accurate picture of the 1950s would include the fact there was another aspect of society that declined from the 1970's on, and that was the "collapse of American community" documented so well by Robert Putnam in [Bowling Alone](http://www.bowlingalone.com/). A whole set of diverse community activities was available in the 1950's that is not present now, and Anderson does not mention this. Putnam "draws on evidence including nearly 500,000 interviews over the last quarter century to show that we sign fewer petitions, belong to fewer organizations that meet, know our neighbors less, meet with friends less frequently, and even socialize with our families less often." Anderson says that the TV data show that "watercooler effect, the phrase describing the buzz in the office around a shared cultural event" peaked in the 1950s and 1960s, because "it was a safe assumption that nearly everyone in your office had watched the same thing the previous night". But this neglects all those other social activities documented by Putnam, which were more prevalent at that time and which were also markers of diversity.  
  
So a more accurate picture might be that there was the growth of one form of mass culture (TV) at a time when other variegated activities were still present. I don't know how the arithmetic works out (and there's an apples vs. oranges quality to it of course) but the onus here is on Anderson to prove his case, and he is being selective in his evidence. It is easy to point at the 1950's as lockstep conformism if you focus only on those aspects of culture that were common and if you neglect all those that were diverse. And this is what he does.  
  
Even as he goes on into the world of music [30] he draws the same caricature-like portrait. He says how "The [hit-making] machine [that was radio] hit its peak in the form of American Top 40, a syndicated weekly radio show started by Casey Kasem in 1970. It began as a three-hour program that counted down the topforty songs on Billboard's Hot 100 singles chart... For a generation of kids who grew up in the seventies and eighties, this was the carrier signal of pop culture."[30]   
  
Now I grew up in the UK, not the US, so maybe things were a little different, but (as I've already touched on in [the previous chapter](http://whimsley.typepad.com/whimsley/2007/02/chapter_1_start.html)) things were not this monolithic. We too had out Sunday evening Top Countdown (hosted by Alan "Fluff" Freeman, pop-pickers) and my brothers and I listened to it regularly, as did a lot of other people. But was it "the carrier signal of pop culture"? No. There are two carrier signals for pop culture - the media and word of mouth. The cool kids were all listening to John Peel from 10 to midnight or to Radio Luxembourg and the rest of us listened to the charts and then got the pointers from our cooler friends as to what's the newest on the alternative side of the music spectrum. So whether you were a Genesis lover or a Black Sabbath follower or whatever, even in those early 1970s there was a variety of tastes around. Anderson is suffering (have I said this often enough?) from a convenient selective vision when he paints his picture of the past.  
  
The End of the Hit Parade [31-32] charts the turn away from mass culture. It is built around a graph that shows the number of hit albums (gold, platinum, multiplatinum and diamond) in each year. The graph shows shows a fairly steady rise from 1957 to 2002 followed by a rapid fall-off after 2002. This turn is explained as follows: "Between 2001 and 2005, the music industry's total sales fell by a quarter. But the number of hit albums fell by nearly half. In 2000, the top five albums... sold a combined 38 million copies. In 2005, the top five sold just half that; only 19.7 million copies. In other words, although the music industry is hurting, the hit-making side of it is hurting more. Customers have shifted to less mainstream fare, fragmenting to a thousand different subgenres." [32-33]  
  
Like so many other figures and paragraphs in the book, this sounds convincing but does not hold up to closer inspection. Anderson is right that "so
mething happened" in the first years of the century, and that the something was, as he says, digital music. One consequence of the shift to digital, we all know, was a move away from buying albums and towards buying individual songs. Here is a paragraph from today's (February 18, 2007) Sunday [Toronto Star](http://www.thestar.com/artsentertainment/article/182997):  


<blockquote>"Individual tracks are clearly driving the business," was the _Entertainment Marketing Letter_'s assessment of the music industry's health at the end of 2006. "Album sales were down by 4.9% in both digital and physical formats to 588 million from 619 million in 2005, while 22 tracks were downloaded more than 1 million times each versus two the previous year."
> 
> </blockquote>

By showing only albums on his chart, Anderson cannot distinguish between two effects of digital music. The first is a shift to individual songs from albums, and the second, to be proven, is the shift of purchases towards a long tail of niche markets. He claims the change is all about The Long Tail, but the quotation above makes it clear that the shift away from albums may have a big effect too. I can't say which one is the more important, except to note that the evidence from comparing HMV and Rhapsody shows little "shift to the tail". It is a topic that Anderson returns to later, and I hope present more evidence when I get to those chapters that the Long Tail effect appears to be muted, at least. And anyway, to be frank, the onus is on Anderson to prove his case and yet again, by his choice of comparison, he has failed to do so.




Who Killed the Hit Album? [33-35] is another section about trends in music; this is a digression on the factors behind the shift to the Long Tail, a shift which is yet to be proven. It is a descriptive section with few data except for music sharing among music fans (which do seem very diverse) and a glimpse into the subgenres that Rhapsody promotes. The remainder is a plausibility argument about people having many different tunes on their iPods. There's not a whole lot to be said about this couple of pages.




Broadcast Blues [35-38] moves the discussion from music to the real problems of radio, and thence on to other areas of culture. It claims to show that "What's happening in music is paralleled in practically every other sector of mass media and entertainment. Consider these statistics from 2005:




  * Hollywood box office fell by 7 percent...


  * Newspaper readership ... fell by 3 percent...


  * Magazine newsstand sales are at their lowest levels... in more than thirty years.


  * Network TV ratings continue to fall."[37]



But these figures do not parallel the shift away from hits that he claimed to have seen in music (albeit without good foundation, as I have shown). The drop in newspaper readership and magazine newsstand sales do not mark a shift from a hit parade to a niche market, although they do mark a move away from physical media to the Internet. The two are not the same: if I stopped buying [This Magazine](http://www.thismagazine.ca) and instead got my social commentary from CNN Online I would be moving towards, not away from, a mass culture. It is clear, to repeat, that the Internet is important and is changing things. What is not clear is whether the shift from hits to the Long Tail is real, or in which cases it is real, and what the magnitude and importance of such a shift (if it exists) would be.




The final section is A Hit-Drive Economy is a Hit-Driven Culture  will take us there.




At the end of this chapter, are we any further ahead than at the beginning? Not really. We have seen that there is a real shift from physical to digital and that some shared "blockbuster" experiences of earlier decades (network TV in particular) have become diluted. But we have not seen evidence of a real shift away from a mass culture to a niche culture, partly because Anderson ignores those aspects of times past that were richest in niches (civic engagement, local organizations, and so on as documented in Bowling Alone) and partly because his data (musically with album charts) do not demonstrate that people are really moving to the niches as they move online. It may be so, and there are forces pushing us in that direction, but as we shall see in later posts there are forces pushing us back the other way too, towards a hit-based, celebrity-based culture. Which one wins in what cases is up for grabs.




Postings will probably slow until the weekend, when I can spend more time on this project again.


		
