---
author: Tom Slee
categories:
- blog archive
date: 2013-11-09 20:07:00
title: This Week in the Sharing Economy (November 8 2013 Edition)
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Another collection of links (about 75) with almost no commentary. There’s so much happening this may be a regular feature.



	
  * Airbnb:

	
    * The big story is the New York challenge, in which the Attorney General’s office is demanding Airbnb data. Airbnb has loudly [refused](http://publicpolicy.airbnb.com/new-york-next-steps/), the AG’s office says their refusal [exaggerates what the state is asking for](http://news.cnet.com/8301-1023_3-57611599-93/new-york-ags-office-airbnb-lying-about-user-data-subpoena/?part%3Drss&subj%3Dnews&tag%3Dtitle). Stil, the Internet Association has [filed on Airbnb’s behalf](http://internetassociation.org/11082013airbnbamicusbrief/).

	
    * What is the Airbnb business? Airbnb paints a picture of community in this [study](https://www.airbnb.ca/press/news/new-study-airbnb-generated-632-million-in-economic-activity-in-new-york?locale%3Den). (mentioned last week). The New York Times casts some doubts on the Airbnb business model [here](http://www.nytimes.com/2013/11/05/nyregion/the-airbnb-economy-in-new-york-lucrative-but-often-unlawful.html), with commentary at the Real Deal [here](http://therealdeal.com/blog/2013/11/04/top-100-airbnb-users-grossed-54m-over-last-three-years/). Both [Sam Roudman](http://techpresident.com/news/24513/analysis-examines-how-much-illegal-money-airbnb-makes-new-york) at TechPresident and [Nancy Scola](http://nextcity.org/sharedcity/entry/the-numbers-airbnb-hasnt-released) at NextCity use my results from [here](http://tomslee.net/2013/10/notes-on-airbnbs-new-york-business.html) to question the claims. I should have something more on this soon.

	
    * In favour of Airbnb: some people like the [breaking rules](http://www.peacefulcombat.com/airbnb-and-the-trouble-with-breaking-rules/), Cato says [govt is bad](http://www.cato.org/blog/big-government-wants-spare-bedroom), and so do [these people](https://www.cdt.org/blogs/gs-hans/0611overbroad-subpoena-airbnb-user-data-smacks-general-warrant). Meanwhile: [Brooklyn](http://technical.ly/brooklyn/2013/11/01/airbnbs-brooklyn-impact/). And here is the [New York Post](http://nypost.com/2013/11/04/turning-your-ny-apartment-into-a-hotel-is-illegal/).

	
    * Hosts: One big story, which came out late last week and has been reposted in several places, was how to [buy an apartment](http://needwant.com/p/buying-apartment-airbnb/) just to rent out on Airbnb. Some, however, are [dubious](http://finance.fortune.cnn.com/2013/11/07/airbnb-rental-income/) about it. Other articles tell us how to manage a [six figure](http://www.fastcompany.com/3021179/secrets-of-running-a-six-figure-airbnb-business) Airbnb business, how to rent out your [second home](http://www.forbes.com/sites/vanessagrout/2013/11/04/how-to-use-airbnb-to-profit-from-your-second-home/), warn you that it’s more [more complex](http://www.intelligentspeculator.net/passive-income-project/buying-property-to-rent-out-airbnb-style-getting-easier-and-more-complex/) than you might have thought, or offer [tips](http://www.lifehacker.com.au/2013/11/top-10-tips-for-first-time-airbnb-hosts/). If you’re doing it seriously, a new set of services is likely to build around this industry, like [Guesthop](http://guesthop.com/), or [Taskrabbit, natch](https://www.taskrabbit.com/san-francisco-ca/t/lightly-clean-and-manage-my-airbnb-property-full-house) or [others](http://collaborativ.co/2013/11/08/airbnb-building-platform-home-services-like-home-cleaning). All these pieces indicate a future that is different from the “Javier likes to show off his favorite Latin dance spots to travelers” vibe that they promote.

	
    * Effect on rentals: [old from SF](http://www.sfbg.com/2013/08/06/thin-air),

	
    * History: [First pitch deck](http://www.businessinsider.com/airbnb-a-13-billion-dollar-startups-first-ever-pitch-deck-2011-9), it was [a tough road](http://venturebeat.com/2013/11/06/airbnb-cofounder-in-the-early-days-every-rejection-we-got-was-an-invitation-to-keep-going/) before the [media moment](http://www.gadling.com/2013/11/06/airbnb-having-media-moment/) and now you get to [work here](http://www.customspaces.com/projects/ZewNn5vLy4/airbnb/).

	
    * Commentary from [Expedia CEO](http://skift.com/2013/10/30/expedia-ceo-is-bullish-about-the-future-of-airbnb/), the [travel industry](http://fredericgonzalo.com/en/2013/07/27/collaborative-economy-in-travel-the-big-disruptor/http://fredericgonzalo.com/en/2013/07/27/collaborative-economy-in-travel-the-big-disruptor/), [Conde Nast Traveler](http://www.cntraveler.com/perrin-post/2013/11/should-you-book-an-airbnb-rental-in-new-york-city), [Consumerist](http://consumerist.com/2013/11/01/will-airbnb-and-etsy-destroy-the-economy-or-save-us-all/), [Hotel News Now](http://www.hotelnewsnow.com/article/12561/Meet-the-new-competition).

	
    * Stories: [misleading photos](http://monocle.io/posts/the-story-of-airbnb-photography), [world tour](http://www.theguardian.com/travel/2013/nov/01/todd-selby-airbnb-locals-world-city-tour),




	
  * More broadly on the sharing economy:

	
    * [Piper-Jaffray Report: The Disruption of Sharing](https://piper2.bluematrix.com/docs/pdf/35ef1fcc-a07b-48cf-ab80-04d80e5665c4.pdf), [a new book](http://greenupgrader.com/27176/meet-the-sharing-economy-with-sharing-is-good/) (also [here](http://www.mnn.com/lifestyle/responsible-living/stories/new-book-explores-the-sharing-economy)), [a directory](http://www.compareandshare.com/sharing-economy-directory/), [opportunities](http://blog.supplymanagement.com/2013/11/the-opportunities-of-the-sharing-economy/), [changing patterns](http://www.economistinsights.com/sites/default/files/EIU_Zuora_WEB_Final.pdf). [Peter Coffee](http://gigaom.com/2013/10/19/four-business-opportunity-that-remove-barriers-to-the-sharing-economy/).

	
    * [Young Global Leaders](http://www3.weforum.org/docs/WEF_YGL_CircularEconomyInnovation_PositionPaper_2013.pdf), [strike back](http://martinpasquier.com/2013/10/15/the-sharing-economy-hangover-states-and-olbiz-strike-back-on-c2c-startups/), [capitalism and regulation](http://science-inc.com/about/blog/2013/10/10/how-capitalism-and-regulation-will-reshape-the-sharing-economy-2/),

	
    * [In Ann Arbor](http://a2share.org/), in [the Arab World](http://ouishare.net/2013/10/sharing-economy-gaining-momentum-in-the-arab-world/#.Unj7_W9KyG8.twitter) ([again](http://www.wamda.com/2013/10/4-issues-sharing-economy-solve-arab-world)) [adopted by corporations](http://www.smartcompany.com.au/growth/economy/34413-subscription-and-sharing-models-popular-with-businesses-could-this-be-the-new-economy.html), [in the Philippines](http://www.mb.com.ph/the-sharing-economy-where-creatives-should-be/), [in Asia](http://citizentekk.com/2013/10/29/asia-ready-sharing-economy/), in [Chicago](http://www.builtinchicago.org/blog/chicago-sharing-startups-featured-national-tv-news-coverage).

	
    * [A tidy profit](http://www.smh.com.au/money/planning/sharing-your-way-to-a-tidy-profit-20131022-2vy0u.html), [mixing business and social change](http://www.fastcoexist.com/3020778/sharing-can-truly-disrupt-business-by-mixing-money-and-social-change), [feel good inside](http://techcitynews.com/2013/10/31/5-sharing-economy-startups-thatll-make-you-feel-good-inside/),

	
    * Or [not](http://www.alternet.org/labor/backed-billionaire-investors-ridesharing-companies-lyft-and-uber-are-dismantling-public).

	
    * Also, [Couchsurfing](http://t.co/SPO7kPYHM7), [reputation as commodity](http://www.slate.com/articles/technology/future_tense/2013/11/reputation_economics_privacy_isn_t_a_right_it_s_a_commodity.html), [Dinner with Peers](https://secure.peers.org/page/signup/dinner-with-peers-report?sp_ref%3D17348104.84.996.t.4180.2),




	
  * Ridesharing (and Lyft):

	
    * [and taxis in San Francisco](http://blogs.kqed.org/newsfix/2013/11/07/taxis-lyft-ride-service-war-on-streets-of-san-francisco), and [in Baltimore](http://technical.ly/baltimore/2013/11/06/lyft-uber-ridesharing-baltimore/),

	
    * [insurance](http://taxicabtimes.com/a-proprietary-promise-the-one-million-dollars-that-lies-behind-closed-door-p1998-1.htm)

	
    * Accenture on insurance, parts [1](http://insuranceblog.accenture.com/tag/sharing-economy/), [2](http://insuranceblog.accenture.com/is-that-opportunity-calling-part-2-of-3/?cid%3Dfs_accinsfy14_10000283_smc_0913#sf19108342),

	
    * [parasitic](http://www.popularresistance.org/privatized-ridesharing-is-a-parasitic-business-model/), [entrepreneur!](http://www.fastcoexist.com/3020788/change-generation/how-one-young-car-sharing-entrepreneur-keeps-disrupting-how-we-get-around), [stalker](http://valleywag.gawker.com/when-your-smartphone-chauffeur-becomes-a-stalker-801080008),

	
    * Freelancers: contradictory views [here](http://www.fastcoexist.com/3021147/its-time-for-the-sharing-economy-to-become-the-sharing-society) and [here](https://medium.com/changing-city/f2e12c2748e2). Also [here](http://www.freelancersunion.org/dispatches/2013/10/24/freelancers-are-building-sharing-economy/).




	
  * TaskRabbit:

	
    * [casualized work](http://libcom.org/blog/ten-ninety-nihilists-06112013) ([repeated from here](http://therealnews.com/t2/component/content/article/269-kevin-carhart/1764-the-ten-ninety-nihilists)), [outsourcing](http://www.nytimes.com/2013/11/10/magazine/outsource-your-way-to-success.html?smid%3Dtw-share&_r%3D0),

	
    * [having problems?](http://www.quora.com/TaskRabbit/How-much-revenue-is-Taskrabbit-com-making), [maybe (old)](http://www.businessweek.com/articles/2013-07-09/trouble-at-taskrabbit-is-bad-news-for-the-sharing-economy), [lacking traction](http://www.quora.com/TaskRabbit/Why-is-TaskRabbit-struggling-to-get-traction/answer/Michael-Horowitz?share%3D1&srid%3DuXR), [background checks](http://www.quora.com/TaskRabbit/What-is-TaskRabbits-background-check-process-like),

	
    * [real jobs](http://www.theverge.com/2013/5/23/4352116/taskrabbit-temp-agency-gig-economy),




		
