---
author: Tom Slee
categories:
- blog archive
date: 2006-06-05 09:48:00
title: Blogging about blogging about blogging
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[Cut the Chatter](http://graemeperrow.blogspot.com/2006/05/more-on-blogging-or-moron-blogging.html) noticed my thing about blogging being egotistical, and wrote something much better in reply. Basically, he says that 




  * yes there is a bit of ego in it [agreed - who am I kidding if I say there's no ego involved in writing]


  * he doesn't really care if people read his stuff [I wish I could say the same, but my constant checking of sitemeter gives me away]


  * he enjoys it. And that's reason enough.



Except he says it better. 




The other thing he says is that he enjoys reading other people's blogs. Which I do too. There's the ones I read because they are about a subject I'm interested in, which makes sense. I read the [Mobile Enterprise Weblog](http://mobileenterprise.typepad.com/weblog/) because I'm interested in mobile computing, and I read [StageLeft](http://www.stageleft.info/) because it's a left-wing Canadian take on politics. The ones that have really surprised me are the ones about daily lives though. My favourite along those lines, which is now being turned into a book, is [Random Acts of Reality](http://randomreality.blogware.com/blog), which is by an emergency medical technician working for the London Ambulance Service. Whenever I think my job is stressful, I just have to read his and I stop worrying about my own job. Like [a few days ago](http://randomreality.blogware.com/blog/_archives/2006/5/30/1993670.html):

<blockquote>I went to a stabbing yesterday - while we'd normally wait for the
police to arrive to escort us into the house, the way that the job was
sent down to us over the computer terminal let me think that I could
safely approach.
  

  

The doorbell was answered by a young man with an obvious wound to the upper arm.
  

  
Getting him onto the ambulance I learned that he had 'come clean'
to his long-term girlfriend about cheating on her two years ago. During
the course of the argument she had then stabbed him in the arm with a
kitchen knife...  

  
My advice to everyone is that you shouldn't have an argument in the kitchen...

> 
> </blockquote>

My brother likes a similar one by a policeman, "[PC Copperfield](http://coppersblog.blogspot.com/)" of "Newtown", whose day includes things like this:

<blockquote>I had to accompany a burglar to the local hospital because an injury he
had sustained in the course of one of his crimes had become infected
(poetic justice indeed). I had to sit handcuffed to him in the waiting
room for an hour or so and eventually had to answer the call of nature.
I removed my end of the handcuffs and attached them to the immovable
waiting room chair before going to the toilet and collecting a few
things from the car. On my return he said he felt humiliated, like an
animal.
> 
> 

> 
> People of Newtown, I do what I can.
> 
> </blockquote>




And then there are those other ones you just come across where someone is writing about their trip to Canada's Wonderland or whatever, and it's fun to read it. I really don't know why that is. Kind of like looking at other people's photos on Flickr. Sometimes you find [links](http://das-l.livejournal.com) to entertaining things like [apartment music](ttp://www.youtube.com/watch?v=w1UpHUN2PEM&amp;eurl=http%3A%2F%2Fwww%2Efl0ppy%2Enl%2Fpage%2Ephp%3Fid%3D110). It's a real timesink, but an enjoyable one.




- and no, I'm not writing and reading this stuff at work. I'm off today.


		
