---
author: Tom Slee
categories:
- blog archive
date: 2008-04-19 00:50:41
title: Linux Grows Up and Gets a Job
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Linux started as a hobby project. But it is now 17 years old and it has grown up, and a [recent report by the Linux Foundation](http://www.linux-foundation.org/publications/linuxkerneldevelopment.php), which extends [a series of investigations by Jonathan Corbett](http://www.linuxworld.com/news/2007/092007-kernel.html?page=1), shows that it is no longer a hobby, it is out in the working world.




The report looks at the Linux kernel, and so does ignores all those other pieces of the operating system (drivers, applications, desktop interfaces and so on). Still, the kernel is the heart of the OS and "one of the largest individual components on almost any Linux system. It also features one of the fastest-moving development processes and involves more developers than any other open source project." So this report, which "looks at how that process works, focusing on nearly three years of kernel history as represented by the 2.6.11 through 2.6.24 releases." is a valuable window on what may happen to successful open source projects as they mature.  
  
One of the highlights: "over 70% of all kernel development is demonstrably done by developers who are being paid for their work". 14% is contributed by developers who are known to be unpaid and independent, and 13% by people who may or may not be paid (unknown), so the amount done by paid workers may be as high as 85%. The Linux kernel, then, is largely the product of professionals, not volunteers.  
  
So Linux has become an economic joint venture of a set of companies, in the same way that [Visa](http://en.wikipedia.org/wiki/Visa_%28company%29) is an economic joint venture of a set of financial institutions. As the Linux Foundation report makes clear, the companies are participating for a diverse set of commercial reasons. Some want to make sure that Linux runs on their hardward. Others want to make sure that the basis of their distribution business is solid. And so on, and none of these companies could achieve their goals independently. In the same way, Visa provides services in many different locations around the world in different sizes and types of stores. Some banks need their service mainly in one country, some in another, but when they work together they all get to provide their services all around the world.  
  
This does not mean that Linux was always a commercial venture, or that all open source projects are commercial ventures. To invoke another parallel, open source software is a creative venture like music. Many people create music for all kinds of reasons. Most people create music for an audience of one when they hum in the kitchen or sing in the shower. A smaller (but still huge) number of people get together to form groups or participate in orchestras or bands. They don't earn a living from it, but they love doing it and enjoy their performances. Some might dream of hitting the big time, others are happy being part of their community. Then a much smaller set of people take it a step further. Maybe they are paid to be in an orchestra; maybe they are in a band with a manager and bar gigs around the country. And a lucky few, of course, hit the big time. They get a record deal, find a big audience, and make some real money.  
  
So is music produced for love or for money? Both of course, in various proportions across the spectrum. Open source started off as a small-scale set of projects done mainly by volunteers. As the scale and scope of open source projects an increasing number have provided their contributors with some money (augmented perhaps by a waitressing job). Now a few of the most successful have hit the big time and become full-scale economically important commercial enterprises.  
  
Things change. As open source software has matured and expanded it has become both more unlike the rest of the world and more like it. It will be fascinating to see what comes next, but the Linux Foundation report has made clear that open source has crossed its commercial Rubicon, and there is probably no going back.




Update: follow-up and response to some discussion [here](http://whimsley.typepad.com/whimsley/2008/05/linux-again.html).


		
