---
author: Tom Slee
categories:
- blog archive
date: 2006-01-08 20:45:00
title: 'FootBinding: Search for the Three Inch Golden Lotus'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

So the other day LS was watching [FootBinding: Search for the Three Inch Golden Lotus](http://www.movingimages.ca/catalogue/Cultdiverse/footbinding.html). Part of the show was about whether footbinding was really oppressive, given that the choice to bind was usually made by mother, who had herself been bound. In particular, "Columbia University Professor Dorothy Ko mounts her show _Every Step a Lotus_ and contends that footbinding was not the tragedy modern thinkers make it out to be"




In Dorothy Ko's [book of the show](http://www.ucpress.edu/books/pages/9687.html) "she contends that footbinding was a reasonable course of action for a woman who lived in
a Confucian culture that placed the highest moral value on domesticity,
motherhood, and handwork."




There is no contradiction between reasonable courses of action and tragedy. It is quite possible for people to make choices and still be oppressed: what matters is the system of incentives. In this case, the origin of the exploitation is in the value given to bound feet (by a patriarchal culture), not in any coercion to bind: once the right incentives are set, coercion is no longer needed. Given that a woman with bound feet would have a better chance at a stable or prosperous future than one without, it made sense for women to choose to bind their daughters' feet. The cost to the decision was high (and higher, of course, for those of lower status who had no others to do work for them, and for whom the binding process started later, if at all), but not as high as the cost of failing to secure a good marriage.




This idea -- that there can be no exploitation as long as people are given choices -- is present today in a lot of free-market arguments. Why not give children the opportunity to work in sweatshops? It gives them a chance to be better off than they would otherwise be. Or, as Gary Becker [argued recently](http://www.becker-posner-blog.com/archives/2006/01/should_the_purc.html#comments), why not let people sell their internal organs for transplants?




Footbinding is a compellingn example of how oppression is perfectly compatible with individual choice (albeit made by mothers, but with their daughters' best interests at heart).


		
