---
author: Tom Slee
categories:
- blog archive
date: 2009-01-20 18:21:22
title: "Mr. Amazon's Bookshop: Doubts About Amazon"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[This is the fifth instalment of Mr. Amazon's Bookshop. A list of all instalments is [here](http://whimsley.typepad.com/whimsley/2008/12/mr-amazons-bookshop.html); the previous instalment is [here](http://whimsley.typepad.com/whimsley/2009/01/mr-amazons-bookshop-what-is-a-book.html).  This instalment was written over the Christmas holiday, well before [Belkingate](http://www.engadget.com/2009/01/20/belkingate-as-new-evidence-turns-up-the-company-keeps-mum/).]  


  


My inability to understand how Amazon worked was the first step in an increasingly tormented relationship with the shop and its owner during the last few months. Two other events pushed me from by early enthusiasm with the peculiar place to a more antagonistic stance.   
  
First, one of the other bookstores in town closed down. Mr. Babbage's _Books with a Difference (Engine_) stocked books that dealt particularly with my old hobby - the steam-driven monstrosity I had built in the stables, and with which I had tinkered on the weekends for years. I bumped into him on the street and he complained that the kids these days bought all their books at Amazon's shop. It's a shame - Mr. Babbage had recommended several good books to me when I visited his shop and also given me several tips at times when I got stuck in the construction of my difference engine. I felt that the world of books was a little poorer for his loss.  
  


The second reason was harder to put my finger on. Even though Mr. Amazon was never at a loss for a book to recommend, I was increasingly disappointed at the predictability of his suggestions, and at the limits of his knowledge whenever I ventured into new areas.  
  
He would recite the comments of others but I increasingly felt that he did so with little conviction. He did not know who these others were or why they wrote what they wrote. One day I asked him what he knew of _The Secret History_ by Donna Tartt and he just told me that someone called _A Customer_ had said that "The Secret History has been one of my favorite leisure-reading selections for several years".

  


I guffawed.

  


He went on to say that "Gary Marfin says it is a very powerful novel and Gary Marfin's real name is, in fact, Gary Marfin." But this told me little - does Gary Marfin have the same refined tastes I do? Unlikely, given that he apparently comes from some place called Sugar Land in Texas: a more un-Whimsley like location I can hardly imagine.  
  
"But what do _you_ think, Amazon, what do _you_ think?" I pestered. All he could come up with was that "329 of 539 customers gave this book five stars" "So what?" I demanded, and actually stamped out of the shop in a huff.  
  
I decided it was time to resolve some of my contradictory impressions about Mr. Amazon's Bookshop. Its virtue is clear - if you know a book he will find it for you. Its limitations are also clear - it is not a real bookshop, for all his postmodernist posturing, and one cannot browse the shelves. For special orders of books Mr. Amazon is impressive, but if I don't go there with a book in mind then all I have to go on are his recommendations. And these, despite the enthusiasm of the young, seemed limited to me.

  
My brow was sorely furrowed all the way home. I fed raw rice to the ducks in the park, but could not even raise a chuckle at the thought of their discomfort as it swelled inside them. But as I approached Whimsley Hall and walked past the stables a thought struck me. Just before going out of business Mr. Babbage had told me that Mr. Amazon had a new trick - instead of going to Mr. Amazon's Bookshop, one could use a difference engine to ask him as many questions as you like. Perhaps, I thought, I could tune my difference engine to ask him for all kinds of recommendations, and then I could get a deeper sense of what his shop augured for the world of books. I was so excited I almost started on this project right away, but my stressful excursion had quite worn me out and I retreated instead to my bedroom and a spoonful of laudanum. Next day, I told myself, I would start up my difference engine and ask a few more questions of Mr. Amazon.


		
