---
author: Tom Slee
categories:
- blog archive
date: 2005-12-15 23:15:00
title: Informed Comment Pessimistic on Iraq
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Here is a depressing observation from Juan Cole at [Informed Comment](http://www.juancole.com/2005/12/high-turnout-expected-as-iraqis-go-to.html):

<blockquote>[The LA Times probably reflects the thinking of a lot of Americans](http://www.latimes.com/news/opinion/editorials/la-ed-iraq15dec15,0,7559925.story?coll=la-news-comment-editorials)
in hoping that these elections are a milestone on the way to
withdrawing US troops from Iraq. I cannot imagine why anyone thinks
that. The Iraqi "government" is a failed state. Virtually no order it
gives has any likelihood of being implemented. It has no army to speak
of and cannot control the country. Its parliamentarians are attacked
and sometimes killed with impunity. Its oil pipelines are routinely
bombed, depriving it of desperately needed income. It faces a powerful
guerrilla movement that is wholly uninterested in the results of
elections and just wants to overthrow the new order. Elections are
unlikely to change any of this.
> 
> </blockquote>

<blockquote>The only way in which these
elections may lead to a US withdrawal is that they will ensconce
parliamentarians who want the US out on a short timetable. Virtually
all the Sunnis who come in will push for that result (which is why the
US Right is silly to be all agog about Fallujans voting), and so with
the members of the Sadr Movement, now a key component of the Shiite
religious United Iraqi Alliance. That is, these elections lead to a US
withdrawal on terms unfavorable to the Bush administration. Nor is
there much hope that a parliament that kicked the US out could turn
around and restore order in the country.
> 
> </blockquote>


		
