---
author: Tom Slee
categories:
- blog archive
date: 2011-04-29 22:47:28
title: 'Facebook-style democracy: only if it suits'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Facebook has been deleting accounts of activist groups in the UK, according to [the Guardian](http://www.guardian.co.uk/uk/2011/apr/29/facebook-activist-pages-purged) and to [students at University College London](http://blog.ucloccupation.com/2011/04/29/over-50-political-accounts-deleted-in-facebook-purge/), in what Adbusters is calling a [#zuckup](http://www.adbusters.org/blogs/adbusters-blog/zuckup.html). Complaints are, of course, on a [Facebook page](https://www.facebook.com/pages/Stop-Social-Network-Censorship/145984358805461).




Luckily, friendly old Liam says Hi on Facebook's behalf, and [explains](http://blog.ucloccupation.com/2011/04/29/facebook-forced-to-respond-to-our-campaign-for-restoration-of-accounts/) that terms of service technicalities outweigh speech:




<blockquote>

> 
> _Hi,_
> 
> 

> 
> _As you may know, Facebook profiles are intended to represent __individual people only. It is a violation of Facebook’s Statement of __Rights and Responsibilities to use a profile to represent a brand, __business, group, or organization. As such, your account was disabled __for violating these guidelines._
> 
> 
</blockquote>




Meanwhile, as Jillian York [explains](http://www.foreignpolicy.com/articles/2011/04/29/freedom_fail?page=0,0) in Foreign Policy, Facebook has never identified with the liberation claims made on its behalf. Here is Adam Conner, reported in the Wall Street Journal [a week ago](http://online.wsj.com/article/SB10001424052748703789104576273242590724876.html):




<blockquote>

> 
> "Maybe we will block content in some countries, but not others," Adam Conner, a Facebook lobbyist, told the Journal. "We are occasionally held in uncomfortable positions because now we're allowing too much, maybe, free speech in countries that haven't experienced it before," he said.
> 
> 
</blockquote>




My only gripe about Jillian York's article - she has been critical of Facebook for some time, unearthing and publicising some of their shadier actions - is that she suggests that "American companies ultimately have a tough choice to make: Uphold American values and the principles of Internet freedom set forth by [Hillary] Clinton, or focus on the bottom line." For some companies, at least, this is not a tough choice at all.


		
