---
author: Tom Slee
categories:
- blog archive
date: 2008-10-24 13:42:24
title: All the Web's a Stage
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Timothy Lee has an excellent [post at Freedom To Tinker](http://freedom-to-tinker.com/blog/tblee/trouble-free-riding). Here is some of it:

<blockquote>[T]alking about "free riding" as a problem the Wikipedia community needs to solve doesn't make any sense. The overwhelming majority of Wikipedia users "free ride," and far from being a drag on Wikipedia's growth, this large audience acts as a powerful _motivator_ for continued contribution to the site. People like to contribute to an encyclopedia with a large readership; indeed, the enormous number of "free-riders"—a.k.a. users—is one of the most appealing things about being a Wikipedia editor.
> 
> This is more than a semantic point. Unfortunately, the "free riding" frame is one of the most common ways people discuss the economics of online content creation, and I think it has been an obstacle to clear thinking.
> 
> </blockquote>

<blockquote>The idea of "free riding" is based on a couple of key 20th-century assumptions that just don't apply to the online world. The first assumption is that the production of content is a net cost that must either be borne by the producer or compensated by consumers. This is obviously true for _some_ categories of content—no one has yet figured out how to peer-produce Hollywood-quality motion pictures, for example—but it's far from universal.  
Moreover, the real world abounds in counterexamples. No one loses sleep over the fact that people "free ride" off of watching company softball games, community orchestras, or amateur poetry readings. To the contrary, it's understood that the vast majority of musicians, poets, and athletes find these activities intrinsically enjoyable, and they're _grateful_ to have an audience "free ride" off of their effort.
> 
> The same principle applies to Wikipedia. Participating in Wikipedia is a net positive experience for both readers _and_ editors. We don't need to "solve" the free rider problem because there are more than enough people out there for whom the act of contributing is its own reward.
> 
> </blockquote>

You can see how we got into this problem. Britannica is an encyclopedia and it is an economic enterprise. Wikipedia ends in pedia so it must be an economic enterprise too. But it is not, and we should look elsewhere for our analogies. Once we stop thinking of Wikipedia in economic terms the supposed paradox disappears. Small wonder that, as Lee says, economists are the ones who have the hardest time understanding it.

Amateurs have performed on other world-stages before now. Sports provides prominent examples: rugby union,Wimbledon and the Olympics were all amateur-only for many years. What happened, of course, is that although these stages were not economic for their participants, the hosts ended up with a lot of money once the world of television and advertising intruded. And once the hosts got money the performers started acting like economic agents too and demanded their share. Giving an amateur performance on a non-profit stage is not a paradox, but giving an amateur performance on a profitable stage is being a sucker.  


  


Wikipedia, for historical reasons, has so far kept advertising and profit out of the picture. But other "platforms of mass collaboration" have not - Amazon, YouTube, IMDB, Bebo have all shown that the owners of the stage can make a lot of money. And once they do, it's only so long before the actors start to demand a share, and the whole dynamic changes.   


  


The indiscriminate gushing over the age of mass collaboration has obscured these differences for now, but they won't for long. And then, I would guess, amateur production may go the way of the amateur olympics. But maybe not - let's hope that non-profit stages stay that way so that the economists' misunderstanding of Wikipedia can continue.


		
