---
author: Tom Slee
categories:
- blog archive
date: 2010-11-16 22:37:48
title: What Else Is Wrong With Government 2.0
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

There were some lively comments on [my previous post](http://whimsley.typepad.com/whimsley/2010/11/what-is-wrong-with-government-20.html), which was really only half-finished, so I’m going to write the other half here. But first, let’s get a few things clear.




I like transparency in government. I think it’s great that people campaign for a more open government, especially here in Canada. I am impressed with the kinds of things some people manage to achieve by scraping through government data. 




Got that? OK. Now here is what’s wrong with Government 2.0.






  1. The rhetoric of citizen engagement too often masks a reality of commercialization ([last time](http://www.google.com/url?q=http%3A%2F%2Fwhimsley.typepad.com%2Fwhimsley%2F2010%2F11%2Fwhat-is-wrong-with-government-20.html&sa=D&sntz=1&usg=AFQjCNGgWZAsV_H9moZNwwiNY_UXb_hbow))


  2. Information is not always democratizing.


  3. Information is not always the problem.


  4. Transparency is an arms race.


  5. Privacy is the other side of the coin.


  6. Money flows to Silicon Valley.




So, one at a time.




**Information is not always democratizing**




In comments on the previous post, [Kevin Donovan](http://www.google.com/url?q=http%3A%2F%2Fwhimsley.typepad.com%2Fwhimsley%2F2010%2F11%2Fwhat-is-wrong-with-government-20.html%23comment-6a00d83451d3b369e20133f5d6f37b970b&sa=D&sntz=1&usg=AFQjCNHaetl5ip7TO_-mRxvoMZNOzfpugw) and [Fazal Majid](http://www.google.com/url?q=http%3A%2F%2Fwhimsley.typepad.com%2Fwhimsley%2F2010%2F11%2Fwhat-is-wrong-with-government-20.html%23comment-6a00d83451d3b369e20133f5e3158b970b&sa=D&sntz=1&usg=AFQjCNEIedTNOUBU66fk5uy-zv3NW1qzxA) both pointed to [this article](http://www.google.com/url?q=https%3A%2F%2Fgurstein.wordpress.com%2F2010%2F09%2F02%2Fopen-data-empowering-the-empowered-or-effective-data-use-for-everyone%2F&sa=D&sntz=1&usg=AFQjCNEb-c8LkW2irKh7Hw7DzbPjoRjcOQ) by Michael Gurstein, who asks “who is in a position to make “effective use” of this newly available data?” and answers himself 




<blockquote>

> 
> ‘open data’ empowers those with access to the basic infrastructure and the background knowledge and skills to make use of the data for specific ends.  Given in fact, that these above mentioned resources are more likely to be found among those who already overall have access to and the resources for making effective use of digitally available information one could suggest that a primary impact of “open data” may be to further empower and enrich the already empowered and the well provided for rather than those most in need of the benefits of such new developments
> 
> 
</blockquote>




It’s worth reading the whole article, and the example of land ownership record digitization in Bangalore, which “allowed the well to do to take the information provided and use that as the basis for instructions to land surveyors and lawyers and others to challenge titles, exploit gaps in title, take advantage of mistakes in documentation, identify opportunities and targets for bribery, among others. They were able to directly translate their enhanced access to the information along with their already available access to capital and professional skills into unequal contests around land titles, court actions, offers of purchase and so on for self-benefit and to further marginalize those already marginalized”




In a [recent talk](http://www.youtube.com/watch?v=E_mTwm5m8DM), Kentaro Toyama asks his audience (at the 8 minute mark), “You and a poor rural farmer are each given a single e-mail account and asked to raise as much money as you can for a charity of your choice. Who would be able to raise more money?” The answer, of course, is that “you” (like me probably urban, western), because we know wealthy people, we have lots of friends with e-mail accounts, we are literate and have lots of experience writing e-mails, and so on. The technology is identical for each, but the result is different because of the context in which it is being used. The Internet does not democratize. Instead, technology amplifies people’s ability to get things done, and the more ability you start with, the more you get.




How would this work with Open Government? How about the "Open311" services ([http://open311.org](http://www.google.com/url?q=http%3A%2F%2Fopen311.org%2F)%2C&sa=D&sntz=1&usg=AFQjCNH9aqYCr-1uQTBGzISj5pF-WBW30Q)) which let citizens report non-emergency issues to local government. The archetypal case is potholes that need fixing. If these services come into widespread use, they will be pushed to skew services towards neighbourhoods where people report most frequently (else why implement the service?), which will be the smartphone-owning home-owning better-off neighbourhoods. The better off get better services.




**Information is not always the problem**




The pothole reporting case is an example of this too. Round the corner from my house is a very rough patch of street that has been that way for a couple of years. The city knows it’s in bad shape. Why isn’t it being fixed? Because there are other, busier stretches of road that are higher priority. Information is not the problem; resources are the problem. There is no group of city workers sitting round waiting for a call about a pothole so they can go out and fix it.




In a different vein, it’s worth reading [danah boyd’s talk](http://www.google.com/url?q=http%3A%2F%2Fwww.danah.org%2Fpapers%2Ftalks%2F2010%2FGov2Expo.html&sa=D&sntz=1&usg=AFQjCNFoC3NIzEHqsuZghqHsrZuXGiMXBQ) about unintended consequences of transparency when not accompanied with interpretation. Raw data such as the registered sex offender list certainly counts as “open government” but she retells an expose from The Economist which began 




<blockquote>

> 
> with the story of Wendy Whitaker who was arrested in 1996 at the age of 17 for having oral sex with a classmate three weeks shy of his 16th birthday. She was convicted of sodomy against a minor, ended up in jail for a year and is now listed on the registry. "She sees people whispering, and parents pulling their children indoors when she walks by." Not only did she have to pay the price for her teenage indiscretions by going to jail, but she's forced to deal with them day-in and day-out for the rest of her life. Because of the registry. I wish that I could say that Wendy's story was rare, but I hear stories like this over and over again. People's lives ruined because of the registry.
> 
> 
</blockquote>




Seeing the problem as one of information can lead us down the wrong path. As boyd says:




<blockquote>

> 
> In focusing on the first step – transparency or access – it’s easy to forget the bigger picture. Internet access does not automagically create an informed citizenry. Likewise, transparent data doesn’t make an informed citizenry. Transparency is only the first step. And when we treat transparency as an end in itself, we can create all sorts of unintended consequences.
> 
> 
</blockquote>




**Transparency is an arms race**




The Open Government initiatives are getting lots of information out into the public that wasn’t effectively public before. That’s good. But now that the information about, say, voting behaviour and donations is open there is a clear incentive for donors and donation recipients to muddy the waters. Intermediaries will appear. Money will be exchanged not as donation but in some other form. I’m sure there are endless ways of working the system, now it needs to be worked. Systems respond to changes, and in this case a move to transparency will be met by a move to obfuscation.




**Privacy is the other side of the coin**




There is one essay in the [Open Government](http://www.google.com/url?q=http%3A%2F%2Foreilly.com%2Fcatalog%2F9780596804367&sa=D&sntz=1&usg=AFQjCNEeUCHXvFke9arCa0X_uOTiljCw3A) collection (by Jeff Jonas and Jim Harper) that addresses privacy concerns. Once data is targeted to be made public, it becomesimportant that improper or inappropriate data not be bandied about. So they recommend such strategies as limiting backups (!), destroying old data, “minimal disclosure in transfer between projects” (which goes counter to the Gov 2.0 direction) and more. It’s almost like the arms race, except instead of mischievously hiding data that could harm yourself, IT professionals are dutifully hiding and destroying data that could harm others.




Data anonymization and aggregation are often cited as ways of handling these issues, but recent developments in “re-identification” have shown that such efforts may be doomed. The identification of individuals within the Netflix Prize data set ([paper](http://www.google.com/url?q=http%3A%2F%2Fwww.cs.utexas.edu%2F~shmat%2Fshmat_oak08netflix.pdf&sa=D&sntz=1&usg=AFQjCNEHjZO8ch3c5lUlweSsdoiT0UYPKg)) led to the cancellation of the second Netflix contest, and has cast a chill on crowdsourcing contests. Legal scholar Paul Ohm’s recent long but highly readable paper on [Broken Promises of Privacy](http://www.google.com/url?q=http%3A%2F%2Fepic.org%2Fprivacy%2Freidentification%2Fohm_article.pdf&sa=D&sntz=1&usg=AFQjCNHZNOT07IY6ZvNaEb4f9JnpvUccAw) suggests that we need to re-assess the basis for many of our data privacy laws because information previously thought to be anonymous has now got to be treated as potentially privacy-damaging.




Bill Schrier, [CTO for the City of Seattle](http://www.google.com/url?q=http%3A%2F%2Fwww.seattle.gov%2Fdoit%2Fabout.htm&sa=D&sntz=1&usg=AFQjCNFpjK3fQOf8Q2mbrNqH4mHuJsR3HQ), addresses privacy in an essay in the Open Government collection. As just one example, many elected officials maintain lists of email addresses for use in contacting constituents, and these lists are a common target for public disclosure requests. It is difficult to prevent misuse of these lists for spam emails and other inappropriate uses. Open Government is good, but receiving penis or breast-enlargement emails as a result of emailing your councillor? Not so much. Other examples he has come across include a chilling effect on grievances because complaint investigations are public records, and the city being forced to provide a complete list of full legal names and dates of birth to a local radio station, “two of the three pieces of information needed to steal employee identities”. Schrier is an open government advocate, but making this data public is “not a trivial or inexpensive task” if it is to be done with care. As he asks, “most of [the problems] can be overcome. But do we really want to make it that easy for everyone to obtain and use that data?”




**Money flows to Silicon Valley**




I’m not quite sure how to articulate this final point, but as I haven’t seen it elsewhere I’ll give it a go. Let’s take an example. Google and the City of San Francisco developed a format the General Transit Feed Specification, [which](http://code.google.com/transit/spec/transit_feed_specification.html) “defines a common format for public transportation schedules and associated geographic information.” Using this, cities can push their transit schedules to Google for publication on Google Maps. 




Useful, for sure. I love to be able to plan trips and Google Maps is a convenient way to do it. But there is a downside, which is that a purely local transaction, of me planning a bus trip in my home city, now involves sending money (via advertising) to California. The winner-take-all nature of the Web means that an increasing number of apparently local exchanges are done via California, such as personal ads via Craigslist. Is that a good thing for the local economy? How would we feel if it weren’t Google but a Chinese company that got the information and the money along with it?




So am I opposed to Open Government? No, but I’m far from convinced that the digital approach to the problem will actually lead to an increase in openness.


		
