---
author: Tom Slee
categories:
- blog archive
date: 2007-02-18 20:57:22
title: The Long Tail 1 - The Long Tail
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is part of my critical reader's companion to _The Long Tail_ and discusses "Chapter 1 - The Long Tail". Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). The previous part in this series is [here](http://whimsley.typepad.com/whimsley/2007/02/youll_be_very_g.html).




Chapter 1 starts with the story of the mountaineering book Touching the Void being lifted from obscurity a decade after its publication by online recommendations at Amazon.com. It's a nice story, and while I haven't read the book, the film of Touching the Void is gripping and moving. But what does this story tell us? "By combining infinite shelf space with real-time information about buying trends and public opinion, they [online booksellers] created the entire Touching the Void phenomenon... Unlimited selection is revealing truths about what consumers want and how they want to get it." [16]  
  
But this is, after all, just a story, and this is not the first time a product has been lifted from obscurity by a sudden word of mouth. In fact, the opening pages of The Tipping Point feature a story that is very similar - the return of Hush Puppies into style after an extended period in the commercial wilderness, as a result of word of mouth in the New York club scene and then fashion scene. And the Hush Puppy story has nothing to do with infinite shelf space - it may have more to do with second hand and unfashionable clothes stores where the first few people could get their Hush Puppies, before they became trendy again. It is tempting to start thinking "yes, but maybe those tiny stores represent a Long Tail of fashion" but that would be to miss the point of the book, which is that the phenomenon is new and coming from digital technologies. To interpret the Long Tail as "variety" leaves us with nothing but an appreciation of the diversity of the physical world (whose tyranny the infinite digital shelf space will release us from). The world does have a lot of variety, but that is not exactly a new observation. So as in the story about 20 kinds of flour in his introduction, we have to be careful about drawing lessons from Touching the Void, however fine the film is.  
  
The Tyranny of Locality [17-18] is the beginning of this first outline of what The Long Tail actually means. And it is clear that there may be something here. There are limits to much retailing as a consequence of "the need to find local audiences". Geographically dispersed individuals with a taste for something non-mainstream (such as Bollywood movies in the USA) may find their tastes unmet because there are not enough of them in any one place to make it commercially viable to sell to them. The online world allows them to be sold without regard for geography (within a single country anyway, because of shipping) and so may allow more such non-mainstream products to find an audience. Another reason that geography is so limiting is that in the physical world there is "not enough shelf space" to carry everything; not enough screens to show all movies, not enough channels to broadcast all the TV shows [18]. The digital world promises to free us from this: "This is the world of scarcity. Now, with online distribution and retail, we are entering a world of abundance. The differences are profound."  
  
This, then, is the beginnings of the hypothesis. Let's think about two things that might also be going on, not discussed here. One is that there has been a long tradition of getting round some of the limits of the physical world. Anderson quotes The Triplets of Belleville as a movie that was critically acclaimed and yet "opened on just six screens nationwide" [17]. Yet the movie did appear right here in the small city where I live, in physical space, on the local arts cinema. So here is a mechanism (the smaller independent cinema) for diluting the tyranny of space, and it is a mechanism that may actually be threatened by the onset of digital distribution. Or may not - some have struggled and others prospered. The existence of independent arts cinemas in the physical world is a reminder that that world is not as homogeneous as Anderson portrays it.  
  
The second phenomenon is to do with fixed against marginal costs. I'm not going to say much about this here (we'll come back to it in a few chapters) but there are things about digital distribution that are different from the physical world in addition to the length of the shelves. Will these other things mess up the Long Tail hypothesis? We'll see. (hint, yes to a degree, although not entirely). For now, again, let's just remind ourselves as we read that this is a hypothesis, not a theory.  
  
Markets Without End [19-24] talks more about the world of abundance, painting a picture of the long shelf of the new digital world against that of the old constrained physical world. Anderson looks at the Rhapsody online music retail service owned by RealNetworks, whose CEO blurbed the book and compares it to Wal-Mart's CD offerings.  
  
Wal-Mart carries about 4,500 unique CD titles, but Anderson shows by looking at Rhapsody's download data that demand for titles outside that number continues out to at least the 800,000th title (downloaded a few times). "Individually, none of those songs is popular, but there are just so many of them that collectively they represent a substantial market... From the perspective of a store like Wal-Mart, the music industry stops at less than 60,000 tracks. However, for online retailers like Rhapsody the market is seemingly never-ending." [22]  
  
The comparison is not valid, for several reasons.  
  
First, let's think about using Wal-Mart as a "physical shelf" basis for comparison. It's not a specialist store, and although it sells a lot of music by volume it does so by doing just what it does in other areas -- picks the top sellers and limits its stock to just them. Wal-Mart sells far fewer titles than a specialist CD store, just as it sells fewer book titles than a specialist bookstore and fewer toys than a specialist toy store. But it still drove Toys-R-Us to the brink (at the last time I checked) of bankruptcy. If you look at specialist stores the comparison is not so stark and may even go the other way. For example, HMV in the UK [reported](http://www.google.ca/url?sa=t&ct=res&cd=2&url=http%3A%2F%2Fwww.hmvgroup.com%2Ffiles%2F924%2Fchairman.pdf&ei=rF_YRZDZNon2gALQu_nZCA&usg=__NjJkov2tCbv3j_LVCn9u2howoUU=&sig2=VdziAZrJOkUJoBT0veq26w) in 2004 (PDF file - see page 5) that "Whilst the 200 best-selling CD albums account for approximately 56% of the market, these titles in HMV UK are approximately 40% of sales. Similar ratios apply to DVD. So, with approximately 60% of HMV UK’s sales coming from the back-catalogue, the resilience of our model was proven during a year in which it faced the sternest of competitive tests." So the physical world consists of those like Wal-Mart who cherry pick the hits (shortest shelves) followed by the big chain stores like HMV (longer shelves) followed by specialist stores that stock just classical music for example, whose shelves may be short but whose stock complements that of HMV and Wal-Mart. To compare Wal-Mart against Rhapsody is misleading as a portrayal of the physical vs. digital worlds. In fact, numbers from a more recent weblog [posting](http://www.thelongtail.com/the_long_tail/2006/04/an_apparent_lon.html) by Anderson shows that Rhapsody makes approximately 48-50% of its sales from the top 200 albums (it shows data for 100 and 1,000 so this is a rough interpolation), compared to HMV's 40%. Rhapsody, by this measure at least (and there are oth
er measures), is more hit driven than HMV.  
  
There's another problem with choosing Wal-Mart as a basis for comparison. Anderson is looking to compare old models against new (remember that "preview of 21st-century economics" subtitle in the introduction?), but Wal-Mart is just as new as digital technology. Its growth in the US throughout the 1990's parallels that of the Internet. It's no old dinosaur being supplanted by new technology, it is just another face of new technology.  
  
We can think of another model for "the Future of Business", which you might call the Long Vice, in which specialist retailers like HMV and (even more) its smaller independent brethren are being squeezed from both sides. On one side is Wal-Mart, using its economies of scale to provide the hits and cherry-pick that revenue from the specialist retailer. On the other side is the online retailer who can pick up some of the smaller selling items. Whether this leaves us with more choice or less (or a bit of both) is up for grabs, and we can talk more about the forces that drive down choice in the modern economy later on when Anderson goes into "Long Tail Economics" in a little more detail. But at least let's acknowledge that the Long Tail story of old physical Wal-Mart vs new digital Rhapsody is fundamentally oversimplified and fails to make Anderson's case.  
  
Anderson spends most of this section on Rhapsody, and then does similar comparisons in other industries; Borders vs. Amazon, Blockbuster vs. Netflix. I'm just going to talk about Borders vs. Amazon here.  
  
Having set the stage plausibly (but incorrectly, as we have seen) with the Rhapsody story, it seems to be just confirming evidence for the Long Tail hypothesis when he says that Amazon makes 25% of its business from books "not available in offline retail stores" or "products you can't find anywhere but online" [23 - diagram]. But there are two problems. First is that misleading phrasing. We have three new-book bookstores in my town. Chapters sells more books, but Words Worth (our independent book store) sells an overlapping set, and A Mysterious Affair sells a different set too (and then there are Christian book stores and probably other ones I don't know of). So our total number of books "available in offline retail stores" is much bigger than the stock of Chapters. Phrasing the comparison between Borders and Amazon as a comparison between "the offline world" and "the online world" is misleading, just as the Wal-Mart vs Rhapsody comparison was misleading. This is especially so because (again, we'll come to this) there are reasons for thinking that while the physical world is populated by a variety of stores - even though some smaller ones are being threatened by the Wal-Mart/Borders model and (ironically) by Amazon and Netflix -- the online world has forces that encourage natural monopolies (quick, name a pure-play new-book online retailer that isn't Amazon) or at least oligopolies. At the beginning of this post I hypothesized about the role of small out-of-the-way stores in the revitalization of Hush Puppies. It is possible that the new world may have less variety in it than the old.  
  
The second problem with the story has been [pointed out](http://www.charlesarthur.com/blog/?p=543) [elsewhere](http://www.theregister.co.uk/2006/07/27/debunking_long_tail_maths/) and discussed (with honesty, I should add) by Anderson [here](http://longtail.typepad.com/the_long_tail/2005/08/a_methodology_f.html). He says that "One of the most quoted statistics in my [original article](http://www.wired.com/wired/archive/12.10/tail.html) was the data point that 57% of Amazon’s book sales are in the Long Tail, defined as beyond the 100,000 books available in the typical Barnes and Noble superstore". Well, that estimate came from an analysis of Amazon's proprietary data (it does not publish detailed breakdowns of its sales). A revised estimate, included without comment in the book, is that the Long Tail accounts for 25% of sales. This is a downward revision of over half, and yet it has not affected Anderson's thesis or his winning enthusiasm for it at all. You have to wonder about a hypothesis that is so little affected by a big change in its underlying data from the real world.  
  
The chapter finishes, as so many of them do in this book, with a ringing call towards a bright future. "as demand shifts towards the niches, the economics of providing them improve further, and so on, creating a positive feedback loop that will transform entire industries -- and the culture -- for decades to come" [26]. At this stage of the book, we just have to say that the jury is out, but if you are like me, you'll be feeling increasingly suspicious and frustrated by the slippery way in which Anderson is putting together facts, stories, and comparisons to create a misleading picture that, wouldn't you know, supports Anderson's hypothesis. There are forces pushing towards an increased reliance on hits (see Wal-Mart above) as well as pushing out the other way. Some people say that online stores are just as hit-driven as bricks-and-mortar. The burden of proof is on Anderson, especially given the evangelical language he uses to describe what he is talking about. And in this chapter he dramatically fails to make his case.


		
