---
author: Tom Slee
categories:
- blog archive
date: 2009-11-20 11:39:44
title: Pirate’s Dilemma Review Remixed
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_My better half had some suggestions to improve [this essay](http://whimsley.typepad.com/whimsley/2009/11/the-pirates-dilemma-by-matt-mason-a-review.html), so I’m taking a second pass at it here because I liked the original myself and I don't do this kind of writing often so I might as well get it right. The style and content are much the same, it just gets going more quickly._




The lives of many idealistic left-wing youth become enmeshed in compromise as they get older and stoke the fires of capitalism during the day while trying to throw a little water on those same fires at night well I understand how this happens because like many middle-aged people I wrestle with these contradictions myself and admire tremendously those who have stuck to their principles even at a real cost to their careers and personal lives which is why the few people who really piss me off and whom I actively scorn and who get my blood boiling are those like _The Pirate’s Dilemma_ author Matt Mason who dons the mantle of rebellion and anti-corporate politics while consulting for Disney and Pepsi and P&G and who babbles about the benefits of sharing because "it's not all about the money any more" while giving presentations to the people who brought you McDonald's "I'm Loving It" campaign and who praises vitamin water company Glacéau for "keeping it real" in its advertising campaigns with 50 Cent before telling us it was sold to Coca Cola for $4.1 billion and who praises Procter & Gamble for its viral video campaign and who is entranced by the way that Nike's Air Force One sneaker owes its success to the remix and who places himself on the romantic anti-establishment side of the battle between graffiti and advertising in "a turf war that has raged for centuries between the establishment and a secretive, loose-knit network that doesn't like the top-down, one-way flow of information in public spaces" only to approvingly quote advertising agency Droga5 on creating "a dialogue between advertising and graffiti" which really means using graffiti for commercial ends and making a buck and if that's not selling out to the man then what the fuck is really? because the punk spirit Mason loves so much and claims to identify with has nothing to do with business models or change agents or entrepreneurial spirit or brand-building no the spirit he writes of was defiantly and nihilistically anti-corporate and Matt Mason lives in a corporate world however much he'd like to think otherwise so when he claims that pirates are those who are "pushing back against authority, decentralizing monopolies, and promoting the rule of the people: the very nature of democracy itself" well I see what he means but when he goes on to claim that the anti-authoritarian ideals of youth culture are becoming a new more extreme, invigorated, and equitable strain of the free market--the decentralized future of capitalism well I just want to shake him by the neck and shout at him that you're obviously not stupid Matt Mason so why don't you do what you know you should do and FOLLOW THE FUCKING MONEY before making pronouncements about the benefits of sharing when it's still the case that money is not shared I mean if I share and you get the money then I'm not being altruistic I'm just being a sucker and you're not promoting community you're exploiting the good intentions of those who are spending their time and talent on your venture so if you want to impress me with the subversive role of DVD bootlegging DON’T JUST DON’T quote billionaire Mark Cuban and Disney co-chair Anne Sweeney and billionaire Steve Jobs at me because if they have found a way to co-exist with piracy it doesn't mean that they and their companies stand for a more democratic and equitable form of capitalism it just means they've found ways of using or living with piracy in a way that promotes their own interests over those of their rivals its meet-the-new-boss-same-as-the-old-boss-but-with-edgier-clothing time so as you can tell I end up not taking him seriously which is unfortunate because he has many entertaining stories of hip-hop bands and pirate radio stations and punk culture although I don’t know whether to trust them because where the book overlaps with things that I do know anything about he is often ludicrously wrong like when he repeatedly refers to Linux as a company or when he damns record companies for figuring out it's more profitable to control the distribution system than it is to nurture artists while completely failing to notice that big chunks of the Web 2.0 world he loves so much work on exactly the same model by owning the spot where the money is which is the platform that gives control of the distribution system or when he gives us a canned history of Wikipedia which is derived from one interview with Jimmy Wales so it's no surprise that it gets several key facts wrong or when he identifies Steve Jobs with openness and sharing and claims that the notoriously secretive and proprietary Apple won the music wars because it truly understood sharing when the fact is that Apple wants to share the music they don't own but wants to keep the technology they do own all to themselves you can ask Palm about that who can't sync their own phones with iTunes or you can ask the developers who have left the iPhone App Store over Apple's arbitrary and opaque approval process so after reading this book Matt Mason takes a place for me with people from an earlier generation like Kevin Kelly who claims to be a maverick while working for Conde Nast or Chris Anderson who claims to be on the side of small and scrappy businesses against big companies while promoting Amazon at $40,000 an appearance or Stewart Brand and John Perry Barlow who strive to combine activities like consulting for senior management at large corporations with statements like "I'm an anti-company man" if you can believe it I mean DO YOU HAVE ANY SELF_AWARENESS AT ALL do you have any sense of modesty and this matters because these people have been successful in leading young idealistic people with good intentions up the garden path in the belief that they are taking part in something progressive and politically anti-establishment but which ends up just feeding money into the pockets of Silicon Valley venture capitalists and the lucky guys who get to sell their startups to Google for a nice billion or so as if that's a triumph of the little guy give me a break.


		
