---
author: Tom Slee
categories:
- blog archive
date: 2007-03-18 21:50:08
title: The Long Tail 10.1 - A Short Note
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This set of posts has been a lot of fun. Thanks to those who have given me feedback along the way, and to those (like Dave of [How To Furnish a Room](http://howtofurnisharoom.blogspot.com) and [RAD](http://www.radthoughts.com/)) who have linked to it and [said nice things](http://howtofurnisharoom.blogspot.com/2007/03/bravo.html) about it. If you're looking for a book to read, by the way, How To Furnish a Room is a great source of ideas.




I had some notes on each chapter and an idea of what I wanted to do with them once I finished reading The Long Tail, but it really is true that writing is a way of finding out what you think, so my views on the book have expanded along the way.




When I started out, I thought it would be enough to just go through the book as I have been doing, but now I don't think that will quite do the trick. The book is really a Big Picture book, so once I get to the end (four more chapters) I think I'll post a couple of Big Picture posts to wrap it up. Then I'll really have to return the book to the library and read something else.


		
