---
author: Tom Slee
categories:
- blog archive
date: 2009-01-14 21:24:35
title: "Lawrence Lessig's Remix: a rambling review"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				_Remix: Making Art and Commerce Thrive in the Hybrid Economy,_  Lawrence Lessig, Penguin 2008.

Lawrence Lessig's latest book is about how "a regime of copyright built for a radically different technological age"  xvi: numbers in square brackets are page numbers] is inhibiting art, culture, and individual expression in a digital world. His inspiration, as a parent of two youngsters, is the "copyright wars" and the effect they are having on a generation of children and young adults. Copyright does have an important role to play, he argues, but Criminalizing an entire generation is too high a price to pay for a copyright system created more than a generation ago" [xviii].

Surprisingly, given the author, the legal portion of the book is a relatively short final section, in which he outlines some common sense and practical suggestions for change in the regulatory environment of the USA. Instead, most of _Remix_ is a description of what Lessig sees as the nascent and booming digital R/W culture that is under threat; of what kind of new activities are appearing and how they work economically. Lessig is mainly concerned with amateur activities like playing, hobbies, and gossip, and with how digital technology has changed them. Unfortunately, the picture he paints is less full of insight than his legal views. He paints a familiar heavily-photoshopped picture of reality that has now become almost orthodoxy in business and technological circles. <!-- more -->
Lessig's views on culture and how it works include no references to the many writers who have thought long and hard about the subject. No Marshall McLuhan or Raymond Williams or their successors here. Instead, in what is an unfortunate Silicon Valley tendency, he simply ignores the history of the subject and decides to concoct his own ideas about cultures past and future, using "the language of today's computer geeks".

He divides culture, in an appropriately binary approach, into two forms. There is RO (read-only) culture: professionally produced, hierarchical, and characterized by control. In RO culture the role of amateurs is to consume "tokens of culture" (recordings, broadcasts and so on). Then there is RW culture (Read/Write), in which the consumers are also creators. RW culture is the domain of both professional and amateur, it is participatory.

The 20th Century, _Remix _says, saw the RO/RW pendulum swing sharply towards hierarchical and professional RO culture: "Never before in the history of human culture had the production of culture been as professionalized. Never before had its production been as concentrated" [29]. The 21st Century, driven by digital technologies, promises a revival of RW culture, a swing of the pendulum back to a more healthy balance. Healthy because the Internet "enables a wider range of people to speak" [132] and gives a new literacy to amateurs, who can "create in contexts that before only professionals ever knew" [108]. In short, the Internet promises to "democratize" culture by reviving RW forms.

In painting this picture _Remix _unfortunately airbrushes out all the RW culture happening in the 20th century and magnifies the new forms of RW culture emerging in the 21st. As a result it portrays what is actually a shift of activity, from some forms of RW culture to others, as a revival of RW culture.

We can imagine R/W culture as a pyramid of creative activities. Billions of people (including children) take part in creative activities casually, for fun, and we call that "play". A small fraction of those people also take part more intensively and with more skill as a means of self-expression and we call those activities "hobbies" or "interests". A very few skilled people become semi-amateur or professional and even fewer still become rich and famous. A healthy, "democratized" culture supports all the levels of this pyramid.

Let's think about the broad base: play. When my teenage self painted a model airplane, or when my children modify a computer game, we are engaging in exactly the amateur creative activity Lessig labels _W_: we are manipulating "tokens of culture". The big difference between my children's creative pastimes and mine is that theirs, being digital, can be distributed by and monitored by other computers. Three things follow from this.

First, their activities can be counted, and this gives the appearance of a huge growth of new cultural activity (millions of videos on YouTube! millions of photos on Flickr!) But such numbers are largely illusory. Most songs and videos are only ever seen or heard by a handful of friends and family, and this kind of small-scale sharing is really no more dramatic than me painting my airplane and showing it to my family and friends. It's just easier to count.

Second, and this is Lessig's main concern: the law can monitor and control digital play. Many creative activities, like creating music, require us to copy the works, either digitally on a computer or recreating songs on our own instruments. All such activity potentially triggers copyright concerns. Even consuming digital works, as Lessig points out, involves a form of copying the material from one place (a disk) to another (RAM) and processing it. DRM technology embedded in the files themselves, limit the ways in which a work can be copied and processed, even the number of times it can be processed. For material shared in public places, software can search and locate instances of songs, videos, and report back to the copyright owner. The intrusion of law and regulation further into our pastimes and hobbies than ever before is a development full of foreboding, and _Remix_ is at its strongest when drawing attention to the intrusion and the dangers it brings with it. There is, to paraphrase Pierre Trudeau, no place for the state in the playrooms of the nation, and _Remix_ is a strong argument for keeping it out.

There is a third change brought about by digital technology. It makes it possible for a few people to make unprecedented amounts of money from other people playing. As with the law, it is now possible to make money not just by selling us a toy to play with, but each and every time we play with it. Facebook, Youtube and other sites are, as _Remix_ admits, increasingly driven by advertising. While Lessig is incensed at the raising of a generation of criminals, he is unfazed at the thought of raising a generation of commodities, whose attention and interest is a source of revenue for some venture capitalist. At a time when advertising directly to children is under increasing scrutiny, and for good reason, the commodification of friendship and of home videos should make a parent of young children concerned. But it does not.

The serious amateur and the part-time professional occupy a layer just above play in the cultural pyramid. In the non-digital world such a person may play in a band at local bars, or sing in local choirs. They may take singing or guitar lessons, or photography classes. They may even write a rarely-read book. These activities are valuable to the performers themselves and to their audience. Lessig is correct and articulate in arguing that the most dramatic benefit of cultural activity is not in the production of great works, but in large numbers of people finding their voice. These marginal but serious activities also generate income for the heavily-populated lower-income rungs of the professional ladder, as choirmasters, guitar teachers, book editors, sound technicians. In short, these small-scale public activities create the market for the "institutions of literacy" that Lessig correctly points out [108] are so important to the development of a healthy culture.

In the digital world, there is little place for these small-scale activities. Small-scale publishers and bookshops are derided by the digitocracy as "gatekeepers", a purely negative function, while Netflix and Amazon are hailed as promoters of democratization. Nothing could be further from the truth: Netflix will never organize zombie walks in October as my local independent video store does; Amazon will never organize author tours for both eminent and marginal authors, as my local indepedent bookstore does. These stores are not "gatekeepers"; they are a central part of a healthy "democratized" culture. There is a whole rich ecosystem of activities, some paid, some not, around the production of small-scale culture, that Internet evangelists repeatedly ignore as they contrast the blandness of 20th century mainstream TV with the quirkiness of some favourite marginal Internet production. But the mainstream is still here in 2009, helped along by Netflix and Google and Amazon. And marginal, countercultural and avant-garde culture has a long history before Tim-Berners Lee.

Amazon and Netflix's economic efficiency derives from the automation of cultural work: carrying out the functions of distribution and promotion without having to pay people to do it. It may be inevitable, but that doesn't make it welcome. You're a student and want to talk to someone at Netflix? Too bad, because their contact page says "If you are a student, we are unable at this time to grant requests for interviews." In the 21st century the money that would have kept enthusiasts involved and employed in promoting culture is going, as our culture moves more online, to a few very wealthy people in Seattle and Silicon Valley. Democratization? I don't think so.

Here's another trope that has become received wisdom in the world of the Internet: it is surprising that people take part in creative activity for free. As if joining in a game of football or painting a picture is surprising. Tied to economics as many are - the discipline that has the least insight into human motivations of all social sciences - they ask what the incentives are to build RW culture [116]? But, as Grant and Wood explain in their excellent book "Blockbusters and Trade Wars", supply has never been the bottleneck for a healthy culture. Mississipi John Hurt had nothing but a harmonica - not even sight - yet he produced music, along with other talented musicians from all kinds of backgrounds and traditions. People find ways to create culture.

The bottleneck, instead, is in finding an audience. Promotion, seen in Remix as a technical matching problem to be solved by automated recommender systems, is the key to the cultural puzzle. And it is not yet proven that the Amazon's and Netflixes of the world are better ways of promoting a diverse culture than the messy mix of older, smaller-scale institutions.

Lessig's optimism regarding the future of serious amateurs and part-time professionals comes from his conviction that the worlds of the amateur and the professional can be reconciled on the Internet in the form of "hybrid economies", where sharing and selling coexist side by side. Such mixtures are vulnerable, as he recognizes. Those who would contribute happily to non-profit Wikipedia do not contribute so happily if the fruits of their efforts are being pocketed by others.

A key chapter of the book is devoted to classifying these sharing and commercial economies; labelling them as communities and community spaces and collaboration spaces. Unfortunately the result is a smattering of examples of attempts to mix money and non-commercial motivations, with varying degrees of success, and little to back up his conviction that the future will see a happy and democratic creation of hybrid models in which creators and platform owners each benefit.

Lessig describes himself as a Lefty, but it is a leftyness of a peculiar Silicon Valley type in these pages. If we take leftyness as being on the side of the underdog, then his attitude to copyright law and regulation makes sense: copyright law can be a way for big companies to limit little people.

But while Lessig doesn't like "professionalism", he has no problem with free markets, or with the commodification of increasing swaths of our lives. His vision of the future of hybrid economies is uncritical. He adopts a Silicon Valley anti-establishment stance by saying that, given a choice between the successful dinosaurs or the hungry upstarts "my taste is for the hungry upstarts" [142]. But given a choice between independent bookstores and Amazon, he's on the side of Amazon and sees the small publisher as "professional" and part of the old, RO culture.

For many cultural and artistic movements there is a "counter-cultural moment" when a previously obscure and out-of-the-way tendency suddenly gains prominence. It may be the surrealists in the '30s, Bauhaus in the '20s, the hippy movement in the late '60s, punk in the late '70s - each had a few years in which it was both important and
yet still opposed to the mainstream. But that counter-cultural moment is short, often just a handful of years, and once it is over, the movement either becomes the mainstream or fades away. Only nine years after the summer of '67 the hippies were a thing of the past and punk set itself up in direct opposition to the pompous and irrelevant dinosaurs that "progressive rock" bands had become.

"Geek culture" has had its counter-cultural moment. It's over.

It is now several years since Wikipedia started, four years since blogging, ten years of Google. When it talks of "hungry upstarts" _Remix _lists Google, Yahoo! and other companies formed by Stanford dropouts, but a few years on, these upstarts (to the extent that Stanford vs Harvard [142] was ever a battle of underdog vs establishment) are now the establishment. Netflix partners with Wal-Mart, Google partners with CBS, Amazon is bigger than any of those "establishment" bookstores it challenged and pushes around publishers with impunity. Geek culture is now mainstream. Google, Amazon, Netflix have passed their counterculture sell-by date.

Lessig is recognized as a leader of admirable efforts to introduce copyright reform issue. The legal reforms which he briefly sketches in the final part of the book are well thought out and practical: deregulating amateur creativity, establishing clear title, simplifying copyright, decriminalizing the copy, and decriminalizing file sharing. His suggestions for changes we need to our norms are also fine so far as they go: extending the norms that govern text (the right to quote small parts of text for example) [275] to other areas of culture where there is no such leeway [104]; making copyright "opt-in" rather than "opt-out", and "rediscovering the limits of regulation". But that last one is a marker of the failings of the book. Ironically timed, given the current financial mess, _Remix_ misses the point that we need also to learn the limits of markets, and the dangers of commodification.		
