---
author: Tom Slee
categories:
- blog archive
date: 2006-06-05 08:02:10
title: Bob Rae
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[Yappa Ding Ding](http://yappadingding.blogspot.com/2006/05/trash-talking-leadership-candidate.html) is all in favour of Bob Rae [for leader of the Liberal Party](http://yappadingding.blogspot.com/2006/05/why-i-endorse-bob-rae-as-federal.html). I'm no Liberal Party member, so my views count for exactly what you paid to read them. But I can't agree with this.




It's not that I think Bob Rae left the province a smoking wreck or anything like that - although the man himself [suggests](http://www.bobrae.ca/en/inthemedias.php#07) that the NDP doesn't know how to govern ("The NDP are good at how to distribute the cake, but not how to make the cake."). Rae Days aside, the popular picture of the NDP provincial government of the time doesn't have a whole lot of relation to the reality. 




It's something else that bothers me. It's this whole thing of people joining parties at the top. To hear Bob Rae, or Belinda Stronach, or Jean Charest, suddenly start talking about the traditions of the Liberal Party just makes my stomach turn over. Here is the front page of his web site:

<blockquote>The Liberal Party of Canada is one of the world's great political
institutions, and I feel fortunate to have the opportunity to seek its
leadership. During this exciting and important time for Liberals, I
encourage you to play an active part in the Party's renewal and
leadership process.
> 
> </blockquote>

Excuuuuse me. Is that what you thought all those years you were with the NDP? Or would you say it about any party that might provide you with a route to power?




I know, it's not like a political party is a sports team that you [support](http://www.pnefc.premiumtv.co.uk/page/Home/0,,10362,00.html) through thick and thin for no good reason whatsoever, even when they let their manager go to the competition and so waste next year's chances of reaching the premiership, the idiots. I mean what were they thinking? It's obvious that Billy Davies has a huge amount to do with the near triumphs of the last two years, and PNE lets him go without a murmur? Jokers. 




Sorry - what was I saying? Oh yes. Changing your mind is OK, but either his political past counts for something or it doesn't. Bob Rae seems to want the best of both worlds - he wants to disavow his NDP past ("I drifted" he says) and yet his only real qualification as a potential prime minister comes from his NDP background and all the work that those in the NDP did to put him in the premier's office. As someone who knocked on a fair number of doors in that campaign, I resent his attitude - he wants to capitalize on the work that many volunteers did, and yet discredit it at the same time. 


		
