---
author: Tom Slee
categories:
- blog archive
date: 2006-03-17 09:00:43
title: Read the numbers on your fruit
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Is this true? And does it apply in Canada? I will have to find out...

<blockquote>Another little tidbit gleaned from April's _Food & Wine_:
those sticker numbers on your fruit actually mean something. Here in
the US, fruit often comes with stickers on it, sometimes telling you
where it's from and/or what it is. There's also a number, but I never
paid attention to that. But on p. 72 I spotted this interesting bit of
information:
> 
> </blockquote>




<blockquote><blockquote>"[T]he sticker labels on fruit: The numbers tell you how
the fruit was grown. Conventionally grown fruit has four digits;
organically grown fruit has five and starts with a nine; genetically
engineered has five numbers and starts with an eight."
>> 
>> </blockquote>
> 
> </blockquote>




<blockquote>Yesterday I checked out the organic apples at the market, and yes,
the numbers did indeed have five digits and started with a nine.
> 
> </blockquote>

Link: [Read the numbers on your fruit](http://www.megnut.com/2006/03/read-the-numbers-on-your-fruit), via [Boing Boing](http://www.boingboing.net/2006/03/16/howto_decode_the_sti.html).


		
