---
author: Tom Slee
categories:
- blog archive
date: 2008-10-16 22:50:20
title: How Long Will This Post Survive?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Will this post still be here on November 1, 2008? Definitely. I'm not going to remove it and I don't see anyone else doing so.

Will it be here on November 1, 3008? Surely not.

So how long will be here? My guess is about 10 years but I'd be interested in your guesses too.

When it goes, how will it go? The most likely cause of deletion is that I stop blogging and Six Apart deletes my blog. Right now I pay them $5 per month for hosting this blog, and if I stop paying them [they say](http://www.typepad.com/legal/terms-of-service.html) "After cancellation, you will no longer have access to your website and all information contained
therein may be deleted by Six Apart. " I would guess that I'm unlikely to want to blog for more than a few years. I've been doing it for -- pause for quick look up -- nearly three years, and regular readers will know I have to pause for breath even now. I don't think this post exists anywhere else; a search for whimsley on [the wayback machine](http://www.archive.org) shows nothing, so that would be it.

Do Six Apart actually go round deleting the blogs of people who stop subscribing? I don't know although actually I doubt it. At least one typepad blog, the wonderfully named "[wit of the staircase](http://theresalduncan.typepad.com/)" by a now-deceased author is still around. But if they do delete it, probably this post will vanish sometime between 2013 and 2020.

Another way it could go is if Six Apart fold. They are privately owned so their finances are not public, but from what I can tell it's a small operation and they have a history with blogging so I would guess they make enough to pay the rent and more.

But it's not just about this blog post of course. If you sign up with Blogger then it costs nothing, so they don't know when you've stopped posting. So even after you stop, and even after you die, your pages will presumably still be there so long as Google's servers are around.

So if this post survives the most likely issues with Six Apart, what will get rid of it? It's difficult to imagine it being here in 100 years but equally difficult to imagine what, short of global cataclysm, will get rid of it.

Any guesses?


		
