---
author: Tom Slee
categories:
- blog archive
date: 2008-11-19 22:17:49
title: Long Tail stops wagging
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

  


Google CEO Eric Schmidt says:

<blockquote>although the tail is very interesting and we enable it, the vast majority of the revenue remains in the head. And this a lesson that businesses have to learn. While you can have a long tail strategy, you better have a head, because that’s where all the revenue is.
> 
> </blockquote>

and this prompts Long Tail author Chris Anderson to [make several admissions](http://www.longtail.com/the_long_tail/2008/11/does-the-long-t.html):

<blockquote>But there were clearly exceptions to [Long Tail behaviour]. One of the main ones was the irony that there was a very short Head of Long Tail _aggregators_: Amazon, iTunes, Google and their kin dominate their markets to a blockbuster-like degree.   
I blamed this on a still-young market and assumed that even aggregators would fall victim to the flight from one-size-fits-all someday. But [new research](http://www.mckinseyquarterly.com/Strategy/Growth/Using_power_curves_to_assess_industry_dynamics_2222) from McKinsey (free registration req'd) suggests that this sort of radical inequality is increasingly the norm as markets get more networked.
> 
> </blockquote>

<blockquote>"Powerlaws do imply wildly unequal distributions of money, power, celebrity and everything else." - so much for 'democratization'.
> 
> </blockquote>

<blockquote>And it's not just companies. The Long Tail--the powerlaw created by network effects--may be creating _super-celebrity_, too.
> 
> </blockquote>

<blockquote>As I've said many times, both in the book and elsewhere, most of the rewards in the Tail are non-monetary: a larger audience for producers, and more choice for consumers.
> 
> </blockquote>

<blockquote>I'll end by conceding a point: It's hard to make money in the Tail.
> 
> </blockquote>

There's more, and he holds on to some of his assertions, but basically, it's all over for the long tail.


		
