---
author: Tom Slee
categories:
- blog archive
date: 2006-06-30 11:22:44
title: Book Review in This Magazine
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[This Magazine](http://www.thismagazine.ca/) reviews_ No One Makes You Shop at Wal-Mart_ in its July/August 2006 edition. Here is what _This_ has to say:

<blockquote>In our free society, even socially and economically progressive outlooks buy into the notion of personal consumer choice. Don't like Wal-Mart's labour practices? If that's the case, they say, vote with your feet and shop somewhere else. But, ironically, this belief reinforces the unrealistically simplified world view Tom Slee calls MarketThink -- the philosophical bedrock of capitalism -- which claims that rational choices will always lead to good outcomes. By examining the complications arising from the choices we make, Slee shows that free choice is actually a deception, and that instead of consistently achieving the best results, a society based on individual choice will often collectively experience negative outcomes, such as, ironically, a limit to the amount of choice we are offered. The solution? In framing the ideas of social philosophers and economists in an accessible way that brings the philosophical to the realm of the practical, Slee makes a solid case for collective action in a world of choice that is inherently interconected, putting to shame the simplistic assumptions of the free market world view. -- _Vladi Ivanov_
> 
> </blockquote>

**Update: **The review is now [online](http://www.thismagazine.ca/issues/2006/07/walmart.php).


		
