---
author: Tom Slee
categories:
- blog archive
date: 2015-08-01 12:46:47
published: false
title: Wishing on a Star
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				The idea continues to float around that reputation systems provide a high-tech, lightweight and bias-free alternative to heavy-handed government regulation, but the truth is more prosaic: reputation systems are the new human resource departments. Really cranky, erratic, and unaccountable human resource departments.

Danny Vinik's essay in Politico, [Uber vs Laws](http://www.politico.com/agenda/story/2015/07/uber-vs-laws-000172) is a good example of the reputation as regulation perspective (Mr. Vinik was kind enough to talk to Yours Truly for the piece, and I was less than articulate, so this is an attack of _esprit d'escalier)_. Here is Danny Vinik:


<blockquote>Government regulations: The sharing economy, many observers hope, could start wiping them out. As sharing companies build powerful, influential customer-rating systems — think of Uber driver ratings, or Yelp stars —the thinking is that the market itself will increasingly police bad actors and frauds, weeding them out without the need for onerous rules.</blockquote>


There is a simple reason that reputation systems can't replace consumer protection regulation, and it is too often passed over in the middle of discussions: they don't even try to tackle the same problems.



	
  * Take Uber: taxi consumer protection regulations govern the mechanical state of the car and the history of the driver, neither of which passengers can assess.

	
  * Take Airbnb: consumer protections in Bed & Breakfasts address fire safety, or health and safety. Neither is easily visible to the visitor.

	
  * Take the "meal-sharing" companies that offer a meal in somebody's home: consumer protection in restaurants focus on health and safety in the way the food is stored and prepared, which is off limits to patrons.

	
  * Each of these three industries are also subject to accessibility requirements, which the Sharing Economy companies claim don't apply to them, and which doesn't even enter into most customers' ratings.


Consumer protection regulations put quality control on things that customers cannot easily see or assess.





		
