---
author: Tom Slee
categories:
- blog archive
date: 2010-01-17 11:53:39
title: 'Google: warlord in a world of bandits?'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

How to think about Google? 







On the one hand there is its widespread participation in open source projects, its statements in favour of [openness](http://googleblog.blogspot.com/2009/12/meaning-of-open.html), its consistent promotion of [net neutrality](http://www.google.com/help/netneutrality_letter.html), its [recent announcement](http://googleblog.blogspot.com/2010/01/new-approach-to-china.html) about "pulling out" of China, and its [opposition](http://googleblog.blogspot.com/2008/09/our-position-on-californias-no-on-8.html) to California's discriminatory Proposition 8. On the other hand, there is its embrace of [secrecy](http://googleblog.blogspot.com/2009/12/meaning-of-open.html) around its core operations, its willingness to promote digital rights management for big media on Vevo, and its [cavalier attitude](http://www.youtube.com/watch?v=A6e7wfDHzew) to privacy.







Google is a company that frames its actions in ethical terms, and which takes a public stance on issues beyond its immediate commercial concerns, while making it clear that it's a business and it exists to make money. The language makes it easy to think about Google as "good" or "evil", and to search for some commonality among its actions along those lines. If it's good then we can trust it with our private information. If it's evil, then its apparently good actions must be a cloak to hide some more devious intent. [](https://writer.zoho.com/#nen1)[Before anyone accuses me of setting up a straw man here are a few quotes from a [single story](http://www.google.com/hostednews/afp/article/ALeqM5jEl-9AmXQtMXDIWkZvhxDa-0Rtfw) hosted, of course, on Google News. Many more available on request.:






  * "I do think that Google is a bit idealistic; they have a streak there," said Colin Maclay, managing director of the Berkman Center for Internet and Society at Harvard University. 


  * "I do think a good part of this is they want to do the right thing," Silicon Valley analyst Rob Enderle of Enderle Group said of Google. "But none of these decisions are simple."


  * "Google believes that one of its asset values is righteousness," said Gartner vice president and analyst Whit Andrews. "It believes if it was not righteous, it would not make as much money as it does."]




Thinking in good-guys/bad-guys terms leads only to confusion. Despite the language, Google doesn't have ethics, it has interests. Sometimes those interests coincide with ours, and sometimes they don't. 







Some time ago Nicholas Carr [suggested](http://www.roughtype.com/archives/2007/11/understanding_g.php) that complementary goods are the key to understanding Google:




Complements are, to put it simply, any products or services that tend be consumed together. Think hot dogs and mustard, or houses and mortgages. For Google, literally everything that happens on the Internet is a complement to its main business. The more things that people and companies do online, the more ads they see and the more money Google makes. In addition, as Internet activity increases, Google collects more data on consumers’ needs and behavior and can tailor its ads more precisely, strengthening its competitive advantage and further increasing its income. As more and more products and services are delivered digitally over computer networks - entertainment, news, software programs, financial transactions - Google’s range of complements is expanding into ever more industry sectors. 

Nearly everything the company does, including building big data centers, buying optical fiber, promoting free Wi-Fi access, fighting copyright restrictions, supporting open source software, and giving away Web services and data, is aimed at reducing the cost and expanding the scope of Internet use. To borrow a well-worn phrase, Google wants information to be free — and that is why Google strikes fear into so many different kinds of companies. There’s one more twist. Because the marginal cost of producing and distributing a new copy of a purely digital product is close to zero, Google not only has the desire to give away informational products; it has the economic leeway to actually do it. Those two facts — the vast breadth of Google’s complements, and the company’s ability to push the price of those complements toward zero — set the company apart from other firms. 




The idea of complements captures much of Google's strategy, but it has a couple of limitations.






  * IBM uses free Linux to sell expensive hardware and services, just as Gillette famously used cheap razors to sell blades, but Google promotes the free nature of the Web to sell our eyeballs to advertisers, and that's not the same. Most of us are not Google's  customers, we are Google's product.


  * Many of Google's actions are more legal and political than economic.




Maybe I'm splitting hairs, but there is another way to think about Google, that comes from political science rather than economics. It explains why Google provides or secures the provision of some public goods on the Internet while limiting the provision of others; why it is genuinely interested in the long-term health of the Internet as a safe environment for users, and why we still shouldn't trust it with our data.







[Aside: I have a feeling that this post is at best a partial success. At the same time, the purely economic description in terms of complementary goods does not cover much of what Google does. I'd be interested to hear of other frameworks for thinking about Google. Or whether it matters.]







In his posthumously published [Power and Prosperity](http://openlibrary.org/b/OL49543M/Power_and_prosperity), Mancur Olson tells a story of China in the 1920s, when the warlord Feng Yu-hsiang defeated "a notorious roving bandit called White Wolf". Most people in Feng's domain preferred life permanently under the thumb of a warlord to life prone to the periodic invasion of roving bandits, and Olson wondered why? His answer was that even a warlord who wants to extract as much tax from his citizens as possible must look to the future, and unlike a roving bandit that future depends on having a relatively productive population. There is an alignment of interests between the population and the warlord that does not exist between the population and the bandits: it is in the interest of the warlord to restrain his takings and so ensure that his victims have a motive to be productive. The warlord also has a motive to clamp down on crime (other than his own), and to provide public goods that benefit those he taxes. Olson describes this as a "second invisible hand", by which autocrats are guided "to use their power, at least to some degree, in accord with the social interest." In a similar way, in a neighbourhood under the control of organized crime there will be no robberies, only a protection racket.







In many ways the Internet is, of course, a place. There is even a word, netizen, to describe us in our role as citizens of the Internet. And if the Internet is going to be a reasonable place to spend our time someone has to provide those common goods that keep it so - security, community standards, and so on. Who will do so?







Google is a warlord of the Internet, surrounded by bandits. It provides public goods because its revenue (advertisements) depends on a safe and yet wide-open Internet. For Google to make money the Internet must be accessible from Google's search engine: enclosures are a threat to its business, whether they be ad-funded like Facebook or subscription-funded like the Wall Street Journal. Netizens must be comfortable and safe from bandits as they go about their daily electronic lives. Google also clamps down on attempts by companies other than itself to generate revenue from the Internet, for example by pushing the limits of copyright in its book-copying efforts, or by pushing open source software at the client side of applications. 







While autocrats provide some public goods, there is a limit and in Google's case we see that limit in privacy and to some extent in copyright. When CEO Eric Schmidt [says (30 second video)](http://www.youtube.com/watch?v=A6e7wfDHzew) "if you have something that you don't want anyone to know, maybe you shouldn't be doing it in the first place", we have bumped up against that limit. And while we may be grateful to Google for keeping us free from the claims of copyright owners, attempts to restrict advertising on and around content will not find a friend in Google.







So yes, let's appreciate Google's stance on China despite what perceptive critics such as [Evgeny Morozov](http://neteffect.foreignpolicy.com/posts/2010/01/13/doubting_the_sincerity_of_googles_threat) say, but let's not kid ourselves that Google is anything other than an organization with some interests that overlap ours.


		
