---
author: Tom Slee
categories:
- blog archive
date: 2005-11-18 19:57:02
title: Voting With Their Feet?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This blog is a shameless attempt at promoting my forthcoming book, "No
One Makes You Shop At Wal-Mart", which the fine people at [Between the Lines](http://www.btlbooks.com/) are publishing next spring.




The book is an argument against a certain kind of thinking -- a very common way of thinking I call MarketThink.
MarketThink is the belief that (in the absence of government action)
the world really does work according to the rules of the idealized
free-market. MarketThink is the claim that, as long as we can exercise
individual choices, the invisible hand of the free market guarantees
that we get what we want.




The title of the book comes from one
particular phrasing of that claim. Wal-Mart has commonly been
criticised for the damage its edge-of-town stores do to city centres.
In response to these criticisms, one of the arguments that Wal-Mart's
supporters make is that "no one makes you shop at Wal-Mart", and that
if people really felt that Wal-Mart was bad for their cities, they
would not patronize it.




An example of this kind of thinking
comes from Ron Galloway, director of the new film "Why Wal-Mart Works
& Why That Makes Some People Crazy", who said on CNN's Showbiz
Tonight on October 31 that "138 million people vote with their feet to
go to Wal-Mart. And Americans are pretty smart. And I think Wal-Mart,
if Wal-Mart were really doing something genuinely wrong, the American
people would be able to figure it out and not go."  
  
What is wrong and why? Well, that's what this blog is about.


		
