---
author: Tom Slee
categories:
- blog archive
date: 2012-01-20 15:06:41
title: 'Alone Together 1: Stories'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				










[The first of a few reflections prompted by Sherry Turkle's _[Alone Together](http://alonetogetherbook.com/)_.]




The sublime Leonard Cohen [in today's Guardian](http://www.guardian.co.uk/music/2012/jan/19/leonard-cohen):




<blockquote>

> 
> I don't really like songs with ideas. They tend to become slogans. They tend to be on the right side of things: ecology or vegetarianism or antiwar. All these are wonderful ideas but I like to work on a song until those slogans, as wonderful as they are and as wholesome as the ideas they promote are, dissolve into deeper convictions of the heart. I never set out to write a didactic song. It's just my experience. All I've got to put in a song is my own experience.
> 
> 
</blockquote>




The same is true of fiction. Songs and stories are powerful ways of communicating, but literature with an agenda is almost always bad literature, stories with a message are almost always shallow morality tales, and the fables that now pepper popular non-fiction books are often particularly egregious examples. Thomas Friedman's taxi drivers and Malcolm Gladwell's hush puppies are the 21st-century template for books on management, business, economics, politics, and technology only because even badly-told stories seduce us.




Whenever I encounter a story in a non-fiction book my guard goes up, whether it's fictional or a retelling of an actual event. I know that I am being presented with a Trojan horse; there's a message hidden inside and the only reason for telling me the story is to sneak that message past my defenses of scepticism and logic. It's a trick, and critical readers must reject it. At some point the tables will turn and the telling of non-fiction tales will be recognized as the dishonest, slippery tactic that it is, but for now we must simply resist them and the invading armies that they are smuggling. Which makes it all the more surprising that I loved Sherry Turkle's _Alone Together_, because it is full of stories.




More precisely, I loved the first half of the book, devoted to observing how humans react to robots that react to humans. In Part Two she observes humans reacting to other humans through the medium of digital networks and is less successful. Her use of stories is one reason why Part One works and Part Two fails, so lets stay with the robots and Part One for now.




First, if you are going to use stories you might as well tell them well and Turkle does so. She has an eye for a telling phrase that sets her apart from most non-fiction writers. From a robot that "develops its own origami of lovemaking positions" to the titles and subtitles of the book, she coins phrases that evoke the contradictions and tensions that are her subjects. "Alone together", "The robotic moment: in solitude, new intimacies", "Networked: in intimacy, new solitudes".




Second, the stories are not archetypes conjured up simply to illustrate a point, but emerge from the extensive observational work Turkle has done: more than 700 interviews over 30 years, decades of bringing robots to schools and nursing homes, sending them home with children for weeks at a time, watching participants interact with robots and watching herself also. "I think of the product as an intimate ethnography" she writes {xiii} and the credibility of the book comes from this longstanding and far-reaching work.




More importantly, in Part One she uses stories to provoke questions, rather than to provide answers. Consider two examples.




Early on, Turkle writes of visiting the American Museum of Natural History with her then-teenaged daughter Rebecca. They approach an exhibit of two giant tortoises from the Galapagos Islands. Rebecca looks at the one visible, motionless, creature and declares "They could have used a robot".




Turkle was taken aback, and started a discussion with other parents and children in the line-up. Several of the children shared Rebecca's concern for the animal and her unimpressed reaction to its authenticity: it would be better for the tortoise itself not to have been brought all this way; a robot would not make the water dirty; "for what they do, you didn't have to have the live ones." The parents disagree: "The point is that they are real. That's the whole point."




What I like is that the story does not deliver a message, but instead prompts questions in the mind of the reader. In this way, despite its factual origin, the story is more fictional/literary than many. Does authenticity matter? If so, under what circumstances, and why? It's the open-ended nature of the event that makes reading _Alone Together_ an active, questioning experience, and one I found very rich.




That's not to say Turkle doesn't have a message to deliver. She does, and she is clear enough about what it is: "I am a psychoanalytically trained psychologist. By both temperament and profession, I place high value on relationships of intimacy and authenticity." {6} The book is about Turkle's increasing concern, after years of enthusiasm, that social technologies are serving to erode these qualities.




The second story is one that has stayed with me because it gets right to the heart of the issues the book raises around authenticity {74}. Visiting Japan in the early 1990s, Turkle heard tales of adult children who, too distant and too busy to visit their aging and infirm parents, hired actors to visit in their stead, playing the part of the adult child. What's more, the parents appreciated and enjoyed the gesture. It's slightly shocking to western sensibilities, but once we hear a little more context it becomes more understandable.




First, the actors are not (in all cases, at least) a deception: the parents recognize them for what they are. Yet the parents "enjoyed the company and played the game". In Japan, being elderly is a role, being a child is a role, and parental visits have a strong dose of ritual to them: the recital of scripts by each party. While the child may not be able to act out their role, at least this way the parent gets to enact theirs, and so to reinforce their identity as an elderly, respected person.




The story, again, provokes questions in the mind of the reader rather than leading us to a staged conclusion: questions about authenticity, when it matters, and why. Turkle's reaction was "if you are willing to send an actor, why not send a robot?" If it does not matter that the visitor is really a child does it matter if the visitor is really a visitor? Does it matter if the visitor is not really visiting (a phone call)? Or why, as my wife asked, should we see this as less than a visit when we could see it instead as more than a bunch of flowers?




To me, the story and the questions it prompts undermine my confidence in my own judgements: to make me realise that they are more tied up with cultural conventions, more arbitrary and more shallow, than I thought. And if prompting reflection is the point, then that's OK because the story is, again, open ended: it is not hiding a pre-planned answer.




Part Two of _Alone Together_ fails because Turkle's interviews and observations focus on bringing out our discontents (new solitudes) with networking technologies. She has a message, and it's one we can either agree with or argue with, but by approaching this part in terms of discontents she fails to escape being didactic. The slogans have not dissolved, in Cohen's words.




Part One succeeds because it explores the "new intimacies": what is surprisingly seductive about interacting with even the most crude and obviously artificial robots. It's this seduction that is so unsettling: the notion that things are "alive enough" for a given kind of relationship; that the most powerful thing a robot can do is to have needs which we can meet.




There is something of a taboo against robots in Western societies. In the last few years we have grown to accept human-sounding artificial voices (the iPhone's Siri being the latest) but we shy away from artifical human appearance. We permit robots as toys and vacuum cleaners, but their use as companions for the aged or as visible service employees is still outside the realm of the every day (at least for now). Interacting with a visible robot is still a novel experience for those of us outside childhood, and so Part One of _Alone Together_ has a sense of a report from a slightly alien future. What she shows us is how vulnerable we are to the seductions of even the most crude simulations, and for unexpected reasons, and the disquiet this provokes is something worth reflecting on. Taboos are vulnerable to suddenly being washed away, and the technological imperative may yet carry us forward into a world where robots are more commonly present. I share Turkle's concern about what impact that will have. More on that next time.











		
