---
author: Tom Slee
categories:
- blog archive
date: 2011-02-18 16:29:30
title: More Egypt, More Facebook
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

# More sceptical, speculative notes on Facebook's role (warning: 4,000 words. If you're really keen but don't like reading online, [here is a PDF](http://whimsley.typepad.com/files/more-egypt-more-facebook.pdf)).












  * 1 Yes, they used Facebook


  * 2 Facebook As Generational Space


  * 3 Not Since the Sixties…


  * 4 Is Egypt a Velvet Revolution?


  * 5 Does it Matter?


  * 6 Social Movements: Loving and Hating the Media


  * 7 Reinstating the Dysfunctional Relationship with Media


  * 8 In Conclusion













## 1 Yes, they used Facebook







I continue to think that the role of digital technologies in the Egyptian rebellion has been overplayed for the reasons I gave [a few days ago](http://whimsley.typepad.com/whimsley/2011/02/egypts-facebook-revolution-looking-under-the-lamp-post-.html), but it does look like there is an element of truth to the "Facebook Revolution" story.




Digital technologies get used for many things, but the key job they played in Egypt, at least, seems to be social media. Facebook was clearly the big story;






  * Facebook owned "Fully 42% of the country's Web surfing on January 27, the day before Egypt's main ISPs abruptly severed ties to the Internet." - [Threatpost](http://threatpost.com/en_us/blogs/facebook-owned-42-egyptian-web-traffic-blackout-013111).


  * Facebook was explicitly singled out by leading activist Wael Ghonim:


    * On [60 Minutes](http://www.cbsnews.com/stories/2011/02/13/60minutes/main20031701_page2.shtml): "If there was no social networks, it would have never been sparked. Because the whole thing before the revolution was the most critical thing. Without Facebook, without Twitter, without Google, without YouTube, this would have never happened."


    * [And](http://www.cnn.com/video/#/video/bestoftv/2011/02/11/exp.ghonim.facebook.thanks.cnn): "I want to meet Mark Zuckerberg one day and thank him… This revolution started on Facebook."





  * Facebook was where Tunisian and Egyptian activists collaborated ([New York Times article](http://www.nytimes.com/2011/02/14/world/middleeast/14egypt-tunisia-protests.html)).


  * Facebook was where the _April 6 Movement_ and the _We Are Khaled Said_ groups formed, (English language versions [here](http://www.facebook.com/group.php?gid=38588398289) and [here](http://www.facebook.com/elshaheeed.co.uk)) which both built and publicised the presence of mass dissent among the urban youth (dissent was already there in some of the labour unions - see [Anand Ghopal](http://www.foreignpolicy.com/articles/2011/02/16/egypt_s_cauldron_of_revolt) in _Foreign Policy_ for a survey of the many labour actions over the last few years, including the Mahalla strike that led to the April 6 Movement, and gave it its name).




(thanks to Steve Radman for many of these links)




Why Facebook? In some countries digital activists are looking for special tools to help them communicate in covert ways, but in Egypt there was enough democratic elbow room for activists in the student and labour movements to organize in public - although not without risks. Perhaps because of this slight openness, online activity seems to have crystallized around the relatively public forum of Facebook. Facebook was permitted, and the educated, urban members of the younger generation adopted it and used it to push up against the limits of acceptable dialog.













## 2 Facebook As Generational Space







Another reason might be that Facebook is still a generational phenomenon (60% of Egypt's Facebook users are under 25 ([>>](http://www.spotonpr.com/mena-facebook-demographics/))). It is an environment where youth feel more at home than the older generation and the authorities, at least for now. And like other generational phenomena, it seems that Facebook plays into a sense of identity for students and youth. Ghonim's comments show that some, at least, feel a sense of ownership of this space: it is theirs, not the older generations.




Generational spaces can be both public and private at the same time. The schoolyard is one such space, where (as Iona and Peter Opie documented half a century ago in [The Lore and Language of Schoolchildren](http://openlibrary.org/works/OL2619550W/The_lore_and_language_of_schoolchildren)) a separate culture can persist, out in the open, under the noses of the rest of society.




Other such generational spaces are less physical. Popular music may qualify at various times. The concerts, gatherings, dress, and attitudes built around it are passed from one teenager to another, while (for the most part) adults are clueless as to what is going on.




Like popular music and the schoolyard, Facebook is urban, social, and generational and its inhabitants have a strong sense of ownership of "their" space. Could Facebook's role be similar to that of popular music in earlier protests?













## 3 Not Since the Sixties…







It pains me to say it, really it does. The "reminiscent of the 1960's" cliche has been used to describe every significant protest in the last 40 years that involves more than five people and a street. But the parallels are too many to ignore, and they emphasize the fact that, despite the technology, Egypt is not a fundamentally different "Revolution 2.0".




Here are some quotations from just one short source: Sean O'Hagan's essay "[Everyone to the Barricades](http://www.guardian.co.uk/world/2008/jan/20/1968theyearofrevolt.features)", published two years ago in The Guardian.




<blockquote>

> 
> 1968 was "a year in which mass protest erupted across the globe, from Paris to Prague, Mexico City to Madrid, Chicago to London."
> 
> 
</blockquote>




O'Hagan quotes Jon Savage on the role that popular music had in amplifying the feelings of a generation:




<blockquote>

> 
> "Pop music is always incredibly prescient and you can hear an increasing ambition and invention in the pop music made in those years, a sense of limitless possibility, but also of immense frustration and edginess. And then, in 1968, it all exploded into something totally unforeseen. In the five years from the emergence of the Beatles in 1963 to the upheaval of 1968 the economic enfranchisement of a generation turned into mass political action, if not fantasy."
> 
> 
</blockquote>




And also this:




<blockquote>

> 
> "I was completely surprised by 1968,' recalls Francois Cerutti, an old-school Marxist and radical bookstore owner quoted in Kurlansky's book. 'I had an idea of the revolutionary process and it was nothing like this. I saw students building barricades, but these were people who knew nothing of revolution. They were not even political. There was no organisation, no planning.'"
> 
> 
</blockquote>




Here is the sudden outbreak, the viral spread from country to country, the rapid politicization of a generation, the seeming spontaneity of protest, that has been so much discussed in Egypt. Here also is the spread of attitudes through a medium that is public, yet generational - popular music in this case, instead of Facebook. These phenomena have been widely credited to the [network nature of the Internet](http://gigaom.com/2011/01/29/twitter-facebook-egypt-tunisia/) and [social media](http://www.huffingtonpost.com/don-tapscott/social-media-key-to-revol_b_823043.html), but the parallels are so clear that it seems unlikely that it's the technological features of the Internet that are making the difference - it's a cultural phenomenon that, in this particular incarnation, is revealed in social media.




The same goes for the [much-trumpeted](http://www.csmonitor.com/Commentary/the-monitors-view/2011/0204/Egypt-s-true-revolution-A-leaderless-movement-fueled-by-universal-values) [leaderless](http://www.huffingtonpost.com/michael-hais-and-morley-winograd/victory-for-egypts-leader_b_822228.html) [character](http://www.thedailybeast.com/blogs-and-stories/2011-02-14/the-internet-generation-egypts-leadership-lesson/) of the rebellion: in which leaders emerge from the protests, rather than the protests being incited and led by experienced politicians. Here is Paris 1968:




<blockquote>

> 
> "In just a few weeks, (Daniel) Cohn-Bendit, who was soon to receive a deportation order from the French government for his role in the ferment, had gone from local student activist to an international figurehead for revolution. 'There I was,' he said, 'the leader of a little university, and in three weeks I was famous all over the world as Danny the Red.'"
> 
> 
</blockquote>




And the similarities continue. Here is O'Hagan on the international importance of that generation's new technology, television, in spreading ideas and attitudes from country to country.




<blockquote>

> 
> "We met through television,' Cohn-Bendit later said of his counterparts in other countries. 'We were the first television generation.' Indeed, the radicals had a much better grasp of the galvanising power of television than the politicians they were trying to overthrow. 'A modern revolutionary group headed for the television, not for the factory,' quipped the late Abbie Hoffman, one of the great political pranksters of 1968 who helped provoke a bloody battle between anti-war protesters and the Chicago police force at the Chicago Democratic convention. As the police attacked them, the protesters chanted: 'The whole world is watching!' And, for the first time, it was."
> 
> 
</blockquote>




Here is Pierre Bourdieu on the importance of television to protesters:




<blockquote>

> 
> "Successful demonstrations are not necessarily those which mobilize the greatest number of people, but those which attract the greatest interest among journalists. Exaggerating only slightly, one might say that fifty clever folk who can make a successful 'happening' get five minutes on TV, can have as much political effect as half a million demonstrators."
> 
> 
</blockquote>




Egypt's rebellion, while of course it is unique, is not a new type of rebellion. There are parallels to other rebellions, including the use of cultural space where the ideas and dreams of a generation could be shared in a semi-public fashion, and the use of new media technology to spread the word to a wider public.













## 4 Is Egypt a Velvet Revolution?







So the Egyptian uprising is not that unique after all. (It's obvious, I hope, that this does nothing to detract from the heroism, creativity, and bravery of those involved). It's not just the student-led riots of 1968; there are similarities to other recent uprisings too, such as the series of "Velvet Revolutions" that spread through Eastern Europe in 1989. Again, let's just look at one source to see what the parallels are. How about Timothy Garton Ash in the New York Review of Books, December 3, 2009? His essay is titled [Velvet Revolution: The Prospects](http://www.nybooks.com/articles/archives/2009/dec/03/velvet-revolution-the-prospects/).




Garton Ash highlights the differences between the "velvet revolutions" (VR) and earlier revolutions:




<blockquote>

> 
> an ideal type of 1989-style revolution, VR, might be contrasted with an ideal type of 1789-style revolution, as further developed in the Russian Revolution of 1917 and Mao’s Chinese revolution. The 1789 ideal type is violent, utopian, professedly class-based, and characterized by a progressive radicalization, culminating in terror. A revolution is not a dinner party, Mao Zedong famously observed…
> 
> 

> 
> The 1989 ideal type, by contrast, is nonviolent, anti-utopian, based not on a single class but on broad social coalitions, and characterized by the application of mass social pressure—”people power”—to bring the current powerholders to negotiate. It culminates not in terror but in compromise. If the totem of 1789-type revolution is the guillotine, that of 1989 is the round table.
> 
> 
</blockquote>




Egypt is clearly in the tradition of the velvet revolutions. The social coalition covers labour, student, and religious groups, and the current uneasy phase of negotiation with the armed forces (as opposed to installing a new leader) is characteristic of the type. Like all the "velvet revolutions", the Egypt uprising is more of a stand _against_ something (Mubarak; corruption; the unfairness of widespread unemployment and high food prices) than _for_ something. Garton Ash writes that




<blockquote>

> 
> "François Furet, the historiographer of the French Revolution, doubted if the velvet revolutions of 1989 should properly be called 'revolutions' at all, since they produced 'not a single new idea.'"
> 
> 
</blockquote>




What is happening in Egypt seems more of a rebellion than a revolution (A rebel, as Camus said, is "someone who says no" (pronoun updated), and this seems to describe the Egyptian protesters.) It has no program beyond the removal of the present system and leadership.




The ending of a protest in compromise is also in the tradition of velvet revolutions. Here is Garton Ash again:




<blockquote>

> 
> "Exit prospects for the ruling elites are critical. Instead of losing their heads on the guillotine, or ending up hanging from lampposts, transition-ready members of an ancien régime, from a president such as F.W. de Klerk all the way down to local apparatchiks and secret policemen, see a bearable, even a rosier future for themselves under a new dispensation."
> 
> 
</blockquote>




And the Eastern European uprisings were not the first of this type:




<blockquote>

> 
> "Semantically, the Czechoslovak revolution may have been the first to be called “velvet,” but Central Europe in 1989 did not spirit this model out of the ether. Relevant earlier history includes not just Central Europe’s own learning process through the failed emancipation attempts of 1953 (East Germany), 1956 (Hungary), 1968 (Czechoslovakia), 1970–1971 and 1980–1981 (Poland), but also the mobilization to unseat General Pinochet in Chile, where the 1988 plebiscite preceded Central Europe’s 1989; the toppling of the Marcoses in the Philippines in 1983–1986, which gave us the wonderful Filipino-English term “people power”; and the “revolution of the carnations” in Portugal in 1974–1975, arguably the first “velvet revolution” in postwar Europe; and all the way back to the seminal example of Gandhi in India."
> 
> 
</blockquote>




So the nature, dynamics and course of the Egyptian uprising has clear precendents. Yes, the activists used Facebook and other tools, because that's where the people are and because that is the medium characteristic of the time and place. But the Internet has not leant a new character to the uprising.













## 5 Does it Matter?







Does it matter whether Facebook is a cultural event (like pop music) or a technology? Yes it does.




Popular music and youth culture has always existed in a state of tension between a mainstream, corporate, profit-oriented industry and a more independent avant garde culture. The tension, and the music, needs to be continually renewed, as each generation rejects the mainstream music of its forebears to create new sounds and events of its own.




If Facebook is a _technology_ that delivers democracy, then we can trust it: more of it can only lead to more democracy. But if Facebook is a _cultural_ phenomenon, then its meaning and role will change as it becomes mainstream - we need to treat it like we treat the record companies, the mainstream media, and our phone companies. Necessary, but not to be trusted.




A difference in the case of Egypt is that while major record companies may have been large commercial organizations, there were at least several of them. The tendency of information technologies to lead to monopoly (see Tim Wu's latest book) means that there's only one Facebook, so there is more confusion between Facebook (the place where people meet) and Facebook (the corporation that owns it). But Facebook The Company is a record label, not a musician. It is not surprising to see the poor response of Facebook to the needs of Egyptian protesters:




<blockquote>

> 
> "Simon Axten, of Facebook's public policy team, said today that the 'real name culture' was an essential element of the social networking platform. However, the policy has also been blamed for making it easy for oppressive regimes to roll up networks of dissidents who use Facebook to communicate." - Joe Fay, The Register, Feb 8, 2011. ([>>](http://www.theregister.co.uk/2011/02/08/facebook_real_names/))
> 
> 
</blockquote>




Or Alexis Madrigal, "The Inside Story of How Facebook Responded to Tunisian Hacks", Jan 24, 2011 in The Atlantic ([>>](http://www.theatlantic.com/technology/archive/2011/01/the-inside-story-of-how-facebook-responded-to-tunisian-hacks/70044/)):




<blockquote>

> 
> "We get requests all the time in a few different contexts where people would like to impersonate someone else. Police wanting to go undercover or human rights activists, say," [Facebook's Chief Security Officer Joe] Sullivan said. "And we, just based on our core mission and core product, don't want to allow that. That's just not what Facebook is. Facebook is a place where people connect with real people in their lives using their real identities."
> 
> 
</blockquote>




If your needs don't match Facebook's "core product", you're out of luck.













## 6 Social Movements: Loving and Hating the Media







The media has always been of central importance for social movements, and activists have always strived to exploit the media of their day in whatever ways they can. At the same time, social movements have never really trusted the media, particularly mainstream media. No one wants to think the mainstream media is on their side. No one trusts it; but everyone looks to it. The relationship between movements and media – particularly mainstream media – has always been fractious and dysfunctional: they need each other, but can't get along together.




Identifying with the creative artist while deploring the actions of the major record labels has been a balancing act for music fans and musicions for decades. Popular music is an exploitative, crass and commercialized industry - but it is also an authentic reflection of young people's artistry. Youth love it and are cynical about it, simultaneously.




So too television. The one-way, broadcast, non-participatory, corporate medium that digital types love to hate, and yet one that can be actively employed by savvy youth and one that is of obvious importance to social movements.




Political protests are, as Bourdieu argues, almost always symbolic acts. Some few are directly aimed at damaging infrastructure, but most often the intended damage is to the credibility of the opponent. Gandhi's Salt March, Martin Luther King's rallies, the Aldermaston marches, Buddhist monk self-immolation, Provisional IRA hunger strikes, and so on are all symbolic. Even confrontational acts such as the Paris 1968 barricades or the Sandinista raid on the Nicaraguan parliament are more aimed at provoking the public than at crippling the state. And a successful symbolic protest is designed with the medium of the day in mind. It is easy to think "without Facebook, how would they publicise their actions?" but there are many ways.




Consider Gandhi (as seen through the lens of a mainstream film, relayed by a friend to me over the phone, and written up on a blog): "A defining moment in the movie "Gandhi" was when Martin Sheen, in the role of an American journalist reports over phone the moral high ground Indians captured in a spectacular display of non-violent resistance at Dharasana Salt Works, May 21, 1930. He yells over phone "Whatever moral ascendancy the West held was lost today. India is free – for she has taken all that steel and cruelty can give, and she has neither cringed or retreated." ([Link](http://spmallick.blogspot.com/2007/03/dissecting-argument.html), [Wikipedia article about Dharasana Satyagraha](http://en.wikipedia.org/wiki/Dharasana_Satyagraha))




Skilled activists design their actions to exploit the media they have at hand, and adapt to new circumstances. A trivial or uninteresting act will attract little attention, no matter what medium conveys it. A dramatic, costly act (see Abbie Hoffmann, above) will provoke interest even through a corporate-controlled, broadcast medium. Demonstrations take place in public squares, not sidestreets. Gandhi's Salt March progressed from town to town so that word of mouth could build support, day by day.




The attitude of many activists to the Internet seems to be different. Some not only work with what they have, but also see the medium itself as an inherently progressive tool. Many identify as much with the medium as with the cause, describing themselves as "digital activists" rather than activists with a particular end in mind. But the Internet is mainstream now, and Facebook is part owned by Goldman Sachs and [has an estimated market value](http://www.bloomberg.com/news/2011-01-28/facebook-s-82-9-billion-valuation-tops-amazon-com-update1-.html) twice as big as Monsanto. It is mainstream. It is commercial. It is not on anyone's side but its own, and activists need to remember that. It is time to recover the dysfunctional relationship that activists had always have with the media, including social media.













## 7 Reinstating the Dysfunctional Relationship with Media







Fortunately, the sound of discontent is becoming more widespread among digital citizens. Here are a few examples that typify the kind of relationship we need to re-establish.




Adrian Chen, Gawker, "Why Facebook Should Do More to Help Egypt’s Protesters", Feb 5, 2011 ([>>](http://gawker.com/#!5752904/why-facebook-should-do-more-to-help-egypts-protesters)):




<blockquote>

> 
> Everybody's talking about the massive Facebook groups that helped spark the uprising, but few remember the headaches Facebook has given these groups. Just four months ago, for example, one of the most popular Egyptian Facebook protest groups, _We Are All Khaled Said_, was deactivated abruptly because its administrators had registered their accounts under pseudonyms to protect themselves from the Mubarak regime. After much (virtual) protest, the 300,000-member group was reinstated, and its young members helped form the vanguard of the current uprising.
> 
> 

> 
> In many ways, Facebook has made itself actively hostile to those who would organize against a repressive regime or advance an unpopular idea. Most problematic is the policy that bans pseudonyms. Facebook defends the policy by saying their service is about "real people making real-world connections." But what if the real world is full of secret police looking to crack down on dissent, or snooping bosses who might be supportive of a regime? Harvard Internet freedom expert Jillian C York calls the real identity policy "ludicrously out of touch."
> 
> 

> 
> And Facebook's notoriously wonky account deactivation system means that activists can find themselves deleted from the site at crucial moments, with little recourse. In 2007, Facebook permanently deactivated the account of the administrator of another important protest group, The April 6 Youth Movement, because its automatic filter thought he was a spammer; he was actually just furiously organizing protests with other members. Many other activists have been muzzled by Facebook's deactivation system, simply for voicing controversial opinions.
> 
> 
</blockquote>




Jillian York, "Facebook and Identification: Caught in a Lie?", Blog Post Jan 19, 2011. [>>](http://jilliancyork.com/2010/11/19/facebook-and-identification-caught-in-a-lie/)




Jillian York, "Policing Content in the Quasi-Public Sphere", [>>](http://opennet.net/policing-content-quasi-public-sphere)




Jillian York, "Facebook for Activists". [>>](http://jilliancyork.com/2011/02/03/facebook-for-activists/)




Zeynep Tufecki, "Facebook: The Privatization of our Privates and Life in the Company Town", May 14, 2010, Technosociology blog. [>>](http://technosociology.org/?p=131)




<blockquote>

> 
> The correct analogy to the current situation would be if tenants had no rights to privacy in their homes because they happen to be renting the walls and doors. This week, you are allowed to close the door but, oops, we changed the terms-of-service. No more closed doors! You had locks last week but we don’t allow them as of this week. Sorry for the misunderstanding.
> 
> 

> 
> Every society has “commons” – shared infrastructure that makes it possible for the society as a whole to function. Internet is now a part of that commons in general and many social applications such as Facebook are part of the “social commons.” That is why Facebook, the corporation, is so valuable and people who own it are very rich. It would not be wise of them to ignore that fact.
> 
> 
</blockquote>




danah boyd, ["Facebook is a Utility; Utilities Get Regulated"](http://www.zephoria.org/thoughts/archives/2010/05/15/facebook-is-a-utility-utilities-get-regulated.html):




<blockquote>

> 
> Yesterday, I ranted about [Facebook and “radical transparency."](http://www.zephoria.org/thoughts/archives/2010/05/14/facebook-and-radical-transparency-a-rant.html) Lots of people wrote to thank me for saying what I said. And so I looked many of them up. Most were on Facebook. I wrote back to some, asking why they were still on Facebook if they disagreed with where the company was going. The narrative was consistent: they felt as though the needed to be there. For work, for personal reasons, because they got to connect with someone there that they couldn’t connect with elsewhere. Nancy Baym did a phenomenal job of explaining this dynamic in her post on Thursday: [“Why, despite myself, I am not leaving Facebook. Yet.”](http://www.onlinefandom.com/archives/why-despite-myself-i-am-not-leaving-facebook-yet/)
> 
> 
</blockquote>




Tunisian activist Sami Ben Gharbia: [samibengharbia.com blog post, Sept 17, 2010](http://samibengharbia.com/2010/09/17/the-internet-freedom-fallacy-and-the-arab-digital-activism/)




<blockquote>

> 
> "This piece stems thus from a major assumption that the U.S. official and corporate involvement in the Internet Freedom movement is harmful for that same freedom."
> 
> 
</blockquote>




These are healthy attitudes to have. Activists have always needed to be both in and against the media. Artists have always had a dysfunctional relationship with the industry that manages them. It's time digital activists took on the same dysfunctional relationship with commercial social media companies, and it's good to see that some of them are.




<blockquote></blockquote>













## 8 In Conclusion







Facebook, the social networking site, has clearly played an important part in Egypt's protests. But it's played a role as a cultural space for a generation, not as a distinctive technology. If Facebook wasn't there, some other medium may well have played the same cultural role, as has happened in the past (the global rash of student protests in 1968, the velvet revolutions).




In the same way that protesters of previous generations used whatever media they had at hand to carry their message, acting both alongside and against the media in many cases, so today's social movements need to both use their advantage with new media, while retaining a healthy scepticism about the commercial nature of the medium itself.




It's fine for a generation to feel ownership of their cultural space, in the same way that other generations have felt ownership of popular music. But they need to keep a clear distinction between what it is they like and the corporation that provides it. Just as youth culture has always had a love-hate role with the music industry, so today's youth need to develop a healthy scepticism - make that cynicism - about the owners of their generational space.













HTML generated by org-mode 7.4 in emacs 23





		
