---
author: Tom Slee
categories:
- blog archive
date: 2006-11-05 00:29:49
title: On Doing My Homework
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

**The Story So Far**






Anthony Evans and I, as well as the [Dorset Dipper](http://www.dorsetdipper.blogspot.com/),
got into a bit of argy-bargy in the comments following Chris Dillow's
review of No One Makes You Shop At Wal-Mart. The story so far is this:  

[Chris Complained](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2006/10/noone_makes_you.html)
that I didn't address Hayek's argument "that markets are a way of
processing countless dispersed pieces of information on people's tastes
and technologies."  

[I Indicated](http://whimsley.typepad.com/whimsley/2006/10/book_review_at_.html)
that "I've never read much of [Hayek]. The bits I have always seemed to
be talking about a reality I didn't recognize. So I can't really
address the point, and will go and read. Mea culpa."   

[Anthony Asserted](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2006/10/noone_makes_you.html#comment-24465759)
that "To write a book on the subject of individualism and free markets
without reading Hayek is shocking", and on that basis he wouldn't read
my book and I'm poorer by $2.  

Now [Anthony has followed up](http://thefilter.blogs.com/thefilter/2006/11/no_one_makes_yo.html) with a full-length post of his own, arguing -- well, a whole bunch of things actually, which I am going to argue back at in...




**This weeks episode.**




Anthony says:

<blockquote>The focus of his book is individualism and competition, and you can't understand either without knowing about Hayek's [Individualism and Economics Order](http://www.amazon.co.uk/Individualism-Economic-Order-F-Hayek/dp/0226320936/sr=8-1/qid=1162638779/ref=sr_1_1/202-7284881-2859013?ie=UTF8&s=books), and [The Use of Knowledge in Society](http://www.virtualschool.edu/mon/Economics/HayekUseOfKnowledge.html). 
> 
> </blockquote>

Or, as he now puts it "you should read up on a topic if you're writing a book on it"





I think this little dispute has its roots in the difference between an education in
the natural sciences and one in the social sciences. No one ever asked
me if I had "read Heisenberg" or "read Pauling" or even "read
Einstein". It's just not a question that makes sense. Their discoveries
get absorbed into the subject; new terminology arises around their
work; new ways of expressing their insights are formulated. Pretty
quickly reading the original is redundant, and is something you do for
historical interest alone. Mathematics, of course, takes this tendency
to the extreme, consciously purging every ounce of historical context
from its theorems as it moves forward in the search for stark elegance.  

So the idea that you need to "read Hayek" or "read Marx" or "read
Weber" is really a bit odd. The insights they had have either faded or
become part of the discipline -- or at least, in the more fractious
world of economics, one strand of it. So yes, I've "read Friedman", and
yes I've "read Becker" and so on. And I've even read a bit of Hayek (I
did just say I haven't read much).
But really, unless you are interested in the historical context of the
arguments at the time -- the whole Lange-Lerner market socialism thing
for example, or where Margaret Thatcher got her inspiration -- I should
not have missed a lot if economics as a discipline has done its job,
and I trust it has.  

So I did go and read the essay on Knowledge in Society,
about the price system and how it captures and coordinates specialized
local knowledge and expertise, and why central planning is doomed to
fail. Fine. These are arguments that have indeed become part of the
mainstream of economics and yes, for the record, I'm familiar with
them. But let's face it, a lot has become understood since 1945 when he
wrote this essay.  

One reason I dislike Hayek's writing in this essay, from a personal
point of view, is its consciously broad-brush approach. This is what I
meant when I said "The bits
I have [read] always seemed to be talking about a reality I didn't recognize."
Journalists know there are two ways to tell a story: from the particular to
the general and from the general to the particular. Hayek starts big (look at that
title "The Use of Knowledge in Society"). Myself, I like to start small
and specific (which is why I called my book after an everyday happening
like shopping). When the devil is in the details, the "think big"
approach is likely to miss important things, and I think this is a
lesson that most economists have learned since Hayek.  

George Akerlof, for example, wrote in his Nobel lecture that "In the
late 1960s there was a shift in the job description of economic
theorists... Since that time, both micro and macroeconomics have
developed a Scarry-ful book of models designed to incorporate into
economic theory a whole variety of realistic behaviors." To read Hayek
now is to read an essay that overreaches. It does not tell me what
happens in any one situation. Stiglitz gets it right when he says that
assuming away market failures is like leaving Hamlet out of the play.   

Anthony disagrees I'm sure, and we are left with what Dipper described as "my assumptions against your assumptions".  

To sum up, there is nothing in what I wrote that I would change having
read this essay. It is true that I don't talk directly in the book
about the role of markets as a mechanism for processing information and
social knowledge, but hey, it's only 240 pages, you can't write about
everything.




Anthony says:

<blockquote>It's ludicrous [for me] to say that a cover-to-cover reading of the book is a pre-requisite for any opinion to be formed.

> 
> </blockquote>

Just for the record, what I actually wrote was




Well, I might say that dismissing a book without reading **any of it **is shocking too, if I hadn't done it so many times myself.  







So relax, we all have to choose what we pay attention to and what we
don't. Go ahead, have opinions, I know I do.




But I still think it's a
bit cheeky to accuse me of not doing my homework on the basis of what I
wrote about not reading much Hayek.





**What about those toilets?**  
  
Anthony says I don't know much about [toilets](http://whimsley.typepad.com/whimsley/2006/10/the_state_versu.html).




Well, I'm not going to work too hard to defend a blog post. There are
indeed inconsistencies there - fair enough. But I actually don't think
the biggest cause of water-wasting toilets is flat-rate water payment
(which has, I think, receded anyway over the years). The costs of
information are at least as significant. Quick, what portion of your
water bill is from toilet flushes? So I stand by my basic argument that
in this case neither state nor market succeeded until our individual
hero came along and solved the problem.




So that's it for now. Thanks to Anthony for letting me know about his post and for the free publicity to his readers.


		
