---
author: Tom Slee
categories:
- blog archive
date: 2011-02-15 13:06:43
title: 'Egypt: Debunking the Twitter-debunker-debunkers'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Ryan Shaw, [in the comments](http://whimsley.typepad.com/whimsley/2011/02/egypts-facebook-revolution-looking-under-the-lamp-post-.html?cid=6a00d83451d3b369e2014e8616d965970d#comment-6a00d83451d3b369e2014e8616d965970d), points to Aaron Bady, who points to Jay Rosen.




Jay Rosen and Aaron Bady dislike simplistic "debunking" articles that caricature claims about the role of the Internet and social media in Egypt and Tunisia. Jay Rosen identifies a genre of ["Twitter Can't Topple Dictators" articles](http://pressthink.org/2011/02/the-twitter-cant-topple-dictators-article/), and says they have six qualities:






  1. Nameless fools are staking maximalist claims.


  2. No links we can use to check the context of those claims.


  3. The masses of deluded people make an appearance so they can be ridiculed.


  4. Bizarre ideas get refuted with a straight face.


  5. Spurious historicity.


  6. The really hard questions are skirted




Aaron Bady's version of Rosen’s argument is [this](http://zunguzungu.wordpress.com/2011/02/14/knowing-and-unknowing-the-egyptian-public/): "it is a fantasy of a particular kind of credulousness, which is then so soberly refuted (by sober debunkers) that the overriding impression left for the audience is only of the performance of seriousness itself, and of the credulous enthusiasm which has been dismissed."




Both have written much better stuff (well, Aaron Bady at least - I confess I'm no fan of Jay Rosen's style) so here's a suggestion to get them back on the wagon: If you are going to start a list with a complaint about "maximalist claims" and a plea to address the "hard questions", don't  hunt for the an extreme case, label it a "genre-defining classic", and tar a wide range of articles with the same brush  of "wildly overdrawn claims", "weaselly question marks", and "derisive debunking".




Shorter: don't use a caricature to combat a caricature.




Even shorter: Pot, meet kettle.




Update: Omri Ceron does a better job [here](http://www.iconindexsymbol.com/2011/02/jay-rosen-is-wrong-twitter-revolution-and-facebook-revolution-cyber-utopians-really-do-think-its-that-simple/).


		
