---
author: Tom Slee
categories:
- blog archive
date: 2006-01-14 19:24:11
title: Which matters more, the income of the average or the average income?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Which matters more, the income of the average citizen or the average income of citizens? 




Via [Brad DeLong](http://delong.typepad.com/sdj/2006/01/the_economy_up_.html) and [Ruy Teixeira](http://www.emergingdemocraticmajorityweblog.com/donkeyrising/archives/001364.php), the story of the American economy in the last five years is summarized in one page by the [Economic Policy Institute](http://www.epi.org/content.cfm/pm110).




Their headlines are:




  1. Profits are up, but the wages and the incomes of average Americans are down.





  2. More and more people are deeper and deeper in debt.





  3. Job creation has not kept up with population growth, and the employment rate has fallen sharply.





  4. Poverty is on the rise.





  5. Rising health care costs are eroding families' already declining income.



An economy is a big thing, and there are a lot of stories in it, some happy and some sad. Productivity, debt, growth, uncertainty, technological advances, poverty, millionaires. Averages give only a very limited picture, and how you evaluate the overall picture depends on which stories you think are important. 




Me, I think the income of average Americans is more important than the average income of Americans.


		
