---
author: Tom Slee
categories:
- blog archive
date: 2006-12-23 18:08:52
title: 2006 Best of the Year List
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

You may have noticed that my normally far-from-hectic posting rate has gone from snail-like to glacial over the last few weeks. Well, be assured that it's going to stay that way for the remainder of 2006. I intend to have even less to say than usual.




Whether we like it or not, this is a season of consumption and so, for no good reason, here is a list of some of the best things I consumed in 2006.




Best fiction I read. [Three Junes](http://www.randomhouse.com/anchor/catalog/display.pperl?isbn=9780385721424&view=rg) by Julia Glass. Not my kind of book at all, which makes it all the more remarkable that I found it unputdownable.




Best non-fiction I read. [Consciousness Explained](http://en.wikipedia.org/wiki/Consciousness_Explained) by Daniel Dennett, who is my new intellectual hero. It was published back in 1991, but my interest in this kind of stuff is relatively recent. I was put onto it via Susan Blackmore's excellent [Consciousness, A Very Short Introduction](http://www.oup.com/uk/catalogue/?ci=9780192805850). A book I'll be reading again in the next couple of weeks, and one that changed how I look at life & death. 




Best movie I watched. [Hidden (Cache)](http://www.imdb.com/title/tt0387898/), directed by Michael Haneke. Watching movies or TV is usually thought to be a passive act. But with this movie you are absolutely engaged from the first shot, wondering what it is you are seeing. Are you the watcher? Are you watching the watcher? Are you a spectator watching the watched? It's riveting. Then there is that one scene in the middle where, all of a sudden, everyone who sees it just gasps or swears. And to finish it off, there is the four-minute long final shot, which you scan from corner to corner for clues. Are there answers to the puzzles the movie poses? Who cares? Not me. Great stuff.




Best TV Series I watched. [Intelligence.](http://www.cbc.ca/intelligence/) It's unusual to be able to watch a Canadian drama series and realize that it's not "good, considering" but just really really good. From the makers of Da Vinci's Inquest, and shown on CBC on Tuesdays, the multiple plotlines, shady deals, double crossing, and excellent acting from the leads (Ian Tracey and Klea Scott) as well as from the big supporting cast make this the best series I've seen since [Oz](http://www.hbo.com/oz/).




Best radio show I listened to. Continues to be [Writers and Company](http://www.cbc.ca/writersandcompany/), where Eleanor Wachtel does a great job of interviewing writers. She gives them space to talk, doesn't get in the way, and as a result I've found several authors I like from this show.




Best restaurant I visited. [Brars](http://www.brars.ca/). Who knew that in the middle of the warehouses and machine shops of the light-industry wasteland that is Brampton, in one of a million mini-malls scattered around Toronto airport, there is a vegetarian Indian restaurant that serves up to a thousand people in an evening, provides good value (it's a buffet for $13), and the great atmosphere of many people enjoying their company and their food. Big tables, lots of rooms, and lots of food (and on the evening I was there, great company too). Being the only non-subcontinent people in the restaurant was a bit of an eye-opener as well - I guess I have some things to learn about this place I live.




Best food shop I bought from - The usual culprits in Kitchener Waterloo are the gourmet places, like Vincenzo's, who are pretty good I must admit. But this was the year I discovered Onkar Food & Spices on Hazelglen Road in Kitchener. Good Indian ingredients at good prices. Plus I get to walk the dog through Monarch Woods when I go there. 




Best other shop in K-W: J&J Cards and Collectibles on Weber Street, just south of University. Some years ago it was a place that sold Pokemon cards for the kids, Magic Cards and Dungeons and Dragons paraphernalia for the teenagers, and so on. In the last couple of years it has expanded, and it now has a great selection of board games, chess stuff, and lots more. The Brothers J have done a great job with this place.




Best book launch of 2006 - No One Makes You Shop at Wal-Mart, at Words Worth books back in June. Great that so many people came out (and bought books). A belated thanks to everyone.


		
