---
author: Tom Slee
categories:
- blog archive
date: 2006-08-13 22:40:40
title: Cool Webby Things Change How We Work
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I routinely use three different computers, and so any web-based tool is a natural for me. I don't want to move stuff around from place to place, and I don't really want to store home things on a work computer. So I find myself - although not without misgivings - keeping more stuff on the web all the time. 




I've used [Gmail](http://mail.google.com) as e-mail interface for some time, and I keep photos on [Flickr](http://www.flickr.com), and now I keep appointments on Google [Calendar](http://www.google.com/calendar). I've just discovered [LibraryThing ](http://www.librarything.com)(hi piefuchs) and am working out what to do with it, but I expect I'll keep some kind of catalogue of my books there. There's no doubt these new applications are changing how useful the web is. I recently started using [Zoho Writer](http://www.zohowriter.com) to write longer weblog posts, and the thing is, I could imagine using it as my main word processing program. It's nowhere near as feature-rich as MS Word, of course - but being free, web-based, and reasonably usable, are three big things in its favour, and that's something I didn't expect a year ago. [Zoho Sheet](http://www.zohosheet.com) is pretty cool too.




One big question is whether Google's forthcoming web-based word processing and spreadsheet programs will be any good. Their [spreadsheet](http://spreadsheets.google.com) is now in Beta, and I'd say it's not quite as good as Zoho Sheet (no graphs, for example). Their word processor is probably not too far off, as they bought Writely a few months ago. While Google [Earth](http://earth.google.com) is one of the coolest programs ever, some other things they have done seem half-finished, so I don't think it is a foregone conclusion that Google will win this particular battle.




I can really see a time, not too far off, when many people will use web-based applications for most of their word processing and spreadsheet programs. Microsoft Office is overdue for some competition from some kind of [disruptive technology](http://www.businessweek.com/chapter/christensen.htm), and in a couple of years MS could have some real problems.


		
