---
author: Tom Slee
categories:
- blog archive
date: 2006-10-08 13:29:28
title: No Attack On Iran
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

It is important that Seymour Hersh exposes the rumblings from various parts of the US government about a potential attack on Iran, but on this occasion I've felt for some time that it's not going to happen. It's not that Bush, Cheney, Rumsfeld and so on wouldn't do such a thing - personally I think they'd do it in a heartbeat if it gained them a few points in the polls - but that they can't even if they want to. It's getting close to the end of Bush's second term, he doesn't have the personal clout any more, and Iraq is such a complete and utter catastrophe that the response to any further military adventurism would, I think, be swift and damning. Now this wouldn't reassure me if I was sitting in Tehran, but that's how it looks from here.




And now someone with some actual knowledge says the same thing. [The Yorkshire Ranter](http://yorkshire-ranter.blogspot.com/) is someone who seems to know his military logistics stuff, and also comes from God's Own County, so he can hardly be wrong, and he [argues ](http://yorkshire-ranter.blogspot.com/2006/10/there-will-be-no-attack-on-iran-this.html)that the US just doesn't have the needed stuff in the area to carry out any attack on Iran.




His recent posts have been excellent - I especially like his [unified theory of stupidity on terrorism](http://yorkshire-ranter.blogspot.com/2006/10/unified-theory-of-stupidity-on.html) where he starts off with this:

<blockquote>I'm beginning to think that it's possible to
discern so many similarities between really stupid opinions on
terrorism that we can call it a theory. Specifically, _if you're talking about state sponsorship, you're probably wrong, unless overwhelming evidence contradicts this_.
As far as I can tell, the modern version of this theory originated in
the late 1970s or early 1980s. It had been about - Shakespeare has a
character in _Richard II_ allege that "all the troubles in our
lands/have in false Bolingbroke their first head and spring" - but the
strong form seems to have originated then.  
  
Key features are that
1) terrorist or guerrilla activity is never the work of the people who
appear to carry it out, 2) instead it is the work of a Sponsor, 3) that
only action against the Sponsor will be effective, 4) even if there is
no obvious sign of the Sponsor's hand, this only demonstrates their
malign skill, and 5) there is evidence, but it is too secret to
produce. In the strong form, it is argued that _all_ nonconventional military activity is the work of the same Sponsor.
> 
> </blockquote>

and his [Recidivist with alert populations](http://yorkshire-ranter.blogspot.com/2006/10/recidivist-with-alert-populations.html), where he says this:

<blockquote>try out the following quote from one Robert Mocny, director of the USVISIT program at DHS:
> 
> </blockquote>

<blockquote>_"We cannot allow to impediment our progress the privacy rights of known criminals."_
> 
> </blockquote>

<blockquote>The law is what I say it is, and you're either with us, or you're with the terrorists. Perhaps _literally_
with them, in the cells. Joseph Sensibaugh, manager of biometric
interoperability for the FBI, meanwhile opines that "It helps the
Department of Homeland Security determine [who's a good guy and who's a bad guy](http://www.cbsnews.com/stories/2006/10/05/60minutes/main2066624.shtml),"
targeting "suspected terrorists" and "remaining recidivist with alert
populations". Not to mention the president of Bolivia and a dead
bluesman, apparently.
> 
> </blockquote>

<blockquote>Why does it specifically have to be
illiterate authoritarianism, by the way? What does that last phrase
actually mean, anyone? Anyway. Enquiring minds want to know more. What
was this "pilot project"? Whose records were given to the DHS? Will
they be told? What are the safeguards? Where are the guarantees?
> 
> </blockquote>

Good questions Alex.


		
