---
author: Tom Slee
categories:
- blog archive
date: 2007-06-19 21:59:31
title: Kindness to Electrons or a Tax Break? Why is Google Building in Iowa?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Which explanation for Google's announcement of a $600 million data centre in Iowa is the right one? This?

<blockquote>Google is interested in placing data centers in
the middle of the country because it is a "busy crossroads of Internet
activity," it said in a statement.
> 
> </blockquote>

or this?

<blockquote>"Last month, Gov. Culver signed a bill upgrading Iowa’s tax system
related to sales tax, use tax, and property tax for computer related
businesses," the governor's office said. "The state legislature's work
exempts the electricity and capital investment necessary for this kind
of a facility from sales tax, as is common in the manufacturing sector."
> 
> </blockquote>

The first report is from trade magazine [InfoWorld](http://www.infoworld.com/article/07/06/19/Google-to-open-new-data-center-in-Iowa_1.html). Google is saving all those electrons from having to go all the way across the country - it's probably some kind of nice green initiative. The second comes from the [Register](http://www.theregister.co.uk/2007/06/19/google_iowa_datacenter/), which is the Private Eye of trade magazines.




Sorry InfoWorld, I'll be getting my tech news from the Register.


		
