---
author: Tom Slee
categories:
- blog archive
date: 2016-02-12 15:24:00
title: "What's Yours is Mine: reviews and other coverage"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Links to coverage of [What's Yours is Mine](http://www.orbooks.com/catalog/whats-yours-is-mine-by-tom-slee/).


## English


Reviews and essays:



 	
  * Toronto Star - [Book slams Uber, Airbnb, sharing economy](https://www.thestar.com/news/canada/2016/05/01/book-takes-on-uber-airbnb-sharing-economy-walkom.html) (Thomas Walkom)

 	
  * The Guardian - [What's Yours is Mine](http://www.theguardian.com/books/2016/apr/02/whats-yours-is-mine-against-the-sharing-economy-tom-slee-review) (Steven Poole)

 	
  * The Spectator - [The unforeseen dangers of Uber and Airbnb](http://www.spectator.co.uk/2016/03/the-unforeseen-dangers-of-uber-and-airbnb/) (Robert E. Levine)

 	
  * Cathy O'Neil - [Tom Slee’s What’s Yours is Mine](https://mathbabe.org/2016/04/20/tom-slees-whats-yours-is-mine/)

 	
  * Saul of Hearts - [Book review](https://medium.com/@saulofhearts/book-review-d60778292ad)

 	
  * ZDNet - [Spam & What's Yours Is Mine, book reviews: The loss of internet innocence](http://www.zdnet.com/article/spam-whats-yours-is-mine-book-reviews-the-loss-of-internet-innocence/) (Wendy M. Grossman)

 	
  * Counterpunch - [Raw Deals: Challenging the Sharing Economy](http://www.counterpunch.org/2016/02/12/raw-deals-challenging-the-sharing-economy/) (Ben Terrall)

 	
  * Truthdig - [What's Yours is Mine](http://www.truthdig.com/arts_culture/item/whats_yours_is_mine_20160502) (Peter Richardson)

 	
  * David Robinson - [Bending The Moral Arc of the Gig Economy](https://medium.com/equal-future/bending-the-moral-arc-of-the-gig-economy-648f8e65219c#.tifvpnbiw)

 	
  * Netopia - [The Broken Promise of the #SharingEconomy](http://www.netopia.eu/the-broken-promise-of-the-sharingeconomy/) (Ralf Grötker)

 	
  * Alternet (excerpt) - [The 'Sharing Economy' Isn't About Sharing: The Dark Reality Behind This Major Workplace Shift](http://www.alternet.org/labor/sharing-economy-isnt-about-sharing-dark-reality-behind-major-workplace-shift)


Interviews:

 	
  * TV Ontario: The Agenda - [Sharing the wealth, unevenly](http://tvo.org/video/programs/the-agenda-with-steve-paikin/sharing-the-wealth-unevenly)

 	
  * Redeye Collective (Vancouver Co-operative Radio) -[ What’s Yours is Mine: Against the Sharing Economy](http://rabble.ca/podcasts/shows/redeye/2016/04/whats-yours-mine-against-sharing-economy) (Lorraine Chisholm)

 	
  * The Register - [What do we do about a problem like Uber?](http://www.theregister.co.uk/2016/01/15/tom_slee_sharing_economy_interview/)

 	
  * Vice - [The Sharing Economy is not your friend](http://www.vice.com/read/the-case-against-airbnb-and-uber)

 	
  * Netopia - [25% Tech, 75% Marketing, 100% Hype – Inside the #SharingEconomy](http://www.netopia.eu/25-tech-75-marketing-100-hype-inside-the-sharingeconomy/)

 	
  * The Communitech Podcast: [Tom Slee critiques the sharing economy](http://news.communitech.ca/multimedia/the-communitech-podcast-tom-slee-on-the-sharing-economy/)

 	
  * This is Hell: [happening Saturday Feb 13, 11am Chicago time](https://thisishell.com/)

 	
  * The Waterloo Chronicle - [Sharing not always caring](http://www.waterloochronicle.ca/news-story/6382561-sharing-not-always-caring-says-author/) (James Jackson)




## International




### German





 	
  * Deutschlandradio Kulture - [Geldwertes Teilen](http://www.deutschlandradiokultur.de/tom-slee-deins-ist-meins-geldwertes-teilen.1270.de.html?dram:article_id=348110) (Felicitas Boeselager)

 	
  * Deer Spiegel - [Angestellte bei Airbnb und Uber: "Diese Jobs schaffen ein neues Prekariat"](http://www.spiegel.de/wirtschaft/airbnb-und-uber-was-steckt-hinter-der-sharing-economy-a-1083971.html) (Nils Klawitter)




### Danish





 	
  * Djøfbladet - [Uber og Airbnb underminerer demokratiet](http://www.djoefbladet.dk/blad/2016/10/uber-og-airbnb-underminerer-demokratiet.aspx) (Assia Awad)

		
