---
author: Tom Slee
categories:
- blog archive
date: 2016-12-31 18:36:55
title: 'Looking back at my 2016: publications and media'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Here is a reasonably complete collection of things written by me, interviews of me, book reviews about my book, and articles to which I contributed through interviews or quotes or data sets for the year 2016. It's been a busy year, and rewarding in many ways.


## Book


My second book _What's Yours is Mine: Against the Sharing Economy_ was published by OR Books in November 2015, but I am including the book and related articles here, making it a "long 2016".



 	
  * US and UK edition ([link](http://www.orbooks.com/catalog/whats-yours-is-mine-by-tom-slee/)), OR Books, November 2015

 	
  * Canadian edition ([link](https://btlbooks.com/book/whats-yours-is-mine)), Between the Lines Press, February 2016

 	
  * German edition ([Deins ist Meins](http://www.kunstmann.de/titel-0-0/deins_ist_meins-1193/)): Verlag Antje Kunstmann

 	
  * Spanish edition: [Lo tuyo es mío](http://www.megustaleer.com/libro/lo-tuyo-es-mio/ES0151310), Taurus, November 2016

 	
  * Simplified Chinese edition: (Ginkgo Book Co.)

 	
  * French language edition (France and Québec): [Ce Qui est à Toi est à Moi](https://www.luxediteur.com/catalogue/a-toi-a-moi/), translated by Hélène Rioux, Lux Editeur




## Book chapter





 	
  * "Trust and Platform Cooperatives" in [Ours to Hack and to Own](http://www.orbooks.com/catalog/ours-to-hack-and-to-own/), edited by Trebor Scholz and Nathan Scheider.




## Invited Essays





 	
  * [The Sharing Economy's Dirty Laundry](https://www.jacobinmag.com/2016/03/uber-airbnb-sharing-economy-housing-tech/), Jacobin, March 2016

 	
  * [The Sharing Economy isn't about sharing](http://www.alternet.org/labor/sharing-economy-isnt-about-sharing-dark-reality-behind-major-workplace-shift), Alternet, March 27, 2016 (excerpt)

 	
  * [What's Yours is Mine](http://www.afr.com/leadership/entrepreneur/whats-yours-is-mine-the-greed-behind-the-new-sharing-economy-20160525-gp3yfo), AFR Weekend, Australian Financial Review, May 28, 2016 (excerpt)

 	
  * [Airbnb is Facing an Existential Expansion Problem](https://hbr.org/2016/07/airbnb-is-facing-an-existential-expansion-problem), Harvard Business Review digital article, July 11, 2016

 	
  * The downsides of sharing, Monocle (rejected)




## Reviews of "What's Yours is Mine"





 	
  * [What's Yours is Mine](http://www.svd.se/dickens-hade-aldrig-tagit-en-uber), Håkan Lindgren, Svenska DagBladet, Jan 11, 2016.

 	
  * [The broken promise of the sharing economy](http://www.netopia.eu/the-broken-promise-of-the-sharingeconomy/), Ralf Grötker, Netopia, Feb 3, 2016

 	
  * [Raw Deals](http://www.counterpunch.org/2016/02/12/raw-deals-challenging-the-sharing-economy/), Ben Terrall, Counterpunch, Feb 12, 2016.

 	
  * [What's Yours is Mine](https://medium.com/@saulofhearts/book-review-d60778292ad#.wh5qsu5pd), Saul of Hearts, Medium, Feb 25, 2016

 	
  * [L'atto d'accusa contro la sharing economy](http://espresso.repubblica.it/visioni/tecnologia/2016/03/08/news/l-atto-d-accusa-contro-la-sharing-economy-le-persone-non-sono-aziende-1.253105), Fabio Chiusi, L'Espresso, 09 March 2016 (Italian)

 	
  * [The Unforeseen Dangers of Uber and Airbnb](http://www.spectator.co.uk/2016/03/the-unforeseen-dangers-of-uber-and-airbnb/), Robert E. Levine, The Spectator (UK), March 5, 2016

 	
  * [Ist Carsharing das neue Lohndumping?](https://www.welt.de/kultur/literarischewelt/article154515115/Ist-Carsharing-das-neue-Lohndumping.html) (German), Welt, Oliver Rasche, April 2016.

 	
  * [Book of the Day](https://www.theguardian.com/books/2016/apr/02/whats-yours-is-mine-against-the-sharing-economy-tom-slee-review), Steven Poole, The Guardian, April 2, 2016.

 	
  * [Tom Slee's What's Yours is Mine](https://mathbabe.org/2016/04/20/tom-slees-whats-yours-is-mine/), Cathy O'Neil, April 20, 2016

 	
  * [Die Sharing Economy - nur eine illusion?](https://ethik-heute.org/die-sharing-economy-nur-eine-illusion/), Birgit Stratmann, Netzwerk Ethikheute,  (German)

 	
  * [Sheared](http://reviewcanada.ca/magazine/2016/05/sheared/), Rohinton Medhora, Literary Review of Canada, May 2016

 	
  * [Book slams Uber, Airbnb, and Sharing Economy](https://www.thestar.com/news/canada/2016/05/01/book-takes-on-uber-airbnb-sharing-economy-walkom.html), Thomas Walkom, Toronto Star, May 1, 2016

 	
  * [What's Yours is Mine](http://www.truthdig.com/arts_culture/item/whats_yours_is_mine_20160502), Peter Richardson, Truthdig, May 2, 2016.

 	
  * [Teile und herrsche](https://www.jungewelt.de/m/artikel/294841.teile-und-herrsche.html), Thomas Wagner, junge Welt, May 10, 2016

 	
  * [What's Yours is Mine](http://lizpelly.com/post/148159855537/review-whats-yours-is-mine-against-the-sharing), Liz Pelly, Maximum Rocknroll, June 2016

 	
  * [What's Yours is Mine](http://www.innovation.cc/book-reviews/21_1_7-doughty_bk-rev_slee_yours-mine.pdf), Howard Doughty, The Innovation Journal, 21 (1) 2016

 	
  * [What's Yours is Mine](http://www.compulsivereader.com/2016/03/25/a-review-of-whats-yours-is-mine-by-tom-slee/), Ruth Latta, The Compulsive Reader, March 25, 2016

 	
  * [Le duel des critiques](http://bfmbusiness.bfmtv.com/mediaplayer/video/le-duel-des-critiques-margaret-thatcher-vs-tom-slee-2110-878557.html), BFM Business, (French, video).




## Interviews





 	
  * [What do we do about a problem like Uber](http://www.theregister.co.uk/2016/01/15/tom_slee_sharing_economy_interview/), Andrew Orlowski, The Register, 15 Jan 2016

 	
  * [Inside the sharing economy](http://www.netopia.eu/25-tech-75-marketing-100-hype-inside-the-sharingeconomy/), Per Strömbäck, Netopia, 3 Feb 2016

 	
  * [Every person a market](https://thisishell.com/interviews/887-tom-slee), Chuck Mertz, This is Hell, 23 Feb 2016 (audio),

 	
  * [The Sharing Economy is Not Your Friend](https://www.vice.com/en_us/article/the-case-against-airbnb-and-uber), Drew Millard, Vice, Feb 2016.

 	
  * [Sharing is not always caring](http://www.waterloochronicle.ca/news-story/6382561-sharing-not-always-caring-says-author/), James Jackson, Waterloo Chronicle, 09 Mar 2016

 	
  * [Geldwertes Teilen](http://www.deutschlandradiokultur.de/tom-slee-deins-ist-meins-geldwertes-teilen.1270.de.html?dram:article_id=348110), DeutschlandRadio Kultur, 12 March 2016 (German)

 	
  * [The technology is just a shiny shopfront](http://www.newstatesman.com/politics/economy/2016/03/technology-just-shiny-shopfront-case-against-sharing-economy), Barbara Speed, The New Statesman, 21 March 2016.

 	
  * ["Diese Jobs schaffen ein neues Prekariat"](http://www.spiegel.de/wirtschaft/airbnb-und-uber-was-steckt-hinter-der-sharing-economy-a-1083971.html), Nils Klawitter, Spiegel Online, 23 March 2016 (German)

 	
  * [Teile und herrsche](http://www.nzz.ch/nzzas/nzz-am-sonntag/sharing-economy-teile-und-herrsche-ld.14306), Barbara Hofler, NZZ Am Sontag, 16 April 2016 (German, Switzerland)

 	
  * [What's Yours is Mine](http://rabble.ca/podcasts/shows/redeye/2016/04/whats-yours-mine-against-sharing-economy), Redeye Collective, Vancouver (audio), 29 April 2016

 	
  * [Sharing the wealth, unevenly](https://www.youtube.com/watch?v=bs830YuQm3g), The Agenda with Steve Paikin, TV Ontario, 4 May 2016

 	
  * [Uber og Airbnb underminerer demokratiet](http://www.djoefbladet.dk/blad/2016/10/uber-og-airbnb-underminerer-demokratiet.aspx), Assia Awad, djoefbladet, 26 May 2016 (Danish)

 	
  * [Sharing economy platforms exist for one purpose only, which is to make money for their investors](https://medium.com/@FelixSimon/sharing-economy-platforms-exist-for-one-purpose-only-which-is-to-make-money-for-their-investors-82aa6cc45989#.iztg63liq), Felix Simon, Medium, 6 June 2016

 	
  * [10 Questions on the sharing economy](http://tvo.org/video/programs/the-agenda-with-steve-paikin/10-questions-on-the-sharing-economy), The Agenda with Steve Paikin, TV Ontario, 14 June 2016

 	
  * [Can’t find a home in Seattle? Airbnb rentals may be to blame](http://www.seattletimes.com/seattle-news/data/cant-find-a-home-in-seattle-airbnb-rentals-may-be-to-blame/), Gene Balk, The Seattle Times, 15 June 2016 (Seattle)

 	
  * [Short-term rentals are reshaping real estate market in some cities](http://www.marketplace.org/2016/09/19/business/short-term-rentals-are-reshaping-real-estate-market-some-cities), Tony Gonzalez, Marketplace, 20 Sept 2016

 	
  * [The Sharing Economy Blues](https://canadiandimension.com/articles/view/the-sharing-economy-blues), David Hugill, Canadian Dimension, 23 September 2016

 	
  * [Die Sharing Economie ist eine Blase](http://www.bilanz.ch/people/die-sharing-economy-ist-eine-blase-761397), (German), Marc Kowalsky, Bilanz, November 2016.

 	
  * [UK Tribunal Rules in Favour of Uber Drivers](http://rabble.ca/podcasts/shows/redeye/2016/11/uk-employment-tribunal-rules-favour-uber-drivers) (audio), Redeye Collective, Vancouver, 22 Nov 2016

 	
  * [The so-called sharing economy](http://www.abc.net.au/radionational/programs/themoney/share-economy/7777658), Richard Aedy, The Money, Australian Broadcasting Corporation, December 2016, (audio)




## Quoted, and Airbnb data





 	
  * [Nobody's Business](https://www.policyalternatives.ca/airbnb): CCPA report on short-term rentals in Toronto, 22 September 2016

 	
    * [Airbnb cutting into available rentals in Toronto](http://www.metronews.ca/news/toronto/2016/09/22/airbnb-cutting-into-available-rentals-in-toronto.html), study shows, Metro News, 22 Sep 2016

 	
    * [Airbnb cutting into available rentals in city](https://www.thestar.com/business/2016/09/22/airbnb-cutting-into-available-rentals-in-city-study-shows.html), Tess Kalinowski, Toronto Star, 22 Sep 2016

 	
    * [Airbnb Is Sapping Toronto Of Rental Housing: Report](http://www.huffingtonpost.ca/2016/09/22/airbnb-toronto-rental-housing_n_12143006.html), Jesse Ferreras, Huffington Post, 22 Sep 2016

 	
    * (and others)




 	
  * [Airbnb has made it nearly impossible to find a place to live in this city](http://fusion.net/story/305584/airbnb-reykjavik/), Kristen V. Brown, Fusion, May 24. (Reykjavik)

 	
  * [How do we research the sharing economy when the data can't be validated?](http://www.washingtonpost.com/news/monkey-cage/wp/2016/06/06/how-do-we-research-the-sharing-economy-when-the-data-cant-be-validated/), Andrew Gelman, Monkey Cage Blog (Washington Post), June 6, 2016.

 	
  * [Cities take aim at Airbnb](http://www.theglobeandmail.com/news/british-columbia/concerns-about-airbnb-impact-on-rentersspread/article30845642/), Sunny Dhillon, Globe and Mail, 11 July 2016

 	
  * [Airbnb in Vancouver and its impact on affordable housing](https://affordablevancouver.files.wordpress.com/2016/07/airbnb-vancouver-report-iain-marjoribanks.pdf), Iain Marjoribanks, 1 June 2016,

 	
  * [Airbnb open to market regulations in large cities like Vancouver](http://www.theglobeandmail.com/news/british-columbia/airbnb-open-to-market-regulations-in-large-cities-like-vancouver/article31093303/), Mike Hager, Globe and Mail, 25 July 2016 (Vancouver)

 	
  * [Iceland tourism and the mixed blessings of Airbnb](https://skift.com/2016/08/19/iceland-tourism-and-the-mixed-blessings-of-airbnb/), Andrew Scheivachman, Skift, 19 Aug 2016

 	
  * [Small towns can't handle the sharing economy tourism boom](http://fusion.net/story/339171/small-towns-airbnb/), Kristen V. Brown, Fusion, 28 August 2016.

 	
  * [Airbnb et Uber](http://ici.radio-canada.ca/premiere/emissions/plus-on-est-de-fous-plus-on-lit/saison-2016-2017/segments/chronique/8926/economie-du-partage-airbnb-uber-capitalisme-nicolas-tittley-arun-sundararajan-tom-slee), Nicholas Tittley,** **Radio Canada, September 2016. (audio)

 	
  * [Lancé à Bordeaux, l’observatoire Airbnb veut créer un débat national](http://rue89bordeaux.com/2016/10/lance-a-bordeaux-lobservatoire-airbnb-veut-creer-debat-national/), Xavier Ridon, Rue89 Bordeaux, 25 Oct 2016 (Bordeaux)

 	
  * [New York deflates Airbnb](http://www.economist.com/news/business/21709353-new-rules-may-temper-airbnb-new-york-its-future-still-looks-bright-new-york-deflates), The Economist, 29 Oct 2016.

 	
  * [The 14 th Global Forum on Tourism Statistics](http://tsf2016venice.enit.it/images/articles/Papers_Forum/6.2_Assessing%20the%20impact%20of%20shared%20accommodation%20for%20city%20tourism.pdf), 23-25 Nov 2016

 	
  * [Consumo collaborativo: dall'anticapitalismo al rilancio del mercato](http://www.ilgiornale.it/news/spettacoli/consumo-collaborativo-dallanticapitalismo-rilancio-mercato-1339915.html), Carlo Lottiere, il Giornale, 7 Dec 2016 (Italian)








## Report: How Airbnb hid the facts in New York City


Together with Murray Cox of Inside Airbnb,  I produced a report on Airbnb's removal of 1500 listings in New York, just in time to make its public release of data look good.



 	
  * The report: [my site](http://tomslee.net/how-airbnb-hid-the-facts-in-nyc), and [Inside Airbnb](http://insideairbnb.com/how-airbnb-hid-the-facts-in-nyc/)

 	
  * [List of media reports](http://tomslee.net/2016/02/airbnb-report-media-coverage.html), including [New York Times](http://www.nytimes.com/2016/02/12/business/airbnb-purged-new-york-listings-to-create-a-rosier-portrait-report-says.html), [The Guardian](https://www.theguardian.com/technology/2016/feb/10/airbnb-new-york-city-listings-purge-multiple-apartment-listings), and [NBC](http://www.nbcnews.com/business/consumer/report-says-airbnb-fudged-data-hide-illegal-hosts-n517656).

 	
  * Airbnb admits it purged listings: [Fusion](http://fusion.net/story/272780/airbnb-new-york-data-purge/),




## Events





 	
  * [Octopus Books](http://octopusbooks.ca/event/what’s-yours-is-mine-against-the-sharing-economy-book-launch-with-author-tom-slee) (Ottawa)

 	
  * [Last but not Least Feast](http://www.wordsworthbooks.com/events/category/the-last-but-not-least-feast-sunday-brunch), Words Worth Books and The New Quarterly (Kitchener-Waterloo)

 	
  * [Word on the Street](http://thewordonthestreet.ca/toronto/festival/participants/tom-slee/) (Toronto)

 	
  * [The City Seminar: The Ghost Economy](http://www.yorku.ca/yuevents/index.asp?Event=37232&Category=0&ShowCal=&TimeSame=Nov&Month=11&Year=2016&EventTitle=York%20Events:%20The+City+Seminar%3A+The+Ghost+Economy), York University, November 4, 2016.

		
