---
author: Tom Slee
categories:
- blog archive
date: 2014-06-03 01:08:00
tags:
- uber
title: Uber Drivers Earning $90K/year? More Evidence Needed
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				




Last Tuesday taxi-disrupting tech company Uber [posted](http://blog.uber.com/uberimpact) on the company blog that "the median income on uberX is more than $90,000/year/driver in New York and more than $74,000/year/driver in San Francisco". I don't think their numbers add up, but first the story so far...







For the notoriously cheap taxi industry, those are some pretty sweet numbers, and they were hailed (hah!) by Matt McFarland of the Washington Post with the headline [Uber's remarkable growth could end the era of poorly paid cab drivers](http://www.washingtonpost.com/blogs/innovations/wp/2014/05/27/ubers-remarkable-growth-could-end-the-era-of-poorly-paid-cab-drivers/). Noting that "estimates of the typical cab driver's salary hover around $30,000", McFarland acknowledged that "Uber's numbers don't account for the costs a driver incurs to own and operate a vehicle. Still, the gap in compensation for providing similar services is astounding".

As the story spread, many just ignored those pesky costs. CNBC [led with](http://www.cnbc.com/id/101710406) "Uber's $90K salary could disrupt the taxi business". The New Orleans Times-Picayune [headlined](http://www.nola.com/business/index.ssf/2014/05/uber_drivers_in_new_york_city.html) its story "Uber drivers in New York City earn more than $90,000 a year, newspaper reports" and Entrepreneur.com [claimed](http://www.entrepreneur.com/article/234289) "The Median Income of an Uber Driver in NYC Is Nearly $100,000". From the technology industry, CEO Mike Jones laid it out at [Code Conference](http://recode.net/2014/05/31/tech-titans-on-income-inequality-and-their-stingy-stingy-industry/): "You're qualified to drive a car, but not professionally doing it. Congratulations, boom, you're making [a] $90,000-a-year average Uber salary."

Among all this enthusiasm, a few voices did raise some questions. In _Time Magazine_ Dan Kedmey [emphasized the costs](http://time.com/119587/do-uberx-drivers-really-take-home-90k-a-year-on-average-not-exactly/):


<blockquote>Unfortunately, the figure excludes many of the costs of running a business, including gas, insurance, parking, maintenance and repairs and the original sale or lease price of the car which can take some hefty bites out of the driver's take home pay. It also measures a median income among a particularly dedicated set of drivers, logging a minimum of 40 hours a week and sometimes much longer hauls.</blockquote>


He asked Uber, but they shrugged their shoulders.


<blockquote>Just how much those costs eat away at a driver's take home wages is not easily gauged, according to Uber spokesman, Lane Kasselman. They can vary depending on the age of vehicle, the density of app users in the city, how many hours the driver puts in and what sort of customer ratings the driver receives. And for now that data, Kasselman says, is proprietary.</blockquote>


At [Mashable](http://mashable.com/2014/05/28/uber-drivers-salary-not-sustainable/), Jason Abbruzzese asked whether the income is sustainable (Uber is looking to entice drivers and has deep pockets, after all), and at The Atlantic's CityLab [Eric Jaffe](http://www.citylab.com/commute/2014/05/theres-no-way-most-uberx-drivers-make-twice-what-traditional-cabbies-do/371669/) pointed to the Uber driver protest in San Francisco, where drivers claimed they "work for less than minimum wage" and asked how these stories could fit together.

Back in December, economists Felix Salmon ([here](http://blogs.reuters.com/felix-salmon/2013/12/11/why-cab-drivers-should-love-uber/)) and Tim Worstall (of [Forbes](http://www.forbes.com/sites/timworstall/2013/12/12/how-lyft-and-uber-will-raise-taxi-drivers-incomes-not-lower-them/)) had both had fingered the culprit for taxi drivers' appalling incomes: the medallion system that many cities use means that medallion owners get to take the money. Now, in the wake of the new claims, Salmon [asked Uber](https://medium.com/@felixsalmon/the-economics-of-everyones-private-driver-464bfd730b38) for details of these extra expenses and they actually sent him numbers (take that, Time Magazine!) showing that business expenses would be around $15K, so the drivers are still making twice the norm: not bad. Salmon deemed these numbers "reasonable and entirely intuitive".

Uber, by the way, takes 20% of the fare, plus a $1 "safety fee".

Now I'm no expert, but I thought I'd take a look at some reports into the taxi industry and see what I could find out about the Uber claims. The short version is this:



	
  * The medallion owners in some cities take roughly the same amount of the fare as Uber. They may be ripping off the drivers, but the lease costs that they charge don't seem to be the main reason for the difference between the numbers. I think Salmon and Worstall have this wrong.

	
  * The Uber claims over car maintenance costs are under what other reports say about the costs. I suspect they are cherry-picked, but they are also not the main reason for the difference.

	
  * The big difference comes from the claim that an uberX car takes in $110,000 in fares over a year, while driving 40,000 miles. A regular taxi takes in about half that, and drives about 50% more. It's not clear where this difference comes from (different cities? different ways of counting? bad guesses?) but if Uber is going to stick by its claim, it needs to explain the difference.

	
  * The media writers who take business expenses as a minor factor in the driver's overall income are way off.

	
  * Put this all together, and the driver incomes look too high.


First let's look at the plight of taxi drivers. I found relatively recent reports on the taxi industry in three major North American cities: a UCLA study on [Los Angeles](http://www.taxi-library.org/driving-poor.pdf) (2006), a San Diego State University report on [San Diego](http://onlinecpi.org/reports/driven-to-despair/) (2012), and [two](http://www.itaxiworkers.ca/Reform%20proposal%202012.pdf) [reports](http://www1.toronto.ca/City%20Of%20Toronto/Municipal%20Licensing%20&%20Standards/1-Files/PDFs/Taxireview/universitystudy.pdf) about Toronto (2008, 2012). Obviously these are not San Francisco and New York, which is what Uber was writing about, but the point is not to ask if they are telling the exact truth, but to see if the picture they paint is a representative one.

The three reports paint a grim picture of a taxi driver's life. In all three cities, most drivers work six 12-hour shifts a week for less than minimum wage, even after tips. These are mainly immigrant men, and most are between 30 and 50 so many have family responsibilities. Health insurance is non-existent, and the job is dangerous with assault, vomit (which they have to pay to get cleaned) and petty aggravations as perpetual companions. I don't think anyone wants to paint a rosy picture of the taxi driver's working conditions.

But now to the numbers. There is a surprising consistency to the three cities (which I write as LA, SD, and TO).



	
  * In their 72 hours of driving each week, a driver will cover about 1200 miles (LA), of which just under half (LA) are "on the meter". The LA study gives an average of 6.2 miles-per-paid-gallon.

	
  * The total income (fares + tips) that comes into the cab over a week is about $1500 (LA), $1100 (SD), or $1150 (TO).

	
  * Gas is a significant expense, and cab drivers have to pay it. The weekly cost is about $250 (LA), $260 (SD), and $250 (TO). This suggests that San Diego drivers cover the same distance as LA, while Toronto (where gas is more expensive) cover significantly less.

	
  * Most taxi drivers pay a lease that covers car insurance and maintenance as well as earning money for the medallion owner. The weekly lease is about $500 (LA), $400 (SD), and $260 (TO). There's quite a bit of variation in each city because there is a mixture of owner-operators, shift drivers, and others at work and their situations are all different.

	
  * The Toronto report separates the car maintenance, depreciation, repair and insurance out. For LA and SD this will come out of the medallion owner's income. It is about $300/week ($70 insurance, $70 maintenance and repairs, $175 on car financing).

	
  * That leave a weekly income for the driver of about $600 (LA), $320 (SD), and $450 (TO). This comes to an annual income of $31,000 (LA), and a terrible $16,60 (SD) and $23,400 (TO).


We can put these in a table and compare them to the Uber estimates:

[Update: changed these figures on June 3 to be better averages of the driver kinds in each city.]
<table rules="groups" cellspacing="0" frame="hsides" border="2" cellpadding="6" > 

<tr >
Quantity (weekly)
LA
SD
TO
Uber (est)
</tr>

<tbody >
<tr >

<td class="left" >Fares + tips
</td>

<td class="right" >1500
</td>

<td class="right" >1100
</td>

<td class="right" >1150
</td>

<td class="right" >2070
</td>
</tr>
</tbody>
<tbody >
<tr >

<td class="left" >Gas
</td>

<td class="right" >250
</td>

<td class="right" >260
</td>

<td class="right" >250
</td>

<td class="right" >115
</td>
</tr>
<tr >

<td class="left" >Lease/Operator
</td>

<td class="right" >250
</td>

<td class="right" >140
</td>

<td class="right" >260
</td>

<td class="right" >414
</td>
</tr>
<tr >

<td class="left" >Car Operation & Depreciation
</td>

<td class="right" >300*
</td>

<td class="right" >300*
</td>

<td class="right" >300
</td>

<td class="right" >76
</td>
</tr>
<tr >

<td class="left" >Other expenses
</td>

<td class="right" >100
</td>

<td class="right" >70
</td>

<td class="right" >90
</td>

<td class="right" >0
</td>
</tr>
<tr >

<td class="left" >Driver Income
</td>

<td class="right" >600
</td>

<td class="right" >330
</td>

<td class="right" >250
</td>

<td class="right" >1465
</td>
</tr>
</tbody>
</table>
* = uses Toronto estimate, as no estimate given in report. Is paid by the lease-holder for those who lease.

Do the Uber numbers make sense? At the very least they need some explaining before we take them seriously. Here are the questions that need answering:



	
  * According to the Washington Post, Uber's sample is "drivers working over 40 hours per week". Are they working the same 72 hour weeks that taxi drivers are?

	
  * Taxi mileage is way higher than Uber' estimate of 770 miles per week. Maybe Uber is not counting the "off meter" miles?

	
  * Can they justify the low gas costs that they estimate or are they not counting time between rides (which is half the mileage for taxi drivers)?

	
  * Uber seems to take more than the leaseholder (after expenses). Given the slagging off that medallion holders get, this surprised me.

	
  * The car maintenance fee for Uber is much lower than for taxi drivers. Does this reflect a lower standard for Uber or where do they get this number?


In short, a lot of questions to be answered before Uber's claims can be justified.






		
