---
author: Tom Slee
categories:
- blog archive
date: 2012-12-31 22:28:31
title: 'Peer-to-Peer Hucksterism: An Open Letter to Tim Wu'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Dear Tim Wu,

Has something happened to your brain? Can your short article in the _New York Times_, [Apps to Regulate Apps](http://www.nytimes.com/2012/12/20/opinion/the-best-way-to-regulate-urban-living-apps.html), be the product of the same grey matter that produced the excellent "Who Controls the Internet?" and the admirable "The Master Switch"? What's going on? I hope it was a momentary lapse and I hope you will change your mind about this sloppy and potentially damaging piece.

You were writing, as you know, about AirBnB and Uber: two new "peer-to-peer" companies building big businesses around apps that let you "book a car ride or rent someone's apartment using your smartphone or computer", and apparently [breaking a few laws](http://www.thestar.com/news/gta/article/1298266--uber-taxi-charged-with-licensing-offences) along the way. You write that "no one can deny that these apps are responding to real demands and helping cities become easier to live in and visit", and you place them on the side of Progress, and the Future; in contrast, the reactions of cities who have banned these apps "recall Ned Ludd's response to the automated loom".

While you do acknowledge that there are complaints about the companies, you decide that "many of the complaints are anecdotal". But complaints are always anecdotal unless someone tallies them, and tallying them is, of course, one of the points of regulation: AirBnB and Uber are not tallying them, that's for sure. They may even try to [sweep them under the rug](http://gawker.com/5825996/airbnb-pillage-victim-says-company-tried-to-keep-her-quiet) in case it damages their valuation: exactly the kind of conflict of interest that make regulations necessary in the first place.

But let's step back a bit. I'm no Valley Visionary, so if I were setting up a business based on offering unlicensed hospitality or cab rides, I might ask myself a few questions first. And I may ask myself: why is it that every town and city I've ever been to has licensing requirements for people offering taxi services or overnight accommodations? Is there a global taxi cartel or a multinational bed-and-breakfast conglomerate enforcing its will on municipalities from Aberystwyth to Yellowknife? And if there isn't -- and of course there isn't, because taxi and B&B operations are usually local and small-scale operations -- I may ask myself: what's behind all these rules?

And if I stopped for more than two minutes before seeking seed funding for my enterprise, I may tell myself about property zoning, about landlord-tenant agreements, about the risks run by customers who step into a taxi or a hotel in a strange city, about liability in the event of accidents, about the importance of equitable access, about complaints investigation, about safety checks, and more. Not, of course, that licensing is unproblematic in all cities – far from it – but these would at least be things I would wonder before proclaiming that those who stand in the way of my right to make a buck are simply Luddites. And if I were to advocate changing zoning regulations in cities throughout the world, and changing taxicab licensing rules too, with all the expense that comes with those changes, I'd have put a little thought into it. Especially because, as you say in your final sentence, "It is, in short, a time to think carefully". Unfortunately, all the evidence is that AirBnB and Uber have not stopped to think, so the idea that they should set the agenda for civic licensing discussions, placing new stresses on the already-stretched finances of municipalities around the world, despite displaying such solipsistic lack of attention, is presumptuous at least and offensive at worst.

Unfortunately your two suggestions – that cities should require the companies to provide applications which could be used by landlords and co-op boards with a check on their tenants' use of AirBnB, or that cities could "simply" require Uber to disclose information about its prices and traffic – do not even scratch the surface of the issues that need to be sorted out before AirBnB or Uber can be taken seriously as forward-thinking, sustainable partners in civic development. And I hope that, if you reflect, you'll agree that the new peer-to-peer companies are a blight on the landscape of egalitarian thinking. Yes, according to [CNN](http://tech.fortune.cnn.com/2012/05/03/airbnb-apartments-social-media/), CEO Brian Chesky "thinks of Airbnb as more than a company – to him it is a movement. His site invites users to return to a time when hitchhiking wasn't dangerous – when it was just fine to share anything with strangers because no one was all that strange." But Brian Chesky has not tried to start a movement, he's started a company: and he hasn't actually done anything much to make hitchhiking less dangerous. He wants his customers to think of it as a movement while he owns the business. While they invoke the communitarian traditions of the informal economy, these new peer-to-peer companies are more likely to erode that economy than enhance it.

We all know the informal economy. I used to hitchhike to university, my neighbours have yard sales, friends help each other move house. None of this activity is regulated because it's at most minimally commercial. But there is a line, of course: if I started having a yard sale every weekend then my neighbours might think I'm stretching a point and complain to the by-law people. If I rented my house to strangers week in and week out – for money -- they might ask if I'm running a rooming house. And that's assuming that the people renting my house aren't [running a brothel](http://www.nbcnews.com/travel/airbnb-rental-sweden-allegedly-used-temporary-brothel-944402). So there is a trade-off here: informal activity for little or no money is OK. Commercial activity plays by different rules; a level of accountability is needed.

So now here comes AirBnB (to take one example), who want to keep the idea that it's about the noncommercial and "sharing" informal economy, and scale it up. They talk about their hosts in a non-commercial sense: earning "additional income", or "extra money" ([link](http://www.theatlanticcities.com/housing/2012/08/micro-subletting-thriving-new-york-it-legal/2897/)) -- rolling out, I could not help but notice, the very phrases used years ago to justify not giving women's jobs the same protections and benefits as men's jobs. It's not the real economy, it's just a bit of pocket money: we don't need all those expensive rules and regulations. But they want to build a [billion dollar business](http://techcrunch.com/2012/09/26/airbnb-is-raising-a-big-third-round-aiming-for-a-valuation-north-of-2b/) on the back of it. And while eBay famously did this for knick-knacks, the nature of the activities makes the two companies completely different. There are information asymmetries with serious consequences here. The model is that AirBnB take 10% of the booking fees and take [0% of the responsibility](http://www.digitaltrends.com/social-media/why-the-house-that-airbnb-built-stands-on-shaky-legal-ground/) for what happens when you book, or hire, a room. Now many exchanges do go well, partly because the early stages of an activity like this do draw from a community of people who are committed to the non-commercial side of the action, but the success attracts others, and for personal safety in such cases (rare incidence but severe consequences) recommender systems are simply not the right tool. It's not like Wikipedia (or eBay or Yelp) because you can't just Undo an apartment-trashing, and the fact that AirBnB had not thought about what happens when an apartment is trashed shows, as Farhad Manjoo [writes](http://www.slate.com/articles/technology/technology/2011/08/renters_from_hell.html), that is simply wasn't thinking. It didn't care. And if Brian Chesky really thought about AirBnB as a movement, he'd care.

The questions are heightened by the contrast between the community-friendly rhetoric of the company and the apparent character of its founders. One has a reported history as a spam-merchant (that and more [from Ryan Tate](http://gawker.com/5853754/the-seedy-spammy-past-of-airbnbs-co+founder?tag=valleywag)), and the financing has raised [ethical questions](http://allthingsd.com/20111001/vcs-unite-chamath-palihapitiya-decries-airbnbs-recent-112m-funding-for-excessive-founder-control-and-cashout-in-email/) about the way in which early investors can take large amounts of money out of the business without diluting their control. The long and short of it is that the company runs as a scheme to make large amounts of money for a small number of people by appealing to large numbers of egalitarian-minded young people. Investment (and presumably board-level presence) from Andreessen-Horowitz, Yuri Milner, and now maybe Peter Thiel, all with well-known neo-liberal attitudes, makes this clear.

Your other company, Uber Taxi, has a similar litany of complaints: taking a [50% cut of tip money](http://gigaom.com/2012/10/05/chicago-cabbies-sue-hip-car-service-uber-for-pocketing-50-of-driver-tips/) (illegal in many places), and [more](http://pandodaily.com/2012/11/14/what-taxi-industry-outsiders-dont-get-about-vc-funded-taxi-apps/). The "surge pricing" following Hurricane Sandy is a clear example of the eat-your-cake-and-have-it approach that characterizes these peer-to-peer businesses: the company [adopts](http://pandodaily.com/2012/10/31/assholes-shrug/) hard-nosed Economics 101 pricing models (which we can argue about) while employing a rhetoric of community and sharing. You can have at most one or the other, but not both. Unsurprisingly it is run, as [Seth Finkelstein](http://sethf.com/infothought/blog/) pointed out on my previous post, by [an admirer of Ayn Rand](http://pandodaily.com/2012/10/24/travis-shrugged/).

The contrast with real efforts to break down barriers to access and to make more accessible, non-commercial travel a reality is dramatic. None of the peer-to-peer companies "[start from an entrenched social problem and work backwards from there](http://cbracy.tumblr.com/post/39314979304/silicon-valleys-problem)" as Catherine Bracy writes. For real inspirarion, look back to efforts like the Ramblers Association's 1932 [mass trespass of Kinder Scout](http://en.wikipedia.org/wiki/Mass_trespass_of_Kinder_Scout), the services provided over the years by the [Youth Hostel Association](http://www.yha.org.uk/about-yha/yha-today) and [Hostelling International](http://en.wikipedia.org/wiki/Hostelling_International), all characterized by a broad base, by people who thought about what they were doing, and who had an actual commitment to their goals. And guess what? Remarkably enough, none of these has billionaire venture capitalists - or even the profit motive - behind them.

So, Tim. Back to the beginning. The Randian, simplistic free-market thoughtlessness behind the wave of "peer-to-peer" companies, and especially those who are trying to uproot regulations that protect consumers, is far from the wave of the future: it's hucksterism masquerading as progress, hubris as vision, callous selfishness as community-mindedness, and it's a disaster waiting to happen. I don't think it's something you want to associate yourself with. Will you retract your support for AirBnB and Uber?

yours,

Tom Slee

Written in Org version 7.8.10 with Emacs version 23		
