---
author: Tom Slee
categories:
- blog archive
date: 2007-04-11 23:42:58
title: The Long Tail 15 - Coda
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is the final part of my critical reader's companion to _The Long Tail_, and it discusses the Coda. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html).

* * *

"Coda" is the very last section of the Long Tail, and this is the very last section of my critique of the book.  





The book's "Coda" is a two page piece that talks about [3D printers](http://en.wikipedia.org/wiki/3D_printing), which may enable all kinds of other goods to become digital - just as documents and music and photos and videos have all moved from being solid things to being digital - "materialized" where you download them.




And the lesson of 3D printing is that we'll see "the explosion of variety we've seen in our culture thanks to digital efficiencies" [226] extended to other areas of our lives.




The coda summarizes some of the things I find so frustrating about this book, and why I've spent so much time on it. It's not just that it's a bad book - although I do believe it is - but that it is a bad book about some really important changes; changes with the potential to do great good and great harm. Reading [Chris Kenny's](http://www.indie4k.com/archives/21) reflective commentary emphasized this for me. Anderson holds up a picture that is very attractive - greater diversity, a broadening of voices in public discussion, a chance for people without connections to have a say, and so on - and he says he's all for it. And he's all against stodgy old "institutions". So the book attracts people who are doing interesting things, and thinking along admirable lines.




But then he betrays us. Because when it comes down to it, he's on the side of multi-millionaires and billionaires, and the "institutions" he feels so rebellious about are small publishers, small bookshops, and so on. Not that he'd put it that way, but that's the effect of his arguments. He argues that we should celebrate Netflix, Amazon and a handful of others, and trust them to be the custodians of our culture because they'll deliver variety. It's a dangerous argument, predicated on the fact that these are somehow different companies - a kinder capitalism. And it's wrong, of course.




To review, here's what I see as the main flaws that run throughout the book:




Flimsy Foundations - Despite the talk of openness, the empirical core of the book is a set of numbers vouched for only by the CEO's of companies who stand to benefit from their association with radical new ideas. Netflix, Amazon, iTunes and Rhapsody let him see their figures under strict conditions. There is, in the end, little to demonstrate that some of these companies are delivering on the promise of the Long Tail. The evidence that iTunes is a "Long Tail aggregator", for example, is non-existent.




Protean Perspectives - The Long Tail is sometimes a set of rules for how to build a profitable business, sometimes an assertion about economic and technological forces, and sometimes a claim about cultural change. The book tries to shove Wikipedia, blogs, Netflix, and more into a single tent - and it doesn't hold. I've no problem with using a single name for multiple related ideas, but Anderson shifts from one meaning to another to another throughout the book, and the result is a form of misdirection as he invokes whichever is needed to make the point he wants to make. It makes criticism difficult, but in the end consistency matters, and the book lacks it. Instead of each part of the story strengthening the others, the whole edifice turns out to be built on nothing.




Failure to Follow the Money - As Bertoldt Brecht said "Amongst the highly placed it is considered low to talk about food. The fact is: they have already eaten." Of course the CEOs of new technology businesses aren't interested in talking about something as mundane as money, but we must, and Anderson doesn't. This matters for two reasons. 




First, the book conflates non-commercial and commercial initiatives - Amazon's recommendation engine and Wikipedia, for example - as if they are not different. But they are. There is much talk of community on the web, but corporate-sponsored "communities", while they do have their place, are not communities in any significant sense. On the other hand, an effort like Indymedia is a real community. These are different things. I have worried that by emphasizing how different the phenomena of the web are that I'm missing the big picture - but I'm pretty confident that's not the case. The Long Tail big picture is a mirage: the closer you get to it, the less tangible it is. 




Second, there is a political effect that we've seen with successful aggregators. A single iTunes, coupled with Wal-Mart, drives many independent businesses out of existence. The result is the opposite of the democratization Anderson claims to be promoting. The emergence of iTunes is a centralization of influence within the music industry, not a decentralization. Amazon is not a proletarian revolt against the tyranny of elitist bookshops, it's the driving out of many small businesses by one big business. Money is flowing through these new organizations, and it is flowing towards fewer people than ever, not more. To ignore the impact of technology on inequality is to take a political stance, and it's not a progressive one.




Selective Vision - We see this in the comparison of the "old world" to the "new world". By comparing Rhapsody music to Wal-Mart, Anderson is stacking the deck - something he does throughout the entire book. What's more, he's mistaking the dynamic that is at work in the world of business. While Anderson sees online commerce as challenging the Wal-Marts of the world, it too often complements them. If I had these posts to write over again I'd start off at the beginning by pointing out that technological forces are creating, not a Long Tail, but a technological vice. On one jaw is the big box store, stocking a few titles at cheap prices. On the other jaw is the online store, stocking everything (but not necessarily selling a whole lot of everything). This is not the way to produce a culture of variety. My prediction: as these enterprises realise how complementary they are, we'll start to see more in the way of mergers between the two worlds.




Selective vision is also at work in his perception of the new companies. While the book celebrates the open sides of their business models, he completely ignores the other side. Google, Amazon, Netflix are all secretive when they want to be. They all pursue patents with vigour in order to close down the possibility of competition. Netflix even [patented](http://www.hackingnetflix.com/2006/04/netflix_patent_.html) its "mailing and response envelope" - this is not "radical transparency" as Anderson has taken to calling it. We the consumers are let inside the walls to play, but in a carefully controlled playroom. And we're kept out away from the valuables.




Finally, in his enthusiasm to celebrate variety he bundles pseudo-variety (wall-of-toothpaste variety) with real variety. Is there no distinction? Of course there is, but Mr. Anderson is blind to it.




The end result of all this selection is a muddled and distorted picture. It sounds great at first reading, as Anderson runs through examples of new variety at breakneck speed, but stop a minute and you realise he's only telling one half of the story - and half the story can never give the whole picture, no matter how many examples he finds. And even then he's not telling it straight.




So what do I think? Do I think the Internet is a force for good or
bad? Yes. Is it a force for increased decentralization or increased
centralization? Absolutely. Is new technology a source of increased
variety or increased homogeneity? No doubt about it.   

  

The Internet and related technologies are going to have a huge effect
on our society. Or rather, many huge effects. And which ones win out -
the good or the bad - will be determined by people actively struggling
to ensure that their vision of it prevails, not by trusting to the
market to solve it for us. Part of the appeal of The Long Tail is that
it talks of the "democratization of production". Innovative cultural
ideas (as opposed to technical ideas) will often be found at the
margins; in Jane Jacobs wonderful phrase "new ideas need old
buildings", and this means they need to be done on the cheap, often
subsidized through non-market routes, and nourished. While Internet
technologies are one more path that cultural innovators can follow, it
is a big mistake to trust commercial enterprises, be it Amazon or
Netflix, to act as custodians of the public space that is variety. With
his heart, I suspect, in the right place, Anderson is leading us down a
dangerous road, and that's why I've spent so many hours showing what's
wrong with his book.




For anyone who has made it to the end, let me finish by pointing you to a [posting](http://www.longtail.com/the_long_tail/2007/01/the_beginners_g.html) on the Long Tail blog, where Chris Anderson walks through the major objections to his book. Here are his "top five mistakes" with a one sentence answer from Anderson (there's more on his blog):

<blockquote>X was a hit! See? Hits aren't dead. - "I never said they were"  
I've done an analysis of this dataset and, in percentage terms, it shows that sales are become more concentrated in the head, not less - "Hah! This is the percentage mistake."  
I'm in the Long Tail and I'm not rich yet - the theory clearly doesn't work. - "The big money in the Long Tail is in aggregation"  
You said that 57% of Amazon sales are Long Tail. No way. - "I know. That part .. has been revised to 25%"  
You call Blockbuster and Barnes & Noble the Short Head. But what about Blockbuster.com and BN.com? They've got every bit as big an inventory as Netflix and Amazon. - "Sigh. Please understand the definitions. Short Head = inventory in the typical store of the largest bricks and mortar retailer in a market.
> 
> </blockquote>

None of these objections is a significant part of what I've presented here, except for number 3 - and I still think it is true that a "theory" unaffected by a 100% change in a major piece of data is a theory that needs a more empirical basis and a little less enthusiasm. My objections are on other grounds entirely. I suspect they come too late to slow down the passage of "Long Tail" into the conventional wisdom of technological/business discussions but hey, you do what you can. Thanks for sticking with me.


		
