---
author: Tom Slee
categories:
- blog archive
date: 2012-12-02 21:12:36
title: 'When Theories Matter: Uprisings in Authoritarian States'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

(Second in a series of hopefully accessible posts about [this](http://papers.ssrn.com/abstract=2116471) hard-to-read paper).




From time to time, sitting in a comfortable chair with a cup of coffee reading disputes about Twitter Revolts and Facebook Revolutions, it is easy to think that The Argument is the Thing. But it isn't, of course. The public profile of these debates about how digital technologies intertwine with dissent in authoritarian states, sprawling from the pages of the _New Yorker_ to _Foreign Policy_, from specialized academic journals to urgent pamphlets, means that the arguments may influence the choices of dissidents operating in perilous environments; may sway them one way or another as they make life-changing decisions. So the least we can do, even those of us on the fringes of the debates, is to try for the truth.




Particularly strange, perhaps, is that these disputes are unavoidably theoretical. Of course, it matters greatly to tell a coherent and accurate story of how events played out in each particular case, but the implications of the debates are most urgent for uprisings that have not yet happened and for protests that have not yet been organized. No matter how exhaustively one recounts the unfolding of events in Tunisia in 2011 and 2012, such a telling alone cannot provide guidance to dissidents in Azerbaijan, in Russia, or in Canada for that matter. We cannot avoid theory: we point to a set of mechanisms and say "this happened here because of these conditions and for these reasons. In other conditions in different places, here are the possible outcomes". Talk turns inevitably to what is primary and what is mere epiphenomenon. We tell stories that highlight what seems essential and draw attention away from the factors that we deem unimportant. We theorize, and we tell stories based on those theories. We retell anecdotes that encapsulate those theories to prove our points.




When it comes to questions of digital technologies and their roles in political change, and particularly dissent in authoritarian states, there is a whole vocabulary that has come into being that carries along a set of narratives. There are assumptions behind terms such as "digital activist", "internet freedom", and "network society" that carry over into the stories and the habitual grooves of thought that we take with us as we try to understand new developments.




One current that has been particularly influential in the debates around the "Arab Spring" uprisings is based on the idea of informational cascades, and this current provides the theory behind much of the optimistic talk about Facebook revolutions and the potential for digital technologies to undermine authoritarian regimes. It's not the only theory of uprisings, but it is a compelling one. So if you're going to tell a different story about digital technologies, you need a different theory. I went looking for what that theory should be, and didn't find one, so I put one together myself, and that's what these posts are about.




Next: a look at information cascades and what they leave out.


		
