---
author: Tom Slee
categories:
- blog archive
date: 2005-12-15 22:08:00
title: Globollocks from the Globe and Mail
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Globollocks is, [according to Daniel Davies](http://crookedtimber.org/2003/10/16/globollocks-watch), aka [dsquared](http://d-squareddigest.blogspot.com/), "breathless and/or mendacious “Globalisation” pieces from neo-liberal commentators". Davies has a magnificently complete scorecard on this, and today's Globe and Mail editorial (I read the dead tree version: the online version is all but the [first paragraph ](http://www.theglobeandmail.com/servlet/Page/document/v4/sub/MarketingPage?user_URL=http://www.theglobeandmail.com%2Fservlet%2FArticleNews%2FTPStory%2FLAC%2F20051215%2FEHONG15%2FTPComment%2FEditorials&ord=1134701575604&brand=theglobeandmail&force_login=true)behind the wall) scores highly. From dsquared's scorecard:




  * 
Mentions China as “globaliser” without qualification—3 points.


  * 
Refers to Botswana, Singapore or Hong Kong as if they provided development models—2 points


  * 
General failure to distinguish between capital and goods openness – 1 points


  * 
Says or implies that there is no anti-globalisation movement in developing countries – 2 points


  * Says or implies that developed world antiglobalisation movement “has no
idea of what it is in favour of”, “is opposed to trade” or “wants poor
countries to stay poor”—1 point each


  * 
In general, argues back and forth between general statements about
trade and specific statements about currently live negotiations – 1-4
points on a sliding scale
(I award 4 on this one).



So I'd award the Globe about 12 points, which is pretty good, especially for a 5-paragraph editorial. Pretty high scoring.


		
