---
author: Tom Slee
categories:
- blog archive
date: 2005-12-06 07:52:10
title: On Their Own in Battered New Orleans - Los Angeles Times
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Via [Brad DeLong](http://delong.typepad.com/sdj/2005/12/a_very_good_lon.html), an essay in the Los Angeles Times about the difficulties of reconstruction in New Orleans: [On Their Own in Battered New Orleans - Los Angeles Times](http://www.latimes.com/news/nationworld/nation/la-na-orleansrisk4dec04,0,7970585,full.story?coll=la-home-headlines).




The article picks up on two ways in which sensible individual choices may lead to very different outcomes. 




What seems to have happened is that the US government has decided that the free market will take care of rebuilding New Orleans, as "the agencies that were stepping up to help guide the city's comeback have stepped back down again" and "[t]o an extent almost inconceivable a few months ago, the only real
actors in the rebuilding drama at the moment are the city's homeowners
and business owners."




Reconstruction of a city is different from buying cauliflower though, and the article quotes Thomas Schelling as saying "There is no market solution to New Orleans... It essentially is a problem of coordinating expectations. If
we all expect each other to come back, we will. If we don't, we won't. But achieving this coordination in the circumstances of New Orleans seems impossible."




The LA Times interviews one woman who is trying to decide whether to return and rebuild or to just move out. She would like to rebuild, but only if she would be surrounded by a neighbourhood. There is no sense rebuilding in a wasteland:

<blockquote>As a work crew gutted 1249 Granada Drive on Monday, heaping appliances,
sofas and sheetrock in a 6-foot pile on the curb, Laurie Vignaud
suddenly realized her only evidence that any of her neighbors had
returned since Katrina was similar heaps outside their houses.
> 
> </blockquote>

<blockquote>But do those piles mean that Granada Drive residents are ready to
rebuild, or simply are picking through the wreckage and trying to buy
time by stopping the mold's spread?
> 
> </blockquote>




<blockquote>"I keep looking at all this stuff and wondering whether they're
coming back or not," said Vignaud. "It's crazy, like a riddle I can't
solve."
> 
> </blockquote>




What is needed here is co-ordinated, collective action rather than individual, market-like behaviour. And those communities that have ways of co-ordinating such activity are the ones who are returning:

<blockquote>In fact, a few neighborhoods appear to have solved the riddle, or
at least to have taken a good run at it. But the ways in which they
have says much about the daunting dimensions of the problem facing the
rest of the city.
> 
> </blockquote>




<blockquote>On the northern edge of the city is New Orleans' Greek Orthodox
community and its church, Holy Trinity Cathedral. As warnings about
Katrina grew darker in the days before the storm, community leaders
matched up families to whisk the elderly and infirm out of danger. In
the days immediately after, they mobilized to come back again.
> 
> </blockquote>




<blockquote>"We ran it like a business," said John D. Georges, the parish
council president and chief executive of Imperial Trading Co., a
regional supplier of convenience stores.
> 
> </blockquote>




<blockquote>Father Anthony Stratis worked the phones and sent out e-mails to
find parishioners. Parish council member Dr. Nick Moustoukas followed
up by wiring money to the neediest. Ten days after the storm, Georges
and council member Christ Kanellakis helicoptered in to rescue the
church's chalice and tabernacle.
> 
> </blockquote>




<blockquote>By acting in concert, members of the Greek community have in
effect provided each other with an immense self-insurance policy,
guaranteeing that if one family rebuilds, others will. And, should more
enticement be needed, the church, according to Georges, Moustoukas and
others, is providing returning families with thousands of dollars of
cash aid, has organized bulk purchases of new appliances and has
arranged for crews that repaired the cathedral to be introduced to
people whose houses are in need of work.
> 
> </blockquote>




<blockquote>By the time the cathedral reopens for its first full service in
two weeks, its marble interior walls will have been repaired, its lawn
will have been resodded and Holy Trinity will be back in business.
> 
> </blockquote>

The second way in which individual choice may go wrong in New Orleans is not so much about the relationship among the citizens of the city, it is more about the relationship between citizens and government. If citizens are to return, they need a commitment from the government that the city will be made safe. Meanwhile. the government is backing off:

<blockquote>"If they put back good levees to the [Category 3] level authorized
before Katrina and we can get a commitment to build them slowly up to
Category 5, people will come back," said Walter Isaacson, a News
Orleans native, former editor of Time magazine, former chairman of CNN
and co-chairman of the Louisiana Recovery Authority, a new state board
appointed by Gov. Kathleen Babineaux Blanco to oversee reconstruction.
"It won't be a purely rational decision, but they'll come."
> 
> </blockquote>




<blockquote>
But the corps has made it clear that it has no intention of making any such grand commitment soon.
> 
> </blockquote>




<blockquote>In part, the problem is cost; estimates of what it would cost to
bring the city's levees up to Category 5 range from $4 billion to more
than $30 billion. In addition, the corps' budget is perhaps the most
closely controlled of any in the federal government, with Congress
ear-marking almost every dollar to particular projects, leaving the
corps little maneuvering room.
> 
> </blockquote>




<blockquote>But there also appears to be a sense among senior corps officials
that local demands for greater protection, if indulged, would be
unceasing.
> 
> </blockquote>




<blockquote>"It's of interest to me," New Orleans district commander Col.
Richard P. Wagenaar told the Los Angeles Times several weeks ago, "that
all the political leaders, all the business leaders and all the
homeowners were all perfectly comfortable with the system on Aug. 28,"
the day before Katrina made landfall. "They knew full well it was being
built to Category 3, and everybody was fine with that," he said.
> 
> </blockquote>




<blockquote>But when a storm of greater strength struck and overwhelmed the
levees, Wagenaar said, people "suddenly wanted to look back and say,
'Hey, what happened?' " The implication: When would calls for still
more ever end?
> 
> </blockquote>




The concern is apparently one of moral hazard, that by investing in New Orleans the agencies will simply encourage demands for more. I have no way of knowing if there is any basis whatsoever to the concerns (although in other circumstances, such as health care, the concern is overrated as Malcolm Gladwell recently explained). But it is clear that without a real commitment from the government, New Orleans won't rebuild quickly.




This is what happens when you have a government who doesn't believe that governments can be useful. It is too bad.


		
