---
author: Tom Slee
categories:
- blog archive
date: 2007-10-13 14:33:24
title: Infrequently Asked Questions
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I did say I have a few pieces I wanted to post still, so here (now the Ontario election is over) is one of them. A few questions a few people have asked me about _No One Makes You Shop at Wal-Mart_...




**Where did you get the title?**  
The title evolved along with the content of the book. I think the first version of it came from Paul Krugman's essay [Enemies of the WTO](http://www.pkarchive.org/trade/wto.html) which was published in Slate on November 24, 1999. I'd admired Krugman's writings for some time, and yet had anti-globalization leanings. The end of his essay (which I quote and misattribute on p. 190) encapsulates the challenge I wanted to address:

<blockquote>Although they [anti-globalization protesters] talk of freedom and democracy, their key demand is that individuals be prevented from getting what they want--that governments be free, nay encouraged, to deny individuals the right to drive cars, work in offices, eat cheeseburgers, and watch satellite TV. Why? Presumably because people will really be happier if they retain their traditional "language, dress, and values." Thus, Spaniards would be happier if they still dressed in black and let narrow-minded priests run their lives, and residents of the American South would be happier if planters still sipped mint juleps, wore white suits, and accepted traditional deference from sharecroppers ... instead of living in this "dreary" modern world in which Madrid is just like Paris and Atlanta is just like New York.   
Well, somehow I suspect that the residents of Madrid and Atlanta, while they may regret some loss of tradition, prefer modernity. And you know what? I think the rest of the world has the right to make the same choice.
> 
> </blockquote>

Just before that paragraph he uses the sentence "And nobody forces you to eat at McDonald's", which I latched onto. When I first sent the book to the publisher I took a couple of syllables out, shortening it to "No One Makes You Eat at McDonald's".




The change to Wal-Mart came about for two reasons. First, the McDonald's example turns out to be a difficult one that I only address 90% of the way through the book, and so the title didn't match the structure of the manuscript. My Wal-Mart story had moved into Chapter 1 by that time, as the very first story in the book, and so "No One Makes You Shop at Wal-Mart" just made a lot more sense. Also, of course, in the years between 1999 and 2005 Wal-Mart had supplanted McDonald's as the pre-eminent symbol of rampaging capitalism. So that decided it.




In retrospect: I'm pretty pleased with how the title worked out. It's misleading because everyone thinks it's a book about Wal-Mart and assumes it's kind of a popular journalistic polemic, but at least it catches the attention and that's all you can hope for.







**Why do you call the town Whimsley?**





To me the name is a mixture of something whimsical and something down to earth, both of which the stories are meant to be. I think the whimsical-whimsley part of that is obvious enough. The "ley" ending is a reference to the many millstone grit towns of Yorkshire that end in that syllable - Burley, Ilkley, Batley, Bramley, Barnsley and probably hundreds of others, but particularly Otley, the nearest town of any size where I grew up. There cannot be many more pragmatic, realistic places around.




In retrospect: I still like the name.




**Why are the two characters called Jack and Jill?**




These names are a reference to the R.D.Laing book _Knots_, which I was introduced to by either Nigel Perry or Clive Norris in 1978. It's a quirky book that sets out patterns of tangled behaviour in short structured vignettes like this:




Jack is afraid Jill is like his mother  
Jill is afraid Jack is like her mother

Jack is afraid  
Jill thinks he is like her mother  
and that Jill is afraid  
Jack thinks she is like his mother




Jill is afraid  
Jack thinks she is like his mother  
and that Jack is afraid  
Jill thinks he is like her mother




To tell the truth, I never really got very far with the book, slim though it is, but the recursive form of these vignettes has stayed with me. I had hoped I could make my stories condensed and elegant in the same fashion, but they ended up being more pedestrian. Ah well. (In earlier drafts the two characters were called Winston and Julia, but that is melodramatic and obvious, so it went.)




**Why did you coin the word MarketThink?**




Was it needed? I'm not sure now. At the time it seemed important. It is close to the idea of market populism that [Thomas Frank](http://www.tcfrank.com/) writes about so well in One Market Under God, and close to the idea of market fundamentalism, a phrase used by many people. But both of these terms convey the idea that their supporters are promoting markets as solutions to all problems. The reason I didn't want to use those is that those who promote this loose, populist ideology do not always promote free markets - certainly not ideal competitive markets. Intellectual property is an obvious area where promoters of private industry are keen to prevent the competition they claim to believe in elsewhere. Nevertheless, the rhetoric of MarketThink portrays the world (governments aside) as if it works like an ideal competitive market, even when proposing actions that contradict that portrayal. Boeing is quite happy to argue for the necessity of government subsidy in the name of markets, and companies that grew large under protectionist regimes are happy to promote free trade as long as they are beneficiaries. So I thought a different word was needed, and MarketThink seemed to be it.




In retrospect: I'd probably avoid coining a new word and simply use "market populism". I was splitting hairs.


		
