---
author: Tom Slee
categories:
- blog archive
date: 2006-04-12 23:44:00
title: Schelling on Iranian Nukes
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Written (based on a talk, so it is a bit casual and disjointed) a little while ago, but newly relevant given the fuss about the Seymour Hersh New Yorker piece. Sample paragraph:

<blockquote>**THE US BUNKER BUSTER |** The US government ought to
recognize the taboo is in its favor and not try to develop a new
generation of weapons with the aim of making them somehow useful on the
battlefield. I’m afraid a lot of people in the Pentagon think, “We are
so rich in nuclear weapons, it is a shame not to use them.” They should
learn we are so rich in people and infrastructure that we will risk
losing that if we encourage others, by our own example, to look
positively on the use of nuclear weapons.
> 
> </blockquote>

Link: [NPQ](http://www.digitalnpq.org/archive/2006_winter/schelling.html).


		
