---
author: Tom Slee
categories:
- blog archive
date: 2006-10-25 23:46:26
title: 'The State Versus The Market: The Tale of the Toilet'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

* * *

[The Flusher King](http://tinyurl.com/yzana2) by Peter Scowen, Toronto Star, Sunday October 22, 2006, p. D1.  

[Maximum Performance Testing of Popular Toilet Models](http://tinyurl.com/ylghy8), 7th Edition, Canadian Water and Wastewater Association.




* * *

The debate seems endless. The left says the
market doesn't work; the right says government just makes things worse. It's an old argument, and it's time to get it sorted out. 





The trouble is, this argument is always made in the abstract. It's just
generalities. Principal-agent problems here, collective action problems
there, it's just so much verbal diarrhoea. 




If you're going to have any chance of a realistic answer, you
have to get your hands dirty and take a close look at a real problem.
So that's what I'm going to do.





And the best place to look? In the toilet. Or more specifically, in the
low-flush toilet which, after many years of messy failures, is now
positively flushed with success. What made it succeed? Was this the
innovation of private industry? Schumpeterian creative destruction at
work? Or is this a case of state-mandated standards flushing away a
problem that the free market just left floating in the pan? 




Thanks to
the [Toronto Star](http://tinyurl.com/yzana2)
(link works for free until the weekend) we now have the unadulterated
story. Pretty much everything I say here comes from that article.





Let's start at the beginning. In places where households don't pay the
full cost of their water, which is a lot of places in North America,
there is a free-rider problem when it comes to water conservation. We'd
all save money if our toilets used less water when they flushed. It
saves in water treatment costs, and it saves because there is less
water to send through the pipes. It's just a good thing. But if we don't pay the whole cost of water ourselves, the best choice for each of us is to stick with our current toilet and let others invest in a low-flush model.





But the free market was failing to deliver a low-flush toilet. While
government bureaucrats were of the opinion that 6 litres is enough to
get rid of what needs to be got rid of, the toilet manufacturers were
all selling models that delivered 13 litres (in imperial measurements,
that's three furlongs and a fortnight) with each pull of the chain (are
there actually any made with chains any more? It would be a great retro
item I think.) Why was the free market failing? Well, probably for lack
of a push from consumers. If you're not paying the full cost of the
water, you don't really care whether your toilet uses 6 litres or 13.





So, the obvious solution here is government intervention, and in some
places (the USA) in the early 1990's the government decided to get tough, and
used its monopoly on force -- you know, that monopoly the libertarians
are always complaining about -- to compel the toilet manufacturers cartel to adopt an
environmentally friendly line. They outlawed high-volume toilets. One for the state! (although to be honest
I don't know which level of the state it was).





But as we've been told by the libertarians and right wingers, government intervention does not necessarily improve matters, and
one reason is the old problem of information. You can sell a toilet
that delivers 6 litres per flush, but as a customer how do you know if
that toilet is going to do what is needed? Well, before you buy it, you
don't, so there is an obvious "market for lemons" problem here. The state
can lead the manufacturers to use less water, but it can't make them
flush thoroughly. Someone needs to do some testing to establish some
clear standards, and who is going to do that?





Market enthusiasts will not be surprised to hear that although the US
government (whichever part it was) had got tough in the letter of the
law, it seems that it didn't follow through, leaving it to municipalities to find a solution. Seattle and Oakland trusted the Third Way idea that testing could be
contracted out to a private industry group called the National Home
Builders' Association, which describes itself "a Washington, D.C.-based
trade association whose mission is to
enhance the climate for housing and the building industry." Market
sceptics would just know these tests aren't going to be really solid,
and so it proved: they used a set of weighted sponges. Sponges!?





Whether this faulty testing was a fault of Blairite PPP illusions or
not, the 1990's was a decade in which government intervention seemed to
have made all things loo-related worse. 




The most vocal opponent of the low-flush
mandate is, of course, ex-Miami Herald columnist Dave Barry. He
describes the low-flush toilets as toilets that can leave you lurking
in the bathroom at a party "for what
seems (to you) like several presidential administrations, flushing,
checking, waiting, flushing, checking." If you have to flush two or
three times, a 6-litre toilet does not save water, and for years Barry
was a vocal defender of "the older 3.5 gallon models - the
toilets that made this nation great; the toilets that our Founding
Fathers fought and died for." (For those who want the primary source
material, much is collected in collections such as [Dave Barry Is Not Taking This Sitting Down](http://www.amazon.com/Dave-Barry-Taking-Sitting-Down/dp/0345444094)).




Mr. Barry has written a lot about toilets, and most of it has been
re-read to me by my two teenage offspring, interrupted by long bouts of
giggling until cornflakes come out of their nose. For those of you who
don't know him, here is a little of Mr. Barry, writing in 2004:




<blockquote>

> 
> I am often criticized for writing immature ''bathroom'' humor, and
not enough about important topics. So today I'm going to write about a
major international event that is going to take place Nov. 17-19 in
Beijing, China: The World Toilet Summit. 
> 
> 

> 
> I am not making up the
World Toilet Summit. It was brought to my attention by alert reader
Marc Howell, who alerted me to the World Toilet Organization, a group
dedicated to improving the world's public toilets, with a website at
worldtoilet.org. (''Org'' is a sound made by many of the world's public
toilets.)  


> 
> 

> 
> This site states that the World Toilet Summit is a
gathering of ''the KEY DECISION MAKERS, KEY OFFICIALS and the MOVERS
AND SHAKERS'' of the international toilet industry. The Beijing host
committee -- which includes (I am still not making any of this up) an
official named ''Stone Wang'' -- states that the summit will feature
workshops on ''hot topics'' in the toilet industry. For example, Mr.
Seok-Nam Gang of the Korea Clean Toilet Association will present
``Toilets As Tourism Attraction.'' 
> 
> 

> 
> Other hot topics include
''Toilets as Marketing Tools'' and ''Generating Revenue Through
Advertisements in Good Toilets.'' There will also be a presentation of
the ''Loo of the Year Awards,'' a tour of ''toilets and related
facilities in Beijing,'' and a ``dinner show.'' 
> 
> 

> 
> I think the
World Toilet Summit is a great idea, because most of the world's public
toilets, in a word, stink. I'm not saying the United States is perfect
in this department. We've made some serious mistakes, the worst being
the introduction of ''low-flow'' toilets, which clog when asked to
handle anything larger than, say, a molecule. 
> 
> 

> 
> Also I am not a
fan of those high-tech public toilets with the automatic sensors that
either (a) become overexcited and flush themselves 37 times before you
even sit down, or (b) lapse into a coma, so that when you're done you
find yourself waving your arms like a lunatic and loudly remarking
''Well, I'm done!'' in an effort to revive your toilet so it will flush
and you can leave, while the people waiting the stall wonder what kind
of sick pervert thing you are doing in there. 
> 
> 
</blockquote>


(I should add that the second World Toilet Forum is [taking place in less than a month](http://www.worldtoilet.org/hp/wto_hp.htm) in Bangkok. Its theme, which I also am not making up, is "Happy Toilet, Healthy Life".)





But back to the main story. 




As state-opponents might expect, a set of black
markets emerged as private industries tried to improve customer satisfaction.
Plumbers would fix the toilets so that they delivered more than the
6-litre amount. Manufacturers claimed 6-litre compliance when their
toilets actually used more. And more blatant than anything, Dave Barry
reported frequently on prohibition-inspired smuggling of 13-litre
Canadian toilets across the border by the Canadian toilet cartel.
Private industry was finding a way around the government mandate.





But then something changed. The City of Toronto, forswearing the full-fledged coercive tactics used by the brutal US regime, decided
instead to offer rebates to people who would install low-flush toilets. 




The
problem of testing raised its ugly head again, and the City of Toronto
got lucky. They contracted Veritec Consulting of Mississauga, where
works modern day hero Bill Gauley (47). When Gauley started testing
toilets he did not use sponges ("I don't know how many people want to
flush sponges" he said), but used mashed potatoes and mashed-up bananas
instead. The result was devastating. He proved that existing toilets
just were not performing as advertised. He extended his work and joined
up with "politics guy" John Koeller of California. They were funded by
a number of Canadian and American municipalities to produce the
definitive work, and in 2003 they pulled the handle on the MaP Report
(Maximum Performance Testing of Popular Toilet Models). 





The industry responded with threats to sue, but once they saw the
evidence they were convinced. And since then, the Star reports, testing
has been paid for by the manufacturers themselves and performance has
improved by leaps and bounds. Not only that, but manufacturers now
proudly stamp "MaP tested and approved" on their products. Now it is
common for toilets to be able to flush not only 250 grams of waste
("the maximum male average" used as a benchmark, which half the toilets
in the 2003 survey failed to flush) but 500 grams, even 1000 grams. And
as Bill Gauley says "if you've ever seen 1,000 grams in a toilet..."





Market sceptics will note that, as Joseph Stiglitz emphasizes in his survey of his own work "Whither Socialism",
the provision of information is a costly exercise that is itself open
to free riding. Information is a public good, and now Veritec's MaP
testing results are available for everyone to read on the Internet. No
individual would find it worth making the effort to do the testing; it
took a large city (and a lot of luck) to get us round that particular
U-bend.





So who is responsible for the happy ending? Is it government in the
form of the City of Toronto? Is it "the industry" who seem to have
bought in to the project? 




The story shows that the state/market dichotomy is false, and that the phrasing of the question is at fault. Posing the
issue as "state versus market" loses touch with reality in the face of
this intricate cross-pollination between municipalities, the US Environmental
Protection Agency (who is likely to develop a labelling system based on
the Veritec tests), Veritec itself (which is a private consultancy) and
quasi-state bodies such as the Canadian Water and Wastewater
Association.




The closer we look, the more dependent on the specifics it
becomes. The story even has an international angle, as today's MaP
tests have moved beyond mashed potato to use cylinders of miso, the
brownish soy-based paste from Japan, encased in LifeStyles brand
condoms so that they can be reused. And much as I'm sceptical of the
benefits of industry-led globalization, I have to admit that the idea
came from private company Toto, makers of the formidable Toto Drake
toilet. It is indeed a tangled web.





Perhaps the message is that, when we look closely enough, economics
falls apart and gives way to sociology and psychology. Perhaps it is that history is, after all, made by individuals, specifically individuals who are prepared to spend hours developing "test specimens" and flushing them down toilets over and over and over again. Perhaps it is
that we need to seek a Buddhist-like middle way between the
Scylla of the market and the Charybdis of the state, but a middle way
that has a more human side to it than the metric driven public-private
partnerships. I don't know. But one thing I do know is that Bill Gauley deserves the thanks of all of us. Maybe someday I'll even get a low-flush toilet myself.


		
