---
author: Tom Slee
categories:
- blog archive
date: 2013-12-10 05:23:19
title: 'This Week in the Sharing Economy: Late Edition'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				In lieu of real content, another set of links.

Picks of the week:



	
  * [Kevin Roose](http://nymag.com/daily/intelligencer/2013/12/uber-might-be-more-valuable-than-facebook.html) speculates about Uber's future

	
  * [Cale Weissman](http://pando.com/2013/12/08/airbnb-says-this-man-does-not-exist-so-i-had-coffee-with-him/) interviews an Airbnb landlord

	
  * [Tomio Geron](http://www.forbes.com/sites/tomiogeron/2013/09/03/startup-homejoy-works-with-cities-to-find-workers/) talks to new Google investees Homejoy.


Peers.org:

	
  * [Grassroots activism behind Airbnb's legal fights](http://tech.fortune.cnn.com/2013/12/09/behind-airbnbs-legal-fights-grassroots-activism/), or [Silicon Valley PR Stunt](http://www.fastcompany.com/3022974/tech-forecast/is-peers-the-sharing-economys-future-or-just-a-great-silicon-valley-pr-stunt)?


Airbnb:

	
  * Their own headquarters are [extravagant](http://www.fastcodesign.com/3022969/design-50/inside-airbnbs-whimsical-new-headquarters), including a [replica of the Dr. Strangelove war room](http://techcrunch.com/2013/12/03/with-a-fresh-200m-in-the-bank-airbnb-built-a-replica-of-the-dr-strangelove-war-room-in-its-office/) as Airbnb joins in the [workspace arms race](http://www.modernluxury.com/san-francisco/story/workspace-arms-race).

	
  * Is the company [returning](http://www.tnooz.com/article/caught-red-handed-airbnb-tripvillas-and-the-curious-case-of-a-rogue-spammer/) to its [spammy roots](http://www.tnooz.com/article/airbnb-admits-rogue-sales-team-used-craigslist-for-stealthy-property-drive/)?

	
  * The [hiring](http://allthingsd.com/20131204/filling-out-its-executive-team-airbnb-hires-operations-and-hr-heads) of executives continues.

	
  * Stories of hosts: [evicted](http://www.nytimes.com/2013/12/03/nyregion/after-renting-out-a-terrace-an-eviction-notice.html), [supportive](http://nypost.com/2013/12/08/how-airbnb-saved-my-house/), [ethically dubious](http://pando.com/2013/12/08/airbnb-says-this-man-does-not-exist-so-i-had-coffee-with-him/).

	
  * More stories? Try [Airbnb confessions](http://www.airbnbconfessions.com/).

	
  * Or [Airbnb marketing in New York](http://www.entrepreneur.com/article/230292).

	
  * [Hotels should be worried](http://skift.com/2013/11/28/why-hotel-brands-should-care-about-airbnbs-disruption/).

	
  * Want to buy a property just to rent out on Airbnb? Try [Mashvisor](http://mashvisor.com/).


Industry:

	
  * Google [invests](http://www.wired.com/business/2013/12/google-homejoy-funding/) in housecleaning as Peers member [Homejoy](https://www.homejoy.com/) hits it big. Homejoy is a Peers partner, but its "professional" employees are, according to [Forbes](http://www.forbes.com/sites/tomiogeron/2013/09/03/startup-homejoy-works-with-cities-to-find-workers/), people who need to show proof of employment to receive government assistance, recruited through municipal employment services.

	
  * DHL launches its [MyWays](https://www.myways.com) delivery service, powered by "people who want to deliver parcels and earn some extra money". Does Peers approve?

	
  * Meanwhile, [Flatclub](http://techcrunch.com/2013/11/27/flatclub-an-airbnb-for-elite-universities-lands-1-5m-investment-to-scale-up) is like Airbnb but only if you went to a fancy university. Sharing without the hoi polloi.

	
  * There is a cynicism to the simplistic claim that "[systems are broken](http://www.inc.com/will-yakowicz/3-reasons-why-the-sharing-economy-is-here-to-stay.html)" and that technology can fix them.

	
  * [Accenture](http://insuranceblog.accenture.com/sharing-economy-explodes-where-do-you-fit-in-part-1-of-3) continues to be interested.

	
  * Lots of actual careers going at [Uber](https://www.uber.com/jobs/list) (not drivers), [Airbnb](https://www.airbnb.ca/jobs) (not B&B owners), [Homejoy](https://www.homejoy.com/job-listings) (not cleaners).


Softball questions from the media:

	
  * [Forbes](http://www.forbes.com/sites/naveenjain/2013/12/03/trust-transparency-and-shared-economy/) asks no difficult questions

	
  * [Wharton Business School](http://knowledge.wharton.upenn.edu/article/sharing-economy-even-mainstream-businesses-want-piece-pie/) cheerleads

	
  * [Inc.com](http://www.inc.com/will-yakowicz/3-reasons-why-the-sharing-economy-is-here-to-stay.html) gushes

	
  * as do [Australians](http://thehoopla.com.au/theres-place-like-strangers-bed/).


Taxis and ridesharing:

	
  * [The Oversharing Economy](http://www.ozy.com/the-oversharing-economy/4126.article)?

	
  * [Lyft and Uber's fleets](http://circuloti.sharedby.co/PD4E9o).

	
  * Uber is making [a lot of money](http://valleywag.gawker.com/leaked-ubers-internal-revenue-and-ride-request-number-1475924182)…

	
  * and might be [more valuable than Facebook](http://nymag.com/daily/intelligencer/2013/12/uber-might-be-more-valuable-than-facebook.html) someday. It certainly

	
  * has [big ambitions](http://www.inc.com/christine-lagorio/uber-tree-delivery-explained.html?cid%3Dreadmore).

	
  * Lyft hires [ex-Netflix and Google](http://venturebeat.com/2013/12/06/lyfts-new-vp-brings-data-science-chops-from-netflix-google-and-space-exclusive/) "data scientist" (not a real job).

	
  * [Blablacar](http://allthingsd.com/20131202/europes-blablacar-has-created-the-purest-version-of-the-sharing-economy-so-far-and-its-working) is more sharing than North American transit companies.

	
  * But [ride sharing](http://www.economist.com/news/britain/21590942-sharing-economy-all-very-wellbut-not-my-car-thanks-single-lane) is still very limited.

	
  * Or you can share [parking](http://urbanland.uli.org/infrastructure-transit/parking-yields-to-the-sharing-economy/).

		
