---
author: Tom Slee
categories:
- blog archive
date: 2012-01-05 22:56:12
title: Ethan Zuckerman's "Cute Cats and the Arab Spring"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

## Table of Contents









  * 1 Dry Tunisian Tinder


  * 2 Cute Cats and Malaysian Opposition


  * 3 Polish lunch rooms


  * 4 Tunisia's Second Act


  * 5 Media Ecology or Network Ecology?













## Cory Doctorow ([*](http://www.guardian.co.uk/technology/blog/2012/jan/03/the-internet-best-dissent-start)) and Jillian York ([*](http://jilliancyork.com/2012/01/03/on-social-media-as-2011-gamechanger/)) were both full of praise for Ethan Zuckerman's Vancouver Human Rights Lecture on _Cute Cats and the Arab Spring_ ([*](http://www.thelaurier.ca/human-rights/human-rights-lecture-2011)), so I listened to the podcast from CBC's Ideas ([*](http://www.cbc.ca/ideas/episodes/2011/12/09/the-vancouver-human-rights-lecture---cute-cats-and-the-arab-spring/)). You can also watch the lecture on YouTube ([*](http://youtu.be/tkDFVz_VL_I)).







Ethan Zuckerman (EZ) has a long and admirable history of involvement in digital activism and a wide knowledge of both technology and social change; the lecture is worth an hour of your time. But (you knew there was a but) in the end I have to disagree with his main thesis.










### 1 Dry Tunisian Tinder







EZ tells us how, after years of sporadic and failed protests in Tunisia, one particular spark in the city of Sidi Bouzid blossomed into the forest fire of revolution. When Mohamed Bouazizi set himself on fire in protest at official interference with his vegetable stall it was a dramatic and desperate act, but not unique: he wasn't the first person to do so even that year. What was different this time?




EZ's argument is that digital social media was different. The early protest was captured on video using a cheap phone and posted to a social networking site where… it did NOT "go viral". Instead the video was picked up by Tunisians _outside_ the country (including EZ's friend Sami ben Gharbia1), who were scanning Tunisian web content for political news and curating it on a site called nawaat.org ([*](http://nawaat.org)).




Al Jazeera got the video from nawaat.org and broadcast it back into Tunisia; Tunisians found out in turn what was going on from Al Jazeera. What's important here, says EZ, is that the new low-cost participatory media is an essential part of a larger media ecosystem that helped to stir up feelings within Tunisia.













### 2 Cute Cats and Malaysian Opposition







In the 1990s EZ ran a web site called Tripod for college/university students. Surprisingly, many people used it not for the Worthy Purposes he and his colleagues had planned, but to share simple and casual things, like pictures of cute cats. Also surprisingly, some of the heaviest use came from Malaysia. Wondering what was going on, Zuckerman got the Malay content translated, only to find that his site was hosting the Malaysian opposition Reformasi movement ([*](http://en.wikipedia.org/wiki/Reformasi_(Malaysia))). Tripod was a space that was difficult for the Malaysian government to censor while being easy to hold discussions.2




And so we reach the "cute cat theory": the ideal places for those who suddenly have important, politically sensitive material they want to share are sites designed for sharing videos and pictures of "cute cats" (Facebook, Twitter, YouTube, Flickr). These sites are easy to use, have a wide reach, and are difficult to censor – if the government shuts them down it annoys a lot of people and alerts them that something interesting is going on. "Cute cats" sites are natural tinder boxes for revolutionary sparks.













### The events EZ recounts are compelling, but a lot of compelling things happen in this strange world, so my first thoughts whenever I hear a story of the Internet producing some unique chain of events is: can I think of a non-Internet example that matches? So here is the lunch-room theory of political dissent (details from [here](http://sunday.niedziela.pl/artykul.php?lg=gb&nr=200409&dz=z_historii&id_art=00004)).







### 3 Polish lunch rooms







On July 8, 1980, in the lunch room at a transport equipment plant in the eastern Polish town of Swidnik, the price of a pork cutlet jumped from 10.20 zloty to 18.10. For Miroslaw Kaczan, this jump was the final straw, and after lunch he switched off the machines he was working on. Others in Department 320 joined him, and other departments in the factory were quick to join. Soon there was a factory-wide stoppage, and it wasn't just about pork cutlets: the demands of the protesters revealed a wealth of pent-up frustration.




News about the strike in Swidnik spread so quickly that within two weeks 50,000 people in the region were on strike. This wave of strikes was resolved on July 25, but the disruption was far from over: three weeks later the strikes at the Gdansk ship yards in northern Poland started, and within a year Solidarnosc had over 9 million members.




In the early days of the strikes, Poles had a hunger for news of the protests, of course, and despite the heavy censorship of official media they found them, through short-wave radio broadcasts from other countries.




So the lunch-room theory is not that different from the cute-cat theory, except that there's no Internet. People gather wherever they gather for their everyday conversations and interactions, and it is in these everyday places that a spark of frustration can catch fire. And once it does catch fire, a combination of broadcast media and a networked public spreads the news quickly.




Perhaps, the Polish example shows, the Internet is not essential for the spark to turn into a fire. Perhaps a digitally networked public is not the only networked public.













### 4 Tunisia's Second Act







Even in Tunisia, politically sensitive material for which there is a high demand has found its way through dangerous pathways to reach a public desperate for news.




In a long piece called Streetbook ([*](http://www.technologyreview.com/web/38379/)) John Pollock interviews two members of an underground Tunisian group called Takriz [_update:_ see Ethan Zuckerman and Jillian York's comments below for reservations about Streetbook]. One of these "Taks" describes how the video that "made the second half of the [Tunisian] revolution" was taken when the regime had shut down the Internet, so "Takriz smuggled a CD of the video over the Algerian border" before forwarding it to Al Jazeera. YouTube may make it it easier and safer to make videos available (at least so long as Google lets it be done anonymously), but when an important video was available, the Internet was not essential to the process of distribution.













### 5 Media Ecology or Network Ecology?







If we are really going to talk about a "media ecology" in the sense EZ means, we need to include all those gathering places–online and offline–which are difficult to shut down precisely because of their everyday, general purpose role. In addition to Facebook and YouTube we need to include factory lunchrooms, mosques and churches, football stadia ([*](http://whimsley.typepad.com/whimsley/2011/09/so-three-cheers-for-evgeny-now-back-to-the-mit-review-articles-some-of-which-display-the-very-internet-centrism-that-moroz.html)), universities, popular music ([*](http://whimsley.typepad.com/whimsley/2011/02/more-egypt-more-facebook.html)), balconies ([*](http://www.juancole.com/2011/08/tv-twitter-facebook-and-the-libyan-revolution.html)), and more.




All these share a number of properties with Cute Cats sites. They are difficult to shut down without annoying large numbers of previously quiescent people, they are difficult to monitor in detail because of the dispersed and varied nature of the interactions that go on, and they are already familiar places for the gathering and sharing of information. EZ says that "we don't take these 'cute cat tools' seriously enough. These tools that anyone can use, that are used 99% of the time for completely banal purposes" but he doesn't take offline everyday institutions for banal sharing seriously enough.




EZ's mistake is the achilles heel of social media advocates. Talk of a "networked society" is justified by comparing today's digitally connected populations to a population of couch potatoes watching prime time TV, but such a comparison overlooks all those other institutions of public networking. Instead of talking of a "media ecology" we should be talking of a "network ecology": the intricate tapestry of multiple networking institutions and practices that makes up a society.




Do digital social media supplement other networking instutions or displace them? There has been a lot of work on this at the individual level, but it's much more difficult to evaluate on a societal level. It is possible that digital social media increase the richness of social networks in a society, but it's also possible (likely?) that digital social media are the kudzu of networks, thriving while they strangle the other components of a rich and diverse network ecology; the best network left standing in an impoverished environment.







### Footnotes







1 Among other things, Sami ben Gharbia is author of a fantastic essay on _The Internet Freedom Fallacy and Arab Digital Activism_ ([*](http://owni.eu/2011/01/15/the-internet-freedom-fallacy-and-the-arab-digital-activism-2/))




2 In fact it may not have been so much that the site was   difficult to censor, as that Malaysian government had decided to   exclude the Internet as a whole from its otherwise-strict censorship   rules ([*](http://techblog.thepcharbor.com/?p=2174)).

























Date: 2012-01-05 22:50:21 EST




Org version 7.6 with Emacs version 23





		
