---
author: Tom Slee
categories:
- blog archive
date: 2006-03-07 22:21:16
title: Wal-Mart Uses Bloggers in PR Campaign
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Link: [Economist's View: Wal-Mart Uses Bloggers in PR Campaign](http://economistsview.typepad.com/economistsview/2006/03/walmart_uses_bl.html).




A couple of months ago Mark Thoma posted a piece on [Wal-Mart's attempt to enter the world of banking](http://economistsview.typepad.com/economistsview/2006/01/always_low_cred.html), which took a fairly even look at both sides of the issue.




The next day he got an e-mail from one Marshall Manson who "does public affairs for Wal-Mart" and today he does us all a service by posting it on his weblog. Here are some of the best bits, but it is worth reading the [whole thing](http://economistsview.typepad.com/economistsview/2006/03/walmart_uses_bl.html).

<blockquote>Mark: 
> 
> 

> 
> I hope you’re well. I just wanted to drop you a line and introduce myself... for my day job - I do online public
affairs for Wal-Mart, working with Mike Krempasky who runs Redstate.org...
> 
> 

> 
> It’s always a challenge when opponents organize to attack corporations. The
companies always seems to have one arm tied behind their backs when they try to
respond, so it’s nice to see folks like you defending them when it’s the right
thing to do [aside: Thoma's piece was not defending them]. 
> 
> 

> 
> If you're interested, I'd like to drop you the occasional update with some
newsworthy info about the company. Let me know.
> 
> 

> 
> And in the meantime, I thought you might be interested in another story that
we're working on today:
> 
> 

> 
> Ever notice the difference between what union leaders do and what union
members want? It's a story almost as old as labor unions themselves -- and
nowhere is it more evident than the union leadership’s campaign against
Wal-Mart...
> 
> 

> 
> Today, Working Families for Wal-Mart released a poll that shows that even as
union leaders continue their anti-Wal-Mart campaign, 96% of union households
shop at Wal-Mart and 63 percent of union households think Wal-Mart is good for
consumers...
> 
> 

> 
> We don't expect to change the minds of the union leadership -- but we'd like
your help. Do you have any other examples of union activities that run directly
counter to their members' wishes or interests?...
> 
> 

> 
> All the best,
> 
> 

> 
> Marshall
> 
> 

> 
> </blockquote>

No comment needed really.


		
