---
author: Tom Slee
categories:
- blog archive
date: 2011-03-04 23:17:04
title: 'Blogs and Bullets: Breaking Down Social Media'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				




## Contents









  * 1 Time to Stop Talking About Social Media? 


  * 2 Giving Up "New Technology" Gerrymandering 


  * 3 Computer Networks and Hierarchies 


  * 4 Inherent Openness 


  * 5 So What Instead? 


  * 6 Footnotes 













## 1. Time to Stop Talking About Social Media?







The debates continue about the role of digital technologies and social media in the Arab/North African uprisings. I was lucky enough to be invited to a workshop last week on [Blogs and Bullets: Social Media and the Struggle for Political Change](http://peacetech.org/) and this post is prompted by some of the fascinating things I heard there.




Time was when we were trapped in what Henry Farrell [describes](http://crookedtimber.org/2011/02/28/the-intellectual-field/#comment-349256) as "a seemingly never-ending debate which seemed to have a lot of very grand claims – The Internet Is Leading To Sliced Freedom and Democracy! Noes! It It is The Autocrat’s Best Friend and so on – combined with a near-total dearth of reliable evidence." But some say such arguments are now obsolete; that we all know the real questions are more complicated than that.1




Still, after the pleas for "nuance" have been made,2 we are often left with a weak determinism, a residual belief in "the internet's special power to connect and liberate" ([Cory Doctorow](http://www.guardian.co.uk/technology/2011/jan/25/net-activism-delusion) in his review of Evgeny Morozov's _Net Delusion_), and a conviction that "The internet is inherently a force for democracy. That will not necessarily always be true, but it is the case today, given its present architecture and the way that people use the network" (Harvard's John Palfrey in [The Economist](http://www.economist.com/debate/days/view/662)). If we are to get beyond "duelling anecdotes" we also have to give up these sweeping claims about the special nature of the Internet.




A team centered around George Washington University [proposed](http://www.usip.org/publications/blogs-and-bullets-new-media-in-contentious-politics) a framework for analyzing how new and social media affect struggles for political change, breaking down the effects into five separate levels, roughly working outward from the individual:






  1. individual transformation 


  2. intergroup relations 


  3. collective action 


  4. regime policies 


  5. external attention 




Maybe it's time to do the same on the other side of the "internet and society" question. Maybe we should stop talking about "information and communication technologies" or "the Internet" or "new and social media" as a single constellation of technologies that have key characteristics in common (distinctively participatory, or distinctively intrusive, for example), and that are sufficiently different from other parts of the world that they need to be talked about separately. The Internet is still pretty new, so we tend to look at it as a definable thing, but digital technologies have now become so multifaceted and so enmeshed in other facets of our lives that such a broad brush obscures more than it reveals.




So here is an exploration of what some of the consequences might be, and a rough sketch of how we might break down "new and social media" into more manageable mouthfuls.













## 2. Giving Up "New Technology" Gerrymandering







"Social media" is often used to mean "media on the Internet", but sometimes people extend the meaning to encompass SMS and MMS messaging even though the networks and protocols are different, as when talking about the 2001 ousting of Philippine president Estrada ([>>](http://www.movements.org/case-study/entry/people-power-ii-in-the-philippines/)). During the Arab uprisings, "social media" has been [stretched](http://www.mobileactive.org/covering-protest-and-revolution-lessons-al-jazeera-innovation-and-mobile-citizen-media) to cover _Al Jazeera_ – a broadcaster – because it draws from YouTube and is commonly accessed over the web in the USA. And Wikileaks is often included in "new media" even though it released its biggest dump of documents to "traditional media". This continual redrawing of the boundaries redefines the category to include whatever is convenient at the time.




Drawing inappropriate boundaries around "new and social media" can also exclude essential elements of a story. A week ago a BBC reporter on the radio described how, within days of seizing control of Benghazi, the Libyan opposition had set up a newspaper and two radio stations alongside a web-based radio station ([web story](http://www.bbc.co.uk/news/world-middle-east-12579451)). An approach that focuses on "new media" would have to include the web radio and exclude the other two initiatives, but to do so would misrepresent the message of a sudden flowering of speech. The Internet is just one of many channels, and activists are using all the media at their disposal. Better, perhaps, to avoid drawing the boundary at all.




Forswearing "new and social media" as a category allows us to include the Benghazi radio stations and newspapers, because they are no longer outside some artificial digital boundary. It frees us up to talk separately and distinctly about blogs, SMS, and Facebook without trying to tie them together in some fake unity: each of these media have distinct architectures, different user bases, different governance models; they serve different purposes, have different interfaces to the rest of the world, and are subject to different commercial pressures.













## 3. Computer Networks and Hierarchies







A second benefit of giving up the term "social media" would be to get rid of outdated analogies between the architecture of the Internet and the nature of the activities that take place on it. We've already seen John Palfrey on that above. Here is a paragraph by Lance Bennett back in 2003:




<blockquote>

> 
> "The implication here is not that the distributed (multi-hub, or polycentric) structure of the Internet somehow causes contemporary activists to organize in remarkably non-hierarchical, broadly distributed, and flexible networks. Digital media applications can take on a variety of forms, from closed and hierarchical, to open and broadly distributed. Preferences for the latter pattern reflect the social, personal, and political contexts in which many global activists define their mutual relationships".3
> 
> 
</blockquote>




That is, anti-hierarchical activists find an accommodating home on the Internet because its network structure maps to their preferred way of organizing themselves.




The shift to Web 2.0 platforms has changed the logical structure of many applications, including the YouTube/Twitter/Facebook trinity,4 to a centralized (single-hub) structure. We continue to speak of networks, but the structure of the human network is no longer mirrored in the structure of the computer communication network. Networks of friends exist only in the cloud of Facebook's servers and SMS messaging has never been carried out on an Internet-style network. There is still much talk of mapping hyperlinks, which form one of the key circulatory systems of the Internet, but the associations of links have been carried over to Facebook friends and to Twitter followers, even though these are beasts of a different sort, living as they do on a single company's private servers.




The commercial Web 2.0 platforms that dominate web traffic are quite different from the archetypal open source software communities (in which copies of the source exist in many places) and even from Wikipedia. They cannot be forked, and we do not get to see the source code for the algorithms that drive them. Using "Wealth of Networks" style logic to discuss how they operate is tempting, but is often inappropriate.




Forswearing "new and social media" would force us to stop making outdated Web 1.0 analogies and inferences about technological structure leading to social structure, even subconciously, and that would be a good thing. If we make ourselves talk about Facebook in particular, rather than social media in general, then it is clear that issues with their terms of service, privacy policies, real-name policies and so on are not details in the big picture of networked technologies but are central to the potential of Facebook as a tool for effecting political change. Given that there are now more active Facebook users ([>>](http://www.facebook.com/press/info.php?statistics)) than there were people on the Internet a decade ago ([World Bank Development Indicators](http://www.google.com/publicdata?ds=wb-wdi&met=it_net_user&dl=en&hl=en&q=number+of+internet+users#met=it_net_user&tdim=true)) this gives those policies their proper level of importance.













## 4. Inherent Openness







A related benefit would be to get rid of arguments that extrapolate from the inherently open nature of the Internet. It is now over a decade since Lessig's _Code and Other Laws of Cyberspace_, and the ever-increasing sophistication and reach of Internet governance in the form of licenses, regulations, trade laws, and other legal or commercial restrictions are making the end-to-end principle increasingly irrelevant.




Blog data and some other data is accessible by spidering or subscribing to suitable collections of sites, but with social media the data is privately held, and outsiders must petition to get access to some or all of it.




Forswearing "new and social media" would force us to drop the empty and misleadingly binary talk of "Internet Freedom" and acknowledge the sliding scale of rights and freedoms that govern individual transactions in both the digital and non-digital realms. Peter Grant and Chris Wood's unfairly neglected but excellent 2005 book [Blockbusters and Trade Wars](http://www.dmpibooks.com/book/blockbusters-and-trade-wars) made it clear that many issues that were supposedly unique to the Internet would be addressed, country by country, by a toolkit of commercial and trade laws, policies and regulations. Their prediction has been proven true over and over again (see also Goldsmith and Wu's [Who Controls the Internet](http://en.wikipedia.org/wiki/Who_Controls_the_Internet%3F)), including Google's [rephrasing](http://static.googleusercontent.com/external_content/untrusted_dlcp/www.google.com/en/us/googleblogs/pdfs/trade_free_flow_of_information.pdf) of Internet censorship as a trade barrier.




Breaking down "social and new media" into smaller categories would also encourage more discussion of the responsibilities of companies wanting to undertake business around the world, such as presenting terms of service in the language of the country of use (Jillian York [points out](http://jilliancyork.com/2011/02/24/would-anonymity-help-activists-on-facebook-a-response-to-luke-allnutt/) that Facebook's terms of service are currently available in only seven languages). Given how important privacy is under authoritarian regimes, terms of service matter.













## 5. So What Instead?







Once we give up on the "tendency" and "on average" arguments around digital technologies, the Internet takes its place as one part of the real world, not a separate entity. Such a picture is increasingly correct, and the process would repeat for social media a pattern that has already played out in other areas. In the early 1990's there was much talk of a "new economics" of the Internet, but in the end it turned out that - with a sharpened focus on increasing returns - traditional economics did explain much of the industrial organization of the digital realm. At the same time there was much talk of how the Internet would break down legal barriers, but such barriers have proven surprisingly resilient, and now many Internet cases are argued within the bounds of existing trade, intellectual property, privacy, and other laws. Disputes that seemed to be specific to the digital realm turn out to be (with the exception of net neutrality) about trade law.




What smaller-scale structures would we talk about, if we give up the grand themes of "social media"? Here is a rough sketch of one division.




Internet-based social network platforms
     Centralized, commercial, privately-owned and advertising-driven, the YouTwitFace world is obviously one of the big stories of the moment. The cost structure of such businesses make them natural, if maybe short-lived, monopolies. To be repetitious, the story is not just one about "networks"; it's also about the terms of service, privacy policies, and advertising policies of the major platform owners. A focus on the Internet has given a tendency to discuss Facebook (the platform)'s role in the current ferment independent of Facebook (the company), but that's unsupportable (much more [here](http://whimsley.typepad.com/whimsley/2011/02/more-egypt-more-facebook.html)). What accommodations have the owners made with the countries in which they operate? 
Mobile Devices
     Messaging on a phone in the street is different from looking at a browser while sitting inside, especially in times of political turmoil. It is quite possible that the phone could supplement political activity while the desktop browser could displace it. Mobility makes a difference, and lumping SMS messaging together with blogs just confuses things. On the other hand, the proprietary nature of the phone network means that device manufacturers and network operators can be leaned on to comply with state-driven security demands (ask [RIM](http://citizenlab.org/tag/blackberry/)). 
Blogs
     Despite Turkey [blocking](http://www.bbc.co.uk/news/technology-12639279) all of blogspot.com, blogging (and especially independent blogging) is architecturally different from social networking platforms. The network of sites is looser, the content more dispersed, the ownership more individual. Blogging plays a different role in political debate and activity to Facebook and other forms of expression. 
Multi-channel outlets
     Al Jazeera, The Guardian, The New York Times: major media operations that have adapted to the web now operate as multi-channel outlets. Does it make sense to situate The Guardian as traditional media and put the Huffington Post in the new media category? I don't see why, but these outlets that can operate in multiple media surely demand different treatment. 
Displaced forms of media
     The winner-take-all structure of digital markets means that in any one niche there are relatively few players compared to the number in the diminishing-returns-based physical world. There's no need for separate special-topic reference publications when Wikipedia can be expanded indefinitely, and there are fewer bookshops online than there are offline. The major cultural outlets for many countries are increasingly based on the west coast of the USA as Hollywood is joined by Apple, Amazon, and Netflix. We are losing a diversity of institutions in the move to a digital terrain, and it is worth investigating what impact that loss has. 
Circumvention tools
     Tools used specifically by activists while carrying out illegal or politically sensitive acts fall into a separate category. Do tools like Tor and the failed Haystack tell us much about social networking and Facebook? I don't think so.
      

Obviously there are many other divisions possible. My main point is: if there is one shift that forswearing "social media" would produce, it would be to talk less about networks and self-organization and to talk more about institutions (commercial, state, and global), and this seems to me a realistic shift given how the digital world has changed over the last few years.  











## 6. Footnotes







1 Caveat: these sweeping claims have not gone away. They are living happily and prosperously in business schools, in popular books, in op-ed pages, and in the halls of Davos. For sophisticated social scientists the utopians are like an embarrassingly loud friend – you know his [sic] faults but you think he's harmless – but to an outside observer you are both members of the same scary mob hanging around at the corner. Sweeping, deterministic ideas still need to be countered, and countered in kind. But for the moment I'll ignore that part of the real world.
















2 You are confusing, he/she is a fence-sitter, I am nuanced.




3 W. Lance Bennett, _Communicating Global Activism: Strengths and Vulnerabilities of Networked Politics_, in Wim van de Donk, Brian D. Loader, Paul G. Nixon, and Dieter Rucht, eds. _Cyberprotest: New Media, Citizens and Social Movements_ London: Routledge, 2003. ([>>](http://depts.washington.edu/gcp/pdf/communicatingglobalactivism.pdf))




4 Can we just use [YouTwitFace](http://www.youtwitface.com/) as a shorthand? Please?













HTML generated by org-mode 7.4 in emacs 23





		
