---
author: Tom Slee
categories:
- blog archive
date: 2008-01-26 14:32:23
title: Barbie slinks back to the confines of feminist-criticism symposia
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Bad news for Yochai Benkler. In his celebration of the Internet, [The Wealth of Networks](http://www.benkler.org), Benkler writes this (p 277):




<blockquote>

> 
> A nine-year-old girl searching Google for Barbie will quite quickly find links to AdiosBarbie.com, to the Barbie Liberation Organization (BLO), and to other, similarly critical sites interspersed among those dedicated to selling and playing with the doll. The contested nature of the doll becomes publicly and everywhere apparent, liberated from the confines of feminist-criticism symposia and undergraduate courses. This simple Web search represents both of the core contributions of the networked information economy. First, from the perspective of the searching girl, it represents a new transparency of cultural symbols. Second, from the perspective of the participants in AdiosBarbie or the BLO, the girl's use of their site completes their own quest to participate in making the cultural meaning of Barbie. The networked information environment provides an outlet for contrary expression and a medium for shaking what we accept as cultural baseline assumptions. Its radically decentralized production modes provide greater freedom to participate effectively in defining the cultural symbols of our day. These characteristics make the networked environment attractive from the perspectives of both personal freedom of expression and an engaged and self-aware political discourse.
> 
> 
</blockquote>




Got all that? Benkler actually lists the first page of Google results for a search on "barbie":




<blockquote>

> 
> barbie.com  
Barbie Collecter  
AdiosBarbie.com  
Barbie Bazaar  
If You Were a Barbie, Which Messed Up Version would you be?  
Visible Barbie project (macabre images...)  
Barbie: The Image of us all (1995 undergraduate paper)  
Andigraph.free.fre (Barbie and Ken sex animation)  
Suicide bomber Barbie  
Barbies (dressed and painted as countercultural images)
> 
> 
</blockquote>




Well, that was a couple of years ago. Here's what [googling barbie](http://www.google.ca/search?q=barbie) on January 26, 2008 gets you:




<blockquote>

> 
> Barbie.com - Activities and Games for Girls Online! (together with eight other links to My Scene, Evertythingggirl, Polly Pocket, Kellyclub, and so on).   
Barbie.co.uk - Activities and Games for Girls Online!  
Barbie - Wikipedia, the free encyclopedia  
Barbie Collector - (The official Mattel site for Barbie Collector)  
Barbie Girls  
Mattel - Our Toys - Barbie  
The Distorted Barbie  
YouTube - barbie girl - aqua  
Barbie - Barbie Dress up - Fashion for Barbie  
Barbie.ca
> 
> 
</blockquote>




The distorted barbie site does still makes the list, and the Aqua parody video is still there, but this search is basically owned by Mattel. Clicking the top link takes you to a pink page with "Think Pink" written in the middle of it, and the majority of the sites feature pink prominently.




No more defining the cultural symbols of our day for you, nine-year-old girl! Quit the self-aware political discourse and get back to dressing that doll in gender-appropriate colours (as selected for you by Mattel).




**Update:** [2009 results](http://whimsley.typepad.com/whimsley/2009/07/googling-barbie-again.html).


		
