---
author: Tom Slee
categories:
- blog archive
date: 2014-01-23 01:39:10
tags:
- airbnb
title: Airbnb Stories
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Telling stories is a powerful, personal way to communicate. That's why Airbnb collects stories from its hosts and puts them [on its web site](https://www.airbnb.ca/stories) and uses them liberally in its publicity.


<blockquote>When the economic crash hit, [Tama](https://www.airbnb.ca/stories/new-york/one-way-forward)’s livelihood as a painter and real estate broker was threatened. A serious health condition was only increasing her expenses, with prescription costs at times topping $1000 per month. Receiving guests not only introduced her to new friends—it allowed her to eat, pay her bills, and stay in her home.</blockquote>


But Chris's story is not on the Airbnb web site.


<blockquote>In San Francisco, [Chris](http://www.sfchronicle.com/bayarea/article/Airbnb-profits-prompted-S-F-eviction-ex-tenant-5164242.php?t=d6c1c46efd3c100abe#/0) lost his home so that his landlord could make more money by renting out apartments on Airbnb. Chris says: "They forced me out of a home I loved. It was incredibly difficult to find a place, especially because I have a really old dog. I ended up paying over double what I was paying there." Chris is now suing his landlord and his attorney says: "Airbnb is contributing to the displacement of long-term tenants in San Francisco... It has made it so easy to go into the short-term rental business; it is ubiquitous."</blockquote>


Most stories on the Airbnb web site are about people renting out the homes in which they live.


<blockquote>[Lisa and Byron](https://www.airbnb.ca/stories/new-york/full-house) are both artists, and have been their whole lives. They first met at an art residence in 1986, were married in 1993, and their family home in a Park Slope brownstone is where they raised their three kids.

This past fall, when their son headed off to university, their downstairs sat empty, so when tuition bills started rolling in, Lisa realized Airbnb was a great solution to help pay for them.</blockquote>


But not all Airbnb hosts rent the house in which they live.


<blockquote>In New York, [Chris](http://www.wnyc.org/story/two-true-stories-airbnb-wars/) lives in Brooklyn but rents out two bedrooms in a separate apartment he leases in Manhattan, at $100 per night.</blockquote>


Sounds like a nice little earner. Some Airbnb hosts are generous, and are on the Airbnb web site.


<blockquote>When New York City was hit by one of the worst hurricanes in history, [Shell](https://www.airbnb.ca/stories/new-york/sandys-impact), a long time host on Airbnb, realized that the loss for some people was devastating. As the waters rose and people had to evacuate their homes, many of them couldn’t return for days, if at all. Shell decided to go online and list her space for free for those who were in need.</blockquote>




Airbnb is quick to claim Shell as part of its "community". It has't been so quick to claim everyone. Not Ken's tenant, for example.





<blockquote>Also in New York, [Ken](http://www.wnyc.org/story/two-true-stories-airbnb-wars/) owns a few buildings in Nolita. He runs a nonprofit that teaches people how to ride bicycles. Now he's hiring private investigators to see what his tenants are doing. Ken doesn't like it: “It’s so not me. It’s like how did I become that guy?” But Apartment 3 had become a kind of hotel, charging $250 a night and he suspects the tenant made half a million dollars before he evicted her. He says of Airbnb that  “They see how lucrative her business was... And they refuse to take it down. So they’re not good guys."</blockquote>


A lot of the Airbnb stories are about friendliness and about connections between people.


<blockquote>[Jonathan](https://www.airbnb.com/stories/los-angeles/the-art-of-receiving) is a single dad raising three kids in Echo Park, Los Angeles. For years he worked 60-80 hour weeks at a job that was unfulfilling, scrambled to care for his three children, and had let his own ceramics studio fall by the wayside. When his schedule was cut back at work, Jonathan decided to list an extra room in his home on Airbnb. His first guest gave him such a positive review that more lined up, and he was soon renting out a second room as well.

Hosting has become not only an extra source of income, it’s also allowed him to be more available to his own family.</blockquote>


But Jerry's story isn't on the Airbnb web site.


<blockquote>

> 
> [Jerry](http://www.nola.com/politics/index.ssf/2013/03/new_orleans_residents_slam_ill.html) lives in New Orleans. He says that "In the French Quarter it is increasingly difficult to know your neighbors because they change every weekend."
> 
> 
</blockquote>




I have resisted telling stories when writing about the sharing economy, even though almost every media report leads with one and even though I've been asked to use them. I'll continue to avoid them, in general, even though it probably limits the audience I'll reach. Why? Because selective storytelling is manipulative and I don't want to be a manipulator and I don't want my readers to be manipulated. (Trust me.)




If you read a heart-warming story promoted by someone with a vested interest, you're being sold a bill of goods. It really is as simple as that. The people in the story may be genuine; the story may be true, and they may be lovely people doing wonderful things. But there are millions of stories in every city, and the magic is in the selection (and the photography). By themselves, stories tell us nothing about the bigger picture, and it's occasionally worth remembering that.

		
