---
author: Tom Slee
categories:
- blog archive
date: 2011-09-18 16:54:00
title: 'Internet-Centrism 2 (of 3):  Streetbook'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

So [three cheers](http://whimsley.typepad.com/whimsley/2011/09/internet-centrism-1-of-3-evgeny-morozov-and-the-net-delusion-.html) for Evgeny. Now back to the _MIT Technology Review_, and in particularJohn Pollock's [Streetbook](http://www.technologyreview.com/web/38379/), an extended set of interviews with two  secretive Tunisian digital activists who go under the pseudonyms  "Foetus" and "Waterman". The article describes how "their organization, Takriz, performed a  remarkable and largely unknown role" in the uprisings.




* * *




F—b— is such an important technology of mass coordination among  young people that it was shut down in Egypt and other North African  countries as the uprisings erupted in January 2011. F—b— was a  technology that allowed many-to-many communication of political ideas,  even under the censorious eye of repressive states; it provided a  space where urban youth could gather to display their collective  strength and build a clear identity separate from the state; it had  fostered trans-national networks across the whole of North Africa;  it lent itself to leaderless mass organization; and it produced  some of the key organizing groups of the Tahrir Square  protests. F—b— is, of course, Football.




The _Ultras_ are groups of hard-core soccer fans who carry out dramatic  displays of their fanaticism (fireworks, huge choreographed artworks,  inventive songs) and who compete amongst each other to out-invent and  out-display the fans of opposing teams. And, yes, fight with police  from time to time.  John Dorsey {[blog](http://mideastsoccer.blogspot.com)} has followed Ultra culture  closely. Here he is from Egypt in January 2011: {[link](http://bleacherreport.com/articles/585682-soccer-fans-play-key-role-in-egyptian-protests)}




<blockquote>

> 
> With Egypt entering its second day of unprecedented anti-government  protests, soccer fans constitute a well-organized and feared pillar of  the marshalling grassroots coalition determined to ensure that  President Hosni Mubarak suffers the same fate as Tunisian President  Zine El Abidine Ben Ali, who was toppled earlier this month by mass  demonstrations.
> 
> 
</blockquote>




Alaa Abd El Fattah, a prominent Egyptian blogger {[Wikipedia article](http://en.wikipedia.org/wiki/Alaa_Abd_El-Fatah)},  was widely quoted as saying "The ultras–the football fan  associations–have played a more significant role than any political  group on the ground at this moment." {[link](http://warincontext.org/2011/01/29/inside-the-egyptian-revolution/)}




Here is Debbie Randle of BBC's "Newsbeat" {[link](http://www.bbc.co.uk/newsbeat/12914113)}.




<blockquote>

> 
> When Newsbeat spoke to some of the ultras, they told us large numbers  of them fought on the front line at the protests.
> 
> 

> 
> They said they passed on their knowledge to other demonstrators and  protected people and their homes.
> 
> 

> 
> Abdullah, who's a member of the Zamalek White Knight Ultras, told  Newsbeat they also helped to organise the protests.
> 
> 

> 
> He said: "We had many meetings to discuss the revolution before it  started. We discussed that we must play an important part for Egypt,  we must support Egypt."
> 
> 

> 
> The official line from the Ultras is that they didn't take part as a  group but Newsbeat has been assured this isn't the case.
> 
> 

> 
> An ultra from a rival group, thought to have around 15,000 members,  said they also played a role.
> 
> 

> 
> They worked alongside the White Knights, usually sworn enemies, to  protest for their country.
> 
> 
</blockquote>




A member of Egypt's NDP was reported on January 26 2011 as  acknowledging the importance of the Ultras: "what we saw on the  streets yesterday are not just Muslim Brotherhood members or  sympathisers but Egyptians at large; those are the Egyptians that you  would see supporting the football national team– and their show of  frustration was genuine and it had to be accommodated." {[link](http://english.ahram.org.eg/~/NewsContent/1/64/4862/Egypt/Politics-/NDP-member-Antiparty-protests-strengthens-reform-c.aspx)}




And _Sports Illustrated_, on January 31 {[link](http://sportsillustrated.cnn.com/2011/writers/dave_zirin/01/31/egypt.soccer/index.html)}:




<blockquote>

> 
> Over the decades that have marked the tenure of Egypt's "President for  Life" Hosni Mubarak, there has been one consistent nexus for anger,  organization, and practical experience in the ancient art of street  fighting: the country's soccer clubs. Over the past week, the most  organized, militant fan clubs, also known as the "ultras," have put  those years of experience to ample use.
> 
> 
</blockquote>




Why soccer? Let's return to James Dorsey as quoted in _Sports Illustrated_: "The involvement of organized soccer fans in Egypt's  anti-government protests constitutes every Arab government's worst  nightmare. Soccer, alongside Islam, offers a rare platform in the  Middle East, a region populated by authoritarian regimes that control  all public spaces, for the venting of pent-up anger and frustration."  Does this seem familiar?




So it looks like the Ultras, which [some describe](http://www.thedailynewsegypt.com/football/the-ultras-white-knights-football-hooliganism-or-social-movement.html) as a social movement,  played a self-conscious role in the Egyptian uprising, using the  uncensored public space of the football terraces to organize  themselves in impressive ways. See (via @techsoc's Twitter feed) [this](http://twitpic.com/6m75j6) remarkable protest last week over the continued imprisonment of Ultra  members following recent protests. The words above the pictures of the  imprisoned apparently read "Free Fans (Ultras)".




The Ultras do use digital technologies to organize themselves, but the  primary means is clearly physical. See these videos for a few  examples: the Stretford End has nothing on these characters.













As we read _Streetbook_, however, we get a different impression of the  Ultras.  The narrative that the article conveys is one in which the  digital activists of Takriz played the key role while the Ultras  themselves are secondary.




_Streetbook_ highlights Takriz's myriad connections, but presents its  "main audience" as "alienated street youth: the lifeblood, often  spilled, of the rebellion in North Africa". Though the article has  many fascinating things to say about the contacts between Takriz and the  street groups, it does not support the presentation of Takriz as the  primary actor in these contacts, and there is a recurrent classism in  the description of how the groups relate.




So Pollock describes how the Taks (members of Takriz), including his  interviewees "Foetus" and "Waterman", had the inspiration of "turning  the spirit (of soccer fans) to political ends", and developing a web  forum for Ultras from different teams. Then "when the revolution  began, the Ultras would come out to play a very different game. They  were transformed into a quick-reaction force of bloody-minded  rioters." The narrative is that the digital activists shaped the  events, transforming soccer hooligans into a "bloody-minded" political  fighting force. But is that what happened? Did initiatives such as the  web forum or the Takriz efforts to direct the Ultras have any impact?  There is no evidence for this in the article. And there is no voice  here from the Ultras themselves. Do they not have anything to say  beyond the wielding of sticks? It is remarkable that in all the  coverage of the Ultras listed above, there is only one piece that mentions a name. Is digital presence required to have a voice in the debate  about what happened in North Africa in 2011? It's not surprising that  the importance of digital tools is exaggerated.




In the same spirit _Streetbook_ describes how, when the Tunisian regime  fell, Egyptian digital activist Hassan Mostafa "reached out to some of  the hardened criminals, 'murderers and drug dealers', he had met while  imprisoned for his Khaled Said protest: their skills would prove  useful in stealing police riot helmets and guns. Through them, Mostafa  recruited an army of toughs from the poorest areas." In Tunisia,  Takriz leaders "use street culture, slang, and obscenities to fire up  street youth". Again, the narrative has the digital activists as the  brains, and the "toughs from the poorest areas" with no digital  connections are reduced to a tool to be "fired up", with no agency of  their own.




The over-emphasis on digital tools is everywhere in _Streetbook_. Most  obvious is the claim that after visiting (overland, the old way) a  group in Serbia, an activist returned with "a book about peaceful  tactics and a computer game called A Force More Powerful, which lets  people play with scenarios for regime change. Taking advantage of the  game's Creative Commons license, April 6 members wrote an Egyptian  version."  It's not like in previous times activists haven't shared  resources and built on each others' work because they didn't have the  right clauses in their license agreements. The hacker group Anonymous  gets a mention for targeting Tunisian government websites with DDOS  "attacks", but was Anonymous's action a significant step in the  escalation of protest?  I doubt it. A Parisian-based activist "wrote a  script, using semantic search techniques based on keywords… to  measure how much time it took for posts to result in responses like  comments". There is nothing wrong with such work, but it is clearly  secondary – at best – to the main events, but in the  Internet-centric "digital revolution" narrative, it gets a speaking  part.




Yet throughout the interview, there are nuggets that reveal an  alternative plot between the lines. Despite the focus on YouTube as a  mechanism for sharing videos, Foetus describes how the video that  "made the second half of the [Tunisian] revolution" was taken when the  regime had shut down the Internet, so "according to a Tak who asked to  remain anonymous, Takriz smuggled a CD of the video over the Algerian  border" before forwarding it to Al Jazeera. What I see here is that,  while YouTube has made it easier and safer to make videos available  (at least so long as Google lets it be done anonymously), when an  important video was available, the Internet was not essential to the  process of distribution. On December 30 in Tunisia, "Lawyers gathered  around the country to protest the government and were attacked and  beaten", and a week later they all went on strike, followed by the  teachers. Lawyers and teachers have their own pre-existing networks,  of course, and probably used them to organize – at least there is no  mention of a lawyers' Facebook page. So while Pollock diligently  tracks each use of FourSquare, each request for help over Facebook,  each use of emails with attachments, and each fake Twitter account, he  skips quickly over the role of leaflets and flyers, meetings in  mosques, university campus organizing, television, and  [balcony-to-balcony](http://www.juancole.com/2011/08/tv-twitter-facebook-and-the-libyan-revolution.html) messaging.




Those who are convinced of the progressive potential of digital  technologies sometimes accuse sceptics of exaggeration. No one, of  course, thinks that Facebook _caused_ the Arab Spring uprisings. But the  Internet-centric narrative is not so much wrong in any one particular,  as inherently distorted in the overall weight it gives to digital  tools. It lends itself to narratives in which technological tools play  a central role, in which the direction of influence is "from social  networks to manifestation in the real world", as _Streetbook_ quotes  Samir Garbaya. The nuggets embedded in _Streetbook_ tend to show that,  more often than not, digital technologies are one option among several  when it comes to the tasks activists face, and that [information transmission](http://www.youtube.com/watch?v=E_mTwm5m8DM) is commonly [not the bottleneck](http://whimsley.typepad.com/whimsley/2010/01/digital-activism-if-information-is-not-the-problem-information-is-not-the-solution.html). There is no doubt that  Facebook played a significant role in the Egyptian uprising, and that  some key videos uploaded to YouTube helped to raise awareness of  persecution, but alternatives have existed and do exist, and it is a  mistake to pass quickly over these alternatives.




Next post - which I hope I'll get done in a day or two - is something  more constructive. If Internet-centrism is a problem, how do we debate  the role of digital technologies in politics? Henry Farrell has an  extensive survey of the topic and some fine insights [here](http://crookedtimber.org/2011/09/14/the-effects-of-the-internet-on-politics/), and I'll  just try to add a few postscripts of my own.


		
