---
author: Tom Slee
categories:
- blog archive
date: 2005-12-15 22:48:39
title: Globe Editorial Again
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Letter to the [Globe and Mail](http://www.globeandmail.com):




Dear Editor,




Regarding your editorial "...and anti-WTO folly".




You tell poor countries to follow Hong Kong and China in "abandoning isolation and central planning and embracing trade and outside investment". But many Latin American countries did just as you ask in the 1990's and did not see the benefits you promise. For every Hong Kong there is a Honduras -- or more than one in fact -- a country that has embraced outside investment for decades and is still miserably poor. 




And while China's growth started in the 1970's, it only joined the WTO in 2001, its economy was and is still highly protected, and its financial markets were largely off-limits to outsiders until the turn of the century. Not exactly a case of prosperity by globalization.




You tell poor countries to "join the international trading system", but most countries that have escaped poverty used practices forbidden under the rules of the WTO. The globalization poster-children of Japan and Korea, and others including the USA, all engaged in capital controls, selective import restrictions, and knock-off industries that would now be called violations of intellectual property rights.




If you want to convince me of globalization's "wealth-creating power" you'll have to do better than that.


		
