---
author: Tom Slee
categories:
- blog archive
date: 2009-01-05 18:41:53
title: "Mr. Amazon's Bookshop: The Appeal of Amazon"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[The table of contents for Mr. Amazon's Bookshop is [here](http://whimsley.typepad.com/whimsley/2008/12/mr-amazons-bookshop.html)]

After my [previous visit](http://whimsley.typepad.com/whimsley/2008/12/mr-amazons-bookshop-first-visits.html) to Mr. Amazon's Bookshop I was furious the whole way home, and wrote the man off as a charletan charlatan. But in a couple of days the book I had ordered (_Special Topics in Calamity Physics_, if you recall) did arrive with the post. Over the next few days I read it, and thoroughly enjoyed it despite the pretensions of the author (I do have a keen eye for pretentiousness), so my feelings for Mr. Amazon's bookshop were mollified a little.

  
Mr. Amazon's shop was frustrating, but over time I discovered that it also had an undeniable appeal. If I was shopping for a particular book and couldn't find it, I soon got used to dropping in at the odd little store and asking Mr. Amazon if he had it. And no matter what I asked, whether it was Nigella Lawson's [How to Eat](http://www.amazon.com/How-Eat-Pleasures-Principles-Good/dp/0471257508) or Kieran Healy's [Last Best Gifts](http://www.amazon.com/Last-Best-Gifts-Altruism-Market/dp/0226322378), he would just reach down behind his desk and come up with the book, holding it up for me to look at. I became accustomed to the no-touch rule. I would have preferred to leaf through the book before buying it, but I'd look at the blurbs on the back, and sometimes he would open up the book so I could see a few pages inside. Then he would take my money, although not before giving one of his recommendations. Usually I would ignore these, but every now and again I would take him up on one. Who could resist a modest suggestion that  "You know sir, some people who bought _Last Best Gifts_ also bought Catherine Waldby's [Tissue Economies: Blood, Organs and Cell Lines in Late Capitalism](http://www.amazon.com/Tissue-Economies-Capitalism-Science-Cultural/dp/0822337703). Would you be interested in that too?" I said yes and he reached down beneath his desk and showed it to me, before putting all the books away again and taking my money.

  


It is true that I could have ordered these books from any of the other stores in the village, but the ones I ordered from Mr. Amazon did usually arrive quicker and cheaper than the others and I got used to relying on him for those books I needed. I still used the other bookstores if I wanted to browse around but went to Amazon's if I knew what I wanted.

  


One day I walked into the shop and noticed that there were a few books lying open on the desk in front of Mr. Amazon. I walked over to them and teased him: "Getting sloppy are we Amazon? Shouldn't these be put away below your desk there?" "Not at all sir" he answered. "I saw you coming and took the liberty of putting out a few books you might like. Would you care to look at these?" And would you know it, I ended up buying one.

  


I think that visit, almost a year after my first encounter, was when I started to look to Mr. Amazon's store first, rather than using it as a last resort. I'd walk in, go straight up to the desk (oddly enough there was never anyone else in the shop) and see what selection he had put out for me. Usually they weren't any good, but I could always say "Amazon, old chap, do you happen to have ..." and he would inevitably reach down behind his desk and produce the very book, usually murmuring something like "Some people who bought this also bought..." and mentioning another book or two.  
  
That was almost two years ago, and I've been a regular customer of Mr. Amazon since then. And I'm far from alone. Mr. Amazon has gained a lot of other fans in the village, especially among the young folk. In fact, they seem to see him as more than just a convenient place to buy books; he's become something of a hero to them. Somehow Mr. Amazon, neatly pressed shirts and all, has gained a reputation as a bit of a rebel, and we all know there's nothing like a streak of the maverick to make youngsters turn their heads.  
  
The first time I noticed this admiration was last spring, as the snow melted to leave the familiar spring-time odour of dog turds on every corner. I was out in the park putting out my usual batch of arsenic-laced sausages to dissuade the villagers from letting their curs roam free, when I heard the scamps on the way home from their schoolhouse, boisterously boasting about what they were going to do when they grew up. "No crappy old publisher is going to stand between my novel and its audience!" I heard one young Jane Austen exclaim, as she kicked her chum affectionately in the groin, "Mr. Amazon's going to tell the whole world about it." "Yeah. Don't you just hate publishers? Damn those gatekeepers. But elitist institutions won't hold the new generation back!" countered her pal as he picked himself up off the ground. "Right!" said a third, "Mass media is so over. Who needs it when Mr. Amazon is on your side?" I smiled at their japes, watching as they ripped the sleeves off the jacket of a hapless and chubby twelve-year-old, smirking at him: "Look at you now, you're just like Random House. 'armless!"   
  
Ah, such idealism! It took me right back to being pelted with stones by that Blemings lad as I scrambled across the rocks under the weir on the way home from school. Happy days!  
  
Their enthusiasm was winning. Could it be, I wondered, that Mr. Amazon was going to open a new world of literature ahead of us? That the balance of power had tilted and that the author, the primary creative force, who I must admit has been so long unfairly neglected by the establishment publishing houses in the big cities of the world, finally had the upper hand? Could those authors (and don't forget the charming authoresses!), with the tyranny of the old world left behind, usher in a new world of variety and diversity? Oh, I did so hope it might be so!

  


But if Mr. Amazon was the key to a new culture, how did he manage it? Try as I might, I could not guess how the little man could always reach to find just the book I asked for. And how had he, a rather prim and proper middle-aged man with none of the attractive whiff of dissipation I possess, gained the attention and even affection of the Scruffiest Generation? I decided that, in fairness to those village shopkeepers I had frequented for years, I should put my hopes of a brave new world on hold until I knew what was going on...


		
