---
author: Tom Slee
categories:
- blog archive
date: 2006-10-10 22:51:14
title: 'Book News: Speaking Engagements'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Maybe it's time to say something about the book again. I've been invited to give a few talks recently - some have already happened, and some coming soon. Thanks to those who have invited me - the ones so far have been very rewarding (for me at least). 




Car Free Day was an event sponsored by [WPIRG](http://www.wpirg.org/wpirg/) in September. They invited me to speak at the outdoor event in Victoria Park and also at the University. Speaking outside with a small audience is difficult - the surrounding noise makes it feel as if you are shouting at people sitting a few feet from you. If you weren't there to hear me, I don't think you missed anything. The University event was better, with about 20 people there and some good discussion afterwards. Most interesting was a comment about an intriguing high-tech public bicycle system in Lyon named [Velo'v](http://www.velov.grandlyon.com/), which seems to be a big success according to a Guardian article reprinted [here](http://www.peopleandplanet.net/pdoc.php?id=2516). 




Kitchener NDP recently hosted [Peggy Nash](http://www.peggynash.ca/), a new MP for Parkdale- High Park in Toronto. I was very impressed. She spoke for 45 minutes with no notes on a wide variety of topics, from a recent fact-finding visit to Lebanon to the ins and outs of Parliamentary committees and was obviously smart and very well informed. I was asked to present her with a copy of my book as a thank you for the visit, which was a privilege. 




After the meeting I met two philosophy profs from the University of Waterloo. Dave DeVidi is using No One Makes You... in a Decision Theory course, and Tim Kenyon may be using it next year in a Critical Thinking course.




In a week and a half I'll be speaking as part of a panel at an event at York University named _Social Justice: From Rhetoric to Action _put on by the [Centre for Social Justice](http://www.socialjustice.org/). The programme is still in a draft form - I'll post more when it gets closer. It's a challenge to condense a piece of the book into an edible-sized chunk for talks, but I think I'm slowly getting better at it.




Finally, I'm an invited speaker next month in an Engineering and Society course that is being run at McMaster University as part of the Peace Studies program. It is called "War and Natural Resources: The Case of Oil" ****which is being run by Graeme MacQueen and Jack Santa Barbara. I'm sure the course is a fascinating one - I just hope I can hold people's interest.




One trouble with writing a book that covers quite a wide range of topics is that you don't get to give the same talk twice -- transit, social justice, and warfare. But the best way to learn more about something is to tell others about it, so this has been very rewarding. 


		
