---
author: Tom Slee
categories:
- blog archive
date: 2006-10-29 19:42:28
title: Quantum Computing Revisited
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

So, following on from my recent [gripe](http://whimsley.typepad.com/whimsley/2006/10/quantum_computi.html) about quantum computing, it turns out that there are others who have thought along similar lines, and actually done the work of going beyond generalized grumbles.




Specifically, Scott Aaronson at Shtetl-Optimized [posts](http://www.scottaaronson.com/blog/2006/10/mistake-of-week-x-works-on-paper-but.html) about a paper by M. I. Dyakonov called [Is Fault-Tolerant Quantum Computation Really Possible?](http://www.arxiv.org/abs/quant-ph/0610117) Dyakonov goes on about the theory of error-correction in (hypothetical) quantum computers, which I know nothing of, and in particular criticizes the "threshold theorem", but he also makes some more elementary points that I did, so here are a few excerpts from Mr/Ms Dyakonov's paper just to show I'm not completely out to lunch.

<blockquote>The enormous literature devoted to [fault-tolerant quantum computation]... is purely mathematical. It is mostly produced by computer scientists with a limited understanding of physics and a somewhat restricted perception of quantum mechanics as nothing more than unitary transformations in Hilbert space plus "entanglement".
> 
> 

> 
> [on decoherence] While the relaxation of two-level systems was thoroughly studied during a large part of the 20th century, and is quite well understood, in the quantum computing literature there is a strong tendency to make it look as an obscure quantum phenomenon.
> 
> </blockquote>

Elsewhere, Dyakonov takes aim at the assumptions of ideal behaviour that permeate discussions of the feasibility of quantum computing, and to my mind does a pretty good job of bringing a little reality into the discussion. Click the Shtetl-Optimized link above for some more discussion of the paper.


		
