---
author: Tom Slee
categories:
- blog archive
date: 2009-02-02 20:14:21
title: "Mr. Amazon's Bookshop: Down with Gatekeepers!"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[This is the seventh instalment of _Mr. Amazon's Bookshop_. A list of all instalments is [here](http://whimsley.typepad.com/whimsley/2008/12/mr-amazons-bookshop.html); the previous instalment is [here](http://whimsley.typepad.com/whimsley/2009/01/mr-amazons-bookshop-the-differ.html).]

Edmund, the gardener's son, has the look of a runt about him: he is undersized, has a perpetually dripping nose and a habit of scratching his backside. He is looked down on by the Whimsley village children, which is an achievement in itself: he positively broadcasts stupidity. On the other hand, his is obedient and hardworking, which are important qualities in the servant classes, and has a strong pair of arms so I decided to let him assist me with my investigation.

I dragged Edmund out to the stables on a warm July morning, ready to set the differ to work and send more questions to Mr. Amazon, and with a fresh supply of pencils to record the results in my trusty notebook. I set the young halfwit to start the bellows and he soon worked up a healthy pressure. I turned the dials and tugged the pulleys to set my question, and was about to pull the master lever one more time, when Edmund shouted and pointed up at the stable roof. I followed the line of the simpleton's finger, and saw the topmost reaches of my differ perspiring and shivering, as if with fever. The pistons wailed, the cylinders grated, and then the edifice ground to a juddering halt with an earsplitting thud. The differ was obviously damaged and my investigations were going nowhere soon. I kicked Edmund out of the stables in frustration.

For the next month I searched for parts, scoured manuals, and consulted other differ enthusiasts in an attempt to fix my machine. And while I waited for the postman to bring the replies to my questions I did what I could to keep myself occupied. I even cleaned some of the abandoned rooms in Whimsley Hall, myself. The drawing room I restored to, if not exactly its former stateliness, then at least habitability. The worst of the cobwebs and nests were evicted, and with a solution of vinegar and water I attacked the windows so vigorously that light penetrated the room for the first time in years. Thanks to the previous gloom the velvet drapery and the rich colours of the upholstery were unfaded, but the profuse spattering of stains were too ingrained to be removed. I did not mind. They were part, you might say, of the fabric of the place, and each with its own memory.

When I was too tired to work on Whimsley Hall I walked to the village and back, pacing the bounds of the old estate. With head thrust forward, deep in thought, and with a perpetual frown on my face I was doubtless a forbidding <strike>site </strike>sight, and I was avoided by most villagers.

It was on one of these walks that I was bumped into, literally, by one of the youngsters I had seen around the village - none other than the pugilistic Jane Austen you may recall [from a couple of months earlier](http://whimsley.typepad.com/whimsley/2009/01/mr-amazons-bookshop-the-appeal-of-amazon.html). I was walking alongside the river, and seized her by the ear as she attempted to barge past on the narrow pathway.

"Ow! Leggo! Piss off guv'nor!" she bawled, in that endearing manner I have come to know so well in the past few months.

"Not before you tell me your name, young harridan!"

"It's Kylie, innit" she grunted.

"How likely. I'm not convinced at all. You know who I am?"

"Yeah, you're the bloke what lives at the Hall, innit?"

"Seventh Earl of Whimsley, but I will let is pass. You can call me Mr. Whimsley and I'll call you Kylie for now. Now listen, I have some questions for you. I need answers and I'm prepared to pay. Shall we say a hot chocolate at Mr. Horton's? That should pay for fifteen minutes of your time."

"Whatever. Just let go of me bloody ear! And stop writin' me dialogue in that patronizing phonetic bullshit way. It's not like you speak the way it's written."

"Deal. Let's go."

I put her down, and we made our way to Mr. Horton's Coffee Establishment where, once I convinced the proprietor Kylie was not about to steal the contents of the till, we sat and drank a mug of hot chocolate. Kylie was a small and wiry child of about fifteen, with a perpetually sullen expression. I told her that I had overheard her yelling about Mr. Amazon's Bookshop and about her literary ambitions and asked to hear more.

"Look, Mr. Whimsley, I like to write. Always have done, ever since looking after my brothers and sisters when they was real young. I made up stories to keep them from ripping the doors off their hinges. Anything to keep the little buggers quiet. So it became a habit, and I reckon I'm pretty good at it. But there's no way any of those hi-faluting publishers are going to pay attention to me. I have no education worth speaking of, no contacts to call on..."

"And almost certainly no talent. But point taken, go on."

"Well, it's like, Mr. Amazon is an odd fish, but I can get the books I like at his shop so I go there sometimes and then one day he told me that if I had written anything I could just give it to him and he'd sell it, just like he sells the other books. Isn't that amazing?"

"It certainly sounds attractive. And have you taken him up on his generous offer?"

"You bet! I mean, at first I was pretty suspicious and figured he just wanted to rob me of my just rewards, but I had a word with Mr. Anderson - he's a bloke that lives down our street - and he told me it's OK. He said Mr. Amazon's way better than those other bookshops for me because they're all elitist institutions and Mr. Amazon's on my side. He said something else really weird too..." (here she looked around and lowered her voice) "He told me that Mr. Amazon's got a long tail. And that made me think I've only ever seen him from the front, and I can't look over the desk. So maybe it's true! What do you think?"

"Oh I doubt that", was my first reaction, "but come to think of it I, too, see him only from the front. And he does have a certain reptilian quality."

"Anyway", Kylie carried on, "I finished my book a few weeks ago. It's called The Adventures of Wazzock. It's about a boy who finds a polished blue stone in a mountain chain near his home. He discovers that his stone is really a dragon egg when it hatches suddenly in the night. Wazzock gives his dragon the name Saphira, which he learns from the village storyteller. After the dragon hatches the King sends his servants after Wazzock and Saphira, in an effort to capture or kill them. Wazzock and Saphira flee their hometown and embark on a number of adventures involving swordplay, magic, friendship, betrayal, and death."

"I'm sure they do. Very good, very good. And how is it going?"

"It's great. It's only been a few weeks, but I've already sold five copies."

"Really! And who to?"

"Well, there's my brother and my mum, and then my friend Sharon, and then two boys in my class. Of course, I told them I'd beat them up if they didn't buy it. That's called marketing."

"And is he selling your book at any of his other shops, or just here in Whimsley?"

"He's selling it...", here her voice dropped to a hushed whisper, "...all over the world. Anywhere you go, you could walk into a Mr. Amazon and ask for The Adventures of Wazzock and he'll sell it to you. Right then and there. Isn't that amaaziing??!! It's just me and my audience. No gatekeepers! It's just like Mr. Anderson said. I'm alread
y working on my next book, so I'm ready once Wazzock goes viral."

"Admirable. Admirable. Now that's enough young Kylie. I may have need of you again. I have obviously underestimated both you and Mr. Amazon. You have given me much to think on. Off you go."

She grabbed my half-eaten doughnut and waltzed out of the door, looking far too pleased with herself. I pondered, is this how it works? Is this the new world? Are "real" bookshops a thing of the past? Perhaps - the idea filled me with dread - despite all my effort at staying up to date, I am not quite as au courant as I like to think. Maybe - notwithstanding my natural flair for the common touch - I am a touch elitist at heart? And could it be that - however maverick I may be in my soul - there is a waft of conservatism that has settled over me in my middle age?

My personal doubts about Mr. Amazon carried over into these broader concerns that I, as a member of the gentry, have such a duty to worry over. Does Mr. Amazon really give any book a chance at success, as young Kylie claims? Is he really an agent in the quest for a more democratic, more varied and diverse culture? Or is he, perhaps, a gatekeeper just as effective as those publishing houses the local hooligans scorn? And is he hiding a long tail behind that desk of his?

Disturbing thoughts. I obviously needed to find out more. My investigation of Amazon seemed to be growing more urgent at every turn, but until the replacement parts for my differ arrived I was stalled. My impatience was, I am sure, almost as intense as yours, waiting for the next episode of my story... 


		
