---
author: Tom Slee
categories:
- blog archive
date: 2006-12-30 19:07:56
title: Second Least Surprising Story of the Week
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Did anyone think that meat from cloned animals would make you sick? I didn't think so. 




The headlines following from the US FDA announcement ([FDA Issues Draft Documents on the Safety of Animal Clones](http://www.fda.gov/bbs/topics/NEWS/2006/NEW01541.html)) are misleading. The headlines are all of the form "Cloned animals deemed safe to eat" (Nature) or "US regulator declares food from cloned animals is safe to eat" (International Herald Tribune), but that's not the story here.




For the record, here is the sentence from the [report](http://www.fda.gov/bbs/topics/NEWS/2006/NEW01541.html).




<blockquote>meat and milk from clones of adult cattle, pigs and goats, and their offspring, are as safe to eat as food from conventionally bred animals.
> 
> </blockquote>

But safety of the meat is not the issue. The real story is towards the end of the announcement:

<blockquote>In the draft guidance, FDA does not recommend any special measures relating
to human food use of offspring of clones of any species.
> 
> </blockquote>

That is, cloned food needs no labels. 




The issue is that cloned animals (like genetically-modified crops) introduce many potential changes to the agricultural industry - changes in the balance of power within the industry, the spread of health conditions associated with high-producing animals, and others I haven't thought of. So given people's natural scepticism about what (if any) benefits there are to this move, many people will not want to eat milk or meat from cloned animals. Whether our suspicions are right or wrong, that should be our choice. 




So the real headline here is, "FDA takes first step towards allowing **unlabelled **food from cloned animals". The labelling is the story. And like with GMO plants, the major companies involved will want to have their meat and eat it - they will want to avoid labelling because cloned animals are no different, but you can bet your shirt that they will be looking for ways to patent techniques associated with cloning.


		
