---
author: Tom Slee
categories:
- blog archive
date: 2005-12-26 22:07:05
title: India creates database to halt theft of lore
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

A fine initiative reported in today's 
[Globe and Mail](http://www.theglobeandmail.com/servlet/ArticleNews/TPStory/LAC/20051226/IBLORE26/TPBusiness/?query=page%3DB5%20and%20sortdate%3D20051226)

<blockquote>For thousands of years, Indian villagers have used an extract from seeds of the neem tree as an insecticide. So when a U.S. company patented a process for producing the substance in 1994, India reacted with outrage. 
> 
> 

> 
> After spending millions of dollars in legal fees to successfully overturn the patent, India's government is now creating a 30-million-page database of traditional knowledge to fend off entrepreneurs trying to patent the country's ancient lore. 
> 
> 

> 
> India is not alone in worrying about "bio-prospectors" profiting from the genetic resources of its plant life with no benefit to its people. 
> 
> 

> 
> It joined with China, Brazil and nine other countries a few years ago to begin pushing for international protections.
> 
> 

> 
> The database project already has caught the interest of others. A South African team recently visited and a Mongolian mission is coming in January, said V.K. Gupta, chairman of India's National Institute for Science Communication and Information Resources.

> 
> 

> 
> The database, called the Traditional Knowledge Data Library (TKDL), will make information available to patent offices around the world to ensure that traditional remedies are not presented as new discoveries.
> 
> 

> 
> "If societies have been using it for centuries why should it be patented?" said Shiv Basant, a senior official at the Health Ministry's Department of Ayurveda, Yoga, Unani, Siddha and Homeopathy, India's traditional health and medical disciplines.
> 
> 

> 
> The government has also successfully challenged patents on the use of the spice turmeric to heal wounds and rashes and a patent on a rice strain derived from India's famed Basmati rice. 
> 
> 

> 
> But that is a tiny fraction of the problem. 
> 
> 

> 
> A 2003 study by Mr. Gupta's institute estimated that about 7,000 patents worldwide are based on indigenous Indian knowledge, far too many for India to challenge in expensive legal fights. 
> 
> 

> 
> Officials hope the database will head off future battles. 
> 
> 

> 
> "If we have all the data in TKDL, we will not have to spend all those millions of dollars," said Ajay Dua of the Commerce Ministry's Department of Industrial Policy and Promotion. 
> 
> 

> 
> Currently it is difficult for overseas patent office researchers to prove purported innovations are really based on old lore because, while the information is widely published in India, it is often in ancient languages such as Sanskrit or modern regional languages like Tamil. 
> 
> 

> 
> "We decided we have to break the language and access barrier," Mr. Gupta said. 
> 
> 

> 
> He convened a group of 150 experts in traditional medicine, scientists, doctors, patent lawyers and computer programmers to put together the database of traditional knowledge. 
> 
> 

> 
> Instead of laboriously translating the manuscripts, the scholars structured the texts into classifications widely used by patent examiners. 
> 
> 

> 
> The texts are then entered in the database, where specially developed software translates them into Hindi, English, German, French, Japanese and Spanish. 
> 
> 

> 
> "We created knowledge conversion software that converts local names of diseases and plants into modern names," Mr. Gupta said. 
> 
> 

> 
> More than 1,500 yoga poses have been catalogued, too. 
> 
> 

> 
> That's because yoga poses also have been patented, often by Indians who are living abroad, Mr. Basant said. 
> 
> 

> 
> A patent researcher can search the database using key words or phrases. 
> 
> 

> 
> So if the plant aloe vera is entered, the traditional term Kumari will come up with a list of its known medicinal uses. 
> 
> 

> 
> More than 10 million pages already have been loaded into the system and 20 million more will be available by the end of 2006, Mr. Gupta said. 
> 
> 

> 
> Several international patent offices have applied for access to the database and it will be made available to them as soon as the group finishes establishing technological and legal safeguards to prevent the knowledge from being wrongly exploited, he said.
> 
> </blockquote>




Vandana Shiva has written a lot about Biopiracy, and this story is a next chapter to some things in her book of the same name. I have not followed the Indian and Pakistani governments' activities in challenging patents on long-known non-innovations, such as [Neem fungicides](http://www.twnside.org.sg/title/revoked.htm), [Basmati rice](http://www.twnside.org.sg/title/basmati.htm) and [Nap Hal wheat](http://www.navdanya.org/news/04feb16.htm). The use of the patent system as a way of enclosing the intellectual commons (as Shiva describes it) illustrates just how distinct the notions of competitive markets and capitalist markets (which are commonly conflated) really are. 


		
