---
author: Tom Slee
categories:
- blog archive
date: 2006-04-16 10:04:00
title: An arrogant convert
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Via Mark Thoma, an unbelievably arrogant article by Patrick Moore, a founder of Greenpeace. He is now in favour of nuclear power. I don't mind that, even though I don't agree with him --- changing your mind is not a bad thing. But something about his article really pisses me off, and it's the conceit of the man. Look at these excerpts:

<blockquote>In the early 1970s when I helped found Greenpeace, I believed that
nuclear energy was synonymous with nuclear holocaust, as did most of my
compatriots. ... Thirty years on, my views have changed, and the rest of the
environmental movement needs to update its views, too...
> 
> </blockquote>

Here we go. Because he has changed his mind, Moore is now absolutely certain that everyone else needs to change their mind too. There is no modesty here; no asking the question: if I was wrong then, why should anyone listen to me now? no asking the question: if I was wrong then, might I be wrong now? No. Mr. Moore is as certain in his position now as he was then, insisting that everyone else needs to listen to him. Sorry. No can do.

<blockquote>I
don't want to underestimate the very real dangers of nuclear technology in the
hands of rogue states, we cannot simply ban every technology that is dangerous....
> 
> </blockquote>




Some years ago I took part in hearings on nuclear power in Ontario where thoughtful people from both sides took part. I was asked, by a member of the Ontario nuclear industry, exactly this question. I answered that it was a non-question. The statement is true of course, but that doesn't mean you adopt every technology despite its dangers. You look at each case and make a decision. In fact, most of the arguments that Moore makes now in favour of nuclear energy are exactly the same as the ones being made then. For example, regarding Three Mile Island:

<blockquote>What nobody noticed at the time, though, was that Three Mile Island was in
fact a success story: The concrete containment structure did just what it was
designed to do -- prevent radiation from escaping ... And although the reactor
itself was crippled, there was no injury or death... 
> 
> </blockquote>

See what I mean? Just because Patrick Moore didn't notice that Three Mile Island was a success story, he assumes no one else did either. Well, people did, on both sides of the debate. And some of us who opposed nuclear power then knew that it was kind of a success story, and wrestled with that, and decided that we still opposed nuclear power. But Moore apparently wasn't among those wrestling with that problem, because he doesn't listen to other people, he just tells them what to think,

<blockquote>And I am not alone among seasoned environmental
activists in changing my mind on this subject. On occasion, such opinions have been met with excommunicationfrom the
anti-nuclear priesthood...
> 
> </blockquote>

This is Mr. Moore trying to maintain for himself the position of rebel-with-a-cause. Not only was he a rebel then (an outspoken, independent-minded activist) but he's a rebel now, against the people he was then a part of. But now he calls Friends of the Earth "the anti-nuclear priesthood" as if they are some kind of power centre. Give him a year or two and he'll be railing against political correctness.




<blockquote>There are signs of a new willingness to listen, though, even among the
staunchest anti-nuclear campaigners. ... nuclear is, by elimination, the
only viable substitute for coal. It's that simple.
> 
> </blockquote>

Oh come on. Here is that certainty again, that arrogant "if I can't think of alternatives, then no one else can either" black-and-white thinking. He is so certain of his own opinions that they are now obvious. Until he changes his mind, and then his new position is obvious too.




Let me be absolutely clear. It's not the mind changing I object to. When it comes to that, I am firmly of the John Maynard Keynes school of thought (in response to a question about what he does when he gets new information, he answered "When the facts change, I change my mind. What do you do, sir?") And it's not the support for nuclear power that I object to, even though I don't agree. Many thoughtful people are in favour of nuclear power. It's the self-importance of his simple-minded thought that gets my blood pressure up.




And happy Easter to you too.




Link: [Economist's View: Global Warming and Nuclear Power](http://economistsview.typepad.com/economistsview/2006/04/global_warming_.html).


		
