---
author: Tom Slee
categories:
- blog archive
date: 2011-05-02 19:23:19
title: '"The most appalling spying machine that has ever been invented"'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Julian Assange, in [an interview with RT](http://rt.com/news/wikileaks-revelations-assange-interview/), is not shy about his opinion of Facebook.




<blockquote>

> 
> **RT: **_And social networking, what role, do you think, sites like Facebook and Twitter, have played in the revolutions in the Middle East? How easy, would you say, is it to manipulate media like that? _
> 
> 

> 
> **JA: **Facebook in particular is the most appalling spying machine that has ever been invented. Here we have the world’s most comprehensive database about people, their relationships, their names, their addresses, their locations and the communications with each other, their relatives, all sitting within the United States, all accessible to US intelligence. Facebook, Google, Yahoo – all these major US organizations have built-in interfaces for US intelligence. It’s not a matter of serving a subpoena. They have an interface that they have developed for US intelligence to use.
> 
> 

> 
> Now, is it the case that Facebook is actually run by US intelligence? No, it’s not like that. It’s simply that US intelligence is able to bring to bear legal and political pressure on them. And it’s costly for them to hand out records one by one, so they have automated the process. Everyone should understand that when they add their friends to Facebook, they are doing free work for United States intelligence agencies in building this database for them.
> 
> 
</blockquote>





		
