---
author: Tom Slee
categories:
- blog archive
date: 2017-01-21 05:18:00
title: On Orange Tyrants
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				A few months ago I read a couple of historical novels by Philippa Gregory, set in the reign of Henry VIII (The King’s Curse, and The Taming of the Queen). I thought I was reading for entertainment, but they have been the best guide to what to expect from Trump that I’ve come across.

Henry was a second son, not brought up to be king, and he was spoiled. He could not bear that anyone be better than him, at riding, at archery, at jousting, whatever.

So what Gregory’s books convey very well is how _not_ to deal with a privileged and powerful narcissistic orange bully with no attention span. Henry could flatter and be generous, and the objects of his flattery would think they had influence. But when Henry’s needs or wants changed, or when anything went badly, these people were suddenly cast aside. His wives are the obvious examples, but counsellors and ambassadors and nobles too.

All of a sudden, they would hear that Henry was disappointed in them. That after years of friendship and loyalty, Henry was dismayed to find that they had let him down (because nothing, ever, was Henry's fault). And then they would simply be frozen out, unable to reach him, refused entrance to court. And maybe they would lose their head. Thomas Wolsey, Thomas Cromwell: both had their moment, and then didn't. (Maybe don't be called "Thomas" or "Anne" either)

So when I see people saying that Trump understands them (the Canadian government, the technology leaders who paid court), that — in the words of the tech leaders — they will set him straight if he goes off-course, I think: _you have no idea how this works_. Of course he and his crew will flatter you, tell you how brilliant you are, how much he admires you. Until he doesn’t. Until he decides that you have disappointed him. And then you will hear about it second hand, or maybe through Twitter. You’re out, and the axe will fall, and you’re not so special after all.

Those “realist” commentators who say they can manage Trump (with a bit of flattery here, a few wise words there) need to read about Henry VIII to see how that story ends.

If that takes too long, they should at least follow [@KngHnryVIII](https://twitter.com/KngHnryVIII) on Twitter, who set it out in August [here](http://www.huffingtonpost.com/entry/8-reasons-donald-trump-is-the-henry-viii-of-americas_us_57c47031e4b0c936aaba59b8). From which:


<blockquote>Let me put it this way, you know that feeling of anxiety and fearful remorse that can steal over you in the darkest hours of the night? I don’t have that. Neither does Trump.</blockquote>


**Update:** David Golumbia points out that Sean Spicer's infamous first press conference may be an example. Told to deliver a stinging rebuke, he follows his master's bidding. When the rebuke causes problems, Trump hangs him out to dry, saying maybe he went too far. That's what you get for riding an orange tiger.		
