---
author: Tom Slee
categories:
- blog archive
date: 2006-05-07 22:21:17
title: Lots of cars => fond of cars?
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I don't have much to stay about this - I just need a place to keep a quote.




Here is an paragraph from Saturday's (May 6) Kitchener-Waterloo Record, which ran a survey about the most important issues that Waterloo Region will have to deal with in the next five years. The big ones are public goods: transport, healthcare, population growth, and clean water. There is a significant fall-off after that to taxes, almagamation, infrastructure, education, and housing.




Anyway, here it is:

<blockquote>Statistics from Waterloo regional police suggest residents here are fond of their cars. Since 1993, the region's population has increased about 15 per cent while the number of cars registered in the region jumped about 34 percent. Registered vehicles in the region totalled 228,000 in 1993. Today, that figure is 390,000.
> 
> </blockquote>

You do see this logic all the time. It uses an implicit revealed preference argument: we have bought more cars, so we must like them (be fond of them). It's at the root of a lot of the claims about consumer sovereignty and the economy. But it's wrong, of course. Buying a car (or not) is a reaction to the transport system you live in, not an expression of some kind of fondness, and a small change that helps to shape that transport system.  



		
