---
author: Tom Slee
categories:
- blog archive
date: 2010-11-28 09:22:08
title: Spot the Difference
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::


Match the caption to the video (thanks to [Chris Weagel](http://human-dog.tumblr.com/) for the middle one). For the full effect play the videos simultaneously.

**Captions**

"[PM, Toronto mayor say 'thugs' to blame for attacks](http://www.cbc.ca/canada/story/2010/06/26/g20-saturday-protests.html)"

"[a bright day for retailers](http://www.bostonherald.com/business/general/view.bg?articleid=1299294&srvc=rss)"

"[shameful, dangerous and counterproductive](http://www.bbc.co.uk/news/uk-politics-11745570)"

"[The violence prompted police to place Canada's largest city in a virtual state of lockdown](http://news.aol.ca/ca/article/g20-protest-turns-violent-in-toronto/19532314)"

"[the American consumer has adapted to the economic climate over the last couple of years and is possibly spending more wisely as the holiday season begins](http://www.bbc.co.uk/news/business-11857218)"

"[When it comes to Black Friday shopping, Hudgens said she most likes “the shopping (and) the savings but mostly the tradition.](http://www.examiner-enterprise.com/articles/2010/11/27/news/news080.txt)"

"[[Black Friday really serves as a bright reminder that in a capitalist society competition and incentives are key to making the most of a voluntary transaction](http://www.ocregister.com/opinion/black-277620-friday-shopping.html)"

**Videos**
