---
author: Tom Slee
categories:
- blog archive
date: 2013-10-01 17:44:08
title: RelayRides, GigaOm
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Nice to see [Mathew Ingram](http://gigaom.com/2013/10/01/trust-reputation-and-regulation-can-the-new-sharing-economy-find-a-way-to-scale/) at GigaOm give a thoughtful precis and response to my [Reputation Systems](http://tomslee.net/2013/09/some-obvious-things-about-internet-reputation-systems.html) post.

Also, it's timely to see today's news that sharing economy company RelayRides has confirmed my predictions in its move away from its original market of hourly rentals and towards longer-term rentals, described in [Wired](http://www.wired.com/business/2013/10/relayrides-drops-hourly-rentals/), [Forbes](http://www.forbes.com/sites/tomiogeron/2013/10/01/relayrides-focuses-on-longer-travel-rentals-as-sharing-economy-focuses-on-travel/) and elsewhere. Hourly rentals may appeal to "sharing" but monthly rentals is just commerce. It's becoming more like a regular car rental company and less like a car-sharing company.

Why? Because of the demand for growth that faces VC funded companies, and according to [Crunchbase](http://www.crunchbase.com/company/relayrides) RelayRides has been funded to the tune of $30m by investors including Google Ventures, General Motors, and others. Let's hope that the boom and bust mentality behind these companies don't have a bad effect on local initiatives like [Community Carshare](http://communitycarshare.ca/) near me, which don't have ambitions to disrupt the world but focus on doing something useful and actually cooperative.		
