---
author: Tom Slee
categories:
- blog archive
date: 2008-04-12 21:43:12
title: Taxi to the Dark Side/Talking to the Taliban
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is not what I usually write about here, as I have little to add to the discussion over the war in Afghanistan, but two things have made a big impression on me in the last couple of weeks.  
  
The first is the series of interviews with 42 members of the Taliban organized by Graeme Smith of the _Globe and Mail_ ([link](http://www.theglobeandmail.com/talkingtothetaliban)). In particular, there is this:

<blockquote>Almost a third of respondents claimed that at least one family member had died in aerial bombings in recent years. Many also described themselves as fighting to defend Afghan villagers from air strikes by foreign troops.
> 
> </blockquote>

...and this, which I guess many people better informed than I already know:

<blockquote>Aerial bombings and civilian deaths have both increased: The United Nations estimates more than 1,500 civilians were killed last year, as compared with the 900 to 1,000 civilian deaths counted by two studies of the previous year. An analysis of the first nine months of 2007 found the number of air strikes was already 50 per cent higher than the total for 2006.
> 
> 

> 
> Civilian bombings emerged as a major theme of the war last year. President Hamid Karzai shed tears in public as he spoke about civilian deaths. In June, a coalition of Afghan aid agencies published a controversial report suggesting that the rate of civilian casualties had doubled from the previous year, and that international forces were starting to rival the Taliban as the greatest source of civilian deaths.
> 
> </blockquote>

The second was watching [Taxi to the Dark Side](http://www.imdb.com/title/tt0854678/), the Oscar-winning documentary about torture in Afghanistan, Iraq, Guantanamo, and elsewhere. It made very clear that most detainees (83,000 at the time the film was made) were not detained by the allied forces, many have committed no crime whatsoever, and that torture of the detainees is common. The effect that the torture and murder of Dilawar, the taxi driver of the title, has on his village is not followed up but is not difficult to imagine.




Aerial bombing and torture are not at the centre of the debate over NATO's role in Afghanistan, but they should be. The debate would then not be about how we can best help the people of Afghanistan; it would be about how we can stop damaging them and driving them to desperate measures. As long as these tactics are part of the military operation in Afghanistan then the longer NATO is there, the more enemies it will create.




_Taxi to the Dark Side_, which includes many interviews with soldiers involved in torture, shows how the ethics of groups can differ from the intentions of the people that make up those groups. Even an army composed largely of well-meaning individuals can act in fundamentally immoral ways. Just as NATO soldiers cannot tell a Taliban veteran from a villager who abhors the Taliban, so Afghan citizens cannot tell the difference between a soldier who will treat them decently and one who will arrest them for nothing and condemn them to torture. In both cases the safe assumption to make is the cautious one. So all Afghan citizens will be suspicious of and hostile to NATO soldiers and NATO soldiers will be suspicious of and hostile to Afghan citizens whether or not that hostility is deserved by the individuals. And each such hostile encounter justifies the hostility of the other side. While NATO is there it is not easy to see how things can improve.




Within Canada, we need to address the question of what kind of war we are part of. The assumption to date is that we are fighting a decent war. As long as aerial bombing and torture are part of the military operation then this is not a decent war.


		
