---
author: Tom Slee
categories:
- blog archive
date: 2009-01-25 08:39:37
title: Motor Neuron Disease/ALS
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

You can react to illness in a couple  of ways.

Take me. I have had a really crappy cold for the last couple of days and so I didn't cook last night, didn't walk the dog this morning, and I've been basically slobbing around and doing nothing.

Or take my friend Tim Lester. Diagnosed with Motor Neuron Disease (also called ALS or Lou Gehrig's Disease) a couple of years ago, he still plays in a band, has done a large part of a walk across the [Speyside Way](http://www.speysideway.org/), promotes MND awareness and continues to raise his kids. His son Alex (who, I happen to know, is prepared to wear a Borat thong in front of a high-school audience) narrates this video on Tim's life with MND; it's a short (2 mins 30s), clear, unsentimental, and helpful description of what challenges the disease brings with it.

  


Maybe I shouldn't let a cold slow me down so much.

  





		
