---
author: Tom Slee
categories:
- blog archive
date: 2005-11-18 21:17:11
title: Rebel Sell Snarky-Tees
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I imagine I'll have a lot to say about [Andrew Potter's Rebel Sell blog](http://www.rebelsell.com/blog). The site, and [the book](http://www.rebelsell.com/), are insightful and yet frustrating. Potter and co-author Joseph Heath acknowledge, like too many on the left don't like to acknowledge, that the collective action problem is a real one, and make a lot from it in their book. They also emphasize the uncomfortable truth that "cultural rebellion, of the type epitomized by Adbusters magazine, is not a threat to the system -- it _is_ the system". 




Their argument is useful because it makes it clear that rebel chic is not the same as real change. The point, I thought when I read the book, is that if we want a just society then we need to focus on actions that lead to real change rather than engaging in individualistic pseudo-protest.




But then they go and do something like [Snarky-tees](http://www.cafepress.com/rebelsell). At this point it starts to look as if they (or at least he -- the blog is Andrew Potter's but not Joseph Heath's) are more interested in ironically mocking the culturally rebellious (and making a buck in the process) than in promoting real change. It looks like despite their protestations to the contrary (see page 342 of the paperback edition), when it comes to it, they don't have a problem with driving the modern consumer economy, they just want to drive it a little further. 


		
