---
author: Tom Slee
categories:
- blog archive
date: 2014-01-24 19:44:48
title: Sharing economy and informal economy
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Earlier this month, New York University business professor Arun Sundararajan [presented](http://smallbusiness.house.gov/uploadedfiles/1-15-2014_revised_sundararajan_testimony.pdf) testimony to the Committee on Small Business of the US House of Representatives. He wants "peer-to-peer" business to be reflected in economic statistics and employment surveys.

When should the sharing economy be treated as part of the real economy, and when should it not? Are you confused? Here is a short guide for the perplexed.

_When the sharing economy should be excluded from the formal economy:_



	
  * taxation

	
  * regulation

	
  * job protection for service providers

	
  * platform-owner liability when things go wrong

	
  * limits on platform-owner freedom of action regarding their "community"

	
  * when a site's design enables racial discrimination on the part of its users.


_When the sharing economy should be part of the formal economy with all its protections and benefits:_



	
  * recognition of positive economic contribution

	
  * legitimacy of platform-owner revenue

	
  * terms of service that protect the platform-owner

	
  * IPOs

	
  * when a site's design makes racial discrimination on the part of its users less likely


I hope that is clear.		
