---
author: Tom Slee
categories:
- blog archive
date: 2007-07-04 11:23:21
title: Happy Shoes III - A few references
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Thanks for the comments, both here and on [Brad DeLong's blog](http://delong.typepad.com/sdj/2007/07/tom-slee-happy-.html). 




The message of the [previous post ](http://whimsley.typepad.com/whimsley/2007/07/happy-shoes-ii.html)was supposed to be that, if left to only isolated consumers and companies,
the prospects for ethical consumption are bleak. As
several people pointed out, in the real world things do look a little
brighter. But all the useful action in credence goods - whether it is the kosher certification market
or fair trade labelling organizations or trade restrictions - happens
because of groups other than the usual competitive
market actors.  






Also, if there is nothing new under the sun there is definitely nothing new on this blog. I'm just trying to work out some things about consumer activism and labour standards "in my own words" after finishing reading [Can Labor Standards Improve Under Globalization?](http://bookstore.petersoninstitute.org/book-store/338.html)
by Kimberly Ann Elliott and Richard B. Freeman which, despite being a
candidate for the most boring title in the history of publishing, is a
fine and practical survey of everything from the role of activist
groups to governmental and transnational institutions like the WTO and
the ILO. I highly recommend it.




For anyone interested, here is a selection of other writing on and around this subject that is available to those of us who don't have everyday university access to journals (most are PDF links):





[The
evolution of credence goods in customer markets: exchanging `pigs in
pokes](http://www.business.aau.dk/evolution/esapapers/esa98/Credence.pdf)', Esben Sloth Andersen and Kristian Philipsen Draft, revised January 10, 1998 




[Monitoring Labor Standards in a Macroeconomic Context](http://www.uvm.edu/~wgibson/research/monitor.pdf ) Bill Gibson, April 2003




[LABOUR AND ENVIRONMENTAL STANDARDS: the “Lemons Problem” in
International Trade Policy](http://econ.ucalgary.ca/fac-files/jdg/standards.pdf) EUGENE BEAULIEU AND JAMES GAISFORD, May
2001




[Is There Consumer Demand for Improved Labor Standards? Evidence from Field Experiments in Social Labeling](http://weber.ucsd.edu/~jlbroz/Courses/PS245/syllabus/hiscox_SocialLabeling.pdf), Michael J. Hiscox and Nicholas F. B. Smyth, 2006?




Timothy J Feddersen, Thomas W Gilligan (2001) [Saints and Markets:
Activists and the Supply of Credence Goods](http://www.blackwell-synergy.com/doi/abs/10.1111/j.1430-9134.2001.00149.x?journalCode=jems ) Journal of Economics &
Management Strategy 10 (1), 149–171. 




[Fair Trade as an Approach to Managing Globalization](http://www.princeton.edu/~smeunier/Hiscox_Fair%20Trade%20and%20Globalization.pdf ) Michael J. Hiscox, conference on Europe and the Management of Globalization, Princeton University, February 23, 2007.




[Signaling Social Responsibility](http://www.ksg.harvard.edu/m-rcbg/CSRI/publications/workingpaper_14_johnston.pdf), Jason Scott Johnston, Robert G. Fuller, Jr., November 2005, Working Paper No. 14, A Working Paper of the: Corporate Social Responsibility Initiative




[Corporate Social Irresponsibility](http://www.democracyjournal.org/article.php?ID=6497&PHPSESSID=795d847ac12b1f19211524ae3d5f4a4d) by Aaron Chatterji and Siona Listokin, Democracy, Winter 2007 (via [Economist's View](http://economistsview.typepad.com/economistsview/2006/12/overcoming_corp.html)) 




[PREFERENCES FOR PROCESSES: THE PROCESS/PRODUCT DISTINCTION AND THE
REGULATION OF CONSUMER CHOICE](http://www.harvardlawreview.org/issues/118/Dec04/KysarFTX.pdf), Harvard Law Review Douglas A. Kysar,
December 2004




Next post - back to some [actual content](http://whimsley.typepad.com/whimsley/2007/07/happy-shoes-iv-.html).


		
