---
author: Tom Slee
categories:
- blog archive
date: 2013-11-11 03:38:17
title: Airbnb Business in New York, Revisited
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Since I did a [post](http://tomslee.net/2013/10/notes-on-airbnbs-new-york-business.html) about Airbnb's business in New York, Airbnb has published [its own study](http://blog.airbnb.com/airbnbs-economic-impact-nyc-community/) and so there has been some follow-up interest in my numbers, [here](http://techpresident.com/news/24513/analysis-examines-how-much-illegal-money-airbnb-makes-new-york), [here](http://nextcity.org/sharedcity/entry/the-numbers-airbnb-hasnt-released), and [here](http://www.cnbc.com/id/101176262).

The data and the conclusions cannot be conclusive because they are a sample (though a big one) of limited publicly-available information. I'm happy to be corrected, but Airbnb would have to release some real numbers to do so, instead of silly 300 word "studies".

I don't have new data, and I think there is enough detail in the [original post](http://tomslee.net/2013/10/notes-on-airbnbs-new-york-business.html) to understand the sources and the limits of the analysis, but here is a PDF presentation that tries to make the conclusions a bit more clear. [Here](http://tomslee.net/wordpress/wp-content/uploads/2013/11/airbnbny_handout.pdf) is a version formatted for download and printing.

[gview file="http://tomslee.net/wordpress/wp-content/uploads/2013/11/airbnbny.pdf" profile="3" save="0"]		
