---
author: Tom Slee
categories:
- blog archive
date: 2015-02-24 03:13:18
title: Going quieter for a while
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				This blog will be going even more quiet than usual for the next few months. The reason is a good one, which is that I have a contract to write a book on and around the sharing economy. As the writing has to be done in and around my actual job and home life I will have to put any and all available time into it for a while.

The Airbnb coding and analysis turns out to be a great way to procrastinate from actually writing, so I will have to put it to one side for now.

In the meantime, anyone interested in the issues raised here may like to look at the following:



	
  * Henry Farrell's "[Dark Leviathan](http://aeon.co/magazine/technology/on-the-high-seas-of-the-hidden-internet/)" in Aeon Magazine is one of the best things I've read in ages on issues of trust, governance, and digital technology. Plus it's got lots of juicy details on Silk Road.

	
  * Murray Cox has put together a beautiful site called [Inside Airbnb](http://insideairbnb.com), which maps the New York data in more detail than I do here. It's invaluable. Plus it has led to other analyses, like this one here by [Ben Wellington](http://iquantny.tumblr.com/post/110747103479/mapping-the-sharing-economy-an-in-depth-view-of), which delve further into the specifics of New York.


See you back here before too long, I hope.		
