---
author: Tom Slee
categories:
- blog archive
date: 2017-01-24 02:08:21
title: Airbnb downloadable data sets
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				I've continued to collect data about listings in cities around the world from the Airbnb web site, and I've been posting maps based on them [here](http://tomslee.net/airbnb-data).  Each map takes some manual work, so I have not uploaded all the data I've collected. But after many requests I've finally uploaded the basic data for all the 99 cities (and/or regions) I've surveyed, and they are available [here](http://tomslee.net/airbnb-data-collection-get-the-data). For some cities, it is just one survey, while for others there are (roughly) monthly surveys over a period of two years or more. Each download is a zip file that contains one or more comma-separated values (CSV) files that can be read into your generic spreadsheet program or other application of choice.

The code I use is posted on github [here](https://github.com/tomslee/airbnb-data-collection/), and the method is described roughly [here](http://tomslee.net/airbnb-data-collection-methodology-and-accuracy), although there are some changes over time. If you find mistakes or if you do find it useful, I would love to hear anything about how you use it.		
