---
author: Tom Slee
categories:
- blog archive
date: 2007-01-24 21:43:42
title: Grumpy Employees Are Productive Employees II
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Tracking back a Google search from someone who landed on my post of the other day about [grumpy employees](http://whimsley.typepad.com/whimsley/2007/01/grumpy_employee.html) led me to this supporting evidence, from the BBC in 2001. The evidence against chirpy people is mounting.




Link: [BBC News | BUSINESS | Unhappy people 'make the best workers'](http://news.bbc.co.uk/2/hi/business/1386484.stm).


<blockquote>Unhappy in your work?

> 
> Well that's exactly how your boss will want it from now on, according to new research from Canada.
> 
> 

> 
> Psychologists from the University of Alberta found miserable people make better workers than happy ones.
> 
> 

> 
> Cheerful people waste too much time trying to maintain their happy mood, while their dour co-workers simply get on with the task in hand, the project found.
> 
> 

> 
> The findings put a question mark over the millions spent each year on ensuring a happy working environment.
> 
> 

> 
> Comedians
> 
> 

> 
> Some companies even hire comedians to keep their employees smiling.
> 
> 

> 
> But if the Canadian research is right, they are wasting their money.
> 
> 

> 
> Grumpy, of Disney's The Seven Dwarves  

Grumpy: rarely whistled while he worked  

The researchers, led by psychologists Robert Sinclair and Carrie Lavis, studied four groups of workers building circuit boards on a production line.
> 
> 

> 
> Although those who described their mood as 'sad' did not produce any more work, they made half as many mistakes as happy workers - so fewer of their products failed quality control tests.
> 
> 

> 
> The study also found miserable people used work to distract themselves from their mood.
> 
> 

> 
> While happy people were more likely to regard work as an unwanted distraction - and a source of unhappiness.
> 
> 

> 
> The findings fly in the face of previous research on the subject, which suggests happy workers are more productive.
> 
> 

> 
> If it catches on, it could also spell the end for bonding weekends, company songs and other attempts at corporate jollity - something that could put a smile on the face of the most stony-faced employee.
> 
> </blockquote>

  




		
