---
author: Tom Slee
categories:
- blog archive
date: 2013-08-30 18:48:00
tags:
- sharing economy
title: Why The Sharing Economy Isn't
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				So a couple of months ago Douglas Atkin, head of Community and E-staff Member at AirBnB, took to the stage of the Le Web conference in London ([video](http://www.youtube.com/watch?v%3Dcp2Hlp2TP-M)) to announce the formation of [Peers](http://www.peers.org/): “a grassroots organization that supports the sharing economy movement.” I like grassroots organizations and I like the co-operative impulse, but this… Well here is his speech in its entirety (in italics) with comments from yours truly.


<blockquote>I joined [AirBnB](http://www.airbnb.com) about four months ago, but I’m going to talk about a different organization.</blockquote>


He means [Peers](http://peers.org).


<blockquote>In fact I’d like to talk about a movement for the sharing economy. By “a movement” I mean exactly that. I mean huge numbers of people, with a shared identity, mobilized to take action to do two things: to grow the peer sharing economy, and to fight for their collective interests against unfair and unreasonable obstacles.</blockquote>


A grassroots organization with 40 corporate “partners”, with unspecified but significant funding, formed with [guidance from](http://www.peers.org/about/) a set of high-profile “thought leaders”, without local chapters, and with nothing much for the grassroots to do, but with an Executive Director on day one.

Andrew Leonard from Salon has been following the story, and tells us that funding comes from “[mission-aligned independent donors](http://www.salon.com/2013/07/31/the_sharing_economy_gets_greedy/%5D%5B%20apparently%20these%20partners%20do%20fund%20Peers%5D%5D.)”. So that’s wealthy backers with a financial interest in the sharing economy. This is not grassroots, it’s astroturf.

If there is one thing that makes me angry, it is people appropriating the language of collective and progressive politics for financial gain. And that’s one thread of what’s going on here. As we shall see. It does seem that Executive Director Natalie Foster’s heart is in the right place, but that’s one of the tragedies of the sharing economy: well-intentioned people end up contributing to immiseration and injustice when they think they are doing the opposite.


<blockquote>So what we’re talking about here is not just people sharing their skills, or their apartment, or their car, but also their collective power to expand the sharing economy together, and to stand up against entrenched interests who stand unfairly in their way. So “people power” if you like, or more accurately “peer power”.</blockquote>


And what we’re _not_ talking about here is venture capital. Going through Crunchbase tells me that the total funding for the 40 partners is over $600M. AirBnB has received $120M, including funding from Andreessen Horowitz, Jeff Bezos, Ashton Kucher. You know, people standing up against entrenched interests.

At the end of this post I’ve added a table of what I could find. It tells us that almost all the funding is going to the Bay Area or New York. The non-profits in this organization are being taken for a ride by the appealing anti-establishment language of Silicon Valley . They need to take a look at who their bedfellows are and what the real agenda is.

Venture Capital funds are not interested in people power, they are interested in an investment with a good return. The fact that Douglas Atkin doesn’t once mention the financial motivations of the forces behind the sharing economy is either dishonest or unbelievably self-deceiving.


<blockquote>Now why would there be a need for such a thing? The sharing economy seems to be barrelling along pretty happily. Why do we need another organization? Well, firstly the opportunity. This was brought home to me a week ago in San Francisco where I attended a meeting of sharing economy participants. So there were drivers, passengers, hosts, guests, and tour guides from [RelayRides](http://relayrides.com), Lyft, AirBnB, Vayable and Sidecar, and they were literally bouncing up and down with enthusiasm about the opportunity to collaborate together — with each other.

So they were developing ideas — brilliant ideas actually — to share customers with each other, across verticals. One person even suggested that there could be a peer economy currency — maybe Bitcoin. Or even points to encourage people to cross verticals and recruit new people into this new economy.</blockquote>


The language changes, the mask slips. Participants become customers, sharing becomes buying. The phrase “across verticals” reminds us that Douglas Atkin is an advertising executive. Now the sharing economy is about loyalty programs and cross marketing? Not the kind of sharing I want to be part of. I don’t have a problem with commerce, but what I do object to is commerce wrapped up in, and appropriating, the language of solidarity.


<blockquote>These people were incredibly impressive, with their passion and their eagerness and creativity to work together locally to expand the sharing economy. So that was the opportunity. It was incredibly exciting to see that. And I did a couple more of these types of meetings, with people from different verticals in the sharing economy in New York, where the same thing happened. So there’s the opportunity.</blockquote>


The Peers organization came together, then, in San Francisco and New York – the well-heeled, well-funded districts of the sharing economy movement.


<blockquote>Secondly, though, there’s the challenges. It’s unlikely, I believe — and I believe this because I used to work for them — that the entrenched interests of the old economy are going to stand idly by as their business model of the past seventy years is challenged by the new economy.</blockquote>


Billion-dollar venture capital funds are out to undercut people who run licensed bed and breakfasts, and he’d have me believe that it’s the B&B owners who are the “entrenched interests”. If this is your idea of a revolution (and it is, unbelievably enough: that comes later) then brother don’t you know, you can count me out.


<blockquote>What’s more, outdated laws and new laws which have been badly conceived, with unintended consequences, really threaten the growth of this nascent new world economy.</blockquote>


The laws that he is talking about are licensing laws and other laws put in place to protect employees, customers, and neighbourhoods. These laws are not all perfect. But the sharing economy has nothing to replace them beyond magical thinking about “trust” (with little accountability).


<blockquote>How much better would it be if citizens banded together to grow and protect their interests in the sharing economy rather than companies wielding their power?</blockquote>


How about banding together to protest when a TaskRabbit customer posts a job to do four loads of laundry and it’s actually 10 or 15 loads covered in cat diarrhea? [No](http://www.businessinsider.com/confessions-of-a-task-rabbit-2011-12): if you do that, you’re fired. The company (a partner of Peers.org, natch) also takes steps to prevent its TaskRabbits from meeting because “They don’t want us unionizing”. I’m sorry, what was that about citizens banding together against companies?


<blockquote>So I’m here to tell you about some plans which will enable people to create a member-driven movement for the sharing economy. If you like, a new kind of union for a new kind of economy. And I’m also here to ask for your support. So if you’re a platform: help your users create this organization and join it. If you’re a thought-leader, blogger, or conference speaker: champion it. And if you’ve got some ready cash, please help fund it.</blockquote>


A new kind of union? What, me and Peter Thiel, [billionaire investor](http://www.fastcompany.com/3012593/taskrabbit-leah-busque) in TaskRabbit? Sorry, I won’t be handing over my cash any time soon.


<blockquote>Now why should you do this? Well it’s the right thing to do. We literally stand on the brink of a new, better kind of economic system, that delivers social as well as economic benefits. In fact, social and economic benefits that the old economy promised but failed to deliver. As Julia, an AirBnB host, told me just last night, “the sharing economy saved my arse”.</blockquote>


The sharing economy is not an alternative to capitalism, it’s the ultimate end point of capitalism in which we are all reduced to temporary labourers and expected to smile about it because we are interested in the experience not the money. Jobs become “extra money” just like women’s jobs used to be “extra money”, and like those jobs they don’t come with things like insurance protection, job security, benefits – none of that old economy stuff. But hey, you’re not an employee, you’re a [micro-entrepreneur](http://www.huffingtonpost.com/2012/07/10/leah-busque-taskrabbit_n_1651880.html). And you’re not doing it for the money, you’re doing it for the experience. We just assume you’re making a living some other way.


<blockquote>The old economy has largely failed us. Most people are not experiencing the economic independence and the happiness that mass production and consumerism promised. Partly, in a way, because the old system centralizes production, wealth and control. That’s just the way it works. And in a sense, that’s largely to blame. The peer sharing economy is a new model, which distributes power, wealth, and control to everyone else. Best of all, the very things that have become the casualties of the old economy — things like economic independence, entrepreneurialism, community, individuality, happiness — are actually built in to the very structure of this new economy. You can’t do sharing without building community, without creating individualized experiences.</blockquote>


The sharing economy is the centralization of global casual labour. Investors invest because individual sharing economy companies have the potential for global reach, collecting a little from each of millions of transactions around the world, and funnelling it to California.


<blockquote>We’ve had this ridiculous debate for the past thirty years ago in this old economy about a work/life balance, because the honest truth is life gets squeezed out because of work. As Rachel says: doing jobs we hate to buy shit we don’t need. But in this sharing economy, life is built in. So Etsy producers get to know their consumers and sell individualized goods. Whenever I take a Lyft or a Sidecar — which are ride-sharing organizations in San Francisco — I always ask them “So why are you doing this?” And their first response is “To interact and meet with new and interesting people”. And then secondly, the flexible hours and a bit of extra cash. It’s the community they are most interested in experiencing.</blockquote>


Trashing consumerism appeals to many environmentally-minded, social-justice oriented people. But if you displace taxi drivers and replace them with casual labour, you’re not improving the work/life balance of drivers, you’re making them poorer.


<blockquote>Fred Mazella was a genius when he named blablacar [blablacar](http://www.blablacar.com/), because he’s actually naming what happens in the car. He named his organization not after the transaction, which is ridesharing, but because people communicate and go “bla bla bla” to each other in the car. He correctly identified what the real benefit of the sharing economy is, which is these other social and economic rewards.</blockquote>


You know, I talk to taxi drivers too. Some of them are interesting people. You should try it sometime.


<blockquote>So there’s a nascent organization which is about to bloom. It’s independent, it’s member-driven, it’s global, it’s not a trade association, it’s not a lobbying group. It will use peer power and collective action to grow the sharing economy and overcome unfair obstacles.</blockquote>


I don’t know if he’s lying or if he believes this stuff, but take a look at the website of [Peers.org](http://peers.org) and tell me you believe it.


<blockquote>I personally want to see the sharing economy grow to become the dominant global economic model in the world, because of the social and economic benefits which are built-in, because of the distributed wealth, control, and power which it represents. It has the possibility of transforming the world for the better. So if you want that too, especially if you’d like to see members champion it for themselves, rather than the usual suspects, come and see me afterwards and I can tell you how you can help. Or talk to [Leah](https://www.taskrabbit.com/about), who is the founder of [TaskRabbit](https://www.taskrabbit.com/) and Fred from [blablacar](http://blablacar.com) or [Lisa Gansky](http://lisagansky.com/). We can all tell you a little more about it.

So Vive La Revolution, and thank you very much.</blockquote>


When all jobs are Taskrabbit jobs, how does anyone earn a living?





## Appendix






Here’s that table of Peers.org partners.
<table rules="groups" cellspacing="0" frame="hsides" border="2" cellpadding="6" > 

<tr >
Company
Funding ($US)
Location
Investors include…
</tr>

<tbody >
<tr >

<td class="left" >AirBnB
</td>

<td class="left" >120M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >Andreessen Horowitz, a $2.5B fund
</td>
</tr>
<tr >

<td class="left" >Airtasker
</td>

<td class="left" >--
</td>

<td class="left" >Sydney, AUS
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Bay Share
</td>

<td class="left" >--
</td>

<td class="left" >--
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Blablacar
</td>

<td class="left" >10M
</td>

<td class="left" >Paris
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Car Next Door
</td>

<td class="left" >--
</td>

<td class="left" >--
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Carpooling.com
</td>

<td class="left" >10M
</td>

<td class="left" >Munich
</td>

<td class="left" >Daimler
</td>
</tr>
<tr >

<td class="left" >City Car Share
</td>

<td class="left" >non-profit
</td>

<td class="left" >San Francisco
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Chegg
</td>

<td class="left" >195M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >(many)
</td>
</tr>
<tr >

<td class="left" >Collaborative Fund
</td>

<td class="left" >(VC)
</td>

<td class="left" >New York
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Collaborative Lab
</td>

<td class="left" >--
</td>

<td class="left" >--
</td>

<td class="left" >--
</td>
</tr>
<tr >

<td class="left" >co:NYC
</td>

<td class="left" >--
</td>

<td class="left" >New York
</td>

<td class="left" >Members include AirBnB etc
</td>
</tr>
<tr >

<td class="left" >Cookening
</td>

<td class="left" >--
</td>

<td class="left" >Paris
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Divvy
</td>

<td class="left" >--
</td>

<td class="left" >Australia
</td>

<td class="left" >--
</td>
</tr>
<tr >

<td class="left" >Farmigo
</td>

<td class="left" >10M
</td>

<td class="left" >Palo Alto
</td>

<td class="left" >Sherbrooke Capital
</td>
</tr>
<tr >

<td class="left" >General Assembly
</td>

<td class="left" >14.3M
</td>

<td class="left" >New York
</td>

<td class="left" >Maveron, a $780M fund
</td>
</tr>
<tr >

<td class="left" >Getaround
</td>

<td class="left" >19M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >Marissa Mayer
</td>
</tr>
<tr >

<td class="left" >Green Spaces
</td>

<td class="left" >
</td>

<td class="left" >New York
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >The Hub
</td>

<td class="left" >--
</td>

<td class="left" >Vienna
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >ioby
</td>

<td class="left" >--
</td>

<td class="left" >New York
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >LiquidSpace
</td>

<td class="left" >12.2M
</td>

<td class="left" >Palo Alto
</td>

<td class="left" >Greylock Partners, a $1.73B fund
</td>
</tr>
<tr >

<td class="left" >Lyft
</td>

<td class="left" >82.5M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >Andreessen Horowitz, a $2.5B fund
</td>
</tr>
<tr >

<td class="left" >Maker Media
</td>

<td class="left" >--
</td>

<td class="left" >San Francisco
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Meetup
</td>

<td class="left" >18.3M
</td>

<td class="left" >New York
</td>

<td class="left" >Omidyar Network
</td>
</tr>
<tr >

<td class="left" >Mesh
</td>

<td class="left" >(book)
</td>

<td class="left" >
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Mosaic
</td>

<td class="left" >22M
</td>

<td class="left" >Oakland
</td>

<td class="left" >Spring Ventures
</td>
</tr>
<tr >

<td class="left" >Open Shed
</td>

<td class="left" >--
</td>

<td class="left" >Australia
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >OuiShare
</td>

<td class="left" >non-profit
</td>

<td class="left" >France?
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >ParkAtMyHouse
</td>

<td class="left" >--
</td>

<td class="left" >UK
</td>

<td class="left" >BMW
</td>
</tr>
<tr >

<td class="left" >RelayRides
</td>

<td class="left" >13M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >General Motors, Google Ventures
</td>
</tr>
<tr >

<td class="left" >Scoot Networks
</td>

<td class="left" >1.65M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >Lisa Gansky
</td>
</tr>
<tr >

<td class="left" >Shareable
</td>

<td class="left" >(magazine)
</td>

<td class="left" >San Francisco
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Side.Cr (Sidecar)
</td>

<td class="left" >10M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >Lisa Gansky, Google Ventures
</td>
</tr>
<tr >

<td class="left" >Skillshare
</td>

<td class="left" >4.65M
</td>

<td class="left" >New York
</td>

<td class="left" >Union Square Ventures, a $200M fund
</td>
</tr>
<tr >

<td class="left" >TaskRabbit
</td>

<td class="left" >37.7M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >Lightspeed Ventures, a $2B fund
</td>
</tr>
<tr >

<td class="left" >TimeRepublik
</td>

<td class="left" >--
</td>

<td class="left" >South Africa?
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Vayable
</td>

<td class="left" >--
</td>

<td class="left" >San Francisco
</td>

<td class="left" >SV Angel, an $89M fund
</td>
</tr>
<tr >

<td class="left" >Yerdle
</td>

<td class="left" >--
</td>

<td class="left" >San Francisco
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >WeWork
</td>

<td class="left" >6.85M
</td>

<td class="left" >New York
</td>

<td class="left" >
</td>
</tr>
<tr >

<td class="left" >Zaarly
</td>

<td class="left" >15.2M
</td>

<td class="left" >San Francisco
</td>

<td class="left" >Kleiner Perkins Caufield & Byers
</td>
</tr>
<tr >

<td class="left" >Zookal
</td>

<td class="left" >1.46M
</td>

<td class="left" >Sydney
</td>

<td class="left" >Filtro Private Equity
</td>
</tr>
</tbody>
</table>





		
