---
categories:
- About
title: "Publications"
date: 2019-12-10
toc: true
---


# Books

-   *No One Makes you Shop at Wal* Mart
    ([link](https://btlbooks.com/book/no-one-makes-you-shop-at-wal-mart))*,*
    Between the Lines Press (2006)
-   *What's Yours is Mine: Against the Sharing Economy (2015)*.
    -   US and UK edition ([link](http://www.orbooks.com/catalog/whats-yours-is-mine-by-tom-slee/)), OR Books, November 2015
    -   Canadian edition ([link](https://btlbooks.com/book/whats-yours-is-mine)), Between the Lines Press, February 2016
    -   German edition ([Deins ist Meins](http://www.kunstmann.de/titel-0-0/deins_ist_meins-1193/)): Verlag Antje Kunstmann
    -   Spanish edition: [Lo tuyo es mío](http://www.megustaleer.com/libro/lo-tuyo-es-mio/ES0151310), Taurus, November 2016
    -   Simplified Chinese edition: (Ginkgo Book Co.)
    -   French language edition (France and Québec): [Ce Qui est à Toi est à Moi](https://www.luxediteur.com/catalogue/a-toi-a-moi/), translated by Hélène Rioux, Lux Editeur
    -   Portuguese edition (Brazil): [Uberização: a nova onda do
        trabalho
        precarizado](https://www.editoraelefante.com.br/produto/uberizacao/),
        translated by João Peres, Editore Elefante.

# Book chapters

-   "Private Sector AI: Ethics and Incentives", (in progress. Workshop [here](https://ethics.utoronto.ca/events/558/toward-a-handbook-of-ethics-of-ai-an-interdisciplinary-workshop/)), in *A Handbook of Ethics of AI*, Oxford University Press, 2019.
-   "Airbnb's Business and Arguments about Data". Address to the [4th
    Annual Asper INTLaw
    Conference,](http://law.robsonhall.com/wp-content/uploads/2018/03/2018_Program_-_ASPER_INTLaw_Conference.pdf) University
    of Manitoba, April 2018.
-   "Trust and Platform Cooperatives" in [Ours to Hack and to Own](http://www.orbooks.com/catalog/ours-to-hack-and-to-own/),
    edited by Trebor Scholz and Nathan Scheider, OR Books 2017.

# Articles, Essays and Other Contributions

-   [Gig work tensions are not going away soon](https://monitormag.ca/articles/gig-work-tensions-are-not-going-away-soon/), *The Monitor*, Canadian Centre for Policy Alternatives, May 1, 2023.
-   [The Rise and Fall of the Sharing Economy](https://www.esst.ch/getattachment/e44fdd6a-7be8-47e6-bb73-962676fc6592/Tom-Slee.aspx), presentation to the [Ernst Schmidheiny
    Foundation](https://www.esst.ch/en-us/esst-en) Symposium,
    November 2018.
-   [Transport: Time for cities to take the lead](https://retina.elpais.com/retina/2018/09/21/tendencias/1537530173_035141.html)
    (Spanish), *El Pais Retina, Series on Shared Mobility*, September
    22, 2018.
-   [Losing Trust in the Sharing Economy](https://lamaletadeportbou.com/articulos/una-perdida-confianza-la-economia-compartida/) (Catalan),
    *La Maleta de Portbou*, September-October 2018.
-   The Rise and Fall of the Sharing Economy Spanish), *Papeles de
    relaciones ecosociales y cambio globa*l, 141, FUHEM, 2018, pp 77-88.
-   [Silicon Valley to Liberal Arts Majors: We Want You](http://bostonreview.net/science-nature/tom-slee-silicon-valley-liberal-arts-majors-we-want-you),
    *Boston Review*, June 14, 2017.
-   [Airbnb is Facing an Existential Expansion Problem](https://hbr.org/2016/07/airbnb-is-facing-an-existential-expansion-problem),
    *Harvard Business Review* digital article, July 11, 2016.
-   [What's Yours is Mine](http://www.afr.com/leadership/entrepreneur/whats-yours-is-mine-the-greed-behind-the-new-sharing-economy-20160525-gp3yfo),
    *AFR Weekend*, Australian Financial Review, May 28, 2016 (book
    excerpt)
-   [The Sharing Economy isn't about sharing](http://www.alternet.org/labor/sharing-economy-isnt-about-sharing-dark-reality-behind-major-workplace-shift),
    *Alternet*, March 27, 2016 (book excerpt)
-   [The Sharing Economy's Dirty Laundry](https://www.jacobinmag.com/2016/03/uber-airbnb-sharing-economy-housing-tech/),
    *Jacobin*, March 2016
-   [In Praise of Fake Reviews](https://thenewinquiry.com/in-praise-of-fake-reviews/), *The
    New Inquiry*, October 2014
-   [Storm Warnings](http://reviewcanada.ca/magazine/2014/09/storm-warnings/)[,
    *Literary Review of Canada*, September 2014. ]{.prenton}A review
    of *To the Cloud: Big Data in a Turbulent World*, by Vincent Mosco
-   [Sharing and Caring](https://www.jacobinmag.com/2014/01/sharing-and-caring),
    *Jacobin*, January 2014
-   [Charity Assets](https://thenewinquiry.com/charity-assets/), *The
    New Inquiry,* November 2013
-   [Hacking Society](http://reviewcanada.ca/magazine/2013/09/hacking-society/) [*Literary
    Review of Canada*, September 2013. ]{.prenton}A review
    of *Networked: The New Social Operating System*, by Lee Rainie and
    Barry Wellman, *Coding Freedom: The Ethics and Aesthetics of
    Hacking*, by E. Gabriella Coleman, and *Black Code: Inside the
    Battle for Cyberspace*, by Ronald J. Deibert
-   [Open Wide](https://thenewinquiry.com/open-wide/), *The New
    Inquiry*, June 2013
-   [Seeing Like a Geek](https://thenewinquiry.com/open-wide/), *Crooked
    Timber*, June 2012
-   [Click to Judge](http://reviewcanada.ca/magazine/2012/04/click-to-judge/),
    *Literary Review of Canada*, [April 2012. ]{.prenton}A review
    of *The Reputation Society: How Online Opinions Are Reshaping the
    Offline World*, edited by Hassan Masum and Mark Tovey
-   [A Caribbean Longsho](http://reviewcanada.ca/magazine/2011/05/a-caribbean-longshot/)[t,](http://reviewcanada.ca/magazine/2011/05/a-caribbean-longshot/) *Literary
    Review of Canada*, May 2011. A review of *Internet Gambling
    Offshore: Caribbean Struggles over Casino Capitalism*, by Andrew F.
    Cooper, with Jamie Supeene.
-   Shopping 'Til We Drop, [*Literary Review of Canada*, November 2009. ]{.prenton}A review of *The Price of a Bargain: The Quest for
    Cheap and the Death of Globalization*, by Gordon Laird

# Reviews of "What's Yours is Mine"

- [Book Review: 'What's Yours Is Mine: Against the Sharing Economy'](https://www.realchangenews.org/2018/03/21/book-review-what-s-yours-mine-against-sharing-economy),
    Mike Wold, Real Change News, March 21, 2018.
-   [What's Yours is Mine](http://www.svd.se/dickens-hade-aldrig-tagit-en-uber), Håkan
    Lindgren, Svenska DagBladet, Jan 11, 2016.
-   [The broken promise of the sharing economy](http://www.netopia.eu/the-broken-promise-of-the-sharingeconomy/),
    Ralf Grötker, Netopia, Feb 3, 2016
-   [Raw Deals](http://www.counterpunch.org/2016/02/12/raw-deals-challenging-the-sharing-economy/),
    Ben Terrall, Counterpunch, Feb 12, 2016.
-   [What's Yours is Mine](https://medium.com/@saulofhearts/book-review-d60778292ad#.wh5qsu5pd),
    Saul of Hearts, Medium, Feb 25, 2016
-   [L'atto d'accusa contro la sharing economy](http://espresso.repubblica.it/visioni/tecnologia/2016/03/08/news/l-atto-d-accusa-contro-la-sharing-economy-le-persone-non-sono-aziende-1.253105),
    Fabio Chiusi, L'Espresso, 09 March 2016 (Italian)
-   [The Unforeseen Dangers of Uber and Airbnb](http://www.spectator.co.uk/2016/03/the-unforeseen-dangers-of-uber-and-airbnb/),
    Robert E. Levine, The Spectator (UK), March 5, 2016
-   [Ist Carsharing das neue Lohndumping?](https://www.welt.de/kultur/literarischewelt/article154515115/Ist-Carsharing-das-neue-Lohndumping.html)
    (German), Welt, Oliver Rasche, April 2016.
-   [Book of the Day](https://www.theguardian.com/books/2016/apr/02/whats-yours-is-mine-against-the-sharing-economy-tom-slee-review),
    Steven Poole, The Guardian, April 2, 2016.
-   [Tom Slee's What's Yours is Mine](https://mathbabe.org/2016/04/20/tom-slees-whats-yours-is-mine/),
    Cathy O'Neil, April 20, 2016
-   [Die Sharing Economy -- nur eine illusion?](https://ethik-heute.org/die-sharing-economy-nur-eine-illusion/), Birgit
    Stratmann, Netzwerk Ethikheute,  (German)
-   [Sheared](http://reviewcanada.ca/magazine/2016/05/sheared/),
    Rohinton Medhora, Literary Review of Canada, May 2016
-   [Book slams Uber, Airbnb, and Sharing Economy](https://www.thestar.com/news/canada/2016/05/01/book-takes-on-uber-airbnb-sharing-economy-walkom.html),
    Thomas Walkom, Toronto Star, May 1, 2016
-   [What's Yours is Mine](http://www.truthdig.com/arts_culture/item/whats_yours_is_mine_20160502),
    Peter Richardson, Truthdig, May 2, 2016.
-   [Teile und herrsche](https://www.jungewelt.de/m/artikel/294841.teile-und-herrsche.html),
    Thomas Wagner, junge Welt, May 10, 2016
-   [What's Yours is Mine](http://lizpelly.com/post/148159855537/review-whats-yours-is-mine-against-the-sharing),
    Liz Pelly, Maximum Rocknroll, June 2016
-   [What's Yours is Mine](http://www.innovation.cc/book-reviews/21_1_7-doughty_bk-rev_slee_yours-mine.pdf),
    Howard Doughty, The Innovation Journal, 21 (1) 2016
-   [What's Yours is Mine](http://www.compulsivereader.com/2016/03/25/a-review-of-whats-yours-is-mine-by-tom-slee/),
    Ruth Latta, The Compulsive Reader, March 25, 2016
-   [Le duel des critiques](http://bfmbusiness.bfmtv.com/mediaplayer/video/le-duel-des-critiques-margaret-thatcher-vs-tom-slee-2110-878557.html),
    BFM Business, (French, video).

# Interviews

-   Interviews on the Sharing Economy, Canadian Broadcast Corporation,
    various.
-   [The Sharing Economy](https://www.youtube.com/watch?v=hzmjnar000k) (YouTube
    link), The World According to Jesse Ventura, RT America,
    August 2018.
-   [The Sharing Economy is a Bubble](https://www.bilanz.ch/people/die-sharing-economy-ist-eine-blase-761397)
    (interview, German), *Bilanz*, November 1, 2016
-   [What do we do about a problem like Uber](http://www.theregister.co.uk/2016/01/15/tom_slee_sharing_economy_interview/),
    Andrew Orlowski, The Register, 15 Jan 2016
-   [Inside the sharing economy](http://www.netopia.eu/25-tech-75-marketing-100-hype-inside-the-sharingeconomy/),
    Per Strömbäck, Netopia, 3 Feb 2016
-   [Every person a market](https://thisishell.com/interviews/887-tom-slee), Chuck
    Mertz, This is Hell, 23 Feb 2016 (audio),
-   [The Sharing Economy is Not Your Friend](https://www.vice.com/en_us/article/the-case-against-airbnb-and-uber),
    Drew Millard, Vice, Feb 2016.
-   [Sharing is not always caring](http://www.waterloochronicle.ca/news-story/6382561-sharing-not-always-caring-says-author/),
    James Jackson, Waterloo Chronicle, 09 Mar 2016
-   [Geldwertes Teilen](http://www.deutschlandradiokultur.de/tom-slee-deins-ist-meins-geldwertes-teilen.1270.de.html?dram:article_id=348110),
    DeutschlandRadio Kultur, 12 March 2016 (German)
-   [The technology is just a shiny shopfront](http://www.newstatesman.com/politics/economy/2016/03/technology-just-shiny-shopfront-case-against-sharing-economy),
    Barbara Speed, The New Statesman, 21 March 2016.
-   ["Diese Jobs schaffen ein neues Prekariat"](http://www.spiegel.de/wirtschaft/airbnb-und-uber-was-steckt-hinter-der-sharing-economy-a-1083971.html),
    Nils Klawitter, Spiegel Online, 23 March 2016 (German)
-   [Teile und herrsche](http://www.nzz.ch/nzzas/nzz-am-sonntag/sharing-economy-teile-und-herrsche-ld.14306),
    Barbara Hofler, NZZ Am Sontag, 16 April 2016 (German, Switzerland)
-   [What's Yours is Mine](http://rabble.ca/podcasts/shows/redeye/2016/04/whats-yours-mine-against-sharing-economy),
    Redeye Collective, Vancouver (audio), 29 April 2016
-   [Sharing the wealth, unevenly](https://www.youtube.com/watch?v=bs830YuQm3g), The Agenda
    with Steve Paikin, TV Ontario, 4 May 2016
-   [Uber og Airbnb underminerer demokratiet](http://www.djoefbladet.dk/blad/2016/10/uber-og-airbnb-underminerer-demokratiet.aspx),
    Assia Awad, djoefbladet, 26 May 2016 (Danish)
-   [Sharing economy platforms exist for one purpose only, which is to make money for their investors](https://medium.com/@FelixSimon/sharing-economy-platforms-exist-for-one-purpose-only-which-is-to-make-money-for-their-investors-82aa6cc45989#.iztg63liq),
    Felix Simon, Medium, 6 June 2016 -   [10 Questions on the sharing
    economy](http://tvo.org/video/programs/the-agenda-with-steve-paikin/10-questions-on-the-sharing-economy) (video)
    ([transcript](http://tvo.org/transcript/2364980/video/programs/the-agenda-with-steve-paikin/10-questions-on-the-sharing-economy)),
    The Agenda with Steve Paikin, TV Ontario, 14 June 2016.
-   [Can't find a home in Seattle? Airbnb rentals may be to blame](http://www.seattletimes.com/seattle-news/data/cant-find-a-home-in-seattle-airbnb-rentals-may-be-to-blame/),
    Gene Balk, The Seattle Times, 15 June 2016 (Seattle)
-   [Short-term rentals are reshaping real estate market in some cities](http://www.marketplace.org/2016/09/19/business/short-term-rentals-are-reshaping-real-estate-market-some-cities),
    Tony Gonzalez, Marketplace, 20 Sept 2016
-   [The Sharing Economy Blues](https://canadiandimension.com/articles/view/the-sharing-economy-blues),
    David Hugill, Canadian Dimension, 23 September 2016
-   [Die Sharing Economie ist eine Blase](http://www.bilanz.ch/people/die-sharing-economy-ist-eine-blase-761397),
    (German), Marc Kowalsky, Bilanz, November 2016.
-   [UK Tribunal Rules in Favour of Uber Drivers](http://rabble.ca/podcasts/shows/redeye/2016/11/uk-employment-tribunal-rules-favour-uber-drivers)
    (audio), Redeye Collective, Vancouver, 22 Nov 2016
-   [The so-called sharing economy](http://www.abc.net.au/radionational/programs/themoney/share-economy/7777658),
    Richard Aedy, The Money, Australian Broadcasting Corporation,
    December 2016, (audio)
-   [The Great Exchange](https://www.cpacanada.ca/en/connecting-and-news/cpa-magazine/articles/2017/april/the-great-exchange),
    Lara Bourdin, CPA Magazine (Chartered Professional Accountants),
    April 1, 2017
-   [Taking the Uber Bus](http://tvo.org/video/programs/the-agenda-with-steve-paikin/taking-the-uber-bus)
    (video)
    ([transcript](https://www.tvo.org//transcript/2438337/video/programs/the-agenda-with-steve-paikin/taking-the-uber-bus)),
    The Agenda, TV Ontario, April 2017.
-   [Sharing Economy. Il rovescio della medaglia](http://www.telosaes.it/primo-piano-scala-c/il-rovescio-della-medaglia.html) (Italian), Mariella
    Palazzolo,  Primo Piano Scala c, April 2017.

# Quotes, and articles using my Airbnb data

-   [Airbnb can't go on unregulated -- it does too much damage to cities](https://www.theguardian.com/commentisfree/2018/oct/24/airbnb-unregulated-damage-cities-barcelona-law-locals), Steven Poole, The Guardian, October 24, 2018.
-   [New data suggests Airbnb's impact on Halifax's rental climate](https://www.thecoast.ca/halifax/new-data-suggests-airbnbs-impact-on-halifaxs-rental-climate/Content?oid=19177672), Sandra Hannenbaum, *The Coast,* November 15, 2018.
-   [Nobody's Business](https://www.policyalternatives.ca/airbnb): CCPA
    report on short-term rentals in Toronto, 22 September 2016
    -   [Airbnb cutting into available rentals in Toronto](http://www.metronews.ca/news/toronto/2016/09/22/airbnb-cutting-into-available-rentals-in-toronto.html),
        study shows, Metro News, 22 Sep 2016
    -   [Airbnb cutting into available rentals in city](https://www.thestar.com/business/2016/09/22/airbnb-cutting-into-available-rentals-in-city-study-shows.html),
        Tess Kalinowski, Toronto Star, 22 Sep 2016
    -   [Airbnb Is Sapping Toronto Of Rental Housing:
        Report](http://www.huffingtonpost.ca/2016/09/22/airbnb-toronto-rental-housing_n_12143006.html),
        Jesse Ferreras, Huffington Post, 22 Sep 2016
    -   (and others)
-   [Airbnb has made it nearly impossible to find a place to live in
    this city](http://fusion.net/story/305584/airbnb-reykjavik/),
    Kristen V. Brown, Fusion, May 24. (Reykjavik)
-   [How do we research the sharing economy when the data can't be
    validated?](http://www.washingtonpost.com/news/monkey-cage/wp/2016/06/06/how-do-we-research-the-sharing-economy-when-the-data-cant-be-validated/),
    Andrew Gelman, Monkey Cage Blog (Washington Post), June 6, 2016.
-   [Cities take aim at
    Airbnb](http://www.theglobeandmail.com/news/british-columbia/concerns-about-airbnb-impact-on-rentersspread/article30845642/),
    Sunny Dhillon, Globe and Mail, 11 July 2016
-   [Airbnb in Vancouver and its impact on affordable
    housing](https://affordablevancouver.files.wordpress.com/2016/07/airbnb-vancouver-report-iain-marjoribanks.pdf),
    Iain Marjoribanks, 1 June 2016,
-   [Airbnb open to market regulations in large cities like
    Vancouver](http://www.theglobeandmail.com/news/british-columbia/airbnb-open-to-market-regulations-in-large-cities-like-vancouver/article31093303/),
    Mike Hager, Globe and Mail, 25 July 2016 (Vancouver)
-   [Iceland tourism and the mixed blessings of
    Airbnb](https://skift.com/2016/08/19/iceland-tourism-and-the-mixed-blessings-of-airbnb/),
    Andrew Scheivachman, Skift, 19 Aug 2016
-   [Small towns can't handle the sharing economy tourism
    boom](http://fusion.net/story/339171/small-towns-airbnb/),
    Kristen V. Brown, Fusion, 28 August 2016.
-   [Airbnb et
    Uber](http://ici.radio-canada.ca/premiere/emissions/plus-on-est-de-fous-plus-on-lit/saison-2016-2017/segments/chronique/8926/economie-du-partage-airbnb-uber-capitalisme-nicolas-tittley-arun-sundararajan-tom-slee),
    Nicholas Tittley,** **Radio Canada, September 2016. (audio)
-   [Lancé à Bordeaux, l'observatoire Airbnb veut créer un débat
    national](http://rue89bordeaux.com/2016/10/lance-a-bordeaux-lobservatoire-airbnb-veut-creer-debat-national/),
    Xavier Ridon, Rue89 Bordeaux, 25 Oct 2016 (Bordeaux)
-   [New York deflates
    Airbnb](http://www.economist.com/news/business/21709353-new-rules-may-temper-airbnb-new-york-its-future-still-looks-bright-new-york-deflates),
    The Economist, 29 Oct 2016.
-   [The 14 th Global Forum on Tourism
    Statistics](http://tsf2016venice.enit.it/images/articles/Papers_Forum/6.2_Assessing%20the%20impact%20of%20shared%20accommodation%20for%20city%20tourism.pdf),
    23-25 Nov 2016
-   [Consumo collaborativo: dall'anticapitalismo al rilancio del
    mercato](http://www.ilgiornale.it/news/spettacoli/consumo-collaborativo-dallanticapitalismo-rilancio-mercato-1339915.html),
    Carlo Lottiere, il Giornale, 7 Dec 2016 (Italian)
-   [Uber uses scare tactics to turn drivers from
    unions](https://www.classaction.com/news/uber-scare-tactics-turn-drivers-from-unions/),
    ClassAction.com, April 12, 2017.
-   [Planning enforcement at the time of
    Airbnb](http://planning%20enforcement%20at%20the%20time%20of%20airbnb/),
    Francesco Mellino, Planning in London, April-June 2017.

# Report: How Airbnb hid the facts in New York City

Together with Murray Cox of Inside Airbnb,  I produced a report on
Airbnb's removal of 1500 listings in New York, just in time to make its
public release of data look good.

-   The report: [my site](http://tomslee.net/how-airbnb-hid-the-facts-in-nyc), and
    [Inside Airbnb](http://insideairbnb.com/how-airbnb-hid-the-facts-in-nyc/)
-   Airbnb admits it purged listings:
    [Fusion](http://fusion.net/story/272780/airbnb-new-york-data-purge/),

Mainstream media:

-   New York Times: [Airbnb Purged New York Listings to Create a Rosier Portrait, Report Says](http://www.nytimes.com/2016/02/12/business/airbnb-purged-new-york-listings-to-create-a-rosier-portrait-report-says.html)
-   The Guardian: [Airbnb purged more than 1,000 New York listings to rig survey -- report](http://www.theguardian.com/technology/2016/feb/10/airbnb-new-york-city-listings-purge-multiple-apartment-listings)
-   Fortune: [Researchers say Airbnb Fudged New York City Listing Data](http://fortune.com/2016/02/11/airbnb-listings-research-data/)
-   CNBC: [Report Says Airbnb Fudged Data To Hide Illegal Hosts](http://www.cnbc.com/2016/02/12/report-says-airbnb-fudged-data-to-hide-illegal-hosts.html)

New York & real estate:

-   The Real Deal: [De Blasio chides Airbnb over alleged data purg](http://therealdeal.com/2016/02/17/de-blasio-chides-airbnb-over-alleged-data-purge/)e
-   New York Daily News: [Airbnb dropped 1,000 possibly illegal listings
    before opening its books to lawmakers](http://www.nydailynews.com/news/world/airbnb-dropped-1g-questionable-listings-opening-books-article-1.2526230)
-   The Real Deal:  [Airbnb purged over 1,000 listings before December data release: report](http://therealdeal.com/2016/02/10/airbnb-purged-over-1000-listings-before-december-data-release-report/)
-   New York Magazine: [Airbnb accused of purging 1000 NYC listings to make its numbers look better](http://nymag.com/following/2016/02/airbnb-accused-of-purging-1000-nyc-listings.html)
-   TechnoBuffalo: [Airbnb used dirty tactics to clean up 1,000 New York City listings](http://www.technobuffalo.com/2016/02/11/airbnb-used-dirty-tactics-to-clean-up-1000-new-york-city-listings/)
-   New York Business Journal: [Airbnb honesty in question after report claims the startup 'photoshopped' data](http://www.bizjournals.com/newyork/news/2016/02/11/airbnb-honesty-in-question-after-photoshopped-data.html)
-   Curbed: [Airbnb May Have Deleted NYC Listings to Bolster Its Image](http://ny.curbed.com/archives/2016/02/12/airbnb_may_have_deleted_nyc_listings_to_bolster_its_image.php){.post-title}

Tech press:

-   Re/code: [Did Airbnb Purge Potentially Illegal NYC Listings Ahead of Its Own Data Dump?](http://recode.net/2016/02/10/did-airbnb-purge-potentially-illegal-nyc-listings-ahead-of-its-own-data-dump/)
-   Fusion: [A new report alleges that Airbnb manipulated data to make
    itself look better
    to regulators](http://fusion.net/story/267202/a-new-report-alleges-that-airbnb-manipulated-data/)
-   Digital Journal: [Airbnb allegedly purged 1,000+ New York listings to rig survey](http://www.digitaljournal.com/business/business/airbnb-removed-over-1-000-new-york-listings-to-rig-survey/article/457233)
-   Gizmodo: [Looks Like Airbnb Manipulated Its Own Data To Appear Less Evil](http://gizmodo.com/looks-like-airbnb-manipulated-its-own-data-to-appear-le-1758476967)
-   The Awl: [The Mystery of the Thousand Missing Airbnbs](http://www.theawl.com/2016/02/the-mystery-of-the-thousand-missing-airbnbs)
-   Boing Boing: https://www.tvo.org/video/programs/the-agenda-with-steve-paikin/10-questions-on-the-sharing-economy
-   [The mystery listings Airbnb "purged" before transparency report](http://boingboing.net/2016/02/11/about-those-mystery-listings-a.html)

Other things:

-   Alternet: [How Airbnb Misled the Public and the Press](http://www.alternet.org/economy/how-airbnb-misled-public-and-press)
-   Next City: [Airbnb Allegedly Manipulated Data to Hide Illegal Hosts in NYC](https://nextcity.org/daily/entry/aribnb-data-new-york-city-illegal-hosts)

International:

-   Accommodation Association of Australia [(reprint of press release)](http://www.aaoa.com.au/Media/News/tabid/1884/ItemID/1116/View/Details/Default.aspx)
-   El Confidencial: [Acusan a Airbnb de manipular sus datos para ocultar propiedades ilegales](http://www.elconfidencial.com/tecnologia/2016-02-11/acusan-a-airbnb-de-manipular-sus-datos-para-ocultar-propiedades-ilegales_1150524/)
-   Preferente:  [Airbnb, acusada de manipular datos para ocultar
    propiedades
    ilegales](http://www.preferente.com/noticias-de-agencias-de-viajes/airbnb-acusada-de-manipular-datos-y-ocultar-propiedades-ilegales-258363.html)
-   Allcompanies (Dutch): [Airbnb verwijderd meer dan 1.000 New York
    aanbiedingen te rig survey --
    rapport](http://allcompanies.website/2016/02/11/airbnb-verwijderd-meer-dan-1-000-new-york-aanbiedingen-te-rig-survey-rapport/)


# Events

-   [Octopus Books](http://octopusbooks.ca/event/what%E2%80%99s-yours-is-mine-against-the-sharing-economy-book-launch-with-author-tom-slee)
    (Ottawa)
-   [Last but not Least Feast](http://www.wordsworthbooks.com/events/category/the-last-but-not-least-feast-sunday-brunch),
    Words Worth Books and The New Quarterly (Kitchener-Waterloo)
-   [Word on the Street](http://thewordonthestreet.ca/toronto/festival/participants/tom-slee/)
    (Toronto)
-   [The City Seminar: The Ghost Economy](http://www.yorku.ca/yuevents/index.asp?Event=37232&Category=0&ShowCal=&TimeSame=Nov&Month=11&Year=2016&EventTitle=York%20Events:%20The+City+Seminar%3A+The+Ghost+Economy),
    York University, November 4, 2016
