---
author: Tom Slee
categories:
- blog archive
date: 2007-03-17 15:50:54
title: The Long Tail 9.3 - The Short Head Part 2
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is another part of my critical reader's companion to _The Long Tail_, and it discusses the second half of Chapter 9 - The Short Head. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html).

* * *

The second half of Chapter 9 is a meandering stroll around the topic of "finding things". It's an odd place for it in the book - this reads like a part of Chapter 7 - The New Tastemakers that has wandered into the wrong part of the book by mistake. Warning - this is even more rambling than the other posts in the series: it is more of a set of half-baked thoughts than a coherent thesis. But hey, this is a blog.




In the Library of Misshelved Books [156-160] starts off this way: "One of the most vexing problems with physical goods is that they force us into crude categorization and static taxonomies, as we saw with Wal-Mart. That means a windbreaker can be in the 'Jackets' section or the 'Sports' section, but not in a 'Blue' section or 'Nylon' section" [156]. A thing has to be in one place or another but not both, and so can be difficult to find. In the online world, things can be in many places at once, and this opens new doors: "The efficiency and success of online retail have illuminated the cost of traditional retail's inflexibility and taxonomical oversimplification. It's one thing to have high prices or limited selection; it's quite another to simply be able to help people find what they want". [157] 




Despite this start, the section is mainly about libraries. It describes the Dewey Decimal System for organizing books and its cultural biases and limitations. The numbers from 200 to 300, for example, are "Religion", but all religions apart from Christianity are lumped into the interval from 290 to 300. But although the cultural bias of the Dewey Decimal System is clear, its practical consequences are small because, as any library aficionado knows, the Dewey Decimal System goes on several places past the decimal point. As a result you can fit as many books between 290 and 300 as in any other interval, because The Long Tail, for example, is "658.802 And"; No One Makes You Shop at Wal-Mart is "306.123 Sle". Anyone who has spent time in a library knows there are some areas where the numbers fly by and others where there are whole shelves that have the same number up to the second decimal place. But that's OK, because additional numbers are free: you could say that the Dewey Decimal System exploits the free shelf space of numbers to extend into the Long Tail of digits. (Aaargh! I have to give Anderson this - the phrase is very infectious.) But anyway, once you have a number for a book, finding it on a shelf is rarely difficult and that's the point.




Shopping in the Miscellaneous Aisle [160-162] starts off by admitting this: "In libraries, at least there is a standard categorization scheme -- the card catalog is there to be searched, and librarians tend to know their stuff" [160]. Haven't seen a card catalog in a while, but it is good to know that Chris Anderson and I agree there is little problem with libraries. So where is there a problem?




Well, it's retail stores: those nylon jackets. And it's true that it can be difficult finding things from time to time (wandering around Toys-R-Us with two pre-school kids was my worst experience, I think). But while this is a section I actually have more agreement with than most in the book, Anderson sets us up again. He complains how difficult it was to look for the Japanese anime classic "Akira" in a Blockbuster store, but "As it turned out, it didn't matter - they didn't have the film" [161]. He contrasts this experience with Amazon, where he types the title into the search bar and gets right to the film immediately, along with recommendations for other films. He also says all films were "in stock and cheaper than Blockbuster. The experience I had with these two stores couldn't have been more different" [161] . He is exaggerating again. This section is about locating things, and if you are searching for something not in stock, then it's not surprising you don't find it. 




But let me give credit where credit is due. The access methods that Amazon has built into its site are very impressive and increasingly sophisticated. As examples I looked for two obscure songs: Ken Boothe's 1972 "Freedom Street" and Fontella Bass's "To Be Free" (I couldn't remember the title and had to browse) and found both quickly, complete with sound sample; I also tried to cheat by looking up "The The" - a band with the worst possible name in a Google-dominated world (try finding them) - but Amazon tracked them down.




If the thing you are looking for is a digital product (a category that is growing rapidly, including songs, beginning to include movies and books) then Amazon can take you to it. But if the thing you are looking for is not digital, as in Anderson's example in Chapter 10 of looking for jam, then Amazon can't take you to the product itself. It can take you to an image of it, and written material about it, but sometimes these are not enough. The virtual shelf is somewhere in between an actual shelf and a card catalogue. Some of the items on the virtual shelf are actual items, and others are cards that tell you "we can send you what's described here".




An area not covered by Anderson is browsing - which is what many of us do when looking through music stores, bookstores, or video stores. Amazon is doing wonders improving its browsing experience (the ability to look inside the book being an obvious example), but it is still struggling uphill, I would say.




The Tyranny of Geography [162-164] returns to one of the book's original claims, that geography limits variety: "in the tyranny of physical space, an audience too thinly spread is the same as no audience at all. Thus, local demand must be a a high enough concentration to compensate for the high costs of physical distribution. In other, more obvious words, not enough local demand equals no store" [163]. The shortfalls in this argument - the various workarounds that we employ, the role of cities in providing that variety and of communities in passing niche products around - were already highlighted by piefuchs in a [comment on Chapter 2](http://whimsley.typepad.com/whimsley/2007/02/this_is_part_of.html#comments). It's not that there's no truth to Anderson's claims, but it's just irritating that he stacks the deck in his own argument's favour even here. When looking at the restrictions on physical stores, he sets out the calculation of sales they can make this way [163]:




Sales =  
The percentage of the population who might buy  
Minus  
The percentage not within ten miles of the store  
Minus   
The percentage that never comes in  
Minus   
The percentage that won't see the item on the shelf  
And so on...




But for some specialist stores in big cities, it could be like this:




Sales =  
The percentage of the city population who might buy  
Plus  
Those from surrounding towns who come in every now and then  
Plus  
Those who phone in special orders  
Plus  
Those whose relatives pick up something for them while they are in town  
And so on...




Variety in the physical world is, as discussed earlier, much more uneven than in the online world. This heterogeneous nature of the physical world does have some other benefits. A place that is a centre for jazz music stores is also likely to be a centre for jazz clubs in the evening, and to be a place where jazz musicians as well as jazz audiences tend to aggregate. The benefits of such cultural centres spill over from the consumption of culture into the production of culture, and then into the invention of new forms of culture. So while it is true that, just like catalogue shopping increased variety in a convenient way to small-town residents in years past, so online retailers "can reach all those many low-density towns as efficiently as the high-density ones, they can tap the Long Tail of distributed demand" [163-164], it is also true that the homogeneity of the online retail world may erode the vitality of those cultural centres that create the culture they sell.




The same is true - even more so - when it comes to international culture. The online world reaches small countries with the same ease that it reaches big countries, and promises to even out consumer access to cultural goods around the world. But this will do little to even out the production of cultural variety, because cultural variety is a product of the lumpiness of our world. It is the uneven concentrations of people, the barriers between one place and another -- the fact that we are all isolated, to some degree, from people elsewhere in the world and so have to grow within our own communities -- that lead to cultural diversity, whether its the brass bands of coal mining towns in the North of England or cajun cooking or the Milan opera. Various forms of cultural protection - subsidies to cultural industries, restrictions on imports, national content regulations - have been successfully used all around the world to promote local culture, and so to maintain diversity in the face of economies of scale. 




Cultural protection has something of a bad reputation these days. Opponents argue that any culture worth its salt will prosper in a global market, but such an argument neglects the economics of cultural goods, where marginal cost is zero. Any revenue that an American TV show sold to a smaller market gains is gravy for its producers, and as a result American shows will typically be far cheaper for TV stations to broadcast than local fare. Again, cultural production is caught in a vice, with one jaw being those economies of scale driving production geared "for an international audience" and the other jaw being the online world, where endless variety is present in principle but not always in practice. 




Skipping ahead a little, Anderson complains that "the Long Tail doesn't have a lobby, so all too often only the Short Head is heard" [167] in legislation of the Internet. But the Long Tail does have a lobby - all those national cultural industries lobbying for the promotion of local culture are part of a struggling Long Tail - but it's not a lobby that gets much support from the Silicon Valley entrepreneurs who praise Anderson's book. This should remind us that if we are looking for a route to a "niche driven culture" then Amazon and Netflix and Rhapsody and Apple's iTunes are not the people we should be looking to as guides to take us there.




Scarce Air [164-166] is a return to another earlier topic: broadcast radio and TV. It adds little to the discussion in Chapter 2. Only one paragraph demands comment, and it's the final one where Anderson laments ad clutter on television. In the US, apparently, "following deregulation in the mid-1980s, network TV ad time per hour increased from six minutes and forty-eight seconds in 1982 to twelve minutes and four seconds in 2001" [165] Why? Because viewers had nowhere to go. 




The implicit claim is that audiences are now "starting to take back their attention" [166] and refusing to put up with this advertising overload. And yet it seems clear that the main way of making money from online activity has become, thanks to Google, the insertion of pervasive advertising content alongside and interspersed with content that we are actually interested in. To suggest that we are moving away from an advertising-driven culture is possible only with the blinkered view of cultural industries that characterise the whole book. But that's part of his irrepressible ability to see the online world through rose-tinted glasses, a trait continued in the final section, which is...




The Dangers of Hitism [166-167] Here Anderson celebrates those "Kids who started using the Internet as twelve-year-olds in 1995 [and who] turned eighteen (the beginning of Nielsen's 18-34 demographic that is highly coveted by advertisers). The males of the species, in particular, were watching less television. Given a choice between the infinite variety and easy ad-dodging online versus network TV, they were choosing the former... The audience is migrating away from broadcast to the Internet, where niche economics rule" [166]. 




It takes only a few moments of reflection to realise that the "infinite variety" of the online world was not the only place they were going. They were also spending many hours in the hit-driven world of video games, where endless variations on the theme of war games are aimed at precisely this 18-34 male audience. But Anderson is blind to all manifestations of hit driven culture that don't fit his thesis. 




It takes only a few more moments to realise that an environment funded by advertising in which ads are easily avoided will not last for long. Something has to change - either companies whose commercial model is based on advertising will fail or advertising will become more intrusive so we can't avoid it.




The chapter as a whole does not, I would say, advance the Long Tail thesis. Instead, by returning to some of the topics from earlier in the book, it inadvertently opens our eyes to the complexities and subtleties of what it takes to make a world of variety. The Long Tail model of internet commerce is not up to the task of building such a world.


		
