---
author: Tom Slee
categories:
- blog archive
date: 2007-03-04 12:03:16
title: The Long Tail 5.1 - One Big Virtual Tent
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is a part of my critical reader's companion to _The Long Tail_, although it doesn't discuss any one chapter. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/the_long_tail/index.html). You have to read upwards, in usual blog fashion. When I get to the end I hope to put these all together in one big file for download.




It's time to take a breather and stop turning the pages of The Long Tail. I hope I've made the point now that there are a lot of problems with the book, a lot of places where (as John said) "It looks like his theory has become so obvious and inevitable to him that he sees the 'revolution' coming even when the facts seem to point in the other direction." It's time to step back a bit. After all, even if much of The Long Tail is fluff, what about the idea at the heart of the book? Even if it takes only a few sentences to state instead of 240 pages, it could still be a penetrating insight that holds up despite the sloppiness of the supporting material. So the question is, if I don't think the world of the Internet is Long Tail, what do I think it is like? Criticism can only take us so far without something constructive to put in its place.




The short answer to these questions are that I believe The Long Tail idea has merit only to the extent that the physical world is trapped in a digital vice of IT-driven big-box stores on the one hand and online stores on the other. Second, that to the extent a single image can be used to describe the world of the Internet, we could say that online commerce replaces a world of Many Little Tents by One Big Virtual Tent.  
There is a lot of stuff under the One Big Virtual Tent, but that stuff is hard to find, there's only one of it, and it's probably based in California.  
  
The core of the Long Tail hypothesis is that (i) Internet-based businesses, unencumbered by the tyranny of physical space, are able to make far more different products available than "bricks and mortar" stores, (ii) Internet-driven increased access to these niche products leads to greater demand for them - demand is driven down into the Long Tail, with the end result that (iii) we move from a market driven by hits or blockbusters to a market of niches. Finally (iv) this coming together of a diversity of tastes with a democracy of production is a think to be celebrated as a natural, unfiltered, and diverse outcome. The Internet brings an "explosion of variety" where "On the infinite aisle, everything is possible" [226].




The first thing to say is that (the title of this entry aside) to stretch one simple image over the entire Internet phenomenon - which Anderson does sometimes - cannot work and is of little use. It's as if we tried to stretch a single image over the invention and development of the internal combustion engine. If you wanted to write a book in the early years of motorized transport talking about the future of business and of culture what would you say? Just that there were many futures to business. There were futures of families scattering across the miles as travel became easier, and of families overcoming distance to stay in touch. There were futures of homogeneity as economies of scale took hold, and futures of variety as people became exposed to influences from outside their own neighbourhood. There were futures of war and of peace, of great depressions, general strikes, longer lives, wonderful sights that could never be reached before. You get the idea. You just can't take a phrase like The Long Tail and stick in on a development with such far-reaching implications as computerization and the Internet and apply it to everything without it losing all meaning. So the Long Tail in its broadest use is meaningless, and needs no competing theory to replace it.




Narrowing the scope of the idea to something more manageable, a reasonable question is "will the shift to online commerce (Amazon, Netflix, iTunes) lead to a more diverse environment for cultural products?" I predict no with some qualifications. Such businesses are freed, as Anderson points out, from the constraints of geography. But geography, as Anderson admits from time to time, not only limits diversity, it is also a source of diversity. When we move our shopping online, the first physical stores to feel the pinch are not the Borders, Blockbuster, and Wal-Marts but are the smaller specialist sellers within physical communities. These specialist sellers are almost completely ignored by Anderson, as I've pointed out in the last several posts. Some specialist sellers will manage to thrive in the online world, but others (a computer book store in my town, for example) will be driven to the wall by online competition. To the extent that we abandon local businesses for online shopping, we lose rather than gain diversity.




If we are to compare the online world to the physical world we must do the job properly and compare all the online world to all the physical world. This is a difficult job, because the physical world is much more uneven than the online world: the economies of scale in the online world tend to create oligopolistic or even monopolistic markets in a way that outdoes even the Wal-Marts of the physical world, and Amazon is as accessible to people in small towns as it is to people in major cities. When looking at the availability of jazz music, for example, piefuchs' [comment on Chapter 2](http://whimsley.typepad.com/whimsley/2007/02/this_is_part_of.html#comments) captures the difficulty of measuring the change:

<blockquote>Growing up in small-town NS I used to love to come to Boston to buy CDs - especially jazz. Now however, anyone can buy any CD on the web, but living here in Boston I can no longer go to a store see the same magnitude of selection, since every record store with a substantial new jazz department has closed. So are more people actually buying jazz instead of the blockbuster or are more people in small towns buying jazz on the web rather than when they travel?
> 
> </blockquote>

The physical world is a world of heterogeneous variety, while the online world is a world of homogeneous variety. It is not clear that averages help very much when comparing physical apples to online oranges, but we can at least say that one thing you don't do is compare Borders (or Chapters/Indigo, or Waterstones) to Amazon and claim you are comparing the physical and online worlds. The measurement biases of the book are pervasive and ignore the shift from a relatively heterogeneous retail environment in the physical world to a homogeneous retail environment in the online world. These biases are a big part of what make the book fundamentally wrong.




The other reason for my disbelief in the Long Tail is that it is not only the niches that benefit from being freed from "the tyranny of geography". Hits benefit too. The phenomenon of movies opening simultaneously worldwide is possible only in a digital age. The possibility of such global rewards, especially when complemented by supply-side economies of scale and multiplied by synergistic products (the action figure and video game of the movie of the book) and given the fixed costs of producing digital content pushes markets towards the Short Head, not the Long Tail. The phenomenon of world-wide bestseller book releases is likewise a recent phenomenon (I believe, but confess I don't have figures to back it up) and as John commented, there is evidence via Anderson's weblog itself that midlist titles are [struggling](http://www.authorsguild.org/miscfiles/midlist.pdf) relative to hits in the bookselling market.




On the demand side too, there are forces that push us towards the Short Head. As Dipper pointed out in the [comments to Chapter 1](http://whimsley.typepad.com/whimsley/2007/02/chapter_1_start.html#comments):

<blockquote>One reason people buy arts and cultural products such as books, dvd's, games, clothes, cars is to participate in cultural life. That means buying what other people are buying
> 
> </blockquote>

The weakening of geographical constraints means that the definition of "other people" broadens out. 




What is the net result of these competing forces? The nearest I can see to a simple statement is that the online world is One Big Virtual Tent whereas the physical world is Many Little Tents. There's little doubt that there is more variety under the One Big Tent than in any of the Many Little Tents (even the biggest of them). But is there more variety in the One Big Tent than in all the Many Little Tents together? Well, if you live close to only one little tent, the answer is undoubtedly Yes. If you live closer to a field crammed with Little Tents, then the answer may be No. And can you find what you want in the One Big Tent? Not yet would be my answer. Finding things online is a topic of Chapter 7 in the book, so there will be more to say there, but let's just say that if you know what you are looking for you can find it on Amazon, but you are unlikely to come across, as I did in my public library, the strange and compelling stories of [Agota Kristof](http://www.google.ca/url?sa=t&ct=res&cd=1&url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FAgota_Kristof&ei=OvvqRc7JCKfQgQLk-ZTaCQ&usg=__X4HIlCanF66WyXwt1jTpJ1ukUTY=&sig2=wGsHzDNG2DjTifzLs1j_ew) by chance.




In comparing Many Little Tents with One Big Virtual Tent also need to look at geography at the level of nations as a source of diversity. As in so much else on this topic, my favourite reference is [Blockbusters and Trade Wars, Popular Culture in a Globalized World](http://www.google.ca/url?sa=t&ct=res&cd=7&url=http%3A%2F%2Fwww.douglas-mcintyre.com%2Fbook_details.asp%3Fb%3D886&ei=-OrqRY36NImKgQLs3qziCQ&usg=__ozoe9c0IdIoqsjeeCLO23YHbDDo=&sig2=4G9pbBo-2suPRisM41X6Gw) by Peter Grant and Chris Wood. The theme of the book is the breaking down of trade and cultural barriers by commerce, including but not exclusively online commerce, and the attempts by smaller countries to preserve and enhance their own cultural output in the face of this challenge. They make a convincing case that a state-driven "cultural toolkit" including tools such as public broadcasting, quotas, subsidies, and more have been essential in helping a diversity of culture to survive and even, on occasion, thrive. 




Needless to say, Anderson does not even begin to address issues of international cultural diversity beyond the fondness of online teenagers for Japanese anime films. Sitting in San Francisco, he does not seem to even notice the fact that there is a distinction to be made between American cultural consumption and that in other parts of the world. I wish I thought he had even heard of Grant and Wood, but they come from Canada so I would guess that he hasn't. [Google](http://www.google.ca/search?hl=en&client=firefox-a&rls=org.mozilla%3Aen-US%3Aofficial&hs=OYD&q=%22long+tail%22+%22blockbusters+and+trade+wars%22&btnG=Search&meta=) tells me that the only page outside this little corner of the Internet that mentions both "long tail" and "blockbusters and trade wars" is a [bibliography page](http://thinkubator.ccsp.sfu.ca/CMNS371/ToC) for a course on the Structure of the Book Publishing Industry in Canada from Simon Fraser University in Vancouver. The ability of online vendors to cross borders is a double-edged sword when it comes to diversity. The ability to keep diversity in One Big Virtual Tent will depend to a large extent on the ability of governments to regulate portions of that tent.




There is one scenario in which the Long Tail does lead to an increase in diversity compared to the physical world, which is the scenario of the Digital Vice (I've renamed it since Chapter 1). The variety of physical stores that unevenly drive an uneven amount of uneven variety may be replaced by a combination of homogeneous big-box stores that sell mainly best-sellers and online stores that sell best-sellers and everything else. In such a world, there is no doubt that the niche purchases will take place online, so that the online world will represent a Long Tail compared to the physical world. But it's a grim outcome nonetheless.




The second question here is, what about the Long Tail of production represented by YouTube, Facebook, MySpace, Flickr, and the world of blogs and Wikipedia? To some extent I tackled this in the discussion of [Chapter 5](http://whimsley.typepad.com/whimsley/2007/02/the_new_produce.html). There are, I would argue, two things going on here, neither of which is Long Tail. One is the moving online of social conversations, play, and pastimes. Writing a diary online does not make it more "production" than writing a diary at home. The shift online loosens some ties and builds others. We tend to end up with (as Yochai Benkler points out in The Wealth of Networks) a looser but wider set of connections than in the physical world - we inhabit networks rather than communities, with different networks for different parts of our lives. Again, Anderson has eyes only for the building of online networks, not the loss of those other contacts that they replace. He repeatedly welcomes the online world in terms of its potential for a democratic future, but such a future is far from assured. To take one example, while the Internet is a great source of information for those who oppose the US war in Iraq, it has failed to coalesce into a significant political movement in the way that opposition to Vietnam did. The opposition to globalization that crystallized around 1999 did so at a physical place (Seattle): the effects of geography are strong and not easily replaced. While the Internet may provide new opportunities for political networking, to the extent that it replaces physical world actions it will not promote a broadening of democracy.




The most interesting and promising aspect of Internet technology is the large-scale collaborative efforts represented by the peer production models of Wikipedia, open-source software, SETI@home and others. These are remarkable, although again they tend to be operations that replace Many Small Tents by One Big Tent - there are fewer of them, but each one is bigger - than in the physical world. The endless comparisons of Encyclopedia Britannica to Wikipedia are somewhat misleading, because it again neglects the complementary physical books (specialist reference material that doesn't get into Britannica) that do not exist in the online world. Is there a big online reference for birdwatchers? I'm not sure, but my guess is that the ease of use of Wikipedia will make it the equivalent of many offline reference works, rather than a single general-purpose encyclopedia. In the offline world, there is no longer a need for Small Tent production - just put your material into the One Big Tent. Again, does this represent greater variety? In some senses yes, in some senses no.




So if there is a single image I'd use instead of the Long Tail, it's the One Big Virtual Tent. It's a tent that holds more than any of the Many Small Tents of the physical world, but which does not guarantee an overall increase in variety. And if you're going to build One Big Virtual Tent, the chances are you won't be building it from an out of the way place - to that extent, the revenue from the homogeneous variety of the online world is going to be finding its way to Silicon Valley rather than to your local community.


		
