---
author: Tom Slee
categories:
- blog archive
date: 2013-02-03 13:30:52
title: Update
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

A few updates after my "self-assessment" post.




First, I've received a dozen or so really helpful and constructive emails from a number of people. It's been good for the ego, and it's definitely given me encouragement to keep at this for a while yet. Sincere thanks to those who wrote (I think I've got back to everyone, but forgive me if I missed one or two). Also, thanks to Henry and Brad for the free labour on their blogs.




Second: I'm in the middle of  moving the blog from here to a shiny new installation at tomslee.net (which has been a stub of a site for a few years). I'll post here when that's done.




Third: in the days after that last post I received one invitation to speak at a conference, one acceptance of a talk at a second, and an invitation to write a multi-book review. Whining in public seems like a good way to go.




Finally: for those looking for No One Makes You, the publisher has this to say:




In the US: the book is available new at [B&N](http://www.barnesandnoble.com/w/no-one-makes-you-shop-at-wal-mart-tom-slee/1007693583?ean=9781897071069) (though it displays an old cover we assure you it is the correct edition). Or, you can contact our office directly (info (at) btlbooks.com or 1-800-718-7201) and we’ll ship you a copy anywhere within North America.




Purchasers in the UK and Europe can order new copies directly through our UK distributor, [Central Books](http://www.centralbooks.co.uk/acatalog/Online_Catalogue_Between_The_Lines__Canada___GBM__1_167.html#a189707106X) (and support an independent distributor of books and magazines).




An ebook edition is being worked on and should soon be available. If you would like to be notified when it is available, please contact our office info (at) btlbooks.com or 1-800-718-7201. Thanks for your interest in _No One Makes You Shop at Wal-Mart_.




I'll post that somewhere permanent once the site has moved.




So 2013 look pretty good. Now I just need to actually write something.


		
