---
author: Tom Slee
categories:
- blog archive
date: 2009-01-29 19:49:40
title: "SYS-CON Media Redux: You Couldn't Make This Stuff Up"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Here is how I was going to start this post:

Do you have fifteen minutes or so? Then relax and, if you don't mind a few f-words, enjoy the hilarity of a supposed media company shooting itself in the foot. Then the other foot. Then going so far beyond shooting itself in the foot you won't believe it.  


But, while that's one way to look at it, there is also the possibility that this is a tragedy. That the state of the world is so grim that these poor hapless people are driven to extremes of apparent stupidity. What could be going on in their lives to reduce them to this? Do they have landlords demanding the rent by tomorrow or they will be out on the street? Or what? Because, really, there is something here that is undeniably pathetic. 

But enough of the teaser. On to the action. A couple of weeks ago I posted about [my own unpleasant experience](http://whimsley.typepad.com/whimsley/2009/01/syscon-media-is-an-appalling-and-shameless-outfit-avoid-it.html) with SYS-CON media. I already knew about, but did not mention, the LinuxWorld fiasco there, because it didn't seem fair. But that's for later.

Yesterday a comment on that post led me to Jame-Ane Ervin's blog, where [she describes](http://jameane.wordpress.com/2009/01/28/how-to-lose-business-and-friends-brought-to-you-by-sys-con-media/) a run-in with the CEO of SYS-CON. In short, as an advertiser on SYS-CON she offered some suggestions, in an abrupt but not impolite way, on how they could improve what they do. And she asked to be removed from their site. According to Jame Ervin (whom I have never met) she got a reply including these words from SYS-CON CEO Fuat Kircaali:

Who the fuck you think you are, lady? Are you fucking out of your mind?




You are certainly mixing SYS-CON media with some other company. The
reason you heard from the CEO of the “most powerful” tech media company
in North America today is because he could not believe your email, out
of more than 4,000 contacts who received the same email, you had to be
the only bitch with a big fucking mouth.

Now it did occur to me that this was so unbelievable, so incomprehensibly over the top, that it was a fake. I mean, I don't know Jame Ervin. It could be a hoax, right? She could have said something unbelievably offensive to Mr. Kircaali to prompt this outburst? The world is a pretty damn strange place sometimes, right?

But today I see that SYS-CON have actually posted, on their own site, [the entire correspondence](http://wireless.sys-con.com/node/823476), to explain their response. So go read it if you are interested. Did Jame Ervin behave outrageously? She did not. The entire correspondence just makes the Kircaali email more jaw-droppingly offensive than it already seemed.

And just in case you thought this was all, SYS-CON also posted [an article about the affair](http://web2.sys-con.com/node/824052). Go ahead, read it. I'll wait here.

Done? Good. I think my favourite line is this:

Well, reporters use the word "bitch" casually these days. Last week, there was a headline published [here](http://virtualization.sys-con.com/node/808918), announcing the new Yahoo CEO as "[Tough Brazen Bitch Takes Over Yahoo](http://virtualization.sys-con.com/node/808918)," but I know Carol Bartz and this crackpot marketing woman is no Carol Bartz.

The linked-to headline is, of course, a SYS-CON one.

Now maybe I shouldn't be joking about something as offensive and aggressive as these insults. But really, the SYS-CON people can surely not be in a position to hurt Ms. Ervin professionally, and I trust they live miles away, so I'm assuming the offense - unpleasant as it is - carries no real threat with it. In which case it comes across as being simply delusional.

And now back to the beginning, where I mentioned LinuxWorld. A technical magazine run by volunteer editors, the [entire editorial board resigned](http://www.groklaw.net/articlebasic.php?story=20050516140036121) a couple of years ago in response to a complete lack of editorial control and in the wake of a scandal involving personal attacks written by a SYS-CON writer. When [Dana Blankenhorn wrote about this](http://mooreslore.corante.com/archives/2005/05/14/a_publishers_ethics.php) SYS-CON responded by, you guessed it, publicly having a go at Blankenhorn. Of course, being SYS-CON, their article is posted across all their publications, including the unbelievable Yacht and Charters Magazine: see [here](http://www.yachtchartersmagazine.com/node/668907?page=1), calling him a "crackpot" (the same word they used for Ms. Ervin) and poking fun at Mr Blankenhorn's possible joblessness.

From what it looks like, he has been in the business for 25 years and
can not find a job, and because of that he hates the company (SYS-CON) and its
founder.

Is this over now? Part of me hopes so. But I admit that another part of me can't wait to see what these people say next. You really couldn't make this stuff up, could you?


		
