---
author: Tom Slee
categories:
- blog archive
date: 2009-01-26 11:04:02
title: "Mr. Amazon's Bookshop: The Differ"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[This is the sixth instalment of Mr. Amazon's Bookshop. A list of all instalments is [here](http://whimsley.typepad.com/whimsley/2008/12/mr-amazons-bookshop.html); the previous instalment is [here](http://whimsley.typepad.com/whimsley/2009/01/mr-amazons-bookshop-doubts-about-amazon.html).]

  


I rocketed over to my stables at the crack of noon and cleaned up the old difference engine, or _differ_ as we enthusiasts call it. My friend Mr. Babbage, you will recall, had told me that Mr. Amazon had a new trick - instead of going to Mr. Amazon's Bookshop, one could use a difference engine to ask him as many questions as you like. I determined to use my differ to interrogate Amazon and better understand how his intriguing operation works.

  


I had to chase out a few voles and a cat that had set up house in among the levers and pistons, and it was nearly dinner time before I fired up the bellows and the great machine began to hum. It had been some while since I last set it going and the smell of burning dust was atrocious. But finally I was able to start communing with it, and I readied my questions.

  
My first query to Mr. Amazon's service was a simple one, and harked back to my earliest visit. "If I tell you I like _Special Topics in Calamity Physics_, what books would you recommend?"

  


I twisted and turned the knobs until the instructions were in place, and then pulled on the master lever to set the machine to work. Steam hissed, a piercing high-pitched whine drilled at my ear drums, and for a moment I thought the whole thing was going to explode. What could be going on? I was sure I had the instructions right. I pulled harder on the lever, hoping to blow past the obstruction, but to no use. The temperature reading was creeping dangerously high and I cast about for what was wrong. Finally I caught sight of a large beetle stuck in one of the outlet valves, obstructing the flow of air. I pulled at the release lever, shutting down the process, and watched in relief as the temperature lowered.  
  
Once I had cleaned out the valves, I took a swig from the sherry bottle and pulled the master lever again. "If I tell you I like _Special Topics in Calamity Physics_, what books would you recommend?" And this time, after a few scraping noises, the output pointers began to swing. A short while deciphering and I had my answer:

_Absurdistan_ by Gary Shteyngart  
_Suite Francaise_ by Irene Nemirovsky  
_The Yiddish Policeman's Union_ by Michael Chabon  
_The Brief Wondrous Life of Oscar Wao_ by Junot Diaz  
... and a handful of others.

  
I was thrilled. I stared at the list, entranced, until a thought crawled into my awareness. Here, it said, was the link between Mr. Amazon's Bookshop and what I think of as a real bookshop.  
  
Mr. Amazon's is not a bookshop. It is closer to the truth to say it is a mechanism, a differ if you like, that we each use to generate our own personal bookshop, with shelves and all, by the questions we ask of its proprietor. I had accused Mr. Amazon of not having shelves, but here was a set of books grouped together as I looked at _Special Topics..._ Surely that is close enough to a shelf.

  
I chose one of the ten recommendations at random by the usual method of throwing a barnyard cat at the wall and counting the number of squeals it emitted. The cat squealed twice to indicate _The Yiddish Policeman's Union_ (occasionally the cat does not scream, so the counting starts at zero). and I sent up my second question to Mr. Amazon. "If I tell you I like _The Yiddish Policeman's Union_, what books would you recommend?" A moment later, back came the answer:  
_The Amazing Adventures of Cavalier and Clay_ (also by Michael Ch
abon)  
_Gentlemen of the Road_ by, you guessed it, Michael Chabon.  
_On Chesil Beach_ by Ian McEwan  
_The Brief Wondrous Life of Oscar Wao_ by Junot Diaz  
... and a handful of others.

  
The shelf is longer, I muttered. Quickly I flung the cat again to select a book from the list (_Falling Man_, by Don DeLillo) and sent off the next query.

_The Yiddish Policeman's Union_ by Michael Chabon  
_Divisadero_ by Michael Ondaatje  
_Tree of Smoke_ by Denis Johnson  
_The Brief Wondrous Life of Oscar Wao_ by Junot Diaz  
... and a handful of others.

  
This could go on indefinitely, I realised. There is no point in simply asking over and over again for recommended books. Sooner or later people stop browsing and either buy a book or leave the shop. I decided to cap the number of requests at a random number (poor cat) between 1 and 20 - 12 on this occasion - and then listed in my notebook each of the dozen books I had picked from among the recommendations. Here is that list:  
  
_Special Topics in Calamity Physics  
The Yiddish Policemen's Union: A Novel (P.S.)  
Falling Man: A Novel  
Tree of Smoke: A Novel  
Bridge of Sighs: A Novel (Vintage Contemporaries)  
The Story of Edgar Sawtelle: A Novel (Oprah Book Club #62)  
The Art of Racing in the Rain  
The Beach House  
Chasing Harry Winston: A Novel  
Celebutantes  
Remember Me?  
Love the One You're With_  
  
That, I decided, looked like one visit to Mr. Amazon's shop. Each book selected from the list was one I had "picked up" and skimmed (at least those parts Mr. Amazon lets me see). Moving along shelves, picking books up that are not too far from the place you stand. There was an undeniable similarity, albeit a pale imitation of the casual, unpredictable and whimsical act of browsing in what I still thought of as a "real" bookshop.  


  


I decided to simulate a second visit. I know Mr. Amazon would have a few recommendations waiting for me, based on my previous visits, so I cat-picked one from the list of books I had "picked up" (_Falling Man: A Novel_) and generated a second list of books:  
  
_Falling Man: A Novel  
Divisadero (Vintage International)  
The Yiddish Policemen's Union: A Novel (P.S.)  
Falling Man: A Novel  
The Brief Wondrous Life of Oscar Wao  
Tree of Smoke: A Novel  
Legacy of Ashes: The History of the CIA  
The Post-American World  
The Second World: Empires and Influence in the New Global Order  
The New Asian Hemisphere: The Irresistible Shift of Global Power to the East  
The Return of History and the End of Dreams  
Dangerous Nation: America's Place in the World, from it's Earliest Days to the Dawn of the 20th Century  
Power, Faith, and Fantasy: America in the Middle East: 1776 to the Present  
Six Days of War: June 1967 and the Making of the Modern Middle East  
The Accidental Empire: Israel and the Birth of the Settlements, 1967-1977  
Six Days of War: June 1967 and the Making of the Modern Middle East_  
_The Arab-Israeli Wars: War and Peace in the Middle East_  
  
Some books, I noticed, were appearing again and again. Who on earth, I wondered, is this _Oscar Wao_ whose brief wondrous life is appearing in all the lists I generate? And what is this _Falling Man_? I had heard of neither, yet Mr. Amazon seemed to be pushing them at me insistently. And how had I got from a literary mystery to what looked like nonfiction books about the near Orient? There was so much to think about in these lists that I copied the second list into my notebook and headed to my library to think, telling Google to bring me some smoked kippers, Turkish coffee, and the latest copy of the _Literary Review_. He bowed obsequiously, but not quickly enough to hide the supercilious smirk he sometimes gives, as if he knows not only what problems I seek to solve but the answers too. But this quest was becoming my own, and I did not want his help.  
  
It was Jennie the one-legged housekeeper who climbed the worn stone steps of the western wing to my library in the turret, bringing the kippers, a wet copy of the _Literary Review_, and a half-empty cup of luke-warm coffee. It is most inconvenient that she is crippled and I shall have to do something about it - perhaps reassign her to the kitchen where she does not have to move about so much? But this is not the time to indulge myself in such sentimental nonsense, I told myself. My warm heart and generous nature is so well known locally that I fear they are often taken advantage of. I must make myself of sterner stuff. So I dismissed Jennie and turned to the _Review_.  
  
First, those two books. It turns out they were not so obscure as I thought. _Falling Man_ is written by that impetuous youngster Don DeLillo, author of _Underworld_. And _Oscar Wao_ won something called a Pulitzer Prize, that is apparently worthy of note in the provinces. Amazon, I was slightly chuffed to realise, was showing me books that were new to me, but - despite what I am often told is my encyclopedic knowledge - far from obscure. I could probably pick up either of those volumes at Words Worth or at Heather's Big House O'Books.  
  
And how did we get from Special Topics to The Arab Israeli Wars? Via _The Falling Man_, it seems. That book is a literary novel (and so linked to Special Topics) and yet is concerned with terrorism, and so leads us into other books about warfare and terrorism. Not too far-fetched, I thought, and yet ingenious.  
  
As I stretched in front of the library fire, the warmth and my exhertions combined to induce a sluggish drowsiness. I drifted in and out of a doze, my mind filled with pictures of endless lists of books, on topics leaping from terrorism to gourmet cooking to accounting in a few bounds. How could I impose some kind of order on this profligacy? What can one learn from this spewing of titles? How does Mr. Amazon impose order? He must, I was convinced, have some mechanism for governing the labours of those poor, enslaved mole-people deep in his basement-factories.  
  
Just before my dozing turned to sleep, I remembered one nugget of information that had come back along with the title in response to my requests - the SalesRank. This, I knew, is Mr. Amazon's seller list. But unlike a real best seller list, it does not stop at a mere ten or so items. Instead, as seems typical of Mr. Amazon's industrious nature, it goes on and on into the hundreds, the thousands, the hundreds of thousands, each book with its rank. That, I decided, would be the starting point for my next investigation.


		
