---
author: Tom Slee
categories:
- blog archive
date: 2006-04-01 19:55:13
title: 'Chain reaction: UK Bookstores'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

In a story that will have a familiar ring to it for anyone from Canada, the Grauniad reports on HMV (aka Waterstone's) being given the go ahead to take over Ottakars: another example of how free markets fail to preserve diversity once economies of scale kick in.




Link: [Chain reaction from Guardian Unlimited: Culture Vulture](http://blogs.guardian.co.uk/culturevulture/archives/2006/03/30/chain_reaction.html#more).


<blockquote>"Waterstone's choose about 5,000 books a year and promote them so that they sell tremendously - at the expense of other books," he said. "If a book isn't taken up within a month, it is replaced. Ottakar's, on the other hand, gives books more time to take off. There are two categories of books - the tortoises and the hares. If this deal goes ahead, we will end up with all hares and no tortoises." And it's not just authors who are apprehensive; figures from across the industry have voiced their concerns. Just last week I spoke to a representative from the Booksellers' Association, who told me that in his opinion, an Ottakar's takeover would have a devastating effect on publishers' chances of introducing debut novelists - or even the lesser-known works of popular authors - to new readers.

> 
> 

> 
> And the Ottakar's story is just the visible face of what is happening to independent bookshops across the UK. Although Ottakar's is a chain, it shares many of the strengths and weaknesses of the independents. Its branches are locally run by staff who are sensitive to the needs of their local communities and choose their stock accordingly (in contrast with Waterstone's, which nowadays operates a policy of centralised buying), but it has neither the revenue nor the advertising clout to compete on a pricing basis with the bigger shops. As a result, Ottakar's have seen their sales and profits falling, making a buyout ever more likely.
> 
> </blockquote>

  

		
