---
author: Tom Slee
categories:
- blog archive
date: 2006-01-28 17:35:41
title: The Evolution of Top Incomes
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Yet more from Mark Thoma, who seems to collect interesting information like I collect collecty things. He posts a series of graphs from the latest Piketty and Saez paper on trends in incomes -- in this case particularly incomes at the very top. In short, the income share of the top 1% took a slight dip between 2000 and 2002 but it looks like a brief post-dot-com interruption in the general trend of increasing inequality starting in the 1970s. 

<blockquote>This paper summarizes the
main findings of the recent studies that have constructed top income and wealth
shares series over the century for a number of countries using tax statistics.
Most countries experience a dramatic drop in top income shares in the first part
of the century due to a precipitous drop in large wealth holdings during the
wars and depression shocks. Top income shares do not recover in the immediate
post war decades. However, over the last 30 years, top income shares have
increased substantially in English speaking countries but not at all in
continental Europe countries or Japan. This increase is due to an unprecedented
surge in top wage incomes starting in the 1970s and accelerating in the 1990s.
> 
> </blockquote>

Oddly, the trend seems to be limited to English speaking countries. Why on earth would that be? There are some speculations both at Thoma's Economist's View and at Brad DeLong's site.




Link: [Economist's View: The Evolution of Top Incomes](http://economistsview.typepad.com/economistsview/2006/01/the_evolution_o.html).


		
