---
author: Tom Slee
categories:
- blog archive
date: 2007-11-09 13:31:46
title: No More Poppies
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I'm not wearing a Poppy this year. 




There are [two ways](http://arts.uwaterloo.ca/~kwesthue/rememday.htm) of thinking about the Poppy. One is the Wilfred Owen way and one is the John McRae way. They are both familiar.




Here is Owen:

<blockquote>If you could hear, at every jolt, the blood  
Come gargling from the froth-corrupted lungs,  
Obscene as cancer, bitter as the cud  
Of vile, incurable sores on innocent tongues,  
My friend, you would not tell with such high zest  
To children ardent for some desperate glory,  
The old Lie; Dulce et Decorum est  
Pro patria mori
> 
> </blockquote>

And here is McRae

<blockquote>
Take up our quarrel with the foe:  

To you from failing hands we throw  

The torch; be yours to hold it high.  

If ye break faith with us who die  

We shall not sleep, though poppies grow  

In Flanders fields.
> 
> </blockquote>

McRae says that war is tragic and heroic; Owen says it is tragic and futile. McRae demands that the death of soldiers
be given meaning by continuing the war that caused their death. Owen
demands that we admit the meaninglessness and criminality of those deaths and prevent further ones.




In Canada at least, the Poppy is now inextricably tangled with the McRae vision of soldiers and warfare. Here is the Canadian Legion's [site](http://www.legion.ca/asp/docs/rempoppy/allabout_e.asp):

<blockquote>His poem speaks of Flanders fields, but the subject is universal – the
fear of the dead that they will be forgotten, that their death will
have been in vain. Remembrance, as symbolized by the Poppy, is our eternal answer which belies that fear.
> 
> </blockquote>

Now Canadian soldiers are fighting in Afghanistan while British soldiers fight in Iraq. The Poppy asks that we give meaning to the death of Canadian soldiers in Afghanistan by "Tak[ing] up our quarrel with the foe"; by pursuing the war. The Poppy has been taken over, in recent years, by those who are using it to perpetuate "The old Lie". Jingoistic patriotism has got its grubby hands on what was once a fine symbol.





Not everyone who wears a poppy means these things by it, of course. Many do as a recognition of the sacrifice of relatives in the second world war. I have no problem with that. It would be much simpler to reject the Poppy if it weren't for the Second
World War. It was, obviously, the essential war that needed to be
fought, and which did have undeniable meaning. But the Second World War
was not the template for wars since then; it was the exception not the
rule.




For me, I can't see how I can wear a Poppy without helping to promote the idea that Canadian soldiers are fighting for just and noble causes. And I can't do that.




We do have an old Alliance for Non-Violent Action button with a poppy and the words "To Remember is to End All War". I'll wear that instead.


		
