---
author: Tom Slee
categories:
- blog archive
date: 2007-03-23 21:45:06
title: The Long Tail 11.2 - Living in a Niche Culture (2)
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is another part of my critical reader's companion to _The Long Tail_, and it discusses the second half of Chapter 11 - Living in a Niche Culture. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html).

* * *

The Rise of Massively Parallel Culture [182-185] reveals yet another of Chris Anderson's weaknesses: as Editor of Wired Magazine in San Francisco he is surrounded by "geek friends" [182].




The Long Tail worldview is digital-optimist-libertarian, is characteristic of Silicon Valley - a culture called [Cyberselfish](http://www.cyberselfish.com/) in the book of the same name by Wired contributor Pauline Borsook. As The New York Times [summarizes](http://query.nytimes.com/gst/fullpage.html?res=9E02E0DD133AF936A15754C0A9669C8B63&sec=&spon=&pagewanted=2):

<blockquote>Ms. Borsook contends that many of the favorite arguments of technolibertarians come from ''bionomics'' -- that is, they like to use metaphors drawn from biology to explain economic behavior and endorse a decentralized free-market system. Reduced to a bumper slogan, Ms. Borsook writes, bionomics states that ''the economy is a rain forest''; in other words, it suggests that ''no one can manage or engineer a rain forest, and rain forests are happiest when they are left alone to evolve, which will then benefit all the happy monkeys, pretty butterflies and funny tapirs that live in them.''
> 
> </blockquote>

Cyberselfish is a few years old now (but a good read nonetheless), and bionomics is a bit last-generation these days, but judging from The Long Tail not much has changed. The outlook is self-involved and, to be frank, self-important. Chris Anderson looks out from Silicon Valley at the rest of the world and doesn't know a whole lot about it - and he doesn't think it important to know about it. When he quotes Karl Marx [62] he doesn't actually quote Marx, he quotes a [report](http://www.viadigitalis.org/wordpress/wp-content/uploads/proamrevolutionfinal.pdf) on digital technology by think tank Demos. The Long Tail is a book on culture with no reference to life outside the USA (except for anime videos). Chris Anderson sees no reason to pay attention to economists or social scientists (not a single economist who deals in the economics of information apart from his Berkeley neighbour Hal Varian, for example - no Stiglitz or Akerlof here), but calls essayist [Clay Shirky](http://en.wikipedia.org/wiki/Clay_Shirky) "a prominent thinker". He quotes his intellectual stablemates Richard Posner, Virginia Postrel, and George Gilder, and says James Surowiecki's The Wisdom of Crowds - a quick read, but not deep - "needs to be read". There's nothing wrong with quoting these people, but the contrast between his references to a certain kind of thinker from a certain kind of place and his complete neglect of so many other strands of thought is stark, especially in a book that does not claim any distinct political outlook. 




This narrowness of vision is surely why he calls his own work "research" even when he is discovering things well known by many others. He is an intellectual imperialist: Columbus "discovering" America all over again - thinkers from outside his own intellectual neighbourhood just don't count. The people who endorse the book are of course, as already pointed out, a coterie of Silicon Valley digerati (and the aforementioned Mr. Surowiecki).




The outlook of the author and the audience for the book come through in the terminology he uses. "Massively parallel" is a computing term - elsewhere he's all, like, "impedance mismatch" and "fractal" and "network economics" and "meme" - the buzzwords of computer engineers and the Santa Fe Institute.




Given this outlook, it is not surprising that it takes Mr. Anderson just a couple of pages of sketchy story telling - references to a bunch of Internet "viral memes" such as Dancing Babies and the truly disgusting "goatse" picture - before he can conclude that the online world - his world - is far more diverse than the world outside his valley. "In short, we're seeing a shift from mass culture to massively parallel culture." [184] He claims that, while the diversity of humanity "has always been true, but it's only now something that we can act on. The resulting rise of niche culture will reshape the social landscape. People are re-forming into thousands of cultural tribes of interest, connected less by geographic proximity and workplace chatter than by shared interests." [184] The narrowness of his own intellectual horizons, and the proportion of his influences that hail from California, suggest that this is less true than he would like to think.




Yochai Benkler is an interesting writer who Anderson pays attention to, although not in The Long Tail. Benkler has a much better picture of the way that the online shift is changing our culture, and what happens when "people shift their attention online" [181]. The picture he gives (Chapter 10 of [The Wealth of Networks](http://www.benkler.org/wealth_of_networks/index.php/Download_PDFs_of_the_book)) documents that the online world is not one of "virtual communities" heralded by the optimists, and is not one of isolation and alienation feared by the pessimists. Instead, he argues that users "increase their connections with preexisting relations" [363] and leads to "weak ties" of networked individuals (rather than the stronger ties implied by the word "community") in the new relationships that we form. There is little indication of "tribes of interest", with the close ties that the phrase suggests, emerging online.




The section ends with a rare quote from an intellectual outside Anderson's usual sphere of influence: "In 1958, Raymond williams, the Marxist sociologist, wrote in Culture and Society: 'There are no masses; there are only ways of seeing people as masses.' He was more right than he knew." [185] Now maybe he means something other than the way I read this, but the sentence strikes me as remarkably arrogant. To assert that Williams, a first-rank thinker and hugely influential in our understanding of the ways that culture and society influence each other, was "more right than he knew" is not only patronizing, but patronizing in an innapropriate, almost embarrassing way given the relative intellectual standing of the two.




If the New Fits [185-189] is about blogs - a truly interesting development (especially for us bloggers). He focuses on two influential blogs (from the short head?): [Daily Kos](http://www.dailykos.com/) and [Instapundit](http://www.instapundit.com/) and points out that they are influential. As I argued in the notes to Chapter 5, he will get no argument from me that the development of social software as a platform for both publishing and conversation, is an important development - but it ain't Long Tail.




A Million Little Pieces [189-191] starts off by asking if a "fragmented culture [is] better or worse culture"? [189], and raises the question of whether the digital world may be a place where "you need not come across topics and view that you have not sought out." [189] - creating a polarized world of insular thought where, as he quotes Christine Rosen, "we are, ironically, finding it increasingly difficult to appreciate genuine individuality" [190]. Anderson asks "Is Rosen right? I suspect not" [190] and then goes on a little idealistic detour that wanders between a paean to the openness and diversity of the online world. It is easy to agree with the statement that "Fundamentally, a society that asks questions and has the power to answer them is a healthier society than one that simply accepts what it's told from a narrow range of experts and institutions" [191], but less easy to see what it has to do with the Long Tail - a tale where our access to variety is channelled through a small number of aggregators whose recommendation systems are private and hidden - a narrow range of (machine-based) experts and institutions indeed.




His optimism is engaging: "I suspect that over time the power of human curiosity combined with near infinite access to information will tend to make most people more open-minded, not less" [191]. To dispute this seems Luddite in the colloquial sense - actual Luddites being admirable, or at lease understandable, and Scrooge-like. But one can see opportunities in the Internet - real innovation, of real novelty, and real social changes - without subscribing to The Long Tail's particular muddled vision of commercial giants and social software platforms.


		
