---
author: Tom Slee
categories:
- blog archive
date: 2014-11-22 05:00:00
tags:
- uber
title: Why Canada should de-activate Uber
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				



_A long post collecting together a number of arguments and resources about Uber and why it doesn't belong in Canada. If you want to print it off, [here](http://tomslee.net/wordpress/wp-content/uploads/2014/11/2014-11_uber_toronto1.pdf) is a PDF._

An updated version of this page is maintained [here](http://tomslee.net/why-canada-should-de-activate-uber), which you can access through the menu above.


In September, Uber [introduced](http://www.thestar.com/business/2014/09/08/uber_introduces_new_ridesharing_service_uberx_to_toronto_mississauga.html) its UberX service in Toronto as part of a broad expansion across Canada (among other countries), and the City of Toronto is now [seeking a court injunction](http://wx.toronto.ca/inter/it/newsrel.nsf/7017df2f20edbe2885256619004e428e/43b5c208afe6f41f85257d940066aa0c?OpenDocument) to stop the company. Back in December 2012 the company was [chased out](http://business.financialpost.com/2012/12/06/uber-toronto-facing-new-licensing-charges-related-to-taxi-business/?__lsa=61ea-1a68) of the city, but now [some](http://www.theglobeandmail.com/globe-debate/the-ubers-are-destined-to-win-the-taxi-wars/article21658996/#dashboard/follows/) [journalists](http://www.theglobeandmail.com/news/toronto/instead-of-blocking-progress-toronto-should-encourage-uber/article21664545/), [business professors](http://www.theglobeandmail.com/news/toronto/toronto-seeks-injunction-to-stop-uber-taxi-service/article21638796/), and even [the mayor](http://www.cbc.ca/news/canada/toronto/uber-is-here-to-stay-toronto-mayor-elect-john-tory-says-1.2840295) (not that one) think it's time to disrupt the taxi industry, ignore the city [licensing and standards](http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=69b5a83b82870410VgnVCM10000071d60f89RCRD) process and let Uber run its taxi alternatives.







You'd think, reading these articles, that customer service is the only issue at stake here. But there's more to it than that: the decision about Uber is also a decision about the kind of jobs we want to have, about accessibility, and about the kind of city in which we want to live. It's about us as consumers, but also us as citizens, us as Canadians, and us as employees.












## Uber is not "the future", it's "a future"






Contrary to the way some articles are written, we do have a choice here. A lot of the links above talk as if Uber were some kind of inevitable future ("The Ubers are destined to win the taxi wars"); here is an example from [Todd Hirsch](http://www.theglobeandmail.com/report-on-business/rob-commentary/rob-insight/taxi-trouble-disruptive-technology-claims-another-unadapting-victim/article21675184/#dashboard/follows/):


<blockquote>It's an economic tale told time and again. Camera film makers. Video stores. The music recording industry. Perhaps most famously, the Luddites – those textile labourers in 19th century England who protested against the introduction of mechanized looms by smashing them. Many of them failed to adapt to new, disruptive technologies and went extinct.

Next on the list may be the taxi industry…</blockquote>


Conflating Uber with the broad advance of technology is just wrong, and it's also exactly what Uber wants us to do. After all, if you're the future, who can argue against that? But thousands of new technology businesses start every year, and many of them fail. Groupon turned out not to be the future of shopping. Mayor John Tory [wants](http://globalnews.ca/news/1681159/is-john-tory-facing-an-uber-battle-at-city-hall/) to "sit down with the Ubers and the Hailos and others of the world", but Hailo has already folded its North American operations. Paris has [turned down](http://venturebeat.com/2014/10/16/paris-court-rules-uberpop-illegal-fines-company-as-uber-vows-to-fight/) UberPop, but it has Autolib', which may be the world's most successful electric-car sharing program. There are many roads to the future—many _innovative_ roads to the future—and the best of them don't involve Uber.

The Uber controversy is not just—or even mainly—a technology story, it's fundamentally a deregulation story; the story of a uniquely American fundamentalist free-market worldview being sold to us in the name of "car-sharing" and innovation.












## Two cheers for regulation






Uber CEO Travis Kalanick's says that his company is engaged in something like an election race in which


<blockquote>Uber is the candidate and [its opponent] is an asshole called Taxi. I'm not totally comfortable with it but we have to bring out the truth of how evil Taxi is.</blockquote>


Kalanick also [referred](http://blog.uber.com/davidplouffe) to "Our opponent – the Big Taxi cartel" when he hired former Obama strategist David Plouffe to run its political lobbying efforts.

It's worth reflecting for a moment on the fact that cities all around the world, with many different political and economic traditions, have decided independently that taxis need some regulation; and there is no "Big Taxi cartel" coordinating these decisions. Taxi firms are generally city-wide, at least until Uber itself came along.

Cities have had their own reasons for regulating taxis. As McGill University Law Professor Paul Stephen Dempsey [wrote](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2241306) in a 1996 paper, regulations typically include:


<blockquote>(1) limited entry (restricting the number of firms, and/or the ratio of taxis to population), usually under a standard of "public convenience and necessity," [PC&N] (2) just, reasonable, and non-discriminatory fares, (3) service standards (e.g., vehicular and driver safety standards, as well as a common carrier obligation of non-discriminatory service, 24-hour radio dispatch capability, and a minimum level of response time), and (4) financial responsibility standards (e.g., insurance).</blockquote>


It is not a coincidence that, all around the world, taxi regulation happens at the city level rather than at a national or provincial level. Different cities have different needs. The one-size-fits-all model that Uber wants to roll out treats Tokyo the same as London the same as Windsor, but as Dempsey (see link above) writes:


<blockquote>In the final analysis, the suitability of taxicab service and pricing is a peculiarly local issue, best tailored by local governments based on their unique populations, spatial densities, road congestion, air pollution, and airport and hotel traffic.</blockquote>


Meanwhile, for all its attempts to conjure up an underdog image, Uber has funding from ([among others](http://www.crunchbase.com/organization/uber)) Google, Jeff Bezos of Amazon, and Goldman Sachs.

It's also worth remembering that taxi deregulation has been tried and failed in many places. For example, Seattle deregulated in 1979 but [found](http://sfcda.org/CPUC/Seattle_DeReg.pdf) that "service quality declined and rates were often higher"; and [a 2004 US report](http://www.cga.ct.gov/2004/rpt/2004-R-0380.htm) noted that


<blockquote>…several studies, including a 1993 Price Waterhouse study, found that overall, in many cities that deregulated, the supply of taxicabs increased, fares increased, service quality declined and there were more trip refusals, lower vehicle quality, and aggressive solicitation of customers resulting from a higher supply of taxicabs.</blockquote>


So taxi regulation is imperfect, but the solution to that imperfection is not to walk away from it. Taxis are part of city infrastructure, like buildings, buses, and subways, and serve a valuable public service. Taxi regulation provides a way for the public and for our elected representatives to have a say in how the taxi industry works, so that (for example) [Toronto can demand](http://www.thestar.com/news/city_hall/2014/02/19/council_votes_to_overhaul_toronto_taxi_industry.html) that the entire taxi fleet must be wheelchair accessible, rolling in over the next decade, or London can introduce a [zero-emission Metrocab](http://www.newmetrocab.com/) to address environmental concerns. The taxi industry may be a flawed part of our democratic institutions, but the solution to flawed democratic institutions is more and better democracy, not the American rejection of government and of democracy's role in the economy.

Despite claims of technological inevitability, saying No to Uber is perfectly compatible with innovation and forward thinking. If Canadian cities such as Toronto do say No to Uber, they would be joining cities around the world such as [Berlin](http://www.redherring.com/startups/berlin-pits-ubers-inevitable-ascent/), [Seoul](http://www.cnet.com/news/seoul-korea-says-uber-is-illegal-promises-to-take-stern-action/), [Madrid](http://novobrief.com/spain-trying-push-uber-country-drivers-will-face-fines-e18000/), and [Paris](http://www.reuters.com/article/2014/10/16/us-france-uber-idUSKCN0I527M20141016) in refusing to roll over and hand the responsibility for their taxi service to Silicon Valley.












## Uber corporate culture






Digital platforms are governed by network effects, which is why Uber's massive funding rounds (having _raised_ $1.5 Billion, they are now [looking](http://blogs.wsj.com/digits/2014/11/20/ubers-massive-fundraising-campaign-forges-ahead-amid-controversy/) to raise another $1 Billion) and rapid global expansion are so important to the company's future. They and their investors know it's a winner-take-all game; that's why Uber CEO Travis Kalanick [admitted](http://www.vanityfair.com/business/2014/12/uber-travis-kalanick-controversy) this month that he undermined the fund-raising efforts of his main competitor, Lyft. The decision facing Canadian cities is not about permitting a smartphone app, it's about handing a large part of Toronto's taxi service over to Uber.

So what kind of company is Uber, that people want to put aside taxi regulation and hand control over to them?

It's a company in the middle of controversy, as executive Emil Michael muses about [digging up dirt on (female) journalists](http://www.buzzfeed.com/bensmith/uber-executive-suggests-digging-up-dirt-on-journalists) who criticize the company. It's a company that spies on its customers using what it calls its "God View" of company data [for party tricks](http://www.forbes.com/sites/kashmirhill/2014/10/03/god-view-uber-allegedly-stalked-users-for-party-goers-viewing-pleasure/) or for [blog posts](https://web.archive.org/web/20140827195715/http://blog.uber.com/2012/01/09/uberdata-san-franciscomics/). It's a company whose [top New York exec is being investigated](http://www.buzzfeed.com/johanabhuiyan/uber-is-investigating-its-top-new-york-executive-for-privacy) internally for tracking a female journalist without her consent. It's a company whose employees have [warned](http://www.modernluxury.com/san-francisco/story/uber-employees-warned-san-francisco-magazine-writer-executives-might-snoop-her) another female journalist that "company higher-ups might access my rider logs".

I emphasize "female journalist" here because the culture of the company is a big part of the problem. Do we want to hand over Toronto streets to a company whose CEO wisecracks about women on demand ("[Yeah, we call that Boob-er](http://pando.com/2014/02/27/we-call-that-boob-er-the-four-most-awful-things-travis-kalanick-said-in-his-gq-profile/)")? Which "[can and does](http://www.marketplace.org/topics/business/final-note/ubers-data-makes-creepy-point-about-company) track one-night stands" and posts a blog entry about the data called "Rides of Glory" (now removed)? Which, more damagingly, ran [a campaign in France](http://www.dailydot.com/business/uber-france-sexism/) (now also removed) called "Avions de Chasse" to pair Uber riders with "hot chick" drivers? As the company [posted](http://www.buzzfeed.com/charliewarzel/french-uber-bird-hunting-promotion-pairs-lyon-riders-with-a) on the English version of its website:


<blockquote>"Avions de chasse" is the French term for "fighter jets", but also the colloquial term to designate an incredibly hot chick. Lucky you! the world's most beautiful "Avions" are waiting for you on this app. Seat back, relax and let them take you on cloud 9!</blockquote>


This is a company that responded to a complaint by a female customer that she was driven 20 miles out of her way to an abandoned lot by saying it was an [inefficient route](http://valleywag.gawker.com/uber-calls-womans-20-mile-nightmare-abduction-an-ineff-1645819700).

It's also a company that [coaches Miami drivers how to circumvent laws](http://www.autoblog.com/2014/11/14/uber-coaching-airport-drivers-violate-rules/). It's a company that [ordered and cancelled](http://money.cnn.com/2014/08/11/technology/uber-fake-ride-requests-lyft/index.html) over 5,000 rides with its main competitor to interfere with their service. It's a company that sets out to [dupe newspapers with fake PR](http://www.laweekly.com/informer/2014/10/29/after-our-uber-expose-their-pr-team-tried-to-dupe-us), and which now talks of "[weaponizing facts](http://www.buzzfeed.com/johanabhuiyan/uber-sought-to-hire-opposition-researcher-to-weaponize-facts)" in its PR campaigns (this company really likes its military analogies). In short, it's a company that reflects the worst of the macho culture of some parts of the technology industry.

In among all the privacy problems, it is worth noting that Uber has one privacy policy for the US, but has [no Canadian privacy policy](http://www.thestar.com/business/2014/11/21/why_uber_has_a_canadian_privacy_problem.html). That's how much Uber is thinking, for all its massive funding base, about privacy issues for Canadian riders.












## Drive income: the Uber unicorn






What really appeals to people who have used Uber (and I am not one of them) is the smooth efficiency of the service, an efficiency that relies on drivers to be in place, ready to take you where you want to go.

According to Uber, efficiency and affordable pricing is combined with fantastic pay for drivers. In May 2014 the company posted a claim [on its website](http://blog.uber.com/uberimpact) that the median uberX annual income is $90,766 in New York City and $74,191 in San Francisco. The claim was hailed (hah!) by Matt McFarland of the Washington Post with the headline _Uber's remarkable growth could end the era of poorly paid cab drivers_. Noting that "estimates of the typical cab driver's salary hover around $30,000", McFarland acknowledged that "Uber's numbers don't account for the costs a driver incurs to own and operate a vehicle. Still, the gap in compensation for providing similar services is astounding".

The claim is indeed astounding. How could Uber pay its drivers three times the pay of a taxi driver, charge riders less, and still be profitable? The initial explanation was that taxi medallion owners in many cities suck all the money out of the taxi system (see financial journalist Felix Salmon [here](http://blogs.reuters.com/felix-salmon/2013/12/11/why-cab-drivers-should-love-uber/) and [here](https://medium.com/@felixsalmon/the-economics-of-everyones-private-driver-464bfd730b38) for example).

I [took a look](http://tomslee.net/2014/06/uber-drivers-earning-90kyear-more-evidence-needed.html) at the claim when it was made and compared Uber's estimates to taxi reports from three different cities. It was clear that Uber was taking out about the same percentage of each dollar of fare from the system as do medallion owners (20% of the fare at the time, plus a $1 "safety fee" per ride), so there was no magic there after all. The company admitted that it was looking only at drivers who logged over 40 hours a week which, given that most drivers are working longer than they are actually "on the app" means that the average is highly selective of the top end of drivers. Finally, Uber massively underestimated the costs of gas, maintenance, insurance, and other expenses (such as tolls) that drivers incur (uberX drivers must drive their own cars).

Since then, the claim has become less and less plausible. Felix Salmon toned down his praise [here](https://medium.com/@felixsalmon/how-well-uberx-pays-part-2-cbc948eaeeaf). Seattle Uber drivers protests in [April](http://www.thestranger.com/seattle/uber-drivers-say-they-need-a-union/Content?oid=19281784) and [August](http://slog.thestranger.com/slog/archives/2014/08/29/uber-drivers-honking-their-horns-in-downtown-seattle-to-protest-pay-cut), San Francisco drivers protested low income in [May](http://time.com/92988/uberx-san-francisco-protest-uber/), Los Angeles drivers protested in [September](http://losangeles.cbslocal.com/2014/09/02/uber-defends-slashing-drivers-rates-amid-la-protest/), New York drivers protested in [September](http://www.buzzfeed.com/johanabhuiyan/uber-drivers-are-protesting) (Uber [backtracked](http://www.slate.com/blogs/moneybox/2014/09/12/uber_drivers_strike_they_protested_cheap_uberx_fares_uber_backed_down.html) over new rules it had introduced) and again in [October](http://www.dailymail.co.uk/news/article-2802430/uber-drivers-new-york-plan-strike-shut-phones-protest-treatment-company.html) along with [San Francisco and London](http://www.buzzfeed.com/johanabhuiyan/uber-drivers-protest-in-sf-and-la-while-drivers-in-ny-and-lo). Low income has been a consistent complaint, including on the active Uber driver forum [UberPeople](http://uberpeople.net/) and at [Reddit](http://www.reddit.com/r/uberdrivers/). Reports from individual Uber drivers failed to come near to the income figures that Uber claimed (for example [this](http://uberpeople.net/threads/fort-worth-30-hr-lies.4595/) report from Fort Worth (strong language!) or [this](http://www.businessinsider.com.au/uber-drivers-say-theyre-making-less-than-minimum-wage-2014-10) report or [this](http://bostinno.streetwise.co/2014/06/09/how-much-do-uberx-drivers-actually-make-per-hour/) report from Boston).

Meanwhile, Uber has been taking a bigger and bigger slice of the consumer dollar. The $1 per trip "[safety fee](http://mashable.com/2014/04/18/uber-adds-1-safe-rides-fee/)" was a start, then they started [charging](http://www.geekwire.com/2014/uber-now-charging-drivers-520-per-year-lease-smartphone/) drivers $10 per week for use of a smartphone, and more recently they [increased](http://www.forbes.com/sites/ellenhuet/2014/09/22/uber-now-taking-its-biggest-uberx-commission-ever-25-percent/) their commission for new drivers in San Francisco to 25% of the fare.

Finally, multiple rounds of fare cuts have put pressure on driver income. Uber insists that a greater number of rides per driver makes up for the price cuts, but drivers themselves [dispute](http://uberpeople.net/threads/real-statistics-price-drops-and-your-earnings.3009/) this claim and there are few numbers from Uber to back it up.

The $90,000 claims have been re-investigated in recent weeks by two of the most consistently informative journalists covering Uber. Johana Bhuiyan of Buzzfeed looked at eleven Uber drivers's pay slips [here](http://www.buzzfeed.com/johanabhuiyan/what-uber-drivers-really-make-according-to-their-pay-stubs); and Slate's Alison Griswold called the $90,000 driver [Uber's Unicorn](http://www.slate.com/articles/business/moneybox/2014/10/uber_driver_salary_the_ride_sharing_company_says_its_drivers_make_great.html), saying "In several months of reporting on Uber, I have yet to come across a single driver earning the equivalent of $90,766 a year." She asked Uber's Lane Kasselman to introduce her to one and concludes: "Last I heard, they’re still looking." Meanwhile, the New York Post [concludes](http://nypost.com/2014/11/02/ubers-claim-of-90k-average-pay-for-drivers-is-overestimated/) that "their take-home pay is closer to the average that yellow cabbies make."












## Rating systems and vulnerable drivers






Money is, of course, one of the main points of contention for many jobs, but Uber is not just another employer. In fact, it's not an employer at all: Uber drivers are "partners", self-employed entrepreneurs who choose to work on the platform. The model of "micro-entrepreneurs" who can choose when to work independently is what makes Uber part of the booming "sharing economy" along with others such as Airbnb. What seems at first like a light-weight and flexible model of work turns out, in Uber's hands, to be another way for the company to have its cake and eat it too.

Uber claims its drivers are not employees, but has been exerting more and more control over their behaviour.

Uber makes it easy for new drivers to join up: it publicizes what many drivers describe as unrealistic earnings to attract interest (see above) and encourages drivers to take out what amount to [subprime loans](http://valleywag.gawker.com/uber-and-its-shady-partners-are-pushing-drivers-into-su-1649936785) in order to buy a car. Then, of course, the driver has to put in long hours to pay off the purchase, and being kicked off the platform becomes even more of a threat.

Uber has taken advantage of the vulnerability of its drivers by imposing more and more strenuous rules. Driver acceptance rates (when the app assigns them to a customer) have to be up around 90% or you get a [notification](http://www.reddit.com/r/uberdrivers/comments/2mykji/my_reply_to_ubers_low_acceptance_rate_email/) to "Please improve your acceptance rate if you want to continue to use the Uber platform". Drivers claim to have been [deactivated](http://www.forbes.com/sites/ellenhuet/2014/10/16/uber-driver-deactivated-over-tweet/) for being critical of the company on Twitter. Drivers on the premium Uber Black service (I have mainly ignored the complexity of the different Uber services here) were suddenly forced to take [requests](http://pando.com/2014/09/04/uber-continues-to-screw-its-partners-now-by-forcing-uber-black-drivers-accept-uberx-fares/) for the lower pay uberX service. The company [tracks](http://www.reddit.com/r/uberdrivers/comments/2mxk8g/uber_doesnt_just_stalk_passengers/) driver locations and complains if they are not to the company liking.

But at the heart of the control is the rating system that permits riders to rate drivers. Most riders give their drivers five stars out of five as a courtesy, but if a driver's rating slips even slightly – below 4.7 in many cities – they can be "deactivated" or kicked off the platform. The system makes drivers vulnerable to the most demanding of riders, as a small number of complaints can lead to the driver losing their way of making a living. And of course there is no appeal, as the driver isn't an employee and the contract is not a work contract. The reports of happy and friendly Uber drivers (see the Globe and Mail articles at the beginning of this post) take on a different meaning once you know the precariousness of Uber drivers' situation. As Forbes' Jeff Bercovici [reported](http://www.forbes.com/sites/jeffbercovici/2014/08/14/what-are-we-actually-rating-when-we-rate-other-people/), "Uber likes this system because it enjoys being able to say all of its drivers have near-perfect ratings. But it's a harsh one for drivers, and also for customers, who find themselves repeatedly forced to choose between guilt, spite and ignorance."

While Uber gets to dictate the behaviour of its drivers in more and more specific ways, it still takes none of the responsibility when things go wrong. Section 230 of the "Communications Decency Act" may seem like an odd law to protect the company, but here's how it works. The law was initially introduced to say that blog sites and other user-content sites such as YouTube were not responsible for content posted by its users. Fair enough. But now Uber says it's not a taxi company, it just runs a web site and an app, and puts drivers in touch with riders. Anything that goes wrong is not Uber's responsibility, it's the driver's. The law is an American one, but challenging Uber is going to be expensive and maybe prohibitively so for Canadians too, especially given the company's formidable bank account.

Uber's rules seem to step over the line regarding whether a driver is, or is not, an employee according to Canada Revenue Agency rules. Sharing economy workers are facing this issue with other companies too, such as cleaning/odd-job service [Handy](http://www.forbes.com/sites/ellenhuet/2014/11/18/contractor-or-employee-silicon-valleys-branding-dilemma/). It's an issue that other industries face, such as [construction](http://www.journalofcommerce.com/Home/News/2011/3/The-deliberate-misclassification-of-workers-hurts-almost-everyone-JOC043591W/), and the root cause is always the same: classification as an independent contractor relieves the hiring company (Uber in this case) from having to pay EI premiums, and from having to abide by employment standards. The risk is pushed entirely onto the subcontractor. When Toronto mayor John Tory says that Uber should be allowed to operate, he's implicitly approving of these arrangements, and allowing bad labour practices to intrude further and further into Canada's workplaces. It's bad for the drivers, and it's bad for our society.












## Customer issues






Among all of these problems, the customer is the one who does well (putting aside the problems with sexism and privacy violation listed at the top of the post). Uber is keeping the prices low, pushing drivers to accept all the rides they are assigned whether or not it makes them money, and is using the rating system to ensure that the drivers put on a friendly face. It's relying on these customers to push cities into permitting the apps.

But even here there are concerns: issues of race are complex: some people of colour report [a dramatically better](http://www.racialicious.com/2012/11/28/cab-drivers-uber-and-the-costs-of-racism/) experience than with taxis but others are concerned about [customer profiling](http://blogs.dallasobserver.com/unfairpark/2013/10/southern_dallas_leaders_say_ub.php), and [potential for discrimination](http://www.nancyleong.com/race-2/uber-privacy-discrimination/). Disability access is more troubling: [blind riders](http://www.sfgate.com/bayarea/article/Uber-accused-in-suit-of-refusing-customers-with-5746412.php) are suing Uber and [disability activists](http://www.chron.com/news/houston-texas/article/Texas-advocates-file-32-disabilities-act-lawsuits-5644400.php) are filing lawsuits.












## Summing up






This post is already too long. I could have written about the occasional horror stories of accidents and abusive behaviour from drivers, but they happen with taxis too. And I've not covered the dubious screening process that Uber uses, or the lack of proper mechanical inspection of the cars, or the difficulties with insurance: these have all been covered elsewhere.

The list of problems with Uber is long. The existing taxi industry is not perfect, especially in big cities, but it is a part of the democratic fabric of the country, and we need to address its problems by better democracy, not by throwing democratic accountability aside for the promise of self-regulation by an unaccountable company with an arrogant, sexist corporate culture, which treats its drivers badly, which walks away from its responsibility when things go wrong, and which is importing an American anti-democratic attitude into this country.






		
