---
author: Tom Slee
categories:
- blog archive
date: 2007-07-14 23:57:59
title: If That's All Right With You - A Modest Manifesto
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

My "[Happy Shoes](http://whimsley.typepad.com/whimsley/2007/07/happy-shoes-iv-.html)" series seems to have faded out one episode before I meant it to. Oh well, maybe I'll get back to it soon. Meanwhile, here is a something a little different, which owes a lot to various posts by Chris Dillow at [Stumbling and Mumbling](http://stumblingandmumbling.typepad.com/).

* * *

The names of Vasili Arkhipov and Stanislav Petrov do not appear in most lists of 20th century heroes, but they should. After all, who else could claim to have literally saved the world?




Arkhipov's moment came during the Cuban Missile Crisis on October 27, 1962, when he was an officer on a Soviet nuclear-armed submarine. When the submarine was bombarded by an American ship an intelligence officer on board thought "that's it - the end" and the captain gave the order to prepare to fire a nuclear missile. Had the missile launched, nuclear war would have begun, but firing a nuclear warhead required the approval of three officers and Arkhipov prevailed on his fellow officers to wait -- and things calmed down. When the [story became public](http://www.latinamericanstudies.org/cold-war/sovietsbomb.htm) in 2002 Thomas Blanton, director of the US National Security Archive, said simply: "A guy called Vasili Arkhipov saved the world".




In 1983, [Stanislav Petrov](http://www.worldcitizens.org/petrov.html) was monitoring the Soviet early warning satellites for signs of a US attack. His instructions were clear: if he detected missiles targeting the USSR he was "to push the button and launch a counter-offensive". But when the system showed five missile launches in the US all headed towards the USSR, sirens blared and warning lights flashed, and a room full of people waited for him to push the button, he didn't. It didn't look right to him and he reported the alarm to his superiors but declared it false. Petrov was right: the signal was a false alarm triggered by the satellite itself, and a war was averted.




You could hardly find two more unheroic heroes. They were not powerful generals or strong warriors, they were mid-level functionaries in the Soviet military: small cogs in a very big machine, far from the centres of political power. And their actions were not the decisive, bold gestures that we expect from heroes but were cautious and sceptical. When others demanded action their heroic response was to say "let's wait and see".




We should value modest people such as Arkhipov and Petrov more highly. It is time for modest people to get the credit they deserve.

* * *

Look around. It is easy to see what kind of character traits we value. We nourish "leaders" all the way from elementary school (where [programs](http://www.boardoftrade.com/vbot_page.asp?pageid=47) [select](http://www.cyr.gov.sk.ca/leaders_tomorrow.html) "[leaders](http://astech.ab.ca/users/folder.asp?FolderID=1623) of [tomorrow](http://www.lotinc.org/)") through [university scholarships](http://whimsley.typepad.com/whimsley/2006/10/scholarships_en.html) and on into the adult world. We heap admiration on those who succeed in reaching positions of power. We encourage single-minded ambition with every book or show or speaker that tells you to "find your passion" or "follow your dream". We applaud extroverts for their gregariousness and self-confidence. 




On the other hand, we undervalue traits such as meekness, generosity, doubt, introversion, a sense of balance, gentleness, irony and competence. In short, we reward arrogance and punish modesty. (I don't mean modesty as in women covering up their bodies so that men don't get excited, of course, I mean modesty as in a sense of limits, lack of pretension).




These unbalanced values distort many aspects of our culture. Consider heroism. We search for our heroes among those who are "exceptional" (climb higher mountains, score more goals, make more money...) but a different and better idea of heroism is possible, in which heroic acts are those that reveal our humanity. Arkhipov and Petrov are two examples. For another, consider the 17th century inhabitants of the village of Eyam (rhymes with dream) in Derbyshire, England. I heard of this from [John Trevor](http://www.geocities.com/trevormidgley/JohnTrevor.html)'s song "Roses of Eyam", as sung by the wonderful [Roy Bailey](http://www.roybailey.net/). The song records how the villagers gave up their lives when bubonic plague arrived in Eyam by sealing themselves off to make sure the disease did not spread to the surrounding areas. The number who died varies according to the telling: some say 259 of 333, some 318 from 350, but there was no doubt that those who sealed themselves off had little chance of survival. There was nothing grandiose here - no rewards, no trophies, no immortality save of the most simple kind. And yet how much more heroic these unknown people are than, say, Bill Gates or Bono.




James Joyce realized that our common humanity is at the core of heroism. By building the greatest novel of the twentieth century around a day in the life of a Leopold Bloom -- a middle-aged, cuckolded, advertising salesman -- Joyce highlighted the epic nature of everyday life. And he is right; the great things in life are universal. Birth and death, giving birth, caring for others: you don't need to explore the remote corners of the world to find these things, yet what can be greater? As Chris Dillow [reminds us](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2006/05/no_more_heroes.html), Thomas Gray knew the value of modest lives. In his "[Elegy Written in a Country Churchyard](http://www.thomasgray.org/cgi-bin/display.cgi?text=elcc)" he surveyed the graves of the "rude Forefathers" of a hamlet:

<blockquote>Let not Ambition mock their useful toil,  
Their homely joys, and destiny obscure;  
Nor Grandeur hear with a disdainful smile  
The short and simple annals of the Poor
> 
> </blockquote>

The poet reminds us of the importance and nobility of modest work compared to the contributions of those who enjoy "the pomp of power". Dillow [again](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2007/07/in-praise-of-li.html): "All the essentials of life come from the little people who clean the streets and make our food. The humblest binman has done more good for me in the last 10 years than [Tony] Blair's managed." Or, as I read in a cookbook, "The discovery of a new dish does more for human happiness than the discovery of a star".




We would have better politicians and CEOs if a sense of service - an inherently modest quality - rather than "leadership quality" was seen as a character trait to be rewarded, and if they recognized that their success comes as much from [luck and the quirks of history](http://whimsley.typepad.com/whimsley/2007/04/predicting_hits.html) as from merit. And even those who do reach the pinnacles with good motives must be treated with suspicion. Power of all strands does, after all, corrupt, and those who see power are the most vulnerable to corruption.




Public discourse suffers from the same warped perspective. Those who parade bold visions and big ideas gain much of the limelight, but such efforts [often](http://www.thelongtail.com/) [have](http://www.wikinomics.com/) more to say about the vanity and presumption of their authors than about the reach of their intellects. A discourse based on big ideas is prone to being diverted by demagogues. Flashy writing and speaking does have its place, but mainly as popularization, and it means little if not built on cautious and detailed work carried out by those with more modest aims. The devil is often in the details and the world can more often be seen by looking closely at a grain of sand than by scanning the far horizon.




Vanity is linked to what must be The Word For 2007: "passionate". At every turn it seems that we are told that the way to happiness is to "find your passion". Companies boast that they have a "passion for excellence". Be all you can be. Follow your dream.




Such ideas are literally self-centred, and are the opposite of the modest life. When you are the star of your own life, those around you are reduced to supporting roles. Who, I cannot help but wonder, is paying for that dream? Who is finding the children's clothes while you are busy finding your passion? Usually it is the family members who have to suffer the absences (physical and mental) of the dreamer. Conor Cruise O'Brien has been called "the greatest living Irishman", yet in a trip to Toronto in the 1990s he was without his family for once, and he was at a loss. Why? Because his family members usually handled the money, the arrangements, the mundane details of his trips. Surely no one who gets those around him to do the drudge work can be considered "great".




Passion not only leads to a self-centred life; it is also the enemy of scepticism, of doubt, and of reflection. To be passionate is to be blinkered. Evangelists, monomaniacs, and demagogues are as passionate as anyone, and follow their dream wherever it takes them. But they are terrible role models. We would do better to emulate those who make and accept the compromises of a modest life; those who treat people around them with respect, who accept that others have dreams too and that, if we all give a little, we may not reach our dream but we may have a better world.




It's not that we should cast down the extrovert and immodest. Every parade needs a leader and, as the saying goes, "you can't lead a parade if you think you look funny sitting on a horse". Movies need stars and some rock bands benefit from a little swagger, but the point is that the starring role, while it grabs the spotlight, is just one of many that combine to produce the finished event. The star cannot shine without a supporting cast. Every great band needs its rhythm section, every orchestra its second fiddles. No politician gets elected without dedicated campaign workers and no matter how comfortable you feel on a horse, you can't lead a parade all on your own because that's not a parade. We need to remember that music, parades, and other events are collective efforts, and value those who feel more comfortable behind the scenes together with those who revel in the spotlight.




Of all roles, perhaps that of the spectator is least appreciated. Being a spectator is seen as passive and uninspired: how often do you hear the phrase "mere spectator" contrasted with "active participant"? Yet us spectators have an essential part to play too, because great events are made great by their spectators. What is a cup final without the fans? A rock concert without the crowd? A festival without the festival-goers? Or consider books: novelist Zadie Smith [recently wrote](http://zadiesmithnews.wordpress.com/2007/01/13/fail-better/) that "A novel is a two-way street, in which the labour required on either side is, in the end, equal... Reading is a skill and an art and readers should take pride in their abilities and have no shame in cultivating them if for no other reason than the fact that writers need you".




Extroverts, as Jonathan Rauch says in [a widely-read essay](http://www.theatlantic.com/doc/200303/rauch), dominate public life. "This is a pity", he goes on, "If introverts ran the world, it would no doubt be a calmer, saner, more peaceful sort of place." Yet introverts get little respect:

<blockquote>Extroverts are seen as bighearted, vibrant, warm, empathic. "People person" is a compliment. Introverts are described with words like "guarded", "loner", "reserved", "taciturn", "self-contained", "private" - narrow, ungenerous words.
> 
> </blockquote>

There are good reasons for this. Extroverts, after all, are in a good position to spread the idea that being outgoing is a good thing. Introverts, on the other hand, are not well suited to evangelize the virtues of quiet.




Restoring a balance will not be easy, because it demands immodest behaviour of modest people. It is difficult to promote the quiet virtues in a world drowning in the verbiage of the loudmouthed. Does it even make sense to stage an outspoken demand for modesty (if that's all right with you?), a brash call for humility, a blunt demand for subtlety, an uncompromising plea for flexibility? Can we be unequivocally on the side of doubt? Does it make sense to spout a monologue on the benefits of shutting the hell up? 




Probably not. The very idea of a manifesto is, of course, immodest. But I think it could be saved by something that is lacking in this attempt, which is irony. Perhaps someone else can do a better job.




We should be able to speak up while accepting the limits of our own arguments if we acknowledge (with Leonard Cohen) that "there is a crack in everything. That's how the light gets in." Contradiction is an opportunity to learn rather than a debate to be fought. Thesis and antithesis are the beginning of synthesis. In exploring both sides of contradictions and arguments we learn to see both sides of a dispute, empathize with hurts and griefs that are not our own, and start to see the cracks in our own beliefs. And that must surely be a goal of any modest agenda - although not before we get the immodest down off their high horses and get them to shut up for a minute.


		
