---
author: Tom Slee
categories:
- blog archive
date: 2007-07-02 12:27:19
title: Happy Shoes I
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is the first in a meandering, loosely-related series of posts about consumer activism. I haven't worked things out to the end so I won't say where I think it's going, and the series may fizzle out but this is, after all, just a blog - and a slow-moving occasional one at that.





Here is a quotation from Andrew Potter and Joseph Heath's book [The Rebel Sell](http://www.rebelsell.com/) (based on a provocative 2002 This Magazine article you can find [here](http://www.thismagazine.ca/issues/2002/11/rebelsell.php) ):





<blockquote>If
consumers are willing to pay more for shoes made by happy workers -- or for eggs
laid by happy chickens -- then there is money to be made in bringing these goods
to market. It's a business model that has already been successfully exploited to
great effect by The Body Shop and Starbucks, among others. [p2]
> 
> </blockquote>

True, or not? 




Here is how it is supposed to work. Suppose
you want to buy a pair of shoes and you only have one choice -- the
only shoes available are from Sweatshoes Inc. , which makes their shoes
in a sweatshop, pays their employees very little, sells shoes for $100,
and makes a profit of $10. You buy them because you need shoes.




Along comes Happy Shoes,
which makes shoes "ethically" and pays their employees better. Because
you are a decent person, you're willing to pay an extra $20 for an
ethically-produced pair from Happy Shoes.




Happy Shoes could pay its employees $10 more than Sweatshoes pays theirs, sell you the
shoes for $120, and still collect a hefty $20 profit. The
Happy Shoes employees are happy because they get paid more, the Happy Shoes customers are happy because they have got their
ethical shoes at a price they're prepared to pay, and
Happy Shoes shareholders are
happy because they have made $20 profit rather than $10. Everyone is better
off if you buy Happy Shoes, except for Sweatshoes - and good
riddance to them.





There have been some successes for ethical consumer products. Ben and Jerry's ice cream and
The Body Shop were long-time standard bearers of companies that have traded on
their ethically-spotless image. Smaller businesses that sell organic foods
or village-produced trinkets do the same. Even Adbusters has got into the
buying and selling game with their Blackspot shoes. It's an appealing
idea: replace the moustache-twirling, cigar-smoking sweatshop-runners
with enlightened and decent people, and you can change the world.





But after a decade or so of consumer activism the successes are still few and far between. As Bill McKibben [writes](http://www.motherjones.com/news/feature/2006/11/hype_vs_hope.html) in the November 2006 Mother Jones:




<blockquote>

> 
> Ben and Jerry didn't change the way Haagen and Dazs viewed the world. Somehow, Bounty has been willing to leave the thoughtful paper towel market to Seventh Generation. For several decades now, environmentalists have been citing the work of [Ray Anderson](http://www.interfaceinc.com/who/founder.html) and Interface, and it's a great example -- but why is there still only one Ray Anderson?
> 
> 
</blockquote>




When it comes to actually putting down cash, are we not prepared to pay the additional money for
Happy Shoes? That's the [next post](http://whimsley.typepad.com/whimsley/2007/07/happy-shoes-ii.html).


		
