---
author: Tom Slee
categories:
- blog archive
date: 2007-02-18 10:20:13
title: The Long Tail 0.2 - Introduction
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is part of my critical reader's companion to _The Long Tail_ and discusses the Introduction. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). The previous part in this series is [here](http://whimsley.typepad.com/whimsley/2007/02/i_know_i_know_n.html).




After taking two posts to get past the cover, you may be very glad to know I have nothing to say about the dedication page or the acknowledgments. This exercise will be long-winded enough without that. Yes, I'm ploughing on, turning pages recklessly past the Table of Contents and all the way to the Introduction. But I'll stop there, and look at it closely.  
  
The point of an Introduction is pretty similar to the cover. It's to set out the main themes of the book, to sketch the argument, and so to draw the reader in. Some writers call it Chapter 1 (that's what I did) and others don't call it a chapter (that's what Anderson does), including it as part of the front matter for the book.  
  
Unsurprisingly then, some of the things I have to say here will repeat what I said about the cover. Anderson starts off by talking about the world we are in now, and this world is "the world the blockbuster built" [1]. (Remember, numbers in square brackets are page numbers in the book, not footnotes) But that world is "starting to tatter at the edges" [2].   
  
I want to spend some time on a paragraph on page 2 where he backs up this claim that blockbusters have had their day. It's not the only place he does this, and we'll return to the question of whether blockbusters are "starting to, gasp, rule less" later, but this is the first time he attempts to bolster the claim. He writes that "Most of the top-fifty selling albums of all time were recorded in the seventies and eighties" [2]. (The end notes make it clear he is talking about the USA here. As elsewhere, most of his figures and data refer to the US.) Interesting, but what about other areas of culture? A parallel statement would be that most of the top-grossing movies of all time were in the same time period. But the top grossing film of all time is Titanic (1997) and even adjusted for inflation, the top box office hits [are](http://www.boxofficemojo.com/alltime/adjusted.htm) Gone With the Wind, Star Wars, The Sound of Music, ET, The Ten Commandments, and Titanic - one each from the thirties, fifties, sixties, seventies, eighties, and nineties. Among the top 50 are 2 from the 1930's, 4 from the 1940's, 5 from the 1950's, 9 from the 1960's, 11 from the 1970's, 7 from the 1980's, 7 from the 1990's, and 4 so far from the 2000's. So there is perhaps a bit of a peak here, but it is not a dramatic one, especially as the figures are biased towards pre-1980 films which have had multiple releases (Disney animations in particular). So movies do not seem to show the same waning blockbuster effect as music. Instead, Anderson points to the waning total theatergoing audience, which seems to me a different phenomenon entirely.   
  
On TV he has a stronger case - the waning of network TV in the US means that "the number one show today wouldn't have made the top ten in 1970". But what about books, the other area of entertainment/culture that he talks about a lot? He doesn't say. The bestselling books of all time are books such as the Bible and Quotations from Chairman Mao, which don't tell us a lot about book-buying habits in the sense he is looking for. A best-selling book can sell for years, decades, or more, giving Beatrix Potter's Peter Rabbit a head start over Asterix. So although I do feel sceptical about the fall-off of blockbuster books (Da Vinci Code and Harry Potter anyone?) I'll give him a break here.   
  
Returning to movies for a moment, there are other sides of the movie industry which tell a different story from the one that Anderson is telling. Peter Grant and Chris Wood's 2004 book [Blockbusters and Trade Wars](http://www.douglas-mcintyre.com/book_details.asp?b=952) explains how (p 76) the era of the blockbuster started with Jaws. Before then, most movies launched in a "rolling opening" screening in major cities first and smaller centres later. Jaws opened on 460 screens - a big change. By 1995 however, "virtually all of the 150 or so movies released by major studios in the United States and Canada opened in more than 800 screens. By the turn of the century, 2,000- to 3,000-screen openings were commonplace. In 2001, Harry Potter and the Sorcerer's Stone opened in the United States on a breathtaking 8,200 screens -- nearly a quarter of all the theatres in America. On its opening weekend in Canada that year, Goldmember managed to seat an even more astonishing 52 per cent of all admissions". Here is a different story - if blockbusters are waning, it is not because we have more choice but because they are living a shorter time, rolling over ever more urgently to make way for the next big opening. Anderson skips over these other consequences of the increasing returns to scale of digital production.  
  
Anderson's conclusion, then, is that hits "are not quite the economic force they used to be". More dramatically, he goes on to say "Where are those fickle consumers going instead? No single place. They are scattered to the winds as markets fragment into countless niches." At this stage in the book, the reader can only say "well, we'll see." He hasn't proven his case yet, that's for sure.  
  
**iTunes Killed the Radio Star** [2-6] contrasts Anderson's own upbringing in the '70s and '80s with a modern teenager. The difference is simple: "The main difference between Ben's adolecence and my own is simply choice. I was limited to what was broadcast over the airwaves. He's got the Internet." Now let's be clear: the Internet is a big thing. It is changing much about this world, including adolescent lives. It's going to change more. Some of the changes will be profound, some banal, some specialist, some pervasive - and it's only just starting. It is the multifaceted nature of the changes it is bringing that make comparisons dangerous. When Anderson says "He plays video games with friends, mostly online" he is confirming that one change is that play has shifted from the streets, from friends homes, to the computer screen and networks. So to compare Broadcast TV to "The Internet" is misleading. This is something I'll return to in later chapters, but what he is describing is not so much an increase in choice as a shift in choices. Some choices (playing in the street) have basically been lost, while others have risen to take their place. Just because these new options travel over the same network as online newspapers does not change the fact that it's just another form of playing with friends.  
  
What's more, Anderson's description of his mass culture youth, hemmed in by the small number of rock stations, and by an inability to explore outside the mainstream, is just not plausible. I mean, I was there. I grew up in the '70s on the edge of Leeds, a middle-sized provincial city in the UK, and went to school in a town of 13,000 people. This was not a cutting edge environment, but even within that I was behind the times - unfashionable, with a narrow taste in music and a conformist taste in clothes. But even I managed, despite my best efforts, to be exposed to non-mainstream culture. The biggest band of the mid-'70s was Led Zeppelin, who thrived despite never being played on radio. My own particular favourite was Pink Floyd (ditto) but there were minor bands a plenty (Wishbone Ash anyone? Hawkwind?) My friend Matthew was into German techno-rock: Tangerine Dream and Kraftwerk. And that was before punk shook everyone up. So to portray this world as devoid of anything but the mainstream is, frankly, ridiculous.  
  
But let's leave my teenage years behind quickly and go back to the book. A section called "The 98 Percent Rule" [6-10] describes the beginnings of the book. The rule is based on a conversation he had with the CEO of Ecast, a digital jukebox company. This CEO pointed o
ut that 98% of all their 10,000 albums had sold at least one track per quarter (three-month period). Anderson is stunned at the variety of people's tastes when unencumbered by the physical limitations of old jukeboxes. This 98 percent rule is that just about anything you can offer for sale will find a buyer, so if you can (in a digital world) offer everything, then you can make money off all those items that sell a few here and there. Hits still matter, but "What if the non-hits--from healthy niche products to outright misses--all together added up to a market as big as, if not bigger than, the hits themselves?" [8].  
  
One reviewer who has challenged this part of the book is Wall Street Journal's Lee Gomes. Gomes argues ([here](http://online.wsj.com/public/article/SB115387606762117314-Inp5lUxHwVDwS_SJv5zaQShPXlE_20070726.html) ) that whereas Anderson claims the 98% rule to be "nearly universal" citing iTunes, Netflix, Amazon and others ("And so it went, from company to company"), Gomes himself found something different:

<blockquote>But when I looked online, I was surprised to see what seemed like the opposite. Ecast says 10% of its songs account for roughly 90% of its streams; monthly data from Rhapsody showed the top 10% songs getting 86% of streams. 
> 
> 

> 
> Bloglines, the widely used blog-reading tool, lists 1.2 million blogs; real ones, not computer-generated "spam blogs." The top 10% of feeds grab 88% of all subscriptions. And 35% have no current subscribers at all -- there's clearly no 98 Percent Rule in the blogosphere.
> 
> At Apple's iTunes, one person who has seen the data -- which Apple doesn't disclose -- said sales "closely track Billboard. It's a hits business. The data tend to refute 'The Long Tail.' "
> 
> Other economists, of course, are looking into these same questions, though some seem to be reaching far more restrained conclusions. Harvard's Anita Elberse, whom Mr. Anderson said was a consultant during his two-year research project, studies the video sales market, both online and off.
> 
> She said in an email that her work to date shows a "slight shift" toward the tail. But she also noted "a rapidly increasing number of titles that never, or very rarely, sell," which suggests "it is difficult for content providers to profit from the 'tail.' "
> 
> It would be wonderful if the world as Mr. Anderson describes it were true: one where "healthy niche products" and even "outright misses" collectively could stand their ground with the culture's increasingly soulless "hits."
> 
> But while every singer-songwriter dreams from his bedroom of making a living off iTunes, few actually do, mostly because so many others have the very same idea. And to the extent that Apple is making money off iTunes, thanks go to Nelly Furtado and other hitmakers. Indeed, you can make the case that the Internet is amplifying the role of hits, even in relation to misses, not diminishing them.
> 
> </blockquote>

Anderson responds on his [weblog](http://www.longtail.com/the_long_tail/2006/07/factchecking_my.html) but while there is dispute over other portions of the book (and we'll get to those in a few posts time) he doesn't challenge this part so far. The 98 percent rule seems to be a rule that is often broken.




Anderson himself replaced the phrasing of "98 percent rule" with "The Long Tail" as he continued his work. The point to make here is that in the introduction, despite some intriguing-sounding stories and some big claims, he has not demonstrated that a "Long Tail effect" actually exists. This matters. 




**Tails Everywhere** [10-11] is one of two places where the book goes seriously off the rails. As we'll see, for most of the book the meaning of "The Long Tail" is fairly clear, but every now and then Anderson seems to get carried away and treat it as just another word for "variety". So here he says "People often ask me to name some product category that does not lend itself to Long Tail economics. My usual answer is that it would be in some undifferentiated commodity, where variety is not only absent but unwanted. Like for instance, flour... Then I happened to step inside our local Whole Foods grocery and realized how wrong I was: Today the grocery carries more than twenty different types of flour... There is, amazingly enough, already a Long Tail in flour." [11] This passage has two large faults. First, it clearly implies that Anderson sees the logic of the Long Tail, most of which is about media and entertainment industries, as extending to pretty much all of economics -- "The Future of Business". Also, he sees it as stretching beyond the digital world. Yet here (and again we'll come back to this when he explains in more detail what he means by a Long Tail effect) he seems to be saying that the mere presence of a variety of goods is sufficient to indicate a change. You have to wonder, does 37 brands of toothpaste reflect a long tail in toothpaste? And what if (something he doesn't mention) they all come from two companies? If he is going to argue that Long Tail simply means the emergence of niche markets then he has to demonstrate that a change is happening, whereby niche markets are becoming more important. Once more, at least in his introduction, he does not do this.




**A Preview Of Twenty-First-Century Economics** [11-13] sets out how Anderson sees his book. First, he sees it as an economics research project (among other things). He's doing economic research that "very few economists" [12] are doing, and venturing into "uncharted waters". "Some of the data in this book" he says "has never before seen the light of day". Anderson claims his role is to "synthesize the results [of the efforts of online entrepreneurs] into a framework. That is, of course, what economics does: It seeks to find neat, easily understood frameworks that describe real-world phenomena". So this is an economics research book, he says.




Let's sum up what I've seen in the introduction. It has some nice sentences, some big claims, but is already showing at least three potential problems. First, he is so far unable to substantiate his claim that the era of blockbusters is waning and that the "mass-culture era" [2] of the '70s and '80s has given way to a world of niche cultures. Second, his 98 percent rule seems dubious. Third, he is claiming to have a book of research that sets the stage for the future of business and twenty-first century economics -- he is setting the bar high. Can he clear it? Let's see...


		
