---
title: "Authenticate Thyself"
subtitle: Notes after reading Fourcade and Healy
draft: true
# description: >
abstract: >
  Marion Fourcade and Kieran Healy have an essay in Aeyon
abstract-title: ""
author: 
  - name: "Tom Slee"
    url: https://tomslee.github.io
    email: tom@tomslee.net
title-block-banner: true
date: last-modified
date-format: long
published-title: Last updated
categories:
- Uncertainties
appendix-style: none
toc: true
toc-depth: 1
toc-title: Contents
knitr:
  opts_chunk:
    out.width: "100%"
number-sections: false
number-depth: 1
callout-appearance: default
execute: 
  freeze: auto
format:
  html:
    html-math-method: katex
    # css: styles.css
    anchor-sections: true
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true
    citation-location: document
    toc-location: left
    lightbox: true
  pdf: 
    documentclass: scrartcl
    papersize: letter
    toc: false
    number-sections: false
    colorlinks: true
    output-file: "algorithmic_pricing_draft"
    output-ext:  "pdf"
    mainfont: "CharterBT-Roman"
    fontsize: 12pt
    linestretch: 1.1
    keep-tex: true
    template-partials:
    - ../../title.tex
    geometry:
    - top=30mm
    - left=30mm
    - heightrounded
    include-in-header:
      text: |
        \definecolor{TealHeading}{RGB}{27, 158, 119}
        \newfontfamily\sectionfont[Color=TealHeading]{RobotoCondensed-Regular}
        \newfontfamily\subsectionfont[Color=TealHeading]{RobotoCondensed-Regular}
        \newfontfamily\subsubsectionfont[Color=TealHeading]{RobotoCondensed-Regular}
        \addtokomafont{section}{\sectionfont}
        \addtokomafont{subsection}{\subsectionfont}
        \addtokomafont{subsubsection}{\subsubsectionfont}
        \usepackage{mdframed}
# pdf-font: "ETbb"
editor: visual
---

# Authenticate Thyself

I highly recommend Marion Fourcade and Kieran Healy's thought-provoking new essay in Aeon called [*Authenticate Thyself*](https://aeon.co/essays/the-sovereign-individual-and-the-paradox-of-the-digital-age), which revisits some ideas from their excellent book [*The Ordinal Society*](https://www.hup.harvard.edu/books/9780674971141). Here are a few thoughts it provoked in me. Italicized paragraphs paraphrase points from the essay.

## I. It's more than surveillance

*The real power of computers is "how they link the ordinary choices we make into systems that constantly adjust and modulate themselves".... "It is more than a means of surveillance".*

Many techno-critics think of Silicon Valley platforms as a form of surveillance, notably Shoshana Zuboff's *The Age of Surveillance Capitalism*. But our entanglement with computers is more complicated than that, and Fourcade and Healy (Fouraly?) really highlight the tensions in our two-way relationship. Yes, of course, Uber drivers don't get to choose whether their work patterns are used to craft their exploitation once they've signed up, so some exchanges are more voluntary than others. But exchanging personal and behavioural information for trip directions on Google Maps, or for music you like on Spotify, or hundreds of other examples, goes beyond "surveillance" to something more consensual, which is not caught simply by the ideas of surveillance and privacy.

One consequence of the exchange is that social media, for example, has become totalizing. That is, attempts to criticize it just feed the beast. The more successful the criticism, the more clicks, the more responses, the more engagement. Yes, I too complained about Twitter on Twitter from time to time before leaving. In a way, this makes the challenge of our networked society more difficult: how can we escape from or divert something that seems to benefit from controversy and criticism?

## II. Hackers gonna hack

*In the early days of the internet, online anonymity was a kind of liberation... the opportunity to experiment with different versions of themselves. Now, the question is no longer whether an identity is genuine {"Is that really [you]{.underline}?") or even authentic ("Who is the real [you]{.underline}?") but whether each element of your digital presence is unmediated by* *artificial intelligence ("Is it [really]{.underline} you?"). Being a legitimate self now requires one to be publicly identifiable, authentic and, increasingly, fully authenticated.*

We are caught in a reality arms race, where each move to authenticate authenticity is countered by attempts to hide aspects of ourselves, to evade what Fouraly call "authenticity traps". We either present a homogeneous, constructed face to the world, or risk the charges that come from changing one's mind, or from acting out of character from time to time. Ironically, the latter is seen as evidence of inauthenticity. We can now present only a single artificially-consistent self in everyday life if we are to succeed in getting that apartment or that job.

The arms race is made worse because there is, to the authentication systems, no difference between a [workaround and an attack](/essays/2019-08-05_workaround_medical/): both are attempts to get from the system an output that was not intended (whatever that means) by the system. And if the system makes mistakes, human resolution of the resulting complaints does not scale. So Uber's drivers and riders now face the blank stare of GPT-5 powered chatbots. With which, [Uber claims](https://www.youtube.com/watch?v=L--pCNSt3F4), in a candidate for most dystopian statement of the year, "every conversation feels more human, and on-brand."

A surprising number of large-scale enterprise systems rely on people employing folk knowledge workarounds to circumvent their clumsiness and bugs. How these will survive in a world of ever-increasing authentication demands is anybody's guess.

## III. The death of irony

*Social media companies relentlessly encourage individuals to publicly express their core commitments. Being exposed as inauthentic can be devastating to reputations and livelihoods.*

"Authenticity traps" are situations where signs, no matter how casual or flippant or ironic, can be selectively wielded as evidence against us.

Irony has never been a strong point of American culture, and nowhere does that matter so much as in the assumptions underlying these ordinal systems. The systems are built on the illusion that we each have an authentic self which can be retrieved from our data so long as provenance can be proved (captured in enterprise systems' use of the term "single source of truth").Which creates challenges for those many circumstances where we do not mean what we say.

The next time he upsets people with a joke, comedian Jimmy Carr dreams of making a public apology "I'm sorry" delivered with eye rolls and obvious sarcasm, so that when those he has offended complain that "you don't really mean that apology" he can reply "So I [can]{.underline} say something and not mean it. Now you're getting it."

(I wrote an essay "[In Praise of Fake Reviews](https://thenewinquiry.com/in-praise-of-fake-reviews/)" on this topic over a decade ago. Things have not improved.)

There is one obvious irony to reading this essay in 2025, which is that one group of people has found a way to triumph over these totalizing systems: to lie and to expose their worst selves to the world, without experiencing any harm. This should be cause for optimism: maybe we can avoid our Kafkaesque doom after all! But sadly, these are the worst people in the world running the most powerful country in the world.

## Scraps

Conservative cabinet minister Michael Gove popularized "[The Blob](https://www.theguardian.com/politics/shortcuts/2013/oct/02/michael-gove-referring-to-the-blob)" to highlight what he saw as the faceless, shape-shifting nature of the Whitehall civil service. Which is a shame, because "faceless and shape-shifting" fits many of the human-computer systems that we deal with, from tech giants to government departments to social media doxxing efforts. From policies to communications departments and now to individual conversations, The Blob has its own presentation-of-self, so
