---
author: Tom Slee
categories:
- blog archive
date: 2006-10-18 21:24:41
title: Radio Interview
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

I had a radio interview this morning courtesy of Phil Johnson, host of [a daily morning show](http://www.kelowna.okoldies.ca/shows/phil-johnson-show) (6am to 9am) in Kelowna, BC. 




He has apparently been running a series talking about consumer choices. One of his regular guests is Michael Neill, who (together with Michelle Neill) owns [Mosaic Books](http://www.mosaicbooks.ca/) in Kelowna, and who has apparently been referring to No One Makes You Shop At Wal-Mart from time to time. Clearly a man of intellect and perception.




Phil Johnson is an articulate host with strong opinions, and we seem to look at the world in a similar kind of way, so the interview was fun once it got started. I say "once it got started" because the phones went on the blink just before he called. Panic! Anyway, it got sorted thanks to a colleague with a mobile phone (thank you Roger). Fifteen minutes later we were all done. It seemed to go by very quickly.




So, my thanks to Phil Johnson and Michael Neill and to Kelowna Oldies 1150. I'll have to celebrate with a glass of the Okanagan's [world beating 2004 Shiraz](http://www.jacksontriggswinery.com/en/pdf/IWSCSF_2006_%20Best_Shiraz.pdf) from Jackson-Triggs.


		
