---
author: Tom Slee
categories:
- blog archive
date: 2007-03-15 08:35:05
title: The Long Tail 9.2 - The Short Head is Alive and Well
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Hits really are as big as ever. Link: [BBC NEWS | Entertainment | Record print run for final Potter](http://news.bbc.co.uk/1/hi/entertainment/6452987.stm).


<blockquote>A record 12 million copies of the final Harry Potter book are to be released in its first US print run.
Publisher Scholastic said July's release of Harry Potter and the Deathly Hallows would be supported by a multi-million dollar marketing drive.
> 
> </blockquote>

Meanwhile, Waterstone's is [getting caught](http://books.guardian.co.uk/news/articles/0,,2033225,00.html) in the big vice between the online retailers and the big grocery chains, (see previous post for how this has affeected CDs)

<blockquote>HMV is planning to close up to 30 of its Waterstone's book shops, give
more space to higher margin items and reduce the number of high brow
books, as part of an overhaul to restore the fortunes of the struggling
business. Details of the restructuring were announced yesterday as HMV
issued yet another profits warning, sending its shares almost 16% lower
to 128.5p...
> 
> 

> 
> The books and music retailer is facing an onslaught from all sides; the
growth of digital music through the likes of iTunes, online retailers
led by Amazon and the big grocery chains such as Tesco and Asda [Wal-Mart] selling
discounted books and CDs.
> 
> </blockquote>


		
