---
author: Tom Slee
categories:
- blog archive
date: 2006-10-10 22:57:54
title: 'Book News: Review'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

The enigmatic [Elephantstrunk](http://elephantstrunk.net/) has some [good things to say](http://elephantstrunk.net/2006/10/05/marginal-counter-revolutionary/) about No One Makes You Shop At Wal-Mart. I hope he or she does not mind if I reproduce it here.







<blockquote>Tom Slee’s [“No one makes you shop at Wal-Mart”](http://www.web.net/%7Etslee/)
should be bundled with every copy of “The Wisdom of Crowds”. I like
“The Wisdom of Crowds” but it always seemed dangerously incomplete.
NOMYSAW is not exactly a counter argument but shows that life is a lot
more complicated than the TWoC might suggest.  

Mr. Slee is clearly exercised by the free ride given to arguments
resting on offers of “choice”. Starting with the Prisoner’s Dilemma the
book shows ways that the seemingly obvious good of giving people the
opportunity to decide what is best for themselves can sometimes make
everyone worse off.
> 
> 

> 
> It’s not an original point but nor is it in fact a controversial
one. What is new is the articulation of what it means and what some
popular arguments don’t. The book uses the Prisoner’s Dilemma as a
simple example of individuals each seeking to maximise their personal
situation and suffering as a result but the most potent are at some
level examples of “The Tragedy of the Commons” but in places where the
Coasian solution of applying property rights is a less comfortable
propositions.
> 
> 

> 
> Finding a whole book, especially one so articulate and clear, about
a persistent but only half formed idea is quite a thrill. I liked it a
lot. Whimsley mentioned on the right is the author’s occasional blog.

> 
> </blockquote>







Thanks very much Mr/Ms Trunk.


		
