---
author: Tom Slee
categories:
- blog archive
date: 2007-02-26 21:14:26
title: The Long Tail 5 - The New Producers
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is a part of my critical reader's companion to _The Long Tail_ and discusses "Chapter 5 - The New Producers". Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). The previous part in this series is [here](http://whimsley.typepad.com/whimsley/2007/02/a_short_history.html).




At the beginning of this chapter [58] Anderson is back in storytelling mode, taking us to the Kamiokande II observatory in Japan to tell us how "one of the greatest astronomical discoveries of the twentieth century unfolded. A key theory explaining how the universe works was confirmed thanks to amateurs in New Zealand and Australia, a former amateur trying to turn professional in Chile, and professional physicists in the United States and Japan." [60] The story shows, according both to British Think-Tank Demos and to astronomy author Timothy Ferris, that astronomy has shifted from "the old days of solitary professionals at their telescopes to a worldwide web linking professionals and amateurs" [60]. 




Like the story of Touching the Void in [Chapter 1](http://whimsley.typepad.com/whimsley/2007/02/chapter_1_start.html), it is a story that is intriguing by itself, but which has very little relationship to the actual Long Tail thesis. The world of astronomy is a different world from that of Amazon.com. The book is about "The Future of Business" and yet astronomy is not a business. It's about "a market of multitudes" [5], but there is nothing in this story about markets. It's about the changes being brought about by the World Wide Web, but although Demos referred to a "worldwide web linking professionals" this story took place in 1987, before the World Wide Web was invented.




That is the weak point of this whole chapter: it tells us that amateur producers and volunteers have taken on a new importance in the world of the Internet but fails to show how this links to the rest of the book. In his original article Anderson did not talk about the production side of business at all. In short, this chapter is only tangentially related to the rest of the book. It looks as if Anderson needed material to fill out his 240 pages (this is one of the two longest chapters in the book), and so he bolted this on to the side. But it doesn't fit. 




So when, as in this first section of the chapter, the book talks [61-62] about SETI@home (the use of spare cycles on home computers to search through large amounts of data in the search for extraterrestrial life) or "clickworkers" identifying craters on Mars, or even open source software -- all interesting subjects -- I'm going to be relentlessly negative and ask "what does this have to do with the rest of the book?"




Democratizing the Tools of Production [62-65] is all about how people can use their PC's at home to engage in "production". Just like I'm doing now, in fact (I have a day off work). Anderson points us to the world of music - "Just as the electric guitar and the garage democratized pop forty years ago, desktop creation and production tools are democratizing the studio" [63], to the written word "aways the leading edge of egalitarianism" [63] and to photo editing and printing. He includes in his reach "video games that let people create and share their own alternative levels" and print-on-demand book publishing. Put together all these examples and it looks as if "we're starting to shift from being passive consumers to active producers" [63]. It's an inspiring image and a common one these days. But again, and as in previous chapters, Anderson is being selective in his selection of examples as he seeks to bolster his thesis. There are two questions that we have to ask when confronted by this plethora of anecdotes.




The first is "What were these new producers (or their equivalents) doing before this new kind of activity came along?" They must have been doing something, after all. We know the answer, I suspect. Some of the time we were indeed watching TV (passive consumers). At other times, as Robert Putnam describes in "Bowling Alone", we were engaged in other activities in or outside the home - local and community activities, whether it be a drink at the local bar or playing second clarinet in a Little Theatre production. A generation ago, the equivalent of those kids spending hours at their desktop digital music studio were probably producing music some other way. I don't know of any study that shows that teenage participation in music-making has increased over the last decade. Maybe it has, maybe it hasn't, but Anderson doesn't even begin to make the case that it has, and pointing to PC software does not make the case.




Another question is about the definition of "production". The Internet is still a shiny new thing, and the things it gets used for are changing rapidly - and will continue to change. But just because something happens on the Internet doesn't make it important, and doesn't make it "production". When I was young I used to make Airfix models of planes and tanks and so on, and I spent hours painting small metal figures of Napoleonic soldiers and creatures from Lord of the Rings. It was fun, but was it "production"? Only in a very distorted view of the world. So what about Chris Anderson's kids "who are, as I write, into machinima -- short computer-animated movies made with video game software.... The first reaction of the kids was to watch and enjoy the machinima movies as entertainment. Their second was to express curiosity as to how they're made. And their third was to ask if they could make on themselves (The answer, of course, is yes)." [64] Do the young Andersons' game-playing activities count as "production" any more than mine did? I suggest not. The fact that they are using a computer is not in and of itself very important.




Or consider home photography. Twenty years ago we may have been sticking photos in scrapbooks rather than putting them on Flickr, but we should ask whether posting on Flickr is any more "production" than sticking pictures in scrapbooks. It is a more visible activity for researchers, for sure. It is easier to count the number of photos on Flickr than to count the number of photos in scrapbooks around the globe, and as a result it is tempting to identify this as new activity or an expanding one. But like the "production" of music it may well not be. It's a shift of an activity from one medium, where it remains fairly private, to another where researchers can more easily access it. But that does not make it significantly different. 




The end result is that, whereas Anderson sees the rise of a new expanded class of creative people: "millions of ordinary people have the tools and the role models to become amateur producers" [65], I suggest that those creative people have always been there, and have always been creating. It's just that the Internet makes it more easy to count their creations.




But, I conveniently hear you say, what about blogging, where "millions of people publish daily for an audience that is collectively larger than any single mainstream media outlet can claim" [63]? Isn't that production? Or what about Wikipedia, which competes with the Encylopedia Britannica? Surely that is production? Patience. That's the next section.




The Wikipedia Phenomenon [65-67] is the first of four consecutive sections (ten pages) that talks about Wikipedia, the remarkable online encyclopedia. And remarkable it is. Even over the last few months, I've found myself using it more and more as a first reference source for a wide variety of questions, from wireless network technologies (where it is very strong, unsurprisingly) to historical questions. Sometimes it's great, sometimes not so much. But it is remarkable.




What's more, Wikipedia counts as production. If it competes with the Encylopedia Britannica, which it does, then I'm happy to count it as bona fide production.




But I'm still going to say that this ten-page section on Wikipedia does little for Anderson's Long Tail thesis, for a few reasons. First, a glance at the index confirms that this is the first place in the book where Wikipedia has been mentioned, and it is mentioned in only scattered places later on. We haven't seen it in the history of the long tail, or in the introductory chapter. Why not? Because like the astronomy story it isn't an example of a market and it's not a business. There has been a lot written about Wikipedia and other open-source content production; the best I've read is [The Wealth of Networks](http://yalepress.yale.edu/yupbooks/book.asp?isbn=0300110561), the exhaustive if sometimes heavy-going book by Yochai Benkler. Benkler describes Wikipedia as part of "the networked public sphere" - a public place that is provided by a network of loose collaborators. A public place is different from a commercial venture such as Amazon.com, and there is reason to believe that Wikipedia and Amazon are not part of the same thing.




Anderson links Wikipedia into his Long Tail thesis by pointing out that, while the Encyclopedia Britannica has to draw a line at which "the priests... decide 'This is not worthy'" [72], Wikipedia "just keeps going". While Britannica has 80,000 entries, Wikipedia has well over a million on all kinds of obscure topics. These entries, from 80,000 to 1 million and beyond, are "the Tail" of Wikipedia [72]. This does look a little like a Long Tail. After all, Britannica is put on a physical shelf and Wikipedia isn't. Britannica is pre-Internet and Wikipedia is Internet. So am I splitting hairs here when I say that Wikipedia is not "Long Tail"? Aren't these things enough to tie them together as part of "the same thing"? I'll argue not, precisely because the Internet is so important. Its impact is so big, so multifarious, that it does little good to link up all Internet-related activities as if they are a single thing. 




Here's an analogy. In Chapter 3 Anderson told us about the expansion of supermarkets in post-World War America, and explained how this was a precursor of the Internet Long Tail, driven instead by a technologically-enhanced infrastructure of better transportation and communication. At the same time a huge collective endeavour was thriving - scientific research, which expanded manyfold from its pre-war scale. This too was enabled by new technologies of communication and transport, enabling people to move around and share information, and providing the ability to collaborate across the miles. And guess what? There is a long tail structure to scientific research too. It goes all the way from the hits (DNA structure, the discovery of the laser, and so on) down to those niche items that are of interest to only a few (improved helium-acetylene potential energy functions, as a non-random example). Whereas pre-war research focused on the hits, the new post-war institution "just keeps going", exploring ever-more obscure backwaters of knowledge, some of which turn out to be surprisingly important. But does it make any sense to talk about scientific R&D and supermarkets as two parts of the post-war Long Tail? No. There's nothing to stop you from doing it, but it doesn't really add anything to our understanding. In the same way, to see Wikipedia as a production-equivalent of Amazon and Netflix does not really help us.




Wikipedia and other large-scale collaborative ventures among both amateurs and professionals are best viewed as networked public goods, as Benkler describes them. The fact that they are big does not make them Long Tail. After all, take any large enterprise, break it into its constituent pieces, plot them along down an x axis in order of decreasing demand, and you are bound to see something like the long tail graph. 




Self-Publishing Without Shame [75-78] follows Anderson's discussion of Wikipedia (some of which I am skipping over, having said quite enough I think) and presents a different view of what lots of little-looked-at content can be on the Internet. There are, you will be shocked to hear, things I agree with in this section. He writes about blogs, other forms of self-publishing, and "citizen journalism" (especially South Korea's "OhmyNews" [78]) and points to these areas as a "crucible of creativity, a place where ideas form and grow before evolving into commercial form". This makes sense. Barnes & Noble CEO says it this way: "Over the next few years, the traditional definition of what a 'published' book is will have less meaning. Individuals will increasingly use the Internet as a first stage to publish their work... The best of this work will turn into physical books." [77] This view of blogs and other web-based forms of expression as "first-step publishing" or pre-commercial publishing seems realistic. 




But I don't want to get carried away with this constructive and positive view of the Long Tail, so let me revert to negativism and point out that this interpretation of what is happening in the world of blogs and other self-publication is not what he has been talking about in the earlier part of the book. First, to see these DIY areas of self-publishing and social networks as
a pool from which hits will be picked is quite different from saying
that demand is shifting to niche products. Second, he says "Blogs are a
Long Tail" [69] but blogs are a non-commercial space for unmediated discussion and opinion. That's great, but the non-commercial nature of it sets it apart from most of what he is talking about as the Long Tail (an infinite shelf of commercial items for sale). The border between non-commercial and commercial parts of the Internet are blurred and changing, but there is still a border. It is not clear, for example, that Wikipedia contributors would continue to contribute if a company "owned" their product and made money off it. It is not clear that bloggers would contribute if others took their content and re-used it for money. Cases are appearing where photographers are complaining about the commercial use of their freely-produced images. The issues of rights and ownership are thorny and there will be years of debate to sort them out.




Case Study: Lonely Island [78-82] reverts to story-telling mode for the case of comedy troupe Lonely Island. It starts with media mogul Barry Diller scoffing at the idea that peer production, or "18 million people producing stuff they think will have appeal" could rival Hollywood and then tells how Lonely Island took their act online and found success after being picked up by Saturday Night Live. The lesson of the story is "on one hand, the existing entertainment industry filters did recognize the appeal of the Lonely Island and found a way to tap it. In that sense, maybe the system works. Yet if three kids with a video camera doing goofy raps and putting them on their web site isn't '18 million people producing stuff they think will have appeal'... I really don't know what is." [81] It is a weak story, of the same kind as the earlier Touching the Void - the Internet as source for successful acts. I could tell the story of unsigned singer Billy Bragg hearing that DJ John Peel was hungry and taking a curry to the recording studio, getting a few tracks played on the show in return, and finding himself on the way to stardom. It's not the Internet, but if it's not someone producing stuff they think will have appeal, well I don't know what is. The point is, there is no point.




The Architecture of Participation [82-84] finishes the chapter in bizarre fashion by acknowledging that "we've seen parts of this story before" and talking about punk rock and its "anyone can do it" attitude. I do wish he would turn back a few pages to where he told us that the '70s and '80s were the years of blockbuster culture: now it's the start of an architecture of participation. And the punk rock story is a good reminder that, for all the mashups and videos on the Internet, there is not a single artistic movement to have come from the Internet culture that rivals punk in its impact. Lonely Island comedy troupe just doesn't do it.




So that's the end of the chapter. For anyone still reading, I want to add one thing about production of digital goods that Anderson does not mention, which is that while it does make certain kinds of production cheaper, it also tends to create "winner take all" markets as [described](http://us.penguingroup.com/nf/Book/BookDisplay/0,,0_9780140259957,00.html) by Robert Frank and Philip Cook, also explained in detail in [Blockbusters and Trade Wars](http://www.douglas-mcintyre.com/book_details.asp?b=886) by Peter Grant and Chris Wood. The fact that the marginal cost of additional copies of a digital good are basically free to create, whether the first copy cost $1 or $100 million, has a number of consequences. One is that "cultural products that are attractive to consumers in a large geographical market have a lower risk and a much greater potential reward than do those that are produced for a smaller market" [Grant and Wood, p. 55] Here is a force that, as they describe, tend to constrain choice rather than promote it. I'm not going to go into this in detail here - just to say that (as [John](http://whimsley.typepad.com/whimsley/2007/02/a_short_history.html) pointed out in a great comment on Chapter 3) - there are winner take all forces at work in cultural industries that push demand away from the "Long Tail", which are ignored by Anderson.




[Just to finish in a really picky way, Anderson says of Wikipedia "There are the popular top 1,000 [articles], which can be found in any encyclopedia: Julius Caesar, World War II, Statistics, etc." [72]. He is being selective again: according to a [list](http://tools.wikimedia.de/%7Eleon/stats/wikicharts/?wiki=enwiki) linked to from Wikipedia itself, the most viewed articles in the English language version in February 2007 were (ignoring home page and other non-article pages): Anna Nicole Smith, Wiki, Valentine's Day, Wikipedia, United States, Naruto (a Japanese anime series), Chinese New Year, World War II, Sex, Deaths in 2007, List of Pokemon, List of Sexual Positions, Sexual Intercourse, Category: Female Porn Stars, and Barak Obama. How many of these top articles have entries in Britannica?]

  

		
