---
author: Tom Slee
categories:
- blog archive
date: 2006-03-03 21:46:12
title: Wal-Mart Extending Dominance of the Grocery Business - New York Times
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

It is easy to forget just how big and powerful Wal-Mart is, but you just need to look at its relationship with its suppliers to be reminded.




I thought Coca Cola (number 91 on the 2003 Fortune 500 with a revenue of $21 billion) and Pepsi Cola (numer 62, revenue of $26 billion) were pretty big companies who controlled their own futures, but according to the New York Times today Wal-Mart has just finished telling Coca Cola not to introduce a diet soda they were going to introduce, and then went on to tell them what drink Coca Cola should make instead, and then it told Coke to change how it distributes Powerade, its sport drink.




Apparently they did the same thing to Pepsi: "Wal-Mart executives asked Pepsi sales representatives in Bentonville to
come up with a new diet soda in flavors not widely available" and Pepsi agreed. Apparently Wal-Mart likes drinks that use Splenda as a sweetener, and what Wal-Mart likes, it gets. 




Of course, the official word around all this is that it is a partnership, that Wal-Mart makes suggestions, and that "it's a collaborative process" but it is clear who is calling the shots. Charles Fishman's excellent book [The Wal-Mart Effect](http://www.walmarteffectbook.com/) documents many such cases of Wal-Mart reaching inside its suppliers and telling them what to produce and how much they (Wal-Mart) will pay for it. The suppliers are left with a Hobson's Choice, especially in cases like Coke and Pepsi where there are two or more players in competition with each other. As the NYT article says: 

<blockquote>"Wal-Mart wants competition," Mr. Greenberg said. "They love that Coke
and Pepsi kill each other in colas to service them. They love
everything where you have close market shares because without that you
don't have high relative profits in the category."
> 
> </blockquote>

For Coke and Pepsi, there is only one thing worse than doing business with Wal-Mart and that's not doing business with Wal-Mart.




Here is my favourite quotation from the article:

<blockquote>"a bottling executive, who requested anonymity for fear of
alienating Wal-Mart, said the retailer thought it could do a better job
stocking and promoting Powerade in its stores than the bottlers could.
> 
> </blockquote>

It is worth reading what the bottling executive says. It is not even critical of Wal-Mart, but he or she still want anonymity. This appears typical behaviour among those who do business with Wal-Mart or who may do so in the future: they won't speak out of line publicly for fear of upsetting Wal-Mart, even when they don't have anything bad to say.




Link: [Wal-Mart Extending Dominance of the Grocery Business](http://www.nytimes.com/2006/03/03/business/03walmart.html?ex=1299042000&en=95bc5bd00b01e78c&ei=5090&partner=rssuserland&emc=rss).


		
