---
author: Tom Slee
categories:
- blog archive
date: 2006-08-13 22:14:32
title: Carnival of Wal-Mart
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Starling Hunter at [The Business of America is Business](http://thebusinessofamericaisbusiness.biz/) puts together collections of weblog posts on a couple of topics on a regular basis. One of those is Wal-Mart, and he included one of my posts in his latest collection: [Carnival of Wal-Mart III](http://www.thebusinessofamericaisbusiness.biz/2006/08/links_for_20060811.html). 




Among the others, there are posts about Chicago and Maryland's new employment laws that affect (or, in Maryland's case, would have affected) Wal-Mart employees, Wal-Mart's failure in Germany, the Walton family's shrinking tax bill, and Wal-Mart's new shoplifting policy.  





Starling Hunter has worked at Boeing as an Electrical Engineer, at Exxon, at MIT's Sloan School of
Management, and now at American University of
Sharjah, "just outside of Dubai, United Arab Emirates". His perspective on Wal-Mart is, unsurprisingly, definitely different from mine -- but I do like his take on [Rockonomics](http://www.thebusinessofamericaisbusiness.biz/2006/07/the_college_of_rock_and_the_bo.html).


		
