---
author: Tom Slee
categories:
- blog archive
date: 2008-12-11 19:10:54
title: Apple's Lemons
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

iPhone application developer Craig Hockenberry writes an open letter to Steve Jobs [here](http://furbo.org/2008/12/09/ring-tone-apps/), featured in Fortune magazine [here](http://apple20.blogs.fortune.cnn.com/2008/12/10/trouble-in-the-99-cent-app-store/), pointing out very reasonably that the 10,000 iPhone applications are experiencing a race to the bottom in terms of price. Charles Teague has put together some great graphs describing the state of the AppStore [here](http://blog.charlesteague.com/links/2008/11/5-months-and-9000-applications-later.html). 

What Craig H sees is this:

developers are lowering prices to the lowest possible level in order to
get favorable placement in iTunes. This proliferation of 99¢ “ringtone
apps” is affecting our product development.  


and here is how:

Raising your price to help cover ... costs makes it hard to get to
the top of the charts. (You’re competing against a lot of other titles
in the lower price tier.) You also have to come to terms with the fact
that you’re only going to be featured for a short time, so you have to
make the bulk of your revenue during this period.




This is why we’re going for simple and cheap instead of complex and
expensive. Not our preferred choice, but the one that’s fiscally
responsible.

The root cause of the low price is a classic market for lemons. Here is Craig H again:

I’ve been thinking about what’s causing this rush to the 99¢ price
point. From what I can tell, it’s because people are buying our
products sight unseen. I see customers complaining about how
“expensive” a $4.99 app is and that it should cost less. (Do they do
the same thing when they walk into Starbucks?) The only justification I
can find for these attitudes is that you only have a screenshot to
evaluate the quality of a product. A buck is easy to waste on an app
that looks great in iTunes but works poorly once you install it.




Our products are a joy to use: as you well know, customers are
willing to pay a premium for a quality products. This quality comes at
a cost—which we’re willing to incur. The issue is then getting people
to see that our $2.99 product really is worth three times the price of
a 99¢ piece of crapware.

This is, of course, the dilemma of the Internet. Publication is easy, even when Apple maintains the right to take your app off their store. This does not mean everyone benefits from the audience that "being published" used to bring with it. It just means that the roadblock to finding an audience is shifted further down the road - getting attention for your product. And asymmetric information is a major barrier in your way. How do you distinguish your shiny needle from the haystack in which it sits?

So where, he asks, are complex, high quality applications for the iPhone going to come from?

I can think of two ways forward for mobile apps in the absence of people being prepared to pay actual money. 

One is that open source community-built applications will come along. But that's less likely on a brand new platform than it is on existing platforms where a broad agreement can be reached on what an application needs to do. 

A second is that the successful applications (beyond Koi Pond) will be entry-points to some valuable service hosted elsewhere, for which someone can charge a subscription price. I'd bet on this second one. But applications for their own sake on mobile devices, it seems, will not be going far.


		
