---
author: Tom Slee
categories:
- blog archive
date: 2012-05-01 22:08:25
title: Reactions to 'Why the "Open Data Movement" is a Joke'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_[Update: In the light of morning I dislike this post. I'll leave it up, but it is too defensive, explains too much, and is too conciliatory given what was thrown at me yesterday.]_




This morning's post, [Why the "Open Data Movement" is a Joke](http://whimsley.typepad.com/whimsley/2012/05/why-the-open-data-movement-is-a-joke.html), attracted more attention than most of what I've written here. Largely this was a result of a Twitter debate between Evgeny Morozov ([@evgenymorozov](https://twitter.com/#!/evgenymorozov)) and O'Reilly Media's Alex Howard ([@digiphile](https://twitter.com/#!/digiphile)). Thanks also to Lorenz Matzat ([@lorz](https://twitter.com/#!/lorz)) and Ryan Shaw ([@rybesh](https://twitter.com/#!/rybesh)) for arguing broadly in favour of the post.




Alex Howard hated the piece, calling it "ill-informed", "lazy, ignorant writing" that "didn't even bother to cite the relevant scholarship", "demonstrably incorrect", "laughable" and more. He also writes that "The author has a habit of writing polemics that include errors or omissions of fact." I am terrible at expressing anything in 140 chars so I'll respond here.




First, it should be obvious that the post was prompted by events here in Canada - and yet no one has actually mentioned any of the Canadian content in any of the comments about the post. This is frustrating. The last five years have been terrible ones for accountability and transparency in this country and yet Canada has just joined and endorsed the Open Government Partnership ([link](http://news.gc.ca/web/article-eng.do?nid=669609)). Does this conjunction say anything about "open data" as a goal? To me it says that a technological "open data" agenda does not indicate a political "open data" agenda, and that -- as I wrote about the Wikileaks cables a year ago ([link](http://whimsley.typepad.com/whimsley/2010/12/wikileaks-shines-a-light-on-the-limits-of-techno-politics.html)) --the fault lines of political beliefs run perpendicular to attitudes about technology, not parallel. So it made me wonder if the idea of open data as a goal for a coherent movement holds water, and whether "opening government via technology" make sense. To Alex Howard - well I don't really know, because for all his outrage he doesn't actually say anything about the first half of the post or about the events that obviously moved me to write it and led to the frustrated tone I wrote it in.




Beyond that, he seems to confuse my contention that the idea of open data as a "movement" is a joke with a broader claim that "open data" is a waste of time or that people working on making data open are all dupes. No such thing! Open data can be a fine thing, but I'd much rather have a fully-staffed StatsCan charging for data than a half-staffed StatsCan providing it for free. Which would he choose? Obviously a fully-staffed StatsCan providing data for free would be ideal, but it doesn't look like we're getting that any time soon. The UK's Francis Maude, the incoming co-chair of the Open Government Partnership, [says that](http://www.guardian.co.uk/public-leaders-network/2012/apr/19/frances-maude-open-government-partnership) "we want to create an army of armchair auditors who can hold government to account". This would be nice, but not at the cost of a real independent auditor.




I suspect that Alex Howard and I just see the world from different points of view. Que sera, sera. But from what I know the Sunlight Foundation is on the side of the angels so I was disappointed to see that Tom Lee of the Sunlight Foundation considered my post "[a jumbled mess](http://twitter.com/tjl/status/197425160490455042)". I do realize that coalition politics makes strange bedfellows, and that broad coalitions can still be worthwhile, but some tents can be so big that they collapse in a shapeless pile of canvas. I worry that the open data tent is one such, and that the apparent common goals of some people under the canvas hide bigger differences. I share the concerns of Alex Howard's colleague [Nat Torkington](http://radar.oreilly.com/2010/08/gov-20-as-means-not-end.html) when he writes this:




<blockquote>

> 
> Obama and his staff, coming from the investment mindset, are building a Gov 2.0 infrastructure that creates a space for economic opportunity, informed citizens, and wider involvement in decision making so the government better reflects the community's will. Cameron and his staff, coming from a cost mindset, are building a Gov 2.0 infrastructure that suggests it will be more about turning government-provided services over to the private sector.
> 
> 
</blockquote>




For me, the gap between the two visions is fundamental and makes the idea that these two goals are part of the same movement, well, a joke. The tension/contradiction between commercial and civic interests that these sentences highlight is one division that seems unresolved and yet fundamental. So having read the responses, I stand by what I wrote.


		
