---
author: Tom Slee
categories:
- blog archive
date: 2006-06-05 20:42:09
title: Attack of the Snobs - American Enterprise Gets It All Wrong
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

It's not quite clear whether [Andrew Potter](http://www.rebelsell.com/blog/2006/5/31/everything-bad-is-good-for-you-the-wal-mart-effect.html) agrees with the American Enterprise Online when he posts pieces of an [article](http://www.theamericanenterprise.org/issues/articleID.19190/article_detail.asp) that is part of their issue Attack of the Snobs. AP himsels makes no comment, but my guess is that he approves of the article in some sense, or else he'd say so. The article itself is entitled In Praise of Ordinary Choices. Given AP's love of tweaking eaters of [organic foods](http://www.rebelsell.com/blog/2006/5/15/the-organic-shuffle.html), my guess is that he's on board with the American Enterprise Institute on this one.




Nevertheless, and much as I enjoyed most of Rebel Sell, he would be wrong. The AEI piece is MarketThink at its crudest. 




First, let's get past the sneers. There's the title "Attack of the Snobs" itself, of course. Then organizations opposing Wal-Mart are "a regular terrarium of screamers". The leaders are "Kerry and Dean assassins and union activists" -- two groups of people it's really hard to tell apart, I'm sure. Wal-Mart's success has come about "contrary to snotty stereotypes,... not by piling clip-on ties and plastic shoes ever deeper on tabletops, but rather via intensive, inventive, high-tech management". I don't know anyone who believes that snotty stereotype, so I think AEI are indulging a few stereotypes of their own. Then they have graphics showing a drawing of a placard with "Suburbia is Rape!" on it -- not a real placard, mind you, just the American Enterprise image of what a placard might be. Once you get past that stuff, you've thrown out 80% of the AEI papers. 




But there is a bit left over. And in that bit there is a big assumption right at the heart of "In Praise of Ordinary Choices" that persists in the other articles I've read from the issue (ie, those that are free). Which is that we've somehow chosen our cities and living environments, and that the fact so many people shop at Wal-Mart means they approve of everything it does. That's what they mean by "ordinary choices", and that's why they start the lead article by saying "The problem with most writing about cities is that people go out and say, 'Here's what I like', and the corollary to that is usually, 'This is what cities ought to be'." In contrast, the AEI believe that our preferences as revealed in our "ordinary choices" are reflected in the growth of cities. They praise author Robert Bruegmann, saying that he

<blockquote>"observes carefully, and shows respect for the billions of small judgments made by ordinary citizens in the course of their daily lives---choices which have cumulatively created the complex "horizontal" communities that Americans now call home."
> 
> </blockquote>

This is wrong in two ways. First, it is basically an assertion that the good things about places where we live [and yes, there are good things] came about because of free-market choices, though even south of the border cities are a mix of market-driven development and urban planning. So that assertion is wrong. Second, it asserts that as long as we have free choice, we'll get the kind of cities we want. But even if the AEI believes this, Andrew Potter knows that's not how individual choice works. He wrote a big part of Rebel Sell based on the problems of arms races and collective action problems, in which individual choices lead to bad results.




Robert Bruegmann himself makes the same kind of assertions. "Europeans are moving into suburbs in increasing numbers... In country after country across Europe, consumers are demanding the convenience of longer store hours, shops closer to where they live, and easier access by automobile. The result is a proliferation of large supermarkets, shopping centers, discount centers, and Big Box retail outlets like Wal-Mart or Target". The implication is clear, in context, that because people want longer store hours, they are somehow voting for the Big Box outlets and the environment they bring with them. But that implication is false. It doesn't follow.




Or in "Live with TAE", Witold Rybcynski is quoted as saying "Sprawl has got good and bad sides, but it's what we've chosen as a people" which is also simply not true. 




So let's be clear. To oppose the developer-driven, market-driven model of city growth that the AEI is promoting does not make you a snob (or an assassin come to think of it). And to observe that we live in sprawling cities doesn't mean we've chosen them. I hope AP agrees, but I fear he doesn't.


		
