---
author: Tom Slee
categories:
- blog archive
date: 2014-04-22 00:08:00
tags:
- airbnb
title: No True Airbnb Host...
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				After months of waiting, Airbnb and the Attorney General of New York finally face each other in court this week to argue over the Attorney General's [subpoena](https://www.eff.org/document/new-york-ag-subpoena-airbnb) for information on the 15,000 or so Airbnb hosts in New York City (summary [at the Guardian](http://www.theguardian.com/world/2014/apr/21/airbnb-new-york-attorney-general-court), more opinion in the overview by Nitasha Tiku at [Valleywag](http://valleywag.gawker.com/new-york-wants-to-subpoena-15-000-users-after-airbnb-re-1565483113)). There's been a flurry of revealing activity and statements, and lots of commentary. So here's more.

The court case is about many things. But what makes it interesting for those of us who don't live in New York is the broader implications of the case, which include:



	
  * The breadth of the Attorney General's subpoena and the proportionality of his actions. Does the subpoena blend into the general fear of government access to individual data in the light of the NSA scandals?

	
  * The illegality of some Airbnb rentals. If the subpoena succeeds and shows that a significant portion of Airbnb's business is based on illegal rentals, then that's a problem for a lot of people.

	
  * If Airbnb rentals are illegal, who is responsible (legally and morally)? Is it the host or Airbnb itself?

	
  * The validity of the law. Airbnb maintain the law is a bad law, inappropriately applied, and that the Airbnb hosts are a new class of business ("micro-entrepreneurs") that need new rules. Does new technology render the old laws obsolete?

	
  * How will this affect the $10B valuation of Airbnb and its prospects for an IPO?

	
  * How will this affect the future of the sharing economy?


The main players are, obviously, Attorney General Eric Schneiderman and Airbnb. But other players appear on the stage, including:

	
  * Airbnb hosts and guests. Hosts have the most to lose if their information is handed over.

	
  * Democrat Senator Elizabeth Krueger. Her position on the issue (see [here](http://www.nysenate.gov/press-release/behalf-regular-new-yorkers-sen-krueger-responds-airbnbs-three-principles) and [today's interview by Nancy Scola](http://nextcity.org/daily/entry/qa-new-york-senator-liz-krueger-airbnbs-doubter-in-chief)) is a bit different from that of the Attorney General, but she is broadly on the same side.

	
  * The technology industries and advocates. The [Internet Association](http://internetassociation.org/11082013airbnbamicusbrief/) and the [Electronic Frontier Foundation](https://www.eff.org/document/amicus-brief-airbnb-v-schneiderman-eff-and-cdt) have both spoken up about the subpoena, placing themselves broadly on the Airbnb side.

	
  * Neighbours, landlords, tenants, and housing co-ops. These are all affected by individuals renting out apartments through Airbnb.

	
  * The hotel industry. While Airbnb has painted hotels as one of the villains in the fight, their role seems to me peripheral.


To start with the narrowest issue: it seems pretty clear that about 2/3 of Airbnb rentals in the city are outside the law in New York, which forbids apartment rentals of under 30 days if the owner is not present. The New York Post report is [here](http://nypost.com/2014/04/21/two-thirds-of-citys-airbnb-rentals-are-illegal-apartments-state/), and is based on an affidavit by the Attorney General's office ([PDF](http://tctechcrunch2011.files.wordpress.com/2014/04/sumanta-ray-affidavit-041814-final.pdf)). That affidavit is, in turn, based on an analysis of Airbnb's business carried out by consultants Connotate for travel site [Skift](http://skift.com/2014/02/13/airbnb-in-nyc-the-real-numbers-behind-the-sharing-story/). Their report is more extensive than, but similar to, the analysis I carried out a while ago [here](http://tomslee.net/2013/11/airbnb-business-in-new-york-revisited.html). Airbnb and Peers recognize this by arguing that the law needs to be changed.

For what it's worth, I find Elizabeth Krueger's position on illegal rentals more reasonable than either the Attorney General's or that of advocacy group Peers. The Attorney General gives the impression of (at least potentially, and despite avowals otherwise) going after all the hosts who have made illegal rentals. Given that law enforcement is usually complaint-based and that Airbnb has done little to warn its hosts of their responsibilities, this seems harsh. Krueger (see links above) puts Airbnb as the root of the problem—making a lot of money off hosts and letting the hosts take all the risk—and I agree with her. Airbnb may not be legally responsible, but it seems to me morally culpable.

But what if the law is just a bad, obsolete law that shouldn't apply to Airbnb hosts anyway, which is what Airbnb has been arguing? Here the onus switches to Airbnb: has it made the case that it can do better than New York's "bad law"? It needs to do more than say "because Technology" if it's going to justify a change.

Most of the Airbnb case is made in its public policy blog posts ([here](http://publicpolicy.airbnb.com/update-airbnb-ny-ag/) and [here](http://publicpolicy.airbnb.com/new-york-airbnb-community/)), in its report on New York ([her](http://blog.airbnb.com/airbnbs-economic-impact-nyc-community/)e), and in its new sharing cities initiative ([here](https://medium.com/life-learning/db9746750a3a)). What these posts show is a remarkable lack of content, and a reliance on heartwarming words and spin that is, in the end, cheap talk.

Airbnb's description of its own hosts is at least consistent. They repeatedly describe their "community" as "regular New Yorkers who occasionally rent out their homes", or "regular New Yorkers just trying to make ends meet". They emphasize that "87 percent of Airbnb hosts rent out the home they live in". These are all phrases that invoke the "sharing economy" vision. When anything goes wrong, Airbnb refers to occasional, incredibly rare "bad apples".

But Airbnb's homespun language is carefully chosen. The 87% figure is the most obviously economical with the truth. It may be true as a percentage of hosts, but only about 63% of _listings_ are single-listing hosts, and as much as anyone can tell, almost half of actual _bookings_ are from hosts who have multiple listings. It's not easy to get definitive answers from scraping the public web site, but Airbnb has consistently refused to challenge these numbers, and so it's a good guess that they are not too far off the truth. They could release their own statistics if they chose, but they don't.

Instead, they put out "reports" that have no methodology, no definitions of key terms, and about 300 words of actual text. Airbnb makes a lot of the fact that it "supports more than 4,500 jobs" but it never says what "support" means. It claims to have "generated $104 million in economic activity outside of Manhattan", but it doesn't say what "generated" means. This may seem like nit-picking, but it isn't: it's just asking for facts instead of spin.

But where things get really bad — for Airbnb hosts who drive the company's revenue as well as for Airbnb's claim to be a responsible provider of safe and well-managed accommodation — is in Airbnb's slippery definition of its own "community".

Airbnb continually claims to speak for its hosts, as in "our hosts want to pay taxes", and repeatedly characterizes its community of "amazing" hosts as "regular" people. It also describes them as "micro-entrepreneurs", suggesting that they are independent. But Airbnb hosts, who are asked increasingly to invest in their own property in order to put it on Airbnb's marketplace, are precariously dependent on Airbnb's whims in order to make money from their investment, which is not an entrepreneurial role at all. If anything goes wrong, the host gets turfed off the market without appeal. If you're a host, how do you know if you are a "bad apple" or a "regular New Yorker"?

Most dramatically, this has happened today. After insisting for months that concerns about multiple listings were exaggerated, Airbnb today [permanently removed](http://publicpolicy.airbnb.com/new-york-airbnb-community/) no fewer than 2,000 New York listings from its platform – roughly 10% of the total. They claim the process has been going on for months, and that it demonstrates their responsibility. But the fact that it happened today of all days, the fact that identifying multiple listings is a trivial exercise, and the fact that the criteria for expulsion are still woefully unclear, makes it difficult to take them seriously ([Jason Clampet at Skift](http://skift.com/2014/04/21/airbnbs-settlement-talks-with-new-york-state-fall-apart-court-case-to-continue/) is excellent on the removals). Here is an excerpt of Airbnb's explanation:


<blockquote>But when we examined our community in New York, we found that some property managers weren't providing a quality, local experience to guests. These hosts weren't making their neighborhood stronger and they weren't delivering the kind of hospitality our guests expect and deserve. In some cases, they were making communities worse, not better. We took a hard look at our community in New York to identify these hosts and we took action.

Earlier this year, we began notifying these hosts that they and their more than 2,000 listings would be permanently removed from the Airbnb community. While we are allowing these hosts to support their existing  bookings, all are now prohibited from accepting new reservations and if you search for a place to stay in New York, you won’t find these listings.</blockquote>


Imagine you are an Airbnb host in New York reading these words. How would you know if you are living up to Airbnb's requirements? Are you making your neighbourhood stronger? Are you delivering the kind of hospitality your guests expect? This is a "[No True Scotsman](http://en.wikipedia.org/wiki/No_true_Scotsman)" argument: the Airbnb community is trustworthy because if you do anything Airbnb decides is wrong then you are not part of the community. The lack of clarity is remarkable and shows that they are not ready to provide the kind of security and accountability that any replacement for rentals regulation would need.

My skepticism over Airbnb's sincerity is heightened because, apparently, one blocking point in the negotiations with New York is that (according to Clampet), "Airbnb would not agree to limits on how many listings a person could have in New York City." It's clear that a large number of bookings is essential to the venture capital model, and goes against the spirit of the "sharing economy" that Airbnb so consistently invokes. But it looks like they're going where the money is. That makes them untrustworthy.

Airbnb's evocative but meaningless cheap talk (for more, see their [Shared Cities initiative](https://medium.com/life-learning/db9746750a3a)) is cynical. I fear that, instead of promoting any realistic idea of sharing, Airbnb will pollute the whole idea as a consequence of the high-return venture capital model it has pursued.		
