---
author: Tom Slee
categories:
- blog archive
date: 2006-05-28 09:30:29
title: Revenge of the elephant racers
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

From today's Sunday Star, how trucks slow everyone down but actually speed up traffice through bottlenecks. It sounds fine in principle -- like making sure everyone walks when there is a fire alarm clears a building quicker, the key thing is to keep traffic smooth, not to permit high speeds. Does it happen in practice? I don't do enough highway driving to know. 




Link: [TheStar.com - Revenge of the elephant racers](http://www.thestar.com/NASApp/cs/ContentServer?pagename=thestar/Layout/Article_PrintFriendly&c=Article&cid=1148681735875&call_pageid=971358637177).

<blockquote>Revenge of the elephant racers
> 
> 

> 
> Why truckers on the 401 team up to control traffic, and help everyone else in the process
> 
> 

> 
> May 28, 2006. 01:00 AM
> 
> 

> 
> ANDREW CHUNG
> 
> 

> 
> TORONTO STAR
> 
> 

> 
> Has
the thought ever occurred to you on the rig-riddled Highway 401 that
truck drivers were deliberately conspiring to prevent you, humming
along in your sleek little Celica, from getting around them?
> 
> 

> 
> Some
drivers thought so last weekend as they approached a bridge
construction zone near Belleville, where the highway lanes narrowed
from two to one. Giant tractor trailers seemed to line up side-by-side,
blocking both lanes, and slow to a speed that left a half-kilometre gap
between them and vehicles farther ahead, which were themselves
following behind another set of trucks doing exactly the same thing.
> 
> 

> 
> Eventually,
one truck let the other merge into the single lane, and everyone
slipped past the construction without much fanfare. But it was slow
moving. Some motorists became furious. A few honked their horns.
Others, with teeth bared and nostrils flaring, took to the highway's
gravel shoulder to bypass the lumbering mechanical beasts.
> 
> 

> 
> It
might be easy to flip these truckers the bird and continue on your way,
except that, as construction season begins, you should know that
traffic experts, driving instructors and even the police say these
trucks could be doing everyone a big favour.
> 
> 

> 
> Though technically
not legal, their tactics over the Victoria Day weekend on the 401
ensured that vehicles passed through the construction zone faster and
more smoothly than they otherwise would have.
> 
> 

> 
> By forcing all the
vehicles leading into the merging lanes to a slower speed, they
prevented the common stop and start "slinky" effect common to
bottlenecks on any major roadway. This, experts say, makes traffic flow
more efficiently.
> 
> 

> 
> "If you have a construction site, you have all
this manoeuvring trying to get through, and that can slow things down.
So what the truck is doing is smoothing that flow," says Eric Miller, a
civil engineering professor at the University of Toronto and a
specialist in transportation systems modelling. 
> 
> 

> 
> At the site of
a merge, you're going to find people jockeying for position, trying to
get through. This can lead to traffic "turbulence."
> 
> 

> 
> "But," says
Miller, "it's going on behind the truck, which doesn't affect the rate
at which people are going through because they're sorted out by the
time they get to the bottleneck."
> 
> 

> 
> Miller cautions this is simply a hypothesis, but it makes sense and should be studied mathematically.
> 
> 

> 
> "Flows
of vehicles on the roadway are very similar to water flowing through a
pipe or air flowing over an airplane wing," he says. Ideally, you want
the flow to be smooth, or laminar, rather than turbulent.   
Yvan
Chartrand, president and founder of the 5th Wheel Training Institute,
which has campuses in Warwick and New Liskeard, Ont., and graduates up
to 700 new truck operators each year, said the technique is simple. He
did it himself.
> 
> 

> 
> "They create a buffer zone in front of them so if
the cars ahead do stop, the trucks don't stop. If they did it well,
these truckers didn't stop. They kept going, and when it was time to
shrink down to one lane of traffic, they went one behind the other and
went past the construction, and then the cars were allowed to pass,"
Chartrand explains.
> 
> 

> 
> In the process, the truckers avoid a
situation where, near a bottleneck, they would have to keep stopping
and starting their trailers, which takes much longer and requires much
more space than a car to do so. 
> 
> 

> 
> As a driver, he says, "you
don't take the time to think these things out, you'll think these
trucks are holding you up. But if you were in a helicopter and saw how
it all plays out, you would see that when it shrank to one lane, there
was no waiting, no stopping; it was easier on the brakes, the clutch,
fuel, and it saved energy and frustration."  
Chartrand says
students are not taught such tactics as part of the school's
curriculum, but instructors pass on their experience when students ask
questions.
> 
> 

> 
> Most truckers get paid by the kilometre, not the hour, so
they need to get where they're going as quickly and efficiently as
possible.
> 
> 

> 
> You might conclude, then, that the tactic is less an act of altruism than selfishness.
> 
> 

> 
> "I
think it was probably a safe, but selfish act, to keep themselves
moving, and not force themselves to do a dangerous manoeuvre," says Ed
Popkie, the Institute's executive director.
> 
> 

> 
> Of course, car
drivers are selfish, too. They typically don't let big rigs merge into
their lanes, especially when they're rushing to get to the cottage on a
long weekend. 
> 
> 

> 
> So rather than find themselves in a situation
where they might have to wait long periods for a sympathetic car
driver, or get frustrated and possibly cut someone off, truckers
sometimes "take control of the situation," Popkie says.
> 
> 

> 
> They'll use their CB radios to call a trucker near them and arrange themselves to safely and smoothly keep their wheels moving. "You
might call out and say, `Okay, it's a go, we're going from two to one
lane up here. Let's stick side by each. I'll let you in when we get to
the end, and we'll make it through,'" Popkie says.
> 
> 

> 
> While it may end up helping everybody in a bottleneck, it's certainly not legal, police say.When
truckers travel side-by-side clogging up both lanes of a highway,
police call it an "elephant race" — because they're big and slow. 
> 
> 

> 
> "That's
an offence," says Ontario Provincial Police Sgt. Cam Woolley, adding
the OPP gets occasional complaints about the practice. "It's failing to
keep right, or unnecessarily slow driving."
> 
> 

> 
> Truckers have used blocking in the past to protest high fuel prices, he says, or simply to be mischievous. 
> 
> 

> 
> Woolley
cautions that it's not up to truckers to control traffic. "If they
wanted to maintain their own speed, to not stop and start, they should
do that in the right-hand lane."
> 
> 

> 
> Chartrand pleads common sense. He says truckers' actions, like everyone else's, must be considered in context.
> 
> 

> 
> "Is
the trucker's intent to slow the traffic up, or is it his intention to
make sure everyone gets there better and faster?" he asks. "Even though
technically it may not be legal, what's wrong with it?"
> 
> 

> 
> "It's
possible," Woolley concedes, "if they were going as fast as they could
without having to stop, it could have been a benefit to traffic, yes."
> 
> 

> 
> So the next time you find yourself in an elephant race, it may be useful to remember the story of the tortoise and the hare:
> 
> 

> 
> Slow and steady... slow and steady.
> 
> </blockquote>


		
