---
author: Tom Slee
categories:
- blog archive
date: 2007-01-14 12:11:55
title: 'Food for Thought: Anti-copyright lobby makes big business richer'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Most of the argument about copyrights these days focuses on the attempts by big copyright holders (Disney etc) to extend the reach and length of copyright. And on most of those arguments I'm in favour of restrictions on copyright. But as usual there is another side to the story, which is eluquently argued here by Sion Touhig. It's a long essay, and I'm just extracting a few pieces here. It's worth reading the whole thing.




Link: [How the anti-copyright lobby makes big business richer | The Register](http://www.theregister.co.uk/2006/12/29/photojournalism_and_copyright/).


<blockquote>We're continually being told the Internet empowers the individual. But speaking as an individual creative worker myself, I'd argue that all this Utopian revolution has achieved so far in my sector is to disempower individuals, strengthen the hand of multinational businesses, and decrease the pool of information available to audiences. All things that the technology utopians say they wanted to avoid.

> 
> 

> 
> I'm a freelance professional photographer, and in recent years, the internet 'economy' has devastated my sector. It's now difficult to make a viable living due to widespread copyright theft from newspapers, media groups, individuals and a glut of images freely or cheaply available on the Web. These have combined to crash the unit cost of images across the board, regardless of category or intrinsic worth. For example, the introduction of Royalty Free 'microstock', which means you can now buy an image for $1.00, is just one factor that has dragged down professional fees...
> 
> 

> 
> The perception is "if it's on the web, it's either free, or I'm
gonna nick it anyway because, hey, 'they' can afford it". The reality
is that there are now more copyright-free or near-free images on the
web than copyright images. Most of them will be on Flickr (owned by
Yahoo!), MySpace (owned by Rupert Murdoch's News Corporation) or the
major corporate image portals. Neither Flickr nor MySpace exist to
commercially leverage images, but clients now go there trawling for
free content, so they don't have to pay a photographer for it. It has
caused a crash in the unit cost of any images which aren't given away
and which are licensed for profit.
> 
> 

> 
> So as a consequence, the only entities that are now able to make
decent profits from photography are large corporations - because only
those corporations have the infrastructure to aggregate images into
massive hubs.
> 
> 

> 
> Fifteen years ago my sector had over a dozen photo-agencies which
worked with freelance photographers, providing images to newspapers and
magazines. Some specialized in sport, some in long-term documentary
projects, some in hard news. Some were co-ops run by their members,
some were big, some were small. In other words, the 'photo-eco-system'
was reasonably diverse and a wide variety of imagery was produced by
professional photographers earning decent fees.
> 
> 

> 
> Nearly all those agencies are out of business and now only a few
major image corporations like Getty Images, Corbis - owned by Bill
Gates - and Jupiter Images dominate the market and produce 'wholly
owned' work - the corporation owns the copyright - either from staff or
contract photographers. The work varies across the board, from high-end
stock photography to news images.
> 
> 

> 
> If wholly-owned or virtually copyright-free (more commonly known as
Royalty Free) content can be aggregated into a hub, and the economies
of scale means the hub drives out smaller competitors, then huge
profits be made.
> 
> 

> 
> Most anti-copyright arguments are based on a distaste for unfairly
held "property". But for individual authors, it's not, and never really
has been a property issue - it's our **labour** we're
talking about. Copyright exists to allow us to earn a living, but
routine flouting of this law simply strengthens the ability of large
companies to seize that labour and sit on it for profit – as **their** property.
> 
> 

> 
> In reality, what is happening on the web is the transfer of the
authors' labour to large corporations for nothing. Anti-copyright
lobbyists have become either unwitting allies, or shills, for big
business.
> 
> </blockquote>

The Register also published [a set of reader responses](http://www.theregister.co.uk/2007/01/09/photojournalism_and_copyright_letters), which are not nearly as interesting.


		
