---
author: Tom Slee
categories:
- blog archive
date: 2010-08-13 20:00:20
title: Links
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

As I seem unable to write anything myself, here are some things worth reading.




For those in and around Waterloo, Yappa Ding Ding continues to be a keen observer of our urban environment. Her recent pieces on [Silver Creek](http://yappadingding.blogspot.com/2010/08/empty-lakes-and-concrete-canyons.html) and[ King Street](http://yappadingding.blogspot.com/2010/08/waterloos-burgeoning-club-zone.html) are great examples. She deserves a wider readership, and not just because she is a friend.




The staff at world's finest video store [Generation X Video](http://www.genxvideo.com/) have been posting a huge number of movie reviews this year at their [blog](http://genxvideo.blogspot.com/). There are lots of reviews of movies I have never heard of, which in itself is great. I do want to highlight the review by Maggie of [Summer Hours](http://genxvideo.blogspot.com/2010/07/maggie-2010-round-of-resounding-recs_15.html), which is one of the best movie reviews I've read in some time.




On the other side of the ocean, Phil Edwards is often an occasional blogger who I usually read for the politics, but he has just been writing some wonderful posts about [beer](http://gapingsilence.wordpress.com/2010/08/10/so-near-my-nose/), about the sublime [Stan Rogers and his mother's gravestone](http://gapingsilence.wordpress.com/2010/08/10/rise-again/) - which you can see from the comments touched me for a couple of personal reasons - and about much else (including nice words about this here blog). I hope his fertile mood continues.


		
