---
author: Tom Slee
categories:
- blog archive
date: 2009-01-11 16:18:02
title: Sys-con media is an appalling and shameless outfit. Avoid it.
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Sys-con is commonly treated as a legitimate media organization. [Google News](http://news.google.com/news?hl=en&ned=&q=sys-con&btnG=Search+News) indexes it, for example, and software companies quote it. My personal experience suggests it is shameless, and that reputable people and organizations should avoid it.

Here's the story. I see that [others](http://weblogs.macromedia.com/jd/archives/2005/10/google_news_pri.html) have experienced something similar.

In October I wrote [a blog post](http://whimsley.typepad.com/whimsley/2008/10/cloudy-monopolies-ii.html) about cloud computing. I received this nice email from sys-con's Jeremy Geelan ("Sr. Vice-President, Editorial and Events"):

Would you be cool with our republishing the post below in full, with your byline and bio (plus a
link back to the original URL) at
[
http://cloudcomputing.sys-con.com](http://cloudcomputing.sys-con.com/)?  
  
[
http://whimsley.typepad.com/whimsley/2008/10/cloudy-monopolies-ii.html](http://whimsley.typepad.com/whimsley/2008/10/cloudy-monopolies-ii.html)  
[
](http://whimsley.typepad.com/whimsley/2008/10/cloudy-monopolies-ii.html)  
[
](http://whimsley.typepad.com/whimsley/2008/10/cloudy-monopolies-ii.html)We try and do this across all our many and varied sites from time to
time by adding insightful posts by writers outside our immediate circle.
It's our way of introducing fresh new voices and technologies to our
audience...  
  

So, let us know, yes? Thank you - meantime have a great Tuesday!
:)  
  

Jeremy G.   





  

A colleague of mine has been to a couple of conferences organized by sys-con. A quick look at their website suggested they are one of those gazillion or so Silicon Valley tech. news sites. So I thought, OK, I know there's no money, and I'm displacing real columnists and it's digital sharecropping, but let's see how it goes. I said OK and they republished the post. No one came through to my blog from their publication, which surprised me, and I did have to tell them to remove a copyright notice which claimed copyright for sys-con, which should have warned me off, but so it goes.

Then in December I looked at my incoming traffic and saw someone had come from Yacht Vacations and Charters Magazine, which also includes my post [here](http://www.yachtchartersmagazine.com/node/725544). I have no interest in my name being associated with anything that looks like a front for advertising junk so I wrote to sys-con at the email address they provided (seta@sys-con.com) saying this:

I recently gave permission for SYS-CON
to reproduce a piece of mine in a journal on cloud computing. I now see
it posted as a commentary in Yacht, Vacation, and Charters magazine. It
is completely inappropriate for that place and I did not give
permission for its use in that context. Please remove it.  
  
The piece I am referring to can be found at [http://www.yachtchartersmagazine.com/node/725544](http://www.yachtchartersmagazine.com/node/725544).  





  
The email bounced. I sent it to another sys-con email address I found. I heard nothing.

Then yesterday I get someone coming to my blog from a third sys-con "magazine", CRM ("The First and Only Independent Magazine Serving CRM Developers"): from [here](http://crm.sys-con.com/node/725544) to be precise. Also inappropriate, also without permission. Plain wrong.

So I googled some text in the article, and it turns out that sys-con has posted my piece on 19 different sites ([here](http://www.google.ca/search?q=%22Is+infrastructure+cloud+computing+a+natural+monopoly%3F+I+suspect+there+will+be+enough+fragmentation+in+the+kinds+of+offering+available+that+a+demand+for+variety+will+make+it+more+like+the+automobile+industry+than+like+the+online+bookstore+industry.%22) is the list). 

I guess I could ask them to remove it again, but this is so obviously bad faith that I'll just post this and unleash the awesome power of my internet influence instead. Plus, when I get back to work, I'll write to the marketing people at work and tell them to stay well away from sys-con. 

Emphasis on the con.


		
