---
author: Tom Slee
categories:
- blog archive
date: 2010-11-11 23:45:51
title: 'Macrowikinomics 2: Ushahidi and Information as Bottleneck'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

_Macrowikinomics_ opens with the rescue of a young Haitian girl after the earthquake of January 2010. Some of her rescuers were far away in the USA: as soon as the earthquake struck, a group of American volunteers put together a web site using [Ushahidi](http://www.google.com/url?q=http%3A%2F%2Fwww.ushahidi.com&sa=D&sntz=1&usg=AFQjCNFkf_NBtWGi0OELK89pd8TlhtL3yw), the Kenyan-created “crisis mapping” software, and together with expatriate Haitians started to turn text messages and tweets into points on a map that could be shared with aid workers. In doing so, they “found themselves center stage in an urgent effort to save lives during one of the largest relief operations in history” [5], and helped to save the seven-year-old.




Macrowikinomics presents Ushahidi a “new paradigm for humanitarian efforts” that




<blockquote>

> 
> turns much of the conventional wisdom upside down. Rather than sit idly by waiting for help, victims supply on-the-ground data using cell phones or whatever communication channels are open to them. Rather than simply donate money, a self-organized network of volunteers triages this data, translating and authenticating text messages and plotting incidents on interactive mapping displays that help aid workers target their response” [6].
> 
> 
</blockquote>




The “Mass-collaboration” approach is a contrast to “the old crisis management paradigm” in which “big institutions and aid workers parachute into a crisis, assess the situation, and dispense aid with the limited information they have” [6]. 




It is admirable that volunteers would put so much effort into helping people in crisis, and it is good that this software enabled them to make a contribution. But is Ushahidi “a new paradigm” for urgent relief operations? Does it really change idle victims and passive donors into active participants? And how much of a contribution did it really make to dealing with the Haiti earthquake? I want to spend a whole post on these questions because the story sets the tone for the whole book.




**Is Information the Bottleneck?**




In a fine talk posted on YouTube just today, IT researcher [Kentaro Toyama](http://www.youtube.com/watch?v=E_mTwm5m8DM) talks of the _Five Myths of Information Technologies for International Development_. One of these myths is that “Information is the Bottleneck”. 




Toyama asks his audience why they are not richer, more educated, and more compassionate than they are, given that they would like to be and that the information needed to become so is available to them (eg, MIT’s Open Courseware)? The answer he gives is that information is not bottleneck to achieving any of these goals. It’s a theme I have [touched on before ](http://www.google.com/url?q=http%3A%2F%2Fwhimsley.typepad.com%2Fwhimsley%2F2010%2F01%2Fdigital-activism-if-information-is-not-the-problem-information-is-not-the-solution.html&sa=D&sntz=1&usg=AFQjCNEVM56fKVWAHZ7KqCcises9nWPalA)in the context of digital activism and which will come up again in these posts, and it applies to crisis response too.




In crisis situations, and in aid operations more generally, information may not be the main problem. As Toyama says on [his blog](http://www.google.com/url?q=http%3A%2F%2Fict4djester.org%2Fblog%2F%3Fp%3D180&sa=D&sntz=1&usg=AFQjCNGPlFVDBXrzZrVmYbCmeU53DieUFg), the Ushahidi effort is two distinct things: (1) the technology platform and (2) the individuals who built and use it, and who are dedicated to helping. 




<blockquote>

> 
> “Much of the excess hype around Ushahidi comes from people who think that (1) is the secret sauce, and that it offers a new hope for development. But, actually, it’s (2) that makes Ushahidi great, and it’s not particularly new. ... for aid purposes, even (1) and (2) only go so far, because (3) is missing. And, what’s (3)? (3) is human/institutional intent and capacity on the ground. As wonderful as Ushahidi (1)+(2) is, it makes no difference if there isn’t (3), a force on the ground that can actually respond meaningfully to the noisy information (1)+(2) produces. In the case of Haiti, response teams were already overwhelmed. Additional information, per se, was only adding to the unread mail.”
> 
> 
</blockquote>




And here is my favourite book on international aid, Elizabeth Pisani’s [The Wisdom of Whores](http://www.google.com/url?q=http%3A%2F%2Fwww.wisdomofwhores.com%2F&sa=D&sntz=1&usg=AFQjCNG3T2xX-Pm6O0ujAFsgi5UjBtWajQ), on information as it affected the AIDS effort:




<blockquote>

> 
> “We were collecting more and more really good information, and then not acting on it. Two things were getting in the way - ideology and money. In the AIDS industry, we have too much of both.” [11]
> 
> 
</blockquote>




**Ushahidi in Haiti**




I can find only a few public attempts to evaluate the Ushahidi effort in Haiti. One is a 16-page[ ](http://www.google.com/url?q=http%3A%2F%2Fwww.usip.org%2Fpublications%2Fcrowdsourcing-crisis-information-in-disaster-affected-haiti&sa=D&sntz=1&usg=AFQjCNEg4Xtx7UD7eeduI3Lx_WEIiIhJRQ)[report](http://www.google.com/url?q=http%3A%2F%2Fwww.usip.org%2Fpublications%2Fcrowdsourcing-crisis-information-in-disaster-affected-haiti&sa=D&sntz=1&usg=AFQjCNEg4Xtx7UD7eeduI3Lx_WEIiIhJRQ) published in September by the United States Institute for Peace, an organization that donated to the effort. It describes some of the contributions that Ushahidi effort made, but presents little in the way of evaluation or analysis. A set of thoughtful reflections by Jaro Valuchi is posted at[ ](http://www.google.com/url?q=http%3A%2F%2Fpakreport.org%2Fblog%2F%3Fp%3D26&sa=D&sntz=1&usg=AFQjCNGu_ShPRJhl63mP_IuAtu4AqzbU4g)[pakreport.org](http://www.google.com/url?q=http%3A%2F%2Fpakreport.org%2Fblog%2F%3Fp%3D26&sa=D&sntz=1&usg=AFQjCNGu_ShPRJhl63mP_IuAtu4AqzbU4g). A [reflection by audiencescapes](http://www.google.com/url?q=http%3A%2F%2Fwww.audiencescapes.org%2Frole-media-humanitarian-crises-potential-lessons-haiti-CDAC-Ushahidi-DISA_TISC-internews&sa=D&sntz=1&usg=AFQjCNHo-KHZI4x9xgzTqmLUlkqiMnq8Ug) is doubtful of the impact of Ushahidi and of crowdsourcing:




<blockquote>

> 
> Despite the enthusiasm surrounding mobile communications, they have real limitations in an environment such as Haiti where most households lack access to the electrical grid and the mobile subscription rate is less than 45 percent. Even Thompson-Reuters, which launched a service that allowed survivors of Haiti's earthquake to receive critical information by text message directly to their phones, free of charge, only had 24,000 people register.
> 
> 

> 
> This is a recognized limitation even by the resource’s proponents. Where the tool draws its strength is in its ability to provide “real-time” information. Ushahidi’s answer to critics of crowdsourcing’s lack of verifiability is [SwiftRiver](http://www.google.com/url?q=http%3A%2F%2Fswift.ushahidi.com%2F&sa=D&sntz=1&usg=AFQjCNFUFEMM_Knxf2vvHi_dd7TczwnsHA), a new open source software platform that acts as a verifying filter that sifts through information through the multiplicity of channels that feeds crowdsourcing. However, the platform has only just recently been made available to the public, so it too is somewhat untested.
> 
> 

> 
> The question of how useful Ushahidi was during the crisis in Haiti for the most part remains unanswered.
> 
> 
</blockquote>




Another is a pair of articles by Paul Currion, an IT specialist who runs a consultancy for humanitarian operations. He[ ](http://www.google.com/url?q=http%3A%2F%2Fmobileactive.org%2Fhow-useful-humanitarian-crowdsourcing&sa=D&sntz=1&usg=AFQjCNEDcWdMF5kuxJX4Z1tmBD6JV0yrkQ)[studied](http://www.google.com/url?q=http%3A%2F%2Fmobileactive.org%2Fhow-useful-humanitarian-crowdsourcing&sa=D&sntz=1&usg=AFQjCNEDcWdMF5kuxJX4Z1tmBD6JV0yrkQ) the roughly 3,000 messages that came in to the Ushahidi effort over the 4646 shortcode that was set up for the purpose and his efforts resulted in frustration:




<blockquote>

> 
> In the end, I was reduced to bouncing around the Ushahidi map, zooming in and out on individual reports – not something I would have time to do if I was actually in the field. Harsh as it sounds, my conclusion was that the data that crowdsourcing of this type is capable of collecting in a large-scale disaster response is operationally useless...
> 
> 

> 
> Disaster response on the scale of the Haiti earthquake or the Pakistan floods is not simply a question of aggregating individual experiences. Anecdotes about children being pulled from rubble by Search and Rescue teams [such as that told on the first page of Macrowikinomics - ed] are heart-warming and may help raise money for aid agencies but such stories are relatively incidental when the humanitarian need is clean water for 1 million people living in that rubble. Crowdsourced information – that is, information voluntarily submitted in an open call to the public – will not ever provide the sort of detail that aid agencies need to procure and supply essential services to entire populations.
> 
> 

> 
> That doesn't mean that crowdsourcing is useless: based on the evidence from Haiti, Ushahidi did contribute to Search and Rescue (SAR). The reason for that is because SAR requires the receipt of a specific request for a specific service at a specific location to be delivered by a specific provider – the opposite of crowdsourcing. SAR is far from being a core component of most humanitarian responses, and benefits from a chain of command that makes responding much simpler. Since that same chain of command does not exist in the wider humanitarian community, ensuring any response to an individual 4636 message is almost impossible.
> 
> 
</blockquote>




Currion asks “could crowdsourcing add value to humanitarian efforts?” and answers himself:




<blockquote>

> 
> Perhaps it could. However, the problem is that nobody who is promoting crowdsourcing currently has presented convincing arguments for that added value. To the extent that it's a crowdsourcing tool, Ushahidi is not useful; to the extent that it's useful, Ushahidi is not a crowdsourcing tool.
> 
> 
</blockquote>




The article provoked some useful discussion (a critical response from Robert Munro, who was part of the text message processing effort, is[ ](http://www.google.com/url?q=http%3A%2F%2Fwww.junglelightspeed.com%2Fevaluating-crowdsourcing%2F&sa=D&sntz=1&usg=AFQjCNHTU_boHePp9bZOAvWQ4N-sTx7nsg)[here](http://www.google.com/url?q=http%3A%2F%2Fwww.junglelightspeed.com%2Fevaluating-crowdsourcing%2F&sa=D&sntz=1&usg=AFQjCNHTU_boHePp9bZOAvWQ4N-sTx7nsg)) and a[ ](http://www.google.com/url?q=http%3A%2F%2Fwww.humanitarian.info%2F2010%2F10%2F31%2Fpostscript-humanitarian-crowdsourcing%2F&sa=D&sntz=1&usg=AFQjCNEwIzI45y4VBt5HwNitUmnXLr1dJw)[follow-up](http://www.google.com/url?q=http%3A%2F%2Fwww.humanitarian.info%2F2010%2F10%2F31%2Fpostscript-humanitarian-crowdsourcing%2F&sa=D&sntz=1&usg=AFQjCNEwIzI45y4VBt5HwNitUmnXLr1dJw) from Currion, in which he concludes:




<blockquote>

> 
> there’s a lot of grandiose yet vague promises that crowdsourcing will revolutionise humanitarian response, and I think we need more than vague promises. Misinformed reporting plays a role in my frustration, but nobody seems to be interested in correcting that misinformation – and when people persist in claiming that their tool will revolutionise the sector based on no evidence, I get suspicious.
> 
> 

> 
> When I was writing the article, I could only judge whether crowdsourcing added value based on the evidence that was available to me – just like everybody else. If presented with new evidence (perhaps an expanded dataset or actual testimonials), I’m prepared to change my opinions – but nobody has presented any such evidence, and we just get repeated anecdotes about how the director of FEMA really liked the Ushahidi map. In particular I asked whether anybody had a clear use case scenario, but none has been forthcoming.
> 
> 
</blockquote>




Those on the inside also recognize that Ushahidi is a complementary tool to other efforts rather than “a new paradigm”. Chris Blow, “one of the longest serving community members”,[ ](http://www.google.com/url?q=http%3A%2F%2Fblog.ushahidi.com%2Findex.php%2F2010%2F05%2F19%2Fallocation-of-time-deploying-ushahidi%2F&sa=D&sntz=1&usg=AFQjCNFFetNrXRZuQCVoFWohYhpO9seu2A)[makes the point](http://www.google.com/url?q=http%3A%2F%2Fblog.ushahidi.com%2Findex.php%2F2010%2F05%2F19%2Fallocation-of-time-deploying-ushahidi%2F&sa=D&sntz=1&usg=AFQjCNFFetNrXRZuQCVoFWohYhpO9seu2A) that “Systems like Ushahidi have turned enormous communication barriers into a trivial installation and training process. But there is a whole other 90% of real work”. 




In other words, Ushahidi and other software projects are one more way that people with a particular set of skills can contribute to disaster relief, but they are no more (and no less) valuable than many other efforts that don’t get attention from high-profile media and books. In a theme that will be repeated throughout this review, the closer you look at examples of Internet-based collaboration, the more they look like a new medium for realizing old (and often admirable) commitments. There is no paradigmatic shift separating Oxfam and Ushahidi.




Clay Shirky also highlights Ushahidi’s impact on reporting electoral violence in several places in his recent book Cognitive Surplus, and again makes the comparison between the information Ushahidi provides and that of the mainstream media, suggesting a fault line between old ways of doing things and the promises of the new technology. But the comparison is again misleading. Mainstream media has never been the way that those on the ground get their information about politically charged events. Information about human rights abuses in Central America during the 1980’s spread throughout North America via networks of solidarity groups, small independent publications, and courageous individuals who went to record what was happening and came back with their reports. Is our collective understanding of violence in Congo today better than that of El Salvador 30 years ago? Not noticeably. The dividing line between activists and mainstream media is not erased by the Internet world.




**Turf wars**




One of the benefits of self-organized mass collaboration, according to Macrowikinomics, is that crowdsourcing avoids the inter-organizational turf wars that plague old-style aid institutions. The authors are damning of the old ways of doing things, claiming that the top-down approach leads to “poor decision making, redundancy, and confusion, and often to wasted money and wasted opportunities. To make matters worse, the end recipients of disaster relief are almost always treated as helpless victims and passive consumers of other people’s charitiy.” [6] Harsh words, and ones that many grass-roots aid organizations involved in Haiti may argue with.




But does the digital paradigm avoid these problems? The answer is no.




Ushahidi plotted incidents and reports on maps of Haiti, but getting realistic maps of post-earthquake Haiti was far from simple. Ushahidi relied on the work of volunteers from [OpenStreetMap](http://www.google.com/url?q=http%3A%2F%2Fwww.openstreetmap.org%2F&sa=D&sntz=1&usg=AFQjCNE2l1DU4af95mpmA7Rv2dlhs-0SOA) (OSM), a remarkable effort to build “a free editable map of the whole world” using volunteer contributions. OpenStreetMap was not the only effort to map Haiti during the crisis; other teams were using Google MapMaker. It would have been better if the two efforts could have been combined to avoid wasteful duplication, but that was not possible, at least in the crucial early days,[ ](http://geosquan.blogspot.com/2010/01/haitian-earthquake-emphasizes-danger-of.html)[despite good intentions](http://geosquan.blogspot.com/2010/01/haitian-earthquake-emphasizes-danger-of.html). The problem was[ ](http://www.google.com/url?q=http%3A%2F%2Fblog.fortiusone.com%2F2010%2F01%2F15%2Fthe-case-for-using-creative-commons-zero-for-disasters%2F&sa=D&sntz=1&usg=AFQjCNH9YSAG3oceGn0MZysJmpNL8eR50Q)[licensing](http://www.google.com/url?q=http%3A%2F%2Fblog.fortiusone.com%2F2010%2F01%2F15%2Fthe-case-for-using-creative-commons-zero-for-disasters%2F&sa=D&sntz=1&usg=AFQjCNH9YSAG3oceGn0MZysJmpNL8eR50Q). As a Google representative[ ](https://groups.google.com/group/mapping-howto/browse_thread/thread/500cc41e29183469?hl=es&pli=1)[explained](https://groups.google.com/group/mapping-howto/browse_thread/thread/500cc41e29183469?hl=es&pli=1) on a forum:




We have previously sponsored OSM's efforts and explored with them how to work together. A sticking point in these past discussions has been OSM's share-alike license clause, according to which any data we combine with their data set must be shared back to OSM. Since we routinely combine proprietary 3rd party and user-contributed data sets on Google Maps in order to create the world's richest base map, we cannot share these combined data sets back to OSM.




Efforts by the Open Geospatial Consortium helped to resolve some of the duplication, but blogger Matt Ball[ ](http://www.google.com/url?q=http%3A%2F%2Fvector1media.com%2Fspatialsustain%2Fwhat-can-be-learned-from-the-volunteer-mapping-efforts-for-haiti.html&sa=D&sntz=1&usg=AFQjCNG9mlDMBBIah2cvYPvlPm57QswXVQ)[concluded](http://www.google.com/url?q=http%3A%2F%2Fvector1media.com%2Fspatialsustain%2Fwhat-can-be-learned-from-the-volunteer-mapping-efforts-for-haiti.html&sa=D&sntz=1&usg=AFQjCNG9mlDMBBIah2cvYPvlPm57QswXVQ) that “While all these efforts were helpful, clearly more work needs to be done for greater coordination and easier portability of data between different platforms and different creators and users of the data.” So turf wars, in the form of data licenses, complicated the digital activists efforts just as they complicate the work of other aid groups.




**Conclusion**




The lesson here is not that Ushahidi is a failure or a waste of time. But the evidence so far shows that it is a valuable but small contribution to the daunting task of disaster relief. New technology can help humanitarian operations, but it needs to be seen as a complement to existing work, not “a new paradigm for humanitarian efforts”. The difference between digital “self-organization” and the aging institutions criticized throughout Macrowikinomics is not so big - both are plagued by issues such as legal contracts, confusion, contradictory commitments, and even rivalries. People are people, whether they interact digitally or face to face. In the end, it’s people on the ground that matter the most, and governments, large NGO’s and experienced staff - for all their clumsiness and bureaucracy - will continue to be central to crisis relief efforts.




The Ushahidi effort in Haiti points to one of the central problems with MacroWikinomics: if information is not the problem, then information is not the solution. Viewing the world through a technology-centric, information-centric lens leads us down the wrong path as we try to diagnose the ills of society and to build a better world.


		
