---
author: Tom Slee
categories:
- blog archive
date: 2015-09-26 18:58:40
tags:
- '1099'
- liss-riordan
- uber
title: More employee/contractor cases
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Boston lawyer Shannon Liss-Riordan has brought two new lawsuits against on-demand delivery companies, claiming that those doing the deliveries should be classified as employees rather than as contractors. [Cyrus Farivar ](http://arstechnica.com/tech-policy/2015/09/two-more-on-demand-delivery-startups-sued-over-alleged-labor-violations/) writes about these newest cases, against GrubHub and DoorDash), while [Davey Alba](http://www.wired.com/2015/09/doordash-grubhub-caviar-labor-suits/) lists the companies sued so far:



	
  * [GrubHub](https://www.documentcloud.org/documents/2432051-grubhub-class-complaint.html)

	
  * [DoorDash](https://www.documentcloud.org/documents/2432052-doordash-class-complaint.html)

	
  * Handy

	
  * Homejoy (now out of business)

	
  * [Washio](http://www.plainsite.org/dockets/2n6onghu1/superior-court-of-california-county-of-san-francisco/barry-taranto-v-washio-inc/)

	
  * Postmates ([here](http://www.bizjournals.com/sanfrancisco/news/2015/07/01/shyp-washio-postmates-sued-uber-lyft-caviar.html) for these three)

	
  * Lyft

	
  * Caviar

	
  * Instacart (has reclassified part of its workforce as a response)

	
  * Shyp (ditto)

	
  * [Uber](http://arstechnica.com/tech-policy/2015/09/uber-now-faces-class-action-lawsuit-in-california-over-expenses-tips/)


A federal judge in San Francisco recently granted class action status to a group of four Uber drivers, making this the first case to be certified as a class action.

(If you want some background on these cases, try [Susie Cagle](http://america.aljazeera.com/opinions/2015/6/worker-protections-theres-no-app-for-that.html)'s illustrated op-ed from June.)

The main argument against employee status has been the flexibility that supposedly comes with service provider status: service providers choose when to work and when not to work. [Benjamin Sachs](http://onlabor.org/2015/07/15/new-dol-guidance-on-employee-status-news-for-uber-or-lyft/#more-5299)  describes a new Interpretation of the Fair Labor Standards Act by the US Department of Labor, which makes it clear that there is more to the definition than just flexibility:


<blockquote>employee status under the FLSA is to be determined according to an “economic realities” test. With respect to the economic realities test, moreover, the Interpretation emphasizes that the test turns on a determination of whether the worker is “economically dependent on the employer (and thus its employee) or is really in business for him or herself (and thus its independent contractor).</blockquote>


A driver putting in 50 hours a week in a car leased by Uber, to take one extreme, is clearly dependent on Uber. A driver putting in a few hours here or there, and also driving for Lyft, is much less dependent.

More from Sachs:


<blockquote>What is the Nature and Degree of the Employer’s Control”  Control is the last factor in the six-prong test, and it’s the last one the Interpretation discusses, but it may be the most relevant for Uber and Lyft.  Why? Because the Interpretation takes up, and then dispenses with, two of the most common views about why on-demand workers ought to be considered independent contractors. First, the Interpretation states that the lack of direct supervision over how work is carried out is “largely insignificant” when workers work offsite. And, second, the Interpretation states that workers’ ability to determine _when _they work is also “not indicative of independent contractor status.”  Citing the Third Circuit’s _DialAmerica Marketing_ decision, the Interpretation thus concludes that “the fact that the workers could control the hours during which they worked and that they were subject to little direct supervision was unsurprising given that such facts are typical of homeworkers and thus largely insignificant in determining their status.”  In other words, you can be an employee even if you set your own hours and are never directly supervised.  This is a conclusion with unmistakable relevance to the on-demand debate.</blockquote>


Those defending companies' rights to classify their workers as independent contractors often warn that if the court cases succeed, then service providers will lose the flexibility that is part of the appeal of "gig economy" work:


<blockquote>“The way we look at it, the laws governing employers require [them] to exert much more control over their employees, monitor, make sure they’re taking break times,” Ted Boutrous, Uber’s lawyer, said in a press conference last week. “It’s inevitable the flexibility and autonomy that drivers crave would have to be limited.” A spokesperson added that managing overtime would be another reason Uber would have to assign shifts.</blockquote>


That's from [Carmel DeAmicis](http://recode.net/2015/08/11/despite-ubers-arguments-flexibility-for-employees-is-a-companys-choice/) of re/code, who writes very smartly about this. She goes on:


<blockquote>They’re stretching the truth. Labor laws don’t prohibit flexible working conditions. If drivers were legally employees, they could still drive one hour one week and 40 the next. In a business like Uber’s, where apps track when workers are logged in, it would be easy for a company to send a push notification to people after four hours of work, requiring them to take a 15 minute break, or for the app to turn off after a 40-hour workweek to prevent overtime. Monitoring drivers would be easy for a company whose algorithms have optimized pricing at all hours.</blockquote>


[Benjamin Sachs](http://onlabor.org/2015/09/25/uber-employee-status-and-flexibility/) also writes about the supposed loss of flexibility that would come with employee status:


<blockquote>If a court determines that these facts are consistent with a finding of employment, the drivers would be “employees.”  But Uber would not somehow then be required to exercise additional control over when and how long the drivers worked, or over other aspects of the job that are currently flexible.  Uber _would _be required to comply with minimum wage laws, safety and health laws, and anti-discrimination laws, and it would be required to contribute to unemployment insurance and withhold payroll taxes and the like.  But it could do all of this without taking away the flexibility that the drivers currently enjoy.</blockquote>


The big problem for Uber and others is that right now they have a cheap labour force who take all the risks associated with providing the service. Uber's business model is based on avoiding regulations: it knows full well that most of its drivers do not have proper insurance for the work they do (I am sure this is one of the reasons that they never break down driver expenses in their claims about income), and may or may not pay full taxes on their income.



		
