---
author: Tom Slee
categories:
- blog archive
date: 2009-09-04 11:20:17
title: 'Google Book Settlement: I think I opted out'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This morning I opted out of the [Google Book Settlement](http://www.googlebooksettlement.com/). At least, I think I did. After going through the forms and clicking the buttons there is a generic page saying something like "your opt-out has been received".  But I have no receipt, no acknowledgement - in short, no proof that I have opted out. Very odd. I emailed Rust Consulting (the settlement administrator) and assume I will get something sometime, but it seems very amateurish for what they keep telling us is such an important change.

As for why I opted out, well I hope to write about that. But I have a deadline for next weekend and a busy time at home (never mind the day job), so I can't do that right now, and this blog will continue to be quiet for a while.

**Update:** After emailing the settlement administrator, I did get an email confirming my opt-out.


		
