---
author: Tom Slee
categories:
- blog archive
date: 2012-12-29 10:51:58
title: 'Wikibollocks Alert: Peer-to-peer sharing went big in 2012'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Wikibollocks entry for today comes from Grist magazine, a "source of nonprofit, independent green journalism", who just ran [a piece on peer-to-peer sharing](http://grist.org/news/peer-to-peer-sharing-went-big-in-2012-and-so-did-opposition) which includes sentences like this.




<blockquote>

> 
> We’re choosing peer-to-peer because we want to do business differently. We actually kind of want to pretend like we’re not doing business at all.
> 
> 
</blockquote>




Some questions for Grist.






  * Why do you think that you are on the same side as Uber (based in the SF Bay area, funded by Jeff Bezos, Goldman Sachs, and a host of venture capitalists), Sidecar (based in the SF Bay area, funded by Google and other venture capitalists), and Lyft (based in San Francisco, in early-stage VC funding) and AirBnB (based in San Francisco, funded by Jeff Bezos, Andreessen Horowitz, Crunch Fund, Ashton Kutcher and other venture capitalists)?


  * Does it not occur to you that when billionaires promote "pretending like we're not doing business at all" then maybe there's something a bit dodgy going on?


  * When Jeff Bezos (personal wealth $18.4B) and Marc Andreessen (personal wealth, $600 million) are one one side and taxi drivers are on the other, what makes you think that Bezos and Andreessen are the progressive side?




Look, Grist, I understand that words like "peer-to-peer" and "sharing" sound nice and egalitarian, but in pieces like this you're actively working against the things you claim to stand for.





		
