---
author: Tom Slee
categories:
- blog archive
date: 2011-10-06 22:30:47
title: 'Broken Promises: Following Your Dreams, and the 99 percent'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This speech by Steve Jobs has been posted in many places over the last 24 hours:







It is a strange speech: quite moving, personal, modest, and thoughtful. But in the end it’s a “follow your dreams” speech, and as such is quite a contrast to another Internet event of the moment, the very moving stories being posted at [We are the 99 percent](http://wearethe99percent.tumblr.com/).




“Follow your dreams” invokes a cosmic bargain (fortune favours the brave) and it also invokes a social bargain: that if you work hard, and have a little luck, society will ensure that your efforts are rewarded. Meanwhile, the "we are the 99%" posters “sense that the fundamental bargain of our economy – work hard, play by the rules, get ahead – has been broken, and they want to see it restored” (Felix Salmon, quoted [here](http://www.thestar.com/business/article/1065057--olive-99-percenters-are-literally-sick-of-being-left-out)).




So nothing against the guy, but over the next few days I’ll think more about what the 99%-ers say than what Steve Jobs said at Stanford. One of the stories he tells is of dropping out of college and, instead, monitoring courses independently. It's an inspiring story, but the contrast to [this post](http://wearethe99percent.tumblr.com/post/11123269648/20-years-old-dropped-out-of-college-because-i), made today, is glaring.


		
