---
author: Tom Slee
categories:
- blog archive
date: 2016-07-02 02:08:12
title: 'Airbnb in Lisbon: a few corrections'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				Airbnb just posted one of its charming city reports providing an Overview of The Airbnb Community in Lisbon and Portugal. The summary is [here ](https://www.airbnbaction.com/the-airbnb-community-contributes-e268-million-in-economic-activity-to-lisbon/)and the full report is [here](https://1zxiw0vqx0oryvpz3ikczauf-wpengine.netdna-ssl.com/wp-content/uploads/2016/06/Portugal_EIS_English_20160627b.pdf). At the prompting of some Lisbon urban geographers and activists concerned about the damage Airbnb is doing to the historic centre of their city, I've done some surveys of Lisbon.

The Airbnb report, as usual, presents some concrete figures, leaves out some other figures, and also presents a lot of figures that are not very interesting at all. It does so with the company's traditional absence of supporting data or methods. Let's look at a few of the most important.

Airbnb: "More than 4,500 hosts shared their space on Airbnb last year"

My results: Between May 2015 and May 2016,  I identify 4633 separate hosts who have properties with reviews. There are over 6000 separate hosts with listings on the site. The Airbnb statement confirms the data I have collected.

Airbnb: 72 percent of hosts in Lisbon have only one listing and hosts have lived in the city for an average of 25 years

My results: In my most recent survey, 71% of hosts have only one listing, confirming Airbnb's statement.

What Airbnb doesn't say: 65% of listings in Lisbon belong to hosts with multiple listings. The majority of listings in Lisbon do not belong to regular folks who use the site only to occasionally rent out the home in which they live. The number of "multiple listing" hosts is growing even faster than the overall number of listings. The total number of listings almost doubled between May 2015 (5600) to June 2016 (over 10,000), and the percentage of listings belonging to multiple-listing hosts has grown from 59% of the total to 65% of the total. To me, this "percent of hosts with only one listing" is always the most deceptive of Airbnb's phrasings, and in the case of Lisbon it is particularly misleading.

Airbnb: A typical listing in Lisbon is shared for 76 nights a year and more than half of all listings in Lisbon are rented for fewer than 90 days.

My results: I don't have reliable occupancy data, but this claim also is noticeable for what it doesn't say. There are about 2,000 Lisbon listings with no reviews at all: clearly a host with no guests causes no problems and makes no money, but using a median value (the "typical" listing) gives each of these listings equal weight. What is of interest is those at the top end: and of course there is not much said here. We can infer that almost half are rented for more than 3 months in the year, but we don't know the concentration at the top end.

What we do know is that the areas with most listings (Santa Maria Maior and Misericordia) have a disproportionate share of the business. Between them, they have about 40% of the listings but well over half of the visits, and (with prices there being more expensive) an even bigger share of the revenue. You can get a better idea of what this means by looking at the maps here (taken from my [listings page](http://tomslee.net/airbnb-data)), and download a full set of listings with each one:



 	
  * [March 2015](https://www.google.com/fusiontables/DataSource?docid=1B1DIDorICeH0LCxzaA6uqUN94M411S2NLo6iKr6V)

 	
  * [March 2016](https://www.google.com/fusiontables/DataSource?docid=1ArRl9V5Xx3_lZ67wB8hTMt10mcePSHJGl6-aIoW-)

 	
  * [June 2016](https://www.google.com/fusiontables/DataSource?docid=1bf6ZosybJKUWugoxsbFU6U2ayAa8pl-4ivGmyDHx)


Airbnb's continued presentation of partial and biased "data" about its activities in cities around the world shows their lack of interest in accountability and, ultimately, their lack of interest in the cities where they operate.		
