---
author: Tom Slee
categories:
- blog archive
date: 2007-03-29 00:19:34
title: The Long Tail 12 - The Infinite Screen
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

This is another part of my critical reader's companion to _The Long Tail_, and it discusses Chapter 12 - The Infinite Screen. Part 0 is [here](http://whimsley.typepad.com/whimsley/2007/02/my_next_several.html). You can find a complete list of the Long Tail pieces [here](http://whimsley.typepad.com/whimsley/2007/03/the_long_tail_l.html).

* * *

Should we give Chris Anderson a break when it comes to Google Video? 




The second sentence of Chapter 12 is "On January 19, 2006, Google unveiled Google Video, the ultimate Long Tail marketplace of the moving image" [193]. Of course, Google Video has been what us pre-digital folks call a "total bust" and YouTube (which doesn't get a mention in the book) is everywhere - so much so that Google bought it.




Well, in January 2007 Chris Anderson [admitted that he got it wrong](http://www.longtail.com/the_long_tail/2007/01/the_beginners_g.html):

<blockquote>This is not to say that there aren't many things I don't cover in the book but should have, and a few things I _did_ cover but shouldn't have *cough* Google Video *cough*. 
> 
> </blockquote>

So yes, let's give him a break. I mean, who knew? Not me. So let's put it on record that I'm giving him a free pass on this one. 




But back to the point. Chapter 12 argues that TV is facing a Long Tail challenge from Internet video, and it starts off by charting the rise of Internet video with a comparison:

<blockquote>MSNBC's The Abrams Report, with a multimillion-dollar budget and a crew of dozens was at the time of this writing watched by an average of 215,000 homes per day. Rocketboom, a Jon Stewart-like comedy news program created online by exactly two people for the cost of some videotapes, two lights, and a cardboard map, was watched by 200,000 homes per day over the same period. Now it's selling advertising and got $40,000 for the five thirty-second spots in its first week. Not quite as high as broadcast TV revenues, perhaps, but the networks would kill for those margins.  
...A generation that grew up online and developed its media consumption habits in the bandwidth paradise of American university dorm rooms is now totally comfortable watching video on a computer screen. [193]
> 
> </blockquote>

Rocketboom may be a comedy news program (5 minutes per day) but let's just note it isn't news. There is no investigation going on, just some messing around with a camera, and studio comedy is pretty cheap no matter how you do it (that's why the cable channels had all those stand-ups on until they discovered reality TV - comedians come cheap). So the financial comparison is a bit apples and oranges.




But the big thing here is to ask where the Rocketboom numbers come from. We've seen that Chris Anderson is relentlessly optimistic in his view of internet technologies, and he lets that attitude get in the way of his objectivity here. Those first-week ads were something of a publicity stunt, bein [auctioned on eBay](http://adverlab.blogspot.com/2006/03/first-ad-on-rocketboom-goes-live.html) according the the [MIT Advertising Lab](http://adverlab.blogspot.com/2006/03/first-ad-on-rocketboom-goes-live.html). A [recent posting](http://adverlab.blogspot.com/2007/03/rocketboom-struggles-for-ad-dollars.html) by the same MIT Advertising Lab shows that the story is different now:

<blockquote>[Rocketboom](http://www.rocketboom.com/) is searching for a new way to put fuel in its tank. Advertising is not doing it. "It's frustrating that we haven't worked it out by now," said the daily video blog's founder, Andrew Baron. "Even though we have a relatively large audience, advertisers are just not happy to do 'small deals,' he explained in an interview. Baron says there are 200,000 downloads of Rocketboom shows, seven days a week. 'They say they want to blast their commercials to millions of people.' So, Rocketboom is again toying with the idea of charging for content. ([MarketWatch](http://www.marketwatch.com/news/story/internet-daily-rocketboom-may-charge/story.aspx?guid=%7BE853CAC4%2D78BE%2D443E%2D822E%2D4FDAFA1D33C7%7D))
> 
> 

> 
> Andrew Baron [last summer](http://www.dembot.com/009793.html): "Or maybe in the future we will decide to take a hit and not run ads some days because we could afford to."
> 
> 

> 
> Wonder what happened to the [Rocketboom being shown on TiVo](http://adverlab.blogspot.com/2006/06/tivo-shows-video-from-internet.html).
> 
> </blockquote>

The rule, which Mr. Anderson knows full well, is that you don't believe what people say about themselves, especially when they're trying to sell something. Let's take a closer look at some claims about the commercials and the viewership.




In [October 2006](http://blogs.marketwatch.com/barnako/2006/10/rocketrbooms_ad.html) "Baron said he's just done a deal worth $80,000 for a week of commercials in his videoblog. Claiming a daily audience of some 300,000 people, Baron could be getting more than a $55 CPM for his ads. You could get a discount, though. He'll sell you a week of spots for $60,000 - if he likes the commercial content."




Another commentator, Ze Frank, has [challenged](http://www.zefrank.com/zesblog/archives/2006/10/rocketbooming.html#more) the Rocketboom numbers, noting some inconsistency in the figures Baron has reported over time:

<blockquote>"Rocketboom is watched by 350,000 people a day."   
April 21, 2006: Rolling Stone magazine [(link)](http://www.rollingstone.com/news/story/9961735/the_rise_of_the_video_blog)
> 
> 

> 
> "[Rocketboom's] audience is up about 100,000 the last month, to about 400,000 a day."   
August 10, 2006: Dow Jones MarketWatch [(link)](http://www.marketwatch.com/News/Story/Story.aspx?guid=%7B98AB133E-4BB3-4ACB-BA24-1EC386E19F13%7D&dist=rss&siteid=mktw&rss=1)
> 
> 

> 
> Q: "Since Amanda left, have you seen any change in the audience?"  
A: "It's grown a bit."   
October 11, 2006: Future of PR Conference [(link)](http://www.valleywag.com/tech/rocketboom/unboomed-drew-baron-on-the-loss-of-his-bunny-206899.php)
> 
> 

> 
> "...over 300,000 downloads per day."  
October 24, 2006 blog post [(link)](http://www.dembot.com/011160.html)
> 
> </blockquote>

Businessweek's Heather Green has [chimed in too](http://www.businessweek.com/the_thread/blogspotting/archives/2006/11/the_continuing_1.html), suggesting that the October figure of "over 300,000 downloads" was an overestimate by about 50%. And how downloads translates into viewers is another issue entirely - does everyone watch to the end of the show, or do they drop it when a friend signs on to MSN? The picture - presented so breezily by Chris Anderson - is complex and obscure, and probably not nearly as dramatic as he makes it look.




The same problem appears elsewhere in Internet advertising-driven sites. There has been controversy over Second Life's claims, nicely summarized by [The Register's Shaun Rudolph](http://www.theregister.co.uk/2007/02/20/second_life_analysis/). There have been complaints about how difficult it is to cancel accounts created on a speculative whim at numerous sites - those account numbers translate into potential advertising money. And the effectiveness of web advertising itself is open to debate, with [some](http://www.clickfraudreport.com/) [serious](http://sfgate.com/cgi-bin/article.cgi?f=/c/a/2006/07/05/BUGL6JOQPA1.DTL) [estimates](http://www.businessweek.com/magazine/content/06_40/b4003001.htm?chan=tc&chan=technology_technology+index+page_best+of+the+magazine) of "click fraud" being around 15% of all clicks - which translates into about $1 billion over charged to advertisers.




So - don't trust self-reported numbers, especially if they support your thesis. Now on with the rest of the chapter.




A Tail for the Taking [194-196] sets out the reason why Anderson sees TV as vulnerable to alternatives - there's a lot of content, most of it not available to us for purely technological reasons, so "the ratio of produced content to available content is higher than in any other industry" [196]. It's a good point, and to his credit he goes on to point out one of the problems - it's not the technology, it's the issue of rights, which is a rat's nest. It's easy to think that the Internet is doing away with old-fashioned laws - and it does challenge many - but let's remember that Napster (the real Napster, that is) got beaten by the law. It's not impotent yet.




TV Outside the Box [196-197] suggests that new material on the Internet could more effectively challenge TV because the rights issues associated with old content are not so problematic. The section has a brief description of one such effort: Barrio305 - a web-only TV service for "urban Latin culture" [197] that each day "streams about 50,000 minutes of video to 5,000 unique users" [197] built on the Brightcove video distribution platform. It's an interesting story, but just a hint of one of many possible futures. Nothing definitive yet, that's for sure. And where do those figures come from? The book has no indication, in endnotes or anywhere else. In [a recent interview](http://www.mediaweek.com/mw/current/article_display.jsp?vnu_content_id=1003559551) the owners claim "about 10,000 viewers" daily. Who knows?




Shorter, Faster, Smaller [198-199] continues the argument in a small way. It points out that videos on the web are much smaller than TV shows" about 3 minutes instead of 30. Anderson thinks that the "arbitrary middle [of 30 minute shows] will not hold" [199]. So this is a nice setup for an argument. So now can we see some data...




Hollywood @ Home [199-200] No we can't. The chapter switches to "The other form of video that will be transformed in a Long Tail world is movies". We're done with TV apparently - like a 3 minute video the story was over before it got started. Is TV going to change? Sure. Will it go "Long Tail"? Who knows? 




One other point about this chapter. Given that Internet video is a different beast from TV - as he says here - maybe the comparison of TV to Internet video is not quite the right one when it comes to describing a change in culture. They both come at us through a screen, but if they are different things then the behaviour trend is not simply TV -> Internet video. There is also Books -> Internet video, and TV -> video games (a "Short Head" form of entertainment), and so on.




In looking at the way things change we have to forget the screen. It's natural to think of things that come through monitors as being kind of like things that come through TV screens, but there are other ways to think. MySpace and Facebook, for example, are more about conversation than media. And if we want to call these forms of activity "Long Tail" then let's remember that the phone companies could be called the ultimate Long Tail business - capturing big company phone bills but making most of their money off those millions of little individual conversations ("verbal production?") and making money off them because there are so many. There's nothing new about providing a service to many people and making money off them. Oil companies make a lot of money selling to hundreds of millions of individual car owners. 




As for movies, as Anderson points out, the way we watch them has expanded from movie theatres to TV, rented DVDs, and now downloaded movies onto hard drives, which will surely become more common in the next two or three years. With each expansion, the nature of the business changes. For Anderson, the complex development is a simple story: 

<blockquote>What the VCR and the video rental store hinted at was the rise of the age of infinite choice. Those stores increased the available selection of movies of any given Saturday night a hundredfold. Today, Netflix increases it a thousandfold. The Internet will increase it a gazillionfold.  
Every time a new technology enables more choice, whether it's the VCR or the Internet, consumers clamor for it. Choice is simply what we want and, apparently, what we've always wanted.
> 
> </blockquote>

gazillionfold??? 




This big conclusion is speculation balanced on top of some very frail data in this chapter. As for whether choice is really "what we want and, apparently, what we've always wanted", well someone could write [a book](http://www.tomslee.net) about that.


		
