---
author: Tom Slee
categories:
- blog archive
date: 2010-12-29 23:54:55
title: Frustrated philosophy student
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

A frustrated philosophy student of my acquaintance [asks](http://screwplato.wordpress.com/2010/12/29/are-philosophers-giving-up-on-reason/): "Are Philosophers Giving Up On Reason?" and reviews _What Philosophers Know_ by Gary Gutting. (Short version: not much).




Frustrated's conclusion:




<blockquote>

> 
> Gutting sets out to show “what philosophers know.” But all that he ends up “showing” is that philosophers have become too afraid of radical skepticism to exercise any skepticism at all, too afraid of having their own false beliefs exposed to expose the false beliefs of others, and too distrustful of their own reason to accept it when it leads them counter to their intuition.
> 
> 
</blockquote>




I don't know the book, but I do think philosophy must do a better job if it wants to hold on to students who care about the state of the world.


		
