---
author: Tom Slee
categories:
- blog archive
date: 2008-02-03 18:12:32
title: Don't be Pompous
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Let's get this straight - I don't have anything against Google any more than I do any other company. But there are times when it just goes out of its way to be a pretentious prat. Today is such a day. 




[Here](http://googleblog.blogspot.com/2008/02/yahoo-and-future-of-internet.html) is Google's unbelievable official response to the Microsoft attempt to buy Yahoo! How about this for a paragraph:

<blockquote>Could Microsoft now attempt to exert the same sort of inappropriate and
illegal influence over the Internet that it did with the PC? While the
Internet rewards competitive innovation, Microsoft has frequently
sought to establish proprietary monopolies -- and then leverage its
dominance into new, adjacent markets.
> 
> </blockquote>

David Drummond (Senior Vice President, Corporate Development and Chief Legal Officer) talks about two principles of the Internet: openness and innovation. 

<blockquote>We take Internet openness, choice and innovation seriously. They are the core of our culture.
> 
> </blockquote>

The beauty of this stance is that you can play the openness and innovation off against each other. Google's important software is just as proprietary, closed source, and hidden as that of Microsoft - in fact more so because M$ has shared source agreements with many companies while Google's core technologies are not shared with anyone. Google does not disclose information about things like water consumption at its server stations because it's a "competitive matter"; Google buys properties under other names because it can get a better deal. In cases like these where Google wants to be secretive they pull the innovation card and talk about innovation and the need to prosper in a competitive market.




When Google wants to promote technologies that are complementary to its own, it makes them open source (for example, in its sponsorship of Firefox browser development) and talks in idealistic terms about "the community". The overlap of interests between Google and its "communities" is partial at best, however, and such talk is cheeky, to say the least, coming from some of the world's richest people. And if making its advertising-driven wealth isn't leveraging its dominance in search into new, adjacent markets then I don't know what is.




In the end, Google and Microsoft are both profit-maximizing companies. No matter how much they couch their goals in suitably vague idealistic terms ("don't be evil" and the "freedom to innovate" respectively) they respond to the incentives faced by all such institutions. I just wish they'd be up front about it and not put out the kind of drivel that Google did today.


		
