---
author: Tom Slee
categories:
- blog archive
date: 2006-08-24 20:22:05
title: Andy Warhol / Supernova
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				


Went into Toronto today, and took a look at the [Andy Warhol exhibition](http://www.ago.net/info/ago_exhibitions/exhibition_specific.cfm?ID=3360) at the Art Gallery of Ontario, "guest curated" by David Cronenberg.





Talking to AK beforehand, she said that the show is as much about
Cronenberg as it is about Warhol, and I see what she means. The theme
is "Stars, Deaths and Disasters, 1962–1964", and it's
the Deaths part that is most obvious, and which Cronenberg has most to
say about on the commentary. Given that Warhol produced so much stuff
the focus on death, particularly grisly death (as in the electric chair
series and the Car Crash series) and disaster does seem to have more to
do with Cronenberg's interests than with Warhol's.   

  

I went not knowing much about Warhol beyond Campbell Soup, Velvet
Underground, and the odd profile of him I'd seen. I wasn't sure whether
I would be impressed or not - I don't have knee jerk reactions for or
against modern art. On the plus side, I like being challenged by art -
anything that makes you take a different look at a piece of the world
deserves praise, whether you agree with it or not - and on the negative
side, I don't have much time for sensationalism for the sake of it. But
how to tell the difference?  

  

I'm glad I saw the exhibition, and some of the things I really liked
(the Elvis image, for example) but overall I ended up with a lower
opinion of Warhol than when I went in.   

  

The films were the least impressive part of the exhibition. ("Blow
Job", "Sleep", "The Couch", "Screen Tests", and something about a
haircut) There is always something about yesterday's iconoclasts that
is a little pathetic, because the most outrageous things tend to look
tamer over time (well, except for Un Chien Andalou perhaps). Most
people go through a phase of self-discovery and exploration of our
place in the world, some with more gusto than others. But most of us
don't call it ground-breaking art and I didn't see much in the films
beyond a desire to shock and a desire to self promote. The expressions
on some of the models/participants/actors were just "hey, look at us,
aren't we something" and I thought - "no". The films seemed to catch
the worst of what the Warhol phenomenon is about: the circular
reasoning behind the fame and celebrity that he seemed to pursue so
relentlessly. Warhol is important in part because of the subjects of
his art (Jackie O, Liz Taylor, Marilyn Monroe); but in some cases the
subjects take on their importance only because it was Warhol who
pointed his camera at them: Warhol, in the end, is important only
because he is Warhol. The insights that the commentary gives into his
apparent shyness, his pursuit of celebrity, and his devotion to
celebrity are creepy. There is a touch of the Paris Hilton here -
famous for being famous. And if Warhol, you say, is deeper than Paris
Hilton, then he would disagree - one wall had his epigram on it: "If you want to know all about Andy Warhol, just look at the surface of
my paintings and films and me, and there I am. There's nothing behind
it." The two of them share something in common.





The silk-screen images were more interesting, and occasionally more
disturbing. The best -- the electric chair series (can't remember their
real name) and some of the Liz Taylor series, and the famous Elvis
Presley images, use the repetitive silk-screen technique to fine
effect, with the sequence of images fading away, or collapsing on
themselves, giving a poignant and melancholy air to the whole image.
Others, such as Race Riot and Car Crash, disturbed me for different
reasons. Where the commentary argued that Warhol forces us to look in a
different way at the images, I'm afraid I just saw them as a
self-promotional artist taking others' grief and distress and making
himself famous from it. His own distance from his subject did not have
the effect on me that it had on Cronenberg. He found the distancing
effect of silkscreen, the coldness of the technique, to demand a new
scrutiny of the image. I had no such reaction - to me Warhol's
recycling of these images as art had little impact.





I'm glad I went, if only to see the iconic Presley image at full size
and in the silk-screened flesh - starting tall and bold, and fading
away into a dim greyness over time, it's difficult not to see it as
prophecy. But I can't take Warhol seriously as a major artist. The fact
that his reputation has grown since his death is, I suspect, mainly a
result of his contemporaries bringing sentimental memories of the their
youth into the now top-of-the-field positions that they occupy.


		
