---
author: Tom Slee
categories:
- blog archive
date: 2014-05-04 14:07:00
tags:
- books
title: "The People's Platform: Who are No Logo's Children?"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				




Of all the books I've read about digital technology and its effects on our culture, Astra Taylor's _The People's Platform_ is closest to my own beliefs. I think it's a wonderful book, but what I really want is to see more people disagree with it.







The trouble is, everyone seems to like _The People's Platform_. In Canada, [The National Post](http://arts.nationalpost.com/2014/03/14/the-peoples-platform-by-astra-taylor-review/) likes it and [The Globe & Mail](http://www.theglobeandmail.com/arts/books-and-media/book-reviews/author-astra-taylor-pens-a-no-logo-for-the-digital-natives/article17501979/) calls it "a No Logo for digital natives". In the UK [The Guardian](http://www.theguardian.com/books/2014/apr/19/peoples-platform-review-astra-taylor-internet) says it is an "invaluable primer" for understanding our networked world, [The Telegraph](http://www.telegraph.co.uk/culture/books/bookreviews/10777956/The-Peoples-Platform-by-Astra-Taylor-review.html) gives it four stars out of five, and [The Financial Times](http://www.ft.com/intl/cms/s/2/68a48852-bb0e-11e3-b2b7-00144feabdc0.html#axzz2zFRATkiy) is positive. In the US I haven't seen reviews in the major papers except for [The Boston Globe](https://www.bostonglobe.com/arts/books/2014/04/22/book-review-the-people-platform-taking-back-power-and-culture-digital-age-astra-taylor/C7KdEkN6dUscCnHunwm7RK/story.html), which is persuaded by Taylor's arguments; but on the left, [Dissent](http://www.dissentmagazine.org/online_articles/web-3-0-imagining-a-peoples-platform) and [Tom Dispatch](http://www.tomdispatch.com/post/175829/) welcome it, while [Kirkus Reviews](https://www.kirkusreviews.com/book-reviews/astra-taylor/the-peoples-platform/) calls it "a cogent and genuine argument for the true democratization of online culture".

The thing is, the book is a challenge to those who see themselves as digital progressives, or part of a digital counterculture—the descendants of _No Logo_, perhaps, who would trace a disruptive, counter-cultural path from the anti-copyright campaigns of the 1990s through Free/Open Source Software to net neutrality campaigns, Creative Commons, Open Data, Pirate Parties, the Arab Spring, Occupy, and Anonymous.

Not that we need to lump these all together of course, but there is a digital-progressive belief that the design of the Internet gives it a unique potential among technological innovations to be democratizing and liberating—and that (despite disenchantment with the advertising giants) this potential has been validated by the ways in which people have used digital technologies to challenge existing power structures.

It's a "Sympathy for the Digital", if you like: a willingness to give digital disruptions the benefit of the political doubt—to overlook the [Wall Street connections](http://thebaffler.com/blog/2014/05/bitcoin_for_undergrads) of Bitcoin, or the ways in which open source institutions have aided the NSA's spying activities—and a readiness to indulge today's billionaires when they adopt the anti-corporate, counter-cultural language of the 1990s. It's that feeling that the Pierre Omidyars of the world are somehow on "our" side because they come from the technology world. It's the reason why the Electronic Frontier Foundation intervened on behalf of Airbnb against the State of New York. It's where left-leaning people meet libertarians.

Taylor's sympathy for the digital has run out. It ran out, perhaps, when the documentary she spent two years of her life making was loaded up onto download sites and her requests for a short grace period were rejected because "philosophy is free". The preciseness of our vocabulary tells us how we look at the world, and reducing cultural creativity to what Taylor calls "that flattening word, content" is a condemnation of the digital world's indifference to artistic work.

The way she sees today's digital landscape, "we are witnessing not a levelling of the cultural playing field, but a rearrangement… In the place of Hollywood moguls, for example, we now have Silicon Valley tycoons (or, more precisely, we have Hollywood moguls _and_ Silicon Valley tycoons". As we look at how the last 15 years have turned out, the big picture that Taylor paints is not one of egalitarian progress, but of a sort of Animal Network, in which the new rulers have taken on the manners and values of the old, while clinging to the rhetoric of rebellion and change to justify their actions.

She takes on a wide range of topics, including equality, openness, the challenges of sustaining creative labour, investigative reporting as a public good, the winner-take-all nature of Web 2.0 platforms, the value of limited copyright, the environmental impact of online culture, gender imbalance in the technology world, the implications of an advertising (and self-promotion) driven culture. She does so with a wide range of reading, and in an accessible style, in a voice that is intelligent and full of conviction. The book is not an academic book or a "big idea" book structured around a populist, easy-to-digest nugget. It's an essay, in the best sense of that word.

Her broad conclusion is that the digital world has not turned out the way that the enthusiasts and evangelists of the last two decades have claimed it would. In addition to predictable targets like Kevin Kelly, Jeff Jarvis, Don Tapscott and the more libertarian strands of Wired culture, Taylor takes on leading digital progressives such as Lawrence Lessig, Clay Shirky, Yochai Benkler, Steven Johnson, and Tim O'Reilly: people who would think of themselves as egalitarian. She places them, broadly, on the wrong side of current debates about the impact of new technologies on culture and society. The book suggests that it's time these digital progressives engaged in some serious questioning of their own viewpoints; that they acknowledge that we live in different times now, and that the ideas and arguments of 1994, or even 2004, have different implications in 2014. I don't know if Taylor would do this, but I'd extend her argument to people like Biella Coleman, whose "Coding Freedom" is a smart example of digital counter-culture thinking, and to the kind of thinking that comes out of the Berkman Center.

Taylor's book is provocative partly because of her own background. As an independent film maker and Occupy activist, she has a history of frustration with mainstream media; in her own words, she is "a prime candidate… for cheering on the revolution that is purportedly being ushered in by the Internet" (p2). We all cluster in camps of one kind or another, and for digital progressives it is easy to argue that a book like Robert Levine's /Free Ride: How Digital Parasites Are Destroying the Culture Business, and How the Culture Business Can Fight Back/ comes from a place of entrenched interest and reaction. It is more difficult to paint Taylor as a digital conservative: this is criticism from inside the tent.

This is why I'm so disappointed that there has been no serious defence of digital progressivism in response to _The People's Platform_. (Have I missed some? Please leave links if so.) The book deserves to spark a debate, but it takes two to tango, and the digital progressives seem to be sitting this dance out. (I would not expect the Kevin Kellys of the world to respond, but I had higher hopes of others).

Why the lack of retort? Could it be that Taylor does not have the profile to justify a response? That it is easier to ignore _The People's Platform_ and wait for it to go away? It certainly looks that way from here. Let's hope I'm proved wrong.

In the absence of a strong response, it's time to say that digital progressivism has no legitimate claim to the political or counter-cultural legacy of _No Logo_ and the movement that book embodied. Sure, part of that political legacy was the anti-copyright campaigns of the early 2000s. Sure, digital initiatives like Indymedia came out of that movement. But that movement was also a protest against branding, and against the McDonaldization of global culture and the American cultural imperialism that accompanied it. For those of us outside the US, the right of individual countries to set their own rules to sustain their cultural industries and their cultures were part of the struggle. If that's a struggle that runs counter to what some call the logic of the Internet, well so be it.






		
