---
author: Tom Slee
categories:
- blog archive
date: 2017-10-09 19:06:02
draft: false
title: 'Airbnb data collection: announcement'
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				I've been doing the Airbnb data collection thing for about four years now, off and on, with my first post being on [October 19, 2013](http://tomslee.net/2013/10/notes-on-airbnbs-new-york-business.html).

It's been interesting, rewarding, and useful for quite a few people, and I think it has helped to push the debate on Airbnb forward in some cases. But there is a time for every season and I think this effort has done what it can, and it's time to move on. I'll continue until the end of the year, and I'll complete any commitments I have made to individuals and groups, but as of the end of the year I will stop running regular data collections.

A few notes / reasons:



 	
  * I've already fallen behind on responding to requests, and I won't be taking more.

 	
  * My code is on github (https://github.com/tomslee/airbnb-data-collection) for anyone who wants to continue and the bulk of the data I have collected will remain at http://tomslee.net/airbnb-data-collection-get-the-data. It could be much better, but it's there.

 	
  * Others are doing a better job of making public data accessible (including the excellent Murray Cox at [Inside Airbnb](http://insideairbnb.com) obviously).

 	
  * People doing serious research tend to roll their own (it's not rocket science) or go to commercial outfits like AirDNA who collect more detail.

 	
  * Cities looking for a partner in managing short-term rentals may consider groups like Host Compliance https://hostcompliance.com.


Thanks for the feedback and contributions, and all the fascinating conversations I've had through this project. Onwards and upwards...		
