---
author: Tom Slee
categories:
- blog archive
date: 2012-05-01 12:46:15
title: Why the "Open Data Movement" is a Joke
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

Two recent announcements from Canada prompt my mood this morning:






  * [Canada Joins International Open Government Partnership](http://news.gc.ca/web/article-eng.do?nid=669609)


  * [Conservative Cuts put half of Statscan jobs at risk](http://www.theglobeandmail.com/news/politics/conservative-cuts-put-half-of-statscan-jobs-at-risk/article2418557/)




A government can simultaneously be the most secretive, controlling Canadian government in recent memory and be welcomed into the club of "open government". The announcements highlight a few problems with the "open data movement" ([Wikipedia page](http://en.wikipedia.org/wiki/Open_data)):




* It's not a movement, at least in any reasonable political or   cultural sense of the word, 


* It's doing nothing for transparency and accountability in   government, 


* It's co-opting the language of progressive change in pursuit of what   turns out to be a small-government-focused subsidy for industry. 






In short, the open data movement is a joke. Those who are on the political left who lend their support to it have some hard decisions to make.










### The Canadian Case: Open is an empty word







The Harper government's actions around "open government", and the lack of any significant consequences for those actions, show just how empty the word "open" has become. For readers outside the country, here is a selection:






  * Cancelling the compulsory long-form census ([link](http://www12.statcan.gc.ca/census-recensement/2011/ref/gazette-eng.cfm)), thereby   demolishing a source of reliable statistical data that guides   government decisions and debates over national priorities. "The   information previously collected by the long-form census   questionnaire will be collected as part of the new voluntary   National Household Survey (NHS)." The decision prompted Statscan   head Munir Sheikh to resign ([link](http://www.cbc.ca/news/canada/story/2010/07/21/statistics-canada-quits.html)). 


  * Firing Health Canada scientists who speak publicly on drug safety   issues ([link](http://www.thestar.com/news/canada/article/1036200--sad-day-for-whistleblowers-union-warns-as-board-rules-on-fired-scientists)). [Update: as "d" comments below, this was the Liberal government in 2004]


  * Muzzling Canada's public scientists in other departments, with one   example being Fisheries and Oceans scientist Kristi Miller   ([link](http://www.cbc.ca/news/canada/story/2012/03/23/f-federal-scientists.html)). More broadly, "Natural Resources Canada scientists have had   to get pre-approval from Minister Christian Paradis's office to   speak with journalists. They must also get ministerial approval for   everything they say to the news media." ([link](http://www.cbc.ca/news/technology/story/2010/09/29/federal-scientists-media-government.html)). 




It's got to the stage where the Canadian Association of Journalists recently awarded its "Code of Silence" award for Canada's most secretive government or publicly-funded agency to the entire federal government ([link](http://this.org/blog/2012/04/30/harper-government-wins-journalists-secrecy-award-who-cares/)).




While there has been opposition to these moves, I think it's fair to say that the "open data movement" has not been central to it. But never mind, Statistics Canada data is now available for free on the government's web site ([link](http://www.ccsd.ca/index.php?option=com_content&view=article&id=222%3Astatistics-canada-to-make-all-online-data-free&catid=44%3Anews&Itemid=172&lang=en)). There seems to be no link between the government's actions and the actions of this "movement", and basically that's because the Open Data Movement is more focused on formats, digitally-acessible data sets, free access to postal codes, and so on than it is focused on actual government transparency around issues that matter. It's a movement that has had no impact on government accountability.













### Who is the Open Data Movement?







Am I being unfair? Who, after all, is the Open Data Movement? Well it turns out there isn't one really, at least when it comes to "open data" in the sense of "open government data", which along with "open scientific data" is one of the two most common uses of the term.




"Open Data Movement" is a phrase dragged out by media-oriented personalities to cloak a private-sector initiative in the mantle of progressive politics. Along with other cyberculture terms ("hacktivism", "unconferences", "hackathons") the word "movement" suggests a countercultural grass-roots initiative for social change, but there isn't anything of the sort that I can see.




Take Tim O'Reilly, who has thrown the phrase around for some time (see [here](http://radar.oreilly.com/2010/12/2011-data.html) for an example from a couple of years ago). Like others who use the phrase, he sees no conflict between civic culture and corporate interests, so the Strata conferences and Open Government conferences he has run have been sponsored by major software, hardware, and computer services companies (including, I think, my employer, for whom I do not speak). [Strata 2012](http://strataconf.com/stratany2012), for example, is co-hosted by Cloudera, sponsored by EMC and MapR, and [many others](http://strataconf.com/stratany2012/public/content/sponsors).




Or take the "Code for America" initiative, which uses language that is explicitly about promoting an alternative vision of how government works ("it's about citizenship and how the internet is fundamentally reshaping the way government can work", It's "a Peace Corp for geeks") and which has many well-intentioned people involved. Yet when it comes to it, there's a lot more here about making uncontroversial data available (including for commercial use) than there is about anything like challenging government on actual accountability or transparency. So it's no surprise that the list of [donors](http://codeforamerica.org/donors/) includes major corporations like EMC (again), ESRI, Google, O'Reilly Media, and Microsoft.




It's not that there's necessarily anything wrong with Code for America, more that it's not a movement in any political or even cultural sense. Another member of the CfA donor list is the Omidyar Network, set up by the eBay billionaire Pierre Omidyar, and it reflects his view that private sector corporate profit-making activity and civic activity are not in tension, but complement each other.




As a result, the actual activities of this "movement" end up being to push for government subsidies of private-sector activity. It's "big society" all over again. This is the [TED worldview](http://thenewinquiry.com/essays/against-ted/), so it's no surprise that the recent Open Government Partnership wraps itself in noble goals such as fighting "corruption, closed doors, the consolidation of power" (see Hillary Rodham Clinton's [remarks](http://www.state.gov/secretary/rm/2012/04/188008.htm)) and basks in the reflected virtue of TED fellow Walid Al-Saqaf ([Open data vital for a new Yemen](http://www.guardian.co.uk/public-leaders-network/2012/apr/13/open-data-vital-for-yemen)) when the most likely outcomes are privatisation initiatives of the kind promoted by [Francis Maude](http://www.guardian.co.uk/public-leaders-network/2012/apr/19/frances-maude-open-government-partnership).













### Abandoning "Free for Commercial Use"







Progressives involved in open data work, of which there are many, could do something useful here. In order to prevent actions around government transparency being hijacked as a front for corporations to get at subsidised raw material, they could promote a "non-commercial use" license of the kind that is an option under some variants of Creative Commons content license.




Until now, groups and individuals with some credibility on the left have maintained constructive if arms-length relations with the corporate/civic almagam that is the Open Data Movement. It's time for them to draw a line, and not let their own often-admirable initiatives get used as a smokescreen for privatisation and small-government initiatives.




Are any doing so, or are there explicitly-progressive initiatives that are making a difference? I'd be interested to hear.













### More reading




Basically, this post follows on from [this](http://whimsley.typepad.com/whimsley/2010/11/what-is-wrong-with-government-20.html) and [this](http://whimsley.typepad.com/whimsley/2010/11/what-else-is-wrong-with-government-20.html), which I wrote a couple of years ago.

		
