---
author: Tom Slee
categories:
- blog archive
date: 2009-02-09 18:23:05
title: "Mr. Amazon's Bookshop: Mr. Amazon's Shelves"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[This is the eighth instalment of _Mr. Amazon's Bookshop_. A list of all instalments is [here](http://whimsley.typepad.com/whimsley/2008/12/mr-amazons-bookshop.html); the previous instalment is [here](http://whimsley.typepad.com/whimsley/2009/02/mr-amazons-bookshop-down-with-gatekeepers.html).]  


  


As the heat of July dried the horse droppings on the road into that agreeably dusty texture they gain in late summer, I received the final piece I needed to repair my differ. I immediately grabbed Edmund again and headed out to the stable.

  


"What's this all about Mr. Whimsley?" asked the idiot child.

  


"Never you mind Edmund. Just watch and learn. And pump those bellows, there's a good lad."

  


The halfwit pumped and soon I was ready to embark on my first serious venture.

  


I had the first few lists of books for what I now thought of as a bookshop grown from a single seed, that seed being Special Topics in Calamity Physics. I had already carried out two "visits" to the shop, first picking up a dozen books in succession, and using Mr. Amazon's recommendations to build shelves around each book, selecting one from the shelf each time as a starting point for a new shelf. Now I wanted to do this again and again, and I wanted to find out just how big the bookshop would grow, and how diverse it would be. This time I would use Mr. Amazon's sales rank to tell me about what kind of books Mr. Amazon is really recommending. Would Mr. Amazon lead me into the world of undiscovered books? Would he, I found myself wondering, recommend Kylie's The Adventures of Wazzock? Would "browsing" through his recommendations uncover the hidden gems in the mass of barely-read, midlist and overlooked books? I could hardly wait to find out.

  


"Right young Edmund, let's get ready for some serious work. You pump the bellows like mad, I'm going to give this engine a run like she's never had before!"

  


"Whoopee!!" yelled the knee-high dullard, and he pumped harder and harder. I flung the cat at the wall and it selected a visit-length of 5 books. I sent off the first request and it came back quick as a flash, I flung the cat, and repeated four more times. I scribbled the list in my notebook, this time together with the sales rank of each book:

Bridge of Sighs (1,132)

The Gathering (978)

On Chesil Beach (3451)

Out Stealing Horses (268)

Man Gone Down (62472)

  


I was exhausted, but a convenient thought came to my mind. Edmund had got the bellows working well enough that he only pumped them one minute in every three.

  


"Edmund! Can you write, young lad?"

  


"That I can Mr. Whimsley sire. I win prizes for my calligraphy."

  


I doubted the word of the stunted cretin, but thought he may be able to help me nevertheless. "I'll give you a chance then. Come here and write what I say." I handed him my pencil and notebook, and constructed the next visit:

Tree of Smoke (3583)

The Savage Detectives (1130)

The Gathering (978)

Bridge of Sighs (1132)

The Story of Edgar Sawtelle (17)

  


I had to admit his handwriting was exemplary, and quick as a flash too. Perhaps young Edmund was not as retarded as I had thought, despite his perpetually snot-dripping nose. We sent a query again and constructed another visit, then another and another. By the end of the morning my notebook was full with no less than a thousand visits. I was exhausted and young Edmund was sweating profusely.

  


I looked at Edmund's nebbish expression and, not for the first time, told myself I was really too kind hearted. Here was this child, destined by bloodline to be nothing but a mere gardener, and here was I giving him this once in a lifetime opportunity to take part in a numerological experiment of the highest order. "Whimsley, you sentimentalist", I told myself, "if you deprive the child of a severe and structured environment you're doing him no favours." Yet my soft heart won over. "Take a break, Edmund", I told him, "and as special reward, you don't have to weed the vegetable patch this afternoon, just the flower beds."

  


"Oh thank you sir."

  


"Just be ready tomorrow morning. We start bright and early at ten."

  


I'm such a soft touch. I spent the rest of the day in the conservatory with a well-deserved bottle of scotch, feeling enthused and energised for the first time in months.


		
