---
author: Tom Slee
categories:
- blog archive
date: 2009-01-16 12:01:45
title: "Mr. Amazon's Bookshop: What is a Book?"
---

::: {.callout-note}

This page has been migrated from an earlier version of this site. 
Links and images may be broken.

:::



				

[This is the fourth instalment of Mr. Amazon's Bookshop. A list of all instalments is [here](http://whimsley.typepad.com/whimsley/2008/12/mr-amazons-bookshop.html); the previous instalment is [here](http://whimsley.typepad.com/whimsley/2009/01/mr-amazons-bookshop-a-conversation-with-the-butler.html).]

The next day I woke early, Google's suggestion that Mr. Amazon's Bookshop was founded on an illusion still hammering in my head. I decided that this puzzle needed to be solved and, unlike so many ideas that come on the threshold of sleep, my notion from the previous evening still seemed like a filly with legs. After breakfasting on the usual kippers, tea, and toast with ginger marmalade, I dressed and rushed into the village. I ducked into Words Worth and scanned the advertisements in the _Literary Review_ until I found what I wanted: an announcement from Gallup Press promoting a new book entitled "_Strengths-Based Leadership_". It sounded like the most ridiculous form of business-speaking, self-help-inspired, positive-thinking twaddle, but the announcement brandished a ribbon-like slash across one corner proclaiming "Coming Soon!" with a date about two months hence - and that's all I needed.  
  
I rushed out of the door, strode down the street, and marched into Mr. Amazon's Bookshop. I walked straight up to his desk and stared him in the eye. "Right then Amazon", I said loudly, "I'd like a copy of _Strengths-Based Leadership_, pronto."  
  
"Certainly sir." He reached down behind his desk again and lifted up a book, "Here it is. Would you like to pre-order it?"  
  
"Aha!" I shouted, pointing at the supposed book. "I've got you! That's not a real book. It's not even published yet. And if that's not a real book, then you're not a real bookshop! You're just a, a.... glorified catalogue!"  
  
"Of course it's a book sir. You can look at the cover, you can order it, and although it may take a little longer to arrive than some other books, it will arrive. If it's not a book, then what could it be? Kippers and toast with ginger marmalade?"  
  
"If it were a book, then I could touch it." I grabbed at it across the desk, but Amazon was too quick for me and pulled it back. "See!" I cried, "it's a trick! I know it's a trick!"  
  
He was unflustered. "Sorry sir, you may not touch the books in our store, but feel free to read the back cover. Or I'll be happy to open it for you to look inside."  
  
I stammered.  
  
"Excuse me sir," he smiled patronizingly at me. "If I may make so bold, you seem to have a very old-fashioned idea of existence. What is a book anyway? Is it a physical lump of ink, paper and glue and card? Or is it the words, the ideas, the tale-well-told? When you buy a book, what is it you are purchasing? Printer's ink and cheap paper, or a connection with the fertile mind of an author?"  
  
"What you think of as a book", he carried on in a patronizing manner, "is simply a replica, a particular physical manifestation of a book. Do you think a mere copy of one manifestation is the original, the archetypal, book? Certainly not - the physical object you so covet is the essence of duplicity; claiming to be a book and yet, in reality, being nothing but a grubby knock-off, a derivative product that supplements the elemental text with what is usually a poorly-chosen font and badly-illustrated covers. The real thing - the authentic book - is in the ether."  
  
"Many would say that books live, not between the covers, but in the conception of their authors - theirs is the heart that beats, the insight that inspires. Even those postmodernists you are so keen on, those who would dismiss authorial intent - even they would claim that a book is the text itself, not its physical manifestation in font and paper. And not only is your precious book itself an illusion but so is your crude idea of some real bookshop from which it is sold. There is nothing, I understand, beyond the text. And I," (did his eyes glisten as he said those words?) "I have the text."  
  
Usually so reserved, I had never seen him display this kind of intensity before and it quite took me aback. I had nothing to say in response. Before I could gather my wits he leant forward: "Let me tell you something, for your ears only", he whispered, "the physical book you love so much is dead. What you see here, delivering books to you by post," (did he sneer at the word "post"?) "this is just the beginning. My shelves are infinite. A book, as you will see, is nothing but a drop of condensation in the Cloud. And I," (Did his teeth twinkle as he smiled?) "I have the Cloud."  
  
"Well then," I riposted bravely, gathering myself together. "If the grubby item you are sending me is not a real book, you won't mind if I don't pay you in this grubby money?" I waved two ten guinea coins under his nose and then put them ostentatiously back in my waistcoat pocket.  
  
"Absolutely not sir. A credit card suits us better."  
  
I spluttered, reduced to inarticulate mumbling, and was about to storm out, feeling that he had got the better of me again, when he spoke yet again.  
  
"May I ask, sir. Do you believe I am real?"  
  
"You? I don't know," I admitted, "I suspect if I reached over the desk you would withdraw yourself quick enough. So how can I know? Tell me then, are you corporeal, or an illusion?"  
  
"I am as real as you are, sir."  
  
"Well that's a relief. At least I know I'm the real thing", I chuckled.  
  
"But you", he continued, "if I may make so bold, are hardly authentic are you? Not very _original_? Your language is a pale imitation of _Sir Henry at Rawlinson End_ without the wit or the puns, your dress reminds me of Uncle Andrew from _A Magician's Nephew_, your stick-like knees are nothing but Mervyn Peake's Mr. Flay and I believe I detect a touch of Robert X. Cringely thrown in for good measure."  
  
"I don't need to be original. I'm real."  
  
"I see. How convenient. Please come again. I'm sure you will."  
  
As I stepped into the gloomy summer rain of Whimsley High Street my mind was whirling. At least, it would have been if I hadn't been busy swilling down some bad cognac to slow it down. Is Amazon a real bookshop? Is there such a thing as a real bookshop? Is Mr. Amazon real? Does any of this matter? I had no idea.


		
